Repository typst/packages, pull requests merged in 2023-10, with the labels that each got.

#174 outrageous:0.1.0
  packages/preview/outrageous/0.1.0/LICENSE
  packages/preview/outrageous/0.1.0/README.md
  packages/preview/outrageous/0.1.0/example-custom.png
  packages/preview/outrageous/0.1.0/example-default.png
  packages/preview/outrageous/0.1.0/examples/basic.typ
  packages/preview/outrageous/0.1.0/examples/rush.pdf
  packages/preview/outrageous/0.1.0/examples/rush.typ
  packages/preview/outrageous/0.1.0/outrageous.typ
  packages/preview/outrageous/0.1.0/typst.toml
Labels: new

#175 i-figured:0.1.0
  packages/preview/i-figured/0.1.0/LICENSE
  packages/preview/i-figured/0.1.0/README.md
  packages/preview/i-figured/0.1.0/examples/basic.png
  packages/preview/i-figured/0.1.0/examples/basic.typ
  packages/preview/i-figured/0.1.0/examples/level-two.png
  packages/preview/i-figured/0.1.0/examples/level-two.typ
  packages/preview/i-figured/0.1.0/i-figured.typ
  packages/preview/i-figured/0.1.0/typst.toml
Labels: new

#179 ascii-ipa:1.1.0
  packages/preview/ascii-ipa/1.1.0/CHANGELOG.md
  packages/preview/ascii-ipa/1.1.0/LICENSE
  packages/preview/ascii-ipa/1.1.0/README.md
  packages/preview/ascii-ipa/1.1.0/ascii-ipa.typ
  packages/preview/ascii-ipa/1.1.0/src/lib.typ
  packages/preview/ascii-ipa/1.1.0/src/translations/branner.typ
  packages/preview/ascii-ipa/1.1.0/src/translations/praat.typ
  packages/preview/ascii-ipa/1.1.0/src/translations/sil.typ
  packages/preview/ascii-ipa/1.1.0/src/translations/xsampa.typ
  packages/preview/ascii-ipa/1.1.0/test/test.typ
  packages/preview/ascii-ipa/1.1.0/typst.toml
Labels: update

#180 Minor fixes to chordx docs
  packages/preview/chordx/0.2.0/CHANGELOG.md
  packages/preview/chordx/0.2.0/README.md
Labels: minor-fix

#178 unify:0.4.2
  packages/preview/unify/0.4.2/LICENSE
  packages/preview/unify/0.4.2/README.md
  packages/preview/unify/0.4.2/examples/overview.jpg
  packages/preview/unify/0.4.2/lib.typ
  packages/preview/unify/0.4.2/postfixes.csv
  packages/preview/unify/0.4.2/prefixes.csv
  packages/preview/unify/0.4.2/typst.toml
  packages/preview/unify/0.4.2/units.csv
Labels: update

#177 truthfy:0.1.0
  packages/preview/truthfy/0.1.0/LICENSE
  packages/preview/truthfy/0.1.0/README.md
  packages/preview/truthfy/0.1.0/example.pdf
  packages/preview/truthfy/0.1.0/example.typ
  packages/preview/truthfy/0.1.0/main.typ
  packages/preview/truthfy/0.1.0/typst.toml
Labels: new

#184 quick-maths:0.1.0
  packages/preview/quick-maths/0.1.0/README.md
  packages/preview/quick-maths/0.1.0/assets/example.svg
  packages/preview/quick-maths/0.1.0/assets/example.typ
  packages/preview/quick-maths/0.1.0/src/lib.typ
  packages/preview/quick-maths/0.1.0/src/quick-maths.typ
  packages/preview/quick-maths/0.1.0/typst.toml
Labels: new

#192 tablex:0.0.6
  packages/preview/tablex/0.0.6/LICENSE
  packages/preview/tablex/0.0.6/README.md
  packages/preview/tablex/0.0.6/tablex.typ
  packages/preview/tablex/0.0.6/typst.toml
Labels: update

#201 typearea:0.1.0
  packages/preview/typearea/0.1.0/LICENSE
  packages/preview/typearea/0.1.0/README.md
  packages/preview/typearea/0.1.0/typearea.typ
  packages/preview/typearea/0.1.0/typst.toml
Labels: new

#205 glossarium:0.2.3
  packages/preview/glossarium/0.2.3/.gitignore
  packages/preview/glossarium/0.2.3/LICENCE
  packages/preview/glossarium/0.2.3/README.md
  packages/preview/glossarium/0.2.3/example/example.pdf
  packages/preview/glossarium/0.2.3/example/example.png
  packages/preview/glossarium/0.2.3/example/example.typ
  packages/preview/glossarium/0.2.3/glossarium.typ
  packages/preview/glossarium/0.2.3/makefile
  packages/preview/glossarium/0.2.3/tbump.toml
  packages/preview/glossarium/0.2.3/typst.toml
Labels: update

#206 chem-par:0.0.1
  packages/preview/chem-par/0.0.1/CHANGELOG.md
  packages/preview/chem-par/0.0.1/LICENSE
  packages/preview/chem-par/0.0.1/README.md
  packages/preview/chem-par/0.0.1/src/chem-par.typ
  packages/preview/chem-par/0.0.1/src/constants.typ
  packages/preview/chem-par/0.0.1/src/lib.typ
  packages/preview/chem-par/0.0.1/src/rules.typ
  packages/preview/chem-par/0.0.1/src/rules/deuterated.typ
  packages/preview/chem-par/0.0.1/src/rules/dropcaps.typ
  packages/preview/chem-par/0.0.1/src/rules/enantiomers.typ
  packages/preview/chem-par/0.0.1/src/rules/formulae.typ
  packages/preview/chem-par/0.0.1/src/rules/greek.typ
  packages/preview/chem-par/0.0.1/src/rules/isomers.typ
  packages/preview/chem-par/0.0.1/src/stateful.typ
  packages/preview/chem-par/0.0.1/typst.toml
Labels: new
