Repository typst/packages, pull requests merged in 2023-08, with the labels that each got.

#70 chordx:0.1.0
  packages/preview/chordx/0.1.0/README.md
Labels: minor-fix

#52 minitoc:0.1.0
  packages/preview/minitoc/0.1.0/LICENSE
  packages/preview/minitoc/0.1.0/README.md
  packages/preview/minitoc/0.1.0/lib.typ
  packages/preview/minitoc/0.1.0/typst.toml
Labels: new, name-approved

#60 algorithmic:0.1.0
  packages/preview/algorithmic/0.1.0/LICENSES/MIT.txt
  packages/preview/algorithmic/0.1.0/README.md
  packages/preview/algorithmic/0.1.0/algorithmic-demo.pdf
  packages/preview/algorithmic/0.1.0/algorithmic-demo.pdf.license
  packages/preview/algorithmic/0.1.0/algorithmic-demo.typ
  packages/preview/algorithmic/0.1.0/algorithmic.typ
  packages/preview/algorithmic/0.1.0/docs/assets/demo-rendered.png
  packages/preview/algorithmic/0.1.0/docs/assets/demo-rendered.png.license
  packages/preview/algorithmic/0.1.0/test.pdf
  packages/preview/algorithmic/0.1.0/test.typ
  packages/preview/algorithmic/0.1.0/typst.toml
Labels: new, name-approved

#95 chic-hdr:0.2.0
  packages/preview/chic-hdr/0.2.0/Chic-header's Manual.pdf
  packages/preview/chic-hdr/0.2.0/LICENSE
  packages/preview/chic-hdr/0.2.0/README.md
  packages/preview/chic-hdr/0.2.0/assets/example-1.png
  packages/preview/chic-hdr/0.2.0/assets/example-2.png
  packages/preview/chic-hdr/0.2.0/assets/usage.png
  packages/preview/chic-hdr/0.2.0/chic-hdr.typ
  packages/preview/chic-hdr/0.2.0/internal.typ
  packages/preview/chic-hdr/0.2.0/typst.toml
Labels: update

#83 statastic:0.1.0
  packages/preview/statastic-0.1.0/LICENSE
  packages/preview/statastic-0.1.0/README.md
  packages/preview/statastic-0.1.0/lib.typ
  packages/preview/statastic-0.1.0/typst.toml
Labels: new

#88 acrostiche:0.3.0
  packages/preview/acrostiche/0.3.0/LICENSE
  packages/preview/acrostiche/0.3.0/README.md
  packages/preview/acrostiche/0.3.0/acrostiche.typ
  packages/preview/acrostiche/0.3.0/typst.toml
Labels: update
