Repository typst/packages, pull requests merged in 2023-09, with the labels that each got.

#87 bytefield:0.0.1
  packages/preview/bytefield/0.0.1/LICENSE
  packages/preview/bytefield/0.0.1/README.md
  packages/preview/bytefield/0.0.1/bytefield.typ
  packages/preview/bytefield/0.0.1/typst.toml
Labels: new

#98 finite:0.1.0
  packages/preview/finite/0.1.0/LICENSE
  packages/preview/finite/0.1.0/README.md
  packages/preview/finite/0.1.0/assets/example.png
  packages/preview/finite/0.1.0/cmd.typ
  packages/preview/finite/0.1.0/draw.typ
  packages/preview/finite/0.1.0/finite.typ
  packages/preview/finite/0.1.0/layout.typ
  packages/preview/finite/0.1.0/manual.pdf
  packages/preview/finite/0.1.0/manual.typ
  packages/preview/finite/0.1.0/tbump.toml
  packages/preview/finite/0.1.0/typst.toml
  packages/preview/finite/0.1.0/util.typ
Labels: new

#99 prooftrees:0.1.0
  packages/preview/prooftrees/0.1.0/LICENSE
  packages/preview/prooftrees/0.1.0/README.md
  packages/preview/prooftrees/0.1.0/examples/prooftree_test.typ
  packages/preview/prooftrees/0.1.0/src/internal.typ
  packages/preview/prooftrees/0.1.0/src/prooftrees.typ
  packages/preview/prooftrees/0.1.0/src/utils.typ
  packages/preview/prooftrees/0.1.0/typst.toml
Labels: new

#100 glossarium:0.2.1
  packages/preview/glossarium/0.2.1/.gitignore
  packages/preview/glossarium/0.2.1/LICENCE
  packages/preview/glossarium/0.2.1/README.md
  packages/preview/glossarium/0.2.1/example/example.pdf
  packages/preview/glossarium/0.2.1/example/example.png
  packages/preview/glossarium/0.2.1/example/example.typ
  packages/preview/glossarium/0.2.1/glossarium.typ
  packages/preview/glossarium/0.2.1/typst.toml
Labels: update

#102 unify:0.4.1
  packages/preview/unify/0.4.1/LICENSE
  packages/preview/unify/0.4.1/README.md
  packages/preview/unify/0.4.1/examples/overview.jpg
  packages/preview/unify/0.4.1/lib.typ
  packages/preview/unify/0.4.1/postfixes.csv
  packages/preview/unify/0.4.1/prefixes.csv
  packages/preview/unify/0.4.1/typst.toml
  packages/preview/unify/0.4.1/units.csv
Labels: update

#103 polylux:0.3.1
  packages/preview/polylux/0.3.1/LICENSE
  packages/preview/polylux/0.3.1/README.md
  packages/preview/polylux/0.3.1/logic.typ
  packages/preview/polylux/0.3.1/polylux.typ
  packages/preview/polylux/0.3.1/themes/bipartite.typ
  packages/preview/polylux/0.3.1/themes/clean.typ
  packages/preview/polylux/0.3.1/themes/metropolis.typ
  packages/preview/polylux/0.3.1/themes/simple.typ
  packages/preview/polylux/0.3.1/themes/themes.typ
  packages/preview/polylux/0.3.1/themes/university.typ
  packages/preview/polylux/0.3.1/typst.toml
  packages/preview/polylux/0.3.1/utils/pdfpc.typ
  packages/preview/polylux/0.3.1/utils/utils.typ
Labels: update

#104 chordx:0.2.0
  packages/preview/chordx/0.2.0/CHANGELOG.md
  packages/preview/chordx/0.2.0/LICENSE
  packages/preview/chordx/0.2.0/README.md
  packages/preview/chordx/0.2.0/lib.typ
  packages/preview/chordx/0.2.0/src/chart.typ
  packages/preview/chordx/0.2.0/src/piano.typ
  packages/preview/chordx/0.2.0/src/single.typ
  packages/preview/chordx/0.2.0/src/utils.typ
  packages/preview/chordx/0.2.0/typst.toml
Labels: update

#105 algo:0.3.2
  packages/preview/algo/0.3.2/LICENSE
  packages/preview/algo/0.3.2/README.md
  packages/preview/algo/0.3.2/algo.typ
  packages/preview/algo/0.3.2/typst.toml
Labels: update

#106 t4t:0.3.1
  packages/preview/t4t/0.3.1/LICENSE
  packages/preview/t4t/0.3.1/README.md
  packages/preview/t4t/0.3.1/alias.typ
  packages/preview/t4t/0.3.1/assert.typ
  packages/preview/t4t/0.3.1/def.typ
  packages/preview/t4t/0.3.1/get.typ
  packages/preview/t4t/0.3.1/is.typ
  packages/preview/t4t/0.3.1/math.typ
  packages/preview/t4t/0.3.1/t4t-manual.pdf
  packages/preview/t4t/0.3.1/t4t-manual.typ
  packages/preview/t4t/0.3.1/tbump.toml
  packages/preview/t4t/0.3.1/tools4typst.typ
  packages/preview/t4t/0.3.1/typst.toml
Labels: update

#108 drafting:0.1.0
  packages/preview/drafting/0.1.0/LICENSE
  packages/preview/drafting/0.1.0/README.md
  packages/preview/drafting/0.1.0/drafting.typ
  packages/preview/drafting/0.1.0/typst.toml
Labels: new

#118 ansi-render:0.3.0
  packages/preview/ansi-render/0.3.0/CHANGELOG.md
  packages/preview/ansi-render/0.3.0/LICENSE
  packages/preview/ansi-render/0.3.0/README.md
  packages/preview/ansi-render/0.3.0/ansi-render.typ
  packages/preview/ansi-render/0.3.0/typst.toml
Labels: update

#119 cetz:0.1.1
  packages/preview/cetz/0.1.1/LICENSE
  packages/preview/cetz/0.1.1/README.md
  packages/preview/cetz/0.1.1/gallery/3d-chart.png
  packages/preview/cetz/0.1.1/gallery/3d-chart.typ
  packages/preview/cetz/0.1.1/gallery/barchart.png
  packages/preview/cetz/0.1.1/gallery/barchart.typ
  packages/preview/cetz/0.1.1/gallery/karls-picture.png
  packages/preview/cetz/0.1.1/gallery/karls-picture.typ
  packages/preview/cetz/0.1.1/gallery/pie-chart.png
  packages/preview/cetz/0.1.1/gallery/pie-chart.typ
  packages/preview/cetz/0.1.1/gallery/plot.png
  packages/preview/cetz/0.1.1/gallery/plot.typ
  packages/preview/cetz/0.1.1/gallery/tree.png
  packages/preview/cetz/0.1.1/gallery/tree.typ
  packages/preview/cetz/0.1.1/manual.pdf
  packages/preview/cetz/0.1.1/manual.typ
  packages/preview/cetz/0.1.1/src/bezier.typ
  packages/preview/cetz/0.1.1/src/canvas.typ
  packages/preview/cetz/0.1.1/src/cmd.typ
  packages/preview/cetz/0.1.1/src/coordinate.typ
  packages/preview/cetz/0.1.1/src/draw.typ
  packages/preview/cetz/0.1.1/src/intersection.typ
  packages/preview/cetz/0.1.1/src/lib.typ
  packages/preview/cetz/0.1.1/src/lib/angle.typ
  packages/preview/cetz/0.1.1/src/lib/axes.typ
  packages/preview/cetz/0.1.1/src/lib/chart.typ
  packages/preview/cetz/0.1.1/src/lib/palette.typ
  packages/preview/cetz/0.1.1/src/lib/plot.typ
  packages/preview/cetz/0.1.1/src/matrix.typ
  packages/preview/cetz/0.1.1/src/path-util.typ
  packages/preview/cetz/0.1.1/src/styles.typ
  packages/preview/cetz/0.1.1/src/tree.typ
  packages/preview/cetz/0.1.1/src/util.typ
  packages/preview/cetz/0.1.1/src/vector.typ
  packages/preview/cetz/0.1.1/typst.toml
Labels: update

#121 chic-hdr:0.3.0
  packages/preview/chic-hdr/0.3.0/Chic-header's Manual.pdf
  packages/preview/chic-hdr/0.3.0/LICENSE
  packages/preview/chic-hdr/0.3.0/README.md
  packages/preview/chic-hdr/0.3.0/assets/example-1.png
  packages/preview/chic-hdr/0.3.0/assets/example-2.png
  packages/preview/chic-hdr/0.3.0/assets/usage.png
  packages/preview/chic-hdr/0.3.0/chic-hdr.typ
  packages/preview/chic-hdr/0.3.0/internal.typ
  packages/preview/chic-hdr/0.3.0/typst.toml
Labels: update

#123 drafting:0.1.1
  packages/preview/drafting/0.1.1/LICENSE
  packages/preview/drafting/0.1.1/README.md
  packages/preview/drafting/0.1.1/drafting.typ
  packages/preview/drafting/0.1.1/typst.toml
Labels: update

#122 babble-bubbles:0.1.0
  packages/preview/babble-bubbles/0.1.0/LICENSE
  packages/preview/babble-bubbles/0.1.0/README.md
  packages/preview/babble-bubbles/0.1.0/examples/callouts.png
  packages/preview/babble-bubbles/0.1.0/lib.typ
  packages/preview/babble-bubbles/0.1.0/typst.toml
Labels: new, name-rejected

#120 gentle-clues:0.1.0
  packages/preview/gentle-clues/0.1.0/LICENSE
  packages/preview/gentle-clues/0.1.0/README.md
  packages/preview/gentle-clues/0.1.0/admonish.typ
  packages/preview/gentle-clues/0.1.0/assets/abstract.svg
  packages/preview/gentle-clues/0.1.0/assets/bell.svg
  packages/preview/gentle-clues/0.1.0/assets/bookmark.svg
  packages/preview/gentle-clues/0.1.0/assets/checkbox.svg
  packages/preview/gentle-clues/0.1.0/assets/crossmark.svg
  packages/preview/gentle-clues/0.1.0/assets/danger.svg
  packages/preview/gentle-clues/0.1.0/assets/excl.svg
  packages/preview/gentle-clues/0.1.0/assets/flag.svg
  packages/preview/gentle-clues/0.1.0/assets/info.svg
  packages/preview/gentle-clues/0.1.0/assets/lightbulb.svg
  packages/preview/gentle-clues/0.1.0/assets/questionmark.svg
  packages/preview/gentle-clues/0.1.0/assets/quote.svg
  packages/preview/gentle-clues/0.1.0/assets/task.svg
  packages/preview/gentle-clues/0.1.0/assets/tip.svg
  packages/preview/gentle-clues/0.1.0/assets/warning.svg
  packages/preview/gentle-clues/0.1.0/typst.toml
Labels: new

#78 nth:0.1.0
  packages/preview/nth/0.1.0/LICENSE
  packages/preview/nth/0.1.0/README.md
  packages/preview/nth/0.1.0/nth.typ
  packages/preview/nth/0.1.0/typst.toml
Labels: new

#107 rose-pine:0.1.0
  packages/preview/rose-pine/0.1.0/.editorconfig
  packages/preview/rose-pine/0.1.0/LICENSE
  packages/preview/rose-pine/0.1.0/README.md
  packages/preview/rose-pine/0.1.0/example.pdf
  packages/preview/rose-pine/0.1.0/example.typ
  packages/preview/rose-pine/0.1.0/lib.typ
  packages/preview/rose-pine/0.1.0/src/apply.typ
  packages/preview/rose-pine/0.1.0/src/template.typ
  packages/preview/rose-pine/0.1.0/src/themes/rose-pine-dawn.typ
  packages/preview/rose-pine/0.1.0/src/themes/rose-pine-moon.typ
  packages/preview/rose-pine/0.1.0/src/themes/rose-pine.typ
  packages/preview/rose-pine/0.1.0/typst.toml
Labels: new

#138 conchord:0.1.1
  packages/preview/conchord/0.1.1/LICENSE
  packages/preview/conchord/0.1.1/README.md
  packages/preview/conchord/0.1.1/examples/compare.png
  packages/preview/conchord/0.1.1/examples/compare.typ
  packages/preview/conchord/0.1.1/examples/crazy.png
  packages/preview/conchord/0.1.1/examples/crazy.typ
  packages/preview/conchord/0.1.1/examples/simple.png
  packages/preview/conchord/0.1.1/examples/simple.typ
  packages/preview/conchord/0.1.1/examples/tabs.png
  packages/preview/conchord/0.1.1/examples/tabs.typ
  packages/preview/conchord/0.1.1/examples/zombie.png
  packages/preview/conchord/0.1.1/examples/zombie.typ
  packages/preview/conchord/0.1.1/lib.typ
  packages/preview/conchord/0.1.1/tabs.typ
  packages/preview/conchord/0.1.1/typst.toml
Labels: update

#140 Fix typo in nth/typst.toml
  packages/preview/nth/0.1.0/typst.toml
Labels: minor-fix

#149 fixed typo in ansi-render/readme
  packages/preview/ansi-render/0.4.1/README.md
Labels: minor-fix

#151 codetastic:0.2.2
  packages/preview/codetastic/0.2.2/LICENSE
  packages/preview/codetastic/0.2.2/README.md
  packages/preview/codetastic/0.2.2/assets/example.png
  packages/preview/codetastic/0.2.2/bitfield.typ
  packages/preview/codetastic/0.2.2/bits.typ
  packages/preview/codetastic/0.2.2/checksum.typ
  packages/preview/codetastic/0.2.2/codetastic.typ
  packages/preview/codetastic/0.2.2/ecc.typ
  packages/preview/codetastic/0.2.2/manual.pdf
  packages/preview/codetastic/0.2.2/manual.typ
  packages/preview/codetastic/0.2.2/qrluts.typ
  packages/preview/codetastic/0.2.2/qrutil.typ
  packages/preview/codetastic/0.2.2/tbump.toml
  packages/preview/codetastic/0.2.2/typst.toml
  packages/preview/codetastic/0.2.2/util.typ
Labels: update

#161 anti-matter:0.0.1
  packages/preview/anti-matter/0.0.1/LICENSE
  packages/preview/anti-matter/0.0.1/README.md
  packages/preview/anti-matter/0.0.1/example.png
  packages/preview/anti-matter/0.0.1/src/lib.typ
  packages/preview/anti-matter/0.0.1/typst.toml
Labels: new
