Repository typst/packages, pull requests merged in 2023-12, with the labels that each got.

#274 wavy:0.1.1
  packages/preview/wavy/0.1.1/LICENSE
  packages/preview/wavy/0.1.1/NOTICE
  packages/preview/wavy/0.1.1/README.md
  packages/preview/wavy/0.1.1/lib.typ
  packages/preview/wavy/0.1.1/typst.toml
  packages/preview/wavy/0.1.1/wavy.js
  packages/preview/wavy/0.1.1/wavy.svg
  packages/preview/wavy/0.1.1/wavy.typ
Labels: update

#276 lemmify:0.1.5
  packages/preview/lemmify/0.1.5/LICENSE
  packages/preview/lemmify/0.1.5/README.md
  packages/preview/lemmify/0.1.5/src/lib.typ
  packages/preview/lemmify/0.1.5/src/styles.typ
  packages/preview/lemmify/0.1.5/src/translations.typ
  packages/preview/lemmify/0.1.5/src/util.typ
  packages/preview/lemmify/0.1.5/typst.toml
Labels: update

#218 socialhub-fa:1.0.0
  packages/preview/socialhub-fa/1.0.0/LICENSE
  packages/preview/socialhub-fa/1.0.0/README.md
  packages/preview/socialhub-fa/1.0.0/examples/examples.pdf
  packages/preview/socialhub-fa/1.0.0/examples/examples.typ
  packages/preview/socialhub-fa/1.0.0/examples/minimal_example.pdf
  packages/preview/socialhub-fa/1.0.0/examples/minimal_example.typ
  packages/preview/socialhub-fa/1.0.0/socialhub-fa.typ
  packages/preview/socialhub-fa/1.0.0/typst.toml
Labels: new

#271 Add missing # to README of babble-bubbles
  packages/preview/babble-bubbles/0.1.0/README.md
Labels: minor-fix

#269 curryst:0.1.0
  packages/preview/curryst/0.1.0/LICENSE
  packages/preview/curryst/0.1.0/README.md
  packages/preview/curryst/0.1.0/curryst.typ
  packages/preview/curryst/0.1.0/examples/basic_example.png
  packages/preview/curryst/0.1.0/examples/example.typ
  packages/preview/curryst/0.1.0/examples/wikipedia_example.png
  packages/preview/curryst/0.1.0/typst.toml
Labels: new

#282 ansi-render:0.6.0
  packages/preview/ansi-render/0.6.0/CHANGELOG.md
  packages/preview/ansi-render/0.6.0/LICENSE
  packages/preview/ansi-render/0.6.0/README.md
  packages/preview/ansi-render/0.6.0/ansi-render.typ
  packages/preview/ansi-render/0.6.0/typst.toml
Labels: update

#288 Fix link to Amazon in `cartao` README.md
  packages/preview/cartao/0.1.0/README.md
Labels: minor-fix

#290 droplet:0.1.0
  packages/preview/droplet/0.1.0/LICENSE
  packages/preview/droplet/0.1.0/README.md
  packages/preview/droplet/0.1.0/assets/example-transform.svg
  packages/preview/droplet/0.1.0/assets/example-transform.typ
  packages/preview/droplet/0.1.0/assets/example.svg
  packages/preview/droplet/0.1.0/assets/example.typ
  packages/preview/droplet/0.1.0/src/droplet.typ
  packages/preview/droplet/0.1.0/src/lib.typ
  packages/preview/droplet/0.1.0/typst.toml
Labels: new

#291 i-figured:0.2.3
  packages/preview/i-figured/0.2.3/LICENSE
  packages/preview/i-figured/0.2.3/README.md
  packages/preview/i-figured/0.2.3/examples/basic.png
  packages/preview/i-figured/0.2.3/examples/basic.typ
  packages/preview/i-figured/0.2.3/examples/level-two.png
  packages/preview/i-figured/0.2.3/examples/level-two.typ
  packages/preview/i-figured/0.2.3/i-figured.typ
  packages/preview/i-figured/0.2.3/typst.toml
Labels: update

#292 drafting:0.1.2
  packages/preview/drafting/0.1.2/LICENSE
  packages/preview/drafting/0.1.2/README.md
  packages/preview/drafting/0.1.2/drafting.typ
  packages/preview/drafting/0.1.2/typst.toml
Labels: update

#283 tada:0.1.0
  packages/preview/tada/0.1.0/LICENSE
  packages/preview/tada/0.1.0/README.md
  packages/preview/tada/0.1.0/lib.typ
  packages/preview/tada/0.1.0/manual.pdf
  packages/preview/tada/0.1.0/src/display.typ
  packages/preview/tada/0.1.0/src/helpers.typ
  packages/preview/tada/0.1.0/src/ops.typ
  packages/preview/tada/0.1.0/src/tabledata.typ
  packages/preview/tada/0.1.0/typst.toml
Labels: new

#299 tablex:0.0.7
  packages/preview/tablex/0.0.7/LICENSE
  packages/preview/tablex/0.0.7/README.md
  packages/preview/tablex/0.0.7/tablex.typ
  packages/preview/tablex/0.0.7/typst.toml
Labels: update

#301 nth:1.0.0
  packages/preview/nth/1.0.0/CHANGELOG.md
  packages/preview/nth/1.0.0/LICENSE
  packages/preview/nth/1.0.0/README.md
  packages/preview/nth/1.0.0/nth.typ
  packages/preview/nth/1.0.0/typst.toml
  packages/preview/nth/1.0.0/typstfmt.toml
Labels: update

#304 physica:0.9.1
  packages/preview/physica/0.9.1/LICENSE.txt
  packages/preview/physica/0.9.1/README.md
  packages/preview/physica/0.9.1/physica.typ
  packages/preview/physica/0.9.1/typst.toml
Labels: update

#307 mitex:0.1.0
  packages/preview/mitex/0.1.0/LICENSE
  packages/preview/mitex/0.1.0/README.md
  packages/preview/mitex/0.1.0/examples/bench.typ
  packages/preview/mitex/0.1.0/examples/example.png
  packages/preview/mitex/0.1.0/examples/example.typ
  packages/preview/mitex/0.1.0/lib.typ
  packages/preview/mitex/0.1.0/mitex.typ
  packages/preview/mitex/0.1.0/mitex.wasm
  packages/preview/mitex/0.1.0/specs/README.md
  packages/preview/mitex/0.1.0/specs/latex/standard.typ
  packages/preview/mitex/0.1.0/specs/mod.typ
  packages/preview/mitex/0.1.0/specs/prelude.typ
  packages/preview/mitex/0.1.0/typst.toml
Labels: new

#302 chic-hdr:0.4.0
  packages/preview/chic-hdr/0.4.0/Chic-header's Manual.pdf
  packages/preview/chic-hdr/0.4.0/LICENSE
  packages/preview/chic-hdr/0.4.0/README.md
  packages/preview/chic-hdr/0.4.0/assets/example-1.png
  packages/preview/chic-hdr/0.4.0/assets/example-2.png
  packages/preview/chic-hdr/0.4.0/assets/usage.png
  packages/preview/chic-hdr/0.4.0/chic-hdr.typ
  packages/preview/chic-hdr/0.4.0/lib/functions.typ
  packages/preview/chic-hdr/0.4.0/lib/layout.typ
  packages/preview/chic-hdr/0.4.0/lib/props.typ
  packages/preview/chic-hdr/0.4.0/lib/types.typ
  packages/preview/chic-hdr/0.4.0/manual/example-1/ex-1.png
  packages/preview/chic-hdr/0.4.0/manual/example-1/ex-2.png
  packages/preview/chic-hdr/0.4.0/manual/example-1/ex-3.png
  packages/preview/chic-hdr/0.4.0/manual/example-2/ex-1.png
  packages/preview/chic-hdr/0.4.0/manual/example-2/ex-2.png
  packages/preview/chic-hdr/0.4.0/manual/example-2/ex-3.png
  packages/preview/chic-hdr/0.4.0/manual/example-3/ex-1.png
  packages/preview/chic-hdr/0.4.0/manual/example-3/ex-2.png
  packages/preview/chic-hdr/0.4.0/manual/example-3/ex-3.png
  packages/preview/chic-hdr/0.4.0/manual/manual.typ
  packages/preview/chic-hdr/0.4.0/manual/template.typ
  packages/preview/chic-hdr/0.4.0/typst.toml
Labels: update

#308 polytonoi:0.1.0
  packages/preview/polytonoi/0.1.0/LICENSE
  packages/preview/polytonoi/0.1.0/README.md
  packages/preview/polytonoi/0.1.0/polytonoi.typ
  packages/preview/polytonoi/0.1.0/typst.toml
Labels: new

#311 ansi-render:0.6.1
  packages/preview/ansi-render/0.6.1/CHANGELOG.md
  packages/preview/ansi-render/0.6.1/LICENSE
  packages/preview/ansi-render/0.6.1/README.md
  packages/preview/ansi-render/0.6.1/ansi-render.typ
  packages/preview/ansi-render/0.6.1/typst.toml
Labels: update

#312 ascii-ipa:1.1.1
  packages/preview/ascii-ipa/1.1.1/CHANGELOG.md
  packages/preview/ascii-ipa/1.1.1/LICENSE
  packages/preview/ascii-ipa/1.1.1/README.md
  packages/preview/ascii-ipa/1.1.1/ascii-ipa.typ
  packages/preview/ascii-ipa/1.1.1/src/lib.typ
  packages/preview/ascii-ipa/1.1.1/src/translations/branner.typ
  packages/preview/ascii-ipa/1.1.1/src/translations/praat.typ
  packages/preview/ascii-ipa/1.1.1/src/translations/sil.typ
  packages/preview/ascii-ipa/1.1.1/src/translations/xsampa.typ
  packages/preview/ascii-ipa/1.1.1/test/test.typ
  packages/preview/ascii-ipa/1.1.1/typst.toml
Labels: update
