Repository typst/packages, pull requests merged in 2023-11, with the labels that each got.

#207 physica:0.8.1
  packages/preview/physica/0.8.1/LICENSE.txt
  packages/preview/physica/0.8.1/README.md
  packages/preview/physica/0.8.1/physica.typ
  packages/preview/physica/0.8.1/typst.toml
Labels: update

#208 commute:0.2.0
  packages/preview/commute/0.2.0/LICENSE
  packages/preview/commute/0.2.0/README.md
  packages/preview/commute/0.2.0/example.typ
  packages/preview/commute/0.2.0/lib.typ
  packages/preview/commute/0.2.0/typst.toml
Labels: update

#222 ctheorems:1.1.0
  packages/preview/ctheorems/1.1.0/LICENSE
  packages/preview/ctheorems/1.1.0/README.md
  packages/preview/ctheorems/1.1.0/assets/basic.png
  packages/preview/ctheorems/1.1.0/assets/manual.pdf
  packages/preview/ctheorems/1.1.0/assets/manual_examples.pdf
  packages/preview/ctheorems/1.1.0/lib.typ
  packages/preview/ctheorems/1.1.0/typst.toml
Labels: update

#217 codly:0.1.0
  packages/preview/codly/0.1.0/LICENSE
  packages/preview/codly/0.1.0/README.md
  packages/preview/codly/0.1.0/codly.typ
  packages/preview/codly/0.1.0/demo.png
  packages/preview/codly/0.1.0/example/brand-python.svg
  packages/preview/codly/0.1.0/example/brand-rust.svg
  packages/preview/codly/0.1.0/example/main.pdf
  packages/preview/codly/0.1.0/example/main.typ
  packages/preview/codly/0.1.0/typst.toml
Labels: new

#221 sourcerer:0.1.0
  packages/preview/sourcerer/0.1.0/DOCS.md
  packages/preview/sourcerer/0.1.0/LICENSE
  packages/preview/sourcerer/0.1.0/README.md
  packages/preview/sourcerer/0.1.0/assets/sourcerer.png
  packages/preview/sourcerer/0.1.0/src/lib.typ
  packages/preview/sourcerer/0.1.0/typst.toml
Labels: new

#213 pinit:0.1.0
  packages/preview/pinit/0.1.0/LICENSE
  packages/preview/pinit/0.1.0/README.md
  packages/preview/pinit/0.1.0/examples/asymptotic.png
  packages/preview/pinit/0.1.0/examples/example-pages.png
  packages/preview/pinit/0.1.0/examples/example.pdf
  packages/preview/pinit/0.1.0/examples/example.png
  packages/preview/pinit/0.1.0/examples/example.typ
  packages/preview/pinit/0.1.0/examples/simple-demo.png
  packages/preview/pinit/0.1.0/lib.typ
  packages/preview/pinit/0.1.0/pinit-core.typ
  packages/preview/pinit/0.1.0/simple-arrow.typ
  packages/preview/pinit/0.1.0/typst.toml
Labels: new, blocked

#223 stonewall:0.1.0
  packages/preview/stonewall/0.1.0/LICENSE
  packages/preview/stonewall/0.1.0/README.md
  packages/preview/stonewall/0.1.0/example/example.pdf
  packages/preview/stonewall/0.1.0/example/example.typ
  packages/preview/stonewall/0.1.0/flags.png
  packages/preview/stonewall/0.1.0/stonewall.typ
  packages/preview/stonewall/0.1.0/typst.toml
Labels: new, blocked

#232 sourcerer:0.2.1
  packages/preview/sourcerer/0.2.1/DOCS.md
  packages/preview/sourcerer/0.2.1/LICENSE
  packages/preview/sourcerer/0.2.1/README.md
  packages/preview/sourcerer/0.2.1/assets/sourcerer.png
  packages/preview/sourcerer/0.2.1/src/lib.typ
  packages/preview/sourcerer/0.2.1/typst.toml
Labels: update

#240 i-figured:0.2.0
  packages/preview/i-figured/0.2.0/LICENSE
  packages/preview/i-figured/0.2.0/README.md
  packages/preview/i-figured/0.2.0/examples/basic.png
  packages/preview/i-figured/0.2.0/examples/basic.typ
  packages/preview/i-figured/0.2.0/examples/level-two.png
  packages/preview/i-figured/0.2.0/examples/level-two.typ
  packages/preview/i-figured/0.2.0/i-figured.typ
  packages/preview/i-figured/0.2.0/typst.toml
Labels: update

#239 codelst:2.0.0
  packages/preview/codelst/2.0.0/LICENSE
  packages/preview/codelst/2.0.0/README.md
  packages/preview/codelst/2.0.0/codelst.typ
  packages/preview/codelst/2.0.0/example.pdf
  packages/preview/codelst/2.0.0/example.typ
  packages/preview/codelst/2.0.0/manual.pdf
  packages/preview/codelst/2.0.0/manual.typ
  packages/preview/codelst/2.0.0/tbump.toml
  packages/preview/codelst/2.0.0/typst.toml
Labels: update

#236 glossarium:0.2.4
  packages/preview/glossarium/0.2.4/.gitignore
  packages/preview/glossarium/0.2.4/LICENCE
  packages/preview/glossarium/0.2.4/README.md
  packages/preview/glossarium/0.2.4/example/example.pdf
  packages/preview/glossarium/0.2.4/example/example.png
  packages/preview/glossarium/0.2.4/example/example.typ
  packages/preview/glossarium/0.2.4/glossarium.typ
  packages/preview/glossarium/0.2.4/makefile
  packages/preview/glossarium/0.2.4/tbump.toml
  packages/preview/glossarium/0.2.4/typst.toml
Labels: update

#237 gentle-clues:0.4.0
  packages/preview/gentle-clues/0.4.0/LICENSE
  packages/preview/gentle-clues/0.4.0/README.md
  packages/preview/gentle-clues/0.4.0/assets/abstract.svg
  packages/preview/gentle-clues/0.4.0/assets/bell.svg
  packages/preview/gentle-clues/0.4.0/assets/bookmark.svg
  packages/preview/gentle-clues/0.4.0/assets/checkbox.svg
  packages/preview/gentle-clues/0.4.0/assets/cleanup-script.sh
  packages/preview/gentle-clues/0.4.0/assets/crossmark.svg
  packages/preview/gentle-clues/0.4.0/assets/danger.svg
  packages/preview/gentle-clues/0.4.0/assets/example.svg
  packages/preview/gentle-clues/0.4.0/assets/excl.svg
  packages/preview/gentle-clues/0.4.0/assets/flag.svg
  packages/preview/gentle-clues/0.4.0/assets/info.svg
  packages/preview/gentle-clues/0.4.0/assets/lightbulb.svg
  packages/preview/gentle-clues/0.4.0/assets/questionmark.svg
  packages/preview/gentle-clues/0.4.0/assets/quote.svg
  packages/preview/gentle-clues/0.4.0/assets/task.svg
  packages/preview/gentle-clues/0.4.0/assets/tip.svg
  packages/preview/gentle-clues/0.4.0/assets/warning.svg
  packages/preview/gentle-clues/0.4.0/gentle-clues.typ
  packages/preview/gentle-clues/0.4.0/screenshot_info-clue.png
  packages/preview/gentle-clues/0.4.0/typst.toml
Labels: update

#229 slydst:0.1.0
  packages/preview/slydst/0.1.0/LICENSE
  packages/preview/slydst/0.1.0/README.md
  packages/preview/slydst/0.1.0/example.typ
  packages/preview/slydst/0.1.0/lib.typ
  packages/preview/slydst/0.1.0/slydst.typ
  packages/preview/slydst/0.1.0/svg/example-01.svg
  packages/preview/slydst/0.1.0/svg/example-02.svg
  packages/preview/slydst/0.1.0/svg/example-03.svg
  packages/preview/slydst/0.1.0/svg/example-04.svg
  packages/preview/slydst/0.1.0/svg/example-05.svg
  packages/preview/slydst/0.1.0/svg/example-06.svg
  packages/preview/slydst/0.1.0/svg/example-07.svg
  packages/preview/slydst/0.1.0/svg/example-08.svg
  packages/preview/slydst/0.1.0/svg/example-09.svg
  packages/preview/slydst/0.1.0/svg/example-10.svg
  packages/preview/slydst/0.1.0/typst.toml
Labels: new

#235 octique:0.1.0
  packages/preview/octique/0.1.0/LICENSE
  packages/preview/octique/0.1.0/README.md
  packages/preview/octique/0.1.0/impl/octique.typ
  packages/preview/octique/0.1.0/octique.typ
  packages/preview/octique/0.1.0/sample/sample.pdf
  packages/preview/octique/0.1.0/sample/sample.typ
  packages/preview/octique/0.1.0/typst.toml
Labels: new

#238 tablem:0.1.0
  packages/preview/tablem/0.1.0/LICENSE
  packages/preview/tablem/0.1.0/README.md
  packages/preview/tablem/0.1.0/examples/example.png
  packages/preview/tablem/0.1.0/examples/example.typ
  packages/preview/tablem/0.1.0/tablem.typ
  packages/preview/tablem/0.1.0/typst.toml
Labels: new, blocked

#244 quill:0.2.0 - fix demo image for dark mode
  packages/preview/quill/0.2.0/README.md
  packages/preview/quill/0.2.0/docs/images/bell.svg
  packages/preview/quill/0.2.0/docs/images/gallery.svg
  packages/preview/quill/0.2.0/docs/images/logo.svg
  packages/preview/quill/0.2.0/docs/images/phase-estimation.svg
  packages/preview/quill/0.2.0/docs/images/qft.svg
  packages/preview/quill/0.2.0/docs/images/teleportation.svg
Labels: minor-fix

#246 i-figured:0.2.1
  packages/preview/i-figured/0.2.1/LICENSE
  packages/preview/i-figured/0.2.1/README.md
  packages/preview/i-figured/0.2.1/examples/basic.png
  packages/preview/i-figured/0.2.1/examples/basic.typ
  packages/preview/i-figured/0.2.1/examples/level-two.png
  packages/preview/i-figured/0.2.1/examples/level-two.typ
  packages/preview/i-figured/0.2.1/i-figured.typ
  packages/preview/i-figured/0.2.1/typst.toml
Labels: update

#245 hydra:0.1.0
  packages/preview/hydra/0.1.0/LICENSE
  packages/preview/hydra/0.1.0/README.md
  packages/preview/hydra/0.1.0/examples/example1.png
  packages/preview/hydra/0.1.0/examples/example2.png
  packages/preview/hydra/0.1.0/examples/example3.png
  packages/preview/hydra/0.1.0/examples/example4.png
  packages/preview/hydra/0.1.0/examples/example5.png
  packages/preview/hydra/0.1.0/examples/main.typ
  packages/preview/hydra/0.1.0/src/default.typ
  packages/preview/hydra/0.1.0/src/lib.typ
  packages/preview/hydra/0.1.0/src/util.typ
  packages/preview/hydra/0.1.0/typst.toml
Labels: new

#250 cartao:0.1.0
  packages/preview/cartao/0.1.0/LICENSE
  packages/preview/cartao/0.1.0/README.md
  packages/preview/cartao/0.1.0/cartao.typ
  packages/preview/cartao/0.1.0/example.pdf
  packages/preview/cartao/0.1.0/typst.toml
Labels: new

#251 fletcher:0.1.0
  packages/preview/fletcher/0.1.0/LICENSE
  packages/preview/fletcher/0.1.0/README.md
  packages/preview/fletcher/0.1.0/docs/examples/example-1.svg
  packages/preview/fletcher/0.1.0/docs/examples/example-2.svg
  packages/preview/fletcher/0.1.0/docs/examples/example.typ
  packages/preview/fletcher/0.1.0/docs/manual.pdf
  packages/preview/fletcher/0.1.0/docs/manual.typ
  packages/preview/fletcher/0.1.0/src/all.typ
  packages/preview/fletcher/0.1.0/src/draw.typ
  packages/preview/fletcher/0.1.0/src/exports.typ
  packages/preview/fletcher/0.1.0/src/layout.typ
  packages/preview/fletcher/0.1.0/src/main.typ
  packages/preview/fletcher/0.1.0/src/marks.typ
  packages/preview/fletcher/0.1.0/src/utils.typ
  packages/preview/fletcher/0.1.0/test/test.pdf
  packages/preview/fletcher/0.1.0/test/test.typ
  packages/preview/fletcher/0.1.0/typst.toml
Labels: new

#259 rubby:0.10.0
  packages/preview/rubby/0.10.0/CHANGELOG.md
  packages/preview/rubby/0.10.0/LICENSE
  packages/preview/rubby/0.10.0/NOTICE
  packages/preview/rubby/0.10.0/README.md
  packages/preview/rubby/0.10.0/example.typ
  packages/preview/rubby/0.10.0/rubby.typ
  packages/preview/rubby/0.10.0/typst.toml
Labels: update

#261 pinit:0.1.2
  packages/preview/pinit/0.1.2/LICENSE
  packages/preview/pinit/0.1.2/README.md
  packages/preview/pinit/0.1.2/examples/asymptotic.png
  packages/preview/pinit/0.1.2/examples/equation-desc.png
  packages/preview/pinit/0.1.2/examples/equation-desc.typ
  packages/preview/pinit/0.1.2/examples/example-pages.png
  packages/preview/pinit/0.1.2/examples/example.pdf
  packages/preview/pinit/0.1.2/examples/example.png
  packages/preview/pinit/0.1.2/examples/example.typ
  packages/preview/pinit/0.1.2/examples/simple-demo.png
  packages/preview/pinit/0.1.2/lib.typ
  packages/preview/pinit/0.1.2/pinit-core.typ
  packages/preview/pinit/0.1.2/simple-arrow.typ
  packages/preview/pinit/0.1.2/typst.toml
Labels: update

#262 `fletcher:0.2.0`
  packages/preview/fletcher/0.2.0/LICENSE
  packages/preview/fletcher/0.2.0/README.md
  packages/preview/fletcher/0.2.0/docs/examples/example-1.svg
  packages/preview/fletcher/0.2.0/docs/examples/example-2.svg
  packages/preview/fletcher/0.2.0/docs/examples/example.typ
  packages/preview/fletcher/0.2.0/docs/manual.pdf
  packages/preview/fletcher/0.2.0/docs/manual.typ
  packages/preview/fletcher/0.2.0/src/all.typ
  packages/preview/fletcher/0.2.0/src/draw.typ
  packages/preview/fletcher/0.2.0/src/exports.typ
  packages/preview/fletcher/0.2.0/src/layout.typ
  packages/preview/fletcher/0.2.0/src/main.typ
  packages/preview/fletcher/0.2.0/src/marks.typ
  packages/preview/fletcher/0.2.0/src/utils.typ
  packages/preview/fletcher/0.2.0/test/test.pdf
  packages/preview/fletcher/0.2.0/test/test.typ
  packages/preview/fletcher/0.2.0/typst.toml
Labels: update

#264 jogs:0.2.1
  packages/preview/jogs/0.2.1/LICENSE
  packages/preview/jogs/0.2.1/README.md
  packages/preview/jogs/0.2.1/examples/fib.svg
  packages/preview/jogs/0.2.1/examples/fib.typ
  packages/preview/jogs/0.2.1/jogs.wasm
  packages/preview/jogs/0.2.1/lib.typ
  packages/preview/jogs/0.2.1/license.html
  packages/preview/jogs/0.2.1/typst.toml
Labels: update

#266 anti-matter:0.1.0
  packages/preview/anti-matter/0.1.0/LICENSE
  packages/preview/anti-matter/0.1.0/README.md
  packages/preview/anti-matter/0.1.0/docs/manual.pdf
  packages/preview/anti-matter/0.1.0/docs/manual.typ
  packages/preview/anti-matter/0.1.0/docs/template.typ
  packages/preview/anti-matter/0.1.0/example/back-matter.typ
  packages/preview/anti-matter/0.1.0/example/chapters.typ
  packages/preview/anti-matter/0.1.0/example/example.png
  packages/preview/anti-matter/0.1.0/example/front-matter.typ
  packages/preview/anti-matter/0.1.0/example/main.typ
  packages/preview/anti-matter/0.1.0/src/core.typ
  packages/preview/anti-matter/0.1.0/src/lib.typ
  packages/preview/anti-matter/0.1.0/src/rules.typ
  packages/preview/anti-matter/0.1.0/src/util.typ
  packages/preview/anti-matter/0.1.0/typst.toml
Labels: update

#254 esotefy:1.0.0
  packages/preview/esotefy/1.0.0/.gitignore
  packages/preview/esotefy/1.0.0/LICENSE
  packages/preview/esotefy/1.0.0/README.md
  packages/preview/esotefy/1.0.0/example.pdf
  packages/preview/esotefy/1.0.0/example.typ
  packages/preview/esotefy/1.0.0/index.typ
  packages/preview/esotefy/1.0.0/typst.toml
Labels: new

#263 tiaoma:0.1.0
  packages/preview/tiaoma/0.1.0/LICENSE
  packages/preview/tiaoma/0.1.0/README.md
  packages/preview/tiaoma/0.1.0/example.svg
  packages/preview/tiaoma/0.1.0/example.typ
  packages/preview/tiaoma/0.1.0/lib.typ
  packages/preview/tiaoma/0.1.0/license.html
  packages/preview/tiaoma/0.1.0/manual.pdf
  packages/preview/tiaoma/0.1.0/manual.typ
  packages/preview/tiaoma/0.1.0/typst.toml
  packages/preview/tiaoma/0.1.0/zint_typst_plugin.wasm
Labels: new
