Repository typst/packages, pull requests merged in 2023-07, with the labels that each got.

#5 big-todo:0.1.0
  packages/preview/big-todo-0.1.0/LICENSE
  packages/preview/big-todo-0.1.0/README.md
  packages/preview/big-todo-0.1.0/lib.typ
  packages/preview/big-todo-0.1.0/screenshot.png
  packages/preview/big-todo-0.1.0/typst.toml
Labels: p-new, p-name-approved

#6 lemmify:0.1.0
  packages/preview/lemmify-0.1.0/LICENSE
  packages/preview/lemmify-0.1.0/README.md
  packages/preview/lemmify-0.1.0/src/lib.typ
  packages/preview/lemmify-0.1.0/src/styles.typ
  packages/preview/lemmify-0.1.0/src/translations.typ
  packages/preview/lemmify-0.1.0/src/util.typ
  packages/preview/lemmify-0.1.0/typst.toml
Labels: p-new, p-name-approved

#10 splash:0.3.0
  packages/preview/splash-0.3.0/LICENSE
  packages/preview/splash-0.3.0/README.md
  packages/preview/splash-0.3.0/src/palettes.typ
  packages/preview/splash-0.3.0/src/palettes/beamer.typ
  packages/preview/splash-0.3.0/src/palettes/google-workspace.typ
  packages/preview/splash-0.3.0/src/palettes/kth.typ
  packages/preview/splash-0.3.0/src/palettes/misc.typ
  packages/preview/splash-0.3.0/src/palettes/okabe-ito.typ
  packages/preview/splash-0.3.0/src/palettes/tailwind-css.typ
  packages/preview/splash-0.3.0/src/palettes/tol.typ
  packages/preview/splash-0.3.0/src/palettes/typst-highlighting.typ
  packages/preview/splash-0.3.0/src/palettes/xcolor.typ
  packages/preview/splash-0.3.0/typst.toml
Labels: p-new, p-name-approved

#11 ascii-ipa:1.0.0
  packages/preview/ascii-ipa-1.0.0/LICENSE
  packages/preview/ascii-ipa-1.0.0/README.md
  packages/preview/ascii-ipa-1.0.0/lib.typ
  packages/preview/ascii-ipa-1.0.0/test.typ
  packages/preview/ascii-ipa-1.0.0/typst.toml
  packages/preview/ascii-ipa-1.0.0/util/branner.typ
  packages/preview/ascii-ipa-1.0.0/util/praat.typ
  packages/preview/ascii-ipa-1.0.0/util/sil.typ
  packages/preview/ascii-ipa-1.0.0/util/xsampa.typ
Labels: p-new, p-name-approved

#8 plotst:0.1.0
  packages/preview/plotst-0.1.0/LICENSE
  packages/preview/plotst-0.1.0/README.md
  packages/preview/plotst-0.1.0/lib.typ
  packages/preview/plotst-0.1.0/plotst/axis.typ
  packages/preview/plotst-0.1.0/plotst/plotting.typ
  packages/preview/plotst-0.1.0/plotst/util/classify.typ
  packages/preview/plotst-0.1.0/plotst/util/util.typ
  packages/preview/plotst-0.1.0/typst.toml
Labels: p-new, p-name-approved

#4 gloss-awe:0.0.3
  packages/preview/gloss-awe-0.0.3/LICENSE
  packages/preview/gloss-awe-0.0.3/README.md
  packages/preview/gloss-awe-0.0.3/glossary.typ
  packages/preview/gloss-awe-0.0.3/typst.toml
Labels: p-new, p-name-approved

#12 showybox:0.1.1
  packages/preview/showybox-0.1.1/LICENSE
  packages/preview/showybox-0.1.1/README.md
  packages/preview/showybox-0.1.1/showy.typ
  packages/preview/showybox-0.1.1/typst.toml
Labels: p-new, p-name-approved

#7 rubby:0.8.0
  packages/preview/rubby-0.8.0/LICENSE
  packages/preview/rubby-0.8.0/NOTICE
  packages/preview/rubby-0.8.0/README.md
  packages/preview/rubby-0.8.0/rubby.typ
  packages/preview/rubby-0.8.0/typst.toml
Labels: p-new, p-name-approved

#14 ansi-render:0.1.0
  packages/preview/ansi-render-0.1.0/LICENSE
  packages/preview/ansi-render-0.1.0/README.md
  packages/preview/ansi-render-0.1.0/ansi_render.typ
  packages/preview/ansi-render-0.1.0/typst.toml
Labels: p-new, p-name-approved

#16 fontawesome:0.1.0
  packages/preview/fontawesome-0.1.0/LICENSE
  packages/preview/fontawesome-0.1.0/README.md
  packages/preview/fontawesome-0.1.0/lib.typ
  packages/preview/fontawesome-0.1.0/typst.toml
Labels: p-new, p-name-approved

#17 big-todo:0.2.0
  packages/preview/big-todo-0.2.0/LICENSE
  packages/preview/big-todo-0.2.0/README.md
  packages/preview/big-todo-0.2.0/lib.typ
  packages/preview/big-todo-0.2.0/typst.toml
Labels: update

#19 leipzig-glossing:0.1.0
  packages/preview/leipzig-glossing-0.1.0/LICENSE.txt
  packages/preview/leipzig-glossing-0.1.0/README.md
  packages/preview/leipzig-glossing-0.1.0/leipzig-gloss.typ
  packages/preview/leipzig-glossing-0.1.0/typst.toml
Labels: new-package, name-approved

#21 funarray:0.2.0 & ouset:0.1.0
  packages/preview/funarray-0.2.0/LICENSE
  packages/preview/funarray-0.2.0/README.md
  packages/preview/funarray-0.2.0/funarray-unsafe.typ
  packages/preview/funarray-0.2.0/funarray.typ
  packages/preview/funarray-0.2.0/typst.toml
  packages/preview/ouset-0.1.0/LICENSE
  packages/preview/ouset-0.1.0/README.md
  packages/preview/ouset-0.1.0/ouset.typ
  packages/preview/ouset-0.1.0/typst.toml
Labels: new-package, name-approved

#23 gloss-awe:0.0.4
  packages/preview/gloss-awe-0.0.4/LICENSE
  packages/preview/gloss-awe-0.0.4/README.md
  packages/preview/gloss-awe-0.0.4/gloss-awe.typ
  packages/preview/gloss-awe-0.0.4/typst.toml
Labels: update

#32 acrostiche:0.2.0
  packages/preview/acrostiche-0.2.0/LICENSE
  packages/preview/acrostiche-0.2.0/README.md
  packages/preview/acrostiche-0.2.0/acrostiche.typ
  packages/preview/acrostiche-0.2.0/typst.toml
Labels: update

#34 showybox:0.2.0
  packages/preview/showybox-0.2.0/LICENSE
  packages/preview/showybox-0.2.0/README.md
  packages/preview/showybox-0.2.0/showy.typ
  packages/preview/showybox-0.2.0/typst.toml
Labels: update

#45 codelst:0.0.3
  packages/preview/codelst-0.0.3/LICENSE
  packages/preview/codelst-0.0.3/README.md
  packages/preview/codelst-0.0.3/codelst.typ
  packages/preview/codelst-0.0.3/example.pdf
  packages/preview/codelst-0.0.3/example.typ
  packages/preview/codelst-0.0.3/manual.pdf
  packages/preview/codelst-0.0.3/manual.typ
  packages/preview/codelst-0.0.3/tbump.toml
  packages/preview/codelst-0.0.3/typst.toml
Labels: new

#51 polylux:0.2.0
  packages/preview/polylux-0.2.0/LICENSE
  packages/preview/polylux-0.2.0/README.md
  packages/preview/polylux-0.2.0/helpers.typ
  packages/preview/polylux-0.2.0/logic.typ
  packages/preview/polylux-0.2.0/polylux.typ
  packages/preview/polylux-0.2.0/themes/bipartite.typ
  packages/preview/polylux-0.2.0/themes/clean.typ
  packages/preview/polylux-0.2.0/themes/metropolis.typ
  packages/preview/polylux-0.2.0/themes/simple.typ
  packages/preview/polylux-0.2.0/themes/themes.typ
  packages/preview/polylux-0.2.0/themes/university.typ
  packages/preview/polylux-0.2.0/typst.toml
Labels: new

#49 unify:0.1.0
  packages/preview/unify-0.1.0/LICENSE
  packages/preview/unify-0.1.0/README.md
  packages/preview/unify-0.1.0/examples/overview.jpg
  packages/preview/unify-0.1.0/lib.typ
  packages/preview/unify-0.1.0/postfixes.csv
  packages/preview/unify-0.1.0/prefixes.csv
  packages/preview/unify-0.1.0/typst.toml
  packages/preview/unify-0.1.0/units.csv
Labels: new

#54 unify:0.4.0
  packages/preview/unify-0.4.0/LICENSE
  packages/preview/unify-0.4.0/README.md
  packages/preview/unify-0.4.0/examples/overview.jpg
  packages/preview/unify-0.4.0/lib.typ
  packages/preview/unify-0.4.0/postfixes.csv
  packages/preview/unify-0.4.0/prefixes.csv
  packages/preview/unify-0.4.0/typst.toml
  packages/preview/unify-0.4.0/units.csv
Labels: update

#58 codelst:1.0.0
  packages/preview/codelst-1.0.0/LICENSE
  packages/preview/codelst-1.0.0/README.md
  packages/preview/codelst-1.0.0/codelst.typ
  packages/preview/codelst-1.0.0/example.pdf
  packages/preview/codelst-1.0.0/example.typ
  packages/preview/codelst-1.0.0/manual.pdf
  packages/preview/codelst-1.0.0/manual.typ
  packages/preview/codelst-1.0.0/typst.toml
Labels: update

#55 diverential:0.2.0
  packages/preview/diverential-0.2.0/LICENSE
  packages/preview/diverential-0.2.0/README.md
  packages/preview/diverential-0.2.0/examples/overview.jpg
  packages/preview/diverential-0.2.0/lib.typ
  packages/preview/diverential-0.2.0/typst.toml
Labels: new, name-approved

#59 tbl:0.0.3
  packages/preview/tbl-0.0.3/LICENSE
  packages/preview/tbl-0.0.3/README.md
  packages/preview/tbl-0.0.3/tbl.typ
  packages/preview/tbl-0.0.3/typst.toml
Labels: new, name-approved

#62 showybox:1.0.0
  packages/preview/showybox-1.0.0/LICENSE
  packages/preview/showybox-1.0.0/README.md
  packages/preview/showybox-1.0.0/Showybox's Manual.pdf
  packages/preview/showybox-1.0.0/assets/custom-radius.png
  packages/preview/showybox-1.0.0/assets/enabling-breakable.png
  packages/preview/showybox-1.0.0/assets/encapsulation.png
  packages/preview/showybox-1.0.0/assets/further-examples.png
  packages/preview/showybox-1.0.0/assets/hello-world-example.png
  packages/preview/showybox-1.0.0/showy.typ
  packages/preview/showybox-1.0.0/typst.toml
Labels: update

#57 glossarium:0.1.0
  packages/preview/glossarium-0.1.0/.github/workflows/CI.yml
  packages/preview/glossarium-0.1.0/.gitignore
  packages/preview/glossarium-0.1.0/LICENCE
  packages/preview/glossarium-0.1.0/README.md
  packages/preview/glossarium-0.1.0/example/example.pdf
  packages/preview/glossarium-0.1.0/example/example.png
  packages/preview/glossarium-0.1.0/example/example.typ
  packages/preview/glossarium-0.1.0/glossarium.typ
  packages/preview/glossarium-0.1.0/makefile
  packages/preview/glossarium-0.1.0/tbump.toml
  packages/preview/glossarium-0.1.0/typst.toml
Labels: new, name-approved

#63 t4t:0.1.0
  packages/preview/t4t-0.1.0/LICENSE
  packages/preview/t4t-0.1.0/README.md
  packages/preview/t4t-0.1.0/alias.typ
  packages/preview/t4t-0.1.0/assert.typ
  packages/preview/t4t-0.1.0/def.typ
  packages/preview/t4t-0.1.0/get.typ
  packages/preview/t4t-0.1.0/is.typ
  packages/preview/t4t-0.1.0/math.typ
  packages/preview/t4t-0.1.0/tbump.toml
  packages/preview/t4t-0.1.0/tools4typst.typ
  packages/preview/t4t-0.1.0/typst.toml
Labels: new

#64 physica:0.7.5
  packages/preview/physica-0.7.5/LICENSE.txt
  packages/preview/physica-0.7.5/README.md
  packages/preview/physica-0.7.5/physica.typ
  packages/preview/physica-0.7.5/typst.toml
Labels: new
