Repository typst/packages, pull requests merged in 2024-08, with the labels that each got.

#869 charged-ieee:0.1.1 and unequivocal-ams:0.1.1
  packages/preview/charged-ieee/0.1.1/LICENSE
  packages/preview/charged-ieee/0.1.1/README.md
  packages/preview/charged-ieee/0.1.1/lib.typ
  packages/preview/charged-ieee/0.1.1/template/main.typ
  packages/preview/charged-ieee/0.1.1/template/refs.bib
  packages/preview/charged-ieee/0.1.1/thumbnail.png
  packages/preview/charged-ieee/0.1.1/typst.toml
  packages/preview/unequivocal-ams/0.1.1/LICENSE
  packages/preview/unequivocal-ams/0.1.1/README.md
  packages/preview/unequivocal-ams/0.1.1/lib.typ
  packages/preview/unequivocal-ams/0.1.1/template/main.typ
  packages/preview/unequivocal-ams/0.1.1/template/refs.bib
  packages/preview/unequivocal-ams/0.1.1/thumbnail.png
  packages/preview/unequivocal-ams/0.1.1/typst.toml
Labels: update

#912 orange-book:0.1.0 - Fix link in toml
  packages/preview/orange-book/0.1.0/typst.toml
Labels: minor fix

#909 pinit:0.2.0
  packages/preview/pinit/0.2.0/LICENSE
  packages/preview/pinit/0.2.0/README.md
  packages/preview/pinit/0.2.0/examples/asymptotic.png
  packages/preview/pinit/0.2.0/examples/equation-desc.png
  packages/preview/pinit/0.2.0/examples/equation-desc.typ
  packages/preview/pinit/0.2.0/examples/example-pages.png
  packages/preview/pinit/0.2.0/examples/example.png
  packages/preview/pinit/0.2.0/examples/example.typ
  packages/preview/pinit/0.2.0/examples/fletcher.png
  packages/preview/pinit/0.2.0/examples/fletcher.typ
  packages/preview/pinit/0.2.0/examples/pinit-for-raw.png
  packages/preview/pinit/0.2.0/examples/pinit-for-raw.typ
  packages/preview/pinit/0.2.0/examples/simple-demo.png
  packages/preview/pinit/0.2.0/examples/simple-demo2.png
  packages/preview/pinit/0.2.0/lib.typ
  packages/preview/pinit/0.2.0/pinit-core.typ
  packages/preview/pinit/0.2.0/pinit-fletcher.typ
  packages/preview/pinit/0.2.0/simple-arrow.typ
  packages/preview/pinit/0.2.0/typst.toml
Labels: update

#916 supercharged-dhbw:3.1.1
  packages/preview/supercharged-dhbw/3.1.1/CHANGELOG.md
  packages/preview/supercharged-dhbw/3.1.1/LICENSE
  packages/preview/supercharged-dhbw/3.1.1/README.md
  packages/preview/supercharged-dhbw/3.1.1/acronym-lib.typ
  packages/preview/supercharged-dhbw/3.1.1/check-attributes.typ
  packages/preview/supercharged-dhbw/3.1.1/confidentiality-statement.typ
  packages/preview/supercharged-dhbw/3.1.1/declaration-of-authorship.typ
  packages/preview/supercharged-dhbw/3.1.1/dhbw.svg
  packages/preview/supercharged-dhbw/3.1.1/examples/example-acronyms.typ
  packages/preview/supercharged-dhbw/3.1.1/examples/example-glossary.typ
  packages/preview/supercharged-dhbw/3.1.1/examples/example-sources.bib
  packages/preview/supercharged-dhbw/3.1.1/examples/example-sources.yml
  packages/preview/supercharged-dhbw/3.1.1/examples/example.pdf
  packages/preview/supercharged-dhbw/3.1.1/examples/example.typ
  packages/preview/supercharged-dhbw/3.1.1/glossary-lib.typ
  packages/preview/supercharged-dhbw/3.1.1/lib.typ
  packages/preview/supercharged-dhbw/3.1.1/locale.typ
  packages/preview/supercharged-dhbw/3.1.1/shared-lib.typ
  packages/preview/supercharged-dhbw/3.1.1/template/acronyms.typ
  packages/preview/supercharged-dhbw/3.1.1/template/assets/ts.svg
  packages/preview/supercharged-dhbw/3.1.1/template/glossary.typ
  packages/preview/supercharged-dhbw/3.1.1/template/main.typ
  packages/preview/supercharged-dhbw/3.1.1/template/sources.bib
  packages/preview/supercharged-dhbw/3.1.1/thumbnail.png
  packages/preview/supercharged-dhbw/3.1.1/titlepage.typ
  packages/preview/supercharged-dhbw/3.1.1/typst.toml
Labels: update

#914 shiroa:0.1.1
  packages/preview/shiroa/0.1.1/LICENSE
  packages/preview/shiroa/0.1.1/README.md
  packages/preview/shiroa/0.1.1/lib.typ
  packages/preview/shiroa/0.1.1/media.typ
  packages/preview/shiroa/0.1.1/meta-and-state.typ
  packages/preview/shiroa/0.1.1/summary-internal.typ
  packages/preview/shiroa/0.1.1/summary.typ
  packages/preview/shiroa/0.1.1/supports-link.typ
  packages/preview/shiroa/0.1.1/supports-text.typ
  packages/preview/shiroa/0.1.1/sys.typ
  packages/preview/shiroa/0.1.1/template-link.typ
  packages/preview/shiroa/0.1.1/template-theme.typ
  packages/preview/shiroa/0.1.1/templates.typ
  packages/preview/shiroa/0.1.1/typst.toml
  packages/preview/shiroa/0.1.1/utils.typ
  packages/preview/shiroa/0.1.1/xcommand.typ
Labels: update

#915 metalogo:1.0.2
  packages/preview/metalogo/1.0.2/.gitignore
  packages/preview/metalogo/1.0.2/LICENSE
  packages/preview/metalogo/1.0.2/README.md
  packages/preview/metalogo/1.0.2/demo.svg
  packages/preview/metalogo/1.0.2/demo.typ
  packages/preview/metalogo/1.0.2/makefile
  packages/preview/metalogo/1.0.2/metalogo.typ
  packages/preview/metalogo/1.0.2/typst.toml
Labels: new

#917 vienna-tech:0.1.1
  packages/preview/vienna-tech/0.1.1/CHANGELOG.md
  packages/preview/vienna-tech/0.1.1/LICENSE
  packages/preview/vienna-tech/0.1.1/README.md
  packages/preview/vienna-tech/0.1.1/src/lib.typ
  packages/preview/vienna-tech/0.1.1/template/abstract.typ
  packages/preview/vienna-tech/0.1.1/template/appendix.typ
  packages/preview/vienna-tech/0.1.1/template/assets/refs.bib
  packages/preview/vienna-tech/0.1.1/template/assets/tuw.jpg
  packages/preview/vienna-tech/0.1.1/template/main.typ
  packages/preview/vienna-tech/0.1.1/template/sections.typ
  packages/preview/vienna-tech/0.1.1/thumbnail.png
  packages/preview/vienna-tech/0.1.1/typst.toml
Labels: update

#918 keyle:0.2.0
  packages/preview/keyle/0.2.0/CHANGELOG.md
  packages/preview/keyle/0.2.0/LICENSE
  packages/preview/keyle/0.2.0/README.md
  packages/preview/keyle/0.2.0/doc/keyle.pdf
  packages/preview/keyle/0.2.0/doc/keyle.typ
  packages/preview/keyle/0.2.0/justfile
  packages/preview/keyle/0.2.0/src/keyle.typ
  packages/preview/keyle/0.2.0/src/sym.typ
  packages/preview/keyle/0.2.0/test/test-1.png
  packages/preview/keyle/0.2.0/test/test-2.png
  packages/preview/keyle/0.2.0/test/test-3.png
  packages/preview/keyle/0.2.0/test/test-4.png
  packages/preview/keyle/0.2.0/test/test-5.png
  packages/preview/keyle/0.2.0/test/test-6.png
  packages/preview/keyle/0.2.0/test/test-7.png
  packages/preview/keyle/0.2.0/test/tests.typ
  packages/preview/keyle/0.2.0/typst.toml
Labels: update

#906 efilrst:0.1.0
  packages/preview/efilrst/0.1.0/LICENSE
  packages/preview/efilrst/0.1.0/README.md
  packages/preview/efilrst/0.1.0/examples/basic.pdf
  packages/preview/efilrst/0.1.0/examples/basic.typ
  packages/preview/efilrst/0.1.0/img/image.png
  packages/preview/efilrst/0.1.0/src/lib.typ
  packages/preview/efilrst/0.1.0/typst.toml
Labels: new

#903 fh-joanneum-iit-thesis:1.1.0
  packages/preview/fh-joanneum-iit-thesis/1.1.0/LICENSE
  packages/preview/fh-joanneum-iit-thesis/1.1.0/README.md
  packages/preview/fh-joanneum-iit-thesis/1.1.0/lib.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/biblio.bib
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/biblio.csl
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/2-intro.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/3-related.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/4-background.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/5-concept.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/6-implementation.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/7-evaluation.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/8-conclusion.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/chapters/global.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/code-snippets/msg.py
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/data/recordings.csv
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/figures/chart-1.svg
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/figures/chart-2.svg
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/figures/logo.svg
  packages/preview/fh-joanneum-iit-thesis/1.1.0/template/thesis.typ
  packages/preview/fh-joanneum-iit-thesis/1.1.0/thumbnail.png
  packages/preview/fh-joanneum-iit-thesis/1.1.0/typst.toml
Labels: new

#908 touying-simpl-hkustgz:0.1.0
  packages/preview/touying-simpl-hkustgz/0.1.0/LICENSE
  packages/preview/touying-simpl-hkustgz/0.1.0/README.md
  packages/preview/touying-simpl-hkustgz/0.1.0/assets/vi/hkustgz-logo.svg
  packages/preview/touying-simpl-hkustgz/0.1.0/examples/main.typ
  packages/preview/touying-simpl-hkustgz/0.1.0/lib.typ
  packages/preview/touying-simpl-hkustgz/0.1.0/template/main.typ
  packages/preview/touying-simpl-hkustgz/0.1.0/thumbnail.png
  packages/preview/touying-simpl-hkustgz/0.1.0/typst.toml
Labels: new

#910 thesist:0.1.0
  packages/preview/thesist/0.1.0/LICENSE
  packages/preview/thesist/0.1.0/README.md
  packages/preview/thesist/0.1.0/src/IST.png
  packages/preview/thesist/0.1.0/src/figure-numbering.typ
  packages/preview/thesist/0.1.0/src/layout.typ
  packages/preview/thesist/0.1.0/src/utils.typ
  packages/preview/thesist/0.1.0/template/Beginning/Abstract-en.typ
  packages/preview/thesist/0.1.0/template/Beginning/Abstract-pt.typ
  packages/preview/thesist/0.1.0/template/Beginning/Acknowledgments.typ
  packages/preview/thesist/0.1.0/template/Beginning/Glossary.typ
  packages/preview/thesist/0.1.0/template/Beginning/Keywords-en.typ
  packages/preview/thesist/0.1.0/template/Beginning/Keywords-pt.typ
  packages/preview/thesist/0.1.0/template/Chapters/0-Quick-guide.typ
  packages/preview/thesist/0.1.0/template/Chapters/1-Introduction.typ
  packages/preview/thesist/0.1.0/template/Chapters/Appendix-A.typ
  packages/preview/thesist/0.1.0/template/Chapters/Appendix-B.typ
  packages/preview/thesist/0.1.0/template/Images/0-Quick-guide/andromeda.jpg
  packages/preview/thesist/0.1.0/template/Images/default-cover.jpg
  packages/preview/thesist/0.1.0/template/main.typ
  packages/preview/thesist/0.1.0/template/refs.bib
  packages/preview/thesist/0.1.0/thumbnail.png
  packages/preview/thesist/0.1.0/typst.toml
Labels: new

#921 fh-joanneum-iit-thesis:1.2.0
  packages/preview/fh-joanneum-iit-thesis/1.2.0/LICENSE
  packages/preview/fh-joanneum-iit-thesis/1.2.0/README.md
  packages/preview/fh-joanneum-iit-thesis/1.2.0/lib.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/biblio.bib
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/biblio.csl
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/1-acknowledgements.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/2-intro.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/3-related.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/4-background.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/5-concept.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/6-implementation.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/7-evaluation.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/8-conclusion.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/global.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/chapters/glossary.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/code-snippets/msg.py
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/data/recordings.csv
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/figures/chart-1.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/figures/chart-2.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/figures/logo.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.0/template/thesis.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.0/thumbnail.png
  packages/preview/fh-joanneum-iit-thesis/1.2.0/typst.toml
Labels: update

#922 lemmify:0.1.6
  packages/preview/lemmify/0.1.6/LICENSE
  packages/preview/lemmify/0.1.6/README.md
  packages/preview/lemmify/0.1.6/src/lib.typ
  packages/preview/lemmify/0.1.6/src/styles.typ
  packages/preview/lemmify/0.1.6/src/translations.typ
  packages/preview/lemmify/0.1.6/src/util.typ
  packages/preview/lemmify/0.1.6/typst.toml
Labels: update

#919 nifty-ntnu-thesis:0.1.0
  packages/preview/nifty-ntnu-thesis/0.1.0/LICENSE
  packages/preview/nifty-ntnu-thesis/0.1.0/README.md
  packages/preview/nifty-ntnu-thesis/0.1.0/example.pdf
  packages/preview/nifty-ntnu-thesis/0.1.0/lib.typ
  packages/preview/nifty-ntnu-thesis/0.1.0/template/figures/kart_student.png
  packages/preview/nifty-ntnu-thesis/0.1.0/template/main.typ
  packages/preview/nifty-ntnu-thesis/0.1.0/template/thesis.bib
  packages/preview/nifty-ntnu-thesis/0.1.0/thumbnail.png
  packages/preview/nifty-ntnu-thesis/0.1.0/typst.toml
Labels: new

#924 modernpro-cv:1.0.1
  packages/preview/modernpro-cv/1.0.1/README.md
  packages/preview/modernpro-cv/1.0.1/modernpro-cv.typ
  packages/preview/modernpro-cv/1.0.1/template/bib.bib
  packages/preview/modernpro-cv/1.0.1/template/cv-double.typ
  packages/preview/modernpro-cv/1.0.1/template/cv-single.typ
  packages/preview/modernpro-cv/1.0.1/thumbnail.png
  packages/preview/modernpro-cv/1.0.1/typst.toml
Labels: update

#926 fh-joanneum-iit-thesis:1.2.2
  packages/preview/fh-joanneum-iit-thesis/1.2.2/LICENSE
  packages/preview/fh-joanneum-iit-thesis/1.2.2/README.md
  packages/preview/fh-joanneum-iit-thesis/1.2.2/lib.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/biblio.bib
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/biblio.csl
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/1-acknowledgements.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/2-intro.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/3-related.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/4-background.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/5-concept.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/6-implementation.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/7-evaluation.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/8-conclusion.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/global.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/chapters/glossary.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/code-snippets/msg.py
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/data/recordings.csv
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/figures/chart-1.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/figures/chart-2.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/figures/logo.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.2/template/thesis.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.2/thumbnail.png
  packages/preview/fh-joanneum-iit-thesis/1.2.2/typst.toml
Labels: update
