Repository typst/packages, pull requests merged in 2024-10, with the labels that each got.

#1020 knowledge-key:1.0.0
  packages/preview/knowledge-key/1.0.0/LICENSE
  packages/preview/knowledge-key/1.0.0/README.md
  packages/preview/knowledge-key/1.0.0/lib.typ
  packages/preview/knowledge-key/1.0.0/template/figures/devops-lifecycle.png
  packages/preview/knowledge-key/1.0.0/template/main.typ
  packages/preview/knowledge-key/1.0.0/template/sections/01-introduction.typ
  packages/preview/knowledge-key/1.0.0/template/sections/02-devops-with-gitlab.typ
  packages/preview/knowledge-key/1.0.0/template/sections/03-terraform.typ
  packages/preview/knowledge-key/1.0.0/template/utils.typ
  packages/preview/knowledge-key/1.0.0/thumbnail.png
  packages/preview/knowledge-key/1.0.0/typst.toml
Labels: new

#1023 grotesk-cv:0.1.1
  packages/preview/grotesk-cv/0.1.1/LICENSE
  packages/preview/grotesk-cv/0.1.1/README.md
  packages/preview/grotesk-cv/0.1.1/lib.typ
  packages/preview/grotesk-cv/0.1.1/template/content/education.typ
  packages/preview/grotesk-cv/0.1.1/template/content/experience.typ
  packages/preview/grotesk-cv/0.1.1/template/content/languages.typ
  packages/preview/grotesk-cv/0.1.1/template/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.1/template/content/personal.typ
  packages/preview/grotesk-cv/0.1.1/template/content/profile.typ
  packages/preview/grotesk-cv/0.1.1/template/content/references.typ
  packages/preview/grotesk-cv/0.1.1/template/content/skills.typ
  packages/preview/grotesk-cv/0.1.1/template/cover.typ
  packages/preview/grotesk-cv/0.1.1/template/cv.typ
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.1/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.1/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.1/template/metadata.typ
  packages/preview/grotesk-cv/0.1.1/thumbnail.png
  packages/preview/grotesk-cv/0.1.1/typst.toml
Labels: update

#1026 nassi:0.1.1
  packages/preview/nassi/0.1.1/LICENSE
  packages/preview/nassi/0.1.1/README.md
  packages/preview/nassi/0.1.1/assets/example-1.png
  packages/preview/nassi/0.1.1/assets/example-1.typ
  packages/preview/nassi/0.1.1/assets/example-2.png
  packages/preview/nassi/0.1.1/assets/example-2.typ
  packages/preview/nassi/0.1.1/assets/example-3.png
  packages/preview/nassi/0.1.1/assets/example-3.typ
  packages/preview/nassi/0.1.1/assets/example-cetz-2.png
  packages/preview/nassi/0.1.1/assets/example-cetz-2.typ
  packages/preview/nassi/0.1.1/assets/example-cetz.png
  packages/preview/nassi/0.1.1/assets/example-cetz.typ
  packages/preview/nassi/0.1.1/src/draw.typ
  packages/preview/nassi/0.1.1/src/elements.typ
  packages/preview/nassi/0.1.1/src/nassi.typ
  packages/preview/nassi/0.1.1/tests/.gitignore
  packages/preview/nassi/0.1.1/tests/.ignore
  packages/preview/nassi/0.1.1/tests/statement/.gitignore
  packages/preview/nassi/0.1.1/tests/statement/out/1.png
  packages/preview/nassi/0.1.1/tests/statement/ref/1.png
  packages/preview/nassi/0.1.1/tests/statement/test.typ
  packages/preview/nassi/0.1.1/tests/switch/.gitignore
  packages/preview/nassi/0.1.1/tests/switch/out/1.png
  packages/preview/nassi/0.1.1/tests/switch/ref/1.png
  packages/preview/nassi/0.1.1/tests/switch/test.typ
  packages/preview/nassi/0.1.1/tests/template.typ
  packages/preview/nassi/0.1.1/typst.toml
Labels: update

#1027 teig:0.1.0
  packages/preview/teig/0.1.0/LICENSE
  packages/preview/teig/0.1.0/README.md
  packages/preview/teig/0.1.0/example.png
  packages/preview/teig/0.1.0/lib.typ
  packages/preview/teig/0.1.0/teig.wasm
  packages/preview/teig/0.1.0/typst.toml
Labels: new

#1025 babel:0.1.1
  packages/preview/babel/0.1.1/.typstignore
  packages/preview/babel/0.1.1/CHANGELOG.md
  packages/preview/babel/0.1.1/Justfile
  packages/preview/babel/0.1.1/LICENSE
  packages/preview/babel/0.1.1/README.md
  packages/preview/babel/0.1.1/assets/example.webp
  packages/preview/babel/0.1.1/assets/logo.svg
  packages/preview/babel/0.1.1/assets/logo.typ
  packages/preview/babel/0.1.1/assets/poster.typ
  packages/preview/babel/0.1.1/assets/poster.webp
  packages/preview/babel/0.1.1/assets/tower-of-babel.svg
  packages/preview/babel/0.1.1/docs/manual.pdf
  packages/preview/babel/0.1.1/docs/manual.typ
  packages/preview/babel/0.1.1/docs/tokyonight_day.tmTheme
  packages/preview/babel/0.1.1/scripts/package
  packages/preview/babel/0.1.1/scripts/setup
  packages/preview/babel/0.1.1/scripts/uninstall
  packages/preview/babel/0.1.1/src/alphabets.typ
  packages/preview/babel/0.1.1/src/alphabets.yaml
  packages/preview/babel/0.1.1/src/baffle.typ
  packages/preview/babel/0.1.1/src/lib.typ
  packages/preview/babel/0.1.1/typst.toml
Labels: new

#1031 orange-book:0.2.0
  packages/preview/orange-book/0.2.0/LICENSE
  packages/preview/orange-book/0.2.0/README.md
  packages/preview/orange-book/0.2.0/lib.typ
  packages/preview/orange-book/0.2.0/my-index.typ
  packages/preview/orange-book/0.2.0/my-outline.typ
  packages/preview/orange-book/0.2.0/template/background.svg
  packages/preview/orange-book/0.2.0/template/creodocs_logo.svg
  packages/preview/orange-book/0.2.0/template/main.typ
  packages/preview/orange-book/0.2.0/template/orange1.jpg
  packages/preview/orange-book/0.2.0/template/orange2.jpg
  packages/preview/orange-book/0.2.0/template/orange3.jpg
  packages/preview/orange-book/0.2.0/template/placeholder.jpg
  packages/preview/orange-book/0.2.0/template/sample.bib
  packages/preview/orange-book/0.2.0/theorems.typ
  packages/preview/orange-book/0.2.0/thumbnail.png
  packages/preview/orange-book/0.2.0/typst.toml
Labels: update

#1030 rivet:0.1.0
  packages/preview/rivet/0.1.0/CHANGELOG.md
  packages/preview/rivet/0.1.0/LICENSE
  packages/preview/rivet/0.1.0/README.md
  packages/preview/rivet/0.1.0/docs/config.typ
  packages/preview/rivet/0.1.0/docs/examples.typ
  packages/preview/rivet/0.1.0/docs/schema.typ
  packages/preview/rivet/0.1.0/gallery.bash
  packages/preview/rivet/0.1.0/gallery/example1.pdf
  packages/preview/rivet/0.1.0/gallery/example1.png
  packages/preview/rivet/0.1.0/gallery/example1.typ
  packages/preview/rivet/0.1.0/gallery/example1.yaml
  packages/preview/rivet/0.1.0/gallery/example2.pdf
  packages/preview/rivet/0.1.0/gallery/example2.png
  packages/preview/rivet/0.1.0/gallery/example2.typ
  packages/preview/rivet/0.1.0/gallery/example2.yaml
  packages/preview/rivet/0.1.0/gallery/example3.pdf
  packages/preview/rivet/0.1.0/gallery/example3.png
  packages/preview/rivet/0.1.0/gallery/example3.typ
  packages/preview/rivet/0.1.0/gallery/example3.yaml
  packages/preview/rivet/0.1.0/gallery/riscv/alu_instr.yaml
  packages/preview/rivet/0.1.0/gallery/riscv/branch_instr.yaml
  packages/preview/rivet/0.1.0/gallery/riscv/mem_instr.yaml
  packages/preview/rivet/0.1.0/gallery/riscv/riscv.pdf
  packages/preview/rivet/0.1.0/gallery/riscv/riscv.typ
  packages/preview/rivet/0.1.0/gallery/test.json
  packages/preview/rivet/0.1.0/gallery/test.pdf
  packages/preview/rivet/0.1.0/gallery/test.typ
  packages/preview/rivet/0.1.0/gallery/test.xml
  packages/preview/rivet/0.1.0/gallery/test.yaml
  packages/preview/rivet/0.1.0/manual.pdf
  packages/preview/rivet/0.1.0/manual.typ
  packages/preview/rivet/0.1.0/src/config.typ
  packages/preview/rivet/0.1.0/src/lib.typ
  packages/preview/rivet/0.1.0/src/range.typ
  packages/preview/rivet/0.1.0/src/renderer.typ
  packages/preview/rivet/0.1.0/src/schema.typ
  packages/preview/rivet/0.1.0/src/structure.typ
  packages/preview/rivet/0.1.0/src/util.typ
  packages/preview/rivet/0.1.0/src/vec.typ
  packages/preview/rivet/0.1.0/src/xml-loader.typ
  packages/preview/rivet/0.1.0/typst.toml
Labels: new

#1029 ichigo:0.1.0
  packages/preview/ichigo/0.1.0/LICENSE
  packages/preview/ichigo/0.1.0/README.md
  packages/preview/ichigo/0.1.0/export.typ
  packages/preview/ichigo/0.1.0/src/L10n/en.ftl
  packages/preview/ichigo/0.1.0/src/L10n/zh.ftl
  packages/preview/ichigo/0.1.0/src/lib.typ
  packages/preview/ichigo/0.1.0/src/model.typ
  packages/preview/ichigo/0.1.0/src/themes.typ
  packages/preview/ichigo/0.1.0/src/themes/simple/lib.typ
  packages/preview/ichigo/0.1.0/src/themes/sketch/lib.typ
  packages/preview/ichigo/0.1.0/src/themes/sketch/res/PKU.svg
  packages/preview/ichigo/0.1.0/src/title.typ
  packages/preview/ichigo/0.1.0/template/main.typ
  packages/preview/ichigo/0.1.0/thumbnail.png
  packages/preview/ichigo/0.1.0/typst.toml
Labels: new

#1033 supercharged-dhbw:3.3.1
  packages/preview/supercharged-dhbw/3.3.1/CHANGELOG.md
  packages/preview/supercharged-dhbw/3.3.1/LICENSE
  packages/preview/supercharged-dhbw/3.3.1/README.md
  packages/preview/supercharged-dhbw/3.3.1/acronym-lib.typ
  packages/preview/supercharged-dhbw/3.3.1/check-attributes.typ
  packages/preview/supercharged-dhbw/3.3.1/confidentiality-statement.typ
  packages/preview/supercharged-dhbw/3.3.1/declaration-of-authorship.typ
  packages/preview/supercharged-dhbw/3.3.1/dhbw.svg
  packages/preview/supercharged-dhbw/3.3.1/examples/example-acronyms.typ
  packages/preview/supercharged-dhbw/3.3.1/examples/example-glossary.typ
  packages/preview/supercharged-dhbw/3.3.1/examples/example-sources.bib
  packages/preview/supercharged-dhbw/3.3.1/examples/example-sources.yml
  packages/preview/supercharged-dhbw/3.3.1/examples/example.pdf
  packages/preview/supercharged-dhbw/3.3.1/examples/example.typ
  packages/preview/supercharged-dhbw/3.3.1/glossary-lib.typ
  packages/preview/supercharged-dhbw/3.3.1/lib.typ
  packages/preview/supercharged-dhbw/3.3.1/locale.typ
  packages/preview/supercharged-dhbw/3.3.1/shared-lib.typ
  packages/preview/supercharged-dhbw/3.3.1/template/acronyms.typ
  packages/preview/supercharged-dhbw/3.3.1/template/assets/ts.svg
  packages/preview/supercharged-dhbw/3.3.1/template/glossary.typ
  packages/preview/supercharged-dhbw/3.3.1/template/main.typ
  packages/preview/supercharged-dhbw/3.3.1/template/sources.bib
  packages/preview/supercharged-dhbw/3.3.1/thumbnail.png
  packages/preview/supercharged-dhbw/3.3.1/titlepage.typ
  packages/preview/supercharged-dhbw/3.3.1/typst.toml
Labels: update

#1034 circuiteria:0.1.0
  packages/preview/circuiteria/0.1.0/LICENSE
  packages/preview/circuiteria/0.1.0/README.md
  packages/preview/circuiteria/0.1.0/doc/example.typ
  packages/preview/circuiteria/0.1.0/doc/examples.typ
  packages/preview/circuiteria/0.1.0/gallery.bash
  packages/preview/circuiteria/0.1.0/gallery/platypus.pdf
  packages/preview/circuiteria/0.1.0/gallery/platypus.png
  packages/preview/circuiteria/0.1.0/gallery/platypus.typ
  packages/preview/circuiteria/0.1.0/gallery/test.pdf
  packages/preview/circuiteria/0.1.0/gallery/test.png
  packages/preview/circuiteria/0.1.0/gallery/test.typ
  packages/preview/circuiteria/0.1.0/gallery/test2.pdf
  packages/preview/circuiteria/0.1.0/gallery/test2.png
  packages/preview/circuiteria/0.1.0/gallery/test2.typ
  packages/preview/circuiteria/0.1.0/gallery/test3.pdf
  packages/preview/circuiteria/0.1.0/gallery/test3.png
  packages/preview/circuiteria/0.1.0/gallery/test3.typ
  packages/preview/circuiteria/0.1.0/gallery/test4.pdf
  packages/preview/circuiteria/0.1.0/gallery/test4.png
  packages/preview/circuiteria/0.1.0/gallery/test4.typ
  packages/preview/circuiteria/0.1.0/gallery/test5.pdf
  packages/preview/circuiteria/0.1.0/gallery/test5.png
  packages/preview/circuiteria/0.1.0/gallery/test5.typ
  packages/preview/circuiteria/0.1.0/gallery/test6.pdf
  packages/preview/circuiteria/0.1.0/gallery/test6.png
  packages/preview/circuiteria/0.1.0/gallery/test6.typ
  packages/preview/circuiteria/0.1.0/gallery/test7.json
  packages/preview/circuiteria/0.1.0/manual.pdf
  packages/preview/circuiteria/0.1.0/manual.typ
  packages/preview/circuiteria/0.1.0/src/circuit.typ
  packages/preview/circuiteria/0.1.0/src/element.typ
  packages/preview/circuiteria/0.1.0/src/elements/alu.typ
  packages/preview/circuiteria/0.1.0/src/elements/block.typ
  packages/preview/circuiteria/0.1.0/src/elements/element.typ
  packages/preview/circuiteria/0.1.0/src/elements/extender.typ
  packages/preview/circuiteria/0.1.0/src/elements/group.typ
  packages/preview/circuiteria/0.1.0/src/elements/logic/and.typ
  packages/preview/circuiteria/0.1.0/src/elements/logic/buf.typ
  packages/preview/circuiteria/0.1.0/src/elements/logic/gate.typ
  packages/preview/circuiteria/0.1.0/src/elements/logic/or.typ
  packages/preview/circuiteria/0.1.0/src/elements/logic/xor.typ
  packages/preview/circuiteria/0.1.0/src/elements/multiplexer.typ
  packages/preview/circuiteria/0.1.0/src/elements/ports.typ
  packages/preview/circuiteria/0.1.0/src/gates.typ
  packages/preview/circuiteria/0.1.0/src/lib.typ
  packages/preview/circuiteria/0.1.0/src/util.typ
  packages/preview/circuiteria/0.1.0/src/wire.typ
  packages/preview/circuiteria/0.1.0/typst.toml
Labels: new

#1035 zero:0.2.0
  packages/preview/zero/0.2.0/LICENSE
  packages/preview/zero/0.2.0/README.md
  packages/preview/zero/0.2.0/src/assertations.typ
  packages/preview/zero/0.2.0/src/formatting.typ
  packages/preview/zero/0.2.0/src/impl.typ
  packages/preview/zero/0.2.0/src/num.typ
  packages/preview/zero/0.2.0/src/parsing.typ
  packages/preview/zero/0.2.0/src/rounding.typ
  packages/preview/zero/0.2.0/src/state.typ
  packages/preview/zero/0.2.0/src/utility.typ
  packages/preview/zero/0.2.0/src/zero.typ
  packages/preview/zero/0.2.0/src/ztable.typ
  packages/preview/zero/0.2.0/typst.toml
Labels: update

#1024 modern-report-umfds:0.1.0
  packages/preview/modern-report-umfds/0.1.0/LICENSE
  packages/preview/modern-report-umfds/0.1.0/README.md
  packages/preview/modern-report-umfds/0.1.0/src/assets/fds.png
  packages/preview/modern-report-umfds/0.1.0/src/assets/um.png
  packages/preview/modern-report-umfds/0.1.0/src/lib.typ
  packages/preview/modern-report-umfds/0.1.0/template/main.typ
  packages/preview/modern-report-umfds/0.1.0/template/refs.bib
  packages/preview/modern-report-umfds/0.1.0/thumbnail.png
  packages/preview/modern-report-umfds/0.1.0/typst.toml
Labels: new

#1044 basic-resume:0.1.2
  packages/preview/basic-resume/0.1.2/.devcontainer/devcontainer.json
  packages/preview/basic-resume/0.1.2/CHANGELOG.md
  packages/preview/basic-resume/0.1.2/LICENSE
  packages/preview/basic-resume/0.1.2/README.md
  packages/preview/basic-resume/0.1.2/docs/manual.pdf
  packages/preview/basic-resume/0.1.2/src/lib.typ
  packages/preview/basic-resume/0.1.2/src/resume.typ
  packages/preview/basic-resume/0.1.2/template/main.typ
  packages/preview/basic-resume/0.1.2/thumbnail.png
  packages/preview/basic-resume/0.1.2/typst.toml
Labels: update

#1046 basalt-backlinks:0.1.0
  packages/preview/basalt-backlinks/0.1.0/LICENSE
  packages/preview/basalt-backlinks/0.1.0/README.md
  packages/preview/basalt-backlinks/0.1.0/src/backlinks.typ
  packages/preview/basalt-backlinks/0.1.0/src/exports.typ
  packages/preview/basalt-backlinks/0.1.0/typst.toml
Labels: new

#1038 not-jku-thesis:0.1.0
  packages/preview/not-jku-thesis/0.1.0/JKU.png
  packages/preview/not-jku-thesis/0.1.0/LICENSE
  packages/preview/not-jku-thesis/0.1.0/README.md
  packages/preview/not-jku-thesis/0.1.0/abstract.typ
  packages/preview/not-jku-thesis/0.1.0/acknowledgement.typ
  packages/preview/not-jku-thesis/0.1.0/big_K.png
  packages/preview/not-jku-thesis/0.1.0/disclaimer.typ
  packages/preview/not-jku-thesis/0.1.0/template.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/Analysis.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/Appendix.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/Conclusion.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/DataCollection.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/Introduction.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/LiteratureReview.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/Methodology.typ
  packages/preview/not-jku-thesis/0.1.0/template/content/Tutorial.typ
  packages/preview/not-jku-thesis/0.1.0/template/glossary.typ
  packages/preview/not-jku-thesis/0.1.0/template/images/Calcipher.jpg
  packages/preview/not-jku-thesis/0.1.0/template/images/JamesBond.jpg
  packages/preview/not-jku-thesis/0.1.0/template/images/Mei.jpg
  packages/preview/not-jku-thesis/0.1.0/template/images/MissMoneypenny.jpg
  packages/preview/not-jku-thesis/0.1.0/template/items.bib
  packages/preview/not-jku-thesis/0.1.0/template/thesis.typ
  packages/preview/not-jku-thesis/0.1.0/template/utils.typ
  packages/preview/not-jku-thesis/0.1.0/thumbnail.png
  packages/preview/not-jku-thesis/0.1.0/titlepage.typ
  packages/preview/not-jku-thesis/0.1.0/typst.toml
Labels: new

#1047 grotesk-cv:0.1.2
  packages/preview/grotesk-cv/0.1.2/LICENSE
  packages/preview/grotesk-cv/0.1.2/README.md
  packages/preview/grotesk-cv/0.1.2/lib.typ
  packages/preview/grotesk-cv/0.1.2/template/content/education.typ
  packages/preview/grotesk-cv/0.1.2/template/content/experience.typ
  packages/preview/grotesk-cv/0.1.2/template/content/languages.typ
  packages/preview/grotesk-cv/0.1.2/template/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.2/template/content/personal.typ
  packages/preview/grotesk-cv/0.1.2/template/content/profile.typ
  packages/preview/grotesk-cv/0.1.2/template/content/references.typ
  packages/preview/grotesk-cv/0.1.2/template/content/skills.typ
  packages/preview/grotesk-cv/0.1.2/template/cover.typ
  packages/preview/grotesk-cv/0.1.2/template/cv.typ
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.2/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.2/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.2/template/info.toml
  packages/preview/grotesk-cv/0.1.2/thumbnail.png
  packages/preview/grotesk-cv/0.1.2/typst.toml
Labels: update

#1049 titleize:0.1.0
  packages/preview/titleize/0.1.0/LICENSE
  packages/preview/titleize/0.1.0/README.md
  packages/preview/titleize/0.1.0/example.png
  packages/preview/titleize/0.1.0/lib.typ
  packages/preview/titleize/0.1.0/titleize.wasm
  packages/preview/titleize/0.1.0/typst.toml
Labels: new

#1045 glossarium:0.4.2
  packages/preview/glossarium/0.4.2/CHANGELOG.md
  packages/preview/glossarium/0.4.2/LICENSE
  packages/preview/glossarium/0.4.2/README.md
  packages/preview/glossarium/0.4.2/glossarium.typ
  packages/preview/glossarium/0.4.2/themes/default.typ
  packages/preview/glossarium/0.4.2/typst.toml
Labels: update

#1051 grotesk-cv:0.1.3
  packages/preview/grotesk-cv/0.1.3/LICENSE
  packages/preview/grotesk-cv/0.1.3/README.md
  packages/preview/grotesk-cv/0.1.3/lib.typ
  packages/preview/grotesk-cv/0.1.3/template/content/education.typ
  packages/preview/grotesk-cv/0.1.3/template/content/experience.typ
  packages/preview/grotesk-cv/0.1.3/template/content/languages.typ
  packages/preview/grotesk-cv/0.1.3/template/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.3/template/content/personal.typ
  packages/preview/grotesk-cv/0.1.3/template/content/profile.typ
  packages/preview/grotesk-cv/0.1.3/template/content/references.typ
  packages/preview/grotesk-cv/0.1.3/template/content/skills.typ
  packages/preview/grotesk-cv/0.1.3/template/cover.typ
  packages/preview/grotesk-cv/0.1.3/template/cv.typ
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.3/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.3/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.3/template/info.toml
  packages/preview/grotesk-cv/0.1.3/thumbnail.png
  packages/preview/grotesk-cv/0.1.3/typst.toml
Labels: update

#1048 resume-ng:1.0.0
  packages/preview/resume-ng/1.0.0/LICENSE
  packages/preview/resume-ng/1.0.0/README.md
  packages/preview/resume-ng/1.0.0/lib/lib.typ
  packages/preview/resume-ng/1.0.0/template/main.typ
  packages/preview/resume-ng/1.0.0/thumbnail.png
  packages/preview/resume-ng/1.0.0/typst.toml
Labels: new

#1053 bloated-neurips:0.5.1
  packages/preview/bloated-neurips/0.5.1/LICENSE
  packages/preview/bloated-neurips/0.5.1/README.md
  packages/preview/bloated-neurips/0.5.1/neurips.typ
  packages/preview/bloated-neurips/0.5.1/neurips2023.typ
  packages/preview/bloated-neurips/0.5.1/neurips2024.typ
  packages/preview/bloated-neurips/0.5.1/template/appendix.typ
  packages/preview/bloated-neurips/0.5.1/template/checklist.typ
  packages/preview/bloated-neurips/0.5.1/template/logo.typ
  packages/preview/bloated-neurips/0.5.1/template/main.bib
  packages/preview/bloated-neurips/0.5.1/template/main.typ
  packages/preview/bloated-neurips/0.5.1/thumbnail.png
  packages/preview/bloated-neurips/0.5.1/typst.toml
Labels: update

#1058 vantage-cv:1.0.0
  packages/preview/vantage-cv/1.0.0/LICENSE
  packages/preview/vantage-cv/1.0.0/README.md
  packages/preview/vantage-cv/1.0.0/icons/calendar.svg
  packages/preview/vantage-cv/1.0.0/icons/email.svg
  packages/preview/vantage-cv/1.0.0/icons/github.svg
  packages/preview/vantage-cv/1.0.0/icons/linkedin.svg
  packages/preview/vantage-cv/1.0.0/icons/location.svg
  packages/preview/vantage-cv/1.0.0/icons/website.svg
  packages/preview/vantage-cv/1.0.0/lib.typ
  packages/preview/vantage-cv/1.0.0/template/configuration.yaml
  packages/preview/vantage-cv/1.0.0/template/main.typ
  packages/preview/vantage-cv/1.0.0/thumbnail.png
  packages/preview/vantage-cv/1.0.0/typst.toml
Labels: new

#1052 tutor:0.6.1 and tutor:0.7.0
  packages/preview/tutor/0.6.1/LICENSE
  packages/preview/tutor/0.6.1/README.md
  packages/preview/tutor/0.6.1/lib.typ
  packages/preview/tutor/0.6.1/typst.toml
  packages/preview/tutor/0.7.0/LICENSE
  packages/preview/tutor/0.7.0/README.md
  packages/preview/tutor/0.7.0/lib.typ
  packages/preview/tutor/0.7.0/typst.toml
Labels: update

#1040 enunciado-facil-fcfm:0.1.0
  packages/preview/enunciado-facil-fcfm/0.1.0/LICENSE
  packages/preview/enunciado-facil-fcfm/0.1.0/README.md
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/departamentos.typ
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/enunciado-facil-fcfm.typ
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/adh.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/das.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dcc.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dcc2.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dfi.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dgf.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dic.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/die.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dii.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dim.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dimec.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/dimin.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/diqbm.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/lib/logos/geo.svg
  packages/preview/enunciado-facil-fcfm/0.1.0/template/main.typ
  packages/preview/enunciado-facil-fcfm/0.1.0/thumbnail.png
  packages/preview/enunciado-facil-fcfm/0.1.0/typst.toml
Labels: new

#1057 grotesk-cv:0.1.4
  packages/preview/grotesk-cv/0.1.4/LICENSE
  packages/preview/grotesk-cv/0.1.4/README.md
  packages/preview/grotesk-cv/0.1.4/lib.typ
  packages/preview/grotesk-cv/0.1.4/template/content/education.typ
  packages/preview/grotesk-cv/0.1.4/template/content/experience.typ
  packages/preview/grotesk-cv/0.1.4/template/content/languages.typ
  packages/preview/grotesk-cv/0.1.4/template/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.4/template/content/personal.typ
  packages/preview/grotesk-cv/0.1.4/template/content/profile.typ
  packages/preview/grotesk-cv/0.1.4/template/content/references.typ
  packages/preview/grotesk-cv/0.1.4/template/content/skills.typ
  packages/preview/grotesk-cv/0.1.4/template/cover.typ
  packages/preview/grotesk-cv/0.1.4/template/cv.typ
  packages/preview/grotesk-cv/0.1.4/template/font/Font Awesome 6 Brands-Regular-400.otf
  packages/preview/grotesk-cv/0.1.4/template/font/Font Awesome 6 Free-Regular-400.otf
  packages/preview/grotesk-cv/0.1.4/template/font/Font Awesome 6 Free-Solid-900.otf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.4/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.4/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.4/template/info.toml
  packages/preview/grotesk-cv/0.1.4/thumbnail.png
  packages/preview/grotesk-cv/0.1.4/typst.toml
Labels: update

#1055 haw-hamburg:0.2.0
  packages/preview/haw-hamburg/0.2.0/.gitignore
  packages/preview/haw-hamburg/0.2.0/CHANGELOG.md
  packages/preview/haw-hamburg/0.2.0/LICENSE
  packages/preview/haw-hamburg/0.2.0/README.md
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/abbreviations.typ
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/bibliography.bib
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/chapters/01_preamble.typ
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/chapters/02_articles.typ
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/dependencies.typ
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/glossary.typ
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/main.pdf
  packages/preview/haw-hamburg/0.2.0/examples/bachelor-thesis/main.typ
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/abbreviations.typ
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/bibliography.bib
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/chapters/01_preamble.typ
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/chapters/02_articles.typ
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/dependencies.typ
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/glossary.typ
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/main.pdf
  packages/preview/haw-hamburg/0.2.0/examples/master-thesis/main.typ
  packages/preview/haw-hamburg/0.2.0/examples/report/abbreviations.typ
  packages/preview/haw-hamburg/0.2.0/examples/report/bibliography.bib
  packages/preview/haw-hamburg/0.2.0/examples/report/chapters/01_preamble.typ
  packages/preview/haw-hamburg/0.2.0/examples/report/chapters/02_articles.typ
  packages/preview/haw-hamburg/0.2.0/examples/report/dependencies.typ
  packages/preview/haw-hamburg/0.2.0/examples/report/glossary.typ
  packages/preview/haw-hamburg/0.2.0/examples/report/main.pdf
  packages/preview/haw-hamburg/0.2.0/examples/report/main.typ
  packages/preview/haw-hamburg/0.2.0/src/assets/ieeetran.csl
  packages/preview/haw-hamburg/0.2.0/src/assets/logo.svg
  packages/preview/haw-hamburg/0.2.0/src/lib.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/abstract.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/cover.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/declaration_of_independent_processing.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/list_of_figures.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/list_of_tables.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/listings.typ
  packages/preview/haw-hamburg/0.2.0/src/pages/outline.typ
  packages/preview/haw-hamburg/0.2.0/src/template.typ
  packages/preview/haw-hamburg/0.2.0/src/translations.typ
  packages/preview/haw-hamburg/0.2.0/template/abbreviations.typ
  packages/preview/haw-hamburg/0.2.0/template/bibliography.bib
  packages/preview/haw-hamburg/0.2.0/template/chapters/01_introduction.typ
  packages/preview/haw-hamburg/0.2.0/template/chapters/02_background.typ
  packages/preview/haw-hamburg/0.2.0/template/dependencies.typ
  packages/preview/haw-hamburg/0.2.0/template/glossary.typ
  packages/preview/haw-hamburg/0.2.0/template/ieeetran.csl
  packages/preview/haw-hamburg/0.2.0/template/main.typ
  packages/preview/haw-hamburg/0.2.0/thumbnail.png
  packages/preview/haw-hamburg/0.2.0/typst.toml
Labels: update

#1056 touying-brandred-uobristol:0.1.1
  packages/preview/touying-brandred-uobristol/0.1.1/LICENSE
  packages/preview/touying-brandred-uobristol/0.1.1/README.md
  packages/preview/touying-brandred-uobristol/0.1.1/examples/example.pdf
  packages/preview/touying-brandred-uobristol/0.1.1/examples/example.typ
  packages/preview/touying-brandred-uobristol/0.1.1/lib.typ
  packages/preview/touying-brandred-uobristol/0.1.1/template/main.typ
  packages/preview/touying-brandred-uobristol/0.1.1/thumbnail.png
  packages/preview/touying-brandred-uobristol/0.1.1/typst.toml
  packages/preview/touying-brandred-uobristol/0.1.1/uob-bullet.svg
  packages/preview/touying-brandred-uobristol/0.1.1/uob-logo.svg
Labels: update

#1065 grayness:0.2.0
  packages/preview/grayness/0.2.0/Arturo_Nieto-Dorantes.webp
  packages/preview/grayness/0.2.0/CHANGELOG.md
  packages/preview/grayness/0.2.0/LICENSE
  packages/preview/grayness/0.2.0/README.md
  packages/preview/grayness/0.2.0/example.png
  packages/preview/grayness/0.2.0/example.typ
  packages/preview/grayness/0.2.0/grayness.wasm
  packages/preview/grayness/0.2.0/lib.typ
  packages/preview/grayness/0.2.0/manual.pdf
  packages/preview/grayness/0.2.0/manual.typ
  packages/preview/grayness/0.2.0/typst.toml
Labels: update

#1062 bookletic:0.3.0
  packages/preview/bookletic/0.3.0/LICENSE
  packages/preview/bookletic/0.3.0/README.md
  packages/preview/bookletic/0.3.0/example/basic.png
  packages/preview/bookletic/0.3.0/example/example.pdf
  packages/preview/bookletic/0.3.0/example/example.typ
  packages/preview/bookletic/0.3.0/example/fancy.png
  packages/preview/bookletic/0.3.0/src/lib.typ
  packages/preview/bookletic/0.3.0/typst.toml
Labels: update

#1067 grotesk-cv:0.1.5
  packages/preview/grotesk-cv/0.1.5/LICENSE
  packages/preview/grotesk-cv/0.1.5/README.md
  packages/preview/grotesk-cv/0.1.5/lib.typ
  packages/preview/grotesk-cv/0.1.5/template/content/education.typ
  packages/preview/grotesk-cv/0.1.5/template/content/experience.typ
  packages/preview/grotesk-cv/0.1.5/template/content/languages.typ
  packages/preview/grotesk-cv/0.1.5/template/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.5/template/content/personal.typ
  packages/preview/grotesk-cv/0.1.5/template/content/profile.typ
  packages/preview/grotesk-cv/0.1.5/template/content/references.typ
  packages/preview/grotesk-cv/0.1.5/template/content/skills.typ
  packages/preview/grotesk-cv/0.1.5/template/cover.typ
  packages/preview/grotesk-cv/0.1.5/template/cv.typ
  packages/preview/grotesk-cv/0.1.5/template/font/Font Awesome 6 Brands-Regular-400.otf
  packages/preview/grotesk-cv/0.1.5/template/font/Font Awesome 6 Free-Regular-400.otf
  packages/preview/grotesk-cv/0.1.5/template/font/Font Awesome 6 Free-Solid-900.otf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.5/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.5/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.5/template/info.toml
  packages/preview/grotesk-cv/0.1.5/thumbnail.png
  packages/preview/grotesk-cv/0.1.5/typst.toml
Labels: update

#1061 brilliant-cv:2.0.3
  packages/preview/brilliant-cv/2.0.3/LICENSE
  packages/preview/brilliant-cv/2.0.3/README.md
  packages/preview/brilliant-cv/2.0.3/cv.typ
  packages/preview/brilliant-cv/2.0.3/docs/docs-template.typ
  packages/preview/brilliant-cv/2.0.3/docs/docs.typ
  packages/preview/brilliant-cv/2.0.3/letter.typ
  packages/preview/brilliant-cv/2.0.3/lib.typ
  packages/preview/brilliant-cv/2.0.3/metadata.toml.schema.json
  packages/preview/brilliant-cv/2.0.3/template/cv.typ
  packages/preview/brilliant-cv/2.0.3/template/letter.typ
  packages/preview/brilliant-cv/2.0.3/template/metadata.toml
  packages/preview/brilliant-cv/2.0.3/template/modules_en/certificates.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_en/education.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_en/professional.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_en/projects.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_en/publications.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_en/skills.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_fr/certificates.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_fr/education.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_fr/professional.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_fr/projects.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_fr/publications.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_fr/skills.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_zh/certificates.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_zh/education.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_zh/professional.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_zh/projects.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_zh/publications.typ
  packages/preview/brilliant-cv/2.0.3/template/modules_zh/skills.typ
  packages/preview/brilliant-cv/2.0.3/template/src/avatar.png
  packages/preview/brilliant-cv/2.0.3/template/src/logos/abc_company.png
  packages/preview/brilliant-cv/2.0.3/template/src/logos/pqr_corp.png
  packages/preview/brilliant-cv/2.0.3/template/src/logos/ucla.png
  packages/preview/brilliant-cv/2.0.3/template/src/logos/xyz_corp.png
  packages/preview/brilliant-cv/2.0.3/template/src/publications.bib
  packages/preview/brilliant-cv/2.0.3/template/src/signature.png
  packages/preview/brilliant-cv/2.0.3/thumbnail.png
  packages/preview/brilliant-cv/2.0.3/typst.toml
  packages/preview/brilliant-cv/2.0.3/utils/injection.typ
  packages/preview/brilliant-cv/2.0.3/utils/lang.typ
  packages/preview/brilliant-cv/2.0.3/utils/styles.typ
Labels: update

#1054 tud-corporate-design-slides:0.1.0
  packages/preview/tud-corporate-design-slides/0.1.0/LICENSE
  packages/preview/tud-corporate-design-slides/0.1.0/README.md
  packages/preview/tud-corporate-design-slides/0.1.0/lib.typ
  packages/preview/tud-corporate-design-slides/0.1.0/template/main.typ
  packages/preview/tud-corporate-design-slides/0.1.0/thumbnail.png
  packages/preview/tud-corporate-design-slides/0.1.0/tud-slides/logos/TU_Dresden_Logo_blau.svg
  packages/preview/tud-corporate-design-slides/0.1.0/tud-slides/logos/TU_Dresden_Logo_weiss.svg
  packages/preview/tud-corporate-design-slides/0.1.0/tud-slides/logos/dresden-concept.svg
  packages/preview/tud-corporate-design-slides/0.1.0/tud-slides/template.typ
  packages/preview/tud-corporate-design-slides/0.1.0/typst.toml
Labels: new

#1060 tgm-hit-protocol:0.1.0
  packages/preview/tgm-hit-protocol/0.1.0/.gitignore
  packages/preview/tgm-hit-protocol/0.1.0/LICENSE
  packages/preview/tgm-hit-protocol/0.1.0/Makefile
  packages/preview/tgm-hit-protocol/0.1.0/README.md
  packages/preview/tgm-hit-protocol/0.1.0/docs/manual.pdf
  packages/preview/tgm-hit-protocol/0.1.0/example.pdf
  packages/preview/tgm-hit-protocol/0.1.0/src/assets/logo-left.png
  packages/preview/tgm-hit-protocol/0.1.0/src/assets/logo-right.png
  packages/preview/tgm-hit-protocol/0.1.0/src/assets/mod.typ
  packages/preview/tgm-hit-protocol/0.1.0/src/glossary.typ
  packages/preview/tgm-hit-protocol/0.1.0/src/l10n.toml
  packages/preview/tgm-hit-protocol/0.1.0/src/l10n.typ
  packages/preview/tgm-hit-protocol/0.1.0/src/lib.typ
  packages/preview/tgm-hit-protocol/0.1.0/template/assets/just-do-it.png
  packages/preview/tgm-hit-protocol/0.1.0/template/assets/mod.typ
  packages/preview/tgm-hit-protocol/0.1.0/template/bibliography.bib
  packages/preview/tgm-hit-protocol/0.1.0/template/glossaries.typ
  packages/preview/tgm-hit-protocol/0.1.0/template/main.typ
  packages/preview/tgm-hit-protocol/0.1.0/thumbnail.png
  packages/preview/tgm-hit-protocol/0.1.0/typst.toml
Labels: new

#1070 grotesk-cv:0.1.6
  packages/preview/grotesk-cv/0.1.6/LICENSE
  packages/preview/grotesk-cv/0.1.6/README.md
  packages/preview/grotesk-cv/0.1.6/lib.typ
  packages/preview/grotesk-cv/0.1.6/template/content/education.typ
  packages/preview/grotesk-cv/0.1.6/template/content/experience.typ
  packages/preview/grotesk-cv/0.1.6/template/content/languages.typ
  packages/preview/grotesk-cv/0.1.6/template/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.6/template/content/personal.typ
  packages/preview/grotesk-cv/0.1.6/template/content/profile.typ
  packages/preview/grotesk-cv/0.1.6/template/content/references.typ
  packages/preview/grotesk-cv/0.1.6/template/content/skills.typ
  packages/preview/grotesk-cv/0.1.6/template/cover.typ
  packages/preview/grotesk-cv/0.1.6/template/cv.typ
  packages/preview/grotesk-cv/0.1.6/template/font/Font Awesome 6 Brands-Regular-400.otf
  packages/preview/grotesk-cv/0.1.6/template/font/Font Awesome 6 Free-Regular-400.otf
  packages/preview/grotesk-cv/0.1.6/template/font/Font Awesome 6 Free-Solid-900.otf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.6/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.6/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.6/template/info.toml
  packages/preview/grotesk-cv/0.1.6/thumbnail.png
  packages/preview/grotesk-cv/0.1.6/typst.toml
Labels: update

#1073 ez-today:0.1.0
  packages/preview/ez-today/0.1.0/LICENSE
  packages/preview/ez-today/0.1.0/README.md
  packages/preview/ez-today/0.1.0/examples/example.typ
  packages/preview/ez-today/0.1.0/ez-today.typ
  packages/preview/ez-today/0.1.0/typst.toml
Labels: new

#1081 cheq:0.2.1
  packages/preview/cheq/0.2.1/LICENSE
  packages/preview/cheq/0.2.1/README.md
  packages/preview/cheq/0.2.1/examples/custom-styles.png
  packages/preview/cheq/0.2.1/examples/custom-styles.typ
  packages/preview/cheq/0.2.1/examples/example.png
  packages/preview/cheq/0.2.1/examples/example.typ
  packages/preview/cheq/0.2.1/lib.typ
  packages/preview/cheq/0.2.1/typst.toml
Labels: update

#1079 tgm-hit-protocol:0.1.0 (README fix)
  packages/preview/tgm-hit-protocol/0.1.0/README.md
Labels: new

#1080 modern-report-umfds:0.1.1
  packages/preview/modern-report-umfds/0.1.1/LICENSE
  packages/preview/modern-report-umfds/0.1.1/README.md
  packages/preview/modern-report-umfds/0.1.1/src/assets/fds.png
  packages/preview/modern-report-umfds/0.1.1/src/assets/um.png
  packages/preview/modern-report-umfds/0.1.1/src/lib.typ
  packages/preview/modern-report-umfds/0.1.1/template/main.typ
  packages/preview/modern-report-umfds/0.1.1/template/refs.bib
  packages/preview/modern-report-umfds/0.1.1/thumbnail.png
  packages/preview/modern-report-umfds/0.1.1/typst.toml
Labels: update

#1075 rich-counters:0.2.0
  packages/preview/rich-counters/0.2.0/LICENSE
  packages/preview/rich-counters/0.2.0/README.md
  packages/preview/rich-counters/0.2.0/example.png
  packages/preview/rich-counters/0.2.0/example.typ
  packages/preview/rich-counters/0.2.0/lib.typ
  packages/preview/rich-counters/0.2.0/typst.toml
Labels: update

#1084 vartable:0.1.1
  packages/preview/vartable/0.1.1/LICENSE
  packages/preview/vartable/0.1.1/README.md
  packages/preview/vartable/0.1.1/documentation.pdf
  packages/preview/vartable/0.1.1/documentation.typ
  packages/preview/vartable/0.1.1/examples/bug1.pdf
  packages/preview/vartable/0.1.1/examples/bug1.png
  packages/preview/vartable/0.1.1/examples/bug1.typ
  packages/preview/vartable/0.1.1/examples/hyperbolicFuntion.pdf
  packages/preview/vartable/0.1.1/examples/hyperbolicFuntion.png
  packages/preview/vartable/0.1.1/examples/hyperbolicFuntion.typ
  packages/preview/vartable/0.1.1/examples/trigonometricFunction.pdf
  packages/preview/vartable/0.1.1/examples/trigonometricFunction.png
  packages/preview/vartable/0.1.1/examples/trigonometricFunction.typ
  packages/preview/vartable/0.1.1/tabvar.typ
  packages/preview/vartable/0.1.1/typst.toml
Labels: update

#1085 minerva-report-fcfm:0.2.1
  packages/preview/minerva-report-fcfm/0.2.1/CHANGELOG.md
  packages/preview/minerva-report-fcfm/0.2.1/LICENSE
  packages/preview/minerva-report-fcfm/0.2.1/README.md
  packages/preview/minerva-report-fcfm/0.2.1/departamentos.typ
  packages/preview/minerva-report-fcfm/0.2.1/logos/adh.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/das.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dcc.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dfi.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dgf.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dic.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/die.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dii.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dim.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dimec.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/dimin.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/diqbm.svg
  packages/preview/minerva-report-fcfm/0.2.1/logos/geo.svg
  packages/preview/minerva-report-fcfm/0.2.1/minerva-report-fcfm.typ
  packages/preview/minerva-report-fcfm/0.2.1/state.typ
  packages/preview/minerva-report-fcfm/0.2.1/template/images/README.md
  packages/preview/minerva-report-fcfm/0.2.1/template/main.typ
  packages/preview/minerva-report-fcfm/0.2.1/template/meta.typ
  packages/preview/minerva-report-fcfm/0.2.1/template/preamble.typ
  packages/preview/minerva-report-fcfm/0.2.1/thumbnail.png
  packages/preview/minerva-report-fcfm/0.2.1/typst.toml
Labels: update

#1074 haw-hamburg-bachelor-thesis:0.3.0, haw-hamburg-master-thesis:0.3.0, haw-hamburg-report:0.3.0 and haw-hamburg:0.3.0
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/LICENSE
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/README.md
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/lib.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/abbreviations.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/bibliography.bib
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/dependencies.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/glossary.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/ieeetran.csl
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/src/main.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/thumbnail.png
  packages/preview/haw-hamburg-bachelor-thesis/0.3.0/typst.toml
  packages/preview/haw-hamburg-master-thesis/0.3.0/LICENSE
  packages/preview/haw-hamburg-master-thesis/0.3.0/README.md
  packages/preview/haw-hamburg-master-thesis/0.3.0/lib.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/abbreviations.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/bibliography.bib
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/dependencies.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/glossary.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/ieeetran.csl
  packages/preview/haw-hamburg-master-thesis/0.3.0/src/main.typ
  packages/preview/haw-hamburg-master-thesis/0.3.0/thumbnail.png
  packages/preview/haw-hamburg-master-thesis/0.3.0/typst.toml
  packages/preview/haw-hamburg-report/0.3.0/LICENSE
  packages/preview/haw-hamburg-report/0.3.0/README.md
  packages/preview/haw-hamburg-report/0.3.0/lib.typ
  packages/preview/haw-hamburg-report/0.3.0/src/abbreviations.typ
  packages/preview/haw-hamburg-report/0.3.0/src/bibliography.bib
  packages/preview/haw-hamburg-report/0.3.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-report/0.3.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-report/0.3.0/src/dependencies.typ
  packages/preview/haw-hamburg-report/0.3.0/src/glossary.typ
  packages/preview/haw-hamburg-report/0.3.0/src/ieeetran.csl
  packages/preview/haw-hamburg-report/0.3.0/src/main.typ
  packages/preview/haw-hamburg-report/0.3.0/thumbnail.png
  packages/preview/haw-hamburg-report/0.3.0/typst.toml
  packages/preview/haw-hamburg/0.3.0/LICENSE
  packages/preview/haw-hamburg/0.3.0/README.md
  packages/preview/haw-hamburg/0.3.0/assets/ieeetran.csl
  packages/preview/haw-hamburg/0.3.0/assets/logo.svg
  packages/preview/haw-hamburg/0.3.0/lib.typ
  packages/preview/haw-hamburg/0.3.0/pages/abstract.typ
  packages/preview/haw-hamburg/0.3.0/pages/cover.typ
  packages/preview/haw-hamburg/0.3.0/pages/declaration_of_independent_processing.typ
  packages/preview/haw-hamburg/0.3.0/pages/list_of_figures.typ
  packages/preview/haw-hamburg/0.3.0/pages/list_of_tables.typ
  packages/preview/haw-hamburg/0.3.0/pages/listings.typ
  packages/preview/haw-hamburg/0.3.0/pages/outline.typ
  packages/preview/haw-hamburg/0.3.0/template.typ
  packages/preview/haw-hamburg/0.3.0/translations.typ
  packages/preview/haw-hamburg/0.3.0/typst.toml
Labels: new, update

#1077 glossarium:0.5.0
  packages/preview/glossarium/0.5.0/CHANGELOG.md
  packages/preview/glossarium/0.5.0/LICENSE
  packages/preview/glossarium/0.5.0/README.md
  packages/preview/glossarium/0.5.0/glossarium.typ
  packages/preview/glossarium/0.5.0/themes/default.typ
  packages/preview/glossarium/0.5.0/typst.toml
Labels: update

#1086 touying:0.5.3
  packages/preview/touying/0.5.3/.gitignore
  packages/preview/touying/0.5.3/LICENSE
  packages/preview/touying/0.5.3/README.md
  packages/preview/touying/0.5.3/changelog.md
  packages/preview/touying/0.5.3/examples/aqua-zh.typ
  packages/preview/touying/0.5.3/examples/aqua.typ
  packages/preview/touying/0.5.3/examples/default.typ
  packages/preview/touying/0.5.3/examples/dewdrop.typ
  packages/preview/touying/0.5.3/examples/example.typ
  packages/preview/touying/0.5.3/examples/metropolis.typ
  packages/preview/touying/0.5.3/examples/simple.typ
  packages/preview/touying/0.5.3/examples/stargazer.typ
  packages/preview/touying/0.5.3/examples/university.typ
  packages/preview/touying/0.5.3/lib.typ
  packages/preview/touying/0.5.3/logo.png
  packages/preview/touying/0.5.3/poster.png
  packages/preview/touying/0.5.3/src/components.typ
  packages/preview/touying/0.5.3/src/configs.typ
  packages/preview/touying/0.5.3/src/core.typ
  packages/preview/touying/0.5.3/src/exports.typ
  packages/preview/touying/0.5.3/src/magic.typ
  packages/preview/touying/0.5.3/src/pdfpc.typ
  packages/preview/touying/0.5.3/src/slides.typ
  packages/preview/touying/0.5.3/src/utils.typ
  packages/preview/touying/0.5.3/themes/aqua.typ
  packages/preview/touying/0.5.3/themes/default.typ
  packages/preview/touying/0.5.3/themes/dewdrop.typ
  packages/preview/touying/0.5.3/themes/metropolis.typ
  packages/preview/touying/0.5.3/themes/simple.typ
  packages/preview/touying/0.5.3/themes/stargazer.typ
  packages/preview/touying/0.5.3/themes/themes.typ
  packages/preview/touying/0.5.3/themes/university.typ
  packages/preview/touying/0.5.3/typst.toml
Labels: update

#1087 touying-aqua:0.5.3
  packages/preview/touying-aqua/0.5.3/README.md
  packages/preview/touying-aqua/0.5.3/lib.typ
  packages/preview/touying-aqua/0.5.3/template/main.typ
  packages/preview/touying-aqua/0.5.3/thumbnail.png
  packages/preview/touying-aqua/0.5.3/typst.toml
Labels: update

#1088 cram-snap:0.2.0
  packages/preview/cram-snap/0.2.0/LICENSE
  packages/preview/cram-snap/0.2.0/README.md
  packages/preview/cram-snap/0.2.0/lib.typ
  packages/preview/cram-snap/0.2.0/template/git-icon.svg
  packages/preview/cram-snap/0.2.0/template/main.typ
  packages/preview/cram-snap/0.2.0/thumbnail.png
  packages/preview/cram-snap/0.2.0/typst.toml
Labels: update

#1072 cetz:0.3.0
  packages/preview/cetz/0.3.0/LICENSE
  packages/preview/cetz/0.3.0/README.md
  packages/preview/cetz/0.3.0/gallery/karls-picture.png
  packages/preview/cetz/0.3.0/gallery/karls-picture.typ
  packages/preview/cetz/0.3.0/gallery/tree.png
  packages/preview/cetz/0.3.0/gallery/tree.typ
  packages/preview/cetz/0.3.0/gallery/waves.png
  packages/preview/cetz/0.3.0/gallery/waves.typ
  packages/preview/cetz/0.3.0/src/aabb.typ
  packages/preview/cetz/0.3.0/src/anchor.typ
  packages/preview/cetz/0.3.0/src/bezier.typ
  packages/preview/cetz/0.3.0/src/canvas.typ
  packages/preview/cetz/0.3.0/src/complex.typ
  packages/preview/cetz/0.3.0/src/coordinate.typ
  packages/preview/cetz/0.3.0/src/deps.typ
  packages/preview/cetz/0.3.0/src/draw.typ
  packages/preview/cetz/0.3.0/src/draw/grouping.typ
  packages/preview/cetz/0.3.0/src/draw/projection.typ
  packages/preview/cetz/0.3.0/src/draw/shapes.typ
  packages/preview/cetz/0.3.0/src/draw/styling.typ
  packages/preview/cetz/0.3.0/src/draw/transformations.typ
  packages/preview/cetz/0.3.0/src/draw/util.typ
  packages/preview/cetz/0.3.0/src/drawable.typ
  packages/preview/cetz/0.3.0/src/hobby.typ
  packages/preview/cetz/0.3.0/src/intersection.typ
  packages/preview/cetz/0.3.0/src/lib.typ
  packages/preview/cetz/0.3.0/src/lib/angle.typ
  packages/preview/cetz/0.3.0/src/lib/decorations.typ
  packages/preview/cetz/0.3.0/src/lib/decorations/brace.typ
  packages/preview/cetz/0.3.0/src/lib/decorations/path.typ
  packages/preview/cetz/0.3.0/src/lib/palette.typ
  packages/preview/cetz/0.3.0/src/lib/pin.typ
  packages/preview/cetz/0.3.0/src/lib/plot-stub.typ
  packages/preview/cetz/0.3.0/src/lib/tree.typ
  packages/preview/cetz/0.3.0/src/mark-shapes.typ
  packages/preview/cetz/0.3.0/src/mark.typ
  packages/preview/cetz/0.3.0/src/matrix.typ
  packages/preview/cetz/0.3.0/src/path-util.typ
  packages/preview/cetz/0.3.0/src/polygon.typ
  packages/preview/cetz/0.3.0/src/process.typ
  packages/preview/cetz/0.3.0/src/styles.typ
  packages/preview/cetz/0.3.0/src/util.typ
  packages/preview/cetz/0.3.0/src/vector.typ
  packages/preview/cetz/0.3.0/src/version.typ
  packages/preview/cetz/0.3.0/typst.toml
Labels: update

#1094 titleize:0.1.1
  packages/preview/titleize/0.1.1/LICENSE
  packages/preview/titleize/0.1.1/README.md
  packages/preview/titleize/0.1.1/example.png
  packages/preview/titleize/0.1.1/lib.typ
  packages/preview/titleize/0.1.1/titleize.wasm
  packages/preview/titleize/0.1.1/typst.toml
Labels: update

#1098 rich-counters:0.2.1
  packages/preview/rich-counters/0.2.1/LICENSE
  packages/preview/rich-counters/0.2.1/README.md
  packages/preview/rich-counters/0.2.1/example.png
  packages/preview/rich-counters/0.2.1/example.typ
  packages/preview/rich-counters/0.2.1/lib.typ
  packages/preview/rich-counters/0.2.1/typst.toml
Labels: update

#1071 fauxreilly:0.1.0
  packages/preview/fauxreilly/0.1.0/$$$-gimmie.svg
  packages/preview/fauxreilly/0.1.0/README.md
  packages/preview/fauxreilly/0.1.0/example.png
  packages/preview/fauxreilly/0.1.0/helpful mol.svg
  packages/preview/fauxreilly/0.1.0/lib.typ
  packages/preview/fauxreilly/0.1.0/typst.toml
Labels: new

#1097 quick-sip:0.1.0
  packages/preview/quick-sip/0.1.0/LICENSE
  packages/preview/quick-sip/0.1.0/README.md
  packages/preview/quick-sip/0.1.0/lib.typ
  packages/preview/quick-sip/0.1.0/template/main.typ
  packages/preview/quick-sip/0.1.0/thumbnail.png
  packages/preview/quick-sip/0.1.0/typst.toml
Labels: new

#1095 fruitify:0.1.1
  packages/preview/fruitify/0.1.1/LICENSE
  packages/preview/fruitify/0.1.1/README.md
  packages/preview/fruitify/0.1.1/fruitify.typ
  packages/preview/fruitify/0.1.1/typst.toml
  packages/preview/fruitify/0.1.1/xorshift_plugin.wasm
Labels: update

#1093 silky-slides-insa:0.1.0
  packages/preview/silky-slides-insa/0.1.0/README.md
  packages/preview/silky-slides-insa/0.1.0/assets/footer.png
  packages/preview/silky-slides-insa/0.1.0/assets/hdf/logo-white.png
  packages/preview/silky-slides-insa/0.1.0/assets/rennes/logo-white.png
  packages/preview/silky-slides-insa/0.1.0/assets/slide-section.svg
  packages/preview/silky-slides-insa/0.1.0/assets/slide-title-visual.svg
  packages/preview/silky-slides-insa/0.1.0/assets/slide-title.svg
  packages/preview/silky-slides-insa/0.1.0/slides-template.typ
  packages/preview/silky-slides-insa/0.1.0/template/main.typ
  packages/preview/silky-slides-insa/0.1.0/thumbnail-full.png
  packages/preview/silky-slides-insa/0.1.0/thumbnail.png
  packages/preview/silky-slides-insa/0.1.0/typst.toml
Labels: new

#1102 pinit:0.2.1
  packages/preview/pinit/0.2.1/LICENSE
  packages/preview/pinit/0.2.1/README.md
  packages/preview/pinit/0.2.1/examples/asymptotic.png
  packages/preview/pinit/0.2.1/examples/equation-desc.png
  packages/preview/pinit/0.2.1/examples/equation-desc.typ
  packages/preview/pinit/0.2.1/examples/example-pages.png
  packages/preview/pinit/0.2.1/examples/example.png
  packages/preview/pinit/0.2.1/examples/example.typ
  packages/preview/pinit/0.2.1/examples/fletcher.png
  packages/preview/pinit/0.2.1/examples/fletcher.typ
  packages/preview/pinit/0.2.1/examples/pinit-for-raw.png
  packages/preview/pinit/0.2.1/examples/pinit-for-raw.typ
  packages/preview/pinit/0.2.1/examples/simple-demo.png
  packages/preview/pinit/0.2.1/examples/simple-demo2.png
  packages/preview/pinit/0.2.1/lib.typ
  packages/preview/pinit/0.2.1/pinit-core.typ
  packages/preview/pinit/0.2.1/pinit-fletcher.typ
  packages/preview/pinit/0.2.1/simple-arrow.typ
  packages/preview/pinit/0.2.1/typst.toml
Labels: update

#1105 touying-unistra-pristine:1.1.0
  packages/preview/touying-unistra-pristine/1.1.0/CHANGELOG.md
  packages/preview/touying-unistra-pristine/1.1.0/LICENSE
  packages/preview/touying-unistra-pristine/1.1.0/README.md
  packages/preview/touying-unistra-pristine/1.1.0/assets/thumbnail.webp
  packages/preview/touying-unistra-pristine/1.1.0/assets/unistra.svg
  packages/preview/touying-unistra-pristine/1.1.0/src/admonition.typ
  packages/preview/touying-unistra-pristine/1.1.0/src/colors.typ
  packages/preview/touying-unistra-pristine/1.1.0/src/lib.typ
  packages/preview/touying-unistra-pristine/1.1.0/src/settings.typ
  packages/preview/touying-unistra-pristine/1.1.0/src/unistra.typ
  packages/preview/touying-unistra-pristine/1.1.0/template/template.typ
  packages/preview/touying-unistra-pristine/1.1.0/template/unistra.svg
  packages/preview/touying-unistra-pristine/1.1.0/typst.toml
Labels: update

#1089 timeliney:0.1.0
  packages/preview/timeliney/0.1.0/LICENSE
  packages/preview/timeliney/0.1.0/README.md
  packages/preview/timeliney/0.1.0/manual.pdf
  packages/preview/timeliney/0.1.0/manual.typ
  packages/preview/timeliney/0.1.0/sample.png
  packages/preview/timeliney/0.1.0/sample.typ
  packages/preview/timeliney/0.1.0/timeliney.typ
  packages/preview/timeliney/0.1.0/typst.toml
Labels: update

#1108 cheq:0.2.2
  packages/preview/cheq/0.2.2/LICENSE
  packages/preview/cheq/0.2.2/README.md
  packages/preview/cheq/0.2.2/examples/custom-styles.png
  packages/preview/cheq/0.2.2/examples/custom-styles.typ
  packages/preview/cheq/0.2.2/examples/example.png
  packages/preview/cheq/0.2.2/examples/example.typ
  packages/preview/cheq/0.2.2/lib.typ
  packages/preview/cheq/0.2.2/typst.toml
Labels: update

#1106 grotesk-cv:1.0.0
  packages/preview/grotesk-cv/1.0.0/CHANGELOG.md
  packages/preview/grotesk-cv/1.0.0/LICENSE
  packages/preview/grotesk-cv/1.0.0/README.md
  packages/preview/grotesk-cv/1.0.0/docs/manual.pdf
  packages/preview/grotesk-cv/1.0.0/src/lib.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/education.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/experience.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/languages.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/other_experience.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/personal.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/profile.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/references.typ
  packages/preview/grotesk-cv/1.0.0/src/template/content/skills.typ
  packages/preview/grotesk-cv/1.0.0/src/template/cover.typ
  packages/preview/grotesk-cv/1.0.0/src/template/cv.typ
  packages/preview/grotesk-cv/1.0.0/src/template/font/Font Awesome 6 Brands-Regular-400.otf
  packages/preview/grotesk-cv/1.0.0/src/template/font/Font Awesome 6 Free-Regular-400.otf
  packages/preview/grotesk-cv/1.0.0/src/template/font/Font Awesome 6 Free-Solid-900.otf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/1.0.0/src/template/img/portrait.png
  packages/preview/grotesk-cv/1.0.0/src/template/info.toml
  packages/preview/grotesk-cv/1.0.0/thumbnail.png
  packages/preview/grotesk-cv/1.0.0/typst.toml
Labels: update

#1109 pro-letter:0.1.0
  packages/preview/pro-letter/0.1.0/LICENSE
  packages/preview/pro-letter/0.1.0/README.md
  packages/preview/pro-letter/0.1.0/lib.typ
  packages/preview/pro-letter/0.1.0/template/main.typ
  packages/preview/pro-letter/0.1.0/thumbnail.png
  packages/preview/pro-letter/0.1.0/typst.toml
Labels: new

#1110 october:1.0.0
  packages/preview/october/1.0.0/LICENSE
  packages/preview/october/1.0.0/README.md
  packages/preview/october/1.0.0/calendar.typ
  packages/preview/october/1.0.0/template/main.typ
  packages/preview/october/1.0.0/thumbnail.png
  packages/preview/october/1.0.0/typst.toml
Labels: new

#1111 pro-letter:0.1.0
  packages/preview/pro-letter/0.1.0/typst.toml
Labels: new

#1113 mannot:0.1.0
  packages/preview/mannot/0.1.0/LICENSE
  packages/preview/mannot/0.1.0/README.md
  packages/preview/mannot/0.1.0/docs/doc-template.typ
  packages/preview/mannot/0.1.0/docs/doc.pdf
  packages/preview/mannot/0.1.0/docs/doc.typ
  packages/preview/mannot/0.1.0/docs/tidy-style.typ
  packages/preview/mannot/0.1.0/examples/showcase.svg
  packages/preview/mannot/0.1.0/examples/showcase.typ
  packages/preview/mannot/0.1.0/examples/usage1.svg
  packages/preview/mannot/0.1.0/examples/usage1.typ
  packages/preview/mannot/0.1.0/examples/usage2.svg
  packages/preview/mannot/0.1.0/examples/usage2.typ
  packages/preview/mannot/0.1.0/examples/usage3.svg
  packages/preview/mannot/0.1.0/examples/usage3.typ
  packages/preview/mannot/0.1.0/examples/usage4.svg
  packages/preview/mannot/0.1.0/examples/usage4.typ
  packages/preview/mannot/0.1.0/examples/usage5.svg
  packages/preview/mannot/0.1.0/examples/usage5.typ
  packages/preview/mannot/0.1.0/src/annot.typ
  packages/preview/mannot/0.1.0/src/lib.typ
  packages/preview/mannot/0.1.0/src/mark.typ
  packages/preview/mannot/0.1.0/src/util.typ
  packages/preview/mannot/0.1.0/typst.toml
Labels: new

#1114 scholarly-tauthesis:0.8.0
  packages/preview/scholarly-tauthesis/0.8.0/.gitattributes
  packages/preview/scholarly-tauthesis/0.8.0/.gitignore
  packages/preview/scholarly-tauthesis/0.8.0/LICENSE
  packages/preview/scholarly-tauthesis/0.8.0/README.md
  packages/preview/scholarly-tauthesis/0.8.0/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.8.0/template/code/README.md
  packages/preview/scholarly-tauthesis/0.8.0/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.8.0/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/README.md
  packages/preview/scholarly-tauthesis/0.8.0/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/images/README.md
  packages/preview/scholarly-tauthesis/0.8.0/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.8.0/template/main.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/meta.typ
  packages/preview/scholarly-tauthesis/0.8.0/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.8.0/thumbnail.png
  packages/preview/scholarly-tauthesis/0.8.0/typst.toml
Labels: update

#1116 gridlock:0.2.0
  packages/preview/gridlock/0.2.0/CHANGELOG.md
  packages/preview/gridlock/0.2.0/LICENSE
  packages/preview/gridlock/0.2.0/README.md
  packages/preview/gridlock/0.2.0/docs/gridlock-manual.pdf
  packages/preview/gridlock/0.2.0/src/lib.typ
  packages/preview/gridlock/0.2.0/typst.toml
Labels: update

#1117 cetz:0.3.1
  packages/preview/cetz/0.3.1/LICENSE
  packages/preview/cetz/0.3.1/README.md
  packages/preview/cetz/0.3.1/gallery/karls-picture.png
  packages/preview/cetz/0.3.1/gallery/karls-picture.typ
  packages/preview/cetz/0.3.1/gallery/tree.png
  packages/preview/cetz/0.3.1/gallery/tree.typ
  packages/preview/cetz/0.3.1/gallery/waves.png
  packages/preview/cetz/0.3.1/gallery/waves.typ
  packages/preview/cetz/0.3.1/src/aabb.typ
  packages/preview/cetz/0.3.1/src/anchor.typ
  packages/preview/cetz/0.3.1/src/bezier.typ
  packages/preview/cetz/0.3.1/src/canvas.typ
  packages/preview/cetz/0.3.1/src/complex.typ
  packages/preview/cetz/0.3.1/src/coordinate.typ
  packages/preview/cetz/0.3.1/src/deps.typ
  packages/preview/cetz/0.3.1/src/draw.typ
  packages/preview/cetz/0.3.1/src/draw/grouping.typ
  packages/preview/cetz/0.3.1/src/draw/projection.typ
  packages/preview/cetz/0.3.1/src/draw/shapes.typ
  packages/preview/cetz/0.3.1/src/draw/styling.typ
  packages/preview/cetz/0.3.1/src/draw/transformations.typ
  packages/preview/cetz/0.3.1/src/draw/util.typ
  packages/preview/cetz/0.3.1/src/drawable.typ
  packages/preview/cetz/0.3.1/src/hobby.typ
  packages/preview/cetz/0.3.1/src/intersection.typ
  packages/preview/cetz/0.3.1/src/lib.typ
  packages/preview/cetz/0.3.1/src/lib/angle.typ
  packages/preview/cetz/0.3.1/src/lib/decorations.typ
  packages/preview/cetz/0.3.1/src/lib/decorations/brace.typ
  packages/preview/cetz/0.3.1/src/lib/decorations/path.typ
  packages/preview/cetz/0.3.1/src/lib/palette.typ
  packages/preview/cetz/0.3.1/src/lib/pin.typ
  packages/preview/cetz/0.3.1/src/lib/plot-stub.typ
  packages/preview/cetz/0.3.1/src/lib/tree.typ
  packages/preview/cetz/0.3.1/src/mark-shapes.typ
  packages/preview/cetz/0.3.1/src/mark.typ
  packages/preview/cetz/0.3.1/src/matrix.typ
  packages/preview/cetz/0.3.1/src/path-util.typ
  packages/preview/cetz/0.3.1/src/polygon.typ
  packages/preview/cetz/0.3.1/src/process.typ
  packages/preview/cetz/0.3.1/src/styles.typ
  packages/preview/cetz/0.3.1/src/util.typ
  packages/preview/cetz/0.3.1/src/vector.typ
  packages/preview/cetz/0.3.1/src/version.typ
  packages/preview/cetz/0.3.1/typst.toml
Labels: update

#1118 cetz-plot:0.1.0
  packages/preview/cetz-plot/0.1.0/LICENSE
  packages/preview/cetz-plot/0.1.0/README.md
  packages/preview/cetz-plot/0.1.0/gallery/.gitkeep
  packages/preview/cetz-plot/0.1.0/gallery/barchart.png
  packages/preview/cetz-plot/0.1.0/gallery/barchart.typ
  packages/preview/cetz-plot/0.1.0/gallery/line.png
  packages/preview/cetz-plot/0.1.0/gallery/line.typ
  packages/preview/cetz-plot/0.1.0/gallery/piechart.png
  packages/preview/cetz-plot/0.1.0/gallery/piechart.typ
  packages/preview/cetz-plot/0.1.0/manual.pdf
  packages/preview/cetz-plot/0.1.0/manual.typ
  packages/preview/cetz-plot/0.1.0/src/axes.typ
  packages/preview/cetz-plot/0.1.0/src/cetz.typ
  packages/preview/cetz-plot/0.1.0/src/chart.typ
  packages/preview/cetz-plot/0.1.0/src/chart/barchart.typ
  packages/preview/cetz-plot/0.1.0/src/chart/barcol-common.typ
  packages/preview/cetz-plot/0.1.0/src/chart/boxwhisker.typ
  packages/preview/cetz-plot/0.1.0/src/chart/columnchart.typ
  packages/preview/cetz-plot/0.1.0/src/chart/piechart.typ
  packages/preview/cetz-plot/0.1.0/src/lib.typ
  packages/preview/cetz-plot/0.1.0/src/plot.typ
  packages/preview/cetz-plot/0.1.0/src/plot/annotation.typ
  packages/preview/cetz-plot/0.1.0/src/plot/bar.typ
  packages/preview/cetz-plot/0.1.0/src/plot/boxwhisker.typ
  packages/preview/cetz-plot/0.1.0/src/plot/contour.typ
  packages/preview/cetz-plot/0.1.0/src/plot/errorbar.typ
  packages/preview/cetz-plot/0.1.0/src/plot/formats.typ
  packages/preview/cetz-plot/0.1.0/src/plot/legend.typ
  packages/preview/cetz-plot/0.1.0/src/plot/line.typ
  packages/preview/cetz-plot/0.1.0/src/plot/mark.typ
  packages/preview/cetz-plot/0.1.0/src/plot/sample.typ
  packages/preview/cetz-plot/0.1.0/src/plot/util.typ
  packages/preview/cetz-plot/0.1.0/src/plot/violin.typ
  packages/preview/cetz-plot/0.1.0/typst.toml
Labels: new

#1119 outrageous:0.3.0
  packages/preview/outrageous/0.3.0/LICENSE
  packages/preview/outrageous/0.3.0/README.md
  packages/preview/outrageous/0.3.0/example-custom.png
  packages/preview/outrageous/0.3.0/example-default.png
  packages/preview/outrageous/0.3.0/examples/basic.typ
  packages/preview/outrageous/0.3.0/examples/rush.pdf
  packages/preview/outrageous/0.3.0/examples/rush.typ
  packages/preview/outrageous/0.3.0/outrageous.typ
  packages/preview/outrageous/0.3.0/typst.toml
Labels: update

#1121 stv-vub-huisstijl:0.1.0
  packages/preview/stv-vub-huisstijl/0.1.0/LICENSE
  packages/preview/stv-vub-huisstijl/0.1.0/README.md
  packages/preview/stv-vub-huisstijl/0.1.0/assets/vub_logo_cmyk.svg
  packages/preview/stv-vub-huisstijl/0.1.0/src/lib.typ
  packages/preview/stv-vub-huisstijl/0.1.0/template/main.typ
  packages/preview/stv-vub-huisstijl/0.1.0/thumbnail.png
  packages/preview/stv-vub-huisstijl/0.1.0/typst.toml
Labels: new

#1122 showybox:2.0.2
  packages/preview/showybox/2.0.2/LICENSE
  packages/preview/showybox/2.0.2/README.md
  packages/preview/showybox/2.0.2/Showybox's Manual.pdf
  packages/preview/showybox/2.0.2/assets/carnot-example.png
  packages/preview/showybox/2.0.2/assets/clairaut-example.png
  packages/preview/showybox/2.0.2/assets/coulomb-example.png
  packages/preview/showybox/2.0.2/assets/divergence-example.png
  packages/preview/showybox/2.0.2/assets/encapsulation-example.png
  packages/preview/showybox/2.0.2/assets/gauss-example.png
  packages/preview/showybox/2.0.2/assets/gradient.svg
  packages/preview/showybox/2.0.2/assets/hello-world.png
  packages/preview/showybox/2.0.2/assets/newton-example.png
  packages/preview/showybox/2.0.2/assets/stokes-example.png
  packages/preview/showybox/2.0.2/assets/two-easy-examples.png
  packages/preview/showybox/2.0.2/examples/examples.pdf
  packages/preview/showybox/2.0.2/examples/examples.typ
  packages/preview/showybox/2.0.2/lib/func.typ
  packages/preview/showybox/2.0.2/lib/id.typ
  packages/preview/showybox/2.0.2/lib/pre-rendering.typ
  packages/preview/showybox/2.0.2/lib/sections.typ
  packages/preview/showybox/2.0.2/lib/shadows.typ
  packages/preview/showybox/2.0.2/manual/manual.typ
  packages/preview/showybox/2.0.2/manual/template.typ
  packages/preview/showybox/2.0.2/showy.typ
  packages/preview/showybox/2.0.2/typst.toml
Labels: update

#1124 elsearticle:0.3.0
  packages/preview/elsearticle/0.3.0/CHANGELOG.md
  packages/preview/elsearticle/0.3.0/LICENSE
  packages/preview/elsearticle/0.3.0/README.md
  packages/preview/elsearticle/0.3.0/docs/manual.pdf
  packages/preview/elsearticle/0.3.0/src/elsearticle.typ
  packages/preview/elsearticle/0.3.0/template/images/typst-logo.svg
  packages/preview/elsearticle/0.3.0/template/main.typ
  packages/preview/elsearticle/0.3.0/template/refs.bib
  packages/preview/elsearticle/0.3.0/thumbnails/main.png
  packages/preview/elsearticle/0.3.0/typst.toml
Labels: update

#1125 use-tabler-icons:0.1.0
  packages/preview/use-tabler-icons/0.1.0/LICENSE
  packages/preview/use-tabler-icons/0.1.0/README.md
  packages/preview/use-tabler-icons/0.1.0/assets/splash.svg
  packages/preview/use-tabler-icons/0.1.0/src/lib-gen.typ
  packages/preview/use-tabler-icons/0.1.0/src/lib-impl.typ
  packages/preview/use-tabler-icons/0.1.0/src/lib.typ
  packages/preview/use-tabler-icons/0.1.0/typst.toml
Labels: new

#1127 grotesk-cv:1.0.1
  packages/preview/grotesk-cv/1.0.1/CHANGELOG.md
  packages/preview/grotesk-cv/1.0.1/LICENSE
  packages/preview/grotesk-cv/1.0.1/README.md
  packages/preview/grotesk-cv/1.0.1/docs/manual.pdf
  packages/preview/grotesk-cv/1.0.1/src/lib.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/education.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/experience.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/languages.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/other_experience.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/personal.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/profile.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/references.typ
  packages/preview/grotesk-cv/1.0.1/src/template/content/skills.typ
  packages/preview/grotesk-cv/1.0.1/src/template/cover.typ
  packages/preview/grotesk-cv/1.0.1/src/template/cv.typ
  packages/preview/grotesk-cv/1.0.1/src/template/font/Font Awesome 6 Brands-Regular-400.otf
  packages/preview/grotesk-cv/1.0.1/src/template/font/Font Awesome 6 Free-Regular-400.otf
  packages/preview/grotesk-cv/1.0.1/src/template/font/Font Awesome 6 Free-Solid-900.otf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/1.0.1/src/template/img/portrait.png
  packages/preview/grotesk-cv/1.0.1/src/template/info.toml
  packages/preview/grotesk-cv/1.0.1/thumbnail.png
  packages/preview/grotesk-cv/1.0.1/typst.toml
Labels: update

#1128 shadowed:0.1.1
  packages/preview/shadowed/0.1.1/LICENSE
  packages/preview/shadowed/0.1.1/README.md
  packages/preview/shadowed/0.1.1/examples/lorem.png
  packages/preview/shadowed/0.1.1/examples/lorem.typ
  packages/preview/shadowed/0.1.1/lib.typ
  packages/preview/shadowed/0.1.1/renderer.wasm
  packages/preview/shadowed/0.1.1/renderer/Cargo.lock
  packages/preview/shadowed/0.1.1/renderer/Cargo.toml
  packages/preview/shadowed/0.1.1/renderer/src/lib.rs
  packages/preview/shadowed/0.1.1/renderer/templates/shadow.svg.jinja
  packages/preview/shadowed/0.1.1/typst.toml
Labels: update

#1129 apa7-ish:0.1.0
  packages/preview/apa7-ish/0.1.0/LICENSE
  packages/preview/apa7-ish/0.1.0/README.md
  packages/preview/apa7-ish/0.1.0/src/apa7ish.typ
  packages/preview/apa7-ish/0.1.0/src/assets/orcid.svg
  packages/preview/apa7-ish/0.1.0/template/example.bib
  packages/preview/apa7-ish/0.1.0/template/main.typ
  packages/preview/apa7-ish/0.1.0/thumbnail.png
  packages/preview/apa7-ish/0.1.0/typst.toml
Labels: new

#1131 latedef:0.1.0
  packages/preview/latedef/0.1.0/LICENSE
  packages/preview/latedef/0.1.0/README.md
  packages/preview/latedef/0.1.0/example-images/1.png
  packages/preview/latedef/0.1.0/example-images/2.png
  packages/preview/latedef/0.1.0/example-images/3.png
  packages/preview/latedef/0.1.0/example-images/4.png
  packages/preview/latedef/0.1.0/example-images/5.png
  packages/preview/latedef/0.1.0/example-images/6.png
  packages/preview/latedef/0.1.0/example-images/7.png
  packages/preview/latedef/0.1.0/latedef.typ
  packages/preview/latedef/0.1.0/render-examples.typ
  packages/preview/latedef/0.1.0/typst.toml
Labels: new

#1123 fontawesome:0.5.0
  packages/preview/fontawesome/0.5.0/LICENSE
  packages/preview/fontawesome/0.5.0/README.md
  packages/preview/fontawesome/0.5.0/lib-gen.typ
  packages/preview/fontawesome/0.5.0/lib-impl.typ
  packages/preview/fontawesome/0.5.0/lib.typ
  packages/preview/fontawesome/0.5.0/typst.toml
Labels: update

#1132 bubble:0.2.2
  packages/preview/bubble/0.2.2/LICENSE
  packages/preview/bubble/0.2.2/README.md
  packages/preview/bubble/0.2.2/lib.typ
  packages/preview/bubble/0.2.2/template/logo.png
  packages/preview/bubble/0.2.2/template/main.typ
  packages/preview/bubble/0.2.2/thumbnail.png
  packages/preview/bubble/0.2.2/typst.toml
Labels: update

#1133 thesist:0.2.0
  packages/preview/thesist/0.2.0/LICENSE
  packages/preview/thesist/0.2.0/README.md
  packages/preview/thesist/0.2.0/src/IST.png
  packages/preview/thesist/0.2.0/src/figure-numbering.typ
  packages/preview/thesist/0.2.0/src/layout.typ
  packages/preview/thesist/0.2.0/src/utils.typ
  packages/preview/thesist/0.2.0/template/Beginning/Abstract-en.typ
  packages/preview/thesist/0.2.0/template/Beginning/Abstract-pt.typ
  packages/preview/thesist/0.2.0/template/Beginning/Acknowledgments.typ
  packages/preview/thesist/0.2.0/template/Beginning/Glossary.typ
  packages/preview/thesist/0.2.0/template/Beginning/Keywords-en.typ
  packages/preview/thesist/0.2.0/template/Beginning/Keywords-pt.typ
  packages/preview/thesist/0.2.0/template/Chapters/0-Quick-guide.typ
  packages/preview/thesist/0.2.0/template/Chapters/1-Introduction.typ
  packages/preview/thesist/0.2.0/template/Chapters/Appendix-A.typ
  packages/preview/thesist/0.2.0/template/Chapters/Appendix-B.typ
  packages/preview/thesist/0.2.0/template/Images/0-Quick-guide/andromeda.jpg
  packages/preview/thesist/0.2.0/template/Images/default-cover.jpg
  packages/preview/thesist/0.2.0/template/main.typ
  packages/preview/thesist/0.2.0/template/refs.bib
  packages/preview/thesist/0.2.0/thumbnail.png
  packages/preview/thesist/0.2.0/typst.toml
Labels: update

#1134 vercanard:1.0.2
  packages/preview/vercanard/1.0.2/LICENSE
  packages/preview/vercanard/1.0.2/README.md
  packages/preview/vercanard/1.0.2/demo.pdf
  packages/preview/vercanard/1.0.2/template.typ
  packages/preview/vercanard/1.0.2/template/main.typ
  packages/preview/vercanard/1.0.2/thumbnail.png
  packages/preview/vercanard/1.0.2/typst.toml
Labels: update

#1112 finely-crafted-cv:0.1.0
  packages/preview/finely-crafted-cv/0.1.0/LICENSE
  packages/preview/finely-crafted-cv/0.1.0/README.md
  packages/preview/finely-crafted-cv/0.1.0/lib.typ
  packages/preview/finely-crafted-cv/0.1.0/src/constants.pdf
  packages/preview/finely-crafted-cv/0.1.0/src/constants.typ
  packages/preview/finely-crafted-cv/0.1.0/src/helpers.typ
  packages/preview/finely-crafted-cv/0.1.0/src/icons/email.svg
  packages/preview/finely-crafted-cv/0.1.0/src/icons/linkedin.svg
  packages/preview/finely-crafted-cv/0.1.0/src/icons/phone.svg
  packages/preview/finely-crafted-cv/0.1.0/src/resume.typ
  packages/preview/finely-crafted-cv/0.1.0/src/state.typ
  packages/preview/finely-crafted-cv/0.1.0/template/assets/my-qr-code.svg
  packages/preview/finely-crafted-cv/0.1.0/template/icons/coral.svg
  packages/preview/finely-crafted-cv/0.1.0/template/icons/earth.svg
  packages/preview/finely-crafted-cv/0.1.0/template/icons/graduation-cap.svg
  packages/preview/finely-crafted-cv/0.1.0/template/icons/microscope.svg
  packages/preview/finely-crafted-cv/0.1.0/template/icons/palm-tree.svg
  packages/preview/finely-crafted-cv/0.1.0/template/icons/whale.svg
  packages/preview/finely-crafted-cv/0.1.0/template/main.typ
  packages/preview/finely-crafted-cv/0.1.0/thumbnail.png
  packages/preview/finely-crafted-cv/0.1.0/typst.toml
Labels: new

#1136 shiroa:0.1.2
  packages/preview/shiroa/0.1.2/LICENSE
  packages/preview/shiroa/0.1.2/README.md
  packages/preview/shiroa/0.1.2/lib.typ
  packages/preview/shiroa/0.1.2/media.typ
  packages/preview/shiroa/0.1.2/meta-and-state.typ
  packages/preview/shiroa/0.1.2/summary-internal.typ
  packages/preview/shiroa/0.1.2/summary.typ
  packages/preview/shiroa/0.1.2/supports-link.typ
  packages/preview/shiroa/0.1.2/supports-text.typ
  packages/preview/shiroa/0.1.2/sys.typ
  packages/preview/shiroa/0.1.2/template-link.typ
  packages/preview/shiroa/0.1.2/template-theme.typ
  packages/preview/shiroa/0.1.2/templates.typ
  packages/preview/shiroa/0.1.2/typst.toml
  packages/preview/shiroa/0.1.2/utils.typ
  packages/preview/shiroa/0.1.2/xcommand.typ
Labels: update

#1137 shadowed:0.1.2
  packages/preview/shadowed/0.1.2/LICENSE
  packages/preview/shadowed/0.1.2/README.md
  packages/preview/shadowed/0.1.2/examples/lorem.png
  packages/preview/shadowed/0.1.2/examples/lorem.typ
  packages/preview/shadowed/0.1.2/src/lib.typ
  packages/preview/shadowed/0.1.2/src/renderer.wasm
  packages/preview/shadowed/0.1.2/src/renderer/Cargo.lock
  packages/preview/shadowed/0.1.2/src/renderer/Cargo.toml
  packages/preview/shadowed/0.1.2/src/renderer/src/lib.rs
  packages/preview/shadowed/0.1.2/src/renderer/templates/shadow.svg.jinja
  packages/preview/shadowed/0.1.2/src/shadowed.typ
  packages/preview/shadowed/0.1.2/typst.toml
Labels: update

#1139 modernpro-coverletter:0.0.5
  packages/preview/modernpro-coverletter/0.0.5/README.md
  packages/preview/modernpro-coverletter/0.0.5/modernpro-coverletter.typ
  packages/preview/modernpro-coverletter/0.0.5/template/coverletter.typ
  packages/preview/modernpro-coverletter/0.0.5/template/statement.typ
  packages/preview/modernpro-coverletter/0.0.5/thumbnail.png
  packages/preview/modernpro-coverletter/0.0.5/typst.toml
Labels: update

#1135 great-theorems:0.1.1
  packages/preview/great-theorems/0.1.1/LICENSE
  packages/preview/great-theorems/0.1.1/README.md
  packages/preview/great-theorems/0.1.1/example.png
  packages/preview/great-theorems/0.1.1/example.typ
  packages/preview/great-theorems/0.1.1/lib.typ
  packages/preview/great-theorems/0.1.1/typst.toml
Labels: update

#1142 acrostiche:0.3.4
  packages/preview/acrostiche/0.3.4/LICENSE
  packages/preview/acrostiche/0.3.4/README.md
  packages/preview/acrostiche/0.3.4/acrostiche.typ
  packages/preview/acrostiche/0.3.4/typst.toml
Labels: update

#1141 numty:0.0.1
  packages/preview/numty/0.0.1/LICENSE
  packages/preview/numty/0.0.1/README.md
  packages/preview/numty/0.0.1/lib.typ
  packages/preview/numty/0.0.1/typst.toml
Labels: new

#1143 orange-book:0.3.0
  packages/preview/orange-book/0.3.0/LICENSE
  packages/preview/orange-book/0.3.0/README.md
  packages/preview/orange-book/0.3.0/lib.typ
  packages/preview/orange-book/0.3.0/my-index.typ
  packages/preview/orange-book/0.3.0/my-outline.typ
  packages/preview/orange-book/0.3.0/template/background.svg
  packages/preview/orange-book/0.3.0/template/creodocs_logo.svg
  packages/preview/orange-book/0.3.0/template/main.typ
  packages/preview/orange-book/0.3.0/template/orange1.jpg
  packages/preview/orange-book/0.3.0/template/orange2.jpg
  packages/preview/orange-book/0.3.0/template/orange3.jpg
  packages/preview/orange-book/0.3.0/template/placeholder.jpg
  packages/preview/orange-book/0.3.0/template/sample.bib
  packages/preview/orange-book/0.3.0/theorems.typ
  packages/preview/orange-book/0.3.0/thumbnail.png
  packages/preview/orange-book/0.3.0/typst.toml
Labels: update

#1138 formalettre:0.1.0
  packages/preview/formalettre/0.1.0/LICENSE
  packages/preview/formalettre/0.1.0/README.md
  packages/preview/formalettre/0.1.0/src/lib.typ
  packages/preview/formalettre/0.1.0/template/src/exemple.typ
  packages/preview/formalettre/0.1.0/thumbnail.png
  packages/preview/formalettre/0.1.0/typst.toml
Labels: new

#1144 accelerated-jacow:0.1.0
  packages/preview/accelerated-jacow/0.1.0/LICENSE
  packages/preview/accelerated-jacow/0.1.0/README.md
  packages/preview/accelerated-jacow/0.1.0/jacow.csl
  packages/preview/accelerated-jacow/0.1.0/jacow.typ
  packages/preview/accelerated-jacow/0.1.0/template/paper.typ
  packages/preview/accelerated-jacow/0.1.0/template/references.bib
  packages/preview/accelerated-jacow/0.1.0/template/writer.svg
  packages/preview/accelerated-jacow/0.1.0/thumbnail.webp
  packages/preview/accelerated-jacow/0.1.0/typst.toml
Labels: new

#1145 peace-of-posters:0.4.3
  packages/preview/peace-of-posters/0.4.3/LICENSE
  packages/preview/peace-of-posters/0.4.3/README.md
  packages/preview/peace-of-posters/0.4.3/boxes.typ
  packages/preview/peace-of-posters/0.4.3/layouts.typ
  packages/preview/peace-of-posters/0.4.3/lib.typ
  packages/preview/peace-of-posters/0.4.3/themes.typ
  packages/preview/peace-of-posters/0.4.3/typst.toml
Labels: update

#1140 modernpro-cv:1.0.2
  packages/preview/modernpro-cv/1.0.2/README.md
  packages/preview/modernpro-cv/1.0.2/modernpro-cv.typ
  packages/preview/modernpro-cv/1.0.2/template/bib.bib
  packages/preview/modernpro-cv/1.0.2/template/cv-double.typ
  packages/preview/modernpro-cv/1.0.2/template/cv-single.typ
  packages/preview/modernpro-cv/1.0.2/thumbnail.png
  packages/preview/modernpro-cv/1.0.2/typst.toml
Labels: update

#1147 finely-crafted-cv:0.1.0
  packages/preview/finely-crafted-cv/0.1.0/src/constants.pdf
Labels: new

#1150 ctheorems:1.1.3
  packages/preview/ctheorems/1.1.3/LICENSE
  packages/preview/ctheorems/1.1.3/README.md
  packages/preview/ctheorems/1.1.3/assets/basic.png
  packages/preview/ctheorems/1.1.3/assets/manual.pdf
  packages/preview/ctheorems/1.1.3/assets/manual_examples.pdf
  packages/preview/ctheorems/1.1.3/lib.typ
  packages/preview/ctheorems/1.1.3/typst.toml
Labels: update

#1154 formalettre:0.1.1
  packages/preview/formalettre/0.1.1/LICENSE
  packages/preview/formalettre/0.1.1/README.md
  packages/preview/formalettre/0.1.1/src/lib.typ
  packages/preview/formalettre/0.1.1/template/src/exemple.typ
  packages/preview/formalettre/0.1.1/thumbnail.png
  packages/preview/formalettre/0.1.1/typst.toml
Labels: update

#1151 glossy:0.1.0
  packages/preview/glossy/0.1.0/LICENSE
  packages/preview/glossy/0.1.0/README.md
  packages/preview/glossy/0.1.0/examples/readme.pdf
  packages/preview/glossy/0.1.0/examples/readme.typ
  packages/preview/glossy/0.1.0/lib.typ
  packages/preview/glossy/0.1.0/src/gloss.typ
  packages/preview/glossy/0.1.0/src/themes.pdf
  packages/preview/glossy/0.1.0/src/themes.typ
  packages/preview/glossy/0.1.0/src/utils.typ
  packages/preview/glossy/0.1.0/thumbnail.png
  packages/preview/glossy/0.1.0/typst.toml
Labels: new

#1156 nassi:0.1.2
  packages/preview/nassi/0.1.2/LICENSE
  packages/preview/nassi/0.1.2/README.md
  packages/preview/nassi/0.1.2/assets/example-1.png
  packages/preview/nassi/0.1.2/assets/example-1.typ
  packages/preview/nassi/0.1.2/assets/example-2.png
  packages/preview/nassi/0.1.2/assets/example-2.typ
  packages/preview/nassi/0.1.2/assets/example-3.png
  packages/preview/nassi/0.1.2/assets/example-3.typ
  packages/preview/nassi/0.1.2/assets/example-cetz-2.png
  packages/preview/nassi/0.1.2/assets/example-cetz-2.typ
  packages/preview/nassi/0.1.2/assets/example-cetz.png
  packages/preview/nassi/0.1.2/assets/example-cetz.typ
  packages/preview/nassi/0.1.2/src/draw.typ
  packages/preview/nassi/0.1.2/src/elements.typ
  packages/preview/nassi/0.1.2/src/nassi.typ
  packages/preview/nassi/0.1.2/tbump.toml
  packages/preview/nassi/0.1.2/tests/.gitignore
  packages/preview/nassi/0.1.2/tests/.ignore
  packages/preview/nassi/0.1.2/tests/statement/.gitignore
  packages/preview/nassi/0.1.2/tests/statement/out/1.png
  packages/preview/nassi/0.1.2/tests/statement/ref/1.png
  packages/preview/nassi/0.1.2/tests/statement/test.typ
  packages/preview/nassi/0.1.2/tests/switch/.gitignore
  packages/preview/nassi/0.1.2/tests/switch/out/1.png
  packages/preview/nassi/0.1.2/tests/switch/ref/1.png
  packages/preview/nassi/0.1.2/tests/switch/test.typ
  packages/preview/nassi/0.1.2/tests/template.typ
  packages/preview/nassi/0.1.2/typst.toml
Labels: update

#1155 codelst:2.0.2
  packages/preview/codelst/2.0.2/CHANGELOG.md
  packages/preview/codelst/2.0.2/Justfile
  packages/preview/codelst/2.0.2/LICENSE
  packages/preview/codelst/2.0.2/README.md
  packages/preview/codelst/2.0.2/docs/example.pdf
  packages/preview/codelst/2.0.2/docs/example.typ
  packages/preview/codelst/2.0.2/docs/manual.pdf
  packages/preview/codelst/2.0.2/docs/manual.typ
  packages/preview/codelst/2.0.2/src/codelst.typ
  packages/preview/codelst/2.0.2/tbump.toml
  packages/preview/codelst/2.0.2/tests/.gitkeep
  packages/preview/codelst/2.0.2/tests/gobble/.gitignore
  packages/preview/codelst/2.0.2/tests/gobble/ref/1.png
  packages/preview/codelst/2.0.2/tests/gobble/test.typ
  packages/preview/codelst/2.0.2/tests/test-spaces.txt
  packages/preview/codelst/2.0.2/tests/test-tabs.txt
  packages/preview/codelst/2.0.2/tests/test1/ref/1.png
  packages/preview/codelst/2.0.2/tests/test1/test.typ
  packages/preview/codelst/2.0.2/typst.toml
Labels: update

#1157 numty:0.0.3
  packages/preview/numty/0.0.3/LICENSE
  packages/preview/numty/0.0.3/README.md
  packages/preview/numty/0.0.3/lib.typ
  packages/preview/numty/0.0.3/test.typ
  packages/preview/numty/0.0.3/typst.toml
Labels: update

#1160 glossy:0.1.0 and glossy:0.1.1
  packages/preview/glossy/0.1.0/src/themes.pdf
  packages/preview/glossy/0.1.1/LICENSE
  packages/preview/glossy/0.1.1/README.md
  packages/preview/glossy/0.1.1/examples/readme.pdf
  packages/preview/glossy/0.1.1/examples/readme.typ
  packages/preview/glossy/0.1.1/lib.typ
  packages/preview/glossy/0.1.1/src/gloss.typ
  packages/preview/glossy/0.1.1/src/themes.typ
  packages/preview/glossy/0.1.1/src/utils.typ
  packages/preview/glossy/0.1.1/thumbnail.png
  packages/preview/glossy/0.1.1/typst.toml
Labels: new, update

#1158 statastic:1.0.0
  packages/preview/statastic/1.0.0/LICENSE
  packages/preview/statastic/1.0.0/README.md
  packages/preview/statastic/1.0.0/lib.typ
  packages/preview/statastic/1.0.0/typst.toml
Labels: update

#1161 tgm-hit-thesis:0.2.0
  packages/preview/tgm-hit-thesis/0.2.0/.gitignore
  packages/preview/tgm-hit-thesis/0.2.0/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.2.0/LICENSE
  packages/preview/tgm-hit-thesis/0.2.0/README.md
  packages/preview/tgm-hit-thesis/0.2.0/docs/manual.pdf
  packages/preview/tgm-hit-thesis/0.2.0/example.pdf
  packages/preview/tgm-hit-thesis/0.2.0/src/assets.typ
  packages/preview/tgm-hit-thesis/0.2.0/src/assets/logo-left.png
  packages/preview/tgm-hit-thesis/0.2.0/src/assets/logo-right.png
  packages/preview/tgm-hit-thesis/0.2.0/src/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.2.0/src/glossary.typ
  packages/preview/tgm-hit-thesis/0.2.0/src/l10n.toml
  packages/preview/tgm-hit-thesis/0.2.0/src/l10n.typ
  packages/preview/tgm-hit-thesis/0.2.0/src/lib.typ
  packages/preview/tgm-hit-thesis/0.2.0/src/utils.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/assets.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/assets/logo.png
  packages/preview/tgm-hit-thesis/0.2.0/template/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/bibliography.bib
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/conclusio.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/danksagung.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/einleitung.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/implementierung.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/konzept.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/kurzfassung.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/retrospektive.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/studie.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/chapters/vorwort.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/glossaries.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/lib.typ
  packages/preview/tgm-hit-thesis/0.2.0/template/main.typ
  packages/preview/tgm-hit-thesis/0.2.0/thumbnail.png
  packages/preview/tgm-hit-thesis/0.2.0/typst.toml
Labels: update

#1162 quill:0.5.0
  packages/preview/quill/0.5.0/LICENSE
  packages/preview/quill/0.5.0/README.md
  packages/preview/quill/0.5.0/src/arrow.typ
  packages/preview/quill/0.5.0/src/decorations.typ
  packages/preview/quill/0.5.0/src/draw-functions.typ
  packages/preview/quill/0.5.0/src/gates.typ
  packages/preview/quill/0.5.0/src/layout.typ
  packages/preview/quill/0.5.0/src/length-helpers.typ
  packages/preview/quill/0.5.0/src/process-args.typ
  packages/preview/quill/0.5.0/src/quantum-circuit.typ
  packages/preview/quill/0.5.0/src/quill.typ
  packages/preview/quill/0.5.0/src/tequila-impl.typ
  packages/preview/quill/0.5.0/src/tequila.typ
  packages/preview/quill/0.5.0/src/utility.typ
  packages/preview/quill/0.5.0/src/verifications.typ
  packages/preview/quill/0.5.0/typst.toml
Labels: update

#1163 droplet:0.3.0
  packages/preview/droplet/0.3.0/LICENSE
  packages/preview/droplet/0.3.0/README.md
  packages/preview/droplet/0.3.0/assets/example.svg
  packages/preview/droplet/0.3.0/assets/example.typ
  packages/preview/droplet/0.3.0/src/droplet.typ
  packages/preview/droplet/0.3.0/src/extract.typ
  packages/preview/droplet/0.3.0/src/lib.typ
  packages/preview/droplet/0.3.0/src/split.typ
  packages/preview/droplet/0.3.0/src/util.typ
  packages/preview/droplet/0.3.0/typst.toml
Labels: update

#1149 showybox:2.0.3
  packages/preview/showybox/2.0.3/LICENSE
  packages/preview/showybox/2.0.3/README.md
  packages/preview/showybox/2.0.3/Showybox's Manual.pdf
  packages/preview/showybox/2.0.3/assets/carnot-example.png
  packages/preview/showybox/2.0.3/assets/clairaut-example.png
  packages/preview/showybox/2.0.3/assets/coulomb-example.png
  packages/preview/showybox/2.0.3/assets/divergence-example.png
  packages/preview/showybox/2.0.3/assets/encapsulation-example.png
  packages/preview/showybox/2.0.3/assets/gauss-example.png
  packages/preview/showybox/2.0.3/assets/gradient.svg
  packages/preview/showybox/2.0.3/assets/hello-world.png
  packages/preview/showybox/2.0.3/assets/newton-example.png
  packages/preview/showybox/2.0.3/assets/stokes-example.png
  packages/preview/showybox/2.0.3/assets/two-easy-examples.png
  packages/preview/showybox/2.0.3/examples/examples.pdf
  packages/preview/showybox/2.0.3/examples/examples.typ
  packages/preview/showybox/2.0.3/lib/func.typ
  packages/preview/showybox/2.0.3/lib/id.typ
  packages/preview/showybox/2.0.3/lib/pre-rendering.typ
  packages/preview/showybox/2.0.3/lib/sections.typ
  packages/preview/showybox/2.0.3/lib/shadows.typ
  packages/preview/showybox/2.0.3/manual/manual.typ
  packages/preview/showybox/2.0.3/manual/template.typ
  packages/preview/showybox/2.0.3/showy.typ
  packages/preview/showybox/2.0.3/typst.toml
Labels: update

#1165 pesha:0.4.0
  packages/preview/pesha/0.4.0/LICENSE
  packages/preview/pesha/0.4.0/README.md
  packages/preview/pesha/0.4.0/lib.typ
  packages/preview/pesha/0.4.0/template/main.typ
  packages/preview/pesha/0.4.0/thumbnail.png
  packages/preview/pesha/0.4.0/typst.toml
Labels: update

#1152 peace-of-posters:0.5.0
  packages/preview/peace-of-posters/0.5.0/LICENSE
  packages/preview/peace-of-posters/0.5.0/README.md
  packages/preview/peace-of-posters/0.5.0/boxes.typ
  packages/preview/peace-of-posters/0.5.0/layouts.typ
  packages/preview/peace-of-posters/0.5.0/lib.typ
  packages/preview/peace-of-posters/0.5.0/templates/pop-uni-fr-poster/Treron_vernans_male_-_Kent_Ridge_Park.jpg
  packages/preview/peace-of-posters/0.5.0/templates/pop-uni-fr-poster/bibliography.bib
  packages/preview/peace-of-posters/0.5.0/templates/pop-uni-fr-poster/main.typ
  packages/preview/peace-of-posters/0.5.0/templates/pop-uni-fr-poster/peace-dove.png
  packages/preview/peace-of-posters/0.5.0/templates/pop-uni-fr-poster/thumbnail.png
  packages/preview/peace-of-posters/0.5.0/themes.typ
  packages/preview/peace-of-posters/0.5.0/typst.toml
Labels: update

#1166 use-tabler-icons:0.2.0
  packages/preview/use-tabler-icons/0.2.0/LICENSE
  packages/preview/use-tabler-icons/0.2.0/README.md
  packages/preview/use-tabler-icons/0.2.0/assets/splash.svg
  packages/preview/use-tabler-icons/0.2.0/src/lib-gen.typ
  packages/preview/use-tabler-icons/0.2.0/src/lib-impl.typ
  packages/preview/use-tabler-icons/0.2.0/src/lib.typ
  packages/preview/use-tabler-icons/0.2.0/typst.toml
Labels: update

#1173 knowledge-key:1.0.1
  packages/preview/knowledge-key/1.0.1/LICENSE
  packages/preview/knowledge-key/1.0.1/README.md
  packages/preview/knowledge-key/1.0.1/lib.typ
  packages/preview/knowledge-key/1.0.1/template/figures/devops-lifecycle.png
  packages/preview/knowledge-key/1.0.1/template/main.typ
  packages/preview/knowledge-key/1.0.1/template/sections/01-introduction.typ
  packages/preview/knowledge-key/1.0.1/template/sections/02-devops-with-gitlab.typ
  packages/preview/knowledge-key/1.0.1/template/sections/03-terraform.typ
  packages/preview/knowledge-key/1.0.1/template/utils.typ
  packages/preview/knowledge-key/1.0.1/thumbnail.png
  packages/preview/knowledge-key/1.0.1/typst.toml
Labels: update

#1164 flyingcircus:3.2.0
  packages/preview/flyingcircus/3.2.0/CHANGELOG.md
  packages/preview/flyingcircus/3.2.0/LICENSE
  packages/preview/flyingcircus/3.2.0/README.md
  packages/preview/flyingcircus/3.2.0/src/FlyingCircus.typ
  packages/preview/flyingcircus/3.2.0/src/Impl.typ
  packages/preview/flyingcircus/3.2.0/src/images/Default.png
  packages/preview/flyingcircus/3.2.0/template/Basic Biplane_stats.json
  packages/preview/flyingcircus/3.2.0/template/Main.typ
  packages/preview/flyingcircus/3.2.0/template/Sample Vehicle_stats.json
  packages/preview/flyingcircus/3.2.0/template/images/Bergziegel_image.jpg
  packages/preview/flyingcircus/3.2.0/template/images/Cover.png
  packages/preview/flyingcircus/3.2.0/template/images/Macchi Frigate.png
  packages/preview/flyingcircus/3.2.0/template/images/Rifle.png
  packages/preview/flyingcircus/3.2.0/template/images/Wandelburg.jpg
  packages/preview/flyingcircus/3.2.0/thumbnail.png
  packages/preview/flyingcircus/3.2.0/typst.toml
Labels: update

#1177 tablex:0.0.9
  packages/preview/tablex/0.0.9/LICENSE-APACHE
  packages/preview/tablex/0.0.9/LICENSE-MIT
  packages/preview/tablex/0.0.9/README.md
  packages/preview/tablex/0.0.9/tablex.typ
  packages/preview/tablex/0.0.9/typst.toml
Labels: update

#1179 cram-snap:0.2.1
  packages/preview/cram-snap/0.2.1/LICENSE
  packages/preview/cram-snap/0.2.1/README.md
  packages/preview/cram-snap/0.2.1/lib.typ
  packages/preview/cram-snap/0.2.1/template/git-icon.svg
  packages/preview/cram-snap/0.2.1/template/main.typ
  packages/preview/cram-snap/0.2.1/thumbnail.png
  packages/preview/cram-snap/0.2.1/typst.toml
Labels: update

#1178 koma-labeling:0.1.0
  packages/preview/koma-labeling/0.1.0/.gitignore
  packages/preview/koma-labeling/0.1.0/CHANGELOG.md
  packages/preview/koma-labeling/0.1.0/LICENSE
  packages/preview/koma-labeling/0.1.0/README.md
  packages/preview/koma-labeling/0.1.0/src/lib.typ
  packages/preview/koma-labeling/0.1.0/typst.toml
Labels: new

#1181 cvssc:0.1.0
  packages/preview/cvssc/0.1.0/LICENSE.txt
  packages/preview/cvssc/0.1.0/README.md
  packages/preview/cvssc/0.1.0/src/cvssc.typ
  packages/preview/cvssc/0.1.0/src/cvssc.wasm
  packages/preview/cvssc/0.1.0/src/docs.pdf
  packages/preview/cvssc/0.1.0/src/docs.typ
  packages/preview/cvssc/0.1.0/src/main.typ
  packages/preview/cvssc/0.1.0/typst.toml
Labels: new

#1182 zero:0.3.0
  packages/preview/zero/0.3.0/LICENSE
  packages/preview/zero/0.3.0/README.md
  packages/preview/zero/0.3.0/src/assertations.typ
  packages/preview/zero/0.3.0/src/formatting.typ
  packages/preview/zero/0.3.0/src/impl.typ
  packages/preview/zero/0.3.0/src/num.typ
  packages/preview/zero/0.3.0/src/parsing.typ
  packages/preview/zero/0.3.0/src/rounding.typ
  packages/preview/zero/0.3.0/src/state.typ
  packages/preview/zero/0.3.0/src/utility.typ
  packages/preview/zero/0.3.0/src/zero.typ
  packages/preview/zero/0.3.0/src/ztable.typ
  packages/preview/zero/0.3.0/typst.toml
Labels: update

#1186 glossarium:0.5.1
  packages/preview/glossarium/0.5.1/CHANGELOG.md
  packages/preview/glossarium/0.5.1/LICENSE
  packages/preview/glossarium/0.5.1/README.md
  packages/preview/glossarium/0.5.1/glossarium.typ
  packages/preview/glossarium/0.5.1/themes/default.typ
  packages/preview/glossarium/0.5.1/typst.toml
Labels: update

#1187 acrostiche:0.3.5
  packages/preview/acrostiche/0.3.5/LICENSE
  packages/preview/acrostiche/0.3.5/README.md
  packages/preview/acrostiche/0.3.5/acrostiche.typ
  packages/preview/acrostiche/0.3.5/typst.toml
Labels: update

#1188 cetz-venn:0.1.2
  packages/preview/cetz-venn/0.1.2/LICENSE
  packages/preview/cetz-venn/0.1.2/README.md
  packages/preview/cetz-venn/0.1.2/gallery/venn2.png
  packages/preview/cetz-venn/0.1.2/gallery/venn2.typ
  packages/preview/cetz-venn/0.1.2/gallery/venn3.png
  packages/preview/cetz-venn/0.1.2/gallery/venn3.typ
  packages/preview/cetz-venn/0.1.2/manual.pdf
  packages/preview/cetz-venn/0.1.2/manual.typ
  packages/preview/cetz-venn/0.1.2/src/lib.typ
  packages/preview/cetz-venn/0.1.2/src/venn.typ
  packages/preview/cetz-venn/0.1.2/typst.toml
Labels: update

#1189 letter-pro:3.0.0
  packages/preview/letter-pro/3.0.0/LICENSE
  packages/preview/letter-pro/3.0.0/README.md
  packages/preview/letter-pro/3.0.0/src/lib.typ
  packages/preview/letter-pro/3.0.0/template/src/main.typ
  packages/preview/letter-pro/3.0.0/template/thumbnail.png
  packages/preview/letter-pro/3.0.0/typst.toml
Labels: update

#1180 quick-minutes:1.0.0
  packages/preview/quick-minutes/1.0.0/LICENSE.txt
  packages/preview/quick-minutes/1.0.0/README.md
  packages/preview/quick-minutes/1.0.0/lang.json
  packages/preview/quick-minutes/1.0.0/name-test.typ
  packages/preview/quick-minutes/1.0.0/quick-minutes.typ
  packages/preview/quick-minutes/1.0.0/template/preview.typ
  packages/preview/quick-minutes/1.0.0/thumbnail.png
  packages/preview/quick-minutes/1.0.0/typst.toml
Labels: new

#1190 quick-minutes:1.0.1
  packages/preview/quick-minutes/1.0.1/LICENSE.txt
  packages/preview/quick-minutes/1.0.1/README.md
  packages/preview/quick-minutes/1.0.1/lang.json
  packages/preview/quick-minutes/1.0.1/name-test.typ
  packages/preview/quick-minutes/1.0.1/quick-minutes.typ
  packages/preview/quick-minutes/1.0.1/template/preview.typ
  packages/preview/quick-minutes/1.0.1/thumbnail.png
  packages/preview/quick-minutes/1.0.1/typst.toml
Labels: update

#1192 vartable:0.1.2
  packages/preview/vartable/0.1.2/LICENSE
  packages/preview/vartable/0.1.2/README.md
  packages/preview/vartable/0.1.2/documentation.pdf
  packages/preview/vartable/0.1.2/documentation.typ
  packages/preview/vartable/0.1.2/examples/bug1.pdf
  packages/preview/vartable/0.1.2/examples/bug1.png
  packages/preview/vartable/0.1.2/examples/bug1.typ
  packages/preview/vartable/0.1.2/examples/hyperbolicFuntion.pdf
  packages/preview/vartable/0.1.2/examples/hyperbolicFuntion.png
  packages/preview/vartable/0.1.2/examples/hyperbolicFuntion.typ
  packages/preview/vartable/0.1.2/examples/trigonometricFunction.pdf
  packages/preview/vartable/0.1.2/examples/trigonometricFunction.png
  packages/preview/vartable/0.1.2/examples/trigonometricFunction.typ
  packages/preview/vartable/0.1.2/tabvar.typ
  packages/preview/vartable/0.1.2/typst.toml
Labels: update

#1185 big-rati:0.1.0
  packages/preview/big-rati/0.1.0/LICENSE
  packages/preview/big-rati/0.1.0/README.md
  packages/preview/big-rati/0.1.0/rational.typ
  packages/preview/big-rati/0.1.0/typst.toml
  packages/preview/big-rati/0.1.0/typst_plugin_bigrational.wasm
Labels: new

#1195 quick-minutes:1.1.0
  packages/preview/quick-minutes/1.1.0/LICENSE.txt
  packages/preview/quick-minutes/1.1.0/README.md
  packages/preview/quick-minutes/1.1.0/lang.json
  packages/preview/quick-minutes/1.1.0/name-test.typ
  packages/preview/quick-minutes/1.1.0/quick-minutes.typ
  packages/preview/quick-minutes/1.1.0/template/preview.typ
  packages/preview/quick-minutes/1.1.0/thumbnail.png
  packages/preview/quick-minutes/1.1.0/typst.toml
Labels: update

#1191 typslides:1.1.1
  packages/preview/typslides/1.1.1/LICENSE
  packages/preview/typslides/1.1.1/README.md
  packages/preview/typslides/1.1.1/img/logo.png
  packages/preview/typslides/1.1.1/img/slide-1.jpg
  packages/preview/typslides/1.1.1/img/slide-2.jpg
  packages/preview/typslides/1.1.1/img/slide-3.jpg
  packages/preview/typslides/1.1.1/img/slide-4.jpg
  packages/preview/typslides/1.1.1/img/slide-5.jpg
  packages/preview/typslides/1.1.1/img/slide-6.jpg
  packages/preview/typslides/1.1.1/img/slide-7.jpg
  packages/preview/typslides/1.1.1/img/slide-8.jpg
  packages/preview/typslides/1.1.1/lib.typ
  packages/preview/typslides/1.1.1/typslides.typ
  packages/preview/typslides/1.1.1/typst.toml
  packages/preview/typslides/1.1.1/utils.typ
Labels: new

#1200 use-tabler-icons:0.3.0
  packages/preview/use-tabler-icons/0.3.0/LICENSE
  packages/preview/use-tabler-icons/0.3.0/README.md
  packages/preview/use-tabler-icons/0.3.0/assets/splash.svg
  packages/preview/use-tabler-icons/0.3.0/src/lib-gen.typ
  packages/preview/use-tabler-icons/0.3.0/src/lib-impl.typ
  packages/preview/use-tabler-icons/0.3.0/src/lib.typ
  packages/preview/use-tabler-icons/0.3.0/typst.toml
Labels: update

#1115 graceful-genetics:0.2.0
  packages/preview/graceful-genetics/0.2.0/CHANGELOG.md
  packages/preview/graceful-genetics/0.2.0/LICENSE
  packages/preview/graceful-genetics/0.2.0/README.md
  packages/preview/graceful-genetics/0.2.0/docs/manual.pdf
  packages/preview/graceful-genetics/0.2.0/src/impl.typ
  packages/preview/graceful-genetics/0.2.0/src/lib.typ
  packages/preview/graceful-genetics/0.2.0/template/a-mail.png
  packages/preview/graceful-genetics/0.2.0/template/main.typ
  packages/preview/graceful-genetics/0.2.0/thumbnails/1.png
  packages/preview/graceful-genetics/0.2.0/thumbnails/2.png
  packages/preview/graceful-genetics/0.2.0/typst.toml
Labels: update

#1202 apa7-ish:0.2.0
  packages/preview/apa7-ish/0.2.0/LICENSE
  packages/preview/apa7-ish/0.2.0/README.md
  packages/preview/apa7-ish/0.2.0/src/apa7ish.typ
  packages/preview/apa7-ish/0.2.0/src/assets/orcid.svg
  packages/preview/apa7-ish/0.2.0/template/example.bib
  packages/preview/apa7-ish/0.2.0/template/main.typ
  packages/preview/apa7-ish/0.2.0/thumbnail.png
  packages/preview/apa7-ish/0.2.0/typst.toml
Labels: update

#1203 quick-minutes:1.1.1
  packages/preview/quick-minutes/1.1.1/LICENSE.txt
  packages/preview/quick-minutes/1.1.1/README.md
  packages/preview/quick-minutes/1.1.1/lang.json
  packages/preview/quick-minutes/1.1.1/name-test.typ
  packages/preview/quick-minutes/1.1.1/quick-minutes.typ
  packages/preview/quick-minutes/1.1.1/template/preview.typ
  packages/preview/quick-minutes/1.1.1/thumbnail.png
  packages/preview/quick-minutes/1.1.1/typst.toml
Labels: update

#1204 kunskap:0.1.0
  packages/preview/kunskap/0.1.0/LICENSE
  packages/preview/kunskap/0.1.0/README.md
  packages/preview/kunskap/0.1.0/example.pdf
  packages/preview/kunskap/0.1.0/example.typ
  packages/preview/kunskap/0.1.0/lib.typ
  packages/preview/kunskap/0.1.0/template/main.typ
  packages/preview/kunskap/0.1.0/thumbnail.png
  packages/preview/kunskap/0.1.0/typst.toml
Labels: new

#1205 accelerated-jacow:0.1.0
  packages/preview/accelerated-jacow/0.1.0/typst.toml
Labels: new

#1206 acrostiche:0.4.0
  packages/preview/acrostiche/0.4.0/.gitignore
  packages/preview/acrostiche/0.4.0/LICENSE
  packages/preview/acrostiche/0.4.0/README.md
  packages/preview/acrostiche/0.4.0/acrostiche.typ
  packages/preview/acrostiche/0.4.0/test.typ
  packages/preview/acrostiche/0.4.0/typst.toml
Labels: update

#1207 numty:0.0.4
  packages/preview/numty/0.0.4/LICENSE
  packages/preview/numty/0.0.4/README.md
  packages/preview/numty/0.0.4/lib.typ
  packages/preview/numty/0.0.4/test.typ
  packages/preview/numty/0.0.4/typst.toml
Labels: update

#1208 quick-minutes:1.1.2
  packages/preview/quick-minutes/1.1.2/LICENSE.txt
  packages/preview/quick-minutes/1.1.2/README.md
  packages/preview/quick-minutes/1.1.2/lang.json
  packages/preview/quick-minutes/1.1.2/name-test.typ
  packages/preview/quick-minutes/1.1.2/quick-minutes.typ
  packages/preview/quick-minutes/1.1.2/template/preview.typ
  packages/preview/quick-minutes/1.1.2/thumbnail.png
  packages/preview/quick-minutes/1.1.2/typst.toml
Labels: update

#1209 glossy:0.1.2
  packages/preview/glossy/0.1.2/LICENSE
  packages/preview/glossy/0.1.2/README.md
  packages/preview/glossy/0.1.2/examples/readme.pdf
  packages/preview/glossy/0.1.2/examples/readme.typ
  packages/preview/glossy/0.1.2/lib.typ
  packages/preview/glossy/0.1.2/src/gloss.typ
  packages/preview/glossy/0.1.2/src/themes.typ
  packages/preview/glossy/0.1.2/src/utils.typ
  packages/preview/glossy/0.1.2/thumbnail.png
  packages/preview/glossy/0.1.2/typst.toml
Labels: update

#1199 silver-dev-cv:1.0.0
  packages/preview/silver-dev-cv/1.0.0/README.md
  packages/preview/silver-dev-cv/1.0.0/silver-dev-cv.typ
  packages/preview/silver-dev-cv/1.0.0/silver-dev-cv/cv.typ
  packages/preview/silver-dev-cv/1.0.0/template/cv.typ
  packages/preview/silver-dev-cv/1.0.0/thumbnail.png
  packages/preview/silver-dev-cv/1.0.0/typst.toml
Labels: new
