Repository typst/packages, pull requests merged in 2024-04, with the labels that each got.

#487 cineca:0.1.0
  packages/preview/cineca/0.1.0/LICENSE
  packages/preview/cineca/0.1.0/README.md
  packages/preview/cineca/0.1.0/example.png
  packages/preview/cineca/0.1.0/example.typ
  packages/preview/cineca/0.1.0/lib.typ
  packages/preview/cineca/0.1.0/typst.toml
  packages/preview/cineca/0.1.0/util/utils.typ
Labels: new

#488 mitex:0.2.3
  packages/preview/mitex/0.2.3/CHANGELOG.md
  packages/preview/mitex/0.2.3/LICENSE
  packages/preview/mitex/0.2.3/README.md
  packages/preview/mitex/0.2.3/examples/bench.typ
  packages/preview/mitex/0.2.3/examples/example.png
  packages/preview/mitex/0.2.3/examples/example.typ
  packages/preview/mitex/0.2.3/lib.typ
  packages/preview/mitex/0.2.3/mitex.typ
  packages/preview/mitex/0.2.3/mitex.wasm
  packages/preview/mitex/0.2.3/specs/README.md
  packages/preview/mitex/0.2.3/specs/latex/standard.typ
  packages/preview/mitex/0.2.3/specs/mod.typ
  packages/preview/mitex/0.2.3/specs/prelude.typ
  packages/preview/mitex/0.2.3/typst.toml
Labels: update

#490 codly:0.2.1
  packages/preview/codly/0.2.1/LICENSE
  packages/preview/codly/0.2.1/README.md
  packages/preview/codly/0.2.1/codly.typ
  packages/preview/codly/0.2.1/demo.png
  packages/preview/codly/0.2.1/typst.toml
Labels: update

#491 fontawesome:0.1.1
  packages/preview/fontawesome/0.1.1/LICENSE
  packages/preview/fontawesome/0.1.1/README.md
  packages/preview/fontawesome/0.1.1/lib.typ
  packages/preview/fontawesome/0.1.1/typst.toml
Labels: update

#486 down:0.1.0
  packages/preview/down/0.1.0/.gitignore
  packages/preview/down/0.1.0/LICENSE
  packages/preview/down/0.1.0/README.md
  packages/preview/down/0.1.0/README.typ
  packages/preview/down/0.1.0/lib.typ
  packages/preview/down/0.1.0/sample.pdf
  packages/preview/down/0.1.0/sample.typ
  packages/preview/down/0.1.0/typst.toml
Labels: new

#492 linguify:0.4.0
  packages/preview/linguify/0.4.0/LICENSE
  packages/preview/linguify/0.4.0/README.md
  packages/preview/linguify/0.4.0/lib/fluent.typ
  packages/preview/linguify/0.4.0/lib/lib.typ
  packages/preview/linguify/0.4.0/lib/linguify.typ
  packages/preview/linguify/0.4.0/lib/linguify_fluent_rs/linguify_fluent_rs.wasm
  packages/preview/linguify/0.4.0/lib/utils.typ
  packages/preview/linguify/0.4.0/typst.toml
Labels: update

#495 physica:0.9.3
  packages/preview/physica/0.9.3/LICENSE.txt
  packages/preview/physica/0.9.3/README.md
  packages/preview/physica/0.9.3/physica.typ
  packages/preview/physica/0.9.3/typst.toml
Labels: update

#493 starter-journal-article:0.2.0
  packages/preview/starter-journal-article/0.2.0/LICENSE
  packages/preview/starter-journal-article/0.2.0/README.md
  packages/preview/starter-journal-article/0.2.0/lib.typ
  packages/preview/starter-journal-article/0.2.0/template/main.typ
  packages/preview/starter-journal-article/0.2.0/template/ref.bib
  packages/preview/starter-journal-article/0.2.0/test.typ
  packages/preview/starter-journal-article/0.2.0/thumbnail.png
  packages/preview/starter-journal-article/0.2.0/typst.toml
Labels: update

#489 mcm-scaffold:0.1.0
  packages/preview/mcm-scaffold/0.1.0/LICENSE
  packages/preview/mcm-scaffold/0.1.0/README.md
  packages/preview/mcm-scaffold/0.1.0/lib.typ
  packages/preview/mcm-scaffold/0.1.0/template/figures/image1.png
  packages/preview/mcm-scaffold/0.1.0/template/main.typ
  packages/preview/mcm-scaffold/0.1.0/template/references.bib
  packages/preview/mcm-scaffold/0.1.0/template/references.yml
  packages/preview/mcm-scaffold/0.1.0/thumbnail.png
  packages/preview/mcm-scaffold/0.1.0/typst.toml
Labels: new

#450 vercanard:1.0.0
  packages/preview/vercanard/1.0.0/LICENSE
  packages/preview/vercanard/1.0.0/README.md
  packages/preview/vercanard/1.0.0/demo.pdf
  packages/preview/vercanard/1.0.0/template.typ
  packages/preview/vercanard/1.0.0/template/main.typ
  packages/preview/vercanard/1.0.0/thumbnail.png
  packages/preview/vercanard/1.0.0/typst.toml
Labels: new

#473 pintorita:0.1.1
  packages/preview/pintorita/0.1.1/LICENSE
  packages/preview/pintorita/0.1.1/NOTICE
  packages/preview/pintorita/0.1.1/README.md
  packages/preview/pintorita/0.1.1/lib.typ
  packages/preview/pintorita/0.1.1/pintora.js
  packages/preview/pintorita/0.1.1/pintorita.svg
  packages/preview/pintorita/0.1.1/pintorita.typ
  packages/preview/pintorita/0.1.1/typst.toml
Labels: update

#500 cumcm-muban:0.2.0
  packages/preview/cumcm-muban/0.2.0/LICENSE
  packages/preview/cumcm-muban/0.2.0/README.md
  packages/preview/cumcm-muban/0.2.0/lib.typ
  packages/preview/cumcm-muban/0.2.0/template/figures/f1.png
  packages/preview/cumcm-muban/0.2.0/template/figures/f2.svg
  packages/preview/cumcm-muban/0.2.0/template/main.typ
  packages/preview/cumcm-muban/0.2.0/template/refs.bib
  packages/preview/cumcm-muban/0.2.0/thumbnail.png
  packages/preview/cumcm-muban/0.2.0/typst.toml
Labels: update

#505 jurz:0.1.0
  packages/preview/jurz/0.1.0/.gitignore
  packages/preview/jurz/0.1.0/LICENSE
  packages/preview/jurz/0.1.0/README.md
  packages/preview/jurz/0.1.0/demo-2.svg
  packages/preview/jurz/0.1.0/demo-3.svg
  packages/preview/jurz/0.1.0/demo-images.sh
  packages/preview/jurz/0.1.0/demo.typ
  packages/preview/jurz/0.1.0/jurz.typ
  packages/preview/jurz/0.1.0/typst.toml
Labels: new

#508 cuti:0.2.1
  packages/preview/cuti/0.2.1/.gitignore
  packages/preview/cuti/0.2.1/LICENSE
  packages/preview/cuti/0.2.1/README.md
  packages/preview/cuti/0.2.1/demo-and-doc/demo-and-doc-cn.typ
  packages/preview/cuti/0.2.1/demo-and-doc/demo-and-doc.typ
  packages/preview/cuti/0.2.1/demo-and-doc/otr/utils.typ
  packages/preview/cuti/0.2.1/lib.typ
  packages/preview/cuti/0.2.1/typst.toml
Labels: update

#507 ssrn-scribe:0.5.0
  packages/preview/ssrn-scribe/0.5.0/README.md
  packages/preview/ssrn-scribe/0.5.0/paper_template.typ
  packages/preview/ssrn-scribe/0.5.0/template/main.typ
  packages/preview/ssrn-scribe/0.5.0/thumbnail.png
  packages/preview/ssrn-scribe/0.5.0/typst.toml
Labels: update

#511 touying:0.4.0 and touying-aqua:0.4.0
  packages/preview/touying-aqua/0.4.0/README.md
  packages/preview/touying-aqua/0.4.0/lib.typ
  packages/preview/touying-aqua/0.4.0/template/main.typ
  packages/preview/touying-aqua/0.4.0/thumbnail.png
  packages/preview/touying-aqua/0.4.0/typst.toml
  packages/preview/touying/0.4.0/.gitignore
  packages/preview/touying/0.4.0/LICENSE
  packages/preview/touying/0.4.0/README.md
  packages/preview/touying/0.4.0/changelog.md
  packages/preview/touying/0.4.0/examples/aqua-zh.typ
  packages/preview/touying/0.4.0/examples/aqua.typ
  packages/preview/touying/0.4.0/examples/dewdrop.typ
  packages/preview/touying/0.4.0/examples/example.typ
  packages/preview/touying/0.4.0/examples/metropolis.typ
  packages/preview/touying/0.4.0/examples/simple.typ
  packages/preview/touying/0.4.0/examples/slides.typ
  packages/preview/touying/0.4.0/examples/university.typ
  packages/preview/touying/0.4.0/lib.typ
  packages/preview/touying/0.4.0/slide.typ
  packages/preview/touying/0.4.0/themes/aqua.typ
  packages/preview/touying/0.4.0/themes/default.typ
  packages/preview/touying/0.4.0/themes/dewdrop.typ
  packages/preview/touying/0.4.0/themes/metropolis.typ
  packages/preview/touying/0.4.0/themes/simple.typ
  packages/preview/touying/0.4.0/themes/themes.typ
  packages/preview/touying/0.4.0/themes/university.typ
  packages/preview/touying/0.4.0/typst.toml
  packages/preview/touying/0.4.0/utils/components.typ
  packages/preview/touying/0.4.0/utils/pdfpc.typ
  packages/preview/touying/0.4.0/utils/states.typ
  packages/preview/touying/0.4.0/utils/utils.typ
Labels: update

#468 exzellenz-tum-thesis:0.1.0
  packages/preview/exzellenz-tum-thesis/0.1.0/LICENSE
  packages/preview/exzellenz-tum-thesis/0.1.0/README.md
  packages/preview/exzellenz-tum-thesis/0.1.0/TUM_logo.svg
  packages/preview/exzellenz-tum-thesis/0.1.0/abstract.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/acknowledgement.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/cover.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/disclaimer.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/template.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/template/Chapter_Appendix.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/template/Chapter_Introduction.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/template/dummy_image.svg
  packages/preview/exzellenz-tum-thesis/0.1.0/template/glossary.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/template/items.bib
  packages/preview/exzellenz-tum-thesis/0.1.0/template/main.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/template/utils.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/thumbnail.png
  packages/preview/exzellenz-tum-thesis/0.1.0/titlepage.typ
  packages/preview/exzellenz-tum-thesis/0.1.0/typst.toml
Labels: new

#513 g-exam:0.3.0
  packages/preview/g-exam/0.3.0/LICENSE
  packages/preview/g-exam/0.3.0/README.md
  packages/preview/g-exam/0.3.0/gallery/exam-table-content.png
  packages/preview/g-exam/0.3.0/src/auxiliary.typ
  packages/preview/g-exam/0.3.0/src/g-clarification.typ
  packages/preview/g-exam/0.3.0/src/g-exam.typ
  packages/preview/g-exam/0.3.0/src/g-question.typ
  packages/preview/g-exam/0.3.0/src/g-solution.typ
  packages/preview/g-exam/0.3.0/src/global.typ
  packages/preview/g-exam/0.3.0/src/lang.toml
  packages/preview/g-exam/0.3.0/src/lib.typ
  packages/preview/g-exam/0.3.0/template/1er exam.typ
  packages/preview/g-exam/0.3.0/template/logo.png
  packages/preview/g-exam/0.3.0/thumbnail.png
  packages/preview/g-exam/0.3.0/typst.toml
Labels: update

#514 glossarium:0.3.0
  packages/preview/glossarium/0.3.0/LICENCE
  packages/preview/glossarium/0.3.0/README.md
  packages/preview/glossarium/0.3.0/examples/full-example/main.pdf
  packages/preview/glossarium/0.3.0/examples/full-example/main.typ
  packages/preview/glossarium/0.3.0/examples/groups/groups.pdf
  packages/preview/glossarium/0.3.0/examples/groups/groups.typ
  packages/preview/glossarium/0.3.0/examples/import-terms-from-yaml-file/glossary.yml
  packages/preview/glossarium/0.3.0/examples/import-terms-from-yaml-file/main.pdf
  packages/preview/glossarium/0.3.0/examples/import-terms-from-yaml-file/main.typ
  packages/preview/glossarium/0.3.0/glossarium.typ
  packages/preview/glossarium/0.3.0/justfile
  packages/preview/glossarium/0.3.0/typst.toml
Labels: update

#515 ilm:0.1.3
  packages/preview/ilm/0.1.3/LICENSE
  packages/preview/ilm/0.1.3/README.md
  packages/preview/ilm/0.1.3/lib.typ
  packages/preview/ilm/0.1.3/template/main.typ
  packages/preview/ilm/0.1.3/template/refs.bib
  packages/preview/ilm/0.1.3/thumbnail.png
  packages/preview/ilm/0.1.3/typst.toml
Labels: update

#512 modern-nju-thesis:0.3.0
  packages/preview/modern-nju-thesis/0.3.0/LICENSE
  packages/preview/modern-nju-thesis/0.3.0/README.md
  packages/preview/modern-nju-thesis/0.3.0/assets/vi/nju-emblem-purple.svg
  packages/preview/modern-nju-thesis/0.3.0/assets/vi/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.0/assets/vi/nju-name-purple.svg
  packages/preview/modern-nju-thesis/0.3.0/assets/vi/nju-name.svg
  packages/preview/modern-nju-thesis/0.3.0/images/editor.png
  packages/preview/modern-nju-thesis/0.3.0/images/proposal.png
  packages/preview/modern-nju-thesis/0.3.0/images/web-app.png
  packages/preview/modern-nju-thesis/0.3.0/layouts/appendix.typ
  packages/preview/modern-nju-thesis/0.3.0/layouts/doc.typ
  packages/preview/modern-nju-thesis/0.3.0/layouts/mainmatter.typ
  packages/preview/modern-nju-thesis/0.3.0/layouts/preface.typ
  packages/preview/modern-nju-thesis/0.3.0/lib.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/acknowledgement.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/bachelor-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/bachelor-abstract.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/bachelor-cover.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/bachelor-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/bachelor-outline-page.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/fonts-display-page.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/list-of-figures.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/list-of-tables.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/master-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/master-abstract.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/master-cover.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/master-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.0/pages/notation.typ
  packages/preview/modern-nju-thesis/0.3.0/template/images/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.0/template/ref.bib
  packages/preview/modern-nju-thesis/0.3.0/template/thesis.typ
  packages/preview/modern-nju-thesis/0.3.0/thumbnail.png
  packages/preview/modern-nju-thesis/0.3.0/typst.toml
  packages/preview/modern-nju-thesis/0.3.0/utils/bilingual-bibliography.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/custom-cuti.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/custom-heading.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/custom-numbering.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/custom-tablex.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/datetime-display.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/double-underline.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/hline.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/indent.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/invisible-heading.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/justify-text.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/style.typ
  packages/preview/modern-nju-thesis/0.3.0/utils/unpairs.typ
Labels: new

#509 yagenda:0.1.0
  packages/preview/yagenda/0.1.0/.gitignore
  packages/preview/yagenda/0.1.0/LICENSE
  packages/preview/yagenda/0.1.0/README.md
  packages/preview/yagenda/0.1.0/agenda.typ
  packages/preview/yagenda/0.1.0/template/agenda.yaml
  packages/preview/yagenda/0.1.0/template/main.typ
  packages/preview/yagenda/0.1.0/thumbnail.png
  packages/preview/yagenda/0.1.0/typst.toml
Labels: new

#516 modern-nju-thesis:0.3.1
  packages/preview/modern-nju-thesis/0.3.1/LICENSE
  packages/preview/modern-nju-thesis/0.3.1/README.md
  packages/preview/modern-nju-thesis/0.3.1/assets/vi/nju-emblem-purple.svg
  packages/preview/modern-nju-thesis/0.3.1/assets/vi/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.1/assets/vi/nju-name-purple.svg
  packages/preview/modern-nju-thesis/0.3.1/assets/vi/nju-name.svg
  packages/preview/modern-nju-thesis/0.3.1/imgs/editor.png
  packages/preview/modern-nju-thesis/0.3.1/imgs/gallery.png
  packages/preview/modern-nju-thesis/0.3.1/imgs/proposal.png
  packages/preview/modern-nju-thesis/0.3.1/imgs/template.png
  packages/preview/modern-nju-thesis/0.3.1/imgs/webapp.png
  packages/preview/modern-nju-thesis/0.3.1/layouts/appendix.typ
  packages/preview/modern-nju-thesis/0.3.1/layouts/doc.typ
  packages/preview/modern-nju-thesis/0.3.1/layouts/mainmatter.typ
  packages/preview/modern-nju-thesis/0.3.1/layouts/preface.typ
  packages/preview/modern-nju-thesis/0.3.1/lib.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/acknowledgement.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/bachelor-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/bachelor-abstract.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/bachelor-cover.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/bachelor-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/bachelor-outline-page.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/fonts-display-page.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/list-of-figures.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/list-of-tables.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/master-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/master-abstract.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/master-cover.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/master-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.1/pages/notation.typ
  packages/preview/modern-nju-thesis/0.3.1/template/images/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.1/template/ref.bib
  packages/preview/modern-nju-thesis/0.3.1/template/thesis.typ
  packages/preview/modern-nju-thesis/0.3.1/thumbnail.png
  packages/preview/modern-nju-thesis/0.3.1/typst.toml
  packages/preview/modern-nju-thesis/0.3.1/utils/bilingual-bibliography.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/custom-cuti.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/custom-heading.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/custom-numbering.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/custom-tablex.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/datetime-display.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/double-underline.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/hline.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/indent.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/invisible-heading.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/justify-text.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/style.typ
  packages/preview/modern-nju-thesis/0.3.1/utils/unpairs.typ
Labels: update

#518 starter-journal-article:0.3.0
  packages/preview/starter-journal-article/0.3.0/LICENSE
  packages/preview/starter-journal-article/0.3.0/README.md
  packages/preview/starter-journal-article/0.3.0/assets/basic.png
  packages/preview/starter-journal-article/0.3.0/assets/basic.typ
  packages/preview/starter-journal-article/0.3.0/assets/custom-abstract.png
  packages/preview/starter-journal-article/0.3.0/assets/custom-abstract.typ
  packages/preview/starter-journal-article/0.3.0/assets/custom-author-info.png
  packages/preview/starter-journal-article/0.3.0/assets/custom-author-info.typ
  packages/preview/starter-journal-article/0.3.0/assets/custom-title.png
  packages/preview/starter-journal-article/0.3.0/assets/custom-title.typ
  packages/preview/starter-journal-article/0.3.0/lib.typ
  packages/preview/starter-journal-article/0.3.0/template/main.typ
  packages/preview/starter-journal-article/0.3.0/template/ref.bib
  packages/preview/starter-journal-article/0.3.0/test.typ
  packages/preview/starter-journal-article/0.3.0/thumbnail.png
  packages/preview/starter-journal-article/0.3.0/typst.toml
Labels: update

#485 tlacuache-thesis-fc-unam:0.1.1
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/LICENSE
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/README.md
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/escudos/FC_crest_black.svg
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/escudos/UNAM_crest_black.svg
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/lib.typ
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/template/capitulo1.typ
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/template/main.typ
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/template/references.bib
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/template/seccion1.typ
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/thumbnail.webp
  packages/preview/tlacuache-thesis-fc-unam/0.1.1/typst.toml
Labels: new

#519 modern-nju-thesis:0.3.2
  packages/preview/modern-nju-thesis/0.3.2/LICENSE
  packages/preview/modern-nju-thesis/0.3.2/README.md
  packages/preview/modern-nju-thesis/0.3.2/assets/vi/nju-emblem-purple.svg
  packages/preview/modern-nju-thesis/0.3.2/assets/vi/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.2/assets/vi/nju-name-purple.svg
  packages/preview/modern-nju-thesis/0.3.2/assets/vi/nju-name.svg
  packages/preview/modern-nju-thesis/0.3.2/imgs/editor.png
  packages/preview/modern-nju-thesis/0.3.2/imgs/gallery.png
  packages/preview/modern-nju-thesis/0.3.2/imgs/proposal.png
  packages/preview/modern-nju-thesis/0.3.2/imgs/template.png
  packages/preview/modern-nju-thesis/0.3.2/imgs/webapp.png
  packages/preview/modern-nju-thesis/0.3.2/layouts/appendix.typ
  packages/preview/modern-nju-thesis/0.3.2/layouts/doc.typ
  packages/preview/modern-nju-thesis/0.3.2/layouts/mainmatter.typ
  packages/preview/modern-nju-thesis/0.3.2/layouts/preface.typ
  packages/preview/modern-nju-thesis/0.3.2/lib.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/acknowledgement.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/bachelor-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/bachelor-abstract.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/bachelor-cover.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/bachelor-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/bachelor-outline-page.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/fonts-display-page.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/list-of-figures.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/list-of-tables.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/master-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/master-abstract.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/master-cover.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/master-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.2/pages/notation.typ
  packages/preview/modern-nju-thesis/0.3.2/template/images/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.2/template/ref.bib
  packages/preview/modern-nju-thesis/0.3.2/template/thesis.typ
  packages/preview/modern-nju-thesis/0.3.2/thumbnail.png
  packages/preview/modern-nju-thesis/0.3.2/typst.toml
  packages/preview/modern-nju-thesis/0.3.2/utils/bilingual-bibliography.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/custom-cuti.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/custom-heading.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/custom-numbering.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/custom-tablex.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/datetime-display.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/double-underline.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/hline.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/indent.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/invisible-heading.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/justify-text.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/style.typ
  packages/preview/modern-nju-thesis/0.3.2/utils/unpairs.typ
Labels: update

#520 ilm:1.0.0
  packages/preview/ilm/1.0.0/LICENSE
  packages/preview/ilm/1.0.0/README.md
  packages/preview/ilm/1.0.0/lib.typ
  packages/preview/ilm/1.0.0/template/main.typ
  packages/preview/ilm/1.0.0/template/refs.bib
  packages/preview/ilm/1.0.0/thumbnail.png
  packages/preview/ilm/1.0.0/typst.toml
Labels: update

#521 suiji:0.2.2
  packages/preview/suiji/0.2.2/LICENSE
  packages/preview/suiji/0.2.2/README.md
  packages/preview/suiji/0.2.2/examples/matrix-rain.pdf
  packages/preview/suiji/0.2.2/examples/matrix-rain.png
  packages/preview/suiji/0.2.2/examples/matrix-rain.typ
  packages/preview/suiji/0.2.2/examples/random-permutation.pdf
  packages/preview/suiji/0.2.2/examples/random-permutation.png
  packages/preview/suiji/0.2.2/examples/random-permutation.typ
  packages/preview/suiji/0.2.2/examples/random-walk.pdf
  packages/preview/suiji/0.2.2/examples/random-walk.png
  packages/preview/suiji/0.2.2/examples/random-walk.typ
  packages/preview/suiji/0.2.2/src/chinese.typ
  packages/preview/suiji/0.2.2/src/lib.typ
  packages/preview/suiji/0.2.2/src/random.typ
  packages/preview/suiji/0.2.2/src/taus.typ
  packages/preview/suiji/0.2.2/tests/test-choice.pdf
  packages/preview/suiji/0.2.2/tests/test-choice.typ
  packages/preview/suiji/0.2.2/tests/test-discrete.pdf
  packages/preview/suiji/0.2.2/tests/test-discrete.typ
  packages/preview/suiji/0.2.2/tests/test-integers.pdf
  packages/preview/suiji/0.2.2/tests/test-integers.typ
  packages/preview/suiji/0.2.2/tests/test-normal.pdf
  packages/preview/suiji/0.2.2/tests/test-normal.typ
  packages/preview/suiji/0.2.2/tests/test-rand-sc.pdf
  packages/preview/suiji/0.2.2/tests/test-rand-sc.typ
  packages/preview/suiji/0.2.2/tests/test-random.pdf
  packages/preview/suiji/0.2.2/tests/test-random.typ
  packages/preview/suiji/0.2.2/tests/test-shuffle.pdf
  packages/preview/suiji/0.2.2/tests/test-shuffle.typ
  packages/preview/suiji/0.2.2/tests/test-uniform.pdf
  packages/preview/suiji/0.2.2/tests/test-uniform.typ
  packages/preview/suiji/0.2.2/typst.toml
Labels: update

#475 scholarly-tauthesis:0.4.0
  .gitmodules
  packages/preview/scholarly-tauthesis/0.4.0/LICENSE
  packages/preview/scholarly-tauthesis/0.4.0/README.md
  packages/preview/scholarly-tauthesis/0.4.0/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.4.0/template/code/README.md
  packages/preview/scholarly-tauthesis/0.4.0/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.4.0/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/README.md
  packages/preview/scholarly-tauthesis/0.4.0/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/images/README.md
  packages/preview/scholarly-tauthesis/0.4.0/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.4.0/template/main.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/meta.typ
  packages/preview/scholarly-tauthesis/0.4.0/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.4.0/thumbnail.png
  packages/preview/scholarly-tauthesis/0.4.0/typst.toml
Labels: new

#522 Minor fix for exzellenz-tum-thesis
  packages/preview/exzellenz-tum-thesis/0.1.0/README.md
  packages/preview/exzellenz-tum-thesis/0.1.0/thumbnail.png
Labels: minor fix

#525 pinit:0.1.4
  packages/preview/pinit/0.1.4/LICENSE
  packages/preview/pinit/0.1.4/README.md
  packages/preview/pinit/0.1.4/examples/asymptotic.png
  packages/preview/pinit/0.1.4/examples/equation-desc.png
  packages/preview/pinit/0.1.4/examples/equation-desc.typ
  packages/preview/pinit/0.1.4/examples/example-pages.png
  packages/preview/pinit/0.1.4/examples/example.pdf
  packages/preview/pinit/0.1.4/examples/example.png
  packages/preview/pinit/0.1.4/examples/example.typ
  packages/preview/pinit/0.1.4/examples/pinit-for-raw.png
  packages/preview/pinit/0.1.4/examples/pinit-for-raw.typ
  packages/preview/pinit/0.1.4/examples/simple-demo.png
  packages/preview/pinit/0.1.4/lib.typ
  packages/preview/pinit/0.1.4/pinit-core.typ
  packages/preview/pinit/0.1.4/simple-arrow.typ
  packages/preview/pinit/0.1.4/typst.toml
Labels: update

#532 ilm:1.1.0
  packages/preview/ilm/1.1.0/LICENSE
  packages/preview/ilm/1.1.0/README.md
  packages/preview/ilm/1.1.0/lib.typ
  packages/preview/ilm/1.1.0/template/main.typ
  packages/preview/ilm/1.1.0/template/refs.bib
  packages/preview/ilm/1.1.0/thumbnail.png
  packages/preview/ilm/1.1.0/typst.toml
Labels: update

#533 pesha:0.2.0
  packages/preview/pesha/0.2.0/LICENSE
  packages/preview/pesha/0.2.0/README.md
  packages/preview/pesha/0.2.0/lib.typ
  packages/preview/pesha/0.2.0/template/main.typ
  packages/preview/pesha/0.2.0/thumbnail.png
  packages/preview/pesha/0.2.0/typst.toml
Labels: update

#484 modern-russian-dissertation:0.0.1
  packages/preview/modern-russian-dissertation/0.0.1/LICENSE
  packages/preview/modern-russian-dissertation/0.0.1/README.md
  packages/preview/modern-russian-dissertation/0.0.1/glossarium.typ
  packages/preview/modern-russian-dissertation/0.0.1/lib.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/common/acronyms.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/common/author.bib
  packages/preview/modern-russian-dissertation/0.0.1/template/common/external.bib
  packages/preview/modern-russian-dissertation/0.0.1/template/common/glossary.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/common/symbols.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/images/brand-python.svg
  packages/preview/modern-russian-dissertation/0.0.1/template/images/brand-rust.svg
  packages/preview/modern-russian-dissertation/0.0.1/template/images/logo.svg
  packages/preview/modern-russian-dissertation/0.0.1/template/images/typst.png
  packages/preview/modern-russian-dissertation/0.0.1/template/parts/appendix.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/parts/conclusion.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/parts/intro.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/parts/part1.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/parts/part2.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/parts/part3.typ
  packages/preview/modern-russian-dissertation/0.0.1/template/thesis.typ
  packages/preview/modern-russian-dissertation/0.0.1/thumbnail.png
  packages/preview/modern-russian-dissertation/0.0.1/typst.toml
Labels: new

#528 cheq:0.1.0
  packages/preview/cheq/0.1.0/LICENSE
  packages/preview/cheq/0.1.0/README.md
  packages/preview/cheq/0.1.0/examples/custom-styles.png
  packages/preview/cheq/0.1.0/examples/custom-styles.typ
  packages/preview/cheq/0.1.0/examples/example.png
  packages/preview/cheq/0.1.0/examples/example.typ
  packages/preview/cheq/0.1.0/lib.typ
  packages/preview/cheq/0.1.0/typst.toml
Labels: new

#531 qcm:0.1.0
  packages/preview/qcm/0.1.0/LICENSE
  packages/preview/qcm/0.1.0/README.md
  packages/preview/qcm/0.1.0/data.json
  packages/preview/qcm/0.1.0/main.typ
  packages/preview/qcm/0.1.0/typst.toml
Labels: new

#523 typpuccino:0.1.0
  packages/preview/typpuccino/0.1.0/LICENSE
  packages/preview/typpuccino/0.1.0/README.md
  packages/preview/typpuccino/0.1.0/example.pdf
  packages/preview/typpuccino/0.1.0/example.typ
  packages/preview/typpuccino/0.1.0/src/frappe.typ
  packages/preview/typpuccino/0.1.0/src/latte.typ
  packages/preview/typpuccino/0.1.0/src/lib.typ
  packages/preview/typpuccino/0.1.0/src/macchiato.typ
  packages/preview/typpuccino/0.1.0/src/mocha.typ
  packages/preview/typpuccino/0.1.0/typst.toml
Labels: new

#524 grayness:0.1.0
  packages/preview/grayness/0.1.0/Arturo_Nieto-Dorantes.webp
  packages/preview/grayness/0.1.0/LICENSE
  packages/preview/grayness/0.1.0/README.md
  packages/preview/grayness/0.1.0/example.png
  packages/preview/grayness/0.1.0/example.typ
  packages/preview/grayness/0.1.0/grayness.wasm
  packages/preview/grayness/0.1.0/lib.typ
  packages/preview/grayness/0.1.0/manual.pdf
  packages/preview/grayness/0.1.0/manual.typ
  packages/preview/grayness/0.1.0/typst.toml
Labels: new

#543 pesha:0.3.0
  packages/preview/pesha/0.3.0/LICENSE
  packages/preview/pesha/0.3.0/README.md
  packages/preview/pesha/0.3.0/lib.typ
  packages/preview/pesha/0.3.0/template/main.typ
  packages/preview/pesha/0.3.0/thumbnail.png
  packages/preview/pesha/0.3.0/typst.toml
Labels: update

#544 modern-nju-thesis:0.3.3
  packages/preview/modern-nju-thesis/0.3.3/LICENSE
  packages/preview/modern-nju-thesis/0.3.3/README.md
  packages/preview/modern-nju-thesis/0.3.3/assets/vi/nju-emblem-purple.svg
  packages/preview/modern-nju-thesis/0.3.3/assets/vi/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.3/assets/vi/nju-name-purple.svg
  packages/preview/modern-nju-thesis/0.3.3/assets/vi/nju-name.svg
  packages/preview/modern-nju-thesis/0.3.3/imgs/editor.png
  packages/preview/modern-nju-thesis/0.3.3/imgs/gallery.png
  packages/preview/modern-nju-thesis/0.3.3/imgs/proposal.png
  packages/preview/modern-nju-thesis/0.3.3/imgs/template.png
  packages/preview/modern-nju-thesis/0.3.3/imgs/webapp.png
  packages/preview/modern-nju-thesis/0.3.3/layouts/appendix.typ
  packages/preview/modern-nju-thesis/0.3.3/layouts/doc.typ
  packages/preview/modern-nju-thesis/0.3.3/layouts/mainmatter.typ
  packages/preview/modern-nju-thesis/0.3.3/layouts/preface.typ
  packages/preview/modern-nju-thesis/0.3.3/lib.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/acknowledgement.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/bachelor-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/bachelor-abstract.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/bachelor-cover.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/bachelor-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/bachelor-outline-page.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/fonts-display-page.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/list-of-figures.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/list-of-tables.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/master-abstract-en.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/master-abstract.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/master-cover.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/master-decl-page.typ
  packages/preview/modern-nju-thesis/0.3.3/pages/notation.typ
  packages/preview/modern-nju-thesis/0.3.3/template/images/nju-emblem.svg
  packages/preview/modern-nju-thesis/0.3.3/template/ref.bib
  packages/preview/modern-nju-thesis/0.3.3/template/thesis.typ
  packages/preview/modern-nju-thesis/0.3.3/thumbnail.png
  packages/preview/modern-nju-thesis/0.3.3/typst.toml
  packages/preview/modern-nju-thesis/0.3.3/utils/bilingual-bibliography.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/custom-cuti.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/custom-heading.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/custom-numbering.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/custom-tablex.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/datetime-display.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/double-underline.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/hline.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/indent.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/invisible-heading.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/justify-text.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/style.typ
  packages/preview/modern-nju-thesis/0.3.3/utils/unpairs.typ
Labels: update

#527 superb-pci:0.1.0
  packages/preview/superb-pci/0.1.0/LICENSE
  packages/preview/superb-pci/0.1.0/README.md
  packages/preview/superb-pci/0.1.0/formatters.typ
  packages/preview/superb-pci/0.1.0/lib.typ
  packages/preview/superb-pci/0.1.0/pci.csl
  packages/preview/superb-pci/0.1.0/template/main.typ
  packages/preview/superb-pci/0.1.0/template/pci-graph-small.png
  packages/preview/superb-pci/0.1.0/template/refs.bib
  packages/preview/superb-pci/0.1.0/thumbnail.png
  packages/preview/superb-pci/0.1.0/typst.toml
Labels: new

#529 outline-summaryst:0.1.0
  packages/preview/outline-summaryst/0.1.0/.gitignore
  packages/preview/outline-summaryst/0.1.0/LICENSE
  packages/preview/outline-summaryst/0.1.0/README.md
  packages/preview/outline-summaryst/0.1.0/examples/example.typ
  packages/preview/outline-summaryst/0.1.0/src/helpers.typ
  packages/preview/outline-summaryst/0.1.0/src/outline-summaryst.typ
  packages/preview/outline-summaryst/0.1.0/typst.toml
Labels: new

#536 iconic-salmon-svg:1.0.0
  packages/preview/iconic-salmon-svg/1.0.0/LICENSE
  packages/preview/iconic-salmon-svg/1.0.0/README.md
  packages/preview/iconic-salmon-svg/1.0.0/examples/examples.pdf
  packages/preview/iconic-salmon-svg/1.0.0/examples/examples.typ
  packages/preview/iconic-salmon-svg/1.0.0/examples/minimal_example.pdf
  packages/preview/iconic-salmon-svg/1.0.0/examples/minimal_example.typ
  packages/preview/iconic-salmon-svg/1.0.0/iconic-salmon-svg.typ
  packages/preview/iconic-salmon-svg/1.0.0/svg/Discord_icon_clyde_black_RGB.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/Discord_icon_clyde_blurple_RGB.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/Discord_icon_clyde_white_RGB.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/Facebook_Logo_Primary.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/GitLab_icon.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/Instagram_logo_2022.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/LinkedIn_icon.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/Logo_of_Twitter.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/ORCID_iD.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/README.md
  packages/preview/iconic-salmon-svg/1.0.0/svg/Stack_Exchange_icon.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/Stack_Overflow_icon.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/TikTok_Icon_Black.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/X_logo_2023.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/YouTube_full-color_icon_(2017).svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/codeberg-logo_icon_blue.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/codeberg-logo_icon_white.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/docker-mark-blue.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/docker-mark-white.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/github-mark-white.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/github-mark.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/gitlab-logo-500.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/gitlab-logo-600.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/mark-gradient-blue-bitbucket.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/mark-gradient-neutral-bitbucket.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/mark-gradient-white-bitbucket.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/skype-icon.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/sourceforge-seeklogo.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/vimeo-tile.svg
  packages/preview/iconic-salmon-svg/1.0.0/svg/xing-icon.svg
  packages/preview/iconic-salmon-svg/1.0.0/typst.toml
Labels: new

#545 minerva-report-fcfm:0.1.0
  packages/preview/minerva-report-fcfm/0.1.0/LICENSE
  packages/preview/minerva-report-fcfm/0.1.0/README.md
  packages/preview/minerva-report-fcfm/0.1.0/departamentos.typ
  packages/preview/minerva-report-fcfm/0.1.0/logos/adh.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/das.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dcc.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dfi.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dgf.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dic.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/die.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dii.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dim.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dimec.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/dimin.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/diqbm.svg
  packages/preview/minerva-report-fcfm/0.1.0/logos/geo.svg
  packages/preview/minerva-report-fcfm/0.1.0/minerva-report-fcfm.typ
  packages/preview/minerva-report-fcfm/0.1.0/template/images/README.md
  packages/preview/minerva-report-fcfm/0.1.0/template/main.typ
  packages/preview/minerva-report-fcfm/0.1.0/template/meta.typ
  packages/preview/minerva-report-fcfm/0.1.0/template/preamble.typ
  packages/preview/minerva-report-fcfm/0.1.0/thumbnail.png
  packages/preview/minerva-report-fcfm/0.1.0/typst.toml
Labels: new

#542 treet:0.1.1
  packages/preview/treet/0.1.1/CHANGELOG.md
  packages/preview/treet/0.1.1/LICENSE
  packages/preview/treet/0.1.1/README.md
  packages/preview/treet/0.1.1/lib.typ
  packages/preview/treet/0.1.1/typst.toml
Labels: update

#540 modern-technique-report:0.1.0
  packages/preview/modern-technique-report/0.1.0/LICENSE
  packages/preview/modern-technique-report/0.1.0/README.md
  packages/preview/modern-technique-report/0.1.0/lib.typ
  packages/preview/modern-technique-report/0.1.0/template/bg.jpg
  packages/preview/modern-technique-report/0.1.0/template/main.typ
  packages/preview/modern-technique-report/0.1.0/thumbnail.png
  packages/preview/modern-technique-report/0.1.0/typst.toml
Labels: new

#547 cheda-seu-thesis:0.2.0
  packages/preview/cheda-seu-thesis/0.2.0/.gitignore
  packages/preview/cheda-seu-thesis/0.2.0/LICENSE
  packages/preview/cheda-seu-thesis/0.2.0/README.md
  packages/preview/cheda-seu-thesis/0.2.0/init-files/bachelor_thesis.typ
  packages/preview/cheda-seu-thesis/0.2.0/init-files/degree_thesis.typ
  packages/preview/cheda-seu-thesis/0.2.0/init-files/demo_image/2-2a.png
  packages/preview/cheda-seu-thesis/0.2.0/init-files/demo_image/2-2b.png
  packages/preview/cheda-seu-thesis/0.2.0/init-files/demo_image/24h_rain.png
  packages/preview/cheda-seu-thesis/0.2.0/init-files/gb-t-7714-2015-numeric-seu.csl
  packages/preview/cheda-seu-thesis/0.2.0/init-files/ref.bib
  packages/preview/cheda-seu-thesis/0.2.0/init-files/thesis.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/assets/cover_school.png
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/assets/statement-bachelor.svg
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/assets/vi/seu.png
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/assets/vi/seu_logo.png
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/assets/vi/东南大学校标文字组合.png
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/gb-t-7714-2015-numeric-seu.csl
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/lib.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/pages/cover-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/pages/cover-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/pages/statement-bachelor-ic.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/pages/statement-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/pages/title-page-degree-cn-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/pages/title-page-degree-en-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/abstract-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/abstract-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/main-body-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/main-body-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/outline-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/outline-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/parts/terminology.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/templates/bachelor.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/templates/degree.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/bachelor-footnote.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/bilingual-bibliography.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/fake-par.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/figure-and-ref.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/fonts.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/numbering-tools.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/outline-tools.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/packages.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/set-bachelor.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/set-degree.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/show-heading.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/smart-pagebreak.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/states.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/thanks.typ
  packages/preview/cheda-seu-thesis/0.2.0/seu-thesis/utils/to-string.typ
  packages/preview/cheda-seu-thesis/0.2.0/thumbnail.webp
  packages/preview/cheda-seu-thesis/0.2.0/typst.toml
Labels: new

#548 suiji:0.3.0
  packages/preview/suiji/0.3.0/LICENSE
  packages/preview/suiji/0.3.0/README.md
  packages/preview/suiji/0.3.0/examples/matrix-rain.pdf
  packages/preview/suiji/0.3.0/examples/matrix-rain.png
  packages/preview/suiji/0.3.0/examples/matrix-rain.typ
  packages/preview/suiji/0.3.0/examples/random-bitmap-fast.pdf
  packages/preview/suiji/0.3.0/examples/random-bitmap-fast.typ
  packages/preview/suiji/0.3.0/examples/random-bitmap.pdf
  packages/preview/suiji/0.3.0/examples/random-bitmap.typ
  packages/preview/suiji/0.3.0/examples/random-permutation.pdf
  packages/preview/suiji/0.3.0/examples/random-permutation.png
  packages/preview/suiji/0.3.0/examples/random-permutation.typ
  packages/preview/suiji/0.3.0/examples/random-walk.pdf
  packages/preview/suiji/0.3.0/examples/random-walk.png
  packages/preview/suiji/0.3.0/examples/random-walk.typ
  packages/preview/suiji/0.3.0/src/chinese.typ
  packages/preview/suiji/0.3.0/src/lcg.typ
  packages/preview/suiji/0.3.0/src/lib.typ
  packages/preview/suiji/0.3.0/src/random-fast.typ
  packages/preview/suiji/0.3.0/src/random.typ
  packages/preview/suiji/0.3.0/src/taus.typ
  packages/preview/suiji/0.3.0/tests/test-choice-f.pdf
  packages/preview/suiji/0.3.0/tests/test-choice-f.typ
  packages/preview/suiji/0.3.0/tests/test-choice.pdf
  packages/preview/suiji/0.3.0/tests/test-choice.typ
  packages/preview/suiji/0.3.0/tests/test-discrete-f.pdf
  packages/preview/suiji/0.3.0/tests/test-discrete-f.typ
  packages/preview/suiji/0.3.0/tests/test-discrete.pdf
  packages/preview/suiji/0.3.0/tests/test-discrete.typ
  packages/preview/suiji/0.3.0/tests/test-integers-f.pdf
  packages/preview/suiji/0.3.0/tests/test-integers-f.typ
  packages/preview/suiji/0.3.0/tests/test-integers.pdf
  packages/preview/suiji/0.3.0/tests/test-integers.typ
  packages/preview/suiji/0.3.0/tests/test-normal-f.pdf
  packages/preview/suiji/0.3.0/tests/test-normal-f.typ
  packages/preview/suiji/0.3.0/tests/test-normal.pdf
  packages/preview/suiji/0.3.0/tests/test-normal.typ
  packages/preview/suiji/0.3.0/tests/test-rand-sc.pdf
  packages/preview/suiji/0.3.0/tests/test-rand-sc.typ
  packages/preview/suiji/0.3.0/tests/test-randi-f.pdf
  packages/preview/suiji/0.3.0/tests/test-randi-f.typ
  packages/preview/suiji/0.3.0/tests/test-random-f.pdf
  packages/preview/suiji/0.3.0/tests/test-random-f.typ
  packages/preview/suiji/0.3.0/tests/test-random.pdf
  packages/preview/suiji/0.3.0/tests/test-random.typ
  packages/preview/suiji/0.3.0/tests/test-shuffle-f.pdf
  packages/preview/suiji/0.3.0/tests/test-shuffle-f.typ
  packages/preview/suiji/0.3.0/tests/test-shuffle.pdf
  packages/preview/suiji/0.3.0/tests/test-shuffle.typ
  packages/preview/suiji/0.3.0/tests/test-uniform-f.pdf
  packages/preview/suiji/0.3.0/tests/test-uniform-f.typ
  packages/preview/suiji/0.3.0/tests/test-uniform.pdf
  packages/preview/suiji/0.3.0/tests/test-uniform.typ
  packages/preview/suiji/0.3.0/typst.toml
Labels: update

#549 curryst:0.3.0
  packages/preview/curryst/0.3.0/LICENSE
  packages/preview/curryst/0.3.0/README.md
  packages/preview/curryst/0.3.0/curryst.typ
  packages/preview/curryst/0.3.0/examples/math-formula.svg
  packages/preview/curryst/0.3.0/examples/math-formula.typ
  packages/preview/curryst/0.3.0/examples/natural-deduction.svg
  packages/preview/curryst/0.3.0/examples/natural-deduction.typ
  packages/preview/curryst/0.3.0/examples/rule-as-premise.svg
  packages/preview/curryst/0.3.0/examples/rule-as-premise.typ
  packages/preview/curryst/0.3.0/examples/usage.svg
  packages/preview/curryst/0.3.0/examples/usage.typ
  packages/preview/curryst/0.3.0/tests/README.md
  packages/preview/curryst/0.3.0/tests/test-01.png
  packages/preview/curryst/0.3.0/tests/test-02.png
  packages/preview/curryst/0.3.0/tests/test-03.png
  packages/preview/curryst/0.3.0/tests/test-04.png
  packages/preview/curryst/0.3.0/tests/test-05.png
  packages/preview/curryst/0.3.0/tests/test-06.png
  packages/preview/curryst/0.3.0/tests/test-07.png
  packages/preview/curryst/0.3.0/tests/test-08.png
  packages/preview/curryst/0.3.0/tests/test-09.png
  packages/preview/curryst/0.3.0/tests/test-10.png
  packages/preview/curryst/0.3.0/tests/test-11.png
  packages/preview/curryst/0.3.0/tests/test-12.png
  packages/preview/curryst/0.3.0/tests/test-13.png
  packages/preview/curryst/0.3.0/tests/test-14.png
  packages/preview/curryst/0.3.0/tests/test-15.png
  packages/preview/curryst/0.3.0/tests/test-16.png
  packages/preview/curryst/0.3.0/tests/test-17.png
  packages/preview/curryst/0.3.0/tests/test-18.png
  packages/preview/curryst/0.3.0/tests/test-19.png
  packages/preview/curryst/0.3.0/tests/test-20.png
  packages/preview/curryst/0.3.0/tests/test-21.png
  packages/preview/curryst/0.3.0/tests/test-22.png
  packages/preview/curryst/0.3.0/tests/test-23.png
  packages/preview/curryst/0.3.0/tests/test-24.png
  packages/preview/curryst/0.3.0/tests/test-25.png
  packages/preview/curryst/0.3.0/tests/tests.typ
  packages/preview/curryst/0.3.0/typst.toml
Labels: update

#534 bubble:0.1.0
  packages/preview/bubble/0.1.0/LICENSE
  packages/preview/bubble/0.1.0/README.md
  packages/preview/bubble/0.1.0/lib.typ
  packages/preview/bubble/0.1.0/template/logo.png
  packages/preview/bubble/0.1.0/template/main.typ
  packages/preview/bubble/0.1.0/thumbnail.png
  packages/preview/bubble/0.1.0/typst.toml
Labels: new

#471 light-cv:0.1.0
  packages/preview/light-cv/0.1.0/LICENSE
  packages/preview/light-cv/0.1.0/README.md
  packages/preview/light-cv/0.1.0/example.png
  packages/preview/light-cv/0.1.0/lib.typ
  packages/preview/light-cv/0.1.0/modules/header.typ
  packages/preview/light-cv/0.1.0/modules/section.typ
  packages/preview/light-cv/0.1.0/modules/skills.typ
  packages/preview/light-cv/0.1.0/modules/utils.typ
  packages/preview/light-cv/0.1.0/template/cv-en.typ
  packages/preview/light-cv/0.1.0/template/media/avatar.jpeg
  packages/preview/light-cv/0.1.0/template/media/ucla.png
  packages/preview/light-cv/0.1.0/template/settings/styles.typ
  packages/preview/light-cv/0.1.0/typst.toml
Labels: new

#551 problemst:0.1.0
  packages/preview/problemst/0.1.0/LICENSE.md
  packages/preview/problemst/0.1.0/README.md
  packages/preview/problemst/0.1.0/pset.typ
  packages/preview/problemst/0.1.0/template/main.typ
  packages/preview/problemst/0.1.0/thumbnail.png
  packages/preview/problemst/0.1.0/typst.toml
Labels: new

#554 modern-sustech-thesis:0.1.0
  packages/preview/modern-sustech-thesis/0.1.0/LICENSE
  packages/preview/modern-sustech-thesis/0.1.0/README.md
  packages/preview/modern-sustech-thesis/0.1.0/configs/SUSTech LOGO CN.svg
  packages/preview/modern-sustech-thesis/0.1.0/configs/SUSTech LOGO EN.svg
  packages/preview/modern-sustech-thesis/0.1.0/configs/abstract.typ
  packages/preview/modern-sustech-thesis/0.1.0/configs/commitment.typ
  packages/preview/modern-sustech-thesis/0.1.0/configs/cover.typ
  packages/preview/modern-sustech-thesis/0.1.0/configs/font.typ
  packages/preview/modern-sustech-thesis/0.1.0/configs/incs.typ
  packages/preview/modern-sustech-thesis/0.1.0/configs/outline.typ
  packages/preview/modern-sustech-thesis/0.1.0/lib.typ
  packages/preview/modern-sustech-thesis/0.1.0/sections/README.md
  packages/preview/modern-sustech-thesis/0.1.0/sections/content.typ
  packages/preview/modern-sustech-thesis/0.1.0/sections/refer.bib
  packages/preview/modern-sustech-thesis/0.1.0/thumbnail.png
  packages/preview/modern-sustech-thesis/0.1.0/typst.toml
Labels: new

#556 pesha:0.3.1
  packages/preview/pesha/0.3.1/LICENSE
  packages/preview/pesha/0.3.1/README.md
  packages/preview/pesha/0.3.1/lib.typ
  packages/preview/pesha/0.3.1/template/main.typ
  packages/preview/pesha/0.3.1/thumbnail.png
  packages/preview/pesha/0.3.1/typst.toml
Labels: update

#560 classic-jmlr:0.4.0
  packages/preview/classic-jmlr/0.4.0/LICENSE
  packages/preview/classic-jmlr/0.4.0/README.md
  packages/preview/classic-jmlr/0.4.0/jmlr.typ
  packages/preview/classic-jmlr/0.4.0/template/appendix.typ
  packages/preview/classic-jmlr/0.4.0/template/blindtext.typ
  packages/preview/classic-jmlr/0.4.0/template/main.bib
  packages/preview/classic-jmlr/0.4.0/template/main.typ
  packages/preview/classic-jmlr/0.4.0/thumbnail.png
  packages/preview/classic-jmlr/0.4.0/typst.toml
Labels: new

#564 fontawesome:0.2.0
  packages/preview/fontawesome/0.2.0/LICENSE
  packages/preview/fontawesome/0.2.0/README.md
  packages/preview/fontawesome/0.2.0/lib-gen.typ
  packages/preview/fontawesome/0.2.0/lib-impl.typ
  packages/preview/fontawesome/0.2.0/lib.typ
  packages/preview/fontawesome/0.2.0/typst.toml
Labels: update

#573 Minor fix for iconic-salmon-svg
  packages/preview/iconic-salmon-svg/1.0.0/README.md
Labels: minor fix

#557 minerva-report-fcfm:0.2.0
  packages/preview/minerva-report-fcfm/0.2.0/CHANGELOG.md
  packages/preview/minerva-report-fcfm/0.2.0/LICENSE
  packages/preview/minerva-report-fcfm/0.2.0/README.md
  packages/preview/minerva-report-fcfm/0.2.0/departamentos.typ
  packages/preview/minerva-report-fcfm/0.2.0/logos/adh.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/das.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dcc.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dfi.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dgf.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dic.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/die.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dii.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dim.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dimec.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/dimin.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/diqbm.svg
  packages/preview/minerva-report-fcfm/0.2.0/logos/geo.svg
  packages/preview/minerva-report-fcfm/0.2.0/minerva-report-fcfm.typ
  packages/preview/minerva-report-fcfm/0.2.0/state.typ
  packages/preview/minerva-report-fcfm/0.2.0/template/images/README.md
  packages/preview/minerva-report-fcfm/0.2.0/template/main.typ
  packages/preview/minerva-report-fcfm/0.2.0/template/meta.typ
  packages/preview/minerva-report-fcfm/0.2.0/template/preamble.typ
  packages/preview/minerva-report-fcfm/0.2.0/thumbnail.png
  packages/preview/minerva-report-fcfm/0.2.0/typst.toml
Labels: update

#570 modern-sustech-thesis:0.1.1
  packages/preview/modern-sustech-thesis/0.1.1/LICENSE
  packages/preview/modern-sustech-thesis/0.1.1/README.md
  packages/preview/modern-sustech-thesis/0.1.1/configs/SUSTech LOGO CN.svg
  packages/preview/modern-sustech-thesis/0.1.1/configs/SUSTech LOGO EN.svg
  packages/preview/modern-sustech-thesis/0.1.1/configs/abstract.typ
  packages/preview/modern-sustech-thesis/0.1.1/configs/commitment.typ
  packages/preview/modern-sustech-thesis/0.1.1/configs/cover.typ
  packages/preview/modern-sustech-thesis/0.1.1/configs/font.typ
  packages/preview/modern-sustech-thesis/0.1.1/configs/incs.typ
  packages/preview/modern-sustech-thesis/0.1.1/configs/outline.typ
  packages/preview/modern-sustech-thesis/0.1.1/lib.typ
  packages/preview/modern-sustech-thesis/0.1.1/sections/README.md
  packages/preview/modern-sustech-thesis/0.1.1/sections/content.typ
  packages/preview/modern-sustech-thesis/0.1.1/sections/refer.bib
  packages/preview/modern-sustech-thesis/0.1.1/thumbnail.png
  packages/preview/modern-sustech-thesis/0.1.1/typst.toml
Labels: update

#584 board-n-pieces:0.2.0
  packages/preview/board-n-pieces/0.2.0/LICENSE
  packages/preview/board-n-pieces/0.2.0/README.md
  packages/preview/board-n-pieces/0.2.0/assets/LICENSE
  packages/preview/board-n-pieces/0.2.0/assets/bb.svg
  packages/preview/board-n-pieces/0.2.0/assets/bw.svg
  packages/preview/board-n-pieces/0.2.0/assets/kb.svg
  packages/preview/board-n-pieces/0.2.0/assets/kw.svg
  packages/preview/board-n-pieces/0.2.0/assets/nb.svg
  packages/preview/board-n-pieces/0.2.0/assets/nw.svg
  packages/preview/board-n-pieces/0.2.0/assets/pb.svg
  packages/preview/board-n-pieces/0.2.0/assets/pw.svg
  packages/preview/board-n-pieces/0.2.0/assets/qb.svg
  packages/preview/board-n-pieces/0.2.0/assets/qw.svg
  packages/preview/board-n-pieces/0.2.0/assets/rb.svg
  packages/preview/board-n-pieces/0.2.0/assets/rw.svg
  packages/preview/board-n-pieces/0.2.0/chess-sym.typ
  packages/preview/board-n-pieces/0.2.0/examples/example-1.svg
  packages/preview/board-n-pieces/0.2.0/examples/example-2.svg
  packages/preview/board-n-pieces/0.2.0/examples/example-3.svg
  packages/preview/board-n-pieces/0.2.0/examples/example-4.svg
  packages/preview/board-n-pieces/0.2.0/examples/example-5.svg
  packages/preview/board-n-pieces/0.2.0/internals.typ
  packages/preview/board-n-pieces/0.2.0/lib.typ
  packages/preview/board-n-pieces/0.2.0/plugin.wasm
  packages/preview/board-n-pieces/0.2.0/typst.toml
Labels: update

#592 cheda-seu-thesis:0.2.1
  packages/preview/cheda-seu-thesis/0.2.1/.gitignore
  packages/preview/cheda-seu-thesis/0.2.1/LICENSE
  packages/preview/cheda-seu-thesis/0.2.1/README.md
  packages/preview/cheda-seu-thesis/0.2.1/init-files/bachelor_thesis.typ
  packages/preview/cheda-seu-thesis/0.2.1/init-files/degree_thesis.typ
  packages/preview/cheda-seu-thesis/0.2.1/init-files/demo_image/2-2a.png
  packages/preview/cheda-seu-thesis/0.2.1/init-files/demo_image/2-2b.png
  packages/preview/cheda-seu-thesis/0.2.1/init-files/demo_image/24h_rain.png
  packages/preview/cheda-seu-thesis/0.2.1/init-files/gb-t-7714-2015-numeric-seu.csl
  packages/preview/cheda-seu-thesis/0.2.1/init-files/ref.bib
  packages/preview/cheda-seu-thesis/0.2.1/init-files/thesis.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/assets/cover_school.png
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/assets/vi/seu.png
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/assets/vi/seu_logo.png
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/assets/vi/东南大学校标文字组合.png
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/lib.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/pages/cover-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/pages/cover-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/pages/statement-bachelor-ic.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/pages/statement-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/pages/title-page-degree-cn-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/pages/title-page-degree-en-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/abstract-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/abstract-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/main-body-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/main-body-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/outline-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/outline-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/parts/terminology.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/templates/bachelor.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/templates/degree.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/bachelor-footnote.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/bilingual-bibliography.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/fake-par.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/figure-and-ref.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/fonts.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/numbering-tools.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/outline-tools.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/packages.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/set-bachelor.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/set-degree.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/show-heading.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/smart-pagebreak.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/states.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/thanks.typ
  packages/preview/cheda-seu-thesis/0.2.1/seu-thesis/utils/to-string.typ
  packages/preview/cheda-seu-thesis/0.2.1/thumbnail.webp
  packages/preview/cheda-seu-thesis/0.2.1/typst.toml
Labels: update

#593 valkyrie:0.1.1
  packages/preview/valkyrie/0.1.1/CHANGELOG.md
  packages/preview/valkyrie/0.1.1/LICENSE
  packages/preview/valkyrie/0.1.1/README.md
  packages/preview/valkyrie/0.1.1/docs/manual.pdf
  packages/preview/valkyrie/0.1.1/src/base-type.typ
  packages/preview/valkyrie/0.1.1/src/ctx.typ
  packages/preview/valkyrie/0.1.1/src/lib.typ
  packages/preview/valkyrie/0.1.1/src/types.typ
  packages/preview/valkyrie/0.1.1/src/types/any.typ
  packages/preview/valkyrie/0.1.1/src/types/array.typ
  packages/preview/valkyrie/0.1.1/src/types/dictionary.typ
  packages/preview/valkyrie/0.1.1/src/types/logical.typ
  packages/preview/valkyrie/0.1.1/src/types/number.typ
  packages/preview/valkyrie/0.1.1/src/types/string.typ
  packages/preview/valkyrie/0.1.1/src/types/tuple.typ
  packages/preview/valkyrie/0.1.1/typst.toml
Labels: update

#595 gentle-clues:0.8.0
  packages/preview/gentle-clues/0.8.0/CHANGELOG.md
  packages/preview/gentle-clues/0.8.0/LICENSE
  packages/preview/gentle-clues/0.8.0/README.md
  packages/preview/gentle-clues/0.8.0/docs.pdf
  packages/preview/gentle-clues/0.8.0/docs.typ
  packages/preview/gentle-clues/0.8.0/gc_overview.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/abstract.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/bell.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/bookmark.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/checkbox.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/crossmark.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/danger.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/example.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/excl.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/flag.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/info.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/lightbulb.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/questionmark.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/quote.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/task.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/tip.svg
  packages/preview/gentle-clues/0.8.0/lib/assets/warning.svg
  packages/preview/gentle-clues/0.8.0/lib/clues.typ
  packages/preview/gentle-clues/0.8.0/lib/lang.toml
  packages/preview/gentle-clues/0.8.0/lib/lib.typ
  packages/preview/gentle-clues/0.8.0/lib/predefined.typ
  packages/preview/gentle-clues/0.8.0/typst.toml
Labels: update

#603 mantys:0.1.3
  packages/preview/mantys/0.1.3/LICENSE
  packages/preview/mantys/0.1.3/README.md
  packages/preview/mantys/0.1.3/docs/assets/headline-example.png
  packages/preview/mantys/0.1.3/docs/assets/thumbnail.png
  packages/preview/mantys/0.1.3/docs/mantys-manual.pdf
  packages/preview/mantys/0.1.3/docs/mantys-manual.typ
  packages/preview/mantys/0.1.3/src/api.typ
  packages/preview/mantys/0.1.3/src/mantys.typ
  packages/preview/mantys/0.1.3/src/mty-tidy.typ
  packages/preview/mantys/0.1.3/src/mty.typ
  packages/preview/mantys/0.1.3/src/theme.typ
  packages/preview/mantys/0.1.3/tbump.toml
  packages/preview/mantys/0.1.3/template/manual.typ
  packages/preview/mantys/0.1.3/typst.toml
Labels: update

#562 modernpro-coverletter:0.0.1
  packages/preview/modernpro-coverletter/0.0.1/README.md
  packages/preview/modernpro-coverletter/0.0.1/modernpro-coverletter.typ
  packages/preview/modernpro-coverletter/0.0.1/template/main.typ
  packages/preview/modernpro-coverletter/0.0.1/thumbnail.png
  packages/preview/modernpro-coverletter/0.0.1/typst.toml
Labels: new

#567 acrotastic:0.1.0
  packages/preview/acrotastic/0.1.0/LICENSE
  packages/preview/acrotastic/0.1.0/README.md
  packages/preview/acrotastic/0.1.0/acrotastic.typ
  packages/preview/acrotastic/0.1.0/typst.toml
Labels: new

#566 tuhi-course-poster-vuw:0.1.0
  packages/preview/tuhi-course-poster-vuw/0.1.0/LICENSE
  packages/preview/tuhi-course-poster-vuw/0.1.0/README.md
  packages/preview/tuhi-course-poster-vuw/0.1.0/template/images/esca101.jpg
  packages/preview/tuhi-course-poster-vuw/0.1.0/template/logo.svg
  packages/preview/tuhi-course-poster-vuw/0.1.0/template/main.typ
  packages/preview/tuhi-course-poster-vuw/0.1.0/thumbnail.png
  packages/preview/tuhi-course-poster-vuw/0.1.0/tuhi-course-poster-vuw.typ
  packages/preview/tuhi-course-poster-vuw/0.1.0/typst.toml
Labels: new

#598 whalogen:0.2.0
  packages/preview/whalogen/0.2.0/LICENSE
  packages/preview/whalogen/0.2.0/README.md
  packages/preview/whalogen/0.2.0/gallery/example.png
  packages/preview/whalogen/0.2.0/gallery/example.typ
  packages/preview/whalogen/0.2.0/lib.typ
  packages/preview/whalogen/0.2.0/manual.pdf
  packages/preview/whalogen/0.2.0/manual.typ
  packages/preview/whalogen/0.2.0/typst.toml
Labels: update
