Repository typst/packages, pull requests merged in 2024-09, with the labels that each got.

#929 bone-resume:0.3.0
  packages/preview/bone-resume/0.3.0/LICENSE
  packages/preview/bone-resume/0.3.0/README.md
  packages/preview/bone-resume/0.3.0/lib.typ
  packages/preview/bone-resume/0.3.0/template/main.typ
  packages/preview/bone-resume/0.3.0/thumbnail.png
  packages/preview/bone-resume/0.3.0/typst.toml
Labels: update

#905 minimal-presentation:0.1.0
  packages/preview/minimal-presentation/0.1.0/LICENSE
  packages/preview/minimal-presentation/0.1.0/README.md
  packages/preview/minimal-presentation/0.1.0/lib.typ
  packages/preview/minimal-presentation/0.1.0/template/image_1.jpg
  packages/preview/minimal-presentation/0.1.0/template/logo.svg
  packages/preview/minimal-presentation/0.1.0/template/logo_light.svg
  packages/preview/minimal-presentation/0.1.0/template/main.typ
  packages/preview/minimal-presentation/0.1.0/thumbnail.png
  packages/preview/minimal-presentation/0.1.0/typst.toml
Labels: new

#930 oasis-align:0.1.0
  packages/preview/oasis-align/0.1.0/LICENSE
  packages/preview/oasis-align/0.1.0/README.md
  packages/preview/oasis-align/0.1.0/examples/graph-visualization.svg
  packages/preview/oasis-align/0.1.0/examples/image-with-image.gif
  packages/preview/oasis-align/0.1.0/examples/image-with-text.gif
  packages/preview/oasis-align/0.1.0/examples/text-with-text.gif
  packages/preview/oasis-align/0.1.0/oasis-align.typ
  packages/preview/oasis-align/0.1.0/typst.toml
Labels: new

#920 acrotastic:0.1.1
  packages/preview/acrotastic/0.1.1/LICENSE
  packages/preview/acrotastic/0.1.1/README.md
  packages/preview/acrotastic/0.1.1/acrotastic.typ
  packages/preview/acrotastic/0.1.1/typst.toml
Labels: update

#934 modern-cv:0.6.0
  packages/preview/modern-cv/0.6.0/LICENSE
  packages/preview/modern-cv/0.6.0/README.md
  packages/preview/modern-cv/0.6.0/assets/images/coverletter.png
  packages/preview/modern-cv/0.6.0/assets/images/coverletter2.png
  packages/preview/modern-cv/0.6.0/assets/images/resume.png
  packages/preview/modern-cv/0.6.0/assets/images/resume2.png
  packages/preview/modern-cv/0.6.0/assets/images/typst_web_editor.png
  packages/preview/modern-cv/0.6.0/lang.toml
  packages/preview/modern-cv/0.6.0/lib.typ
  packages/preview/modern-cv/0.6.0/template/coverletter.typ
  packages/preview/modern-cv/0.6.0/template/coverletter2.typ
  packages/preview/modern-cv/0.6.0/template/profile.png
  packages/preview/modern-cv/0.6.0/template/resume.typ
  packages/preview/modern-cv/0.6.0/typst.toml
Labels: update

#937 touying:0.5.1 and touying-aqua:0.5.1
  packages/preview/touying-aqua/0.5.1/README.md
  packages/preview/touying-aqua/0.5.1/lib.typ
  packages/preview/touying-aqua/0.5.1/template/main.typ
  packages/preview/touying-aqua/0.5.1/thumbnail.png
  packages/preview/touying-aqua/0.5.1/typst.toml
  packages/preview/touying/0.5.1/.gitignore
  packages/preview/touying/0.5.1/LICENSE
  packages/preview/touying/0.5.1/README.md
  packages/preview/touying/0.5.1/changelog.md
  packages/preview/touying/0.5.1/examples/aqua-zh.typ
  packages/preview/touying/0.5.1/examples/aqua.typ
  packages/preview/touying/0.5.1/examples/default.typ
  packages/preview/touying/0.5.1/examples/dewdrop.typ
  packages/preview/touying/0.5.1/examples/example.typ
  packages/preview/touying/0.5.1/examples/metropolis.typ
  packages/preview/touying/0.5.1/examples/simple.typ
  packages/preview/touying/0.5.1/examples/stargazer.typ
  packages/preview/touying/0.5.1/examples/university.typ
  packages/preview/touying/0.5.1/lib.typ
  packages/preview/touying/0.5.1/src/components.typ
  packages/preview/touying/0.5.1/src/configs.typ
  packages/preview/touying/0.5.1/src/core.typ
  packages/preview/touying/0.5.1/src/exports.typ
  packages/preview/touying/0.5.1/src/magic.typ
  packages/preview/touying/0.5.1/src/pdfpc.typ
  packages/preview/touying/0.5.1/src/slides.typ
  packages/preview/touying/0.5.1/src/utils.typ
  packages/preview/touying/0.5.1/themes/aqua.typ
  packages/preview/touying/0.5.1/themes/default.typ
  packages/preview/touying/0.5.1/themes/dewdrop.typ
  packages/preview/touying/0.5.1/themes/metropolis.typ
  packages/preview/touying/0.5.1/themes/simple.typ
  packages/preview/touying/0.5.1/themes/stargazer.typ
  packages/preview/touying/0.5.1/themes/themes.typ
  packages/preview/touying/0.5.1/themes/university.typ
  packages/preview/touying/0.5.1/typst.toml
Labels: update

#932 weave:0.1.0
  packages/preview/weave/0.1.0/.gitignore
  packages/preview/weave/0.1.0/LICENSE
  packages/preview/weave/0.1.0/README.md
  packages/preview/weave/0.1.0/lib.typ
  packages/preview/weave/0.1.0/tests/README.md
  packages/preview/weave/0.1.0/tests/tests.typ
  packages/preview/weave/0.1.0/typst.toml
Labels: new

#936 touying-buaa:0.2.0
  packages/preview/touying-buaa/0.2.0/LICENSE
  packages/preview/touying-buaa/0.2.0/README.md
  packages/preview/touying-buaa/0.2.0/assets/vi/buaa-logo.svg
  packages/preview/touying-buaa/0.2.0/examples/main.typ
  packages/preview/touying-buaa/0.2.0/lib.typ
  packages/preview/touying-buaa/0.2.0/template/main.typ
  packages/preview/touying-buaa/0.2.0/thumbnail.webp
  packages/preview/touying-buaa/0.2.0/typst.toml
Labels: update

#944 gentle-clues:1.0.0
  packages/preview/gentle-clues/1.0.0/LICENSE
  packages/preview/gentle-clues/1.0.0/README.md
  packages/preview/gentle-clues/1.0.0/gc-overview.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/abstract.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/bell.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/checkbox.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/code.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/conclusion.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/crossmark.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/danger.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/excl.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/experiment.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/flag.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/info.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/lightbulb.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/questionmark.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/quote.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/simple-graph.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/task.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/tip.svg
  packages/preview/gentle-clues/1.0.0/lib/assets/warning.svg
  packages/preview/gentle-clues/1.0.0/lib/clues.typ
  packages/preview/gentle-clues/1.0.0/lib/lang.toml
  packages/preview/gentle-clues/1.0.0/lib/lib.typ
  packages/preview/gentle-clues/1.0.0/lib/predefined.typ
  packages/preview/gentle-clues/1.0.0/lib/theme.typ
  packages/preview/gentle-clues/1.0.0/typst.toml
Labels: update

#946 cheq:0.2.0
  packages/preview/cheq/0.2.0/LICENSE
  packages/preview/cheq/0.2.0/README.md
  packages/preview/cheq/0.2.0/examples/custom-styles.png
  packages/preview/cheq/0.2.0/examples/custom-styles.typ
  packages/preview/cheq/0.2.0/examples/example.png
  packages/preview/cheq/0.2.0/examples/example.typ
  packages/preview/cheq/0.2.0/lib.typ
  packages/preview/cheq/0.2.0/typst.toml
Labels: update

#950 tiaoma:0.2.1
  packages/preview/tiaoma/0.2.1/LICENSE
  packages/preview/tiaoma/0.2.1/README.md
  packages/preview/tiaoma/0.2.1/example.svg
  packages/preview/tiaoma/0.2.1/example.typ
  packages/preview/tiaoma/0.2.1/lib.typ
  packages/preview/tiaoma/0.2.1/license.html
  packages/preview/tiaoma/0.2.1/manual.pdf
  packages/preview/tiaoma/0.2.1/manual.typ
  packages/preview/tiaoma/0.2.1/tidy_style.typ
  packages/preview/tiaoma/0.2.1/typst.toml
  packages/preview/tiaoma/0.2.1/zint_typst_plugin.wasm
Labels: update

#952 quill:0.4.0
  packages/preview/quill/0.4.0/LICENSE
  packages/preview/quill/0.4.0/README.md
  packages/preview/quill/0.4.0/docs/architecture.md
  packages/preview/quill/0.4.0/docs/images/bell.svg
  packages/preview/quill/0.4.0/docs/images/composition.svg
  packages/preview/quill/0.4.0/docs/images/gallery.svg
  packages/preview/quill/0.4.0/docs/images/logo.svg
  packages/preview/quill/0.4.0/docs/images/phase-estimation.svg
  packages/preview/quill/0.4.0/docs/images/qft.svg
  packages/preview/quill/0.4.0/docs/images/teleportation.svg
  packages/preview/quill/0.4.0/src/arrow.typ
  packages/preview/quill/0.4.0/src/decorations.typ
  packages/preview/quill/0.4.0/src/draw-functions.typ
  packages/preview/quill/0.4.0/src/gates.typ
  packages/preview/quill/0.4.0/src/layout.typ
  packages/preview/quill/0.4.0/src/length-helpers.typ
  packages/preview/quill/0.4.0/src/process-args.typ
  packages/preview/quill/0.4.0/src/quantum-circuit.typ
  packages/preview/quill/0.4.0/src/quill.typ
  packages/preview/quill/0.4.0/src/tequila-impl.typ
  packages/preview/quill/0.4.0/src/tequila.typ
  packages/preview/quill/0.4.0/src/utility.typ
  packages/preview/quill/0.4.0/src/verifications.typ
  packages/preview/quill/0.4.0/typst.toml
Labels: update

#927 not-tudabeamer-2023:0.1.0
  packages/preview/not-tudabeamer-2023/0.1.0/.gitignore
  packages/preview/not-tudabeamer-2023/0.1.0/LICENSE
  packages/preview/not-tudabeamer-2023/0.1.0/README.md
  packages/preview/not-tudabeamer-2023/0.1.0/lib.typ
  packages/preview/not-tudabeamer-2023/0.1.0/template/main.typ
  packages/preview/not-tudabeamer-2023/0.1.0/thumbnail.webp
  packages/preview/not-tudabeamer-2023/0.1.0/typst.toml
Labels: new

#938 modern-hsh-thesis:1.0.0
  packages/preview/modern-hsh-thesis/1.0.0/CHANGELOG.md
  packages/preview/modern-hsh-thesis/1.0.0/LICENSE
  packages/preview/modern-hsh-thesis/1.0.0/README.md
  packages/preview/modern-hsh-thesis/1.0.0/docs/manual.pdf
  packages/preview/modern-hsh-thesis/1.0.0/src/Logo.svg
  packages/preview/modern-hsh-thesis/1.0.0/src/Wortmarke.svg
  packages/preview/modern-hsh-thesis/1.0.0/src/lib.typ
  packages/preview/modern-hsh-thesis/1.0.0/template/Code/code.typ
  packages/preview/modern-hsh-thesis/1.0.0/template/abbreviations.typ
  packages/preview/modern-hsh-thesis/1.0.0/template/chapters/1-einleitung.typ
  packages/preview/modern-hsh-thesis/1.0.0/template/customFunctions.typ
  packages/preview/modern-hsh-thesis/1.0.0/template/main.typ
  packages/preview/modern-hsh-thesis/1.0.0/template/sources.bib
  packages/preview/modern-hsh-thesis/1.0.0/template/sources.yaml
  packages/preview/modern-hsh-thesis/1.0.0/thumbnail.png
  packages/preview/modern-hsh-thesis/1.0.0/typst.toml
Labels: new

#945 rubber-article:0.1.0
  packages/preview/rubber-article/0.1.0/CHANGELOG.md
  packages/preview/rubber-article/0.1.0/LICENSE
  packages/preview/rubber-article/0.1.0/README.md
  packages/preview/rubber-article/0.1.0/src/lib.typ
  packages/preview/rubber-article/0.1.0/template/main.typ
  packages/preview/rubber-article/0.1.0/thumbnail.png
  packages/preview/rubber-article/0.1.0/typst.toml
Labels: new

#951 casual-szu-report:0.1.0
  packages/preview/casual-szu-report/0.1.0/LICENSE
  packages/preview/casual-szu-report/0.1.0/README.md
  packages/preview/casual-szu-report/0.1.0/lib.typ
  packages/preview/casual-szu-report/0.1.0/template/img/AnimalWell.png
  packages/preview/casual-szu-report/0.1.0/template/main.typ
  packages/preview/casual-szu-report/0.1.0/template/refs.bib
  packages/preview/casual-szu-report/0.1.0/thumbnail.png
  packages/preview/casual-szu-report/0.1.0/typst.toml
Labels: new

#956 unofficial-fhict-document-template:1.0.1
  packages/preview/unofficial-fhict-document-template/1.0.1/LICENSE
  packages/preview/unofficial-fhict-document-template/1.0.1/README.md
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/DE-flag.svg
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/EN-flag.svg
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/ES-flag.svg
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/FR-flag.svg
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/NL-flag.svg
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/NOTICE
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/fontys-for-society.png
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/for-society.png
  packages/preview/unofficial-fhict-document-template/1.0.1/assets/language.yml
  packages/preview/unofficial-fhict-document-template/1.0.1/lib.typ
  packages/preview/unofficial-fhict-document-template/1.0.1/showcase-r.png
  packages/preview/unofficial-fhict-document-template/1.0.1/template/main.typ
  packages/preview/unofficial-fhict-document-template/1.0.1/thumbnail.png
  packages/preview/unofficial-fhict-document-template/1.0.1/typst.toml
Labels: update

#957 equate:0.2.1
  packages/preview/equate/0.2.1/LICENSE
  packages/preview/equate/0.2.1/README.md
  packages/preview/equate/0.2.1/assets/example-1.svg
  packages/preview/equate/0.2.1/assets/example-2.svg
  packages/preview/equate/0.2.1/assets/example-local.svg
  packages/preview/equate/0.2.1/assets/example-local.typ
  packages/preview/equate/0.2.1/assets/example.typ
  packages/preview/equate/0.2.1/src/equate.typ
  packages/preview/equate/0.2.1/src/lib.typ
  packages/preview/equate/0.2.1/typst.toml
Labels: update

#958 tgm-hit-thesis:0.1.1
  packages/preview/tgm-hit-thesis/0.1.1/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.1.1/LICENSE
  packages/preview/tgm-hit-thesis/0.1.1/README.md
  packages/preview/tgm-hit-thesis/0.1.1/docs/manual.pdf
  packages/preview/tgm-hit-thesis/0.1.1/example.pdf
  packages/preview/tgm-hit-thesis/0.1.1/src/assets.typ
  packages/preview/tgm-hit-thesis/0.1.1/src/assets/logo-left.png
  packages/preview/tgm-hit-thesis/0.1.1/src/assets/logo-right.png
  packages/preview/tgm-hit-thesis/0.1.1/src/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.1.1/src/glossary.typ
  packages/preview/tgm-hit-thesis/0.1.1/src/l10n.toml
  packages/preview/tgm-hit-thesis/0.1.1/src/l10n.typ
  packages/preview/tgm-hit-thesis/0.1.1/src/lib.typ
  packages/preview/tgm-hit-thesis/0.1.1/src/utils.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/assets.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/assets/logo.png
  packages/preview/tgm-hit-thesis/0.1.1/template/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/bibliography.bib
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/conclusio.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/danksagung.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/einleitung.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/implementierung.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/konzept.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/kurzfassung.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/retrospektive.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/studie.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/chapters/vorwort.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/glossaries.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/lib.typ
  packages/preview/tgm-hit-thesis/0.1.1/template/main.typ
  packages/preview/tgm-hit-thesis/0.1.1/thumbnail.png
  packages/preview/tgm-hit-thesis/0.1.1/typst.toml
Labels: update

#943 miage-rapide-tp:0.1.0
  packages/preview/miage-rapide-tp/0.1.0/README.md
  packages/preview/miage-rapide-tp/0.1.0/assets/MIAGE.png
  packages/preview/miage-rapide-tp/0.1.0/lib.typ
  packages/preview/miage-rapide-tp/0.1.0/template/code/example.sql
  packages/preview/miage-rapide-tp/0.1.0/template/code/main.py
  packages/preview/miage-rapide-tp/0.1.0/template/main.typ
  packages/preview/miage-rapide-tp/0.1.0/thumbnail.png
  packages/preview/miage-rapide-tp/0.1.0/typst.toml
Labels: new

#947 classy-german-invoice:0.2.0
  packages/preview/classy-german-invoice/0.2.0/LICENSE
  packages/preview/classy-german-invoice/0.2.0/README.md
  packages/preview/classy-german-invoice/0.2.0/lib.typ
  packages/preview/classy-german-invoice/0.2.0/template/main.typ
  packages/preview/classy-german-invoice/0.2.0/thumbnail.png
  packages/preview/classy-german-invoice/0.2.0/typst.toml
Labels: new

#960 ctxjs:0.1.0
  packages/preview/ctxjs/0.1.0/LICENSE
  packages/preview/ctxjs/0.1.0/README.md
  packages/preview/ctxjs/0.1.0/ctxjs.wasm
  packages/preview/ctxjs/0.1.0/lib.typ
  packages/preview/ctxjs/0.1.0/typst.toml
Labels: new

#961 README fix for tiaoma:0.2.0 and tiamoa:0.2.1
  packages/preview/tiaoma/0.2.0/README.md
  packages/preview/tiaoma/0.2.1/README.md
Labels: minor fix, blocked

#962 clear-iclr:0.4.0
  packages/preview/clear-iclr/0.4.0/LICENSE
  packages/preview/clear-iclr/0.4.0/README.md
  packages/preview/clear-iclr/0.4.0/iclr.csl
  packages/preview/clear-iclr/0.4.0/iclr.typ
  packages/preview/clear-iclr/0.4.0/iclr2025.typ
  packages/preview/clear-iclr/0.4.0/template/logo.typ
  packages/preview/clear-iclr/0.4.0/template/main.bib
  packages/preview/clear-iclr/0.4.0/template/main.typ
  packages/preview/clear-iclr/0.4.0/thumbnail.png
  packages/preview/clear-iclr/0.4.0/typst.toml
Labels: new

#964 miage-rapide-tp:0.1.1
  packages/preview/miage-rapide-tp/0.1.1/README.md
  packages/preview/miage-rapide-tp/0.1.1/assets/MIAGE.png
  packages/preview/miage-rapide-tp/0.1.1/lib.typ
  packages/preview/miage-rapide-tp/0.1.1/template/code/example.sql
  packages/preview/miage-rapide-tp/0.1.1/template/code/main.py
  packages/preview/miage-rapide-tp/0.1.1/template/main.typ
  packages/preview/miage-rapide-tp/0.1.1/thumbnail.png
  packages/preview/miage-rapide-tp/0.1.1/typst.toml
Labels: update

#965 truthfy:0.5.0
  packages/preview/truthfy/0.5.0/LICENSE
  packages/preview/truthfy/0.5.0/README.md
  packages/preview/truthfy/0.5.0/example.pdf
  packages/preview/truthfy/0.5.0/example.typ
  packages/preview/truthfy/0.5.0/main.typ
  packages/preview/truthfy/0.5.0/typst.toml
Labels: update

#966 aero-check:0.1.1
  packages/preview/aero-check/0.1.1/LICENSE
  packages/preview/aero-check/0.1.1/README.md
  packages/preview/aero-check/0.1.1/lib.typ
  packages/preview/aero-check/0.1.1/template/main.typ
  packages/preview/aero-check/0.1.1/thumbnail.png
  packages/preview/aero-check/0.1.1/typst.toml
Labels: update

#970 Minor fix for tgm-hit-thesis:0.1.1 (changelog and manual correction)
  packages/preview/tgm-hit-thesis/0.1.1/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.1.1/docs/manual.pdf
Labels: minor fix

#972 outrageous:0.2.0
  packages/preview/outrageous/0.2.0/LICENSE
  packages/preview/outrageous/0.2.0/README.md
  packages/preview/outrageous/0.2.0/example-custom.png
  packages/preview/outrageous/0.2.0/example-default.png
  packages/preview/outrageous/0.2.0/examples/basic.typ
  packages/preview/outrageous/0.2.0/examples/rush.pdf
  packages/preview/outrageous/0.2.0/examples/rush.typ
  packages/preview/outrageous/0.2.0/outrageous.typ
  packages/preview/outrageous/0.2.0/typst.toml
Labels: update

#974 tgm-hit-thesis:0.1.2
  packages/preview/tgm-hit-thesis/0.1.2/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.1.2/LICENSE
  packages/preview/tgm-hit-thesis/0.1.2/README.md
  packages/preview/tgm-hit-thesis/0.1.2/docs/manual.pdf
  packages/preview/tgm-hit-thesis/0.1.2/example.pdf
  packages/preview/tgm-hit-thesis/0.1.2/src/assets.typ
  packages/preview/tgm-hit-thesis/0.1.2/src/assets/logo-left.png
  packages/preview/tgm-hit-thesis/0.1.2/src/assets/logo-right.png
  packages/preview/tgm-hit-thesis/0.1.2/src/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.1.2/src/glossary.typ
  packages/preview/tgm-hit-thesis/0.1.2/src/l10n.toml
  packages/preview/tgm-hit-thesis/0.1.2/src/l10n.typ
  packages/preview/tgm-hit-thesis/0.1.2/src/lib.typ
  packages/preview/tgm-hit-thesis/0.1.2/src/utils.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/assets.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/assets/logo.png
  packages/preview/tgm-hit-thesis/0.1.2/template/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/bibliography.bib
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/conclusio.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/danksagung.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/einleitung.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/implementierung.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/konzept.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/kurzfassung.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/retrospektive.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/studie.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/chapters/vorwort.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/glossaries.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/lib.typ
  packages/preview/tgm-hit-thesis/0.1.2/template/main.typ
  packages/preview/tgm-hit-thesis/0.1.2/thumbnail.png
  packages/preview/tgm-hit-thesis/0.1.2/typst.toml
Labels: update

#948 light-report-uia:0.1.0
  packages/preview/light-report-uia/0.1.0/LICENSE
  packages/preview/light-report-uia/0.1.0/README.md
  packages/preview/light-report-uia/0.1.0/lib.typ
  packages/preview/light-report-uia/0.1.0/media/UIA_en.svg
  packages/preview/light-report-uia/0.1.0/media/UIA_no.svg
  packages/preview/light-report-uia/0.1.0/template/main.typ
  packages/preview/light-report-uia/0.1.0/template/references.yml
  packages/preview/light-report-uia/0.1.0/thumbnail.png
  packages/preview/light-report-uia/0.1.0/typst.toml
Labels: new

#971 pointless-size:0.1.0
  packages/preview/pointless-size/0.1.0/.gitignore
  packages/preview/pointless-size/0.1.0/LICENSE
  packages/preview/pointless-size/0.1.0/README.md
  packages/preview/pointless-size/0.1.0/lib.typ
  packages/preview/pointless-size/0.1.0/typst.toml
  packages/preview/pointless-size/0.1.0/zihao.typ
Labels: new

#954 meppp:0.2.0
  packages/preview/meppp/0.2.0/LICENSE
  packages/preview/meppp/0.2.0/README.md
  packages/preview/meppp/0.2.0/lib.typ
  packages/preview/meppp/0.2.0/pkulogo.png
  packages/preview/meppp/0.2.0/table.typ
  packages/preview/meppp/0.2.0/template.typ
  packages/preview/meppp/0.2.0/template/example_fig.png
  packages/preview/meppp/0.2.0/template/example_ref.bib
  packages/preview/meppp/0.2.0/template/main.typ
  packages/preview/meppp/0.2.0/thumbnail.png
  packages/preview/meppp/0.2.0/typst.toml
Labels: update

#977 tgm-hit-thesis:0.1.3
  packages/preview/tgm-hit-thesis/0.1.3/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.1.3/LICENSE
  packages/preview/tgm-hit-thesis/0.1.3/README.md
  packages/preview/tgm-hit-thesis/0.1.3/docs/manual.pdf
  packages/preview/tgm-hit-thesis/0.1.3/example.pdf
  packages/preview/tgm-hit-thesis/0.1.3/src/assets.typ
  packages/preview/tgm-hit-thesis/0.1.3/src/assets/logo-left.png
  packages/preview/tgm-hit-thesis/0.1.3/src/assets/logo-right.png
  packages/preview/tgm-hit-thesis/0.1.3/src/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.1.3/src/glossary.typ
  packages/preview/tgm-hit-thesis/0.1.3/src/l10n.toml
  packages/preview/tgm-hit-thesis/0.1.3/src/l10n.typ
  packages/preview/tgm-hit-thesis/0.1.3/src/lib.typ
  packages/preview/tgm-hit-thesis/0.1.3/src/utils.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/assets.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/assets/logo.png
  packages/preview/tgm-hit-thesis/0.1.3/template/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/bibliography.bib
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/conclusio.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/danksagung.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/einleitung.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/implementierung.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/konzept.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/kurzfassung.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/retrospektive.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/studie.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/chapters/vorwort.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/glossaries.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/lib.typ
  packages/preview/tgm-hit-thesis/0.1.3/template/main.typ
  packages/preview/tgm-hit-thesis/0.1.3/thumbnail.png
  packages/preview/tgm-hit-thesis/0.1.3/typst.toml
Labels: update

#963 echarm:0.1.0
  packages/preview/echarm/0.1.0/LICENSE
  packages/preview/echarm/0.1.0/README.md
  packages/preview/echarm/0.1.0/echarts.kbc1
  packages/preview/echarm/0.1.0/echarts_helper.js
  packages/preview/echarm/0.1.0/examples/candlestick.png
  packages/preview/echarm/0.1.0/examples/candlestick.typ
  packages/preview/echarm/0.1.0/examples/gauge.png
  packages/preview/echarm/0.1.0/examples/gauge.typ
  packages/preview/echarm/0.1.0/examples/mixed_charts.png
  packages/preview/echarm/0.1.0/examples/mixed_charts.typ
  packages/preview/echarm/0.1.0/examples/pie.png
  packages/preview/echarm/0.1.0/examples/pie.typ
  packages/preview/echarm/0.1.0/examples/radar.png
  packages/preview/echarm/0.1.0/examples/radar.typ
  packages/preview/echarm/0.1.0/examples/scatter.png
  packages/preview/echarm/0.1.0/examples/scatter.typ
  packages/preview/echarm/0.1.0/lib.typ
  packages/preview/echarm/0.1.0/typst.toml
Labels: new

#978 spreet:0.1.0
  packages/preview/spreet/0.1.0/LICENSE
  packages/preview/spreet/0.1.0/README.md
  packages/preview/spreet/0.1.0/lib.typ
  packages/preview/spreet/0.1.0/spreet.wasm
  packages/preview/spreet/0.1.0/typst.toml
Labels: new

#979 Fix for quill:0.4.0
  packages/preview/quill/0.4.0/README.md
  packages/preview/quill/0.4.0/docs/images/logo.svg
  packages/preview/quill/0.4.0/typst.toml
Labels: minor fix

#981 typographix-polytechnique-reports:0.1.4
  packages/preview/typographix-polytechnique-reports/0.1.4/.gitignore
  packages/preview/typographix-polytechnique-reports/0.1.4/CONTRIBUTING.md
  packages/preview/typographix-polytechnique-reports/0.1.4/LICENSE
  packages/preview/typographix-polytechnique-reports/0.1.4/README.md
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/README.md
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/armes.svg
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/example.bib
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/filet-court.svg
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/filet-long.svg
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/logo-x-ip-paris.svg
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/logo-x.svg
  packages/preview/typographix-polytechnique-reports/0.1.4/assets/typst.png
  packages/preview/typographix-polytechnique-reports/0.1.4/cover.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/guide.pdf
  packages/preview/typographix-polytechnique-reports/0.1.4/guide.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/heading.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/outline.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/page.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/polytechnique.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/report-thumbnail.png
  packages/preview/typographix-polytechnique-reports/0.1.4/template/report.typ
  packages/preview/typographix-polytechnique-reports/0.1.4/typst.toml
Labels: update

#982 supercharged-dhbw:3.2.0
  packages/preview/supercharged-dhbw/3.2.0/CHANGELOG.md
  packages/preview/supercharged-dhbw/3.2.0/LICENSE
  packages/preview/supercharged-dhbw/3.2.0/README.md
  packages/preview/supercharged-dhbw/3.2.0/acronym-lib.typ
  packages/preview/supercharged-dhbw/3.2.0/check-attributes.typ
  packages/preview/supercharged-dhbw/3.2.0/confidentiality-statement.typ
  packages/preview/supercharged-dhbw/3.2.0/declaration-of-authorship.typ
  packages/preview/supercharged-dhbw/3.2.0/dhbw.svg
  packages/preview/supercharged-dhbw/3.2.0/examples/example-acronyms.typ
  packages/preview/supercharged-dhbw/3.2.0/examples/example-glossary.typ
  packages/preview/supercharged-dhbw/3.2.0/examples/example-sources.bib
  packages/preview/supercharged-dhbw/3.2.0/examples/example-sources.yml
  packages/preview/supercharged-dhbw/3.2.0/examples/example.pdf
  packages/preview/supercharged-dhbw/3.2.0/examples/example.typ
  packages/preview/supercharged-dhbw/3.2.0/glossary-lib.typ
  packages/preview/supercharged-dhbw/3.2.0/lib.typ
  packages/preview/supercharged-dhbw/3.2.0/locale.typ
  packages/preview/supercharged-dhbw/3.2.0/shared-lib.typ
  packages/preview/supercharged-dhbw/3.2.0/template/acronyms.typ
  packages/preview/supercharged-dhbw/3.2.0/template/assets/ts.svg
  packages/preview/supercharged-dhbw/3.2.0/template/glossary.typ
  packages/preview/supercharged-dhbw/3.2.0/template/main.typ
  packages/preview/supercharged-dhbw/3.2.0/template/sources.bib
  packages/preview/supercharged-dhbw/3.2.0/thumbnail.png
  packages/preview/supercharged-dhbw/3.2.0/titlepage.typ
  packages/preview/supercharged-dhbw/3.2.0/typst.toml
Labels: update

#985 scholarly-tauthesis:0.7.0
  packages/preview/scholarly-tauthesis/0.7.0/.gitattributes
  packages/preview/scholarly-tauthesis/0.7.0/.gitignore
  packages/preview/scholarly-tauthesis/0.7.0/LICENSE
  packages/preview/scholarly-tauthesis/0.7.0/README.md
  packages/preview/scholarly-tauthesis/0.7.0/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.7.0/template/code/README.md
  packages/preview/scholarly-tauthesis/0.7.0/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.7.0/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/README.md
  packages/preview/scholarly-tauthesis/0.7.0/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/images/README.md
  packages/preview/scholarly-tauthesis/0.7.0/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.7.0/template/main.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/meta.typ
  packages/preview/scholarly-tauthesis/0.7.0/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.7.0/thumbnail.png
  packages/preview/scholarly-tauthesis/0.7.0/typst.toml
Labels: update

#969 touying-brandred-uobristol:0.1.0
  packages/preview/touying-brandred-uobristol/0.1.0/LICENSE
  packages/preview/touying-brandred-uobristol/0.1.0/README.md
  packages/preview/touying-brandred-uobristol/0.1.0/examples/example.pdf
  packages/preview/touying-brandred-uobristol/0.1.0/examples/example.typ
  packages/preview/touying-brandred-uobristol/0.1.0/lib.typ
  packages/preview/touying-brandred-uobristol/0.1.0/template/main.typ
  packages/preview/touying-brandred-uobristol/0.1.0/thumbnail.png
  packages/preview/touying-brandred-uobristol/0.1.0/typst.toml
  packages/preview/touying-brandred-uobristol/0.1.0/uob-bullet.svg
  packages/preview/touying-brandred-uobristol/0.1.0/uob-logo.svg
Labels: new

#983 modern-uit-thesis:0.1.0
  packages/preview/modern-uit-thesis/0.1.0/LICENSE
  packages/preview/modern-uit-thesis/0.1.0/README.md
  packages/preview/modern-uit-thesis/0.1.0/assets/backpage.svg
  packages/preview/modern-uit-thesis/0.1.0/assets/frontpage_full.svg
  packages/preview/modern-uit-thesis/0.1.0/assets/logo.svg
  packages/preview/modern-uit-thesis/0.1.0/lib.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/abbreviations.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/abstract.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/acknowledgements.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/backpage.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/epigraph.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/frontpage.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/glossarium.typ
  packages/preview/modern-uit-thesis/0.1.0/modules/supervisors.typ
  packages/preview/modern-uit-thesis/0.1.0/template/chapters/basic-usage.typ
  packages/preview/modern-uit-thesis/0.1.0/template/chapters/figures.typ
  packages/preview/modern-uit-thesis/0.1.0/template/chapters/global.typ
  packages/preview/modern-uit-thesis/0.1.0/template/chapters/introduction.typ
  packages/preview/modern-uit-thesis/0.1.0/template/chapters/typst-basics.typ
  packages/preview/modern-uit-thesis/0.1.0/template/chapters/utilities.typ
  packages/preview/modern-uit-thesis/0.1.0/template/figures/dining_philosophers.png
  packages/preview/modern-uit-thesis/0.1.0/template/figures/philosophers.png
  packages/preview/modern-uit-thesis/0.1.0/template/figures/plot_serial.svg
  packages/preview/modern-uit-thesis/0.1.0/template/figures/uit_aurora.jpg
  packages/preview/modern-uit-thesis/0.1.0/template/refs.bib
  packages/preview/modern-uit-thesis/0.1.0/template/thesis.typ
  packages/preview/modern-uit-thesis/0.1.0/template/utils/caption.typ
  packages/preview/modern-uit-thesis/0.1.0/template/utils/feedback.typ
  packages/preview/modern-uit-thesis/0.1.0/template/utils/form.typ
  packages/preview/modern-uit-thesis/0.1.0/template/utils/subfigure.typ
  packages/preview/modern-uit-thesis/0.1.0/template/utils/symbols.typ
  packages/preview/modern-uit-thesis/0.1.0/template/utils/todo.typ
  packages/preview/modern-uit-thesis/0.1.0/thumbnail.png
  packages/preview/modern-uit-thesis/0.1.0/typst.toml
Labels: new

#986 classy-german-invoice:0.3.0
  packages/preview/classy-german-invoice/0.3.0/LICENSE
  packages/preview/classy-german-invoice/0.3.0/README.md
  packages/preview/classy-german-invoice/0.3.0/lib.typ
  packages/preview/classy-german-invoice/0.3.0/template/example_signature.png
  packages/preview/classy-german-invoice/0.3.0/template/main.typ
  packages/preview/classy-german-invoice/0.3.0/thumbnail.png
  packages/preview/classy-german-invoice/0.3.0/typst.toml
Labels: update

#989 fh-joanneum-iit-thesis:1.2.3
  packages/preview/fh-joanneum-iit-thesis/1.2.3/LICENSE
  packages/preview/fh-joanneum-iit-thesis/1.2.3/README.md
  packages/preview/fh-joanneum-iit-thesis/1.2.3/lib.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/biblio.bib
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/biblio.csl
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/1-intro.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/2-related.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/3-background.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/4-concept.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/5-implementation.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/6-evaluation.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/7-conclusion.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/acknowledgements.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/global.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/chapters/glossary.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/code-snippets/msg.py
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/data/recordings.csv
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/figures/chart-1.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/figures/chart-2.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/figures/logo.svg
  packages/preview/fh-joanneum-iit-thesis/1.2.3/template/thesis.typ
  packages/preview/fh-joanneum-iit-thesis/1.2.3/thumbnail.png
  packages/preview/fh-joanneum-iit-thesis/1.2.3/typst.toml
Labels: update

#991 bloated-neurips:0.5.0
  packages/preview/bloated-neurips/0.5.0/LICENSE
  packages/preview/bloated-neurips/0.5.0/README.md
  packages/preview/bloated-neurips/0.5.0/neurips.typ
  packages/preview/bloated-neurips/0.5.0/neurips2023.typ
  packages/preview/bloated-neurips/0.5.0/neurips2024.typ
  packages/preview/bloated-neurips/0.5.0/template/appendix.typ
  packages/preview/bloated-neurips/0.5.0/template/checklist.typ
  packages/preview/bloated-neurips/0.5.0/template/logo.typ
  packages/preview/bloated-neurips/0.5.0/template/main.bib
  packages/preview/bloated-neurips/0.5.0/template/main.typ
  packages/preview/bloated-neurips/0.5.0/thumbnail.png
  packages/preview/bloated-neurips/0.5.0/typst.toml
Labels: update

#993 supercharged-dhbw:3.3.0
  packages/preview/supercharged-dhbw/3.3.0/CHANGELOG.md
  packages/preview/supercharged-dhbw/3.3.0/LICENSE
  packages/preview/supercharged-dhbw/3.3.0/README.md
  packages/preview/supercharged-dhbw/3.3.0/acronym-lib.typ
  packages/preview/supercharged-dhbw/3.3.0/check-attributes.typ
  packages/preview/supercharged-dhbw/3.3.0/confidentiality-statement.typ
  packages/preview/supercharged-dhbw/3.3.0/declaration-of-authorship.typ
  packages/preview/supercharged-dhbw/3.3.0/dhbw.svg
  packages/preview/supercharged-dhbw/3.3.0/examples/example-acronyms.typ
  packages/preview/supercharged-dhbw/3.3.0/examples/example-glossary.typ
  packages/preview/supercharged-dhbw/3.3.0/examples/example-sources.bib
  packages/preview/supercharged-dhbw/3.3.0/examples/example-sources.yml
  packages/preview/supercharged-dhbw/3.3.0/examples/example.pdf
  packages/preview/supercharged-dhbw/3.3.0/examples/example.typ
  packages/preview/supercharged-dhbw/3.3.0/glossary-lib.typ
  packages/preview/supercharged-dhbw/3.3.0/lib.typ
  packages/preview/supercharged-dhbw/3.3.0/locale.typ
  packages/preview/supercharged-dhbw/3.3.0/shared-lib.typ
  packages/preview/supercharged-dhbw/3.3.0/template/acronyms.typ
  packages/preview/supercharged-dhbw/3.3.0/template/assets/ts.svg
  packages/preview/supercharged-dhbw/3.3.0/template/glossary.typ
  packages/preview/supercharged-dhbw/3.3.0/template/main.typ
  packages/preview/supercharged-dhbw/3.3.0/template/sources.bib
  packages/preview/supercharged-dhbw/3.3.0/thumbnail.png
  packages/preview/supercharged-dhbw/3.3.0/titlepage.typ
  packages/preview/supercharged-dhbw/3.3.0/typst.toml
Labels: update

#995 crossregex:0.2.0
  packages/preview/crossregex/0.2.0/LICENSE
  packages/preview/crossregex/0.2.0/README.md
  packages/preview/crossregex/0.2.0/examples/standard.svg
  packages/preview/crossregex/0.2.0/examples/sudoku-main.svg
  packages/preview/crossregex/0.2.0/src/crossregex.wasm
  packages/preview/crossregex/0.2.0/src/hex.typ
  packages/preview/crossregex/0.2.0/src/layout.typ
  packages/preview/crossregex/0.2.0/src/lib.typ
  packages/preview/crossregex/0.2.0/src/process.typ
  packages/preview/crossregex/0.2.0/src/regex.typ
  packages/preview/crossregex/0.2.0/src/square.typ
  packages/preview/crossregex/0.2.0/typst.toml
Labels: update

#990 shadowed:0.1.0
  packages/preview/shadowed/0.1.0/.gitignore
  packages/preview/shadowed/0.1.0/LICENSE
  packages/preview/shadowed/0.1.0/README.md
  packages/preview/shadowed/0.1.0/benchmarks/justfile
  packages/preview/shadowed/0.1.0/benchmarks/main.typ
  packages/preview/shadowed/0.1.0/benchmarks/results.md
  packages/preview/shadowed/0.1.0/examples/lorem.png
  packages/preview/shadowed/0.1.0/examples/lorem.typ
  packages/preview/shadowed/0.1.0/lib.typ
  packages/preview/shadowed/0.1.0/renderer.wasm
  packages/preview/shadowed/0.1.0/renderer/Cargo.lock
  packages/preview/shadowed/0.1.0/renderer/Cargo.toml
  packages/preview/shadowed/0.1.0/renderer/justfile
  packages/preview/shadowed/0.1.0/renderer/src/lib.rs
  packages/preview/shadowed/0.1.0/renderer/templates/shadow.svg.jinja
  packages/preview/shadowed/0.1.0/typst.toml
Labels: new

#992 blind-cvpr:0.5.0
  packages/preview/blind-cvpr/0.5.0/LICENSE
  packages/preview/blind-cvpr/0.5.0/README.md
  packages/preview/blind-cvpr/0.5.0/cvpr.typ
  packages/preview/blind-cvpr/0.5.0/cvpr2022.typ
  packages/preview/blind-cvpr/0.5.0/cvpr2025.typ
  packages/preview/blind-cvpr/0.5.0/ieee.csl
  packages/preview/blind-cvpr/0.5.0/template/logo.typ
  packages/preview/blind-cvpr/0.5.0/template/main.bib
  packages/preview/blind-cvpr/0.5.0/template/main.typ
  packages/preview/blind-cvpr/0.5.0/thumbnail.png
  packages/preview/blind-cvpr/0.5.0/typst.toml
Labels: new

#998 frackable:0.1.0
  packages/preview/frackable/0.1.0/CHANGELOG.md
  packages/preview/frackable/0.1.0/LICENSE
  packages/preview/frackable/0.1.0/README.md
  packages/preview/frackable/0.1.0/example.png
  packages/preview/frackable/0.1.0/src/impl.typ
  packages/preview/frackable/0.1.0/src/lib.typ
  packages/preview/frackable/0.1.0/typst.toml
Labels: new

#1000 silky-report-insa:0.3.1 and silky-letter-insa:0.2.1
  packages/preview/silky-letter-insa/0.2.1/README.md
  packages/preview/silky-letter-insa/0.2.1/assets/footer.png
  packages/preview/silky-letter-insa/0.2.1/assets/hdf/logo.png
  packages/preview/silky-letter-insa/0.2.1/assets/rennes/logo.png
  packages/preview/silky-letter-insa/0.2.1/letter-template.typ
  packages/preview/silky-letter-insa/0.2.1/template/main.typ
  packages/preview/silky-letter-insa/0.2.1/thumbnail.png
  packages/preview/silky-letter-insa/0.2.1/typst.toml
  packages/preview/silky-report-insa/0.3.1/README.md
  packages/preview/silky-report-insa/0.3.1/assets/footer.png
  packages/preview/silky-report-insa/0.3.1/assets/hdf/back-cover1.png
  packages/preview/silky-report-insa/0.3.1/assets/hdf/back-cover2.jpeg
  packages/preview/silky-report-insa/0.3.1/assets/hdf/front-cover1.jpeg
  packages/preview/silky-report-insa/0.3.1/assets/hdf/front-cover2.png
  packages/preview/silky-report-insa/0.3.1/assets/hdf/front-cover3.jpeg
  packages/preview/silky-report-insa/0.3.1/assets/hdf/logo.png
  packages/preview/silky-report-insa/0.3.1/assets/rennes/back-cover1.png
  packages/preview/silky-report-insa/0.3.1/assets/rennes/back-cover2.jpeg
  packages/preview/silky-report-insa/0.3.1/assets/rennes/front-cover1.jpeg
  packages/preview/silky-report-insa/0.3.1/assets/rennes/front-cover2.png
  packages/preview/silky-report-insa/0.3.1/assets/rennes/front-cover3.jpeg
  packages/preview/silky-report-insa/0.3.1/assets/rennes/logo.png
  packages/preview/silky-report-insa/0.3.1/document-template.typ
  packages/preview/silky-report-insa/0.3.1/template/main.typ
  packages/preview/silky-report-insa/0.3.1/thumbnail-insa-document.png
  packages/preview/silky-report-insa/0.3.1/thumbnail-insa-report.png
  packages/preview/silky-report-insa/0.3.1/thumbnail-insa-stage.png
  packages/preview/silky-report-insa/0.3.1/thumbnail.png
  packages/preview/silky-report-insa/0.3.1/typst.toml
Labels: update

#1001 acrostiche:0.3.3
  packages/preview/acrostiche/0.3.3/LICENSE
  packages/preview/acrostiche/0.3.3/README.md
  packages/preview/acrostiche/0.3.3/acrostiche.typ
  packages/preview/acrostiche/0.3.3/typst.toml
Labels: update

#999 quetta:0.2.0
  packages/preview/quetta/0.2.0/LICENSE
  packages/preview/quetta/0.2.0/README.md
  packages/preview/quetta/0.2.0/logo.typ
  packages/preview/quetta/0.2.0/src/gondor.typ
  packages/preview/quetta/0.2.0/src/quenya.typ
  packages/preview/quetta/0.2.0/src/quetta.typ
  packages/preview/quetta/0.2.0/src/tengwar_proto.typ
  packages/preview/quetta/0.2.0/typst.toml
Labels: update

#939 fauve-cdb:0.1.0
  packages/preview/fauve-cdb/0.1.0/LICENSE
  packages/preview/fauve-cdb/0.1.0/README.md
  packages/preview/fauve-cdb/0.1.0/assets/UR.png
  packages/preview/fauve-cdb/0.1.0/assets/logo.png
  packages/preview/fauve-cdb/0.1.0/src/abstracts-bg.typ
  packages/preview/fauve-cdb/0.1.0/src/cover-bg.typ
  packages/preview/fauve-cdb/0.1.0/src/lib.typ
  packages/preview/fauve-cdb/0.1.0/src/utils.typ
  packages/preview/fauve-cdb/0.1.0/template/main.typ
  packages/preview/fauve-cdb/0.1.0/thumbnail.png
  packages/preview/fauve-cdb/0.1.0/typst.toml
Labels: new, waiting-on-author

#1006 georges-yetyp:0.2.0
  packages/preview/georges-yetyp/0.2.0/LICENSE
  packages/preview/georges-yetyp/0.2.0/README.fr.md
  packages/preview/georges-yetyp/0.2.0/README.md
  packages/preview/georges-yetyp/0.2.0/lib.typ
  packages/preview/georges-yetyp/0.2.0/logo-polytech.png
  packages/preview/georges-yetyp/0.2.0/template/logo.png
  packages/preview/georges-yetyp/0.2.0/template/main.typ
  packages/preview/georges-yetyp/0.2.0/thumbnail.png
  packages/preview/georges-yetyp/0.2.0/typst.toml
Labels: update

#1007 frackable:0.2.0
  packages/preview/frackable/0.2.0/CHANGELOG.md
  packages/preview/frackable/0.2.0/LICENSE
  packages/preview/frackable/0.2.0/README.md
  packages/preview/frackable/0.2.0/docs/manual.pdf
  packages/preview/frackable/0.2.0/example.png
  packages/preview/frackable/0.2.0/src/impl.typ
  packages/preview/frackable/0.2.0/src/lib.typ
  packages/preview/frackable/0.2.0/typst.toml
Labels: update

#1008 elsearticle:0.2.1
  packages/preview/elsearticle/0.2.1/CHANGELOG.md
  packages/preview/elsearticle/0.2.1/LICENSE
  packages/preview/elsearticle/0.2.1/README.md
  packages/preview/elsearticle/0.2.1/docs/manual.pdf
  packages/preview/elsearticle/0.2.1/docs/manual.typ
  packages/preview/elsearticle/0.2.1/src/elsearticle.typ
  packages/preview/elsearticle/0.2.1/template/images/typst-logo.svg
  packages/preview/elsearticle/0.2.1/template/main.typ
  packages/preview/elsearticle/0.2.1/template/refs.bib
  packages/preview/elsearticle/0.2.1/thumbnails/main.png
  packages/preview/elsearticle/0.2.1/typst.toml
Labels: update

#1009 kouhu:0.1.0
  packages/preview/kouhu/0.1.0/LICENSE
  packages/preview/kouhu/0.1.0/README.md
  packages/preview/kouhu/0.1.0/data/zhlipsum.json
  packages/preview/kouhu/0.1.0/doc/manual.pdf
  packages/preview/kouhu/0.1.0/doc/manual.typ
  packages/preview/kouhu/0.1.0/lib.typ
  packages/preview/kouhu/0.1.0/typst.toml
  packages/preview/kouhu/0.1.0/utils/convert_from_zhlipsum.py
Labels: new

#1013 crudo:0.1.1
  packages/preview/crudo/0.1.1/.gitignore
  packages/preview/crudo/0.1.1/CHANGELOG.md
  packages/preview/crudo/0.1.1/LICENSE
  packages/preview/crudo/0.1.1/README.md
  packages/preview/crudo/0.1.1/docs/manual.pdf
  packages/preview/crudo/0.1.1/gallery/thumbnail.pdf
  packages/preview/crudo/0.1.1/src/lib.typ
  packages/preview/crudo/0.1.1/thumbnail.png
  packages/preview/crudo/0.1.1/typst.toml
Labels: update

#1002 note-me:0.3.0
  packages/preview/note-me/0.3.0/.gitignore
  packages/preview/note-me/0.3.0/LICENSE
  packages/preview/note-me/0.3.0/README.md
  packages/preview/note-me/0.3.0/example.pdf
  packages/preview/note-me/0.3.0/example.svg
  packages/preview/note-me/0.3.0/example.typ
  packages/preview/note-me/0.3.0/icons/alert.svg
  packages/preview/note-me/0.3.0/icons/info.svg
  packages/preview/note-me/0.3.0/icons/light-bulb.svg
  packages/preview/note-me/0.3.0/icons/question.svg
  packages/preview/note-me/0.3.0/icons/report.svg
  packages/preview/note-me/0.3.0/icons/stop.svg
  packages/preview/note-me/0.3.0/lib.typ
  packages/preview/note-me/0.3.0/note-me-more.typ
  packages/preview/note-me/0.3.0/note-me.typ
  packages/preview/note-me/0.3.0/stick-together.typ
  packages/preview/note-me/0.3.0/typst.toml
Labels: update

#1011 kouhu:0.1.1
  packages/preview/kouhu/0.1.1/LICENSE
  packages/preview/kouhu/0.1.1/README.md
  packages/preview/kouhu/0.1.1/data/zhlipsum.json
  packages/preview/kouhu/0.1.1/doc/manual.pdf
  packages/preview/kouhu/0.1.1/doc/manual.typ
  packages/preview/kouhu/0.1.1/lib.typ
  packages/preview/kouhu/0.1.1/typst.toml
  packages/preview/kouhu/0.1.1/utils/convert_from_zhlipsum.py
Labels: update

#1016 ctxjs:0.1.1
  packages/preview/ctxjs/0.1.1/LICENSE
  packages/preview/ctxjs/0.1.1/README.md
  packages/preview/ctxjs/0.1.1/ctxjs.wasm
  packages/preview/ctxjs/0.1.1/lib.typ
  packages/preview/ctxjs/0.1.1/typst.toml
Labels: update

#1014 grotesk-cv:0.1.0
  packages/preview/grotesk-cv/0.1.0/LICENSE
  packages/preview/grotesk-cv/0.1.0/README.md
  packages/preview/grotesk-cv/0.1.0/content/education.typ
  packages/preview/grotesk-cv/0.1.0/content/experience.typ
  packages/preview/grotesk-cv/0.1.0/content/languages.typ
  packages/preview/grotesk-cv/0.1.0/content/other_experience.typ
  packages/preview/grotesk-cv/0.1.0/content/personal.typ
  packages/preview/grotesk-cv/0.1.0/content/profile.typ
  packages/preview/grotesk-cv/0.1.0/content/references.typ
  packages/preview/grotesk-cv/0.1.0/content/skills.typ
  packages/preview/grotesk-cv/0.1.0/lib.typ
  packages/preview/grotesk-cv/0.1.0/metadata.typ
  packages/preview/grotesk-cv/0.1.0/template/cover.typ
  packages/preview/grotesk-cv/0.1.0/template/cv.typ
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Black.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-BlackItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Bold.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-BoldItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-ExtraBold.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-ExtraBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-ExtraLight.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-ExtraLightItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Italic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Light.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-LightItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Medium.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-MediumItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Regular.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-SemiBold.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-SemiBoldItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-Thin.ttf
  packages/preview/grotesk-cv/0.1.0/template/font/HankenGrotesk-ThinItalic.ttf
  packages/preview/grotesk-cv/0.1.0/template/img/portrait.png
  packages/preview/grotesk-cv/0.1.0/thumbnail.png
  packages/preview/grotesk-cv/0.1.0/typst.toml
Labels: new

#1017 nulite:0.1.0
  packages/preview/nulite/0.1.0/LICENSE
  packages/preview/nulite/0.1.0/README.md
  packages/preview/nulite/0.1.0/examples/bar-chart.typ
  packages/preview/nulite/0.1.0/examples/image.png
  packages/preview/nulite/0.1.0/examples/spec.json
  packages/preview/nulite/0.1.0/lib.typ
  packages/preview/nulite/0.1.0/typst.toml
  packages/preview/nulite/0.1.0/vegalite.kbc1
Labels: new

#1019 finite:0.3.2
  packages/preview/finite/0.3.2/LICENSE
  packages/preview/finite/0.3.2/README.md
  packages/preview/finite/0.3.2/assets/example.png
  packages/preview/finite/0.3.2/cmd.typ
  packages/preview/finite/0.3.2/draw.typ
  packages/preview/finite/0.3.2/finite.typ
  packages/preview/finite/0.3.2/layout.typ
  packages/preview/finite/0.3.2/manual.pdf
  packages/preview/finite/0.3.2/manual.typ
  packages/preview/finite/0.3.2/typst.toml
  packages/preview/finite/0.3.2/util.typ
Labels: update
