Repository typst/packages, pull requests merged in 2024-02, with the labels that each got.

#366 jogs:v0.2.3
  packages/preview/jogs/0.2.3/LICENSE
  packages/preview/jogs/0.2.3/README.md
  packages/preview/jogs/0.2.3/examples/fib.svg
  packages/preview/jogs/0.2.3/examples/fib.typ
  packages/preview/jogs/0.2.3/jogs.wasm
  packages/preview/jogs/0.2.3/lib.typ
  packages/preview/jogs/0.2.3/license.html
  packages/preview/jogs/0.2.3/typst.toml
Labels: update

#367 truthfy:0.3.0
  packages/preview/truthfy/0.3.0/.gitignore
  packages/preview/truthfy/0.3.0/LICENSE
  packages/preview/truthfy/0.3.0/README.md
  packages/preview/truthfy/0.3.0/example.pdf
  packages/preview/truthfy/0.3.0/example.typ
  packages/preview/truthfy/0.3.0/main.typ
  packages/preview/truthfy/0.3.0/typst.toml
Labels: update

#368 tiaoma:v0.2.0
  packages/preview/tiaoma/0.2.0/LICENSE
  packages/preview/tiaoma/0.2.0/README.md
  packages/preview/tiaoma/0.2.0/example.svg
  packages/preview/tiaoma/0.2.0/example.typ
  packages/preview/tiaoma/0.2.0/lib.typ
  packages/preview/tiaoma/0.2.0/license.html
  packages/preview/tiaoma/0.2.0/manual.pdf
  packages/preview/tiaoma/0.2.0/manual.typ
  packages/preview/tiaoma/0.2.0/tidy_style.typ
  packages/preview/tiaoma/0.2.0/typst.toml
  packages/preview/tiaoma/0.2.0/zint_typst_plugin.wasm
Labels: update

#369 conchord:0.2.0
  packages/preview/conchord/0.2.0/LICENSE
  packages/preview/conchord/0.2.0/README.md
  packages/preview/conchord/0.2.0/examples/compare.png
  packages/preview/conchord/0.2.0/examples/compare.typ
  packages/preview/conchord/0.2.0/examples/crazy.png
  packages/preview/conchord/0.2.0/examples/crazy.typ
  packages/preview/conchord/0.2.0/examples/simple.png
  packages/preview/conchord/0.2.0/examples/simple.typ
  packages/preview/conchord/0.2.0/examples/tabs.png
  packages/preview/conchord/0.2.0/examples/tabs.typ
  packages/preview/conchord/0.2.0/examples/zombie.png
  packages/preview/conchord/0.2.0/examples/zombie.typ
  packages/preview/conchord/0.2.0/lib.typ
  packages/preview/conchord/0.2.0/tabs/drawing.typ
  packages/preview/conchord/0.2.0/tabs/gen.typ
  packages/preview/conchord/0.2.0/tabs/tabs.typ
  packages/preview/conchord/0.2.0/typst.toml
Labels: update

#373 pubmatter:0.1.0
  packages/preview/pubmatter/0.1.0/LICENSE
  packages/preview/pubmatter/0.1.0/README.md
  packages/preview/pubmatter/0.1.0/pubmatter.typ
  packages/preview/pubmatter/0.1.0/typst.toml
  packages/preview/pubmatter/0.1.0/validate-frontmatter.typ
Labels: new

#378 Add a second, extended index file
  bundler/Cargo.lock
  bundler/Cargo.toml
  bundler/src/main.rs
Labels: feature request

#381 touying:0.2.1
  packages/preview/touying/0.2.1/.gitignore
  packages/preview/touying/0.2.1/LICENSE
  packages/preview/touying/0.2.1/README.md
  packages/preview/touying/0.2.1/examples/dewdrop.typ
  packages/preview/touying/0.2.1/examples/example.typ
  packages/preview/touying/0.2.1/examples/metropolis.typ
  packages/preview/touying/0.2.1/examples/simple.typ
  packages/preview/touying/0.2.1/examples/slides.typ
  packages/preview/touying/0.2.1/examples/university.typ
  packages/preview/touying/0.2.1/lib.typ
  packages/preview/touying/0.2.1/slide.typ
  packages/preview/touying/0.2.1/themes/dewdrop.typ
  packages/preview/touying/0.2.1/themes/metropolis.typ
  packages/preview/touying/0.2.1/themes/simple.typ
  packages/preview/touying/0.2.1/themes/themes.typ
  packages/preview/touying/0.2.1/themes/university.typ
  packages/preview/touying/0.2.1/typst.toml
  packages/preview/touying/0.2.1/utils/pdfpc.typ
  packages/preview/touying/0.2.1/utils/states.typ
  packages/preview/touying/0.2.1/utils/utils.typ
Labels: update

#384 anatomy:0.1.1
  packages/preview/anatomy/0.1.1/.gitignore
  packages/preview/anatomy/0.1.1/LICENSE
  packages/preview/anatomy/0.1.1/README.md
  packages/preview/anatomy/0.1.1/README.pdf
  packages/preview/anatomy/0.1.1/README.typ
  packages/preview/anatomy/0.1.1/export.typ
  packages/preview/anatomy/0.1.1/img/export-1.svg
  packages/preview/anatomy/0.1.1/img/export-2.svg
  packages/preview/anatomy/0.1.1/img/export-3.svg
  packages/preview/anatomy/0.1.1/lib.typ
  packages/preview/anatomy/0.1.1/typst.toml
Labels: update

#390 g-exam:0.1.1
  packages/preview/g-exam/0.1.1/LICENSE
  packages/preview/g-exam/0.1.1/README.md
  packages/preview/g-exam/0.1.1/examples/exam-001.pdf
  packages/preview/g-exam/0.1.1/examples/exam-001.typ
  packages/preview/g-exam/0.1.1/examples/exam-002.pdf
  packages/preview/g-exam/0.1.1/examples/exam-002.typ
  packages/preview/g-exam/0.1.1/examples/exam-003.pdf
  packages/preview/g-exam/0.1.1/examples/exam-003.typ
  packages/preview/g-exam/0.1.1/examples/exam-005.pdf
  packages/preview/g-exam/0.1.1/examples/exam-005.typ
  packages/preview/g-exam/0.1.1/examples/exam-minimal.pdf
  packages/preview/g-exam/0.1.1/examples/exam-minimal.typ
  packages/preview/g-exam/0.1.1/examples/logo.png
  packages/preview/g-exam/0.1.1/g-exam.typ
  packages/preview/g-exam/0.1.1/lang.toml
  packages/preview/g-exam/0.1.1/typst.toml
Labels: update

#391 fletcher:0.4.2
  packages/preview/fletcher/0.4.2/LICENSE
  packages/preview/fletcher/0.4.2/README.md
  packages/preview/fletcher/0.4.2/docs/example-gallery/feynman-diagram-dark.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/feynman-diagram-light.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/feynman-diagram.typ
  packages/preview/fletcher/0.4.2/docs/example-gallery/first-isomorphism-theorem-dark.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/first-isomorphism-theorem-light.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/first-isomorphism-theorem.typ
  packages/preview/fletcher/0.4.2/docs/example-gallery/flowchart-trap-dark.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/flowchart-trap-light.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/flowchart-trap.typ
  packages/preview/fletcher/0.4.2/docs/example-gallery/ml-architecture-dark.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/ml-architecture-light.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/ml-architecture.typ
  packages/preview/fletcher/0.4.2/docs/example-gallery/state-machine-dark.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/state-machine-light.svg
  packages/preview/fletcher/0.4.2/docs/example-gallery/state-machine.typ
  packages/preview/fletcher/0.4.2/docs/manual.pdf
  packages/preview/fletcher/0.4.2/docs/manual.typ
  packages/preview/fletcher/0.4.2/docs/style.typ
  packages/preview/fletcher/0.4.2/src/draw.typ
  packages/preview/fletcher/0.4.2/src/exports.typ
  packages/preview/fletcher/0.4.2/src/layout.typ
  packages/preview/fletcher/0.4.2/src/main.typ
  packages/preview/fletcher/0.4.2/src/marks.typ
  packages/preview/fletcher/0.4.2/src/shapes.typ
  packages/preview/fletcher/0.4.2/src/utils.typ
  packages/preview/fletcher/0.4.2/test/test.pdf
  packages/preview/fletcher/0.4.2/test/test.typ
  packages/preview/fletcher/0.4.2/typst.toml
Labels: update

#396 ctheorems:1.1.2
  packages/preview/ctheorems/1.1.2/LICENSE
  packages/preview/ctheorems/1.1.2/README.md
  packages/preview/ctheorems/1.1.2/assets/basic.png
  packages/preview/ctheorems/1.1.2/assets/manual.pdf
  packages/preview/ctheorems/1.1.2/assets/manual_examples.pdf
  packages/preview/ctheorems/1.1.2/lib.typ
  packages/preview/ctheorems/1.1.2/typst.toml
Labels: update
