Repository typst/packages, pull requests merged in 2024-03, with the labels that each got.

#401 chordx:0.3.0
  packages/preview/chordx/0.3.0/CHANGELOG.md
  packages/preview/chordx/0.3.0/LICENSE
  packages/preview/chordx/0.3.0/README.md
  packages/preview/chordx/0.3.0/lib.typ
  packages/preview/chordx/0.3.0/src/chart.typ
  packages/preview/chordx/0.3.0/src/piano.typ
  packages/preview/chordx/0.3.0/src/single.typ
  packages/preview/chordx/0.3.0/src/utils.typ
  packages/preview/chordx/0.3.0/typst.toml
Labels: update

#402 wordometer:0.1.1
  packages/preview/wordometer/0.1.1/LICENSE
  packages/preview/wordometer/0.1.1/README.md
  packages/preview/wordometer/0.1.1/docs/manual.pdf
  packages/preview/wordometer/0.1.1/docs/manual.typ
  packages/preview/wordometer/0.1.1/src/lib.typ
  packages/preview/wordometer/0.1.1/test/tests.pdf
  packages/preview/wordometer/0.1.1/test/tests.typ
  packages/preview/wordometer/0.1.1/typst.toml
Labels: update

#405 touying:0.3.0
  packages/preview/touying/0.3.0/.gitignore
  packages/preview/touying/0.3.0/LICENSE
  packages/preview/touying/0.3.0/README.md
  packages/preview/touying/0.3.0/examples/dewdrop.typ
  packages/preview/touying/0.3.0/examples/example.typ
  packages/preview/touying/0.3.0/examples/metropolis.typ
  packages/preview/touying/0.3.0/examples/simple.typ
  packages/preview/touying/0.3.0/examples/slides.typ
  packages/preview/touying/0.3.0/examples/university.typ
  packages/preview/touying/0.3.0/lib.typ
  packages/preview/touying/0.3.0/slide.typ
  packages/preview/touying/0.3.0/themes/dewdrop.typ
  packages/preview/touying/0.3.0/themes/metropolis.typ
  packages/preview/touying/0.3.0/themes/simple.typ
  packages/preview/touying/0.3.0/themes/themes.typ
  packages/preview/touying/0.3.0/themes/university.typ
  packages/preview/touying/0.3.0/typst.toml
  packages/preview/touying/0.3.0/utils/components.typ
  packages/preview/touying/0.3.0/utils/pdfpc.typ
  packages/preview/touying/0.3.0/utils/states.typ
  packages/preview/touying/0.3.0/utils/utils.typ
Labels: update

#406 touying:0.3.1
  packages/preview/touying/0.3.1/.gitignore
  packages/preview/touying/0.3.1/LICENSE
  packages/preview/touying/0.3.1/README.md
  packages/preview/touying/0.3.1/examples/dewdrop.typ
  packages/preview/touying/0.3.1/examples/example.typ
  packages/preview/touying/0.3.1/examples/metropolis.typ
  packages/preview/touying/0.3.1/examples/simple.typ
  packages/preview/touying/0.3.1/examples/slides.typ
  packages/preview/touying/0.3.1/examples/university.typ
  packages/preview/touying/0.3.1/lib.typ
  packages/preview/touying/0.3.1/slide.typ
  packages/preview/touying/0.3.1/themes/dewdrop.typ
  packages/preview/touying/0.3.1/themes/metropolis.typ
  packages/preview/touying/0.3.1/themes/simple.typ
  packages/preview/touying/0.3.1/themes/themes.typ
  packages/preview/touying/0.3.1/themes/university.typ
  packages/preview/touying/0.3.1/typst.toml
  packages/preview/touying/0.3.1/utils/components.typ
  packages/preview/touying/0.3.1/utils/pdfpc.typ
  packages/preview/touying/0.3.1/utils/states.typ
  packages/preview/touying/0.3.1/utils/utils.typ
Labels: update

#407 note-me:0.2.1
  packages/preview/note-me/0.2.1/.gitignore
  packages/preview/note-me/0.2.1/LICENSE
  packages/preview/note-me/0.2.1/README.md
  packages/preview/note-me/0.2.1/example.pdf
  packages/preview/note-me/0.2.1/example.svg
  packages/preview/note-me/0.2.1/example.typ
  packages/preview/note-me/0.2.1/icons/alert.svg
  packages/preview/note-me/0.2.1/icons/info.svg
  packages/preview/note-me/0.2.1/icons/light-bulb.svg
  packages/preview/note-me/0.2.1/icons/question.svg
  packages/preview/note-me/0.2.1/icons/report.svg
  packages/preview/note-me/0.2.1/icons/stop.svg
  packages/preview/note-me/0.2.1/lib.typ
  packages/preview/note-me/0.2.1/note-me-more.typ
  packages/preview/note-me/0.2.1/note-me.typ
  packages/preview/note-me/0.2.1/stick-together.typ
  packages/preview/note-me/0.2.1/typst.toml
Labels: update

#412 mitex:0.2.2
  packages/preview/mitex/0.2.2/LICENSE
  packages/preview/mitex/0.2.2/README.md
  packages/preview/mitex/0.2.2/examples/bench.typ
  packages/preview/mitex/0.2.2/examples/example.png
  packages/preview/mitex/0.2.2/examples/example.typ
  packages/preview/mitex/0.2.2/lib.typ
  packages/preview/mitex/0.2.2/mitex.typ
  packages/preview/mitex/0.2.2/mitex.wasm
  packages/preview/mitex/0.2.2/specs/README.md
  packages/preview/mitex/0.2.2/specs/latex/standard.typ
  packages/preview/mitex/0.2.2/specs/mod.typ
  packages/preview/mitex/0.2.2/specs/prelude.typ
  packages/preview/mitex/0.2.2/typst.toml
Labels: update

#413 bytefield:0.0.5
  packages/preview/bytefield/0.0.5/CHANGELOG.md
  packages/preview/bytefield/0.0.5/LICENSE
  packages/preview/bytefield/0.0.5/README.md
  packages/preview/bytefield/0.0.5/bytefield.typ
  packages/preview/bytefield/0.0.5/common.typ
  packages/preview/bytefield/0.0.5/lib/api.typ
  packages/preview/bytefield/0.0.5/lib/asserts.typ
  packages/preview/bytefield/0.0.5/lib/gen.typ
  packages/preview/bytefield/0.0.5/lib/states.typ
  packages/preview/bytefield/0.0.5/lib/types.typ
  packages/preview/bytefield/0.0.5/lib/utils.typ
  packages/preview/bytefield/0.0.5/typst.toml
Labels: update

#414 quill:0.2.1
  packages/preview/quill/0.2.1/LICENSE
  packages/preview/quill/0.2.1/README.md
  packages/preview/quill/0.2.1/docs/guide/quill-guide.pdf
  packages/preview/quill/0.2.1/docs/images/bell.svg
  packages/preview/quill/0.2.1/docs/images/gallery.svg
  packages/preview/quill/0.2.1/docs/images/logo.svg
  packages/preview/quill/0.2.1/docs/images/phase-estimation.svg
  packages/preview/quill/0.2.1/docs/images/qft.svg
  packages/preview/quill/0.2.1/docs/images/teleportation.svg
  packages/preview/quill/0.2.1/src/arrow.typ
  packages/preview/quill/0.2.1/src/decorations.typ
  packages/preview/quill/0.2.1/src/draw-functions.pdf
  packages/preview/quill/0.2.1/src/draw-functions.typ
  packages/preview/quill/0.2.1/src/gates.pdf
  packages/preview/quill/0.2.1/src/gates.typ
  packages/preview/quill/0.2.1/src/layout.typ
  packages/preview/quill/0.2.1/src/length-helpers.typ
  packages/preview/quill/0.2.1/src/process-args.typ
  packages/preview/quill/0.2.1/src/quill.pdf
  packages/preview/quill/0.2.1/src/quill.typ
  packages/preview/quill/0.2.1/src/utility.typ
  packages/preview/quill/0.2.1/typst.toml
Labels: update

#415 rose-pine:0.2.0
  packages/preview/rose-pine/0.2.0/.editorconfig
  packages/preview/rose-pine/0.2.0/LICENSE
  packages/preview/rose-pine/0.2.0/README.md
  packages/preview/rose-pine/0.2.0/example.pdf
  packages/preview/rose-pine/0.2.0/example.typ
  packages/preview/rose-pine/0.2.0/lib.typ
  packages/preview/rose-pine/0.2.0/src/apply.typ
  packages/preview/rose-pine/0.2.0/src/rose-pine-template.tmTheme
  packages/preview/rose-pine/0.2.0/src/template.typ
  packages/preview/rose-pine/0.2.0/src/themes/rose-pine-dawn.tmTheme
  packages/preview/rose-pine/0.2.0/src/themes/rose-pine-dawn.typ
  packages/preview/rose-pine/0.2.0/src/themes/rose-pine-moon.tmTheme
  packages/preview/rose-pine/0.2.0/src/themes/rose-pine-moon.typ
  packages/preview/rose-pine/0.2.0/src/themes/rose-pine.tmTheme
  packages/preview/rose-pine/0.2.0/src/themes/rose-pine.typ
  packages/preview/rose-pine/0.2.0/typst.toml
Labels: update

#399 yats:0.1.0
  packages/preview/yats/0.1.0/LICENSE
  packages/preview/yats/0.1.0/README.md
  packages/preview/yats/0.1.0/example.typ
  packages/preview/yats/0.1.0/typst.toml
  packages/preview/yats/0.1.0/yats.typ
Labels: new

#419 touying:0.3.2
  packages/preview/touying/0.3.2/.gitignore
  packages/preview/touying/0.3.2/LICENSE
  packages/preview/touying/0.3.2/README.md
  packages/preview/touying/0.3.2/examples/aqua-zh.typ
  packages/preview/touying/0.3.2/examples/aqua.typ
  packages/preview/touying/0.3.2/examples/dewdrop.typ
  packages/preview/touying/0.3.2/examples/example.typ
  packages/preview/touying/0.3.2/examples/metropolis.typ
  packages/preview/touying/0.3.2/examples/simple.typ
  packages/preview/touying/0.3.2/examples/slides.typ
  packages/preview/touying/0.3.2/examples/university.typ
  packages/preview/touying/0.3.2/lib.typ
  packages/preview/touying/0.3.2/slide.typ
  packages/preview/touying/0.3.2/template/main.typ
  packages/preview/touying/0.3.2/themes/aqua.typ
  packages/preview/touying/0.3.2/themes/default.typ
  packages/preview/touying/0.3.2/themes/dewdrop.typ
  packages/preview/touying/0.3.2/themes/metropolis.typ
  packages/preview/touying/0.3.2/themes/simple.typ
  packages/preview/touying/0.3.2/themes/themes.typ
  packages/preview/touying/0.3.2/themes/university.typ
  packages/preview/touying/0.3.2/thumbnail.png
  packages/preview/touying/0.3.2/typst.toml
  packages/preview/touying/0.3.2/utils/components.typ
  packages/preview/touying/0.3.2/utils/pdfpc.typ
  packages/preview/touying/0.3.2/utils/states.typ
  packages/preview/touying/0.3.2/utils/utils.typ
Labels: update

#410 linguify:0.2.0
  packages/preview/linguify/0.2.0/LICENSE
  packages/preview/linguify/0.2.0/README.md
  packages/preview/linguify/0.2.0/linguify.typ
  packages/preview/linguify/0.2.0/typst.toml
Labels: update

#420 delegis:0.1.0
  packages/preview/delegis/0.1.0/.gitignore
  packages/preview/delegis/0.1.0/LICENSE
  packages/preview/delegis/0.1.0/README.md
  packages/preview/delegis/0.1.0/delegis.typ
  packages/preview/delegis/0.1.0/template/main.typ
  packages/preview/delegis/0.1.0/template/wuespace.jpg
  packages/preview/delegis/0.1.0/thumbnail.png
  packages/preview/delegis/0.1.0/typst.toml
Labels: new

#423 showman:0.1.1
  packages/preview/showman/0.1.1/README.md
  packages/preview/showman/0.1.1/lib.typ
  packages/preview/showman/0.1.1/src/formatter.typ
  packages/preview/showman/0.1.1/src/runner.typ
  packages/preview/showman/0.1.1/typst.toml
Labels: update

#421 colorful-boxes:1.3.1
  packages/preview/colorful-boxes/1.3.1/LICENSE
  packages/preview/colorful-boxes/1.3.1/README.md
  packages/preview/colorful-boxes/1.3.1/background.svg
  packages/preview/colorful-boxes/1.3.1/examples/colorbox.png
  packages/preview/colorful-boxes/1.3.1/examples/colorbox.typ
  packages/preview/colorful-boxes/1.3.1/examples/outline-colorbox.png
  packages/preview/colorful-boxes/1.3.1/examples/outline-colorbox.typ
  packages/preview/colorful-boxes/1.3.1/examples/slanted-colorbox.png
  packages/preview/colorful-boxes/1.3.1/examples/slanted-colorbox.typ
  packages/preview/colorful-boxes/1.3.1/examples/stickybox.png
  packages/preview/colorful-boxes/1.3.1/examples/stickybox.typ
  packages/preview/colorful-boxes/1.3.1/lib.typ
  packages/preview/colorful-boxes/1.3.1/tape.svg
  packages/preview/colorful-boxes/1.3.1/typst.toml
Labels: update

#436 linguify:0.3.0
  packages/preview/linguify/0.3.0/LICENSE
  packages/preview/linguify/0.3.0/README.md
  packages/preview/linguify/0.3.0/linguify.typ
  packages/preview/linguify/0.3.0/typst.toml
Labels: update

#428 cuti:0.1.0
  packages/preview/cuti/0.1.0/.gitignore
  packages/preview/cuti/0.1.0/LICENSE
  packages/preview/cuti/0.1.0/README.md
  packages/preview/cuti/0.1.0/demo-and-doc/demo-and-doc-cn.pdf
  packages/preview/cuti/0.1.0/demo-and-doc/demo-and-doc-cn.typ
  packages/preview/cuti/0.1.0/demo-and-doc/demo-and-doc.pdf
  packages/preview/cuti/0.1.0/demo-and-doc/demo-and-doc.typ
  packages/preview/cuti/0.1.0/lib.typ
  packages/preview/cuti/0.1.0/typst.toml
Labels: new

#422 sunny-famnit:0.1.0
  packages/preview/sunny-famnit/0.1.0/LICENSE
  packages/preview/sunny-famnit/0.1.0/README.md
  packages/preview/sunny-famnit/0.1.0/examples/attachments.typ
  packages/preview/sunny-famnit/0.1.0/examples/example.pdf
  packages/preview/sunny-famnit/0.1.0/examples/example.typ
  packages/preview/sunny-famnit/0.1.0/examples/image.png
  packages/preview/sunny-famnit/0.1.0/examples/my_references.bib
  packages/preview/sunny-famnit/0.1.0/lib.typ
  packages/preview/sunny-famnit/0.1.0/template/main.typ
  packages/preview/sunny-famnit/0.1.0/thumbnail.png
  packages/preview/sunny-famnit/0.1.0/typst.toml
Labels: new

#430 slydst:0.1.1
  packages/preview/slydst/0.1.1/LICENSE
  packages/preview/slydst/0.1.1/README.md
  packages/preview/slydst/0.1.1/example.typ
  packages/preview/slydst/0.1.1/lib.typ
  packages/preview/slydst/0.1.1/slydst.typ
  packages/preview/slydst/0.1.1/svg/example-01.svg
  packages/preview/slydst/0.1.1/svg/example-02.svg
  packages/preview/slydst/0.1.1/svg/example-03.svg
  packages/preview/slydst/0.1.1/svg/example-04.svg
  packages/preview/slydst/0.1.1/svg/example-05.svg
  packages/preview/slydst/0.1.1/svg/example-06.svg
  packages/preview/slydst/0.1.1/svg/example-07.svg
  packages/preview/slydst/0.1.1/svg/example-08.svg
  packages/preview/slydst/0.1.1/svg/example-09.svg
  packages/preview/slydst/0.1.1/svg/example-10.svg
  packages/preview/slydst/0.1.1/typst.toml
Labels: update

#434 cumcm-muban:0.1.0
  packages/preview/cumcm-muban/0.1.0/LICENSE
  packages/preview/cumcm-muban/0.1.0/README.md
  packages/preview/cumcm-muban/0.1.0/lib.typ
  packages/preview/cumcm-muban/0.1.0/template/figures/f1.png
  packages/preview/cumcm-muban/0.1.0/template/figures/f2.svg
  packages/preview/cumcm-muban/0.1.0/template/main.typ
  packages/preview/cumcm-muban/0.1.0/template/refs.bib
  packages/preview/cumcm-muban/0.1.0/thumbnail.png
  packages/preview/cumcm-muban/0.1.0/typst.toml
Labels: new

#437 codelst:2.0.1
  packages/preview/codelst/2.0.1/LICENSE
  packages/preview/codelst/2.0.1/README.md
  packages/preview/codelst/2.0.1/codelst.typ
  packages/preview/codelst/2.0.1/example.pdf
  packages/preview/codelst/2.0.1/example.typ
  packages/preview/codelst/2.0.1/manual.pdf
  packages/preview/codelst/2.0.1/manual.typ
  packages/preview/codelst/2.0.1/tbump.toml
  packages/preview/codelst/2.0.1/typst.toml
Labels: update

#439 curryst:0.2.0
  packages/preview/curryst/0.2.0/LICENSE
  packages/preview/curryst/0.2.0/README.md
  packages/preview/curryst/0.2.0/curryst.typ
  packages/preview/curryst/0.2.0/examples/math-formula.png
  packages/preview/curryst/0.2.0/examples/math-formula.typ
  packages/preview/curryst/0.2.0/examples/natural-deduction.png
  packages/preview/curryst/0.2.0/examples/natural-deduction.typ
  packages/preview/curryst/0.2.0/examples/rule-as-premise.png
  packages/preview/curryst/0.2.0/examples/rule-as-premise.typ
  packages/preview/curryst/0.2.0/examples/usage.png
  packages/preview/curryst/0.2.0/examples/usage.typ
  packages/preview/curryst/0.2.0/tests/README.md
  packages/preview/curryst/0.2.0/tests/test-01.png
  packages/preview/curryst/0.2.0/tests/test-02.png
  packages/preview/curryst/0.2.0/tests/test-03.png
  packages/preview/curryst/0.2.0/tests/test-04.png
  packages/preview/curryst/0.2.0/tests/test-05.png
  packages/preview/curryst/0.2.0/tests/test-06.png
  packages/preview/curryst/0.2.0/tests/test-07.png
  packages/preview/curryst/0.2.0/tests/test-08.png
  packages/preview/curryst/0.2.0/tests/test-09.png
  packages/preview/curryst/0.2.0/tests/test-10.png
  packages/preview/curryst/0.2.0/tests/test-11.png
  packages/preview/curryst/0.2.0/tests/test-12.png
  packages/preview/curryst/0.2.0/tests/test-13.png
  packages/preview/curryst/0.2.0/tests/test-14.png
  packages/preview/curryst/0.2.0/tests/test-15.png
  packages/preview/curryst/0.2.0/tests/test-16.png
  packages/preview/curryst/0.2.0/tests/test-17.png
  packages/preview/curryst/0.2.0/tests/test-18.png
  packages/preview/curryst/0.2.0/tests/tests.typ
  packages/preview/curryst/0.2.0/typst.toml
Labels: update

#440 tutor:0.4.0
  packages/preview/tutor/0.4.0/LICENSE
  packages/preview/tutor/0.4.0/README.md
  packages/preview/tutor/0.4.0/lib.typ
  packages/preview/tutor/0.4.0/typst.toml
Labels: update

#427 silky-report-insa:0.1.0
  packages/preview/silky-report-insa/0.1.0/README.md
  packages/preview/silky-report-insa/0.1.0/cover.jpeg
  packages/preview/silky-report-insa/0.1.0/footer.png
  packages/preview/silky-report-insa/0.1.0/lib.typ
  packages/preview/silky-report-insa/0.1.0/template/main.typ
  packages/preview/silky-report-insa/0.1.0/thumbnail.png
  packages/preview/silky-report-insa/0.1.0/typst.toml
Labels: new

#441 minimalistic-latex-cv:0.1.0
  packages/preview/minimalistic-latex-cv/0.1.0/LICENSE
  packages/preview/minimalistic-latex-cv/0.1.0/README.md
  packages/preview/minimalistic-latex-cv/0.1.0/lib.typ
  packages/preview/minimalistic-latex-cv/0.1.0/template/main.typ
  packages/preview/minimalistic-latex-cv/0.1.0/template/photo.jpeg
  packages/preview/minimalistic-latex-cv/0.1.0/thumbnail.png
  packages/preview/minimalistic-latex-cv/0.1.0/typst.toml
Labels: new

#443 suiji:0.1.0
  packages/preview/suiji/0.1.0/LICENSE
  packages/preview/suiji/0.1.0/README.md
  packages/preview/suiji/0.1.0/examples/rand-perm.pdf
  packages/preview/suiji/0.1.0/examples/rand-perm.png
  packages/preview/suiji/0.1.0/examples/rand-perm.typ
  packages/preview/suiji/0.1.0/examples/rand-walk.pdf
  packages/preview/suiji/0.1.0/examples/rand-walk.png
  packages/preview/suiji/0.1.0/examples/rand-walk.typ
  packages/preview/suiji/0.1.0/lib.typ
  packages/preview/suiji/0.1.0/typst.toml
Labels: new

#444 fuzzy-cnoi-statement:0.1.0
  packages/preview/fuzzy-cnoi-statement/0.1.0/LICENSE
  packages/preview/fuzzy-cnoi-statement/0.1.0/README.md
  packages/preview/fuzzy-cnoi-statement/0.1.0/fuzzy-cnoi-statement.typ
  packages/preview/fuzzy-cnoi-statement/0.1.0/template/color1.in
  packages/preview/fuzzy-cnoi-statement/0.1.0/template/fig.png
  packages/preview/fuzzy-cnoi-statement/0.1.0/template/main.typ
  packages/preview/fuzzy-cnoi-statement/0.1.0/thumbnail.png
  packages/preview/fuzzy-cnoi-statement/0.1.0/typst.toml
Labels: new

#429 scrutinize:0.2.0
  packages/preview/scrutinize/0.2.0/LICENSE
  packages/preview/scrutinize/0.2.0/README.md
  packages/preview/scrutinize/0.2.0/docs/manual.pdf
  packages/preview/scrutinize/0.2.0/docs/manual.typ
  packages/preview/scrutinize/0.2.0/docs/template.typ
  packages/preview/scrutinize/0.2.0/gallery/gk-ek-austria.pdf
  packages/preview/scrutinize/0.2.0/gallery/gk-ek-austria.typ
  packages/preview/scrutinize/0.2.0/gallery/question-types-solved.pdf
  packages/preview/scrutinize/0.2.0/gallery/question-types.pdf
  packages/preview/scrutinize/0.2.0/gallery/question-types.typ
  packages/preview/scrutinize/0.2.0/gallery/small-example-solved.pdf
  packages/preview/scrutinize/0.2.0/gallery/small-example.pdf
  packages/preview/scrutinize/0.2.0/gallery/small-example.typ
  packages/preview/scrutinize/0.2.0/gallery/test.pdf
  packages/preview/scrutinize/0.2.0/gallery/test.typ
  packages/preview/scrutinize/0.2.0/src/grading.typ
  packages/preview/scrutinize/0.2.0/src/lib.typ
  packages/preview/scrutinize/0.2.0/src/question.typ
  packages/preview/scrutinize/0.2.0/src/questions.typ
  packages/preview/scrutinize/0.2.0/src/utils.typ
  packages/preview/scrutinize/0.2.0/typst.toml
Labels: update

#442 lucky-icml:0.2.1 and bloated-neurips:0.2.1
  packages/preview/bloated-neurips/0.2.1/LICENSE
  packages/preview/bloated-neurips/0.2.1/README.md
  packages/preview/bloated-neurips/0.2.1/neurips2023.typ
  packages/preview/bloated-neurips/0.2.1/template/logo.typ
  packages/preview/bloated-neurips/0.2.1/template/main.bib
  packages/preview/bloated-neurips/0.2.1/template/main.typ
  packages/preview/bloated-neurips/0.2.1/thumbnail.png
  packages/preview/bloated-neurips/0.2.1/typst.toml
  packages/preview/lucky-icml/0.2.1/LICENSE
  packages/preview/lucky-icml/0.2.1/README.md
  packages/preview/lucky-icml/0.2.1/icml2024.csl
  packages/preview/lucky-icml/0.2.1/icml2024.typ
  packages/preview/lucky-icml/0.2.1/template/appendix.typ
  packages/preview/lucky-icml/0.2.1/template/icml-numpapers.svg
  packages/preview/lucky-icml/0.2.1/template/logo.typ
  packages/preview/lucky-icml/0.2.1/template/main.bib
  packages/preview/lucky-icml/0.2.1/template/main.typ
  packages/preview/lucky-icml/0.2.1/thumbnail.png
  packages/preview/lucky-icml/0.2.1/typst.toml
Labels: new

#447 badgery:0.1.0
  packages/preview/badgery/0.1.0/.gitignore
  packages/preview/badgery/0.1.0/LICENSE
  packages/preview/badgery/0.1.0/README.md
  packages/preview/badgery/0.1.0/badgery.typ
  packages/preview/badgery/0.1.0/demo.png
  packages/preview/badgery/0.1.0/example/main.pdf
  packages/preview/badgery/0.1.0/example/main.typ
  packages/preview/badgery/0.1.0/typst.toml
Labels: new

#449 fuzzy-cnoi-statement:0.1.1
  packages/preview/fuzzy-cnoi-statement/0.1.1/LICENSE
  packages/preview/fuzzy-cnoi-statement/0.1.1/README.md
  packages/preview/fuzzy-cnoi-statement/0.1.1/fuzzy-cnoi-statement.typ
  packages/preview/fuzzy-cnoi-statement/0.1.1/template/color1.in
  packages/preview/fuzzy-cnoi-statement/0.1.1/template/fig.png
  packages/preview/fuzzy-cnoi-statement/0.1.1/template/main.typ
  packages/preview/fuzzy-cnoi-statement/0.1.1/thumbnail.png
  packages/preview/fuzzy-cnoi-statement/0.1.1/typst.toml
Labels: update

#454 xarrow:0.3.1
  packages/preview/xarrow/0.3.1/LICENSE
  packages/preview/xarrow/0.3.1/README.md
  packages/preview/xarrow/0.3.1/lib.typ
  packages/preview/xarrow/0.3.1/typst.toml
Labels: update

#455 badgery:0.1.1
  packages/preview/badgery/0.1.1/.gitignore
  packages/preview/badgery/0.1.1/LICENSE
  packages/preview/badgery/0.1.1/README.md
  packages/preview/badgery/0.1.1/badgery.typ
  packages/preview/badgery/0.1.1/demo.png
  packages/preview/badgery/0.1.1/example/main.pdf
  packages/preview/badgery/0.1.1/example/main.typ
  packages/preview/badgery/0.1.1/typst.toml
Labels: update

#418 ssrn-scribe:0.4.9
  packages/preview/ssrn-scribe/0.4.9/README.md
  packages/preview/ssrn-scribe/0.4.9/paper_template.typ
  packages/preview/ssrn-scribe/0.4.9/template/main.typ
  packages/preview/ssrn-scribe/0.4.9/thumbnail.png
  packages/preview/ssrn-scribe/0.4.9/typst.toml
Labels: new

#448 board-n-pieces:0.1.0
  packages/preview/board-n-pieces/0.1.0/LICENSE
  packages/preview/board-n-pieces/0.1.0/README.md
  packages/preview/board-n-pieces/0.1.0/abi.typ
  packages/preview/board-n-pieces/0.1.0/assets/LICENSE
  packages/preview/board-n-pieces/0.1.0/assets/bb.svg
  packages/preview/board-n-pieces/0.1.0/assets/bw.svg
  packages/preview/board-n-pieces/0.1.0/assets/kb.svg
  packages/preview/board-n-pieces/0.1.0/assets/kw.svg
  packages/preview/board-n-pieces/0.1.0/assets/nb.svg
  packages/preview/board-n-pieces/0.1.0/assets/nw.svg
  packages/preview/board-n-pieces/0.1.0/assets/pb.svg
  packages/preview/board-n-pieces/0.1.0/assets/pw.svg
  packages/preview/board-n-pieces/0.1.0/assets/qb.svg
  packages/preview/board-n-pieces/0.1.0/assets/qw.svg
  packages/preview/board-n-pieces/0.1.0/assets/rb.svg
  packages/preview/board-n-pieces/0.1.0/assets/rw.svg
  packages/preview/board-n-pieces/0.1.0/chess-sym.typ
  packages/preview/board-n-pieces/0.1.0/examples/example-1.png
  packages/preview/board-n-pieces/0.1.0/examples/example-2.png
  packages/preview/board-n-pieces/0.1.0/examples/example-3.png
  packages/preview/board-n-pieces/0.1.0/examples/example-4.png
  packages/preview/board-n-pieces/0.1.0/internals.typ
  packages/preview/board-n-pieces/0.1.0/lib.typ
  packages/preview/board-n-pieces/0.1.0/plugin.wasm
  packages/preview/board-n-pieces/0.1.0/typst.toml
Labels: new

#456 cuti:0.2.0
  packages/preview/cuti/0.2.0/.gitignore
  packages/preview/cuti/0.2.0/LICENSE
  packages/preview/cuti/0.2.0/README.md
  packages/preview/cuti/0.2.0/demo-and-doc/demo-and-doc-cn.pdf
  packages/preview/cuti/0.2.0/demo-and-doc/demo-and-doc-cn.typ
  packages/preview/cuti/0.2.0/demo-and-doc/demo-and-doc.pdf
  packages/preview/cuti/0.2.0/demo-and-doc/demo-and-doc.typ
  packages/preview/cuti/0.2.0/demo-and-doc/otr/utils.typ
  packages/preview/cuti/0.2.0/lib.typ
  packages/preview/cuti/0.2.0/typst.toml
Labels: update

#452 modern-unito-thesis:0.1.0
  packages/preview/modern-unito-thesis/0.1.0/LICENSE
  packages/preview/modern-unito-thesis/0.1.0/README.md
  packages/preview/modern-unito-thesis/0.1.0/lib.typ
  packages/preview/modern-unito-thesis/0.1.0/template/chapters/conclusions.typ
  packages/preview/modern-unito-thesis/0.1.0/template/chapters/example.typ
  packages/preview/modern-unito-thesis/0.1.0/template/chapters/introduction.typ
  packages/preview/modern-unito-thesis/0.1.0/template/imgs/logo.svg
  packages/preview/modern-unito-thesis/0.1.0/template/main.typ
  packages/preview/modern-unito-thesis/0.1.0/template/works.yml
  packages/preview/modern-unito-thesis/0.1.0/thumbnail.png
  packages/preview/modern-unito-thesis/0.1.0/typst.toml
Labels: new

#458 board-n-pieces:0.1.0 (minor documentation fix)
  packages/preview/board-n-pieces/0.1.0/README.md
Labels: minor fix

#433 g-exam:0.2.0
  packages/preview/g-exam/0.2.0/LICENSE
  packages/preview/g-exam/0.2.0/README.md
  packages/preview/g-exam/0.2.0/examples/exam-001.pdf
  packages/preview/g-exam/0.2.0/examples/exam-001.typ
  packages/preview/g-exam/0.2.0/examples/exam-002.pdf
  packages/preview/g-exam/0.2.0/examples/exam-002.typ
  packages/preview/g-exam/0.2.0/examples/exam-003.pdf
  packages/preview/g-exam/0.2.0/examples/exam-003.typ
  packages/preview/g-exam/0.2.0/examples/exam-005.pdf
  packages/preview/g-exam/0.2.0/examples/exam-005.typ
  packages/preview/g-exam/0.2.0/examples/exam-006.pdf
  packages/preview/g-exam/0.2.0/examples/exam-006.typ
  packages/preview/g-exam/0.2.0/examples/exam-localization.pdf
  packages/preview/g-exam/0.2.0/examples/exam-localization.typ
  packages/preview/g-exam/0.2.0/examples/exam-minimal.pdf
  packages/preview/g-exam/0.2.0/examples/exam-minimal.typ
  packages/preview/g-exam/0.2.0/examples/exam-points-position.pdf
  packages/preview/g-exam/0.2.0/examples/exam-points-position.typ
  packages/preview/g-exam/0.2.0/examples/logo.png
  packages/preview/g-exam/0.2.0/g-exam.typ
  packages/preview/g-exam/0.2.0/lang.toml
  packages/preview/g-exam/0.2.0/template/1er exam.typ
  packages/preview/g-exam/0.2.0/template/logo.png
  packages/preview/g-exam/0.2.0/thumbnail.png
  packages/preview/g-exam/0.2.0/typst.toml
Labels: update

#462 suiji:0.2.0
  packages/preview/suiji/0.2.0/LICENSE
  packages/preview/suiji/0.2.0/README.md
  packages/preview/suiji/0.2.0/examples/matrix-rain.pdf
  packages/preview/suiji/0.2.0/examples/matrix-rain.png
  packages/preview/suiji/0.2.0/examples/matrix-rain.typ
  packages/preview/suiji/0.2.0/examples/random-permutation.pdf
  packages/preview/suiji/0.2.0/examples/random-permutation.png
  packages/preview/suiji/0.2.0/examples/random-permutation.typ
  packages/preview/suiji/0.2.0/examples/random-walk.pdf
  packages/preview/suiji/0.2.0/examples/random-walk.png
  packages/preview/suiji/0.2.0/examples/random-walk.typ
  packages/preview/suiji/0.2.0/src/lib.typ
  packages/preview/suiji/0.2.0/src/random.typ
  packages/preview/suiji/0.2.0/src/taus.typ
  packages/preview/suiji/0.2.0/tests/test-choice.pdf
  packages/preview/suiji/0.2.0/tests/test-choice.typ
  packages/preview/suiji/0.2.0/tests/test-integers.pdf
  packages/preview/suiji/0.2.0/tests/test-integers.typ
  packages/preview/suiji/0.2.0/tests/test-normal.pdf
  packages/preview/suiji/0.2.0/tests/test-normal.typ
  packages/preview/suiji/0.2.0/tests/test-random.pdf
  packages/preview/suiji/0.2.0/tests/test-random.typ
  packages/preview/suiji/0.2.0/tests/test-shuffle.pdf
  packages/preview/suiji/0.2.0/tests/test-shuffle.typ
  packages/preview/suiji/0.2.0/tests/test-uniform.pdf
  packages/preview/suiji/0.2.0/tests/test-uniform.typ
  packages/preview/suiji/0.2.0/typst.toml
Labels: update

#463 ilm:0.1.1
  packages/preview/ilm/0.1.1/LICENSE
  packages/preview/ilm/0.1.1/README.md
  packages/preview/ilm/0.1.1/lib.typ
  packages/preview/ilm/0.1.1/template/main.typ
  packages/preview/ilm/0.1.1/template/refs.bib
  packages/preview/ilm/0.1.1/thumbnail.png
  packages/preview/ilm/0.1.1/typst.toml
Labels: update

#464 pesha:0.1.0
  packages/preview/pesha/0.1.0/LICENSE
  packages/preview/pesha/0.1.0/README.md
  packages/preview/pesha/0.1.0/lib.typ
  packages/preview/pesha/0.1.0/template/main.typ
  packages/preview/pesha/0.1.0/thumbnail.png
  packages/preview/pesha/0.1.0/typst.toml
Labels: new

#460 bamdone-aiaa:0.1.0
  packages/preview/bamdone-aiaa/0.1.0/LICENSE.md
  packages/preview/bamdone-aiaa/0.1.0/README.md
  packages/preview/bamdone-aiaa/0.1.0/lib.typ
  packages/preview/bamdone-aiaa/0.1.0/template/main.typ
  packages/preview/bamdone-aiaa/0.1.0/template/refs.bib
  packages/preview/bamdone-aiaa/0.1.0/thumbnail.png
  packages/preview/bamdone-aiaa/0.1.0/typst.toml
Labels: new

#425 arkheion:0.1.0
  packages/preview/arkheion/0.1.0/README.md
  packages/preview/arkheion/0.1.0/example.png
  packages/preview/arkheion/0.1.0/orcid.svg
  packages/preview/arkheion/0.1.0/template.typ
  packages/preview/arkheion/0.1.0/template/bibliography.bib
  packages/preview/arkheion/0.1.0/template/image.png
  packages/preview/arkheion/0.1.0/template/main.typ
  packages/preview/arkheion/0.1.0/typst.toml
Labels: new

#465 silky-letter-insa:0.1.0
  packages/preview/silky-letter-insa/0.1.0/README.md
  packages/preview/silky-letter-insa/0.1.0/footer.png
  packages/preview/silky-letter-insa/0.1.0/lib.typ
  packages/preview/silky-letter-insa/0.1.0/logo.png
  packages/preview/silky-letter-insa/0.1.0/template/main.typ
  packages/preview/silky-letter-insa/0.1.0/thumbnail.png
  packages/preview/silky-letter-insa/0.1.0/typst.toml
Labels: new

#472 ttt-utils:0.1.0
  packages/preview/ttt-utils/0.1.0/LICENSE
  packages/preview/ttt-utils/0.1.0/README.md
  packages/preview/ttt-utils/0.1.0/lib/assignments.typ
  packages/preview/ttt-utils/0.1.0/lib/components.typ
  packages/preview/ttt-utils/0.1.0/lib/grading.typ
  packages/preview/ttt-utils/0.1.0/lib/helpers.typ
  packages/preview/ttt-utils/0.1.0/lib/layout.typ
  packages/preview/ttt-utils/0.1.0/lib/lib.typ
  packages/preview/ttt-utils/0.1.0/lib/random.typ
  packages/preview/ttt-utils/0.1.0/typst.toml
Labels: new

#478 ilm:0.1.2
  packages/preview/ilm/0.1.2/LICENSE
  packages/preview/ilm/0.1.2/README.md
  packages/preview/ilm/0.1.2/lib.typ
  packages/preview/ilm/0.1.2/template/main.typ
  packages/preview/ilm/0.1.2/template/refs.bib
  packages/preview/ilm/0.1.2/thumbnail.png
  packages/preview/ilm/0.1.2/typst.toml
Labels: update

#480 gentle-clues:0.7.1
  packages/preview/gentle-clues/0.7.1/.gitignore
  packages/preview/gentle-clues/0.7.1/CHANGELOG.md
  packages/preview/gentle-clues/0.7.1/LICENSE
  packages/preview/gentle-clues/0.7.1/README.md
  packages/preview/gentle-clues/0.7.1/assets/abstract.svg
  packages/preview/gentle-clues/0.7.1/assets/bell.svg
  packages/preview/gentle-clues/0.7.1/assets/bookmark.svg
  packages/preview/gentle-clues/0.7.1/assets/checkbox.svg
  packages/preview/gentle-clues/0.7.1/assets/crossmark.svg
  packages/preview/gentle-clues/0.7.1/assets/danger.svg
  packages/preview/gentle-clues/0.7.1/assets/example.svg
  packages/preview/gentle-clues/0.7.1/assets/excl.svg
  packages/preview/gentle-clues/0.7.1/assets/flag.svg
  packages/preview/gentle-clues/0.7.1/assets/info.svg
  packages/preview/gentle-clues/0.7.1/assets/lightbulb.svg
  packages/preview/gentle-clues/0.7.1/assets/questionmark.svg
  packages/preview/gentle-clues/0.7.1/assets/quote.svg
  packages/preview/gentle-clues/0.7.1/assets/task.svg
  packages/preview/gentle-clues/0.7.1/assets/tip.svg
  packages/preview/gentle-clues/0.7.1/assets/warning.svg
  packages/preview/gentle-clues/0.7.1/gc_overview.svg
  packages/preview/gentle-clues/0.7.1/gentle-clues.typ
  packages/preview/gentle-clues/0.7.1/lang.toml
  packages/preview/gentle-clues/0.7.1/typst.toml
Labels: update

#469 starter-journal-article:0.1.1
  packages/preview/starter-journal-article/0.1.1/README.md
  packages/preview/starter-journal-article/0.1.1/lib.typ
  packages/preview/starter-journal-article/0.1.1/template/.gitignore
  packages/preview/starter-journal-article/0.1.1/template/main.typ
  packages/preview/starter-journal-article/0.1.1/template/ref.bib
  packages/preview/starter-journal-article/0.1.1/thumbnail.png
  packages/preview/starter-journal-article/0.1.1/typst.toml
Labels: new

#476 touying:0.3.3 and touying-aqua:0.3.3
  packages/preview/touying-aqua/0.3.3/README.md
  packages/preview/touying-aqua/0.3.3/lib.typ
  packages/preview/touying-aqua/0.3.3/template/main.typ
  packages/preview/touying-aqua/0.3.3/thumbnail.png
  packages/preview/touying-aqua/0.3.3/typst.toml
  packages/preview/touying/0.3.3/.gitignore
  packages/preview/touying/0.3.3/LICENSE
  packages/preview/touying/0.3.3/README.md
  packages/preview/touying/0.3.3/changelog.md
  packages/preview/touying/0.3.3/examples/aqua-zh.typ
  packages/preview/touying/0.3.3/examples/aqua.typ
  packages/preview/touying/0.3.3/examples/dewdrop.typ
  packages/preview/touying/0.3.3/examples/example.typ
  packages/preview/touying/0.3.3/examples/metropolis.typ
  packages/preview/touying/0.3.3/examples/simple.typ
  packages/preview/touying/0.3.3/examples/slides.typ
  packages/preview/touying/0.3.3/examples/university.typ
  packages/preview/touying/0.3.3/lib.typ
  packages/preview/touying/0.3.3/slide.typ
  packages/preview/touying/0.3.3/themes/aqua.typ
  packages/preview/touying/0.3.3/themes/default.typ
  packages/preview/touying/0.3.3/themes/dewdrop.typ
  packages/preview/touying/0.3.3/themes/metropolis.typ
  packages/preview/touying/0.3.3/themes/simple.typ
  packages/preview/touying/0.3.3/themes/themes.typ
  packages/preview/touying/0.3.3/themes/university.typ
  packages/preview/touying/0.3.3/typst.toml
  packages/preview/touying/0.3.3/utils/components.typ
  packages/preview/touying/0.3.3/utils/pdfpc.typ
  packages/preview/touying/0.3.3/utils/states.typ
  packages/preview/touying/0.3.3/utils/utils.typ
Labels: new, update

#474 ascii-ipa:1.1.1 (metadata update)
  packages/preview/ascii-ipa/1.0.0/typst.toml
  packages/preview/ascii-ipa/1.1.0/typst.toml
  packages/preview/ascii-ipa/1.1.1/typst.toml
  test.typ
Labels: minor fix

#409 klaro-ifsc-sj:0.1.0
  packages/preview/klaro-ifsc-sj/0.1.0/LICENSE
  packages/preview/klaro-ifsc-sj/0.1.0/README.md
  packages/preview/klaro-ifsc-sj/0.1.0/assets/ifsc-v.png
  packages/preview/klaro-ifsc-sj/0.1.0/lib.typ
  packages/preview/klaro-ifsc-sj/0.1.0/template/main.typ
  packages/preview/klaro-ifsc-sj/0.1.0/thumbnail.png
  packages/preview/klaro-ifsc-sj/0.1.0/typst.toml
Labels: new

#481 suiji:0.2.1
  packages/preview/suiji/0.2.1/LICENSE
  packages/preview/suiji/0.2.1/README.md
  packages/preview/suiji/0.2.1/examples/matrix-rain.pdf
  packages/preview/suiji/0.2.1/examples/matrix-rain.png
  packages/preview/suiji/0.2.1/examples/matrix-rain.typ
  packages/preview/suiji/0.2.1/examples/random-permutation.pdf
  packages/preview/suiji/0.2.1/examples/random-permutation.png
  packages/preview/suiji/0.2.1/examples/random-permutation.typ
  packages/preview/suiji/0.2.1/examples/random-walk.pdf
  packages/preview/suiji/0.2.1/examples/random-walk.png
  packages/preview/suiji/0.2.1/examples/random-walk.typ
  packages/preview/suiji/0.2.1/src/lib.typ
  packages/preview/suiji/0.2.1/src/random.typ
  packages/preview/suiji/0.2.1/src/taus.typ
  packages/preview/suiji/0.2.1/tests/test-choice.pdf
  packages/preview/suiji/0.2.1/tests/test-choice.typ
  packages/preview/suiji/0.2.1/tests/test-discrete.pdf
  packages/preview/suiji/0.2.1/tests/test-discrete.typ
  packages/preview/suiji/0.2.1/tests/test-integers.pdf
  packages/preview/suiji/0.2.1/tests/test-integers.typ
  packages/preview/suiji/0.2.1/tests/test-normal.pdf
  packages/preview/suiji/0.2.1/tests/test-normal.typ
  packages/preview/suiji/0.2.1/tests/test-random.pdf
  packages/preview/suiji/0.2.1/tests/test-random.typ
  packages/preview/suiji/0.2.1/tests/test-shuffle.pdf
  packages/preview/suiji/0.2.1/tests/test-shuffle.typ
  packages/preview/suiji/0.2.1/tests/test-uniform.pdf
  packages/preview/suiji/0.2.1/tests/test-uniform.typ
  packages/preview/suiji/0.2.1/typst.toml
Labels: update

#482 smooth-tmlr:0.3.0
  packages/preview/smooth-tmlr/0.3.0/LICENSE
  packages/preview/smooth-tmlr/0.3.0/README.md
  packages/preview/smooth-tmlr/0.3.0/template/appendix.typ
  packages/preview/smooth-tmlr/0.3.0/template/logo.typ
  packages/preview/smooth-tmlr/0.3.0/template/main.bib
  packages/preview/smooth-tmlr/0.3.0/template/main.typ
  packages/preview/smooth-tmlr/0.3.0/thumbnail.png
  packages/preview/smooth-tmlr/0.3.0/tmlr.csl
  packages/preview/smooth-tmlr/0.3.0/tmlr.typ
  packages/preview/smooth-tmlr/0.3.0/typst.toml
Labels: new

#466 invoice-maker:1.1.0
  packages/preview/invoice-maker/1.1.0/LICENSE
  packages/preview/invoice-maker/1.1.0/README.md
  packages/preview/invoice-maker/1.1.0/lib.typ
  packages/preview/invoice-maker/1.1.0/template/banner.png
  packages/preview/invoice-maker/1.1.0/template/main.typ
  packages/preview/invoice-maker/1.1.0/thumbnail.png
  packages/preview/invoice-maker/1.1.0/typst.toml
Labels: new
