Repository typst/packages, pull requests merged in 2025-03, with the labels that each got.

#1685 kanjimo:0.1.0
  packages/preview/kanjimo/0.1.0/LICENSE
  packages/preview/kanjimo/0.1.0/README.md
  packages/preview/kanjimo/0.1.0/data/kanjiapi_full.cbor
  packages/preview/kanjimo/0.1.0/docs/typst-screenshot.png
  packages/preview/kanjimo/0.1.0/lib.typ
  packages/preview/kanjimo/0.1.0/src.typ
  packages/preview/kanjimo/0.1.0/typst.toml
Labels: new

#1893 cetz:0.3.3
  packages/preview/cetz/0.3.3/LICENSE
  packages/preview/cetz/0.3.3/README.md
  packages/preview/cetz/0.3.3/gallery/karls-picture.png
  packages/preview/cetz/0.3.3/gallery/karls-picture.typ
  packages/preview/cetz/0.3.3/gallery/paciolis.png
  packages/preview/cetz/0.3.3/gallery/paciolis.typ
  packages/preview/cetz/0.3.3/gallery/periodic-table.png
  packages/preview/cetz/0.3.3/gallery/periodic-table.typ
  packages/preview/cetz/0.3.3/gallery/plate-capacitor.png
  packages/preview/cetz/0.3.3/gallery/plate-capacitor.typ
  packages/preview/cetz/0.3.3/gallery/tree.png
  packages/preview/cetz/0.3.3/gallery/tree.typ
  packages/preview/cetz/0.3.3/gallery/waves.png
  packages/preview/cetz/0.3.3/gallery/waves.typ
  packages/preview/cetz/0.3.3/src/aabb.typ
  packages/preview/cetz/0.3.3/src/anchor.typ
  packages/preview/cetz/0.3.3/src/bezier.typ
  packages/preview/cetz/0.3.3/src/canvas.typ
  packages/preview/cetz/0.3.3/src/complex.typ
  packages/preview/cetz/0.3.3/src/coordinate.typ
  packages/preview/cetz/0.3.3/src/deps.typ
  packages/preview/cetz/0.3.3/src/draw.typ
  packages/preview/cetz/0.3.3/src/draw/grouping.typ
  packages/preview/cetz/0.3.3/src/draw/projection.typ
  packages/preview/cetz/0.3.3/src/draw/shapes.typ
  packages/preview/cetz/0.3.3/src/draw/styling.typ
  packages/preview/cetz/0.3.3/src/draw/transformations.typ
  packages/preview/cetz/0.3.3/src/draw/util.typ
  packages/preview/cetz/0.3.3/src/drawable.typ
  packages/preview/cetz/0.3.3/src/hobby.typ
  packages/preview/cetz/0.3.3/src/intersection.typ
  packages/preview/cetz/0.3.3/src/lib.typ
  packages/preview/cetz/0.3.3/src/lib/angle.typ
  packages/preview/cetz/0.3.3/src/lib/decorations.typ
  packages/preview/cetz/0.3.3/src/lib/decorations/brace.typ
  packages/preview/cetz/0.3.3/src/lib/decorations/path.typ
  packages/preview/cetz/0.3.3/src/lib/palette.typ
  packages/preview/cetz/0.3.3/src/lib/pin.typ
  packages/preview/cetz/0.3.3/src/lib/tree.typ
  packages/preview/cetz/0.3.3/src/mark-shapes.typ
  packages/preview/cetz/0.3.3/src/mark.typ
  packages/preview/cetz/0.3.3/src/matrix.typ
  packages/preview/cetz/0.3.3/src/path-util.typ
  packages/preview/cetz/0.3.3/src/polygon.typ
  packages/preview/cetz/0.3.3/src/process.typ
  packages/preview/cetz/0.3.3/src/sorting.typ
  packages/preview/cetz/0.3.3/src/styles.typ
  packages/preview/cetz/0.3.3/src/util.typ
  packages/preview/cetz/0.3.3/src/vector.typ
  packages/preview/cetz/0.3.3/src/version.typ
  packages/preview/cetz/0.3.3/typst.toml
Labels: update

#1869 jogs:0.2.4
  packages/preview/jogs/0.2.4/LICENSE
  packages/preview/jogs/0.2.4/README.md
  packages/preview/jogs/0.2.4/examples/fib.svg
  packages/preview/jogs/0.2.4/examples/fib.typ
  packages/preview/jogs/0.2.4/jogs.wasm
  packages/preview/jogs/0.2.4/lib.typ
  packages/preview/jogs/0.2.4/license.html
  packages/preview/jogs/0.2.4/typst.toml
Labels: update

#1870 equate:0.3.1
  packages/preview/equate/0.3.1/LICENSE
  packages/preview/equate/0.3.1/README.md
  packages/preview/equate/0.3.1/assets/example-1.svg
  packages/preview/equate/0.3.1/assets/example-2.svg
  packages/preview/equate/0.3.1/assets/example.typ
  packages/preview/equate/0.3.1/src/equate.typ
  packages/preview/equate/0.3.1/src/lib.typ
  packages/preview/equate/0.3.1/typst.toml
Labels: update

#1871 quick-maths:0.2.1
  packages/preview/quick-maths/0.2.1/LICENSE
  packages/preview/quick-maths/0.2.1/README.md
  packages/preview/quick-maths/0.2.1/assets/example.svg
  packages/preview/quick-maths/0.2.1/assets/example.typ
  packages/preview/quick-maths/0.2.1/src/lib.typ
  packages/preview/quick-maths/0.2.1/src/quick-maths.typ
  packages/preview/quick-maths/0.2.1/typst.toml
Labels: update

#1876 tableau-icons:0.330.0
  packages/preview/tableau-icons/0.330.0/LICENSE
  packages/preview/tableau-icons/0.330.0/README.md
  packages/preview/tableau-icons/0.330.0/_tableau-icons-ref.typ
  packages/preview/tableau-icons/0.330.0/docs/banner.png
  packages/preview/tableau-icons/0.330.0/docs/changelog.typ
  packages/preview/tableau-icons/0.330.0/docs/tableau-icons-doc.pdf
  packages/preview/tableau-icons/0.330.0/docs/tableau-icons-doc.typ
  packages/preview/tableau-icons/0.330.0/docs/thumbnail_list.typ
  packages/preview/tableau-icons/0.330.0/lib.typ
  packages/preview/tableau-icons/0.330.0/tableau-icons.typ
  packages/preview/tableau-icons/0.330.0/tools/generate_unicode_reference.py
  packages/preview/tableau-icons/0.330.0/tools/update_icon_set.py
  packages/preview/tableau-icons/0.330.0/typst.toml
Labels: update

#1878 muchpdf:0.1.1
  packages/preview/muchpdf/0.1.1/LICENSE
  packages/preview/muchpdf/0.1.1/README.md
  packages/preview/muchpdf/0.1.1/lib.typ
  packages/preview/muchpdf/0.1.1/muchpdf.wasm
  packages/preview/muchpdf/0.1.1/typst.toml
Labels: update

#1884 relescope:0.0.1
  packages/preview/relescope/0.0.1/LICENSE
  packages/preview/relescope/0.0.1/README.md
  packages/preview/relescope/0.0.1/bin/plugin.wasm
  packages/preview/relescope/0.0.1/examples/example.svg
  packages/preview/relescope/0.0.1/examples/example.typ
  packages/preview/relescope/0.0.1/src/lib.typ
  packages/preview/relescope/0.0.1/src/wrap.typ
  packages/preview/relescope/0.0.1/typst.toml
Labels: new

#1886 decasify:0.9.1
  packages/preview/decasify/0.9.1/LICENSE
  packages/preview/decasify/0.9.1/README.md
  packages/preview/decasify/0.9.1/decasify.typ
  packages/preview/decasify/0.9.1/decasify.wasm
  packages/preview/decasify/0.9.1/readme_1.svg
  packages/preview/decasify/0.9.1/readme_2.svg
  packages/preview/decasify/0.9.1/typst.toml
Labels: update

#1887 circuiteria:0.2.0
  packages/preview/circuiteria/0.2.0/LICENSE
  packages/preview/circuiteria/0.2.0/README.md
  packages/preview/circuiteria/0.2.0/doc/example.typ
  packages/preview/circuiteria/0.2.0/doc/examples.typ
  packages/preview/circuiteria/0.2.0/gallery/platypus.pdf
  packages/preview/circuiteria/0.2.0/gallery/platypus.png
  packages/preview/circuiteria/0.2.0/gallery/platypus.typ
  packages/preview/circuiteria/0.2.0/gallery/test.pdf
  packages/preview/circuiteria/0.2.0/gallery/test.png
  packages/preview/circuiteria/0.2.0/gallery/test.typ
  packages/preview/circuiteria/0.2.0/gallery/test2.pdf
  packages/preview/circuiteria/0.2.0/gallery/test2.png
  packages/preview/circuiteria/0.2.0/gallery/test2.typ
  packages/preview/circuiteria/0.2.0/gallery/test3.pdf
  packages/preview/circuiteria/0.2.0/gallery/test3.png
  packages/preview/circuiteria/0.2.0/gallery/test3.typ
  packages/preview/circuiteria/0.2.0/gallery/test4.pdf
  packages/preview/circuiteria/0.2.0/gallery/test4.png
  packages/preview/circuiteria/0.2.0/gallery/test4.typ
  packages/preview/circuiteria/0.2.0/gallery/test5.pdf
  packages/preview/circuiteria/0.2.0/gallery/test5.png
  packages/preview/circuiteria/0.2.0/gallery/test5.typ
  packages/preview/circuiteria/0.2.0/gallery/test6.pdf
  packages/preview/circuiteria/0.2.0/gallery/test6.png
  packages/preview/circuiteria/0.2.0/gallery/test6.typ
  packages/preview/circuiteria/0.2.0/gallery/test7.json
  packages/preview/circuiteria/0.2.0/justfile
  packages/preview/circuiteria/0.2.0/manual.pdf
  packages/preview/circuiteria/0.2.0/manual.typ
  packages/preview/circuiteria/0.2.0/src/circuit.typ
  packages/preview/circuiteria/0.2.0/src/element.typ
  packages/preview/circuiteria/0.2.0/src/elements/alu.typ
  packages/preview/circuiteria/0.2.0/src/elements/block.typ
  packages/preview/circuiteria/0.2.0/src/elements/electrical/src_drain.typ
  packages/preview/circuiteria/0.2.0/src/elements/element.typ
  packages/preview/circuiteria/0.2.0/src/elements/extender.typ
  packages/preview/circuiteria/0.2.0/src/elements/group.typ
  packages/preview/circuiteria/0.2.0/src/elements/logic/and.typ
  packages/preview/circuiteria/0.2.0/src/elements/logic/buf.typ
  packages/preview/circuiteria/0.2.0/src/elements/logic/gate.typ
  packages/preview/circuiteria/0.2.0/src/elements/logic/or.typ
  packages/preview/circuiteria/0.2.0/src/elements/logic/xor.typ
  packages/preview/circuiteria/0.2.0/src/elements/multiplexer.typ
  packages/preview/circuiteria/0.2.0/src/elements/ports.typ
  packages/preview/circuiteria/0.2.0/src/gates.typ
  packages/preview/circuiteria/0.2.0/src/lib.typ
  packages/preview/circuiteria/0.2.0/src/util.typ
  packages/preview/circuiteria/0.2.0/src/wire.typ
  packages/preview/circuiteria/0.2.0/typst.toml
Labels: update

#1894 vlna:0.1.0
  packages/preview/vlna/0.1.0/LICENSE
  packages/preview/vlna/0.1.0/README.md
  packages/preview/vlna/0.1.0/examples/example.typ
  packages/preview/vlna/0.1.0/lib.typ
  packages/preview/vlna/0.1.0/typst.toml
Labels: new

#1896 ilm:1.4.1
  packages/preview/ilm/1.4.1/LICENSE
  packages/preview/ilm/1.4.1/README.md
  packages/preview/ilm/1.4.1/lib.typ
  packages/preview/ilm/1.4.1/template/main.typ
  packages/preview/ilm/1.4.1/template/refs.bib
  packages/preview/ilm/1.4.1/thumbnail.png
  packages/preview/ilm/1.4.1/typst.toml
Labels: update

#1898 illc-mol-thesis:0.1.2
  packages/preview/illc-mol-thesis/0.1.2/LICENSE
  packages/preview/illc-mol-thesis/0.1.2/README.md
  packages/preview/illc-mol-thesis/0.1.2/img/illclogo.svg
  packages/preview/illc-mol-thesis/0.1.2/img/thumbnail.png
  packages/preview/illc-mol-thesis/0.1.2/src/main.typ
  packages/preview/illc-mol-thesis/0.1.2/template/main.typ
  packages/preview/illc-mol-thesis/0.1.2/template/references.bib
  packages/preview/illc-mol-thesis/0.1.2/typst.toml
Labels: update

#1882 typsium:0.2.0
  packages/preview/typsium/0.2.0/LICENSE
  packages/preview/typsium/0.2.0/README.md
  packages/preview/typsium/0.2.0/src/data-model.typ
  packages/preview/typsium/0.2.0/src/formula-parser.typ
  packages/preview/typsium/0.2.0/src/lib.typ
  packages/preview/typsium/0.2.0/src/regex.typ
  packages/preview/typsium/0.2.0/src/resources/elements.csv
  packages/preview/typsium/0.2.0/src/utils.typ
  packages/preview/typsium/0.2.0/typst.toml
Labels: update

#1899 minimal-presentation:0.5.0
  packages/preview/minimal-presentation/0.5.0/LICENSE
  packages/preview/minimal-presentation/0.5.0/README.md
  packages/preview/minimal-presentation/0.5.0/lib.typ
  packages/preview/minimal-presentation/0.5.0/template/image_1.jpg
  packages/preview/minimal-presentation/0.5.0/template/logo.svg
  packages/preview/minimal-presentation/0.5.0/template/logo_light.svg
  packages/preview/minimal-presentation/0.5.0/template/main.typ
  packages/preview/minimal-presentation/0.5.0/thumbnail.png
  packages/preview/minimal-presentation/0.5.0/typst.toml
Labels: update

#1900 haw-hamburg-bachelor-thesis:0.5.0, haw-hamburg-master-thesis:0.5.0, haw-hamburg-report:0.5.0 and haw-hamburg:0.5.0
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/LICENSE
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/README.md
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/lib.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/abbreviations.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/bibliography.bib
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/dependencies.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/glossary.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/ieeetran.csl
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/src/main.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/thumbnail.png
  packages/preview/haw-hamburg-bachelor-thesis/0.5.0/typst.toml
  packages/preview/haw-hamburg-master-thesis/0.5.0/LICENSE
  packages/preview/haw-hamburg-master-thesis/0.5.0/README.md
  packages/preview/haw-hamburg-master-thesis/0.5.0/lib.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/abbreviations.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/bibliography.bib
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/dependencies.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/glossary.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/ieeetran.csl
  packages/preview/haw-hamburg-master-thesis/0.5.0/src/main.typ
  packages/preview/haw-hamburg-master-thesis/0.5.0/thumbnail.png
  packages/preview/haw-hamburg-master-thesis/0.5.0/typst.toml
  packages/preview/haw-hamburg-report/0.5.0/LICENSE
  packages/preview/haw-hamburg-report/0.5.0/README.md
  packages/preview/haw-hamburg-report/0.5.0/lib.typ
  packages/preview/haw-hamburg-report/0.5.0/src/abbreviations.typ
  packages/preview/haw-hamburg-report/0.5.0/src/bibliography.bib
  packages/preview/haw-hamburg-report/0.5.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-report/0.5.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-report/0.5.0/src/dependencies.typ
  packages/preview/haw-hamburg-report/0.5.0/src/glossary.typ
  packages/preview/haw-hamburg-report/0.5.0/src/ieeetran.csl
  packages/preview/haw-hamburg-report/0.5.0/src/main.typ
  packages/preview/haw-hamburg-report/0.5.0/thumbnail.png
  packages/preview/haw-hamburg-report/0.5.0/typst.toml
  packages/preview/haw-hamburg/0.5.0/LICENSE
  packages/preview/haw-hamburg/0.5.0/README.md
  packages/preview/haw-hamburg/0.5.0/assets/ieeetran.csl
  packages/preview/haw-hamburg/0.5.0/assets/logo.svg
  packages/preview/haw-hamburg/0.5.0/lib.typ
  packages/preview/haw-hamburg/0.5.0/pages/abstract.typ
  packages/preview/haw-hamburg/0.5.0/pages/cover.typ
  packages/preview/haw-hamburg/0.5.0/pages/declaration_of_independent_processing.typ
  packages/preview/haw-hamburg/0.5.0/pages/list_of_figures.typ
  packages/preview/haw-hamburg/0.5.0/pages/list_of_tables.typ
  packages/preview/haw-hamburg/0.5.0/pages/listings.typ
  packages/preview/haw-hamburg/0.5.0/pages/outline.typ
  packages/preview/haw-hamburg/0.5.0/template.typ
  packages/preview/haw-hamburg/0.5.0/translations.typ
  packages/preview/haw-hamburg/0.5.0/typst.toml
Labels: update

#1901 tidy:0.4.2
  packages/preview/tidy/0.4.2/LICENSE
  packages/preview/tidy/0.4.2/README.md
  packages/preview/tidy/0.4.2/src/helping.typ
  packages/preview/tidy/0.4.2/src/new-parser.typ
  packages/preview/tidy/0.4.2/src/old-parser.typ
  packages/preview/tidy/0.4.2/src/parse-module.typ
  packages/preview/tidy/0.4.2/src/show-example.typ
  packages/preview/tidy/0.4.2/src/show-module.typ
  packages/preview/tidy/0.4.2/src/styles.typ
  packages/preview/tidy/0.4.2/src/styles/default.typ
  packages/preview/tidy/0.4.2/src/styles/help.typ
  packages/preview/tidy/0.4.2/src/styles/minimal.typ
  packages/preview/tidy/0.4.2/src/testing.typ
  packages/preview/tidy/0.4.2/src/tidy.typ
  packages/preview/tidy/0.4.2/src/utilities.typ
  packages/preview/tidy/0.4.2/typst.toml
Labels: update

#1891 universal-hit-thesis:0.3.0
  packages/preview/universal-hit-thesis/0.3.0/LICENSE
  packages/preview/universal-hit-thesis/0.3.0/README.md
  packages/preview/universal-hit-thesis/0.3.0/common/components/bilingual-bibliography.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/digital-signature.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/enheading.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/figure.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/footer.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/header.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/table.typ
  packages/preview/universal-hit-thesis/0.3.0/common/components/typography.typ
  packages/preview/universal-hit-thesis/0.3.0/common/config/constants.typ
  packages/preview/universal-hit-thesis/0.3.0/common/pages/abstract.typ
  packages/preview/universal-hit-thesis/0.3.0/common/pages/achievement.typ
  packages/preview/universal-hit-thesis/0.3.0/common/pages/acknowledgement.typ
  packages/preview/universal-hit-thesis/0.3.0/common/pages/bibliography.typ
  packages/preview/universal-hit-thesis/0.3.0/common/pages/conclusion.typ
  packages/preview/universal-hit-thesis/0.3.0/common/pages/outline.typ
  packages/preview/universal-hit-thesis/0.3.0/common/theme/type.typ
  packages/preview/universal-hit-thesis/0.3.0/common/utils/states.typ
  packages/preview/universal-hit-thesis/0.3.0/common/utils/word-template-diff-tool.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/components/typography.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/conf.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/config/constants.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/lib.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/pages/cover.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/pages/declaration-of-originality.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/utils/counters.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/utils/numbering.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/bachelor/utils/states.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/doctor/conf.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/doctor/config/constants.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/doctor/lib.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/doctor/pages/cover.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/doctor/pages/declaration-of-originality.typ
  packages/preview/universal-hit-thesis/0.3.0/harbin/doctor/pages/personal-resume.typ
  packages/preview/universal-hit-thesis/0.3.0/lib.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/conf.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/config/constants.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/lib.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/pages/cover.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/pages/declaration-of-originality.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/pages/personal-resume.typ
  packages/preview/universal-hit-thesis/0.3.0/shenzhen/master/utils/states.typ
  packages/preview/universal-hit-thesis/0.3.0/templates/gb-t-7714-2015-numeric-hit.csl
  packages/preview/universal-hit-thesis/0.3.0/templates/hit-thesis-ref.bib
  packages/preview/universal-hit-thesis/0.3.0/templates/shenzhen-master.typ
  packages/preview/universal-hit-thesis/0.3.0/templates/universal-bachelor.typ
  packages/preview/universal-hit-thesis/0.3.0/templates/universal-doctor.typ
  packages/preview/universal-hit-thesis/0.3.0/thumbnail.png
  packages/preview/universal-hit-thesis/0.3.0/typst.toml
Labels: update

#1834 flyingcircus:3.2.1
  packages/preview/flyingcircus/3.2.1/CHANGELOG.md
  packages/preview/flyingcircus/3.2.1/LICENSE
  packages/preview/flyingcircus/3.2.1/README.md
  packages/preview/flyingcircus/3.2.1/src/FlyingCircus.typ
  packages/preview/flyingcircus/3.2.1/src/Impl.typ
  packages/preview/flyingcircus/3.2.1/src/images/Default.png
  packages/preview/flyingcircus/3.2.1/template/Basic Biplane_stats.json
  packages/preview/flyingcircus/3.2.1/template/Main.typ
  packages/preview/flyingcircus/3.2.1/template/Sample Vehicle_stats.json
  packages/preview/flyingcircus/3.2.1/template/images/Bergziegel_image.jpg
  packages/preview/flyingcircus/3.2.1/template/images/Cover.png
  packages/preview/flyingcircus/3.2.1/template/images/Macchi Frigate.png
  packages/preview/flyingcircus/3.2.1/template/images/Rifle.png
  packages/preview/flyingcircus/3.2.1/template/images/Wandelburg.jpg
  packages/preview/flyingcircus/3.2.1/thumbnail.png
  packages/preview/flyingcircus/3.2.1/typst.toml
Labels: update

#1903 tracl:0.5.1
  packages/preview/tracl/0.5.1/LICENSE
  packages/preview/tracl/0.5.1/README.md
  packages/preview/tracl/0.5.1/lib.typ
  packages/preview/tracl/0.5.1/template/association-for-computational-linguistics-blinky.csl
  packages/preview/tracl/0.5.1/template/main.typ
  packages/preview/tracl/0.5.1/thumbnail.png
  packages/preview/tracl/0.5.1/typst.toml
Labels: update

#1902 touying-unistra-pristine:1.3.1
  packages/preview/touying-unistra-pristine/1.3.1/typst.toml
Labels: update

#1907 algo:0.3.5
  packages/preview/algo/0.3.5/LICENSE
  packages/preview/algo/0.3.5/README.md
  packages/preview/algo/0.3.5/algo.typ
  packages/preview/algo/0.3.5/typst.toml
Labels: update

#1885 scripst:1.1.0
  packages/preview/scripst/1.1.0/LICENSE
  packages/preview/scripst/1.1.0/README.md
  packages/preview/scripst/1.1.0/README_zh-CN.md
  packages/preview/scripst/1.1.0/docs/article.typ
  packages/preview/scripst/1.1.0/docs/book.typ
  packages/preview/scripst/1.1.0/docs/builds/article.pdf
  packages/preview/scripst/1.1.0/docs/builds/book.pdf
  packages/preview/scripst/1.1.0/docs/builds/report.pdf
  packages/preview/scripst/1.1.0/docs/chap1.typ
  packages/preview/scripst/1.1.0/docs/chap2.typ
  packages/preview/scripst/1.1.0/docs/chap3.typ
  packages/preview/scripst/1.1.0/docs/chap4.typ
  packages/preview/scripst/1.1.0/docs/locale/article-en.typ
  packages/preview/scripst/1.1.0/docs/locale/builds/article-en.pdf
  packages/preview/scripst/1.1.0/docs/locale/pic/pic.jpg
  packages/preview/scripst/1.1.0/docs/pic/pic.jpg
  packages/preview/scripst/1.1.0/docs/report.typ
  packages/preview/scripst/1.1.0/makefile
  packages/preview/scripst/1.1.0/previews/article-1.png
  packages/preview/scripst/1.1.0/previews/article-12.png
  packages/preview/scripst/1.1.0/previews/article-2.png
  packages/preview/scripst/1.1.0/previews/article-9.png
  packages/preview/scripst/1.1.0/previews/book-1.png
  packages/preview/scripst/1.1.0/previews/book-2.png
  packages/preview/scripst/1.1.0/previews/countblock.png
  packages/preview/scripst/1.1.0/previews/report-1.png
  packages/preview/scripst/1.1.0/previews/report-2.png
  packages/preview/scripst/1.1.0/src/components.typ
  packages/preview/scripst/1.1.0/src/configs.typ
  packages/preview/scripst/1.1.0/src/locale.typ
  packages/preview/scripst/1.1.0/src/locale/locale.yml
  packages/preview/scripst/1.1.0/src/main.typ
  packages/preview/scripst/1.1.0/src/package.typ
  packages/preview/scripst/1.1.0/src/styling.typ
  packages/preview/scripst/1.1.0/src/template.typ
  packages/preview/scripst/1.1.0/template/main.typ
  packages/preview/scripst/1.1.0/thumbnail.png
  packages/preview/scripst/1.1.0/typst.toml
Labels: new

#1910 quick-cards:0.1.1
  packages/preview/quick-cards/0.1.1/LICENSE
  packages/preview/quick-cards/0.1.1/README.md
  packages/preview/quick-cards/0.1.1/src/card-templates.typ
  packages/preview/quick-cards/0.1.1/src/core.typ
  packages/preview/quick-cards/0.1.1/src/lib.typ
  packages/preview/quick-cards/0.1.1/src/utils.typ
  packages/preview/quick-cards/0.1.1/typst.toml
Labels: update

#1883 typsium-atomic:0.1.0
  packages/preview/typsium-atomic/0.1.0/LICENSE
  packages/preview/typsium-atomic/0.1.0/README.md
  packages/preview/typsium-atomic/0.1.0/src/lib.typ
  packages/preview/typsium-atomic/0.1.0/typst.toml
Labels: new

#1914 typsium-ghs:0.1.0
  packages/preview/typsium-ghs/0.1.0/LICENSE
  packages/preview/typsium-ghs/0.1.0/README.md
  packages/preview/typsium-ghs/0.1.0/src/ghs.typ
  packages/preview/typsium-ghs/0.1.0/src/hp.typ
  packages/preview/typsium-ghs/0.1.0/src/lib.typ
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS01.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS02.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS03.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS04.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS05.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS06.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS07.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS08.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/ghs-pictograms/GHS09.svg
  packages/preview/typsium-ghs/0.1.0/src/resources/hp-statements.tsv
  packages/preview/typsium-ghs/0.1.0/typst.toml
Labels: new

#1916 flow:0.3.0
  packages/preview/flow/0.3.0/CHANGELOG.md
  packages/preview/flow/0.3.0/LICENSE.md
  packages/preview/flow/0.3.0/README.md
  packages/preview/flow/0.3.0/asset/data.toml
  packages/preview/flow/0.3.0/asset/halcyon.tmTheme
  packages/preview/flow/0.3.0/src/asset.typ
  packages/preview/flow/0.3.0/src/callout.typ
  packages/preview/flow/0.3.0/src/cfg.typ
  packages/preview/flow/0.3.0/src/checkbox.typ
  packages/preview/flow/0.3.0/src/gfx/draw.typ
  packages/preview/flow/0.3.0/src/gfx/maybe-stub.typ
  packages/preview/flow/0.3.0/src/gfx/mod.typ
  packages/preview/flow/0.3.0/src/gfx/render/mod.typ
  packages/preview/flow/0.3.0/src/gfx/render/segment.typ
  packages/preview/flow/0.3.0/src/gfx/stub.typ
  packages/preview/flow/0.3.0/src/gfx/stub/draw.typ
  packages/preview/flow/0.3.0/src/gfx/util.typ
  packages/preview/flow/0.3.0/src/hacks.typ
  packages/preview/flow/0.3.0/src/info.typ
  packages/preview/flow/0.3.0/src/keywords.typ
  packages/preview/flow/0.3.0/src/lib.typ
  packages/preview/flow/0.3.0/src/palette.typ
  packages/preview/flow/0.3.0/src/template.typ
  packages/preview/flow/0.3.0/src/tyck.typ
  packages/preview/flow/0.3.0/src/util/mod.typ
  packages/preview/flow/0.3.0/src/util/preset/ana.typ
  packages/preview/flow/0.3.0/src/util/preset/arrow.typ
  packages/preview/flow/0.3.0/src/util/preset/calculus.typ
  packages/preview/flow/0.3.0/src/util/preset/linalg.typ
  packages/preview/flow/0.3.0/src/util/preset/mod.typ
  packages/preview/flow/0.3.0/src/util/preset/ops.typ
  packages/preview/flow/0.3.0/src/util/preset/quantum.typ
  packages/preview/flow/0.3.0/src/xlink.typ
  packages/preview/flow/0.3.0/template/main.typ
  packages/preview/flow/0.3.0/thumbnail/page-1.png
  packages/preview/flow/0.3.0/typst.toml
  packages/preview/flow/0.3.0/util/common
  packages/preview/flow/0.3.0/util/flow
  packages/preview/flow/0.3.0/util/flow-export
  packages/preview/flow/0.3.0/util/flow-query
Labels: update

#1912 tuhi-exam-vuw:0.2.0
  packages/preview/tuhi-exam-vuw/0.2.0/LICENSE
  packages/preview/tuhi-exam-vuw/0.2.0/README.md
  packages/preview/tuhi-exam-vuw/0.2.0/logo.svg
  packages/preview/tuhi-exam-vuw/0.2.0/template/appendix.typ
  packages/preview/tuhi-exam-vuw/0.2.0/template/figures/roquefort.png
  packages/preview/tuhi-exam-vuw/0.2.0/template/logo.svg
  packages/preview/tuhi-exam-vuw/0.2.0/template/main.typ
  packages/preview/tuhi-exam-vuw/0.2.0/thumbnail.png
  packages/preview/tuhi-exam-vuw/0.2.0/tuhi-exam-vuw.typ
  packages/preview/tuhi-exam-vuw/0.2.0/typst.toml
Labels: update

#1917 use-tabler-icons:0.11.0
  packages/preview/use-tabler-icons/0.11.0/LICENSE
  packages/preview/use-tabler-icons/0.11.0/README.md
  packages/preview/use-tabler-icons/0.11.0/assets/banner.svg
  packages/preview/use-tabler-icons/0.11.0/src/lib-gen.typ
  packages/preview/use-tabler-icons/0.11.0/src/lib-impl.typ
  packages/preview/use-tabler-icons/0.11.0/src/lib.typ
  packages/preview/use-tabler-icons/0.11.0/typst.toml
Labels: update

#1920 peace-of-posters:0.5.2
  packages/preview/peace-of-posters/0.5.2/LICENSE
  packages/preview/peace-of-posters/0.5.2/README.md
  packages/preview/peace-of-posters/0.5.2/boxes.typ
  packages/preview/peace-of-posters/0.5.2/layouts.typ
  packages/preview/peace-of-posters/0.5.2/lib.typ
  packages/preview/peace-of-posters/0.5.2/templates/pop-uni-fr-poster/Treron_vernans_male_-_Kent_Ridge_Park.jpg
  packages/preview/peace-of-posters/0.5.2/templates/pop-uni-fr-poster/bibliography.bib
  packages/preview/peace-of-posters/0.5.2/templates/pop-uni-fr-poster/main.typ
  packages/preview/peace-of-posters/0.5.2/templates/pop-uni-fr-poster/peace-dove.png
  packages/preview/peace-of-posters/0.5.2/templates/pop-uni-fr-poster/thumbnail.png
  packages/preview/peace-of-posters/0.5.2/themes.typ
  packages/preview/peace-of-posters/0.5.2/typst.toml
Labels: update

#1921 modern-sjtu-thesis:0.2.0
  packages/preview/modern-sjtu-thesis/0.2.0/.gitignore
  packages/preview/modern-sjtu-thesis/0.2.0/LICENSE
  packages/preview/modern-sjtu-thesis/0.2.0/README.md
  packages/preview/modern-sjtu-thesis/0.2.0/assets/sjtu-logo.png
  packages/preview/modern-sjtu-thesis/0.2.0/layouts/appendix.typ
  packages/preview/modern-sjtu-thesis/0.2.0/layouts/doc.typ
  packages/preview/modern-sjtu-thesis/0.2.0/layouts/mainmatter.typ
  packages/preview/modern-sjtu-thesis/0.2.0/layouts/preface.typ
  packages/preview/modern-sjtu-thesis/0.2.0/lib.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/abstract-en.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/abstract.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/achievement.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/acknowledgement.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/bib.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/cover-bachelor.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/cover-en.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/cover.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/declare.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/outline.typ
  packages/preview/modern-sjtu-thesis/0.2.0/pages/summary-en.typ
  packages/preview/modern-sjtu-thesis/0.2.0/style.typ
  packages/preview/modern-sjtu-thesis/0.2.0/template/figures/energy-distribution.png
  packages/preview/modern-sjtu-thesis/0.2.0/template/ref.bib
  packages/preview/modern-sjtu-thesis/0.2.0/template/thesis.typ
  packages/preview/modern-sjtu-thesis/0.2.0/thumbnail.png
  packages/preview/modern-sjtu-thesis/0.2.0/typst.toml
  packages/preview/modern-sjtu-thesis/0.2.0/utils/checkbox.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/datetime-display.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/distr.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/header.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/heading.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/list-enum-align.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/style.typ
  packages/preview/modern-sjtu-thesis/0.2.0/utils/uline.typ
Labels: update

#1909 modern-ovgu-fma-polylux:0.1.0
  packages/preview/modern-ovgu-fma-polylux/0.1.0/LICENSE
  packages/preview/modern-ovgu-fma-polylux/0.1.0/README.md
  packages/preview/modern-ovgu-fma-polylux/0.1.0/Signet_FMA.svg
  packages/preview/modern-ovgu-fma-polylux/0.1.0/Signet_FMA_de.svg
  packages/preview/modern-ovgu-fma-polylux/0.1.0/Signet_FMA_en.svg
  packages/preview/modern-ovgu-fma-polylux/0.1.0/images/header-slide.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/images/outline-slide.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/images/slide-content.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/images/slide-image.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/images/slide-math.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/images/title-slide.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/math-utils.typ
  packages/preview/modern-ovgu-fma-polylux/0.1.0/modern-ovgu-fma-polylux.typ
  packages/preview/modern-ovgu-fma-polylux/0.1.0/template/example-image.jpg
  packages/preview/modern-ovgu-fma-polylux/0.1.0/template/example.bib
  packages/preview/modern-ovgu-fma-polylux/0.1.0/template/main.typ
  packages/preview/modern-ovgu-fma-polylux/0.1.0/thumbnail.png
  packages/preview/modern-ovgu-fma-polylux/0.1.0/typst.toml
Labels: new

#1922 theoretic:0.2.0
  packages/preview/theoretic/0.2.0/README.md
  packages/preview/theoretic/0.2.0/UNLICENSE
  packages/preview/theoretic/0.2.0/lib.typ
  packages/preview/theoretic/0.2.0/typst.toml
Labels: update

#1919 js:0.1.2
  packages/preview/js/0.1.2/LICENSE
  packages/preview/js/0.1.2/README.md
  packages/preview/js/0.1.2/js.typ
  packages/preview/js/0.1.2/template/example.typ
  packages/preview/js/0.1.2/thumbnail.png
  packages/preview/js/0.1.2/typst.toml
Labels: update

#1923 tuhi-labscript-vuw:0.2.0
  packages/preview/tuhi-labscript-vuw/0.2.0/LICENSE
  packages/preview/tuhi-labscript-vuw/0.2.0/README.md
  packages/preview/tuhi-labscript-vuw/0.2.0/template/figures/tea.jpg
  packages/preview/tuhi-labscript-vuw/0.2.0/template/main.typ
  packages/preview/tuhi-labscript-vuw/0.2.0/thumbnail.png
  packages/preview/tuhi-labscript-vuw/0.2.0/tuhi-labscript-vuw.typ
  packages/preview/tuhi-labscript-vuw/0.2.0/typst.toml
Labels: update

#1926 lemmify:0.1.8
  packages/preview/lemmify/0.1.8/LICENSE
  packages/preview/lemmify/0.1.8/README.md
  packages/preview/lemmify/0.1.8/src/lib.typ
  packages/preview/lemmify/0.1.8/src/styles.typ
  packages/preview/lemmify/0.1.8/src/translations.typ
  packages/preview/lemmify/0.1.8/src/util.typ
  packages/preview/lemmify/0.1.8/typst.toml
Labels: update

#1925 shiroa:0.2.0
  packages/preview/shiroa/0.2.0/LICENSE
  packages/preview/shiroa/0.2.0/README.md
  packages/preview/shiroa/0.2.0/lib.typ
  packages/preview/shiroa/0.2.0/media.typ
  packages/preview/shiroa/0.2.0/meta-and-state.typ
  packages/preview/shiroa/0.2.0/summary-internal.typ
  packages/preview/shiroa/0.2.0/summary.typ
  packages/preview/shiroa/0.2.0/supports-link.typ
  packages/preview/shiroa/0.2.0/supports-text.typ
  packages/preview/shiroa/0.2.0/sys.typ
  packages/preview/shiroa/0.2.0/template-link.typ
  packages/preview/shiroa/0.2.0/template-theme.typ
  packages/preview/shiroa/0.2.0/templates.typ
  packages/preview/shiroa/0.2.0/typst.toml
  packages/preview/shiroa/0.2.0/utils.typ
  packages/preview/shiroa/0.2.0/xcommand.typ
Labels: update

#1918 harvard-gsas-thesis-oat:0.1.2
  packages/preview/harvard-gsas-thesis-oat/0.1.2/LICENSE
  packages/preview/harvard-gsas-thesis-oat/0.1.2/README.md
  packages/preview/harvard-gsas-thesis-oat/0.1.2/img/thumbnail.png
  packages/preview/harvard-gsas-thesis-oat/0.1.2/lib.typ
  packages/preview/harvard-gsas-thesis-oat/0.1.2/templates/main.typ
  packages/preview/harvard-gsas-thesis-oat/0.1.2/typst.toml
Labels: update

#1847 clean-math-thesis:0.3.0
  packages/preview/clean-math-thesis/0.3.0/.gitignore
  packages/preview/clean-math-thesis/0.3.0/LICENSE
  packages/preview/clean-math-thesis/0.3.0/README.md
  packages/preview/clean-math-thesis/0.3.0/lib.typ
  packages/preview/clean-math-thesis/0.3.0/template/References.bib
  packages/preview/clean-math-thesis/0.3.0/template/chapter/abstract.typ
  packages/preview/clean-math-thesis/0.3.0/template/chapter/appendix.typ
  packages/preview/clean-math-thesis/0.3.0/template/chapter/conclusions_outlook.typ
  packages/preview/clean-math-thesis/0.3.0/template/chapter/declaration.typ
  packages/preview/clean-math-thesis/0.3.0/template/chapter/dummy_chapter.typ
  packages/preview/clean-math-thesis/0.3.0/template/chapter/introduction.typ
  packages/preview/clean-math-thesis/0.3.0/template/customization/colors.typ
  packages/preview/clean-math-thesis/0.3.0/template/customization/great-theorems-customized.typ
  packages/preview/clean-math-thesis/0.3.0/template/images/logo_placeholder.svg
  packages/preview/clean-math-thesis/0.3.0/template/main.typ
  packages/preview/clean-math-thesis/0.3.0/thumbnail.png
  packages/preview/clean-math-thesis/0.3.0/typst.toml
Labels: update

#1930 physica:0.9.5
  packages/preview/physica/0.9.5/LICENSE.txt
  packages/preview/physica/0.9.5/README.md
  packages/preview/physica/0.9.5/physica.typ
  packages/preview/physica/0.9.5/typst.toml
Labels: update

#1932 brilliant-cv:2.0.5
  packages/preview/brilliant-cv/2.0.5/LICENSE
  packages/preview/brilliant-cv/2.0.5/README.md
  packages/preview/brilliant-cv/2.0.5/cv.typ
  packages/preview/brilliant-cv/2.0.5/docs/docs-template.typ
  packages/preview/brilliant-cv/2.0.5/docs/docs.typ
  packages/preview/brilliant-cv/2.0.5/letter.typ
  packages/preview/brilliant-cv/2.0.5/lib.typ
  packages/preview/brilliant-cv/2.0.5/metadata.toml.schema.json
  packages/preview/brilliant-cv/2.0.5/template/cv.typ
  packages/preview/brilliant-cv/2.0.5/template/letter.typ
  packages/preview/brilliant-cv/2.0.5/template/metadata.toml
  packages/preview/brilliant-cv/2.0.5/template/modules_en/certificates.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_en/education.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_en/professional.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_en/projects.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_en/publications.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_en/skills.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_fr/certificates.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_fr/education.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_fr/professional.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_fr/projects.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_fr/publications.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_fr/skills.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_it/certificates.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_it/education.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_it/professional.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_it/projects.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_it/publications.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_it/skills.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_zh/certificates.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_zh/education.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_zh/professional.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_zh/projects.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_zh/publications.typ
  packages/preview/brilliant-cv/2.0.5/template/modules_zh/skills.typ
  packages/preview/brilliant-cv/2.0.5/template/src/avatar.png
  packages/preview/brilliant-cv/2.0.5/template/src/logos/abc_company.png
  packages/preview/brilliant-cv/2.0.5/template/src/logos/pqr_corp.png
  packages/preview/brilliant-cv/2.0.5/template/src/logos/ucla.png
  packages/preview/brilliant-cv/2.0.5/template/src/logos/xyz_corp.png
  packages/preview/brilliant-cv/2.0.5/template/src/publications.bib
  packages/preview/brilliant-cv/2.0.5/template/src/signature.png
  packages/preview/brilliant-cv/2.0.5/thumbnail.png
  packages/preview/brilliant-cv/2.0.5/typst.toml
  packages/preview/brilliant-cv/2.0.5/utils/injection.typ
  packages/preview/brilliant-cv/2.0.5/utils/lang.typ
  packages/preview/brilliant-cv/2.0.5/utils/styles.typ
Labels: update

#1936 fletcher:0.5.6
  packages/preview/fletcher/0.5.6/LICENSE
  packages/preview/fletcher/0.5.6/README.md
  packages/preview/fletcher/0.5.6/docs/gallery/1-commutative.svg
  packages/preview/fletcher/0.5.6/docs/gallery/1-commutative.typ
  packages/preview/fletcher/0.5.6/docs/gallery/2-algebra-cube.svg
  packages/preview/fletcher/0.5.6/docs/gallery/2-algebra-cube.typ
  packages/preview/fletcher/0.5.6/docs/gallery/3-ml-architecture.svg
  packages/preview/fletcher/0.5.6/docs/gallery/3-ml-architecture.typ
  packages/preview/fletcher/0.5.6/docs/gallery/4-io-flowchart.svg
  packages/preview/fletcher/0.5.6/docs/gallery/4-io-flowchart.typ
  packages/preview/fletcher/0.5.6/docs/gallery/5-digraph.svg
  packages/preview/fletcher/0.5.6/docs/gallery/5-digraph.typ
  packages/preview/fletcher/0.5.6/docs/gallery/6-node-groups.svg
  packages/preview/fletcher/0.5.6/docs/gallery/6-node-groups.typ
  packages/preview/fletcher/0.5.6/docs/gallery/7-uml-diagram.svg
  packages/preview/fletcher/0.5.6/docs/gallery/7-uml-diagram.typ
  packages/preview/fletcher/0.5.6/docs/manual.pdf
  packages/preview/fletcher/0.5.6/docs/manual.typ
  packages/preview/fletcher/0.5.6/docs/readme-examples/1-first-isomorphism-theorem-dark.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/1-first-isomorphism-theorem-light.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/1-first-isomorphism-theorem.typ
  packages/preview/fletcher/0.5.6/docs/readme-examples/2-flowchart-trap-dark.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/2-flowchart-trap-light.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/2-flowchart-trap.typ
  packages/preview/fletcher/0.5.6/docs/readme-examples/3-state-machine-dark.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/3-state-machine-light.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/3-state-machine.typ
  packages/preview/fletcher/0.5.6/docs/readme-examples/4-feynman-diagram-dark.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/4-feynman-diagram-light.svg
  packages/preview/fletcher/0.5.6/docs/readme-examples/4-feynman-diagram.typ
  packages/preview/fletcher/0.5.6/docs/style.typ
  packages/preview/fletcher/0.5.6/src/coords.typ
  packages/preview/fletcher/0.5.6/src/default-marks.typ
  packages/preview/fletcher/0.5.6/src/deps.typ
  packages/preview/fletcher/0.5.6/src/diagram.typ
  packages/preview/fletcher/0.5.6/src/draw.typ
  packages/preview/fletcher/0.5.6/src/edge.typ
  packages/preview/fletcher/0.5.6/src/exports.typ
  packages/preview/fletcher/0.5.6/src/marks.typ
  packages/preview/fletcher/0.5.6/src/node.typ
  packages/preview/fletcher/0.5.6/src/shapes.typ
  packages/preview/fletcher/0.5.6/src/utils.typ
  packages/preview/fletcher/0.5.6/typst.toml
Labels: update

#1931 markly:0.3.0
  packages/preview/markly/0.3.0/LICENSE
  packages/preview/markly/0.3.0/README.md
  packages/preview/markly/0.3.0/example/main.pdf
  packages/preview/markly/0.3.0/example/main.typ
  packages/preview/markly/0.3.0/example/ping-pong.jpg
  packages/preview/markly/0.3.0/img.svg
  packages/preview/markly/0.3.0/img.typ
  packages/preview/markly/0.3.0/lib.typ
  packages/preview/markly/0.3.0/typst.toml
Labels: update

#1937 flow:0.3.1
  packages/preview/flow/0.3.1/CHANGELOG.md
  packages/preview/flow/0.3.1/LICENSE.md
  packages/preview/flow/0.3.1/README.md
  packages/preview/flow/0.3.1/asset/data.toml
  packages/preview/flow/0.3.1/asset/halcyon.tmTheme
  packages/preview/flow/0.3.1/src/asset.typ
  packages/preview/flow/0.3.1/src/callout.typ
  packages/preview/flow/0.3.1/src/cfg.typ
  packages/preview/flow/0.3.1/src/checkbox.typ
  packages/preview/flow/0.3.1/src/gfx/draw.typ
  packages/preview/flow/0.3.1/src/gfx/maybe-stub.typ
  packages/preview/flow/0.3.1/src/gfx/mod.typ
  packages/preview/flow/0.3.1/src/gfx/render/mod.typ
  packages/preview/flow/0.3.1/src/gfx/render/segment.typ
  packages/preview/flow/0.3.1/src/gfx/stub.typ
  packages/preview/flow/0.3.1/src/gfx/stub/draw.typ
  packages/preview/flow/0.3.1/src/gfx/util.typ
  packages/preview/flow/0.3.1/src/hacks.typ
  packages/preview/flow/0.3.1/src/info.typ
  packages/preview/flow/0.3.1/src/keywords.typ
  packages/preview/flow/0.3.1/src/lib.typ
  packages/preview/flow/0.3.1/src/palette.typ
  packages/preview/flow/0.3.1/src/template.typ
  packages/preview/flow/0.3.1/src/tyck.typ
  packages/preview/flow/0.3.1/src/util/mod.typ
  packages/preview/flow/0.3.1/src/util/preset/ana.typ
  packages/preview/flow/0.3.1/src/util/preset/arrow.typ
  packages/preview/flow/0.3.1/src/util/preset/calculus.typ
  packages/preview/flow/0.3.1/src/util/preset/linalg.typ
  packages/preview/flow/0.3.1/src/util/preset/mod.typ
  packages/preview/flow/0.3.1/src/util/preset/ops.typ
  packages/preview/flow/0.3.1/src/util/preset/quantum.typ
  packages/preview/flow/0.3.1/src/xlink.typ
  packages/preview/flow/0.3.1/template/main.typ
  packages/preview/flow/0.3.1/thumbnail/page-1.png
  packages/preview/flow/0.3.1/typst.toml
  packages/preview/flow/0.3.1/util/common
  packages/preview/flow/0.3.1/util/flow
  packages/preview/flow/0.3.1/util/flow-export
  packages/preview/flow/0.3.1/util/flow-query
Labels: update

#1929 owlbear:0.0.1
  packages/preview/owlbear/0.0.1/.gitignore
  packages/preview/owlbear/0.0.1/CHANGELOG.md
  packages/preview/owlbear/0.0.1/LICENSE
  packages/preview/owlbear/0.0.1/README.md
  packages/preview/owlbear/0.0.1/lib.typ
  packages/preview/owlbear/0.0.1/style/fonts.typ
  packages/preview/owlbear/0.0.1/style/theme.typ
  packages/preview/owlbear/0.0.1/templates/book.typ
  packages/preview/owlbear/0.0.1/typst.toml
Labels: new

#1939 tableau-icons:0.331.0
  packages/preview/tableau-icons/0.331.0/.gitignore
  packages/preview/tableau-icons/0.331.0/LICENSE
  packages/preview/tableau-icons/0.331.0/README.md
  packages/preview/tableau-icons/0.331.0/_tableau-icons-ref.typ
  packages/preview/tableau-icons/0.331.0/docs/banner.png
  packages/preview/tableau-icons/0.331.0/docs/changelog.typ
  packages/preview/tableau-icons/0.331.0/docs/tableau-icons-doc.pdf
  packages/preview/tableau-icons/0.331.0/docs/tableau-icons-doc.typ
  packages/preview/tableau-icons/0.331.0/docs/thumbnail_list.typ
  packages/preview/tableau-icons/0.331.0/lib.typ
  packages/preview/tableau-icons/0.331.0/tableau-icons.typ
  packages/preview/tableau-icons/0.331.0/typst.toml
Labels: update

#1941 modern-hsh-thesis:1.0.2
  packages/preview/modern-hsh-thesis/1.0.2/.gitignore
  packages/preview/modern-hsh-thesis/1.0.2/CHANGELOG.md
  packages/preview/modern-hsh-thesis/1.0.2/CONTRIBUTING.md
  packages/preview/modern-hsh-thesis/1.0.2/LICENSE
  packages/preview/modern-hsh-thesis/1.0.2/README.md
  packages/preview/modern-hsh-thesis/1.0.2/docs/manual.pdf
  packages/preview/modern-hsh-thesis/1.0.2/src/Logo.svg
  packages/preview/modern-hsh-thesis/1.0.2/src/Wortmarke.svg
  packages/preview/modern-hsh-thesis/1.0.2/src/lib.typ
  packages/preview/modern-hsh-thesis/1.0.2/template/Code/code.typ
  packages/preview/modern-hsh-thesis/1.0.2/template/abbreviations.typ
  packages/preview/modern-hsh-thesis/1.0.2/template/chapters/1-einleitung.typ
  packages/preview/modern-hsh-thesis/1.0.2/template/customFunctions.typ
  packages/preview/modern-hsh-thesis/1.0.2/template/main.typ
  packages/preview/modern-hsh-thesis/1.0.2/template/sources.bib
  packages/preview/modern-hsh-thesis/1.0.2/template/sources.yaml
  packages/preview/modern-hsh-thesis/1.0.2/thumbnail.png
  packages/preview/modern-hsh-thesis/1.0.2/typst.toml
Labels: update

#1942 linkst:0.1.0
  packages/preview/linkst/0.1.0/LICENSE
  packages/preview/linkst/0.1.0/README.md
  packages/preview/linkst/0.1.0/gallery/coupon.png
  packages/preview/linkst/0.1.0/gallery/trefoil-debug.png
  packages/preview/linkst/0.1.0/gallery/trefoil.png
  packages/preview/linkst/0.1.0/src/grids.typ
  packages/preview/linkst/0.1.0/src/knots.typ
  packages/preview/linkst/0.1.0/src/lib.typ
  packages/preview/linkst/0.1.0/tests/test.typ
  packages/preview/linkst/0.1.0/typst.toml
Labels: new

#1940 min-manual:0.1.0
  packages/preview/min-manual/0.1.0/LICENSE
  packages/preview/min-manual/0.1.0/README.md
  packages/preview/min-manual/0.1.0/src/lib.typ
  packages/preview/min-manual/0.1.0/template/assets/logo.png
  packages/preview/min-manual/0.1.0/template/assets/module.typ
  packages/preview/min-manual/0.1.0/template/doc-comments.typ
  packages/preview/min-manual/0.1.0/template/manual.typ
  packages/preview/min-manual/0.1.0/thumbnail.png
  packages/preview/min-manual/0.1.0/typst.toml
Labels: new

#1943 curvly:0.1.0
  packages/preview/curvly/0.1.0/LICENSE
  packages/preview/curvly/0.1.0/README.md
  packages/preview/curvly/0.1.0/examples/air_force.svg
  packages/preview/curvly/0.1.0/examples/air_force.typ
  packages/preview/curvly/0.1.0/examples/award.svg
  packages/preview/curvly/0.1.0/examples/award.typ
  packages/preview/curvly/0.1.0/examples/compile
  packages/preview/curvly/0.1.0/examples/fitness.svg
  packages/preview/curvly/0.1.0/examples/fitness.typ
  packages/preview/curvly/0.1.0/examples/frying_pan_paddle.png
  packages/preview/curvly/0.1.0/examples/kitchen.svg
  packages/preview/curvly/0.1.0/examples/kitchen.typ
  packages/preview/curvly/0.1.0/lib.typ
  packages/preview/curvly/0.1.0/typst.toml
Labels: new

#1945 arborly:0.1.1
  packages/preview/arborly/0.1.1/LICENSE
  packages/preview/arborly/0.1.1/README.md
  packages/preview/arborly/0.1.1/docs/manual.pdf
  packages/preview/arborly/0.1.1/docs/manual.typ
  packages/preview/arborly/0.1.1/src/lib.typ
  packages/preview/arborly/0.1.1/typst.toml
Labels: update

#1947 uo-tsinghua-thesis:0.2.0
  packages/preview/uo-tsinghua-thesis/0.2.0/LICENSE.txt
  packages/preview/uo-tsinghua-thesis/0.2.0/README.md
  packages/preview/uo-tsinghua-thesis/0.2.0/lib.typ
  packages/preview/uo-tsinghua-thesis/0.2.0/pkuthss-info/pkuthss-changelog.typ
  packages/preview/uo-tsinghua-thesis/0.2.0/pkuthss-info/pkuthss-contributors.typ
  packages/preview/uo-tsinghua-thesis/0.2.0/pkuthss-info/pkuthss-typst-LICENSE.txt
  packages/preview/uo-tsinghua-thesis/0.2.0/template/images/tupianhint.png
  packages/preview/uo-tsinghua-thesis/0.2.0/template/其他内容.typ
  packages/preview/uo-tsinghua-thesis/0.2.0/template/文献库.bib
  packages/preview/uo-tsinghua-thesis/0.2.0/template/正文.typ
  packages/preview/uo-tsinghua-thesis/0.2.0/template/设置.typ
  packages/preview/uo-tsinghua-thesis/0.2.0/thumbnail.png
  packages/preview/uo-tsinghua-thesis/0.2.0/typst.toml
Labels: new

#1938 frame-it:1.1.0
  packages/preview/frame-it/1.1.0/.gitignore
  packages/preview/frame-it/1.1.0/CHANGELOG.md
  packages/preview/frame-it/1.1.0/LICENSE
  packages/preview/frame-it/1.1.0/README.md
  packages/preview/frame-it/1.1.0/README.typ
  packages/preview/frame-it/1.1.0/justfile
  packages/preview/frame-it/1.1.0/src/bundled-layout.typ
  packages/preview/frame-it/1.1.0/src/layout.typ
  packages/preview/frame-it/1.1.0/src/lib.typ
  packages/preview/frame-it/1.1.0/src/parse.typ
  packages/preview/frame-it/1.1.0/src/styles/boxy.typ
  packages/preview/frame-it/1.1.0/src/styles/hint.typ
  packages/preview/frame-it/1.1.0/src/styles/thmbox.typ
  packages/preview/frame-it/1.1.0/src/styling.typ
  packages/preview/frame-it/1.1.0/typst.toml
Labels: update

#1948 typslides:1.2.5
  packages/preview/typslides/1.2.5/LICENSE
  packages/preview/typslides/1.2.5/README.md
  packages/preview/typslides/1.2.5/img/logo.png
  packages/preview/typslides/1.2.5/img/slide-1.svg
  packages/preview/typslides/1.2.5/img/slide-2.svg
  packages/preview/typslides/1.2.5/img/slide-3.svg
  packages/preview/typslides/1.2.5/img/slide-4.svg
  packages/preview/typslides/1.2.5/img/slide-5.svg
  packages/preview/typslides/1.2.5/img/slide-6.svg
  packages/preview/typslides/1.2.5/img/slide-7.svg
  packages/preview/typslides/1.2.5/img/slide-8.svg
  packages/preview/typslides/1.2.5/img/slide-9.svg
  packages/preview/typslides/1.2.5/lib.typ
  packages/preview/typslides/1.2.5/template/bibliography.bib
  packages/preview/typslides/1.2.5/template/main.typ
  packages/preview/typslides/1.2.5/thumbnail.png
  packages/preview/typslides/1.2.5/typslides.typ
  packages/preview/typslides/1.2.5/typst.toml
  packages/preview/typslides/1.2.5/utils.typ
Labels: update

#1787 kdl-unofficial-template:0.1.0
  packages/preview/kdl-unofficial-template/0.1.0/LICENSE
  packages/preview/kdl-unofficial-template/0.1.0/README.md
  packages/preview/kdl-unofficial-template/0.1.0/lib/assets/img/bg_left.jpg
  packages/preview/kdl-unofficial-template/0.1.0/lib/assets/img/bg_right.jpg
  packages/preview/kdl-unofficial-template/0.1.0/lib/assets/img/bg_section.jpg
  packages/preview/kdl-unofficial-template/0.1.0/lib/assets/img/bg_title.jpg
  packages/preview/kdl-unofficial-template/0.1.0/lib/lib.typ
  packages/preview/kdl-unofficial-template/0.1.0/lib/src/braid.typ
  packages/preview/kdl-unofficial-template/0.1.0/lib/src/pageref.typ
  packages/preview/kdl-unofficial-template/0.1.0/lib/src/skills.typ
  packages/preview/kdl-unofficial-template/0.1.0/lib/src/style.typ
  packages/preview/kdl-unofficial-template/0.1.0/lib/src/trackers.typ
  packages/preview/kdl-unofficial-template/0.1.0/template/main/.envrc
  packages/preview/kdl-unofficial-template/0.1.0/template/main/assets/bibliography.bib
  packages/preview/kdl-unofficial-template/0.1.0/template/main/chapters/01-intro.typ
  packages/preview/kdl-unofficial-template/0.1.0/template/main/chapters/02-pre-gen.typ
  packages/preview/kdl-unofficial-template/0.1.0/template/main/main.typ
  packages/preview/kdl-unofficial-template/0.1.0/template/thumbnail.png
  packages/preview/kdl-unofficial-template/0.1.0/typst.toml
Labels: new

#1950 wicked:0.1.1
  packages/preview/wicked/0.1.1/LICENSE
  packages/preview/wicked/0.1.1/README.md
  packages/preview/wicked/0.1.1/docs.pdf
  packages/preview/wicked/0.1.1/docs.typ
  packages/preview/wicked/0.1.1/images/example.png
  packages/preview/wicked/0.1.1/src/lib.typ
  packages/preview/wicked/0.1.1/src/wick.typ
  packages/preview/wicked/0.1.1/typst.toml
Labels: update

#1952 haw-hamburg-bachelor-thesis:0.5.1, haw-hamburg-master-thesis:0.5.1, haw-hamburg-report:0.5.1 and haw-hamburg:0.5.1
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/LICENSE
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/README.md
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/lib.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/abbreviations.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/bibliography.bib
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/chapters/02_background.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/dependencies.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/glossary.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/ieeetran.csl
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/src/main.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/thumbnail.png
  packages/preview/haw-hamburg-bachelor-thesis/0.5.1/typst.toml
  packages/preview/haw-hamburg-master-thesis/0.5.1/LICENSE
  packages/preview/haw-hamburg-master-thesis/0.5.1/README.md
  packages/preview/haw-hamburg-master-thesis/0.5.1/lib.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/abbreviations.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/bibliography.bib
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/chapters/02_background.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/dependencies.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/glossary.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/ieeetran.csl
  packages/preview/haw-hamburg-master-thesis/0.5.1/src/main.typ
  packages/preview/haw-hamburg-master-thesis/0.5.1/thumbnail.png
  packages/preview/haw-hamburg-master-thesis/0.5.1/typst.toml
  packages/preview/haw-hamburg-report/0.5.1/LICENSE
  packages/preview/haw-hamburg-report/0.5.1/README.md
  packages/preview/haw-hamburg-report/0.5.1/lib.typ
  packages/preview/haw-hamburg-report/0.5.1/src/abbreviations.typ
  packages/preview/haw-hamburg-report/0.5.1/src/bibliography.bib
  packages/preview/haw-hamburg-report/0.5.1/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-report/0.5.1/src/chapters/02_background.typ
  packages/preview/haw-hamburg-report/0.5.1/src/dependencies.typ
  packages/preview/haw-hamburg-report/0.5.1/src/glossary.typ
  packages/preview/haw-hamburg-report/0.5.1/src/ieeetran.csl
  packages/preview/haw-hamburg-report/0.5.1/src/main.typ
  packages/preview/haw-hamburg-report/0.5.1/thumbnail.png
  packages/preview/haw-hamburg-report/0.5.1/typst.toml
  packages/preview/haw-hamburg/0.5.1/LICENSE
  packages/preview/haw-hamburg/0.5.1/README.md
  packages/preview/haw-hamburg/0.5.1/assets/ieeetran.csl
  packages/preview/haw-hamburg/0.5.1/assets/logo.svg
  packages/preview/haw-hamburg/0.5.1/lib.typ
  packages/preview/haw-hamburg/0.5.1/pages/abstract.typ
  packages/preview/haw-hamburg/0.5.1/pages/cover.typ
  packages/preview/haw-hamburg/0.5.1/pages/declaration_of_independent_processing.typ
  packages/preview/haw-hamburg/0.5.1/pages/list_of_figures.typ
  packages/preview/haw-hamburg/0.5.1/pages/list_of_tables.typ
  packages/preview/haw-hamburg/0.5.1/pages/listings.typ
  packages/preview/haw-hamburg/0.5.1/pages/outline.typ
  packages/preview/haw-hamburg/0.5.1/template.typ
  packages/preview/haw-hamburg/0.5.1/translations.typ
  packages/preview/haw-hamburg/0.5.1/typst.toml
Labels: update

#1955 tiaoma:0.3.0
  packages/preview/tiaoma/0.3.0/3rdparty_license.html
  packages/preview/tiaoma/0.3.0/LICENSE
  packages/preview/tiaoma/0.3.0/README.md
  packages/preview/tiaoma/0.3.0/example.svg
  packages/preview/tiaoma/0.3.0/example.typ
  packages/preview/tiaoma/0.3.0/lib.typ
  packages/preview/tiaoma/0.3.0/license.html
  packages/preview/tiaoma/0.3.0/manual.pdf
  packages/preview/tiaoma/0.3.0/manual.typ
  packages/preview/tiaoma/0.3.0/tidy_style.typ
  packages/preview/tiaoma/0.3.0/typst.toml
  packages/preview/tiaoma/0.3.0/zint_typst_plugin.wasm
Labels: update

#1958 shuxuejuan:0.1.1
  packages/preview/shuxuejuan/0.1.1/LICENSE
  packages/preview/shuxuejuan/0.1.1/README.md
  packages/preview/shuxuejuan/0.1.1/examples/example.typ
  packages/preview/shuxuejuan/0.1.1/lib.typ
  packages/preview/shuxuejuan/0.1.1/src/answer.typ
  packages/preview/shuxuejuan/0.1.1/src/env.typ
  packages/preview/shuxuejuan/0.1.1/src/export.typ
  packages/preview/shuxuejuan/0.1.1/src/question-group.typ
  packages/preview/shuxuejuan/0.1.1/src/question.typ
  packages/preview/shuxuejuan/0.1.1/src/reference.typ
  packages/preview/shuxuejuan/0.1.1/src/utils.typ
  packages/preview/shuxuejuan/0.1.1/typst.toml
Labels: update

#1959 suboutline:0.3.0
  packages/preview/suboutline/0.3.0/LICENSE
  packages/preview/suboutline/0.3.0/README.md
  packages/preview/suboutline/0.3.0/lib.typ
  packages/preview/suboutline/0.3.0/typst.toml
Labels: update

#1961 versatile-apa:7.1.1
  packages/preview/versatile-apa/7.1.1/README.md
  packages/preview/versatile-apa/7.1.1/assets/img/ORCID_iD.svg.png
  packages/preview/versatile-apa/7.1.1/lib.typ
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-bar-graph.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-consort-flowchart.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-illustration-experimental-stimuli.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-map.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-mixed-methods-research-figure.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-path-model.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample-qualitative-research-figure.png
  packages/preview/versatile-apa/7.1.1/template/assets/images/sample.line-graph.png
  packages/preview/versatile-apa/7.1.1/template/assets/src/main.py
  packages/preview/versatile-apa/7.1.1/template/bibliography/ref.bib
  packages/preview/versatile-apa/7.1.1/template/bibliography/ref.yml
  packages/preview/versatile-apa/7.1.1/template/main.typ
  packages/preview/versatile-apa/7.1.1/template/sections/appendix.typ
  packages/preview/versatile-apa/7.1.1/template/sections/computer-code.typ
  packages/preview/versatile-apa/7.1.1/template/sections/figures.typ
  packages/preview/versatile-apa/7.1.1/template/sections/footnote.typ
  packages/preview/versatile-apa/7.1.1/template/sections/introduction.typ
  packages/preview/versatile-apa/7.1.1/template/sections/lists.typ
  packages/preview/versatile-apa/7.1.1/template/sections/math.typ
  packages/preview/versatile-apa/7.1.1/template/sections/quotes.typ
  packages/preview/versatile-apa/7.1.1/template/sections/tables.typ
  packages/preview/versatile-apa/7.1.1/thumbnail.png
  packages/preview/versatile-apa/7.1.1/typst.toml
  packages/preview/versatile-apa/7.1.1/utils/apa-figure.typ
  packages/preview/versatile-apa/7.1.1/utils/appendix.typ
  packages/preview/versatile-apa/7.1.1/utils/authoring.typ
  packages/preview/versatile-apa/7.1.1/utils/languages.typ
  packages/preview/versatile-apa/7.1.1/utils/orcid.typ
  packages/preview/versatile-apa/7.1.1/utils/to-string.typ
Labels: update

#1962 vonsim:0.2.0
  packages/preview/vonsim/0.2.0/LICENSE
  packages/preview/vonsim/0.2.0/README.md
  packages/preview/vonsim/0.2.0/lib.typ
  packages/preview/vonsim/0.2.0/mips.sublime-syntax
  packages/preview/vonsim/0.2.0/typst.toml
  packages/preview/vonsim/0.2.0/vonsim.sublime-syntax
  packages/preview/vonsim/0.2.0/vonsim.tmTheme
Labels: update

#1963 alexandria:0.1.2
  packages/preview/alexandria/0.1.2/.gitignore
  packages/preview/alexandria/0.1.2/CHANGELOG.md
  packages/preview/alexandria/0.1.2/LICENSE
  packages/preview/alexandria/0.1.2/README.md
  packages/preview/alexandria/0.1.2/docs/manual.pdf
  packages/preview/alexandria/0.1.2/gallery/example.pdf
  packages/preview/alexandria/0.1.2/src/alexandria.wasm
  packages/preview/alexandria/0.1.2/src/hayagriva.typ
  packages/preview/alexandria/0.1.2/src/internal.typ
  packages/preview/alexandria/0.1.2/src/lib.typ
  packages/preview/alexandria/0.1.2/src/state.typ
  packages/preview/alexandria/0.1.2/thumbnail-dark.svg
  packages/preview/alexandria/0.1.2/thumbnail-light.svg
  packages/preview/alexandria/0.1.2/typst.toml
Labels: update

#1967 relescope:0.0.2
  packages/preview/relescope/0.0.2/LICENSE
  packages/preview/relescope/0.0.2/README.md
  packages/preview/relescope/0.0.2/bin/plugin.wasm
  packages/preview/relescope/0.0.2/examples/example-pick.svg
  packages/preview/relescope/0.0.2/examples/example-pick.typ
  packages/preview/relescope/0.0.2/examples/example-scope.svg
  packages/preview/relescope/0.0.2/examples/example-scope.typ
  packages/preview/relescope/0.0.2/examples/example-template.typ
  packages/preview/relescope/0.0.2/src/lib.typ
  packages/preview/relescope/0.0.2/src/wrap.typ
  packages/preview/relescope/0.0.2/typst.toml
Labels: update

#1968 cmarker:0.1.3
  packages/preview/cmarker/0.1.3/LICENSE
  packages/preview/cmarker/0.1.3/README.md
  packages/preview/cmarker/0.1.3/examples/hexagons.png
  packages/preview/cmarker/0.1.3/examples/simple.png
  packages/preview/cmarker/0.1.3/lib.typ
  packages/preview/cmarker/0.1.3/plugin.wasm
  packages/preview/cmarker/0.1.3/typst.toml
Labels: update

#1969 cetz:0.3.4
  packages/preview/cetz/0.3.4/LICENSE
  packages/preview/cetz/0.3.4/README.md
  packages/preview/cetz/0.3.4/gallery/karls-picture.png
  packages/preview/cetz/0.3.4/gallery/karls-picture.typ
  packages/preview/cetz/0.3.4/gallery/paciolis.png
  packages/preview/cetz/0.3.4/gallery/paciolis.typ
  packages/preview/cetz/0.3.4/gallery/periodic-table.png
  packages/preview/cetz/0.3.4/gallery/periodic-table.typ
  packages/preview/cetz/0.3.4/gallery/plate-capacitor.png
  packages/preview/cetz/0.3.4/gallery/plate-capacitor.typ
  packages/preview/cetz/0.3.4/gallery/tree.png
  packages/preview/cetz/0.3.4/gallery/tree.typ
  packages/preview/cetz/0.3.4/gallery/waves.png
  packages/preview/cetz/0.3.4/gallery/waves.typ
  packages/preview/cetz/0.3.4/src/aabb.typ
  packages/preview/cetz/0.3.4/src/anchor.typ
  packages/preview/cetz/0.3.4/src/bezier.typ
  packages/preview/cetz/0.3.4/src/canvas.typ
  packages/preview/cetz/0.3.4/src/complex.typ
  packages/preview/cetz/0.3.4/src/coordinate.typ
  packages/preview/cetz/0.3.4/src/deps.typ
  packages/preview/cetz/0.3.4/src/draw.typ
  packages/preview/cetz/0.3.4/src/draw/grouping.typ
  packages/preview/cetz/0.3.4/src/draw/projection.typ
  packages/preview/cetz/0.3.4/src/draw/shapes.typ
  packages/preview/cetz/0.3.4/src/draw/styling.typ
  packages/preview/cetz/0.3.4/src/draw/transformations.typ
  packages/preview/cetz/0.3.4/src/draw/util.typ
  packages/preview/cetz/0.3.4/src/drawable.typ
  packages/preview/cetz/0.3.4/src/hobby.typ
  packages/preview/cetz/0.3.4/src/intersection.typ
  packages/preview/cetz/0.3.4/src/lib.typ
  packages/preview/cetz/0.3.4/src/lib/angle.typ
  packages/preview/cetz/0.3.4/src/lib/decorations.typ
  packages/preview/cetz/0.3.4/src/lib/decorations/brace.typ
  packages/preview/cetz/0.3.4/src/lib/decorations/path.typ
  packages/preview/cetz/0.3.4/src/lib/palette.typ
  packages/preview/cetz/0.3.4/src/lib/pin.typ
  packages/preview/cetz/0.3.4/src/lib/tree.typ
  packages/preview/cetz/0.3.4/src/mark-shapes.typ
  packages/preview/cetz/0.3.4/src/mark.typ
  packages/preview/cetz/0.3.4/src/matrix.typ
  packages/preview/cetz/0.3.4/src/path-util.typ
  packages/preview/cetz/0.3.4/src/polygon.typ
  packages/preview/cetz/0.3.4/src/process.typ
  packages/preview/cetz/0.3.4/src/sorting.typ
  packages/preview/cetz/0.3.4/src/styles.typ
  packages/preview/cetz/0.3.4/src/util.typ
  packages/preview/cetz/0.3.4/src/vector.typ
  packages/preview/cetz/0.3.4/src/version.typ
  packages/preview/cetz/0.3.4/typst.toml
Labels: update

#1970 fh-joanneum-iit-thesis:2.1.2
  packages/preview/fh-joanneum-iit-thesis/2.1.2/LICENSE
  packages/preview/fh-joanneum-iit-thesis/2.1.2/README.md
  packages/preview/fh-joanneum-iit-thesis/2.1.2/lib.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/biblio.bib
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/biblio.csl
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/1-intro.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/2-related.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/3-background.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/4-concept.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/5-implementation.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/6-evaluation.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/7-conclusion.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/acknowledgements.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/appendix.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/global.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/glossary-definitions.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/chapters/glossary.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/code-snippets/msg.py
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/data/recordings.csv
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/figures/chart-1.svg
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/figures/chart-2.svg
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/figures/logo.svg
  packages/preview/fh-joanneum-iit-thesis/2.1.2/template/thesis.typ
  packages/preview/fh-joanneum-iit-thesis/2.1.2/thumbnail.png
  packages/preview/fh-joanneum-iit-thesis/2.1.2/typst.toml
Labels: update

#1972 tiptoe:0.3.0
  packages/preview/tiptoe/0.3.0/LICENSE.txt
  packages/preview/tiptoe/0.3.0/README.md
  packages/preview/tiptoe/0.3.0/src/arc-impl.typ
  packages/preview/tiptoe/0.3.0/src/arc.typ
  packages/preview/tiptoe/0.3.0/src/assert.typ
  packages/preview/tiptoe/0.3.0/src/curve.typ
  packages/preview/tiptoe/0.3.0/src/line.typ
  packages/preview/tiptoe/0.3.0/src/marks.typ
  packages/preview/tiptoe/0.3.0/src/path-to-curve.typ
  packages/preview/tiptoe/0.3.0/src/path.typ
  packages/preview/tiptoe/0.3.0/src/tiptoe.typ
  packages/preview/tiptoe/0.3.0/src/utility.typ
  packages/preview/tiptoe/0.3.0/typst.toml
Labels: update

#1973 tuhi-course-poster-vuw:0.2.0
  packages/preview/tuhi-course-poster-vuw/0.2.0/LICENSE
  packages/preview/tuhi-course-poster-vuw/0.2.0/README.md
  packages/preview/tuhi-course-poster-vuw/0.2.0/template/images/esca101.jpg
  packages/preview/tuhi-course-poster-vuw/0.2.0/template/logo.svg
  packages/preview/tuhi-course-poster-vuw/0.2.0/template/main.typ
  packages/preview/tuhi-course-poster-vuw/0.2.0/thumbnail.png
  packages/preview/tuhi-course-poster-vuw/0.2.0/tuhi-course-poster-vuw.typ
  packages/preview/tuhi-course-poster-vuw/0.2.0/typst.toml
Labels: update

#1974 tuhi-booklet-vuw:0.2.0
  packages/preview/tuhi-booklet-vuw/0.2.0/LICENSE
  packages/preview/tuhi-booklet-vuw/0.2.0/README.md
  packages/preview/tuhi-booklet-vuw/0.2.0/template/figures/illustration.jpg
  packages/preview/tuhi-booklet-vuw/0.2.0/template/info.yaml
  packages/preview/tuhi-booklet-vuw/0.2.0/template/main.typ
  packages/preview/tuhi-booklet-vuw/0.2.0/template/teas.json
  packages/preview/tuhi-booklet-vuw/0.2.0/thumbnail.png
  packages/preview/tuhi-booklet-vuw/0.2.0/tuhi-booklet-vuw.typ
  packages/preview/tuhi-booklet-vuw/0.2.0/typst.toml
Labels: update

#1957 matset:0.1.0
  packages/preview/matset/0.1.0/LICENSE
  packages/preview/matset/0.1.0/README.md
  packages/preview/matset/0.1.0/api.typ
  packages/preview/matset/0.1.0/matset.wasm
  packages/preview/matset/0.1.0/typesetting.typ
  packages/preview/matset/0.1.0/typst.toml
Labels: new

#1799 quizst:0.3.2
  packages/preview/quizst/0.3.2/LICENSE
  packages/preview/quizst/0.3.2/README.md
  packages/preview/quizst/0.3.2/lib.typ
  packages/preview/quizst/0.3.2/template/input/example.json
  packages/preview/quizst/0.3.2/template/main.typ
  packages/preview/quizst/0.3.2/template/thumbnail.png
  packages/preview/quizst/0.3.2/typst.toml
Labels: new

#1977 scripst:1.1.1
  packages/preview/scripst/1.1.1/LICENSE
  packages/preview/scripst/1.1.1/README.md
  packages/preview/scripst/1.1.1/README_zh-CN.md
  packages/preview/scripst/1.1.1/docs/article.typ
  packages/preview/scripst/1.1.1/docs/book.typ
  packages/preview/scripst/1.1.1/docs/builds/article.pdf
  packages/preview/scripst/1.1.1/docs/builds/book.pdf
  packages/preview/scripst/1.1.1/docs/builds/report.pdf
  packages/preview/scripst/1.1.1/docs/chap1.typ
  packages/preview/scripst/1.1.1/docs/chap2.typ
  packages/preview/scripst/1.1.1/docs/chap3.typ
  packages/preview/scripst/1.1.1/docs/chap4.typ
  packages/preview/scripst/1.1.1/docs/locale/article-en.typ
  packages/preview/scripst/1.1.1/docs/locale/builds/article-en.pdf
  packages/preview/scripst/1.1.1/docs/locale/pic/pic.jpg
  packages/preview/scripst/1.1.1/docs/pic/pic.jpg
  packages/preview/scripst/1.1.1/docs/report.typ
  packages/preview/scripst/1.1.1/makefile
  packages/preview/scripst/1.1.1/previews/article-1.png
  packages/preview/scripst/1.1.1/previews/article-12.png
  packages/preview/scripst/1.1.1/previews/article-2.png
  packages/preview/scripst/1.1.1/previews/article-9.png
  packages/preview/scripst/1.1.1/previews/book-1.png
  packages/preview/scripst/1.1.1/previews/book-2.png
  packages/preview/scripst/1.1.1/previews/countblock.png
  packages/preview/scripst/1.1.1/previews/labelset.jpg
  packages/preview/scripst/1.1.1/previews/report-1.png
  packages/preview/scripst/1.1.1/previews/report-2.png
  packages/preview/scripst/1.1.1/src/components.typ
  packages/preview/scripst/1.1.1/src/configs.typ
  packages/preview/scripst/1.1.1/src/locale.typ
  packages/preview/scripst/1.1.1/src/locale/locale.typ
  packages/preview/scripst/1.1.1/src/locale/locale.yml
  packages/preview/scripst/1.1.1/src/main.typ
  packages/preview/scripst/1.1.1/src/package.typ
  packages/preview/scripst/1.1.1/src/scripst.typ
  packages/preview/scripst/1.1.1/src/styling.typ
  packages/preview/scripst/1.1.1/src/template.typ
  packages/preview/scripst/1.1.1/template/main.typ
  packages/preview/scripst/1.1.1/thumbnail.png
  packages/preview/scripst/1.1.1/typst.toml
Labels: update

#1956 scholarly-tauthesis:0.10.2
  packages/preview/scholarly-tauthesis/0.10.2/.gitattributes
  packages/preview/scholarly-tauthesis/0.10.2/.gitignore
  packages/preview/scholarly-tauthesis/0.10.2/LICENSE
  packages/preview/scholarly-tauthesis/0.10.2/README.md
  packages/preview/scholarly-tauthesis/0.10.2/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.10.2/template/code/README.md
  packages/preview/scholarly-tauthesis/0.10.2/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.10.2/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/README.md
  packages/preview/scholarly-tauthesis/0.10.2/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/images/README.md
  packages/preview/scholarly-tauthesis/0.10.2/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.10.2/template/main.typ
  packages/preview/scholarly-tauthesis/0.10.2/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.10.2/thumbnail.png
  packages/preview/scholarly-tauthesis/0.10.2/typst.toml
Labels: update

#1979 modern-unimib-thesis:0.1.0
  packages/preview/modern-unimib-thesis/0.1.0/LICENSE.txt
  packages/preview/modern-unimib-thesis/0.1.0/README.md
  packages/preview/modern-unimib-thesis/0.1.0/lib.typ
  packages/preview/modern-unimib-thesis/0.1.0/template/images/logo_unimib.png
  packages/preview/modern-unimib-thesis/0.1.0/template/main.typ
  packages/preview/modern-unimib-thesis/0.1.0/template/refs.bib
  packages/preview/modern-unimib-thesis/0.1.0/thumbnail.png
  packages/preview/modern-unimib-thesis/0.1.0/typst.toml
Labels: new

#1980 chordx:0.6.0
  packages/preview/chordx/0.6.0/CHANGELOG.md
  packages/preview/chordx/0.6.0/LICENSE
  packages/preview/chordx/0.6.0/README.md
  packages/preview/chordx/0.6.0/lib.typ
  packages/preview/chordx/0.6.0/src/chart.typ
  packages/preview/chordx/0.6.0/src/piano.typ
  packages/preview/chordx/0.6.0/src/single.typ
  packages/preview/chordx/0.6.0/src/utils.typ
  packages/preview/chordx/0.6.0/typst.toml
Labels: update

#1982 fancy-units:0.1.1
  packages/preview/fancy-units/0.1.1/LICENSE
  packages/preview/fancy-units/0.1.1/README.md
  packages/preview/fancy-units/0.1.1/docs/examples.svg
  packages/preview/fancy-units/0.1.1/src/content.typ
  packages/preview/fancy-units/0.1.1/src/lib.typ
  packages/preview/fancy-units/0.1.1/src/number.typ
  packages/preview/fancy-units/0.1.1/src/unit.typ
  packages/preview/fancy-units/0.1.1/typst.toml
Labels: update

#1985 blinky:0.1.1
  packages/preview/blinky/0.1.1/LICENSE
  packages/preview/blinky/0.1.1/README.md
  packages/preview/blinky/0.1.1/blinky.wasm
  packages/preview/blinky/0.1.1/lib.typ
  packages/preview/blinky/0.1.1/typst.toml
Labels: update

#1986 marginalia:0.1.3
  packages/preview/marginalia/0.1.3/README.md
  packages/preview/marginalia/0.1.3/UNLICENSE
  packages/preview/marginalia/0.1.3/lib.typ
  packages/preview/marginalia/0.1.3/typst.toml
Labels: update

#1987 chronos:0.2.1
  packages/preview/chronos/0.2.1/LICENSE
  packages/preview/chronos/0.2.1/README.md
  packages/preview/chronos/0.2.1/TODO.md
  packages/preview/chronos/0.2.1/docs/example.typ
  packages/preview/chronos/0.2.1/docs/examples.typ
  packages/preview/chronos/0.2.1/docs/gaps_seps.typ
  packages/preview/chronos/0.2.1/docs/groups.typ
  packages/preview/chronos/0.2.1/docs/notes.typ
  packages/preview/chronos/0.2.1/docs/participants.typ
  packages/preview/chronos/0.2.1/docs/sequences.typ
  packages/preview/chronos/0.2.1/gallery/example1.pdf
  packages/preview/chronos/0.2.1/gallery/example1.typ
  packages/preview/chronos/0.2.1/gallery/example2.pdf
  packages/preview/chronos/0.2.1/gallery/example2.typ
  packages/preview/chronos/0.2.1/gallery/example3.pdf
  packages/preview/chronos/0.2.1/gallery/example3.typ
  packages/preview/chronos/0.2.1/gallery/ferris.png
  packages/preview/chronos/0.2.1/gallery/gitea.png
  packages/preview/chronos/0.2.1/gallery/me.jpg
  packages/preview/chronos/0.2.1/gallery/notes.pdf
  packages/preview/chronos/0.2.1/gallery/notes.typ
  packages/preview/chronos/0.2.1/gallery/readme/boilerplate.pdf
  packages/preview/chronos/0.2.1/gallery/readme/boilerplate.png
  packages/preview/chronos/0.2.1/gallery/readme/boilerplate.typ
  packages/preview/chronos/0.2.1/gallery/readme/lifelines.pdf
  packages/preview/chronos/0.2.1/gallery/readme/lifelines.png
  packages/preview/chronos/0.2.1/gallery/readme/lifelines.typ
  packages/preview/chronos/0.2.1/gallery/readme/simple_sequence.pdf
  packages/preview/chronos/0.2.1/gallery/readme/simple_sequence.png
  packages/preview/chronos/0.2.1/gallery/readme/simple_sequence.typ
  packages/preview/chronos/0.2.1/gallery/typst.png
  packages/preview/chronos/0.2.1/justfile
  packages/preview/chronos/0.2.1/manual.pdf
  packages/preview/chronos/0.2.1/manual.typ
  packages/preview/chronos/0.2.1/src/cetz.typ
  packages/preview/chronos/0.2.1/src/consts.typ
  packages/preview/chronos/0.2.1/src/diagram.typ
  packages/preview/chronos/0.2.1/src/group.typ
  packages/preview/chronos/0.2.1/src/lib.typ
  packages/preview/chronos/0.2.1/src/note.typ
  packages/preview/chronos/0.2.1/src/parser2.typ
  packages/preview/chronos/0.2.1/src/participant.typ
  packages/preview/chronos/0.2.1/src/renderer.typ
  packages/preview/chronos/0.2.1/src/separator.typ
  packages/preview/chronos/0.2.1/src/sequence.typ
  packages/preview/chronos/0.2.1/src/styles.typ
  packages/preview/chronos/0.2.1/src/sync.typ
  packages/preview/chronos/0.2.1/src/syntax.ebnf
  packages/preview/chronos/0.2.1/src/utils.pdf
  packages/preview/chronos/0.2.1/src/utils.typ
  packages/preview/chronos/0.2.1/typst.toml
Labels: update

#1990 parcio-thesis:0.2.0
  packages/preview/parcio-thesis/0.2.0/LICENSE
  packages/preview/parcio-thesis/0.2.0/README.md
  packages/preview/parcio-thesis/0.2.0/src/parcio.typ
  packages/preview/parcio-thesis/0.2.0/src/titlepage.typ
  packages/preview/parcio-thesis/0.2.0/src/translations.toml
  packages/preview/parcio-thesis/0.2.0/src/util.typ
  packages/preview/parcio-thesis/0.2.0/template/appendix.typ
  packages/preview/parcio-thesis/0.2.0/template/bibliography/apalike.csl
  packages/preview/parcio-thesis/0.2.0/template/bibliography/refs.bib
  packages/preview/parcio-thesis/0.2.0/template/chapters/abstract.typ
  packages/preview/parcio-thesis/0.2.0/template/chapters/background/background.typ
  packages/preview/parcio-thesis/0.2.0/template/chapters/conclusion/conc.typ
  packages/preview/parcio-thesis/0.2.0/template/chapters/eval/eval.typ
  packages/preview/parcio-thesis/0.2.0/template/chapters/introduction/intro.typ
  packages/preview/parcio-thesis/0.2.0/template/images/ovgu-fin.svg
  packages/preview/parcio-thesis/0.2.0/template/legal.typ
  packages/preview/parcio-thesis/0.2.0/template/thesis.typ
  packages/preview/parcio-thesis/0.2.0/thumbnails/1.png
  packages/preview/parcio-thesis/0.2.0/thumbnails/2.png
  packages/preview/parcio-thesis/0.2.0/thumbnails/3.png
  packages/preview/parcio-thesis/0.2.0/typst.toml
Labels: update

#1992 fractusist:0.2.0
  packages/preview/fractusist/0.2.0/LICENSE
  packages/preview/fractusist/0.2.0/README.md
  packages/preview/fractusist/0.2.0/examples/dragon-curve-n12.png
  packages/preview/fractusist/0.2.0/examples/dragon-curve-n12.typ
  packages/preview/fractusist/0.2.0/examples/hypotrochoid-a19-b16-h2.png
  packages/preview/fractusist/0.2.0/examples/hypotrochoid-a19-b16-h2.typ
  packages/preview/fractusist/0.2.0/examples/koch-snowflake-n4.png
  packages/preview/fractusist/0.2.0/examples/koch-snowflake-n4.typ
  packages/preview/fractusist/0.2.0/examples/sierpinski-triangle-n6.png
  packages/preview/fractusist/0.2.0/examples/sierpinski-triangle-n6.typ
  packages/preview/fractusist/0.2.0/src/dragon.typ
  packages/preview/fractusist/0.2.0/src/hilbert.typ
  packages/preview/fractusist/0.2.0/src/koch.typ
  packages/preview/fractusist/0.2.0/src/lib.typ
  packages/preview/fractusist/0.2.0/src/lissajous.typ
  packages/preview/fractusist/0.2.0/src/sierpinski.typ
  packages/preview/fractusist/0.2.0/src/spirograph.typ
  packages/preview/fractusist/0.2.0/typst.toml
Labels: update

#1994 tuhi-programme-vuw:0.1.0
  packages/preview/tuhi-programme-vuw/0.1.0/README.md
  packages/preview/tuhi-programme-vuw/0.1.0/template/main.typ
  packages/preview/tuhi-programme-vuw/0.1.0/template/teas.json
  packages/preview/tuhi-programme-vuw/0.1.0/template/teas.yml
  packages/preview/tuhi-programme-vuw/0.1.0/thumbnail.png
  packages/preview/tuhi-programme-vuw/0.1.0/tuhi-programme-vuw.typ
  packages/preview/tuhi-programme-vuw/0.1.0/typst.toml
Labels: new

#1995 alexandria:0.1.3
  packages/preview/alexandria/0.1.3/.gitignore
  packages/preview/alexandria/0.1.3/CHANGELOG.md
  packages/preview/alexandria/0.1.3/LICENSE
  packages/preview/alexandria/0.1.3/README.md
  packages/preview/alexandria/0.1.3/docs/manual.pdf
  packages/preview/alexandria/0.1.3/gallery/example.pdf
  packages/preview/alexandria/0.1.3/src/alexandria.wasm
  packages/preview/alexandria/0.1.3/src/hayagriva.typ
  packages/preview/alexandria/0.1.3/src/internal.typ
  packages/preview/alexandria/0.1.3/src/lib.typ
  packages/preview/alexandria/0.1.3/src/state.typ
  packages/preview/alexandria/0.1.3/thumbnail-dark.svg
  packages/preview/alexandria/0.1.3/thumbnail-light.svg
  packages/preview/alexandria/0.1.3/typst.toml
Labels: update

#1997 simpleplot:0.1.1
  packages/preview/simpleplot/0.1.1/LICENSE.txt
  packages/preview/simpleplot/0.1.1/README.md
  packages/preview/simpleplot/0.1.1/graph.png
  packages/preview/simpleplot/0.1.1/graph_bright.png
  packages/preview/simpleplot/0.1.1/graph_dark.png
  packages/preview/simpleplot/0.1.1/lib.typ
  packages/preview/simpleplot/0.1.1/typst.toml
Labels: update

#1998 tgm-hit-thesis:0.3.0
  packages/preview/tgm-hit-thesis/0.3.0/.gitignore
  packages/preview/tgm-hit-thesis/0.3.0/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.3.0/LICENSE
  packages/preview/tgm-hit-thesis/0.3.0/README.md
  packages/preview/tgm-hit-thesis/0.3.0/docs/manual.pdf
  packages/preview/tgm-hit-thesis/0.3.0/example.pdf
  packages/preview/tgm-hit-thesis/0.3.0/src/assets.typ
  packages/preview/tgm-hit-thesis/0.3.0/src/assets/logo-left.png
  packages/preview/tgm-hit-thesis/0.3.0/src/assets/logo-right.png
  packages/preview/tgm-hit-thesis/0.3.0/src/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.3.0/src/bib.typ
  packages/preview/tgm-hit-thesis/0.3.0/src/glossary.typ
  packages/preview/tgm-hit-thesis/0.3.0/src/l10n.toml
  packages/preview/tgm-hit-thesis/0.3.0/src/l10n.typ
  packages/preview/tgm-hit-thesis/0.3.0/src/lib.typ
  packages/preview/tgm-hit-thesis/0.3.0/src/utils.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/assets.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/assets/logo.png
  packages/preview/tgm-hit-thesis/0.3.0/template/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/bibliography.bib
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/conclusio.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/danksagung.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/einleitung.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/implementierung.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/konzept.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/kurzfassung.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/retrospektive.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/studie.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/chapters/vorwort.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/glossaries.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/lib.typ
  packages/preview/tgm-hit-thesis/0.3.0/template/main.typ
  packages/preview/tgm-hit-thesis/0.3.0/thumbnail.png
  packages/preview/tgm-hit-thesis/0.3.0/typst.toml
Labels: update

#1999 diatypst:0.5.0
  packages/preview/diatypst/0.5.0/LICENSE
  packages/preview/diatypst/0.5.0/README.md
  packages/preview/diatypst/0.5.0/example/diaprojektor.jpg
  packages/preview/diatypst/0.5.0/example/diatype.jpg
  packages/preview/diatypst/0.5.0/example/example.pdf
  packages/preview/diatypst/0.5.0/example/example.typ
  packages/preview/diatypst/0.5.0/example/example_full.pdf
  packages/preview/diatypst/0.5.0/lib.typ
  packages/preview/diatypst/0.5.0/screenshots/Example-Section.png
  packages/preview/diatypst/0.5.0/screenshots/Example-Slide.png
  packages/preview/diatypst/0.5.0/screenshots/Example-TOC.png
  packages/preview/diatypst/0.5.0/screenshots/Example-Title.png
  packages/preview/diatypst/0.5.0/screenshots/Full-Example-Slide.png
  packages/preview/diatypst/0.5.0/screenshots/Full-Example-TOC.png
  packages/preview/diatypst/0.5.0/screenshots/Thumbnail.png
  packages/preview/diatypst/0.5.0/template/main.typ
  packages/preview/diatypst/0.5.0/typst.toml
Labels: update

#2001 modern-sjtu-thesis:0.2.1
  packages/preview/modern-sjtu-thesis/0.2.1/.gitignore
  packages/preview/modern-sjtu-thesis/0.2.1/LICENSE
  packages/preview/modern-sjtu-thesis/0.2.1/README.md
  packages/preview/modern-sjtu-thesis/0.2.1/assets/sjtu-logo.png
  packages/preview/modern-sjtu-thesis/0.2.1/layouts/appendix.typ
  packages/preview/modern-sjtu-thesis/0.2.1/layouts/doc.typ
  packages/preview/modern-sjtu-thesis/0.2.1/layouts/mainmatter.typ
  packages/preview/modern-sjtu-thesis/0.2.1/layouts/preface.typ
  packages/preview/modern-sjtu-thesis/0.2.1/lib.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/abstract-en.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/abstract.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/achievement.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/acknowledgement.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/bib.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/cover-bachelor.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/cover-en.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/cover.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/declare.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/outline.typ
  packages/preview/modern-sjtu-thesis/0.2.1/pages/summary-en.typ
  packages/preview/modern-sjtu-thesis/0.2.1/template/figures/energy-distribution.png
  packages/preview/modern-sjtu-thesis/0.2.1/template/ref.bib
  packages/preview/modern-sjtu-thesis/0.2.1/template/thesis.typ
  packages/preview/modern-sjtu-thesis/0.2.1/thumbnail.png
  packages/preview/modern-sjtu-thesis/0.2.1/typst.toml
  packages/preview/modern-sjtu-thesis/0.2.1/utils/bilingual-bibliography.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/checkbox.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/datetime-display.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/distr.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/header.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/heading.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/list-enum-align.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/style.typ
  packages/preview/modern-sjtu-thesis/0.2.1/utils/uline.typ
Labels: update

#1978 statementsp:0.1.0
  packages/preview/statementsp/0.1.0/LICENSE.txt
  packages/preview/statementsp/0.1.0/README.md
  packages/preview/statementsp/0.1.0/images/sampleimage.jpg
  packages/preview/statementsp/0.1.0/images/superdefinition.png
  packages/preview/statementsp/0.1.0/statementsp.typ
  packages/preview/statementsp/0.1.0/typst.toml
Labels: new

#2004 alchemist:0.1.5
  packages/preview/alchemist/0.1.5/LICENSE
  packages/preview/alchemist/0.1.5/README.md
  packages/preview/alchemist/0.1.5/lib.typ
  packages/preview/alchemist/0.1.5/src/default.typ
  packages/preview/alchemist/0.1.5/src/drawer.typ
  packages/preview/alchemist/0.1.5/src/drawer/branch.typ
  packages/preview/alchemist/0.1.5/src/drawer/cram.typ
  packages/preview/alchemist/0.1.5/src/drawer/cycle.typ
  packages/preview/alchemist/0.1.5/src/drawer/hook.typ
  packages/preview/alchemist/0.1.5/src/drawer/link.typ
  packages/preview/alchemist/0.1.5/src/drawer/molecule.typ
  packages/preview/alchemist/0.1.5/src/drawer/parenthesis.typ
  packages/preview/alchemist/0.1.5/src/elements/lewis.typ
  packages/preview/alchemist/0.1.5/src/elements/links.typ
  packages/preview/alchemist/0.1.5/src/elements/molecule.typ
  packages/preview/alchemist/0.1.5/src/utils/anchors.typ
  packages/preview/alchemist/0.1.5/src/utils/angles.typ
  packages/preview/alchemist/0.1.5/src/utils/context.typ
  packages/preview/alchemist/0.1.5/src/utils/utils.typ
  packages/preview/alchemist/0.1.5/typst.toml
Labels: update

#1964 chic-hdr:0.5.0
  packages/preview/chic-hdr/0.5.0/LICENSE
  packages/preview/chic-hdr/0.5.0/README.md
  packages/preview/chic-hdr/0.5.0/assets/example-1.png
  packages/preview/chic-hdr/0.5.0/assets/example-2.png
  packages/preview/chic-hdr/0.5.0/assets/usage.png
  packages/preview/chic-hdr/0.5.0/chic-hdr.typ
  packages/preview/chic-hdr/0.5.0/lib/functions.typ
  packages/preview/chic-hdr/0.5.0/lib/layout.typ
  packages/preview/chic-hdr/0.5.0/lib/props.typ
  packages/preview/chic-hdr/0.5.0/lib/types.typ
  packages/preview/chic-hdr/0.5.0/typst.toml
Labels: update

#2008 tally:0.1.0
  packages/preview/tally/0.1.0/.gitignore
  packages/preview/tally/0.1.0/CHANGELOG.md
  packages/preview/tally/0.1.0/LICENSE
  packages/preview/tally/0.1.0/README.md
  packages/preview/tally/0.1.0/src/lib.typ
  packages/preview/tally/0.1.0/typst.toml
Labels: new

#1996 modernpro-cv:1.1.0
  packages/preview/modernpro-cv/1.1.0/README.md
  packages/preview/modernpro-cv/1.1.0/modernpro-cv.typ
  packages/preview/modernpro-cv/1.1.0/template/bib.bib
  packages/preview/modernpro-cv/1.1.0/template/cv-double.typ
  packages/preview/modernpro-cv/1.1.0/template/cv-single.typ
  packages/preview/modernpro-cv/1.1.0/thumbnail.png
  packages/preview/modernpro-cv/1.1.0/typst.toml
Labels: update

#2010 amsterdammetje-article:0.1.0
  packages/preview/amsterdammetje-article/0.1.0/LICENSE
  packages/preview/amsterdammetje-article/0.1.0/README.md
  packages/preview/amsterdammetje-article/0.1.0/lib.typ
  packages/preview/amsterdammetje-article/0.1.0/logoUvA_en.svg
  packages/preview/amsterdammetje-article/0.1.0/logoUvA_nl.svg
  packages/preview/amsterdammetje-article/0.1.0/template/main.typ
  packages/preview/amsterdammetje-article/0.1.0/template/references.bib
  packages/preview/amsterdammetje-article/0.1.0/thumbnail.png
  packages/preview/amsterdammetje-article/0.1.0/typst.toml
Labels: new

#2015 decasify:0.10.1
  packages/preview/decasify/0.10.1/LICENSE
  packages/preview/decasify/0.10.1/README.md
  packages/preview/decasify/0.10.1/decasify.typ
  packages/preview/decasify/0.10.1/decasify.wasm
  packages/preview/decasify/0.10.1/readme_1.svg
  packages/preview/decasify/0.10.1/readme_2.svg
  packages/preview/decasify/0.10.1/readme_3.svg
  packages/preview/decasify/0.10.1/typst.toml
Labels: update

#2017 fletcher:0.5.7
  packages/preview/fletcher/0.5.7/LICENSE
  packages/preview/fletcher/0.5.7/README.md
  packages/preview/fletcher/0.5.7/docs/gallery/1-commutative.svg
  packages/preview/fletcher/0.5.7/docs/gallery/1-commutative.typ
  packages/preview/fletcher/0.5.7/docs/gallery/2-algebra-cube.svg
  packages/preview/fletcher/0.5.7/docs/gallery/2-algebra-cube.typ
  packages/preview/fletcher/0.5.7/docs/gallery/3-ml-architecture.svg
  packages/preview/fletcher/0.5.7/docs/gallery/3-ml-architecture.typ
  packages/preview/fletcher/0.5.7/docs/gallery/4-io-flowchart.svg
  packages/preview/fletcher/0.5.7/docs/gallery/4-io-flowchart.typ
  packages/preview/fletcher/0.5.7/docs/gallery/5-digraph.svg
  packages/preview/fletcher/0.5.7/docs/gallery/5-digraph.typ
  packages/preview/fletcher/0.5.7/docs/gallery/6-node-groups.svg
  packages/preview/fletcher/0.5.7/docs/gallery/6-node-groups.typ
  packages/preview/fletcher/0.5.7/docs/gallery/7-uml-diagram.svg
  packages/preview/fletcher/0.5.7/docs/gallery/7-uml-diagram.typ
  packages/preview/fletcher/0.5.7/docs/gallery/8-tree.svg
  packages/preview/fletcher/0.5.7/docs/gallery/8-tree.typ
  packages/preview/fletcher/0.5.7/docs/manual.pdf
  packages/preview/fletcher/0.5.7/docs/manual.typ
  packages/preview/fletcher/0.5.7/docs/readme-examples/1-first-isomorphism-theorem-dark.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/1-first-isomorphism-theorem-light.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/1-first-isomorphism-theorem.typ
  packages/preview/fletcher/0.5.7/docs/readme-examples/2-flowchart-trap-dark.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/2-flowchart-trap-light.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/2-flowchart-trap.typ
  packages/preview/fletcher/0.5.7/docs/readme-examples/3-state-machine-dark.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/3-state-machine-light.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/3-state-machine.typ
  packages/preview/fletcher/0.5.7/docs/readme-examples/4-feynman-diagram-dark.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/4-feynman-diagram-light.svg
  packages/preview/fletcher/0.5.7/docs/readme-examples/4-feynman-diagram.typ
  packages/preview/fletcher/0.5.7/docs/style.typ
  packages/preview/fletcher/0.5.7/src/coords.typ
  packages/preview/fletcher/0.5.7/src/default-marks.typ
  packages/preview/fletcher/0.5.7/src/deps.typ
  packages/preview/fletcher/0.5.7/src/diagram.typ
  packages/preview/fletcher/0.5.7/src/draw.typ
  packages/preview/fletcher/0.5.7/src/edge.typ
  packages/preview/fletcher/0.5.7/src/exports.typ
  packages/preview/fletcher/0.5.7/src/marks.typ
  packages/preview/fletcher/0.5.7/src/node.typ
  packages/preview/fletcher/0.5.7/src/shapes.typ
  packages/preview/fletcher/0.5.7/src/utils.typ
  packages/preview/fletcher/0.5.7/typst.toml
Labels: update

#2020 unofficial-hka-thesis:1.0.1
  packages/preview/unofficial-hka-thesis/1.0.1/LICENSE
  packages/preview/unofficial-hka-thesis/1.0.1/README.md
  packages/preview/unofficial-hka-thesis/1.0.1/assets/HKALogo.png
  packages/preview/unofficial-hka-thesis/1.0.1/assets/SAPLogo.svg
  packages/preview/unofficial-hka-thesis/1.0.1/assets/company.jpg
  packages/preview/unofficial-hka-thesis/1.0.1/assets/company.svg
  packages/preview/unofficial-hka-thesis/1.0.1/assets/image-1.png
  packages/preview/unofficial-hka-thesis/1.0.1/assets/image-2.png
  packages/preview/unofficial-hka-thesis/1.0.1/assets/image.png
  packages/preview/unofficial-hka-thesis/1.0.1/lib.typ
  packages/preview/unofficial-hka-thesis/1.0.1/modules/titlepage.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/abbreviations.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/bibliography/thesis.bib
  packages/preview/unofficial-hka-thesis/1.0.1/template/chapters/1_introduction.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/chapters/2_foundations.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/chapters/A1_Material.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/chapters/A2_Transcripts.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/figures/tiger.png
  packages/preview/unofficial-hka-thesis/1.0.1/template/logo/HKALogo.png
  packages/preview/unofficial-hka-thesis/1.0.1/template/logo/company.svg
  packages/preview/unofficial-hka-thesis/1.0.1/template/settings/metadata.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/settings/settings.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/supplementary/abstract.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/supplementary/abstractGerman.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/supplementary/statutoryDeclaration.typ
  packages/preview/unofficial-hka-thesis/1.0.1/template/thesis.typ
  packages/preview/unofficial-hka-thesis/1.0.1/thumbnail.png
  packages/preview/unofficial-hka-thesis/1.0.1/typst.toml
Labels: update

#2023 scholarly-tauthesis:0.11.0
  packages/preview/scholarly-tauthesis/0.11.0/.gitattributes
  packages/preview/scholarly-tauthesis/0.11.0/.gitignore
  packages/preview/scholarly-tauthesis/0.11.0/LICENSE
  packages/preview/scholarly-tauthesis/0.11.0/README.md
  packages/preview/scholarly-tauthesis/0.11.0/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.11.0/template/code/README.md
  packages/preview/scholarly-tauthesis/0.11.0/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.11.0/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/B.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/README.md
  packages/preview/scholarly-tauthesis/0.11.0/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/images/README.md
  packages/preview/scholarly-tauthesis/0.11.0/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.11.0/template/main.typ
  packages/preview/scholarly-tauthesis/0.11.0/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.11.0/thumbnail.png
  packages/preview/scholarly-tauthesis/0.11.0/typst.toml
Labels: update

#2027 Always use the filesystem timestamp if Git did not succeed
  bundler/src/timestamp.rs
Labels: meta

#2009 tuhi-alumni-vuw:0.1.0
  packages/preview/tuhi-alumni-vuw/0.1.0/LICENSE
  packages/preview/tuhi-alumni-vuw/0.1.0/README.md
  packages/preview/tuhi-alumni-vuw/0.1.0/braid.svg
  packages/preview/tuhi-alumni-vuw/0.1.0/template/images/person.jpg
  packages/preview/tuhi-alumni-vuw/0.1.0/template/main.typ
  packages/preview/tuhi-alumni-vuw/0.1.0/thumbnail.png
  packages/preview/tuhi-alumni-vuw/0.1.0/tuhi-alumni-vuw.typ
  packages/preview/tuhi-alumni-vuw/0.1.0/typst.toml
Labels: new

#2016 vienna-tech:1.0.0
  packages/preview/vienna-tech/1.0.0/CHANGELOG.md
  packages/preview/vienna-tech/1.0.0/LICENSE
  packages/preview/vienna-tech/1.0.0/README.md
  packages/preview/vienna-tech/1.0.0/src/constructors.typ
  packages/preview/vienna-tech/1.0.0/src/lib.typ
  packages/preview/vienna-tech/1.0.0/src/styles.typ
  packages/preview/vienna-tech/1.0.0/src/utils.typ
  packages/preview/vienna-tech/1.0.0/template/abstract.typ
  packages/preview/vienna-tech/1.0.0/template/appendix.typ
  packages/preview/vienna-tech/1.0.0/template/assets/refs.bib
  packages/preview/vienna-tech/1.0.0/template/main.typ
  packages/preview/vienna-tech/1.0.0/template/sections.typ
  packages/preview/vienna-tech/1.0.0/thumbnail.png
  packages/preview/vienna-tech/1.0.0/typst.toml
Labels: update

#1880 touying-ppt-hustvn:0.1.0
  packages/preview/touying-ppt-hustvn/0.1.0/LICENSE
  packages/preview/touying-ppt-hustvn/0.1.0/README.md
  packages/preview/touying-ppt-hustvn/0.1.0/assets/ending-bg-blue-16-9.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/ending-bg-blue-4-3.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/ending-bg-red-16-9.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/ending-bg-red-4-3.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/footer-left.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/title-bg-blue-16-9.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/title-bg-blue-4-3.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/title-bg-red-16-9.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/title-bg-red-4-3.png
  packages/preview/touying-ppt-hustvn/0.1.0/assets/title-top-left.png
  packages/preview/touying-ppt-hustvn/0.1.0/examples/main.typ
  packages/preview/touying-ppt-hustvn/0.1.0/lib.typ
  packages/preview/touying-ppt-hustvn/0.1.0/template/main.typ
  packages/preview/touying-ppt-hustvn/0.1.0/thumbnail.png
  packages/preview/touying-ppt-hustvn/0.1.0/typst.toml
Labels: new

#2029 theorion:0.3.3
  packages/preview/theorion/0.3.3/LICENSE
  packages/preview/theorion/0.3.3/README.md
  packages/preview/theorion/0.3.3/core.typ
  packages/preview/theorion/0.3.3/cosmos/clouds.typ
  packages/preview/theorion/0.3.3/cosmos/cosmos.typ
  packages/preview/theorion/0.3.3/cosmos/default.typ
  packages/preview/theorion/0.3.3/cosmos/fancy.typ
  packages/preview/theorion/0.3.3/cosmos/rainbow.typ
  packages/preview/theorion/0.3.3/cosmos/simple.typ
  packages/preview/theorion/0.3.3/deps.typ
  packages/preview/theorion/0.3.3/examples/example-ar.typ
  packages/preview/theorion/0.3.3/examples/example-zh.typ
  packages/preview/theorion/0.3.3/examples/example.png
  packages/preview/theorion/0.3.3/examples/example.typ
  packages/preview/theorion/0.3.3/i18n.typ
  packages/preview/theorion/0.3.3/lib.typ
  packages/preview/theorion/0.3.3/typst.toml
Labels: update

#2030 sano-presentation-template:1.0.0
  packages/preview/sano-presentation-template/1.0.0/LICENSE
  packages/preview/sano-presentation-template/1.0.0/README.md
  packages/preview/sano-presentation-template/1.0.0/lib.typ
  packages/preview/sano-presentation-template/1.0.0/template/main.typ
  packages/preview/sano-presentation-template/1.0.0/thumbnail.png
  packages/preview/sano-presentation-template/1.0.0/typst.toml
Labels: new

#2031 peace-of-posters:0.5.3
  packages/preview/peace-of-posters/0.5.3/LICENSE
  packages/preview/peace-of-posters/0.5.3/README.md
  packages/preview/peace-of-posters/0.5.3/boxes.typ
  packages/preview/peace-of-posters/0.5.3/layouts.typ
  packages/preview/peace-of-posters/0.5.3/lib.typ
  packages/preview/peace-of-posters/0.5.3/templates/pop-uni-fr-poster/Treron_vernans_male_-_Kent_Ridge_Park.jpg
  packages/preview/peace-of-posters/0.5.3/templates/pop-uni-fr-poster/bibliography.bib
  packages/preview/peace-of-posters/0.5.3/templates/pop-uni-fr-poster/main.typ
  packages/preview/peace-of-posters/0.5.3/templates/pop-uni-fr-poster/peace-dove.png
  packages/preview/peace-of-posters/0.5.3/templates/pop-uni-fr-poster/thumbnail.png
  packages/preview/peace-of-posters/0.5.3/themes.typ
  packages/preview/peace-of-posters/0.5.3/typst.toml
Labels: update

#1989 minimal-presentation:0.6.0
  packages/preview/minimal-presentation/0.6.0/LICENSE
  packages/preview/minimal-presentation/0.6.0/README.md
  packages/preview/minimal-presentation/0.6.0/lib.typ
  packages/preview/minimal-presentation/0.6.0/template/bibliography.yaml
  packages/preview/minimal-presentation/0.6.0/template/image_1.jpg
  packages/preview/minimal-presentation/0.6.0/template/logo.svg
  packages/preview/minimal-presentation/0.6.0/template/logo_light.svg
  packages/preview/minimal-presentation/0.6.0/template/main.typ
  packages/preview/minimal-presentation/0.6.0/thumbnail.png
  packages/preview/minimal-presentation/0.6.0/typst.toml
Labels: update

#2032 formalettre:0.1.2
  packages/preview/formalettre/0.1.2/LICENSE
  packages/preview/formalettre/0.1.2/README.md
  packages/preview/formalettre/0.1.2/src/lib.typ
  packages/preview/formalettre/0.1.2/template/src/exemple.typ
  packages/preview/formalettre/0.1.2/thumbnail.png
  packages/preview/formalettre/0.1.2/typst.toml
Labels: update

#2034 not-tudabeamer-2023:0.2.0
  packages/preview/not-tudabeamer-2023/0.2.0/.gitignore
  packages/preview/not-tudabeamer-2023/0.2.0/LICENSE
  packages/preview/not-tudabeamer-2023/0.2.0/README.md
  packages/preview/not-tudabeamer-2023/0.2.0/lib.typ
  packages/preview/not-tudabeamer-2023/0.2.0/template/main.typ
  packages/preview/not-tudabeamer-2023/0.2.0/thumbnail.webp
  packages/preview/not-tudabeamer-2023/0.2.0/typst.toml
Labels: update

#2035 frame-it:1.1.1
  packages/preview/frame-it/1.1.1/.gitignore
  packages/preview/frame-it/1.1.1/LICENSE
  packages/preview/frame-it/1.1.1/README.md
  packages/preview/frame-it/1.1.1/README.typ
  packages/preview/frame-it/1.1.1/src/bundled-layout.typ
  packages/preview/frame-it/1.1.1/src/layout.typ
  packages/preview/frame-it/1.1.1/src/lib.typ
  packages/preview/frame-it/1.1.1/src/parse.typ
  packages/preview/frame-it/1.1.1/src/styles/boxy.typ
  packages/preview/frame-it/1.1.1/src/styles/hint.typ
  packages/preview/frame-it/1.1.1/src/styles/thmbox.typ
  packages/preview/frame-it/1.1.1/src/styling.typ
  packages/preview/frame-it/1.1.1/src/utils/html.typ
  packages/preview/frame-it/1.1.1/typst.toml
Labels: update

#2036 problemst:0.1.2
  packages/preview/problemst/0.1.2/LICENSE.md
  packages/preview/problemst/0.1.2/README.md
  packages/preview/problemst/0.1.2/pset.pdf
  packages/preview/problemst/0.1.2/pset.typ
  packages/preview/problemst/0.1.2/template/main.typ
  packages/preview/problemst/0.1.2/thumbnail.png
  packages/preview/problemst/0.1.2/typst.toml
Labels: update

#2038 touying-quarto-clean:0.1.0
  packages/preview/touying-quarto-clean/0.1.0/typst.toml
Labels: new

#2044 adaptable-pset:0.1.0
  packages/preview/adaptable-pset/0.1.0/LICENSE
  packages/preview/adaptable-pset/0.1.0/README.md
  packages/preview/adaptable-pset/0.1.0/docs/manual.pdf
  packages/preview/adaptable-pset/0.1.0/src/lib.typ
  packages/preview/adaptable-pset/0.1.0/template/main.typ
  packages/preview/adaptable-pset/0.1.0/thumbnail.png
  packages/preview/adaptable-pset/0.1.0/typst.toml
Labels: new

#2037 now-radboud-thesis:0.1.0
  packages/preview/now-radboud-thesis/0.1.0/LICENSE
  packages/preview/now-radboud-thesis/0.1.0/Logo_Radboud_University.svg
  packages/preview/now-radboud-thesis/0.1.0/README.md
  packages/preview/now-radboud-thesis/0.1.0/radboud-thesis.typ
  packages/preview/now-radboud-thesis/0.1.0/template/bibliography.bib
  packages/preview/now-radboud-thesis/0.1.0/template/thesis.typ
  packages/preview/now-radboud-thesis/0.1.0/thumbnail.png
  packages/preview/now-radboud-thesis/0.1.0/typst.toml
Labels: new

#2042 tuhi-postcard-vuw:0.1.0
  packages/preview/tuhi-postcard-vuw/0.1.0/LICENSE
  packages/preview/tuhi-postcard-vuw/0.1.0/README.md
  packages/preview/tuhi-postcard-vuw/0.1.0/envelope-at-fill.svg
  packages/preview/tuhi-postcard-vuw/0.1.0/info-circle-fill.svg
  packages/preview/tuhi-postcard-vuw/0.1.0/telephone-fill.svg
  packages/preview/tuhi-postcard-vuw/0.1.0/template/images/TEAS.jpg
  packages/preview/tuhi-postcard-vuw/0.1.0/template/images/logo.svg
  packages/preview/tuhi-postcard-vuw/0.1.0/template/main.typ
  packages/preview/tuhi-postcard-vuw/0.1.0/thumbnail.png
  packages/preview/tuhi-postcard-vuw/0.1.0/tuhi-postcard-vuw.typ
  packages/preview/tuhi-postcard-vuw/0.1.0/typst.toml
Labels: new

#1777 modern-whs-thesis:0.3.0
  packages/preview/modern-whs-thesis/0.3.0/README.md
  packages/preview/modern-whs-thesis/0.3.0/example/acronyms.typ
  packages/preview/modern-whs-thesis/0.3.0/example/bibliography.bib
  packages/preview/modern-whs-thesis/0.3.0/example/chapters/00_abstract.typ
  packages/preview/modern-whs-thesis/0.3.0/example/chapters/01_introduction.typ
  packages/preview/modern-whs-thesis/0.3.0/example/chapters/02_definitions.typ
  packages/preview/modern-whs-thesis/0.3.0/example/chapters/03_concept.typ
  packages/preview/modern-whs-thesis/0.3.0/example/chapters/04_implementation.typ
  packages/preview/modern-whs-thesis/0.3.0/example/chapters/05_conclusion.typ
  packages/preview/modern-whs-thesis/0.3.0/example/main.typ
  packages/preview/modern-whs-thesis/0.3.0/example/meta.typ
  packages/preview/modern-whs-thesis/0.3.0/template/elements.typ
  packages/preview/modern-whs-thesis/0.3.0/template/iso690-author-date-de.csl
  packages/preview/modern-whs-thesis/0.3.0/template/lib.typ
  packages/preview/modern-whs-thesis/0.3.0/template/partial/affidavit.typ
  packages/preview/modern-whs-thesis/0.3.0/template/partial/glossar.typ
  packages/preview/modern-whs-thesis/0.3.0/template/partial/images/background.jpg
  packages/preview/modern-whs-thesis/0.3.0/template/partial/title.typ
  packages/preview/modern-whs-thesis/0.3.0/template/settings.typ
  packages/preview/modern-whs-thesis/0.3.0/thumbnail.png
  packages/preview/modern-whs-thesis/0.3.0/typst.toml
Labels: update

#1776 modern-whs-assignment:0.2.0
  packages/preview/modern-whs-assignment/0.2.0/README.md
  packages/preview/modern-whs-assignment/0.2.0/example/chapters/01_introduction.typ
  packages/preview/modern-whs-assignment/0.2.0/example/main.typ
  packages/preview/modern-whs-assignment/0.2.0/example/meta.typ
  packages/preview/modern-whs-assignment/0.2.0/example/references.bib
  packages/preview/modern-whs-assignment/0.2.0/template/images/logo.png
  packages/preview/modern-whs-assignment/0.2.0/template/lib.typ
  packages/preview/modern-whs-assignment/0.2.0/template/partial/iso690-author-date-de.csl
  packages/preview/modern-whs-assignment/0.2.0/template/partial/title.typ
  packages/preview/modern-whs-assignment/0.2.0/template/util.typ
  packages/preview/modern-whs-assignment/0.2.0/thumbnail.png
  packages/preview/modern-whs-assignment/0.2.0/typst.toml
Labels: update

#2046 bloated-neurips:0.7.0
  packages/preview/bloated-neurips/0.7.0/LICENSE
  packages/preview/bloated-neurips/0.7.0/README.md
  packages/preview/bloated-neurips/0.7.0/neurips.typ
  packages/preview/bloated-neurips/0.7.0/neurips2023.typ
  packages/preview/bloated-neurips/0.7.0/neurips2024.typ
  packages/preview/bloated-neurips/0.7.0/neurips2025.typ
  packages/preview/bloated-neurips/0.7.0/template/appendix.typ
  packages/preview/bloated-neurips/0.7.0/template/checklist.typ
  packages/preview/bloated-neurips/0.7.0/template/logo.typ
  packages/preview/bloated-neurips/0.7.0/template/main.bib
  packages/preview/bloated-neurips/0.7.0/template/main.typ
  packages/preview/bloated-neurips/0.7.0/thumbnail.png
  packages/preview/bloated-neurips/0.7.0/typst.toml
Labels: update

#2049 nifty-ntnu-thesis:0.1.2
  packages/preview/nifty-ntnu-thesis/0.1.2/LICENSE
  packages/preview/nifty-ntnu-thesis/0.1.2/README.md
  packages/preview/nifty-ntnu-thesis/0.1.2/example.pdf
  packages/preview/nifty-ntnu-thesis/0.1.2/lib.typ
  packages/preview/nifty-ntnu-thesis/0.1.2/template/figures/kart_student.png
  packages/preview/nifty-ntnu-thesis/0.1.2/template/main.typ
  packages/preview/nifty-ntnu-thesis/0.1.2/template/thesis.bib
  packages/preview/nifty-ntnu-thesis/0.1.2/thumbnail.png
  packages/preview/nifty-ntnu-thesis/0.1.2/typst.toml
Labels: update

#2050 thesist:1.0.1
  packages/preview/thesist/1.0.1/LICENSE
  packages/preview/thesist/1.0.1/README.md
  packages/preview/thesist/1.0.1/src/IST.png
  packages/preview/thesist/1.0.1/src/figure-numbering.typ
  packages/preview/thesist/1.0.1/src/heading-styles.typ
  packages/preview/thesist/1.0.1/src/layout.typ
  packages/preview/thesist/1.0.1/src/utils.typ
  packages/preview/thesist/1.0.1/template/Beginning/Abstract-en.typ
  packages/preview/thesist/1.0.1/template/Beginning/Abstract-pt.typ
  packages/preview/thesist/1.0.1/template/Beginning/Acknowledgments.typ
  packages/preview/thesist/1.0.1/template/Beginning/Extra-page.typ
  packages/preview/thesist/1.0.1/template/Beginning/Glossary.typ
  packages/preview/thesist/1.0.1/template/Beginning/Keywords-en.typ
  packages/preview/thesist/1.0.1/template/Beginning/Keywords-pt.typ
  packages/preview/thesist/1.0.1/template/Chapters/0-Quick-guide.typ
  packages/preview/thesist/1.0.1/template/Chapters/1-Introduction.typ
  packages/preview/thesist/1.0.1/template/Chapters/Appendix-A.typ
  packages/preview/thesist/1.0.1/template/Chapters/Appendix-B.typ
  packages/preview/thesist/1.0.1/template/Images/0-Quick-guide/example.jpg
  packages/preview/thesist/1.0.1/template/Images/default-alameda.jpg
  packages/preview/thesist/1.0.1/template/Images/default-taguspark.jpg
  packages/preview/thesist/1.0.1/template/main.typ
  packages/preview/thesist/1.0.1/template/refs.bib
  packages/preview/thesist/1.0.1/thumbnail.png
  packages/preview/thesist/1.0.1/typst.toml
Labels: update

#2045 enja-bib:0.1.0
  packages/preview/enja-bib/0.1.0/LICENSE
  packages/preview/enja-bib/0.1.0/README.md
  packages/preview/enja-bib/0.1.0/example/mybib_en.bib
  packages/preview/enja-bib/0.1.0/example/mybib_jp.bib
  packages/preview/enja-bib/0.1.0/example/test.typ
  packages/preview/enja-bib/0.1.0/src/bib-setting-custom/bib-setting-jsme.typ
  packages/preview/enja-bib/0.1.0/src/bib-setting-custom/bib-setting-plain.typ
  packages/preview/enja-bib/0.1.0/src/bib-setting-fucntion.typ
  packages/preview/enja-bib/0.1.0/src/bib-style.typ
  packages/preview/enja-bib/0.1.0/src/bib-tex.typ
  packages/preview/enja-bib/0.1.0/src/lib.typ
  packages/preview/enja-bib/0.1.0/typst.toml
Labels: new

#2051 nordic:0.1.0
  packages/preview/nordic/0.1.0/LICENSE
  packages/preview/nordic/0.1.0/README.md
  packages/preview/nordic/0.1.0/nordic.typ
  packages/preview/nordic/0.1.0/package.zip
  packages/preview/nordic/0.1.0/typst.toml
Labels: new

#2053 modern-xmu-thesis:0.1.0
  packages/preview/modern-xmu-thesis/0.1.0/LICENSE
  packages/preview/modern-xmu-thesis/0.1.0/README.md
  packages/preview/modern-xmu-thesis/0.1.0/assets/xmu-zi-jiageng.svg
  packages/preview/modern-xmu-thesis/0.1.0/layouts/appendix.typ
  packages/preview/modern-xmu-thesis/0.1.0/layouts/doc.typ
  packages/preview/modern-xmu-thesis/0.1.0/layouts/mainmatter.typ
  packages/preview/modern-xmu-thesis/0.1.0/layouts/preface.typ
  packages/preview/modern-xmu-thesis/0.1.0/lib.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/acknowledgement.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bachelor-abstract-en.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bachelor-abstract.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bachelor-cover.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bachelor-integrity.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bachelor-outline-page-en.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bachelor-outline-page.typ
  packages/preview/modern-xmu-thesis/0.1.0/pages/bilingual-bibliography.typ
  packages/preview/modern-xmu-thesis/0.1.0/template/images/xmu-logo.svg
  packages/preview/modern-xmu-thesis/0.1.0/template/ref.bib
  packages/preview/modern-xmu-thesis/0.1.0/template/thesis.typ
  packages/preview/modern-xmu-thesis/0.1.0/thumbnail.png
  packages/preview/modern-xmu-thesis/0.1.0/typst.toml
  packages/preview/modern-xmu-thesis/0.1.0/utils/datetime-display.typ
  packages/preview/modern-xmu-thesis/0.1.0/utils/invisible-heading.typ
  packages/preview/modern-xmu-thesis/0.1.0/utils/style.typ
  packages/preview/modern-xmu-thesis/0.1.0/utils/unpairs.typ
Labels: new

#2056 tally:0.1.1
  packages/preview/tally/0.1.1/.gitignore
  packages/preview/tally/0.1.1/CHANGELOG.md
  packages/preview/tally/0.1.1/LICENSE
  packages/preview/tally/0.1.1/README.md
  packages/preview/tally/0.1.1/src/lib.typ
  packages/preview/tally/0.1.1/typst.toml
Labels: update

#2048 unofficial-sdu-thesis:0.2.0
  packages/preview/unofficial-sdu-thesis/0.2.0/LICENSE
  packages/preview/unofficial-sdu-thesis/0.2.0/README.md
  packages/preview/unofficial-sdu-thesis/0.2.0/imgs/logo.svg
  packages/preview/unofficial-sdu-thesis/0.2.0/layouts/appendix.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/layouts/doc.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/layouts/mainmatter.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/lib.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/pages/abstract.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/pages/acknowledgement.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/pages/bib.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/pages/cover.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/pages/outline.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/styles/distr.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/styles/enums.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/styles/figures.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/styles/fonts.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/styles/heading.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/template/concise.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/template/img/AlbertEinstein.png
  packages/preview/unofficial-sdu-thesis/0.2.0/template/img/ClaudeElwoodShannon.png
  packages/preview/unofficial-sdu-thesis/0.2.0/template/img/John von Neumann.png
  packages/preview/unofficial-sdu-thesis/0.2.0/template/img/appendix/Lenna.png
  packages/preview/unofficial-sdu-thesis/0.2.0/template/img/appendix/Sierpinski_pyramid.jpg
  packages/preview/unofficial-sdu-thesis/0.2.0/template/img/appendix/Sigmoid.svg
  packages/preview/unofficial-sdu-thesis/0.2.0/template/ref.bib
  packages/preview/unofficial-sdu-thesis/0.2.0/template/thesis.typ
  packages/preview/unofficial-sdu-thesis/0.2.0/thumbnail.png
  packages/preview/unofficial-sdu-thesis/0.2.0/typst.toml
Labels: update

#2005 modern-unimib-thesis:0.1.1
  packages/preview/modern-unimib-thesis/0.1.1/LICENSE
  packages/preview/modern-unimib-thesis/0.1.1/LOGO_LICENSE.txt
  packages/preview/modern-unimib-thesis/0.1.1/README.md
  packages/preview/modern-unimib-thesis/0.1.1/lib.typ
  packages/preview/modern-unimib-thesis/0.1.1/template/images/logo_unimib.png
  packages/preview/modern-unimib-thesis/0.1.1/template/main.typ
  packages/preview/modern-unimib-thesis/0.1.1/template/refs.bib
  packages/preview/modern-unimib-thesis/0.1.1/thumbnail.png
  packages/preview/modern-unimib-thesis/0.1.1/typst.toml
Labels: update

#2055 adaptable-pset:0.1.1
  packages/preview/adaptable-pset/0.1.1/LICENSE
  packages/preview/adaptable-pset/0.1.1/README.md
  packages/preview/adaptable-pset/0.1.1/docs/manual.pdf
  packages/preview/adaptable-pset/0.1.1/src/lib.typ
  packages/preview/adaptable-pset/0.1.1/template/main.typ
  packages/preview/adaptable-pset/0.1.1/thumbnail.png
  packages/preview/adaptable-pset/0.1.1/typst.toml
Labels: update

#2059 fractusist:0.2.1
  packages/preview/fractusist/0.2.1/LICENSE
  packages/preview/fractusist/0.2.1/README.md
  packages/preview/fractusist/0.2.1/examples/dragon-curve-n12.png
  packages/preview/fractusist/0.2.1/examples/dragon-curve-n12.typ
  packages/preview/fractusist/0.2.1/examples/hypotrochoid-a19-b16-h2.png
  packages/preview/fractusist/0.2.1/examples/hypotrochoid-a19-b16-h2.typ
  packages/preview/fractusist/0.2.1/examples/koch-snowflake-n4.png
  packages/preview/fractusist/0.2.1/examples/koch-snowflake-n4.typ
  packages/preview/fractusist/0.2.1/examples/pythagorean-tree-n12.png
  packages/preview/fractusist/0.2.1/examples/pythagorean-tree-n12.typ
  packages/preview/fractusist/0.2.1/examples/random-fractal-tree-n14.png
  packages/preview/fractusist/0.2.1/examples/random-fractal-tree-n14.typ
  packages/preview/fractusist/0.2.1/examples/sierpinski-triangle-n6.png
  packages/preview/fractusist/0.2.1/examples/sierpinski-triangle-n6.typ
  packages/preview/fractusist/0.2.1/src/dragon.typ
  packages/preview/fractusist/0.2.1/src/fibonacci.typ
  packages/preview/fractusist/0.2.1/src/hilbert.typ
  packages/preview/fractusist/0.2.1/src/koch.typ
  packages/preview/fractusist/0.2.1/src/lib.typ
  packages/preview/fractusist/0.2.1/src/lissajous.typ
  packages/preview/fractusist/0.2.1/src/sierpinski.typ
  packages/preview/fractusist/0.2.1/src/spirograph.typ
  packages/preview/fractusist/0.2.1/src/tree.typ
  packages/preview/fractusist/0.2.1/typst.toml
Labels: update

#2060 blinky:0.2.0
  packages/preview/blinky/0.2.0/LICENSE
  packages/preview/blinky/0.2.0/README.md
  packages/preview/blinky/0.2.0/lib.typ
  packages/preview/blinky/0.2.0/typst.toml
Labels: update

#2061 modern-uit-thesis:0.1.4
  packages/preview/modern-uit-thesis/0.1.4/Justfile
  packages/preview/modern-uit-thesis/0.1.4/LICENSE
  packages/preview/modern-uit-thesis/0.1.4/README.md
  packages/preview/modern-uit-thesis/0.1.4/assets/backpage.svg
  packages/preview/modern-uit-thesis/0.1.4/assets/frontpage_full.svg
  packages/preview/modern-uit-thesis/0.1.4/assets/logo.svg
  packages/preview/modern-uit-thesis/0.1.4/flake.lock
  packages/preview/modern-uit-thesis/0.1.4/flake.nix
  packages/preview/modern-uit-thesis/0.1.4/lib.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/abbreviations.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/abstract.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/acknowledgements.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/backpage.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/epigraph.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/frontpage.typ
  packages/preview/modern-uit-thesis/0.1.4/modules/supervisors.typ
  packages/preview/modern-uit-thesis/0.1.4/scripts/package
  packages/preview/modern-uit-thesis/0.1.4/scripts/setup
  packages/preview/modern-uit-thesis/0.1.4/scripts/uninstall
  packages/preview/modern-uit-thesis/0.1.4/template/chapters/appendix.typ
  packages/preview/modern-uit-thesis/0.1.4/template/chapters/basic-usage.typ
  packages/preview/modern-uit-thesis/0.1.4/template/chapters/figures.typ
  packages/preview/modern-uit-thesis/0.1.4/template/chapters/introduction.typ
  packages/preview/modern-uit-thesis/0.1.4/template/chapters/typst-basics.typ
  packages/preview/modern-uit-thesis/0.1.4/template/chapters/utilities.typ
  packages/preview/modern-uit-thesis/0.1.4/template/code-snippets/Program.fsx
  packages/preview/modern-uit-thesis/0.1.4/template/figures/dining_philosophers.png
  packages/preview/modern-uit-thesis/0.1.4/template/figures/philosophers.png
  packages/preview/modern-uit-thesis/0.1.4/template/figures/plot_serial.svg
  packages/preview/modern-uit-thesis/0.1.4/template/figures/table.csv
  packages/preview/modern-uit-thesis/0.1.4/template/figures/uit_aurora.jpg
  packages/preview/modern-uit-thesis/0.1.4/template/refs.bib
  packages/preview/modern-uit-thesis/0.1.4/template/thesis.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/caption.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/feedback.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/form.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/global.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/subfigure.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/symbols.typ
  packages/preview/modern-uit-thesis/0.1.4/template/utils/todo.typ
  packages/preview/modern-uit-thesis/0.1.4/thumbnail.png
  packages/preview/modern-uit-thesis/0.1.4/typst.toml
  packages/preview/modern-uit-thesis/0.1.4/xcharter.nix
Labels: update

#2062 ttt-utils:0.1.4
  packages/preview/ttt-utils/0.1.4/LICENSE
  packages/preview/ttt-utils/0.1.4/README.md
  packages/preview/ttt-utils/0.1.4/lib/assignments.typ
  packages/preview/ttt-utils/0.1.4/lib/components.typ
  packages/preview/ttt-utils/0.1.4/lib/grading.typ
  packages/preview/ttt-utils/0.1.4/lib/helpers.typ
  packages/preview/ttt-utils/0.1.4/lib/layout.typ
  packages/preview/ttt-utils/0.1.4/lib/lib.typ
  packages/preview/ttt-utils/0.1.4/lib/random.typ
  packages/preview/ttt-utils/0.1.4/typst.toml
Labels: update

#2057 frame-it:1.1.2
  packages/preview/frame-it/1.1.2/LICENSE
  packages/preview/frame-it/1.1.2/README.md
  packages/preview/frame-it/1.1.2/README.typ
  packages/preview/frame-it/1.1.2/src/bundled-layout.typ
  packages/preview/frame-it/1.1.2/src/inspect.typ
  packages/preview/frame-it/1.1.2/src/layout.typ
  packages/preview/frame-it/1.1.2/src/lib.typ
  packages/preview/frame-it/1.1.2/src/parse.typ
  packages/preview/frame-it/1.1.2/src/styles/boxy.typ
  packages/preview/frame-it/1.1.2/src/styles/hint.typ
  packages/preview/frame-it/1.1.2/src/styles/thmbox.typ
  packages/preview/frame-it/1.1.2/src/styling.typ
  packages/preview/frame-it/1.1.2/src/utils/encode.typ
  packages/preview/frame-it/1.1.2/src/utils/html.typ
  packages/preview/frame-it/1.1.2/typst.toml
Labels: update

#2064 kthesis:0.1.1
  packages/preview/kthesis/0.1.1/.envrc
  packages/preview/kthesis/0.1.1/.gitignore
  packages/preview/kthesis/0.1.1/LICENSE-MIT
  packages/preview/kthesis/0.1.1/LICENSE-MIT-0
  packages/preview/kthesis/0.1.1/README.md
  packages/preview/kthesis/0.1.1/assets/KTH_logo_RGB_bla.svg
  packages/preview/kthesis/0.1.1/shell.nix
  packages/preview/kthesis/0.1.1/src/covers.typ
  packages/preview/kthesis/0.1.1/src/for-diva.typ
  packages/preview/kthesis/0.1.1/src/front-matter.typ
  packages/preview/kthesis/0.1.1/src/lang.toml
  packages/preview/kthesis/0.1.1/src/lib.typ
  packages/preview/kthesis/0.1.1/src/styling-setup.typ
  packages/preview/kthesis/0.1.1/src/utils.typ
  packages/preview/kthesis/0.1.1/template/acronyms.typ
  packages/preview/kthesis/0.1.1/template/content/abstract-1-en.typ
  packages/preview/kthesis/0.1.1/template/content/abstract-2-sv.typ
  packages/preview/kthesis/0.1.1/template/content/abstract-3-pt.typ
  packages/preview/kthesis/0.1.1/template/content/acknowledgements.typ
  packages/preview/kthesis/0.1.1/template/content/ch01-introduction.typ
  packages/preview/kthesis/0.1.1/template/content/ch02-background.typ
  packages/preview/kthesis/0.1.1/template/content/ch03-method.typ
  packages/preview/kthesis/0.1.1/template/content/ch04-the-thing.typ
  packages/preview/kthesis/0.1.1/template/content/ch05-results.typ
  packages/preview/kthesis/0.1.1/template/content/ch06-discussion.typ
  packages/preview/kthesis/0.1.1/template/content/ch07-conclusion.typ
  packages/preview/kthesis/0.1.1/template/content/zz-a-usage.typ
  packages/preview/kthesis/0.1.1/template/content/zz-b-else.typ
  packages/preview/kthesis/0.1.1/template/references.yaml
  packages/preview/kthesis/0.1.1/template/thesis.typ
  packages/preview/kthesis/0.1.1/thumbnail.png
  packages/preview/kthesis/0.1.1/typst.toml
Labels: update

#2066 harvard-gsas-thesis-oat:0.1.3
  packages/preview/harvard-gsas-thesis-oat/0.1.3/LICENSE
  packages/preview/harvard-gsas-thesis-oat/0.1.3/README.md
  packages/preview/harvard-gsas-thesis-oat/0.1.3/img/thumbnail.png
  packages/preview/harvard-gsas-thesis-oat/0.1.3/lib.typ
  packages/preview/harvard-gsas-thesis-oat/0.1.3/templates/main.typ
  packages/preview/harvard-gsas-thesis-oat/0.1.3/typst.toml
Labels: update

#2067 peace-of-posters:0.5.4
  packages/preview/peace-of-posters/0.5.4/LICENSE
  packages/preview/peace-of-posters/0.5.4/README.md
  packages/preview/peace-of-posters/0.5.4/boxes.typ
  packages/preview/peace-of-posters/0.5.4/layouts.typ
  packages/preview/peace-of-posters/0.5.4/lib.typ
  packages/preview/peace-of-posters/0.5.4/templates/pop-uni-fr-poster/Treron_vernans_male_-_Kent_Ridge_Park.jpg
  packages/preview/peace-of-posters/0.5.4/templates/pop-uni-fr-poster/bibliography.bib
  packages/preview/peace-of-posters/0.5.4/templates/pop-uni-fr-poster/main.typ
  packages/preview/peace-of-posters/0.5.4/templates/pop-uni-fr-poster/peace-dove.png
  packages/preview/peace-of-posters/0.5.4/templates/pop-uni-fr-poster/thumbnail.png
  packages/preview/peace-of-posters/0.5.4/themes.typ
  packages/preview/peace-of-posters/0.5.4/typst.toml
Labels: update

#2070 js:0.1.3
  packages/preview/js/0.1.3/LICENSE
  packages/preview/js/0.1.3/README.md
  packages/preview/js/0.1.3/js.typ
  packages/preview/js/0.1.3/template/example.typ
  packages/preview/js/0.1.3/thumbnail.png
  packages/preview/js/0.1.3/typst.toml
Labels: update

#2069 commute:0.3.0
  packages/preview/commute/0.3.0/LICENSE
  packages/preview/commute/0.3.0/README.md
  packages/preview/commute/0.3.0/example.typ
  packages/preview/commute/0.3.0/lib.typ
  packages/preview/commute/0.3.0/typst.toml
Labels: update

#2068 pintorita:0.1.4
  packages/preview/pintorita/0.1.4/LICENSE
  packages/preview/pintorita/0.1.4/NOTICE
  packages/preview/pintorita/0.1.4/README.md
  packages/preview/pintorita/0.1.4/lib.typ
  packages/preview/pintorita/0.1.4/pintora.js
  packages/preview/pintorita/0.1.4/pintorita.svg
  packages/preview/pintorita/0.1.4/pintorita.typ
  packages/preview/pintorita/0.1.4/typst.toml
Labels: update

#2072 dashy-todo:0.0.3
  packages/preview/dashy-todo/0.0.3/LICENSE
  packages/preview/dashy-todo/0.0.3/README.md
  packages/preview/dashy-todo/0.0.3/example.svg
  packages/preview/dashy-todo/0.0.3/example.typ
  packages/preview/dashy-todo/0.0.3/lib/side-margin.typ
  packages/preview/dashy-todo/0.0.3/lib/todo.typ
  packages/preview/dashy-todo/0.0.3/typst.toml
Labels: update

#2073 numty:0.0.5
  packages/preview/numty/0.0.5/typst.toml
Labels: update

#2074 harvard-gsas-thesis-oat:0.1.4
  packages/preview/harvard-gsas-thesis-oat/0.1.4/LICENSE
  packages/preview/harvard-gsas-thesis-oat/0.1.4/README.md
  packages/preview/harvard-gsas-thesis-oat/0.1.4/img/thumbnail.png
  packages/preview/harvard-gsas-thesis-oat/0.1.4/lib.typ
  packages/preview/harvard-gsas-thesis-oat/0.1.4/templates/main.typ
  packages/preview/harvard-gsas-thesis-oat/0.1.4/typst.toml
Labels: update

#2075 mannot:0.2.3
  packages/preview/mannot/0.2.3/LICENSE
  packages/preview/mannot/0.2.3/README.md
  packages/preview/mannot/0.2.3/docs/doc-template.typ
  packages/preview/mannot/0.2.3/docs/doc.pdf
  packages/preview/mannot/0.2.3/docs/doc.typ
  packages/preview/mannot/0.2.3/docs/tidy-style.typ
  packages/preview/mannot/0.2.3/examples/showcase.svg
  packages/preview/mannot/0.2.3/examples/showcase.typ
  packages/preview/mannot/0.2.3/examples/usage1.svg
  packages/preview/mannot/0.2.3/examples/usage1.typ
  packages/preview/mannot/0.2.3/examples/usage2.svg
  packages/preview/mannot/0.2.3/examples/usage2.typ
  packages/preview/mannot/0.2.3/examples/usage3.svg
  packages/preview/mannot/0.2.3/examples/usage3.typ
  packages/preview/mannot/0.2.3/examples/usage4.svg
  packages/preview/mannot/0.2.3/examples/usage4.typ
  packages/preview/mannot/0.2.3/examples/usage5.svg
  packages/preview/mannot/0.2.3/examples/usage5.typ
  packages/preview/mannot/0.2.3/src/annot.typ
  packages/preview/mannot/0.2.3/src/lib.typ
  packages/preview/mannot/0.2.3/src/mark.typ
  packages/preview/mannot/0.2.3/src/util.typ
  packages/preview/mannot/0.2.3/typst.toml
Labels: update

#2077 citegeist:0.1.0
  packages/preview/citegeist/0.1.0/LICENSE
  packages/preview/citegeist/0.1.0/README.md
  packages/preview/citegeist/0.1.0/citegeist.wasm
  packages/preview/citegeist/0.1.0/lib.typ
  packages/preview/citegeist/0.1.0/typst.toml
Labels: new

#2080 subpar:0.2.2
  packages/preview/subpar/0.2.2/CHANGELOG.md
  packages/preview/subpar/0.2.2/LICENSE
  packages/preview/subpar/0.2.2/README.md
  packages/preview/subpar/0.2.2/assets/i18n.toml
  packages/preview/subpar/0.2.2/assets/manual.pdf
  packages/preview/subpar/0.2.2/assets/showcase.png
  packages/preview/subpar/0.2.2/src/default.typ
  packages/preview/subpar/0.2.2/src/lib.typ
  packages/preview/subpar/0.2.2/src/util.typ
  packages/preview/subpar/0.2.2/typst.toml
Labels: update

#2079 ijimai:0.0.1
  packages/preview/ijimai/0.0.1/LICENSE
  packages/preview/ijimai/0.0.1/README.md
  packages/preview/ijimai/0.0.1/ijimai.typ
  packages/preview/ijimai/0.0.1/template/Jane Smith.jpg
  packages/preview/ijimai/0.0.1/template/John Doe.jpg
  packages/preview/ijimai/0.0.1/template/axes.svg
  packages/preview/ijimai/0.0.1/template/bibliography.bib
  packages/preview/ijimai/0.0.1/template/cylinder.svg
  packages/preview/ijimai/0.0.1/template/paper.toml
  packages/preview/ijimai/0.0.1/template/paper.typ
  packages/preview/ijimai/0.0.1/template/tetrahedron.svg
  packages/preview/ijimai/0.0.1/template/unir logo.svg
  packages/preview/ijimai/0.0.1/thumbnail.png
  packages/preview/ijimai/0.0.1/typst.toml
Labels: new

#2083 fractusist:0.3.0
  packages/preview/fractusist/0.3.0/LICENSE
  packages/preview/fractusist/0.3.0/README.md
  packages/preview/fractusist/0.3.0/examples/dragon-curve-ex.png
  packages/preview/fractusist/0.3.0/examples/dragon-curve-ex.typ
  packages/preview/fractusist/0.3.0/examples/hypotrochoid-ex.png
  packages/preview/fractusist/0.3.0/examples/hypotrochoid-ex.typ
  packages/preview/fractusist/0.3.0/examples/koch-snowflake-ex.png
  packages/preview/fractusist/0.3.0/examples/koch-snowflake-ex.typ
  packages/preview/fractusist/0.3.0/examples/pythagorean-tree-ex.png
  packages/preview/fractusist/0.3.0/examples/pythagorean-tree-ex.typ
  packages/preview/fractusist/0.3.0/examples/random-fractal-tree-ex.png
  packages/preview/fractusist/0.3.0/examples/random-fractal-tree-ex.typ
  packages/preview/fractusist/0.3.0/examples/sierpinski-triangle-ex.png
  packages/preview/fractusist/0.3.0/examples/sierpinski-triangle-ex.typ
  packages/preview/fractusist/0.3.0/src/iterative/fibonacci.typ
  packages/preview/fractusist/0.3.0/src/iterative/z-order.typ
  packages/preview/fractusist/0.3.0/src/lib.typ
  packages/preview/fractusist/0.3.0/src/lsystem/dragon.typ
  packages/preview/fractusist/0.3.0/src/lsystem/hilbert.typ
  packages/preview/fractusist/0.3.0/src/lsystem/koch.typ
  packages/preview/fractusist/0.3.0/src/lsystem/lsystem-lib.typ
  packages/preview/fractusist/0.3.0/src/lsystem/lsystem.typ
  packages/preview/fractusist/0.3.0/src/lsystem/sierpinski.typ
  packages/preview/fractusist/0.3.0/src/parametric/lissajous.typ
  packages/preview/fractusist/0.3.0/src/parametric/spirograph.typ
  packages/preview/fractusist/0.3.0/src/recursive/carpet.typ
  packages/preview/fractusist/0.3.0/src/recursive/tree.typ
  packages/preview/fractusist/0.3.0/typst.toml
Labels: update

#2084 codly:1.3.0
  packages/preview/codly/1.3.0/.gitignore
  packages/preview/codly/1.3.0/LICENSE
  packages/preview/codly/1.3.0/README.md
  packages/preview/codly/1.3.0/assets/annotations.png
  packages/preview/codly/1.3.0/assets/codly-disable.png
  packages/preview/codly/1.3.0/assets/codly-offset.png
  packages/preview/codly/1.3.0/assets/codly-range.png
  packages/preview/codly/1.3.0/assets/crab.png
  packages/preview/codly/1.3.0/assets/demo.png
  packages/preview/codly/1.3.0/assets/highlight-ref.png
  packages/preview/codly/1.3.0/assets/highlights.png
  packages/preview/codly/1.3.0/assets/line-ref.png
  packages/preview/codly/1.3.0/assets/offset-from.png
  packages/preview/codly/1.3.0/assets/smart-indent.png
  packages/preview/codly/1.3.0/bench/test-codly-12/main.typ
  packages/preview/codly/1.3.0/bench/test-codly-main/main.typ
  packages/preview/codly/1.3.0/codly.typ
  packages/preview/codly/1.3.0/docs.pdf
  packages/preview/codly/1.3.0/src/args.json
  packages/preview/codly/1.3.0/src/args.typ
  packages/preview/codly/1.3.0/src/lib.typ
  packages/preview/codly/1.3.0/src/typst-small.png
  packages/preview/codly/1.3.0/typst.toml
Labels: update

#2003 unofficial-fhict-document-template:1.1.3
  packages/preview/unofficial-fhict-document-template/1.1.3/LICENSE
  packages/preview/unofficial-fhict-document-template/1.1.3/README.md
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/DE-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/EN-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/ES-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/FR-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/NL-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/NOTICE
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/fontys-for-society.png
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/for-society.png
  packages/preview/unofficial-fhict-document-template/1.1.3/assets/language.yml
  packages/preview/unofficial-fhict-document-template/1.1.3/img/showcase-l.png
  packages/preview/unofficial-fhict-document-template/1.1.3/img/showcase-r.png
  packages/preview/unofficial-fhict-document-template/1.1.3/lib.typ
  packages/preview/unofficial-fhict-document-template/1.1.3/template/main.typ
  packages/preview/unofficial-fhict-document-template/1.1.3/typst.toml
Labels: update

#2085 tenv:0.1.2
  packages/preview/tenv/0.1.2/LICENSE
  packages/preview/tenv/0.1.2/README.md
  packages/preview/tenv/0.1.2/example.png
  packages/preview/tenv/0.1.2/lib.typ
  packages/preview/tenv/0.1.2/typst.toml
Labels: update

#2087 stonewall:0.2.0
  packages/preview/stonewall/0.2.0/LICENSE
  packages/preview/stonewall/0.2.0/README.md
  packages/preview/stonewall/0.2.0/example.typ
  packages/preview/stonewall/0.2.0/flags.png
  packages/preview/stonewall/0.2.0/stonewall.typ
  packages/preview/stonewall/0.2.0/typst.toml
Labels: update

#2086 tracl:0.5.2
  packages/preview/tracl/0.5.2/LICENSE
  packages/preview/tracl/0.5.2/README.md
  packages/preview/tracl/0.5.2/lib.typ
  packages/preview/tracl/0.5.2/template/association-for-computational-linguistics-blinky.csl
  packages/preview/tracl/0.5.2/template/main.typ
  packages/preview/tracl/0.5.2/thumbnail.png
  packages/preview/tracl/0.5.2/typst.toml
Labels: update
