Repository typst/packages, pull requests merged in 2025-01, with the labels that each got.

#1450 defined:0.1.0
  packages/preview/defined/0.1.0/LICENSE
  packages/preview/defined/0.1.0/README.md
  packages/preview/defined/0.1.0/src/defined.typ
  packages/preview/defined/0.1.0/src/lib.typ
  packages/preview/defined/0.1.0/src/utils.typ
  packages/preview/defined/0.1.0/typst.toml
Labels: new

#1462 mitex:0.2.5
  packages/preview/mitex/0.2.5/CHANGELOG.md
  packages/preview/mitex/0.2.5/LICENSE
  packages/preview/mitex/0.2.5/README.md
  packages/preview/mitex/0.2.5/examples/bench.typ
  packages/preview/mitex/0.2.5/examples/example.pdf
  packages/preview/mitex/0.2.5/examples/example.png
  packages/preview/mitex/0.2.5/examples/example.typ
  packages/preview/mitex/0.2.5/lib.typ
  packages/preview/mitex/0.2.5/mitex.typ
  packages/preview/mitex/0.2.5/mitex.wasm
  packages/preview/mitex/0.2.5/specs/README.md
  packages/preview/mitex/0.2.5/specs/latex/standard.typ
  packages/preview/mitex/0.2.5/specs/mod.typ
  packages/preview/mitex/0.2.5/specs/prelude.typ
  packages/preview/mitex/0.2.5/typst.toml
Labels: update

#1464 nonsense:0.1.0
  packages/preview/nonsense/0.1.0/LICENSE
  packages/preview/nonsense/0.1.0/README.md
  packages/preview/nonsense/0.1.0/lib.typ
  packages/preview/nonsense/0.1.0/template/main.typ
  packages/preview/nonsense/0.1.0/thumbnail.png
  packages/preview/nonsense/0.1.0/typst.toml
Labels: new

#1453 fancy-affil:0.1.0
  packages/preview/fancy-affil/0.1.0/README.md
  packages/preview/fancy-affil/0.1.0/src/affiliation.typ
  packages/preview/fancy-affil/0.1.0/src/lib.typ
  packages/preview/fancy-affil/0.1.0/tests/tests.typ
  packages/preview/fancy-affil/0.1.0/typst.toml
Labels: new

#1466 ez-today:0.2.0
  packages/preview/ez-today/0.2.0/LICENSE
  packages/preview/ez-today/0.2.0/README.md
  packages/preview/ez-today/0.2.0/examples/example.typ
  packages/preview/ez-today/0.2.0/ez-today.typ
  packages/preview/ez-today/0.2.0/typst.toml
Labels: update

#1467 jumble:0.0.1
  packages/preview/jumble/0.0.1/LICENSE
  packages/preview/jumble/0.0.1/README.md
  packages/preview/jumble/0.0.1/gallery.bash
  packages/preview/jumble/0.0.1/gallery/readme_banner.typ
  packages/preview/jumble/0.0.1/gallery/readme_banner_dark.svg
  packages/preview/jumble/0.0.1/gallery/readme_banner_default.svg
  packages/preview/jumble/0.0.1/gallery/readme_banner_light.svg
  packages/preview/jumble/0.0.1/manual.pdf
  packages/preview/jumble/0.0.1/manual.typ
  packages/preview/jumble/0.0.1/src/base.typ
  packages/preview/jumble/0.0.1/src/lib.typ
  packages/preview/jumble/0.0.1/src/md.typ
  packages/preview/jumble/0.0.1/src/misc.typ
  packages/preview/jumble/0.0.1/src/sha.typ
  packages/preview/jumble/0.0.1/src/utils.typ
  packages/preview/jumble/0.0.1/typst.toml
Labels: new

#1468 derive-it:0.1.2
  packages/preview/derive-it/0.1.2/LICENSE
  packages/preview/derive-it/0.1.2/README.md
  packages/preview/derive-it/0.1.2/examples/example.pdf
  packages/preview/derive-it/0.1.2/examples/example.png
  packages/preview/derive-it/0.1.2/examples/example.typ
  packages/preview/derive-it/0.1.2/lib.typ
  packages/preview/derive-it/0.1.2/typst.toml
Labels: update

#1469 touying-unistra-pristine:1.3.0
  packages/preview/touying-unistra-pristine/1.3.0/CHANGELOG.md
  packages/preview/touying-unistra-pristine/1.3.0/LICENSE
  packages/preview/touying-unistra-pristine/1.3.0/README.md
  packages/preview/touying-unistra-pristine/1.3.0/assets/thumbnail.webp
  packages/preview/touying-unistra-pristine/1.3.0/assets/unistra.svg
  packages/preview/touying-unistra-pristine/1.3.0/src/admonition.typ
  packages/preview/touying-unistra-pristine/1.3.0/src/colors.typ
  packages/preview/touying-unistra-pristine/1.3.0/src/lib.typ
  packages/preview/touying-unistra-pristine/1.3.0/src/unistra.typ
  packages/preview/touying-unistra-pristine/1.3.0/template/template.typ
  packages/preview/touying-unistra-pristine/1.3.0/template/unistra.svg
  packages/preview/touying-unistra-pristine/1.3.0/typst.toml
Labels: update

#1471 orange-book:0.5.0
  packages/preview/orange-book/0.5.0/LICENSE
  packages/preview/orange-book/0.5.0/README.md
  packages/preview/orange-book/0.5.0/lib.typ
  packages/preview/orange-book/0.5.0/my-index.typ
  packages/preview/orange-book/0.5.0/my-outline.typ
  packages/preview/orange-book/0.5.0/template/background.svg
  packages/preview/orange-book/0.5.0/template/creodocs_logo.svg
  packages/preview/orange-book/0.5.0/template/main.typ
  packages/preview/orange-book/0.5.0/template/orange1.jpg
  packages/preview/orange-book/0.5.0/template/orange2.jpg
  packages/preview/orange-book/0.5.0/template/orange3.jpg
  packages/preview/orange-book/0.5.0/template/placeholder.jpg
  packages/preview/orange-book/0.5.0/template/sample.bib
  packages/preview/orange-book/0.5.0/theorems.typ
  packages/preview/orange-book/0.5.0/thumbnail.png
  packages/preview/orange-book/0.5.0/typst.toml
Labels: update

#1472 colorful-boxes:1.4.1
  packages/preview/colorful-boxes/1.4.1/LICENSE
  packages/preview/colorful-boxes/1.4.1/README.md
  packages/preview/colorful-boxes/1.4.1/background.svg
  packages/preview/colorful-boxes/1.4.1/examples/colorbox.pdf
  packages/preview/colorful-boxes/1.4.1/examples/colorbox.png
  packages/preview/colorful-boxes/1.4.1/examples/colorbox.typ
  packages/preview/colorful-boxes/1.4.1/examples/outline-colorbox.pdf
  packages/preview/colorful-boxes/1.4.1/examples/outline-colorbox.png
  packages/preview/colorful-boxes/1.4.1/examples/outline-colorbox.typ
  packages/preview/colorful-boxes/1.4.1/examples/slanted-colorbox.pdf
  packages/preview/colorful-boxes/1.4.1/examples/slanted-colorbox.png
  packages/preview/colorful-boxes/1.4.1/examples/slanted-colorbox.typ
  packages/preview/colorful-boxes/1.4.1/examples/stickybox.pdf
  packages/preview/colorful-boxes/1.4.1/examples/stickybox.png
  packages/preview/colorful-boxes/1.4.1/examples/stickybox.typ
  packages/preview/colorful-boxes/1.4.1/lib.typ
  packages/preview/colorful-boxes/1.4.1/tape.svg
  packages/preview/colorful-boxes/1.4.1/typst.toml
Labels: update

#1473 ourchat:0.1.0
  packages/preview/ourchat/0.1.0/LICENSE
  packages/preview/ourchat/0.1.0/README.md
  packages/preview/ourchat/0.1.0/examples/custom.svg
  packages/preview/ourchat/0.1.0/examples/custom.typ
  packages/preview/ourchat/0.1.0/examples/simple.svg
  packages/preview/ourchat/0.1.0/examples/simple.typ
  packages/preview/ourchat/0.1.0/src/default-profile.png
  packages/preview/ourchat/0.1.0/src/lib.typ
  packages/preview/ourchat/0.1.0/typst.toml
Labels: new

#1474 metalogo:1.2.0
  packages/preview/metalogo/1.2.0/LICENSE
  packages/preview/metalogo/1.2.0/README.md
  packages/preview/metalogo/1.2.0/demo.svg
  packages/preview/metalogo/1.2.0/demo.typ
  packages/preview/metalogo/1.2.0/lib.typ
  packages/preview/metalogo/1.2.0/metalogo.typ
  packages/preview/metalogo/1.2.0/typst.toml
Labels: update

#1475 modern-cug-thesis:0.2.4
  packages/preview/modern-cug-thesis/0.2.4/LICENSE
  packages/preview/modern-cug-thesis/0.2.4/README.md
  packages/preview/modern-cug-thesis/0.2.4/layouts/appendix.typ
  packages/preview/modern-cug-thesis/0.2.4/layouts/doc.typ
  packages/preview/modern-cug-thesis/0.2.4/layouts/mainmatter.typ
  packages/preview/modern-cug-thesis/0.2.4/lib.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/fonts-display-page.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/notation.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/abstract-en.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/abstract.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/acknowledgement.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/cover.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/declaration.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/list-of-defence-commitee.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/list-of-figures-tables.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/outline.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/resume.typ
  packages/preview/modern-cug-thesis/0.2.4/pages/postgraduate/titlepage.typ
  packages/preview/modern-cug-thesis/0.2.4/template/chapters/chapter1.typ
  packages/preview/modern-cug-thesis/0.2.4/template/chapters/intro.typ
  packages/preview/modern-cug-thesis/0.2.4/template/images/A-1.1.2校徽图案.jpg
  packages/preview/modern-cug-thesis/0.2.4/template/images/示意图1.png
  packages/preview/modern-cug-thesis/0.2.4/template/ref.bib
  packages/preview/modern-cug-thesis/0.2.4/template/thesis.typ
  packages/preview/modern-cug-thesis/0.2.4/thumbnail.png
  packages/preview/modern-cug-thesis/0.2.4/typst.toml
  packages/preview/modern-cug-thesis/0.2.4/utils/anonymous-info.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/bilingual-bibliography.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/custom-cuti.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/custom-heading.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/custom-numbering.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/custom-tablex.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/datetime-display.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/double-underline.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/gb-t-7714-2005-numeric-cug.csl
  packages/preview/modern-cug-thesis/0.2.4/utils/hline.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/indent.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/invisible-heading.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/justify-text.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/style.typ
  packages/preview/modern-cug-thesis/0.2.4/utils/unpairs.typ
Labels: update

#1476 tblr:0.3.1
  packages/preview/tblr/0.3.1/LICENSE
  packages/preview/tblr/0.3.1/README.md
  packages/preview/tblr/0.3.1/examples/booktabs-2.svg
  packages/preview/tblr/0.3.1/examples/booktabs-2.typ
  packages/preview/tblr/0.3.1/examples/booktabs.svg
  packages/preview/tblr/0.3.1/examples/booktabs.typ
  packages/preview/tblr/0.3.1/examples/decimal-align.svg
  packages/preview/tblr/0.3.1/examples/decimal-align.typ
  packages/preview/tblr/0.3.1/examples/general-align.svg
  packages/preview/tblr/0.3.1/examples/general-align.typ
  packages/preview/tblr/0.3.1/examples/grant-spend.svg
  packages/preview/tblr/0.3.1/examples/grant-spend.typ
  packages/preview/tblr/0.3.1/examples/population-2.svg
  packages/preview/tblr/0.3.1/examples/population-2.typ
  packages/preview/tblr/0.3.1/examples/population.svg
  packages/preview/tblr/0.3.1/examples/population.typ
  packages/preview/tblr/0.3.1/tblr.typ
  packages/preview/tblr/0.3.1/typst.toml
Labels: update

#1478 kouhu:0.2.0
  packages/preview/kouhu/0.2.0/LICENSE
  packages/preview/kouhu/0.2.0/README.md
  packages/preview/kouhu/0.2.0/data/zhlipsum.json
  packages/preview/kouhu/0.2.0/doc/manual.pdf
  packages/preview/kouhu/0.2.0/doc/manual.typ
  packages/preview/kouhu/0.2.0/lib.typ
  packages/preview/kouhu/0.2.0/typst.toml
  packages/preview/kouhu/0.2.0/utils/convert_from_zhlipsum.py
Labels: update

#1479 typographix-polytechnique-reports:0.1.6
  packages/preview/typographix-polytechnique-reports/0.1.6/.gitignore
  packages/preview/typographix-polytechnique-reports/0.1.6/CONTRIBUTING.md
  packages/preview/typographix-polytechnique-reports/0.1.6/LICENSE
  packages/preview/typographix-polytechnique-reports/0.1.6/README.md
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/README.md
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/armes.svg
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/example.bib
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/filet-court.svg
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/filet-long.svg
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/logo-x-ip-paris.svg
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/logo-x.svg
  packages/preview/typographix-polytechnique-reports/0.1.6/assets/typst.png
  packages/preview/typographix-polytechnique-reports/0.1.6/cover.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/guide.pdf
  packages/preview/typographix-polytechnique-reports/0.1.6/guide.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/heading.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/outline.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/page.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/polytechnique.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/report-thumbnail.png
  packages/preview/typographix-polytechnique-reports/0.1.6/template/report.typ
  packages/preview/typographix-polytechnique-reports/0.1.6/typst.toml
Labels: update

#1521 Allow CC-BY, CC-BY-SA, and CC0 licenses
  README.md
  bundler/Cargo.lock
  bundler/Cargo.toml
  bundler/src/main.rs
Labels: meta

#1482 vienna-tech:0.1.3
  packages/preview/vienna-tech/0.1.3/CHANGELOG.md
  packages/preview/vienna-tech/0.1.3/LICENSE
  packages/preview/vienna-tech/0.1.3/README.md
  packages/preview/vienna-tech/0.1.3/src/lib.typ
  packages/preview/vienna-tech/0.1.3/template/abstract.typ
  packages/preview/vienna-tech/0.1.3/template/appendix.typ
  packages/preview/vienna-tech/0.1.3/template/assets/refs.bib
  packages/preview/vienna-tech/0.1.3/template/assets/tuw.jpg
  packages/preview/vienna-tech/0.1.3/template/main.typ
  packages/preview/vienna-tech/0.1.3/template/sections.typ
  packages/preview/vienna-tech/0.1.3/thumbnail.png
  packages/preview/vienna-tech/0.1.3/typst.toml
Labels: update

#1484 codly:1.2.0
  packages/preview/codly/1.2.0/.gitignore
  packages/preview/codly/1.2.0/LICENSE
  packages/preview/codly/1.2.0/README.md
  packages/preview/codly/1.2.0/assets/annotations.png
  packages/preview/codly/1.2.0/assets/codly-disable.png
  packages/preview/codly/1.2.0/assets/codly-offset.png
  packages/preview/codly/1.2.0/assets/codly-range.png
  packages/preview/codly/1.2.0/assets/crab.png
  packages/preview/codly/1.2.0/assets/demo.png
  packages/preview/codly/1.2.0/assets/highlight-ref.png
  packages/preview/codly/1.2.0/assets/highlights.png
  packages/preview/codly/1.2.0/assets/line-ref.png
  packages/preview/codly/1.2.0/assets/offset-from.png
  packages/preview/codly/1.2.0/assets/smart-indent.png
  packages/preview/codly/1.2.0/codly.typ
  packages/preview/codly/1.2.0/docs.pdf
  packages/preview/codly/1.2.0/src/args.json
  packages/preview/codly/1.2.0/src/args.typ
  packages/preview/codly/1.2.0/src/lib.typ
  packages/preview/codly/1.2.0/src/typst-small.png
  packages/preview/codly/1.2.0/typst.toml
Labels: update

#1485 ansi-render:0.8.0
  packages/preview/ansi-render/0.8.0/CHANGELOG.md
  packages/preview/ansi-render/0.8.0/LICENSE
  packages/preview/ansi-render/0.8.0/README.md
  packages/preview/ansi-render/0.8.0/lib.typ
  packages/preview/ansi-render/0.8.0/typst.toml
Labels: update

#1492 basic-resume:0.2.3
  packages/preview/basic-resume/0.2.3/CHANGELOG.md
  packages/preview/basic-resume/0.2.3/LICENSE
  packages/preview/basic-resume/0.2.3/README.md
  packages/preview/basic-resume/0.2.3/docs/manual.pdf
  packages/preview/basic-resume/0.2.3/src/lib.typ
  packages/preview/basic-resume/0.2.3/src/resume.typ
  packages/preview/basic-resume/0.2.3/template/main.typ
  packages/preview/basic-resume/0.2.3/thumbnail.png
  packages/preview/basic-resume/0.2.3/typst.toml
Labels: update

#1496 quick-sip:0.1.1
  packages/preview/quick-sip/0.1.1/LICENSE
  packages/preview/quick-sip/0.1.1/README.md
  packages/preview/quick-sip/0.1.1/lib.typ
  packages/preview/quick-sip/0.1.1/template/main.typ
  packages/preview/quick-sip/0.1.1/thumbnail.png
  packages/preview/quick-sip/0.1.1/typst.toml
Labels: update

#1497 tada:0.2.0
  packages/preview/tada/0.2.0/LICENSE
  packages/preview/tada/0.2.0/README.md
  packages/preview/tada/0.2.0/lib.typ
  packages/preview/tada/0.2.0/manual.pdf
  packages/preview/tada/0.2.0/src/display.typ
  packages/preview/tada/0.2.0/src/helpers.typ
  packages/preview/tada/0.2.0/src/ops.typ
  packages/preview/tada/0.2.0/src/tabledata.typ
  packages/preview/tada/0.2.0/typst.toml
Labels: update

#1520 unofficial-fhict-document-template:1.1.2
  packages/preview/unofficial-fhict-document-template/1.1.2/LICENSE
  packages/preview/unofficial-fhict-document-template/1.1.2/README.md
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/DE-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/EN-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/ES-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/FR-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/NL-flag.svg
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/NOTICE
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/fontys-for-society.png
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/for-society.png
  packages/preview/unofficial-fhict-document-template/1.1.2/assets/language.yml
  packages/preview/unofficial-fhict-document-template/1.1.2/img/showcase-l.png
  packages/preview/unofficial-fhict-document-template/1.1.2/img/showcase-r.png
  packages/preview/unofficial-fhict-document-template/1.1.2/lib.typ
  packages/preview/unofficial-fhict-document-template/1.1.2/template/main.typ
  packages/preview/unofficial-fhict-document-template/1.1.2/typst.toml
Labels: update

#1502 fractus:0.1.0
  packages/preview/fractus/0.1.0/LICENSE
  packages/preview/fractus/0.1.0/README.md
  packages/preview/fractus/0.1.0/lib.typ
  packages/preview/fractus/0.1.0/typst.toml
Labels: new

#1504 genealotree:0.2.0
  packages/preview/genealotree/0.2.0/LICENSE
  packages/preview/genealotree/0.2.0/README.md
  packages/preview/genealotree/0.2.0/calc-functions.typ
  packages/preview/genealotree/0.2.0/draw-functions.typ
  packages/preview/genealotree/0.2.0/genealotree.typ
  packages/preview/genealotree/0.2.0/typst.toml
Labels: update

#1507 fletcher:0.5.4
  packages/preview/fletcher/0.5.4/LICENSE
  packages/preview/fletcher/0.5.4/README.md
  packages/preview/fletcher/0.5.4/docs/gallery/1-commutative.svg
  packages/preview/fletcher/0.5.4/docs/gallery/1-commutative.typ
  packages/preview/fletcher/0.5.4/docs/gallery/2-algebra-cube.svg
  packages/preview/fletcher/0.5.4/docs/gallery/2-algebra-cube.typ
  packages/preview/fletcher/0.5.4/docs/gallery/3-ml-architecture.svg
  packages/preview/fletcher/0.5.4/docs/gallery/3-ml-architecture.typ
  packages/preview/fletcher/0.5.4/docs/gallery/4-io-flowchart.svg
  packages/preview/fletcher/0.5.4/docs/gallery/4-io-flowchart.typ
  packages/preview/fletcher/0.5.4/docs/gallery/5-digraph.svg
  packages/preview/fletcher/0.5.4/docs/gallery/5-digraph.typ
  packages/preview/fletcher/0.5.4/docs/gallery/6-node-groups.svg
  packages/preview/fletcher/0.5.4/docs/gallery/6-node-groups.typ
  packages/preview/fletcher/0.5.4/docs/gallery/7-uml-diagram.svg
  packages/preview/fletcher/0.5.4/docs/gallery/7-uml-diagram.typ
  packages/preview/fletcher/0.5.4/docs/manual.pdf
  packages/preview/fletcher/0.5.4/docs/manual.typ
  packages/preview/fletcher/0.5.4/docs/readme-examples/1-first-isomorphism-theorem-dark.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/1-first-isomorphism-theorem-light.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/1-first-isomorphism-theorem.typ
  packages/preview/fletcher/0.5.4/docs/readme-examples/2-flowchart-trap-dark.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/2-flowchart-trap-light.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/2-flowchart-trap.typ
  packages/preview/fletcher/0.5.4/docs/readme-examples/3-state-machine-dark.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/3-state-machine-light.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/3-state-machine.typ
  packages/preview/fletcher/0.5.4/docs/readme-examples/4-feynman-diagram-dark.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/4-feynman-diagram-light.svg
  packages/preview/fletcher/0.5.4/docs/readme-examples/4-feynman-diagram.typ
  packages/preview/fletcher/0.5.4/docs/style.typ
  packages/preview/fletcher/0.5.4/src/coords.typ
  packages/preview/fletcher/0.5.4/src/default-marks.typ
  packages/preview/fletcher/0.5.4/src/deps.typ
  packages/preview/fletcher/0.5.4/src/diagram.typ
  packages/preview/fletcher/0.5.4/src/draw.typ
  packages/preview/fletcher/0.5.4/src/edge.typ
  packages/preview/fletcher/0.5.4/src/exports.typ
  packages/preview/fletcher/0.5.4/src/marks.typ
  packages/preview/fletcher/0.5.4/src/node.typ
  packages/preview/fletcher/0.5.4/src/shapes.typ
  packages/preview/fletcher/0.5.4/src/utils.typ
  packages/preview/fletcher/0.5.4/typst.toml
Labels: update

#1509 fancy-units:0.1.0
  packages/preview/fancy-units/0.1.0/LICENSE
  packages/preview/fancy-units/0.1.0/README.md
  packages/preview/fancy-units/0.1.0/docs/examples.svg
  packages/preview/fancy-units/0.1.0/docs/examples.typ
  packages/preview/fancy-units/0.1.0/docs/manual.pdf
  packages/preview/fancy-units/0.1.0/docs/manual.typ
  packages/preview/fancy-units/0.1.0/docs/my-tidy.typ
  packages/preview/fancy-units/0.1.0/src/content.typ
  packages/preview/fancy-units/0.1.0/src/lib.typ
  packages/preview/fancy-units/0.1.0/src/number.typ
  packages/preview/fancy-units/0.1.0/src/unit.typ
  packages/preview/fancy-units/0.1.0/typst.toml
Labels: new

#1510 exmllent:0.1.0, handy-dora:0.1.0 and zebraw:0.1.0
  packages/preview/exmllent/0.1.0/LICENSE
  packages/preview/exmllent/0.1.0/README.md
  packages/preview/exmllent/0.1.0/lib.typ
  packages/preview/exmllent/0.1.0/parser.typ
  packages/preview/exmllent/0.1.0/typst.toml
  packages/preview/handy-dora/0.1.0/LICENSE
  packages/preview/handy-dora/0.1.0/README.md
  packages/preview/handy-dora/0.1.0/handy_dora.wasm
  packages/preview/handy-dora/0.1.0/lib.typ
  packages/preview/handy-dora/0.1.0/mod.typ
  packages/preview/handy-dora/0.1.0/typst.toml
  packages/preview/zebraw/0.1.0/LICENSE
  packages/preview/zebraw/0.1.0/README.md
  packages/preview/zebraw/0.1.0/assets/example1.svg
  packages/preview/zebraw/0.1.0/assets/example2.svg
  packages/preview/zebraw/0.1.0/assets/example3.svg
  packages/preview/zebraw/0.1.0/assets/line-spacing.svg
  packages/preview/zebraw/0.1.0/lib.typ
  packages/preview/zebraw/0.1.0/typst.toml
Labels: new

#1490 typ2anki:0.1.0
  packages/preview/typ2anki/0.1.0/LICENSE
  packages/preview/typ2anki/0.1.0/README.md
  packages/preview/typ2anki/0.1.0/src/assets/anki.svg
  packages/preview/typ2anki/0.1.0/src/lib.typ
  packages/preview/typ2anki/0.1.0/typst.toml
Labels: new

#1470 tatras-ieee:0.1.0
  packages/preview/tatras-ieee/0.1.0/LICENSE
  packages/preview/tatras-ieee/0.1.0/README.md
  packages/preview/tatras-ieee/0.1.0/lib.typ
  packages/preview/tatras-ieee/0.1.0/template/main.typ
  packages/preview/tatras-ieee/0.1.0/template/refs.bib
  packages/preview/tatras-ieee/0.1.0/thumbnail.png
  packages/preview/tatras-ieee/0.1.0/typst.toml
Labels: new

#1463 swe-cv:1.0.0
  packages/preview/swe-cv/1.0.0/LICENSE
  packages/preview/swe-cv/1.0.0/README.md
  packages/preview/swe-cv/1.0.0/lib.typ
  packages/preview/swe-cv/1.0.0/template/configuration.yaml
  packages/preview/swe-cv/1.0.0/template/main.typ
  packages/preview/swe-cv/1.0.0/thumbnail.png
  packages/preview/swe-cv/1.0.0/typst.toml
Labels: new

#1481 plotsy-3d:0.1.0
  packages/preview/plotsy-3d/0.1.0/LICENSE
  packages/preview/plotsy-3d/0.1.0/README.md
  packages/preview/plotsy-3d/0.1.0/examples/examples.pdf
  packages/preview/plotsy-3d/0.1.0/examples/examples.typ
  packages/preview/plotsy-3d/0.1.0/examples/examples1.png
  packages/preview/plotsy-3d/0.1.0/examples/examples10.png
  packages/preview/plotsy-3d/0.1.0/examples/examples2.png
  packages/preview/plotsy-3d/0.1.0/examples/examples3.png
  packages/preview/plotsy-3d/0.1.0/examples/examples4.png
  packages/preview/plotsy-3d/0.1.0/examples/examples5.png
  packages/preview/plotsy-3d/0.1.0/examples/examples6.png
  packages/preview/plotsy-3d/0.1.0/examples/examples7.png
  packages/preview/plotsy-3d/0.1.0/examples/examples8.png
  packages/preview/plotsy-3d/0.1.0/examples/examples9.png
  packages/preview/plotsy-3d/0.1.0/plotsy-3d.typ
  packages/preview/plotsy-3d/0.1.0/typst.toml
Labels: new

#1513 hydra:0.5.2
  packages/preview/hydra/0.5.2/CHANGELOG.md
  packages/preview/hydra/0.5.2/LICENSE
  packages/preview/hydra/0.5.2/README.md
  packages/preview/hydra/0.5.2/doc/manual.pdf
  packages/preview/hydra/0.5.2/examples/example.png
  packages/preview/hydra/0.5.2/src/core.typ
  packages/preview/hydra/0.5.2/src/lib.typ
  packages/preview/hydra/0.5.2/src/selectors.typ
  packages/preview/hydra/0.5.2/src/util.typ
  packages/preview/hydra/0.5.2/src/util/assert.typ
  packages/preview/hydra/0.5.2/src/util/core.typ
  packages/preview/hydra/0.5.2/typst.toml
Labels: update

#1514 basic-report:0.1.0
  packages/preview/basic-report/0.1.0/LICENSE
  packages/preview/basic-report/0.1.0/README.md
  packages/preview/basic-report/0.1.0/lib.typ
  packages/preview/basic-report/0.1.0/template/assets/aerospace-engineering.png
  packages/preview/basic-report/0.1.0/template/main.typ
  packages/preview/basic-report/0.1.0/thumbnail.png
  packages/preview/basic-report/0.1.0/titlepage.typ
  packages/preview/basic-report/0.1.0/typst.toml
Labels: new

#1517 basalt-backlinks:0.1.1
  packages/preview/basalt-backlinks/0.1.1/LICENSE
  packages/preview/basalt-backlinks/0.1.1/README.md
  packages/preview/basalt-backlinks/0.1.1/src/backlinks.typ
  packages/preview/basalt-backlinks/0.1.1/src/exports.typ
  packages/preview/basalt-backlinks/0.1.1/typst.toml
Labels: update

#1519 abbr:0.1.1
  packages/preview/abbr/0.1.1/LICENSE
  packages/preview/abbr/0.1.1/README.md
  packages/preview/abbr/0.1.1/abbr.typ
  packages/preview/abbr/0.1.1/example.png
  packages/preview/abbr/0.1.1/example.typ
  packages/preview/abbr/0.1.1/typst.toml
Labels: update

#1522 htlwienwest-da:0.2.1
  packages/preview/htlwienwest-da/0.2.1/LICENSE
  packages/preview/htlwienwest-da/0.2.1/README.md
  packages/preview/htlwienwest-da/0.2.1/blob/p01.png
  packages/preview/htlwienwest-da/0.2.1/blob/p08.png
  packages/preview/htlwienwest-da/0.2.1/blob/p12.png
  packages/preview/htlwienwest-da/0.2.1/blob/p19.png
  packages/preview/htlwienwest-da/0.2.1/lib.typ
  packages/preview/htlwienwest-da/0.2.1/lib/assertions.typ
  packages/preview/htlwienwest-da/0.2.1/lib/elements.typ
  packages/preview/htlwienwest-da/0.2.1/lib/fontchecker.typ
  packages/preview/htlwienwest-da/0.2.1/lib/images/HTLWienWest.png
  packages/preview/htlwienwest-da/0.2.1/lib/pages/arbeitsaufteilung.typ
  packages/preview/htlwienwest-da/0.2.1/lib/pages/deckblatt.typ
  packages/preview/htlwienwest-da/0.2.1/lib/pages/dokumentation.typ
  packages/preview/htlwienwest-da/0.2.1/lib/pages/eidesstattliche.typ
  packages/preview/htlwienwest-da/0.2.1/lib/settings.typ
  packages/preview/htlwienwest-da/0.2.1/lib/template.typ
  packages/preview/htlwienwest-da/0.2.1/template/abbildungen/demoAbb.jpeg
  packages/preview/htlwienwest-da/0.2.1/template/abbildungen/typst.svg
  packages/preview/htlwienwest-da/0.2.1/template/anhang.typ
  packages/preview/htlwienwest-da/0.2.1/template/diplomarbeit.typ
  packages/preview/htlwienwest-da/0.2.1/template/literaturverzeichnis.bib
  packages/preview/htlwienwest-da/0.2.1/thumbnail.png
  packages/preview/htlwienwest-da/0.2.1/typst.toml
Labels: update

#1523 glossy:0.5.2
  packages/preview/glossy/0.5.2/.gitignore
  packages/preview/glossy/0.5.2/LICENSE
  packages/preview/glossy/0.5.2/README.md
  packages/preview/glossy/0.5.2/bin/autotest.sh
  packages/preview/glossy/0.5.2/lib.typ
  packages/preview/glossy/0.5.2/src/gloss.typ
  packages/preview/glossy/0.5.2/src/schemas.typ
  packages/preview/glossy/0.5.2/src/themes.typ
  packages/preview/glossy/0.5.2/src/themes/academic.typ
  packages/preview/glossy/0.5.2/src/themes/basic.typ
  packages/preview/glossy/0.5.2/src/themes/chicago-index.typ
  packages/preview/glossy/0.5.2/src/themes/compact.typ
  packages/preview/glossy/0.5.2/src/themes/table.typ
  packages/preview/glossy/0.5.2/src/themes/twocol.typ
  packages/preview/glossy/0.5.2/src/utils.typ
  packages/preview/glossy/0.5.2/tests/abbreviated-syntax/ref/1.png
  packages/preview/glossy/0.5.2/tests/abbreviated-syntax/test.typ
  packages/preview/glossy/0.5.2/tests/demo/ref/1.png
  packages/preview/glossy/0.5.2/tests/demo/test.typ
  packages/preview/glossy/0.5.2/tests/determine-article/ref/1.png
  packages/preview/glossy/0.5.2/tests/determine-article/test.typ
  packages/preview/glossy/0.5.2/tests/format-term/ref/1.png
  packages/preview/glossy/0.5.2/tests/format-term/test.typ
  packages/preview/glossy/0.5.2/tests/forward-links/ref/1.png
  packages/preview/glossy/0.5.2/tests/forward-links/test.typ
  packages/preview/glossy/0.5.2/tests/group-specified/abbreviations.json
  packages/preview/glossy/0.5.2/tests/group-specified/ref/1.png
  packages/preview/glossy/0.5.2/tests/group-specified/ref/2.png
  packages/preview/glossy/0.5.2/tests/group-specified/ref/3.png
  packages/preview/glossy/0.5.2/tests/group-specified/ref/4.png
  packages/preview/glossy/0.5.2/tests/group-specified/test.typ
  packages/preview/glossy/0.5.2/tests/no-sort/glossary.yml
  packages/preview/glossy/0.5.2/tests/no-sort/ref/1.png
  packages/preview/glossy/0.5.2/tests/no-sort/test.typ
  packages/preview/glossy/0.5.2/tests/page-numbers/ref/1.png
  packages/preview/glossy/0.5.2/tests/page-numbers/ref/2.png
  packages/preview/glossy/0.5.2/tests/page-numbers/ref/3.png
  packages/preview/glossy/0.5.2/tests/page-numbers/ref/4.png
  packages/preview/glossy/0.5.2/tests/page-numbers/test.typ
  packages/preview/glossy/0.5.2/tests/pluralize/test.typ
  packages/preview/glossy/0.5.2/tests/refs-exhaustive/test.typ
  packages/preview/glossy/0.5.2/tests/sorting/ref/1.png
  packages/preview/glossy/0.5.2/tests/sorting/test.typ
  packages/preview/glossy/0.5.2/tests/theme-gallery/ref/1.png
  packages/preview/glossy/0.5.2/tests/theme-gallery/test.typ
  packages/preview/glossy/0.5.2/tests/utf-handling/glossary.yml
  packages/preview/glossy/0.5.2/tests/utf-handling/ref/1.png
  packages/preview/glossy/0.5.2/tests/utf-handling/test.typ
  packages/preview/glossy/0.5.2/themeshots.png
  packages/preview/glossy/0.5.2/thumbnail.png
  packages/preview/glossy/0.5.2/typst.toml
Labels: update

#1524 accelerated-jacow:0.1.2
  packages/preview/accelerated-jacow/0.1.2/LICENSE
  packages/preview/accelerated-jacow/0.1.2/README.md
  packages/preview/accelerated-jacow/0.1.2/jacow.csl
  packages/preview/accelerated-jacow/0.1.2/jacow.typ
  packages/preview/accelerated-jacow/0.1.2/template/paper.typ
  packages/preview/accelerated-jacow/0.1.2/template/references.bib
  packages/preview/accelerated-jacow/0.1.2/template/writer.svg
  packages/preview/accelerated-jacow/0.1.2/thumbnail.webp
  packages/preview/accelerated-jacow/0.1.2/typst.toml
Labels: update

#1525 run-liners:0.1.0
  packages/preview/run-liners/0.1.0/.gitignore
  packages/preview/run-liners/0.1.0/LICENSE
  packages/preview/run-liners/0.1.0/README.md
  packages/preview/run-liners/0.1.0/bin/autotest.sh
  packages/preview/run-liners/0.1.0/docs/manual.pdf
  packages/preview/run-liners/0.1.0/docs/manual.typ
  packages/preview/run-liners/0.1.0/lib.typ
  packages/preview/run-liners/0.1.0/src/main.typ
  packages/preview/run-liners/0.1.0/tests/all-calls/ref/1.png
  packages/preview/run-liners/0.1.0/tests/all-calls/test.typ
  packages/preview/run-liners/0.1.0/tests/thumbnail/ref/1.png
  packages/preview/run-liners/0.1.0/tests/thumbnail/test.typ
  packages/preview/run-liners/0.1.0/thumbnail.png
  packages/preview/run-liners/0.1.0/typst.toml
Labels: new

#1512 ailab-isetbz:0.1.0
  packages/preview/ailab-isetbz/0.1.0/LICENSE
  packages/preview/ailab-isetbz/0.1.0/README.md
  packages/preview/ailab-isetbz/0.1.0/common/isetbz.jpg
  packages/preview/ailab-isetbz/0.1.0/lib.typ
  packages/preview/ailab-isetbz/0.1.0/template/Biblio.bib
  packages/preview/ailab-isetbz/0.1.0/template/main.typ
  packages/preview/ailab-isetbz/0.1.0/thumbnail.png
  packages/preview/ailab-isetbz/0.1.0/typst.toml
Labels: new

#1529 soviet-matrix:0.2.0
  packages/preview/soviet-matrix/0.2.0/LICENSE
  packages/preview/soviet-matrix/0.2.0/README.md
  packages/preview/soviet-matrix/0.2.0/demo.gif
  packages/preview/soviet-matrix/0.2.0/lib.typ
  packages/preview/soviet-matrix/0.2.0/mino/LICENSE
  packages/preview/soviet-matrix/0.2.0/mino/README.md
  packages/preview/soviet-matrix/0.2.0/mino/tetris.typ
  packages/preview/soviet-matrix/0.2.0/template/main.typ
  packages/preview/soviet-matrix/0.2.0/thumbnail.png
  packages/preview/soviet-matrix/0.2.0/typst.toml
Labels: update

#1531 use-tabler-icons:0.8.0
  packages/preview/use-tabler-icons/0.8.0/LICENSE
  packages/preview/use-tabler-icons/0.8.0/README.md
  packages/preview/use-tabler-icons/0.8.0/assets/splash.svg
  packages/preview/use-tabler-icons/0.8.0/src/lib-gen.typ
  packages/preview/use-tabler-icons/0.8.0/src/lib-impl.typ
  packages/preview/use-tabler-icons/0.8.0/src/lib.typ
  packages/preview/use-tabler-icons/0.8.0/typst.toml
Labels: update

#1494 classy-german-invoice:0.3.1
  packages/preview/classy-german-invoice/0.3.1/LICENSE
  packages/preview/classy-german-invoice/0.3.1/README.md
  packages/preview/classy-german-invoice/0.3.1/lib.typ
  packages/preview/classy-german-invoice/0.3.1/template/example_signature.png
  packages/preview/classy-german-invoice/0.3.1/template/main.typ
  packages/preview/classy-german-invoice/0.3.1/thumbnail.png
  packages/preview/classy-german-invoice/0.3.1/typst.toml
Labels: update

#1536 light-cv:0.2.0
  packages/preview/light-cv/0.2.0/LICENSE
  packages/preview/light-cv/0.2.0/README.md
  packages/preview/light-cv/0.2.0/example.png
  packages/preview/light-cv/0.2.0/lib.typ
  packages/preview/light-cv/0.2.0/modules/header.typ
  packages/preview/light-cv/0.2.0/modules/section.typ
  packages/preview/light-cv/0.2.0/modules/skills.typ
  packages/preview/light-cv/0.2.0/modules/utils.typ
  packages/preview/light-cv/0.2.0/template/cv-en.typ
  packages/preview/light-cv/0.2.0/template/media/avatar.jpeg
  packages/preview/light-cv/0.2.0/template/media/ucla.png
  packages/preview/light-cv/0.2.0/template/settings/styles.typ
  packages/preview/light-cv/0.2.0/typst.toml
Labels: update

#1493 unofficial-hka-thesis:1.0.0
  packages/preview/unofficial-hka-thesis/1.0.0/LICENSE
  packages/preview/unofficial-hka-thesis/1.0.0/README.md
  packages/preview/unofficial-hka-thesis/1.0.0/assets/HKALogo.png
  packages/preview/unofficial-hka-thesis/1.0.0/assets/company.jpg
  packages/preview/unofficial-hka-thesis/1.0.0/assets/company.svg
  packages/preview/unofficial-hka-thesis/1.0.0/assets/image-1.png
  packages/preview/unofficial-hka-thesis/1.0.0/assets/image-2.png
  packages/preview/unofficial-hka-thesis/1.0.0/assets/image.png
  packages/preview/unofficial-hka-thesis/1.0.0/lib.typ
  packages/preview/unofficial-hka-thesis/1.0.0/modules/titlepage.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/abbreviations.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/bibliography/thesis.bib
  packages/preview/unofficial-hka-thesis/1.0.0/template/chapters/1_introduction.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/chapters/2_foundations.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/chapters/A1_Material.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/chapters/A2_Transcripts.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/figures/tiger.png
  packages/preview/unofficial-hka-thesis/1.0.0/template/logo/HKALogo.png
  packages/preview/unofficial-hka-thesis/1.0.0/template/logo/company.svg
  packages/preview/unofficial-hka-thesis/1.0.0/template/settings/metadata.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/settings/settings.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/supplementary/abstract.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/supplementary/abstractGerman.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/supplementary/statutoryDeclaration.typ
  packages/preview/unofficial-hka-thesis/1.0.0/template/thesis.typ
  packages/preview/unofficial-hka-thesis/1.0.0/thumbnail.png
  packages/preview/unofficial-hka-thesis/1.0.0/typst.toml
Labels: new

#1527 easy-typography:0.1.0
  packages/preview/easy-typography/0.1.0/.gitignore
  packages/preview/easy-typography/0.1.0/LICENSE
  packages/preview/easy-typography/0.1.0/README.md
  packages/preview/easy-typography/0.1.0/lib.typ
  packages/preview/easy-typography/0.1.0/src/constants.typ
  packages/preview/easy-typography/0.1.0/src/main.typ
  packages/preview/easy-typography/0.1.0/tests/basic/ref/1.png
  packages/preview/easy-typography/0.1.0/tests/basic/test.typ
  packages/preview/easy-typography/0.1.0/thumbnail.png
  packages/preview/easy-typography/0.1.0/typst.toml
Labels: new

#1526 tasteful-pairings:0.1.0
  packages/preview/tasteful-pairings/0.1.0/.gitignore
  packages/preview/tasteful-pairings/0.1.0/LICENSE
  packages/preview/tasteful-pairings/0.1.0/README.md
  packages/preview/tasteful-pairings/0.1.0/lib.typ
  packages/preview/tasteful-pairings/0.1.0/src/main.typ
  packages/preview/tasteful-pairings/0.1.0/tests/gallery/ref/1.png
  packages/preview/tasteful-pairings/0.1.0/tests/gallery/test.typ
  packages/preview/tasteful-pairings/0.1.0/thumbnail.png
  packages/preview/tasteful-pairings/0.1.0/typst.toml
Labels: new

#1541 flow:0.1.2
  packages/preview/flow/0.1.2/LICENSE.md
  packages/preview/flow/0.1.2/README.md
  packages/preview/flow/0.1.2/src/callout.typ
  packages/preview/flow/0.1.2/src/cfg.typ
  packages/preview/flow/0.1.2/src/checkbox.typ
  packages/preview/flow/0.1.2/src/gfx.typ
  packages/preview/flow/0.1.2/src/gfx/draw.typ
  packages/preview/flow/0.1.2/src/gfx/maybe-stub.typ
  packages/preview/flow/0.1.2/src/gfx/render.typ
  packages/preview/flow/0.1.2/src/gfx/stub.typ
  packages/preview/flow/0.1.2/src/gfx/stub/draw.typ
  packages/preview/flow/0.1.2/src/gfx/util.typ
  packages/preview/flow/0.1.2/src/info.typ
  packages/preview/flow/0.1.2/src/keywords.typ
  packages/preview/flow/0.1.2/src/lib.typ
  packages/preview/flow/0.1.2/src/palette.typ
  packages/preview/flow/0.1.2/src/presentation.typ
  packages/preview/flow/0.1.2/src/template.typ
  packages/preview/flow/0.1.2/src/tyck.typ
  packages/preview/flow/0.1.2/src/util.typ
  packages/preview/flow/0.1.2/src/util/linalg.typ
  packages/preview/flow/0.1.2/template/main.typ
  packages/preview/flow/0.1.2/thumbnail/page-1.png
  packages/preview/flow/0.1.2/typst.toml
Labels: new

#1538 handy-dora:0.1.0 and rexllent:0.2.0
  packages/preview/handy-dora/0.1.0/README.md
  packages/preview/handy-dora/0.1.0/assets/21w2www7w28p.png
  packages/preview/handy-dora/0.1.0/assets/2312936963s.png
  packages/preview/handy-dora/0.1.0/assets/example1.png
  packages/preview/handy-dora/0.1.0/assets/example2.png
  packages/preview/handy-dora/0.1.0/assets/example3.png
  packages/preview/handy-dora/0.1.0/assets/example4.png
  packages/preview/handy-dora/0.1.0/typst.toml
  packages/preview/rexllent/0.2.0/LICENSE
  packages/preview/rexllent/0.2.0/README.md
  packages/preview/rexllent/0.2.0/assets/example1.png
  packages/preview/rexllent/0.2.0/assets/example2.png
  packages/preview/rexllent/0.2.0/assets/example3.png
  packages/preview/rexllent/0.2.0/assets/example4.png
  packages/preview/rexllent/0.2.0/assets/example5.png
  packages/preview/rexllent/0.2.0/assets/example6.png
  packages/preview/rexllent/0.2.0/assets/excel.png
  packages/preview/rexllent/0.2.0/lib.typ
  packages/preview/rexllent/0.2.0/mod.typ
  packages/preview/rexllent/0.2.0/rexllent.wasm
  packages/preview/rexllent/0.2.0/typst.toml
Labels: new

#1516 basalt-lib:1.0.0
  packages/preview/basalt-lib/1.0.0/LICENSE
  packages/preview/basalt-lib/1.0.0/README.md
  packages/preview/basalt-lib/1.0.0/src/exports.typ
  packages/preview/basalt-lib/1.0.0/src/metadata-with-id.typ
  packages/preview/basalt-lib/1.0.0/src/note.typ
  packages/preview/basalt-lib/1.0.0/src/tag.typ
  packages/preview/basalt-lib/1.0.0/src/vault.typ
  packages/preview/basalt-lib/1.0.0/src/xlink.typ
  packages/preview/basalt-lib/1.0.0/typst.toml
Labels: new

#1532 modern-bnu-course-paper:0.1.0
  packages/preview/modern-bnu-course-paper/0.1.0/LICENSE
  packages/preview/modern-bnu-course-paper/0.1.0/README.md
  packages/preview/modern-bnu-course-paper/0.1.0/assets/vi/bnu-name.svg
  packages/preview/modern-bnu-course-paper/0.1.0/assets/vi/old_bnu-name.svg
  packages/preview/modern-bnu-course-paper/0.1.0/layouts/appendix.typ
  packages/preview/modern-bnu-course-paper/0.1.0/layouts/doc.typ
  packages/preview/modern-bnu-course-paper/0.1.0/layouts/mainmatter.typ
  packages/preview/modern-bnu-course-paper/0.1.0/layouts/preface.typ
  packages/preview/modern-bnu-course-paper/0.1.0/lib.typ
  packages/preview/modern-bnu-course-paper/0.1.0/others/bachelor-proposal.typ
  packages/preview/modern-bnu-course-paper/0.1.0/others/master-proposal-logo.png
  packages/preview/modern-bnu-course-paper/0.1.0/others/master-proposal.typ
  packages/preview/modern-bnu-course-paper/0.1.0/others/style.typ
  packages/preview/modern-bnu-course-paper/0.1.0/pages/abstract.typ
  packages/preview/modern-bnu-course-paper/0.1.0/pages/acknowledgement.typ
  packages/preview/modern-bnu-course-paper/0.1.0/pages/fonts-display-page.typ
  packages/preview/modern-bnu-course-paper/0.1.0/pages/notation.typ
  packages/preview/modern-bnu-course-paper/0.1.0/pages/outline-page.typ
  packages/preview/modern-bnu-course-paper/0.1.0/template/images/bnu-emblem.svg
  packages/preview/modern-bnu-course-paper/0.1.0/template/paper.typ
  packages/preview/modern-bnu-course-paper/0.1.0/template/ref.bib
  packages/preview/modern-bnu-course-paper/0.1.0/thumbnail.png
  packages/preview/modern-bnu-course-paper/0.1.0/typst.toml
  packages/preview/modern-bnu-course-paper/0.1.0/utils/bilingual-bibliography.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/custom-algo.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/custom-cuti.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/custom-heading.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/custom-numbering.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/custom-tablex.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/datetime-display.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/double-underline.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/hline.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/indent.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/invisible-heading.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/justify-text.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/style.typ
  packages/preview/modern-bnu-course-paper/0.1.0/utils/unpairs.typ
Labels: new

#1533 finely-crafted-cv:0.2.0
  packages/preview/finely-crafted-cv/0.2.0/LICENSE
  packages/preview/finely-crafted-cv/0.2.0/README.md
  packages/preview/finely-crafted-cv/0.2.0/lib.typ
  packages/preview/finely-crafted-cv/0.2.0/src/constants.typ
  packages/preview/finely-crafted-cv/0.2.0/src/helpers.typ
  packages/preview/finely-crafted-cv/0.2.0/src/icons/email.svg
  packages/preview/finely-crafted-cv/0.2.0/src/icons/linkedin.svg
  packages/preview/finely-crafted-cv/0.2.0/src/icons/phone.svg
  packages/preview/finely-crafted-cv/0.2.0/src/resume.typ
  packages/preview/finely-crafted-cv/0.2.0/src/state.typ
  packages/preview/finely-crafted-cv/0.2.0/template/assets/my-qr-code.svg
  packages/preview/finely-crafted-cv/0.2.0/template/icons/coral.svg
  packages/preview/finely-crafted-cv/0.2.0/template/icons/earth.svg
  packages/preview/finely-crafted-cv/0.2.0/template/icons/graduation-cap.svg
  packages/preview/finely-crafted-cv/0.2.0/template/icons/microscope.svg
  packages/preview/finely-crafted-cv/0.2.0/template/icons/palm-tree.svg
  packages/preview/finely-crafted-cv/0.2.0/template/icons/whale.svg
  packages/preview/finely-crafted-cv/0.2.0/template/main.typ
  packages/preview/finely-crafted-cv/0.2.0/thumbnail.png
  packages/preview/finely-crafted-cv/0.2.0/typst.toml
Labels: new, update

#1534 pigmentpedia:0.3.0
  packages/preview/pigmentpedia/0.3.0/LICENSE
  packages/preview/pigmentpedia/0.3.0/README.md
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-icon-black.svg
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-icon-white.svg
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-icon.svg
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-logo-black.svg
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-logo-sm.png
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-logo-white.svg
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-logo.png
  packages/preview/pigmentpedia/0.3.0/assets/logo/pigmentpedia-logo.svg
  packages/preview/pigmentpedia/0.3.0/examples/example.pdf
  packages/preview/pigmentpedia/0.3.0/examples/example.typ
  packages/preview/pigmentpedia/0.3.0/lib.typ
  packages/preview/pigmentpedia/0.3.0/pigments/misc/Chinese/zhcn-trad.typ
  packages/preview/pigmentpedia/0.3.0/pigments/misc/Crayola.typ
  packages/preview/pigmentpedia/0.3.0/pigments/misc/Japanese/jajp-trad.typ
  packages/preview/pigmentpedia/0.3.0/pigments/palettes/Catppuccin.typ
  packages/preview/pigmentpedia/0.3.0/pigments/palettes/Nord.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/CSS.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/DIC.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/HKS.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/ISCC-NBS/ISCC-NBS.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/ISCC-NBS/nbs-iscc.txt
  packages/preview/pigmentpedia/0.3.0/pigments/standards/NCS.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/NipponPaint.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/Pantone.typ
  packages/preview/pigmentpedia/0.3.0/pigments/standards/RAL.typ
  packages/preview/pigmentpedia/0.3.0/src/convert.typ
  packages/preview/pigmentpedia/0.3.0/src/display.typ
  packages/preview/pigmentpedia/0.3.0/src/pigment-playground.typ
  packages/preview/pigmentpedia/0.3.0/src/pigments.typ
  packages/preview/pigmentpedia/0.3.0/src/private.typ
  packages/preview/pigmentpedia/0.3.0/src/search.typ
  packages/preview/pigmentpedia/0.3.0/src/show-tree.typ
  packages/preview/pigmentpedia/0.3.0/src/text-contrast.typ
  packages/preview/pigmentpedia/0.3.0/typst.toml
Labels: update

#1544 thesist:1.0.0
  packages/preview/thesist/1.0.0/LICENSE
  packages/preview/thesist/1.0.0/README.md
  packages/preview/thesist/1.0.0/src/IST.png
  packages/preview/thesist/1.0.0/src/figure-numbering.typ
  packages/preview/thesist/1.0.0/src/heading-styles.typ
  packages/preview/thesist/1.0.0/src/layout.typ
  packages/preview/thesist/1.0.0/src/utils.typ
  packages/preview/thesist/1.0.0/template/Beginning/Abstract-en.typ
  packages/preview/thesist/1.0.0/template/Beginning/Abstract-pt.typ
  packages/preview/thesist/1.0.0/template/Beginning/Acknowledgments.typ
  packages/preview/thesist/1.0.0/template/Beginning/Extra-page.typ
  packages/preview/thesist/1.0.0/template/Beginning/Glossary.typ
  packages/preview/thesist/1.0.0/template/Beginning/Keywords-en.typ
  packages/preview/thesist/1.0.0/template/Beginning/Keywords-pt.typ
  packages/preview/thesist/1.0.0/template/Chapters/0-Quick-guide.typ
  packages/preview/thesist/1.0.0/template/Chapters/1-Introduction.typ
  packages/preview/thesist/1.0.0/template/Chapters/Appendix-A.typ
  packages/preview/thesist/1.0.0/template/Chapters/Appendix-B.typ
  packages/preview/thesist/1.0.0/template/Images/0-Quick-guide/example.jpg
  packages/preview/thesist/1.0.0/template/Images/default-alameda.jpg
  packages/preview/thesist/1.0.0/template/Images/default-taguspark.jpg
  packages/preview/thesist/1.0.0/template/main.typ
  packages/preview/thesist/1.0.0/template/refs.bib
  packages/preview/thesist/1.0.0/thumbnail.png
  packages/preview/thesist/1.0.0/typst.toml
Labels: update

#1549 grotesk-cv:1.0.2
  packages/preview/grotesk-cv/1.0.2/CHANGELOG.md
  packages/preview/grotesk-cv/1.0.2/LICENSE
  packages/preview/grotesk-cv/1.0.2/README.md
  packages/preview/grotesk-cv/1.0.2/docs/manual.pdf
  packages/preview/grotesk-cv/1.0.2/src/lib.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/education.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/experience.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/languages.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/other_experience.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/personal.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/profile.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/references.typ
  packages/preview/grotesk-cv/1.0.2/src/template/content/skills.typ
  packages/preview/grotesk-cv/1.0.2/src/template/cover.typ
  packages/preview/grotesk-cv/1.0.2/src/template/cv.typ
  packages/preview/grotesk-cv/1.0.2/src/template/img/portrait.png
  packages/preview/grotesk-cv/1.0.2/src/template/info.toml
  packages/preview/grotesk-cv/1.0.2/thumbnail.png
  packages/preview/grotesk-cv/1.0.2/typst.toml
Labels: update

#1530 conchord:0.3.0
  packages/preview/conchord/0.3.0/LICENSE
  packages/preview/conchord/0.3.0/README.md
  packages/preview/conchord/0.3.0/chords/draw-chord.typ
  packages/preview/conchord/0.3.0/chords/sheet.typ
  packages/preview/conchord/0.3.0/chords/smart-chord.typ
  packages/preview/conchord/0.3.0/examples/compare.png
  packages/preview/conchord/0.3.0/examples/compare.typ
  packages/preview/conchord/0.3.0/examples/crazy.png
  packages/preview/conchord/0.3.0/examples/crazy.typ
  packages/preview/conchord/0.3.0/examples/red-chords.png
  packages/preview/conchord/0.3.0/examples/red-chords.typ
  packages/preview/conchord/0.3.0/examples/sheet-styles.png
  packages/preview/conchord/0.3.0/examples/sheet-styles.typ
  packages/preview/conchord/0.3.0/examples/simple-gen.png
  packages/preview/conchord/0.3.0/examples/simple-gen.typ
  packages/preview/conchord/0.3.0/examples/simple.png
  packages/preview/conchord/0.3.0/examples/simple.typ
  packages/preview/conchord/0.3.0/examples/tabs.png
  packages/preview/conchord/0.3.0/examples/tabs.typ
  packages/preview/conchord/0.3.0/examples/true-bass.png
  packages/preview/conchord/0.3.0/examples/true-bass.typ
  packages/preview/conchord/0.3.0/examples/zombie.png
  packages/preview/conchord/0.3.0/examples/zombie.typ
  packages/preview/conchord/0.3.0/gen/conchord_gen.wasm
  packages/preview/conchord/0.3.0/gen/gen.typ
  packages/preview/conchord/0.3.0/lib.typ
  packages/preview/conchord/0.3.0/reference/reference.pdf
  packages/preview/conchord/0.3.0/tabs/drawing.typ
  packages/preview/conchord/0.3.0/tabs/gen.typ
  packages/preview/conchord/0.3.0/tabs/tabs.typ
  packages/preview/conchord/0.3.0/typst.toml
Labels: update

#1489 xyznote:0.3.0
  packages/preview/xyznote/0.3.0/LICENSE
  packages/preview/xyznote/0.3.0/README.md
  packages/preview/xyznote/0.3.0/src/color-box.typ
  packages/preview/xyznote/0.3.0/src/colors.typ
  packages/preview/xyznote/0.3.0/src/lib.typ
  packages/preview/xyznote/0.3.0/template/main.typ
  packages/preview/xyznote/0.3.0/template/refs.bib
  packages/preview/xyznote/0.3.0/thumbnail.png
  packages/preview/xyznote/0.3.0/typst.toml
Labels: update

#1546 curryst:0.4.0
  packages/preview/curryst/0.4.0/LICENSE
  packages/preview/curryst/0.4.0/README.md
  packages/preview/curryst/0.4.0/curryst.typ
  packages/preview/curryst/0.4.0/examples/math-formula.svg
  packages/preview/curryst/0.4.0/examples/math-formula.typ
  packages/preview/curryst/0.4.0/examples/natural-deduction.svg
  packages/preview/curryst/0.4.0/examples/natural-deduction.typ
  packages/preview/curryst/0.4.0/examples/rule-as-premise.svg
  packages/preview/curryst/0.4.0/examples/rule-as-premise.typ
  packages/preview/curryst/0.4.0/examples/usage.svg
  packages/preview/curryst/0.4.0/examples/usage.typ
  packages/preview/curryst/0.4.0/typst.toml
Labels: update

#1552 summy:0.1.0
  packages/preview/summy/0.1.0/LICENSE
  packages/preview/summy/0.1.0/README.md
  packages/preview/summy/0.1.0/lib.typ
  packages/preview/summy/0.1.0/template/main.typ
  packages/preview/summy/0.1.0/template/units/00-general-formula.typ
  packages/preview/summy/0.1.0/template/units/01-lorem-ipsum.typ
  packages/preview/summy/0.1.0/template/units/02-lorem-ipsum.typ
  packages/preview/summy/0.1.0/template/units/03-lorem-ipsum.typ
  packages/preview/summy/0.1.0/template/units/04-lorem-ipsum.typ
  packages/preview/summy/0.1.0/template/units/05-lorem-ipsum.typ
  packages/preview/summy/0.1.0/thumbnail.png
  packages/preview/summy/0.1.0/typst.toml
Labels: new

#1554 pillar:0.3.1
  packages/preview/pillar/0.3.1/LICENSE
  packages/preview/pillar/0.3.1/README.md
  packages/preview/pillar/0.3.1/src/impl.typ
  packages/preview/pillar/0.3.1/src/pillar.typ
  packages/preview/pillar/0.3.1/typst.toml
Labels: update

#1550 zero:0.3.2
  packages/preview/zero/0.3.2/LICENSE
  packages/preview/zero/0.3.2/README.md
  packages/preview/zero/0.3.2/src/align-column.typ
  packages/preview/zero/0.3.2/src/assertations.typ
  packages/preview/zero/0.3.2/src/formatting.typ
  packages/preview/zero/0.3.2/src/impl.typ
  packages/preview/zero/0.3.2/src/num.typ
  packages/preview/zero/0.3.2/src/parsing.typ
  packages/preview/zero/0.3.2/src/rounding.typ
  packages/preview/zero/0.3.2/src/state.typ
  packages/preview/zero/0.3.2/src/utility.typ
  packages/preview/zero/0.3.2/src/zero.typ
  packages/preview/zero/0.3.2/src/ztable.typ
  packages/preview/zero/0.3.2/typst.toml
Labels: update

#1551 tidy:0.4.1
  packages/preview/tidy/0.4.1/LICENSE
  packages/preview/tidy/0.4.1/README.md
  packages/preview/tidy/0.4.1/src/helping.typ
  packages/preview/tidy/0.4.1/src/new-parser.typ
  packages/preview/tidy/0.4.1/src/old-parser.typ
  packages/preview/tidy/0.4.1/src/parse-module.typ
  packages/preview/tidy/0.4.1/src/show-example.typ
  packages/preview/tidy/0.4.1/src/show-module.typ
  packages/preview/tidy/0.4.1/src/styles.typ
  packages/preview/tidy/0.4.1/src/styles/default.typ
  packages/preview/tidy/0.4.1/src/styles/help.typ
  packages/preview/tidy/0.4.1/src/styles/minimal.typ
  packages/preview/tidy/0.4.1/src/testing.typ
  packages/preview/tidy/0.4.1/src/tidy.typ
  packages/preview/tidy/0.4.1/src/utilities.typ
  packages/preview/tidy/0.4.1/typst.toml
Labels: update

#1491 chordish:0.2.0
  packages/preview/chordish/0.2.0/LICENSE
  packages/preview/chordish/0.2.0/README.md
  packages/preview/chordish/0.2.0/chord-definitions.typ
  packages/preview/chordish/0.2.0/chords.typ
  packages/preview/chordish/0.2.0/lib.typ
  packages/preview/chordish/0.2.0/template/main.typ
  packages/preview/chordish/0.2.0/template/songs/Example Song.typ
  packages/preview/chordish/0.2.0/thumbnail.png
  packages/preview/chordish/0.2.0/typst.toml
Labels: update

#1539 modern-ecnu-thesis:0.1.0
  packages/preview/modern-ecnu-thesis/0.1.0/LICENSE
  packages/preview/modern-ecnu-thesis/0.1.0/README.md
  packages/preview/modern-ecnu-thesis/0.1.0/assets/ecnu-bachelor-thesis-cover.svg
  packages/preview/modern-ecnu-thesis/0.1.0/assets/ecnu-emblem-name.svg
  packages/preview/modern-ecnu-thesis/0.1.0/assets/ecnu-emblem.svg
  packages/preview/modern-ecnu-thesis/0.1.0/assets/ecnu-name-en.svg
  packages/preview/modern-ecnu-thesis/0.1.0/layouts/appendix.typ
  packages/preview/modern-ecnu-thesis/0.1.0/layouts/doc.typ
  packages/preview/modern-ecnu-thesis/0.1.0/layouts/mainmatter.typ
  packages/preview/modern-ecnu-thesis/0.1.0/layouts/preface.typ
  packages/preview/modern-ecnu-thesis/0.1.0/lib.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/acknowledgement.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/bachelor-abstract-en.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/bachelor-abstract.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/bachelor-cover.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/bachelor-decl-page.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/bachelor-outline-page.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/fonts-display-page.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/list-of-figures.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/list-of-tables.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/master-abstract-en.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/master-abstract.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/master-committee.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/master-cover.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/master-decl-page.typ
  packages/preview/modern-ecnu-thesis/0.1.0/pages/notation.typ
  packages/preview/modern-ecnu-thesis/0.1.0/template/Makefile
  packages/preview/modern-ecnu-thesis/0.1.0/template/images/ecnu-emblem.svg
  packages/preview/modern-ecnu-thesis/0.1.0/template/ref.bib
  packages/preview/modern-ecnu-thesis/0.1.0/template/thesis.typ
  packages/preview/modern-ecnu-thesis/0.1.0/thumbnail.png
  packages/preview/modern-ecnu-thesis/0.1.0/typst.toml
  packages/preview/modern-ecnu-thesis/0.1.0/utils/bilingual-bibliography.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/custom-cuti.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/custom-heading.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/custom-numbering.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/custom-tablex.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/datetime-display.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/double-underline.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/fix-cjk-linebreak.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/gb-t-7714-2015-numeric-nosup.csl
  packages/preview/modern-ecnu-thesis/0.1.0/utils/hline.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/indent.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/invisible-heading.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/justify-text.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/pagebreak-from-odd.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/panic-page.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/str.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/style.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/unpairs.typ
  packages/preview/modern-ecnu-thesis/0.1.0/utils/word-counter.typ
Labels: new

#1553 metronic:1.0.0
  packages/preview/metronic/1.0.0/LICENSE
  packages/preview/metronic/1.0.0/README.md
  packages/preview/metronic/1.0.0/template.typ
  packages/preview/metronic/1.0.0/template/main.typ
  packages/preview/metronic/1.0.0/thumbnail.png
  packages/preview/metronic/1.0.0/typst.toml
Labels: new

#1556 clean-dhbw:0.1.0
  packages/preview/clean-dhbw/0.1.0/LICENSE
  packages/preview/clean-dhbw/0.1.0/README.md
  packages/preview/clean-dhbw/0.1.0/acronym-lib.typ
  packages/preview/clean-dhbw/0.1.0/check-attributes.typ
  packages/preview/clean-dhbw/0.1.0/confidentiality-statement.typ
  packages/preview/clean-dhbw/0.1.0/declaration-of-authorship.typ
  packages/preview/clean-dhbw/0.1.0/dhbw.svg
  packages/preview/clean-dhbw/0.1.0/docs/assumptions.md
  packages/preview/clean-dhbw/0.1.0/docs/design-explained.md
  packages/preview/clean-dhbw/0.1.0/docs/im-begin-chapter.png
  packages/preview/clean-dhbw/0.1.0/docs/usability-issues.md
  packages/preview/clean-dhbw/0.1.0/glossary-lib.typ
  packages/preview/clean-dhbw/0.1.0/lib.typ
  packages/preview/clean-dhbw/0.1.0/locale.typ
  packages/preview/clean-dhbw/0.1.0/shared-lib.typ
  packages/preview/clean-dhbw/0.1.0/template/acronyms.typ
  packages/preview/clean-dhbw/0.1.0/template/assets/ts.svg
  packages/preview/clean-dhbw/0.1.0/template/glossary.typ
  packages/preview/clean-dhbw/0.1.0/template/main.typ
  packages/preview/clean-dhbw/0.1.0/template/sources.bib
  packages/preview/clean-dhbw/0.1.0/thumbnail.png
  packages/preview/clean-dhbw/0.1.0/titlepage.typ
  packages/preview/clean-dhbw/0.1.0/typst.toml
Labels: new

#1564 pigmentpedia:0.3.1
  packages/preview/pigmentpedia/0.3.1/LICENSE
  packages/preview/pigmentpedia/0.3.1/README.md
  packages/preview/pigmentpedia/0.3.1/assets/logo/pigmentpedia-icon.svg
  packages/preview/pigmentpedia/0.3.1/assets/logo/pigmentpedia-logo.svg
  packages/preview/pigmentpedia/0.3.1/examples/example.pdf
  packages/preview/pigmentpedia/0.3.1/examples/example.typ
  packages/preview/pigmentpedia/0.3.1/lib.typ
  packages/preview/pigmentpedia/0.3.1/pigments/misc/Chinese/zhcn-trad.typ
  packages/preview/pigmentpedia/0.3.1/pigments/misc/Crayola.typ
  packages/preview/pigmentpedia/0.3.1/pigments/misc/Japanese/jajp-trad.typ
  packages/preview/pigmentpedia/0.3.1/pigments/palettes/Catppuccin.typ
  packages/preview/pigmentpedia/0.3.1/pigments/palettes/Nord.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/CSS.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/DIC.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/HKS.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/ISCC-NBS/ISCC-NBS.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/ISCC-NBS/nbs-iscc.txt
  packages/preview/pigmentpedia/0.3.1/pigments/standards/NCS.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/NipponPaint.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/Pantone.typ
  packages/preview/pigmentpedia/0.3.1/pigments/standards/RAL.typ
  packages/preview/pigmentpedia/0.3.1/src/convert.typ
  packages/preview/pigmentpedia/0.3.1/src/display.typ
  packages/preview/pigmentpedia/0.3.1/src/pigment-playground.typ
  packages/preview/pigmentpedia/0.3.1/src/pigments.typ
  packages/preview/pigmentpedia/0.3.1/src/private.typ
  packages/preview/pigmentpedia/0.3.1/src/search.typ
  packages/preview/pigmentpedia/0.3.1/src/show-tree.typ
  packages/preview/pigmentpedia/0.3.1/src/text-contrast.typ
  packages/preview/pigmentpedia/0.3.1/typst.toml
Labels: update

#1566 siddhi-syntax:0.1.0
  packages/preview/siddhi-syntax/0.1.0/LICENSE
  packages/preview/siddhi-syntax/0.1.0/README.md
  packages/preview/siddhi-syntax/0.1.0/lib.typ
  packages/preview/siddhi-syntax/0.1.0/siddhi.sublime-syntax
  packages/preview/siddhi-syntax/0.1.0/typst.toml
Labels: new

#1559 jaconf-mscs:0.1.0
  packages/preview/jaconf-mscs/0.1.0/LICENSE
  packages/preview/jaconf-mscs/0.1.0/README.md
  packages/preview/jaconf-mscs/0.1.0/lib.typ
  packages/preview/jaconf-mscs/0.1.0/sice.csl
  packages/preview/jaconf-mscs/0.1.0/template/main.typ
  packages/preview/jaconf-mscs/0.1.0/template/refs.yml
  packages/preview/jaconf-mscs/0.1.0/thumbnail.png
  packages/preview/jaconf-mscs/0.1.0/typst.toml
Labels: new

#1568 prismath:0.1.0
  packages/preview/prismath/0.1.0/LICENSE
  packages/preview/prismath/0.1.0/README.md
  packages/preview/prismath/0.1.0/src/lib.typ
  packages/preview/prismath/0.1.0/typst.toml
Labels: new

#1561 dashy-todo:0.0.2
  packages/preview/dashy-todo/0.0.2/LICENSE
  packages/preview/dashy-todo/0.0.2/README.md
  packages/preview/dashy-todo/0.0.2/example.svg
  packages/preview/dashy-todo/0.0.2/example.typ
  packages/preview/dashy-todo/0.0.2/lib/place-in-page-margin.typ
  packages/preview/dashy-todo/0.0.2/lib/side-margin.typ
  packages/preview/dashy-todo/0.0.2/lib/todo.typ
  packages/preview/dashy-todo/0.0.2/typst.toml
Labels: update

#1569 rexllent:0.2.3
  packages/preview/rexllent/0.2.3/LICENSE
  packages/preview/rexllent/0.2.3/README.md
  packages/preview/rexllent/0.2.3/assets/example1.png
  packages/preview/rexllent/0.2.3/assets/example2.png
  packages/preview/rexllent/0.2.3/assets/example3.png
  packages/preview/rexllent/0.2.3/assets/example4.png
  packages/preview/rexllent/0.2.3/assets/example5.png
  packages/preview/rexllent/0.2.3/assets/example6.png
  packages/preview/rexllent/0.2.3/assets/example7.png
  packages/preview/rexllent/0.2.3/assets/excel.png
  packages/preview/rexllent/0.2.3/lib.typ
  packages/preview/rexllent/0.2.3/mod.typ
  packages/preview/rexllent/0.2.3/rexllent.wasm
  packages/preview/rexllent/0.2.3/typst.toml
Labels: update

#1567 divine-words:0.1.0
  packages/preview/divine-words/0.1.0/LICENSE
  packages/preview/divine-words/0.1.0/README.md
  packages/preview/divine-words/0.1.0/lib.typ
  packages/preview/divine-words/0.1.0/template/bib.bib
  packages/preview/divine-words/0.1.0/template/main.typ
  packages/preview/divine-words/0.1.0/thumbnail.png
  packages/preview/divine-words/0.1.0/typst.toml
Labels: new

#1565 zen-zine:0.2.0
  packages/preview/zen-zine/0.2.0/LICENSE
  packages/preview/zen-zine/0.2.0/README.md
  packages/preview/zen-zine/0.2.0/lib.typ
  packages/preview/zen-zine/0.2.0/template/main.typ
  packages/preview/zen-zine/0.2.0/template/preview.png
  packages/preview/zen-zine/0.2.0/typst.toml
Labels: update

#1488 lacy-ubc-math-project:0.1.0
  packages/preview/lacy-ubc-math-project/0.1.0/LICENSE
  packages/preview/lacy-ubc-math-project/0.1.0/README.md
  packages/preview/lacy-ubc-math-project/0.1.0/cleanup.nu
  packages/preview/lacy-ubc-math-project/0.1.0/drawing.typ
  packages/preview/lacy-ubc-math-project/0.1.0/format.typ
  packages/preview/lacy-ubc-math-project/0.1.0/help.typ
  packages/preview/lacy-ubc-math-project/0.1.0/lib.typ
  packages/preview/lacy-ubc-math-project/0.1.0/manual.pdf
  packages/preview/lacy-ubc-math-project/0.1.0/manual.typ
  packages/preview/lacy-ubc-math-project/0.1.0/shorthand.typ
  packages/preview/lacy-ubc-math-project/0.1.0/template/assets/madeline-math.jpg
  packages/preview/lacy-ubc-math-project/0.1.0/template/common.typ
  packages/preview/lacy-ubc-math-project/0.1.0/template/project1.typ
  packages/preview/lacy-ubc-math-project/0.1.0/thumbnail.png
  packages/preview/lacy-ubc-math-project/0.1.0/typst.toml
  packages/preview/lacy-ubc-math-project/0.1.0/unsafe.typ
Labels: new

#1575 ansi-render:0.8.0
  packages/preview/ansi-render/0.8.0/README.md
Labels: update

#1576 zebraw:0.2.0
  packages/preview/zebraw/0.2.0/LICENSE
  packages/preview/zebraw/0.2.0/README.md
  packages/preview/zebraw/0.2.0/assets/example1.svg
  packages/preview/zebraw/0.2.0/assets/example2.svg
  packages/preview/zebraw/0.2.0/assets/example3.svg
  packages/preview/zebraw/0.2.0/assets/example4.svg
  packages/preview/zebraw/0.2.0/assets/example5.svg
  packages/preview/zebraw/0.2.0/assets/example6.svg
  packages/preview/zebraw/0.2.0/assets/example7.svg
  packages/preview/zebraw/0.2.0/assets/example8.svg
  packages/preview/zebraw/0.2.0/assets/line-spacing.svg
  packages/preview/zebraw/0.2.0/lib.typ
  packages/preview/zebraw/0.2.0/typst.toml
Labels: update

#1577 clean-dhbw:0.1.0
  packages/preview/clean-dhbw/0.1.0/README.md
Labels: new

#1557 ncku-later:0.1.0
  packages/preview/ncku-later/0.1.0/LICENSE
  packages/preview/ncku-later/0.1.0/Makefile
  packages/preview/ncku-later/0.1.0/README.md
  packages/preview/ncku-later/0.1.0/assets/watermark-20160509_v2-a4.svg
  packages/preview/ncku-later/0.1.0/layouts/extended-abstract-en.typ
  packages/preview/ncku-later/0.1.0/layouts/mainmatter-or-appendix.typ
  packages/preview/ncku-later/0.1.0/layouts/whole.typ
  packages/preview/ncku-later/0.1.0/lib.typ
  packages/preview/ncku-later/0.1.0/pages/abstract.typ
  packages/preview/ncku-later/0.1.0/pages/acknowledge.typ
  packages/preview/ncku-later/0.1.0/pages/approved-by.typ
  packages/preview/ncku-later/0.1.0/pages/cover.typ
  packages/preview/ncku-later/0.1.0/pages/outline.typ
  packages/preview/ncku-later/0.1.0/pages/ref.typ
  packages/preview/ncku-later/0.1.0/template/contents/abstract.typ
  packages/preview/ncku-later/0.1.0/template/contents/acknowledgement.typ
  packages/preview/ncku-later/0.1.0/template/contents/appendix.typ
  packages/preview/ncku-later/0.1.0/template/contents/extended-abstract-en.typ
  packages/preview/ncku-later/0.1.0/template/contents/mainmatter.typ
  packages/preview/ncku-later/0.1.0/template/images/image1.png
  packages/preview/ncku-later/0.1.0/template/main.typ
  packages/preview/ncku-later/0.1.0/template/ref.bib
  packages/preview/ncku-later/0.1.0/template/setup.typ
  packages/preview/ncku-later/0.1.0/thumbnail.png
  packages/preview/ncku-later/0.1.0/typst.toml
  packages/preview/ncku-later/0.1.0/utils/page-numb.typ
Labels: new

#1573 cram-snap:0.2.2
  packages/preview/cram-snap/0.2.2/LICENSE
  packages/preview/cram-snap/0.2.2/README.md
  packages/preview/cram-snap/0.2.2/lib.typ
  packages/preview/cram-snap/0.2.2/template/git-icon.svg
  packages/preview/cram-snap/0.2.2/template/main.typ
  packages/preview/cram-snap/0.2.2/thumbnail.png
  packages/preview/cram-snap/0.2.2/typst.toml
Labels: update

#1580 lacy-ubc-math-project:0.1.1
  packages/preview/lacy-ubc-math-project/0.1.1/LICENSE
  packages/preview/lacy-ubc-math-project/0.1.1/README.md
  packages/preview/lacy-ubc-math-project/0.1.1/cleanup.nu
  packages/preview/lacy-ubc-math-project/0.1.1/drawing.typ
  packages/preview/lacy-ubc-math-project/0.1.1/format.typ
  packages/preview/lacy-ubc-math-project/0.1.1/help.typ
  packages/preview/lacy-ubc-math-project/0.1.1/lib.typ
  packages/preview/lacy-ubc-math-project/0.1.1/manual.pdf
  packages/preview/lacy-ubc-math-project/0.1.1/manual.typ
  packages/preview/lacy-ubc-math-project/0.1.1/shorthand.typ
  packages/preview/lacy-ubc-math-project/0.1.1/template/assets/madeline-math.jpg
  packages/preview/lacy-ubc-math-project/0.1.1/template/common.typ
  packages/preview/lacy-ubc-math-project/0.1.1/template/project1.typ
  packages/preview/lacy-ubc-math-project/0.1.1/thumbnail.png
  packages/preview/lacy-ubc-math-project/0.1.1/typst.toml
  packages/preview/lacy-ubc-math-project/0.1.1/unsafe.typ
Labels: update

#1579 modern-cug-thesis:0.2.5
  packages/preview/modern-cug-thesis/0.2.5/LICENSE
  packages/preview/modern-cug-thesis/0.2.5/README.md
  packages/preview/modern-cug-thesis/0.2.5/layouts/appendix.typ
  packages/preview/modern-cug-thesis/0.2.5/layouts/doc.typ
  packages/preview/modern-cug-thesis/0.2.5/layouts/mainmatter.typ
  packages/preview/modern-cug-thesis/0.2.5/lib.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/fonts-display-page.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/notation.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/abstract-en.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/abstract.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/acknowledgement.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/cover.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/declaration.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/list-of-defence-commitee.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/list-of-figures-tables.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/outline.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/resume.typ
  packages/preview/modern-cug-thesis/0.2.5/pages/postgraduate/titlepage.typ
  packages/preview/modern-cug-thesis/0.2.5/template/chapters/chapter1.typ
  packages/preview/modern-cug-thesis/0.2.5/template/chapters/intro.typ
  packages/preview/modern-cug-thesis/0.2.5/template/images/A-1.1.2校徽图案.jpg
  packages/preview/modern-cug-thesis/0.2.5/template/images/示意图1.png
  packages/preview/modern-cug-thesis/0.2.5/template/ref.bib
  packages/preview/modern-cug-thesis/0.2.5/template/thesis.typ
  packages/preview/modern-cug-thesis/0.2.5/thumbnail.png
  packages/preview/modern-cug-thesis/0.2.5/typst.toml
  packages/preview/modern-cug-thesis/0.2.5/utils/anonymous-info.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/bilingual-bibliography.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/custom-cuti.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/custom-heading.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/custom-numbering.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/custom-tablex.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/datetime-display.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/double-underline.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/gb-t-7714-2005-numeric-cug.csl
  packages/preview/modern-cug-thesis/0.2.5/utils/hline.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/indent.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/invisible-heading.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/justify-text.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/number-per-chapter.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/style.typ
  packages/preview/modern-cug-thesis/0.2.5/utils/unpairs.typ
Labels: update

#1578 upb-corporate-design-slides:0.1.2
  packages/preview/upb-corporate-design-slides/0.1.2/LICENSE
  packages/preview/upb-corporate-design-slides/0.1.2/README.md
  packages/preview/upb-corporate-design-slides/0.1.2/backgrounds/content.svg
  packages/preview/upb-corporate-design-slides/0.1.2/backgrounds/section.svg
  packages/preview/upb-corporate-design-slides/0.1.2/backgrounds/title.svg
  packages/preview/upb-corporate-design-slides/0.1.2/lib.typ
  packages/preview/upb-corporate-design-slides/0.1.2/template/main.typ
  packages/preview/upb-corporate-design-slides/0.1.2/thumbnail.png
  packages/preview/upb-corporate-design-slides/0.1.2/typst.toml
Labels: update

#1581 classic-aau-report:0.2.0
  packages/preview/classic-aau-report/0.2.0/AAUgraphics/aau_logo_circle_en.svg
  packages/preview/classic-aau-report/0.2.0/AAUgraphics/aau_logo_da.svg
  packages/preview/classic-aau-report/0.2.0/AAUgraphics/aau_logo_en.svg
  packages/preview/classic-aau-report/0.2.0/AAUgraphics/aau_waves.svg
  packages/preview/classic-aau-report/0.2.0/LICENSE
  packages/preview/classic-aau-report/0.2.0/README.md
  packages/preview/classic-aau-report/0.2.0/lib.typ
  packages/preview/classic-aau-report/0.2.0/template/appendices/scripting.typ
  packages/preview/classic-aau-report/0.2.0/template/chapters/conclusion.typ
  packages/preview/classic-aau-report/0.2.0/template/chapters/custom-macros.typ
  packages/preview/classic-aau-report/0.2.0/template/chapters/introduction.typ
  packages/preview/classic-aau-report/0.2.0/template/chapters/problem-analysis.typ
  packages/preview/classic-aau-report/0.2.0/template/figures/.gitkeep
  packages/preview/classic-aau-report/0.2.0/template/main.typ
  packages/preview/classic-aau-report/0.2.0/template/references.bib
  packages/preview/classic-aau-report/0.2.0/template/setup/macros.typ
  packages/preview/classic-aau-report/0.2.0/template/setup/todo.typ
  packages/preview/classic-aau-report/0.2.0/thumbnail.png
  packages/preview/classic-aau-report/0.2.0/typst.toml
Labels: update

#1543 minimal-presentation:0.4.0
  packages/preview/minimal-presentation/0.4.0/LICENSE
  packages/preview/minimal-presentation/0.4.0/README.md
  packages/preview/minimal-presentation/0.4.0/lib.typ
  packages/preview/minimal-presentation/0.4.0/template/image_1.jpg
  packages/preview/minimal-presentation/0.4.0/template/logo.svg
  packages/preview/minimal-presentation/0.4.0/template/logo_light.svg
  packages/preview/minimal-presentation/0.4.0/template/main.typ
  packages/preview/minimal-presentation/0.4.0/thumbnail.png
  packages/preview/minimal-presentation/0.4.0/typst.toml
Labels: update

#1584 lemmify:0.1.7
  packages/preview/lemmify/0.1.7/LICENSE
  packages/preview/lemmify/0.1.7/README.md
  packages/preview/lemmify/0.1.7/src/lib.typ
  packages/preview/lemmify/0.1.7/src/styles.typ
  packages/preview/lemmify/0.1.7/src/translations.typ
  packages/preview/lemmify/0.1.7/src/util.typ
  packages/preview/lemmify/0.1.7/typst.toml
Labels: update

#1585 echarm:0.2.0
  packages/preview/echarm/0.2.0/LICENSE
  packages/preview/echarm/0.2.0/README.md
  packages/preview/echarm/0.2.0/echarm.kbc1
  packages/preview/echarm/0.2.0/examples/candlestick.png
  packages/preview/echarm/0.2.0/examples/candlestick.typ
  packages/preview/echarm/0.2.0/examples/gauge.png
  packages/preview/echarm/0.2.0/examples/gauge.typ
  packages/preview/echarm/0.2.0/examples/mixed_charts.png
  packages/preview/echarm/0.2.0/examples/mixed_charts.typ
  packages/preview/echarm/0.2.0/examples/pie.png
  packages/preview/echarm/0.2.0/examples/pie.typ
  packages/preview/echarm/0.2.0/examples/radar.png
  packages/preview/echarm/0.2.0/examples/radar.typ
  packages/preview/echarm/0.2.0/examples/scatter.png
  packages/preview/echarm/0.2.0/examples/scatter.typ
  packages/preview/echarm/0.2.0/lib.typ
  packages/preview/echarm/0.2.0/typst.toml
Labels: update

#1586 modern-report-umfds:0.1.2
  packages/preview/modern-report-umfds/0.1.2/LICENSE
  packages/preview/modern-report-umfds/0.1.2/README.md
  packages/preview/modern-report-umfds/0.1.2/src/assets/fds.png
  packages/preview/modern-report-umfds/0.1.2/src/assets/um.png
  packages/preview/modern-report-umfds/0.1.2/src/lib.typ
  packages/preview/modern-report-umfds/0.1.2/template/main.typ
  packages/preview/modern-report-umfds/0.1.2/template/refs.bib
  packages/preview/modern-report-umfds/0.1.2/thumbnail.png
  packages/preview/modern-report-umfds/0.1.2/typst.toml
Labels: update

#1582 lucky-icml:0.7.0
  packages/preview/lucky-icml/0.7.0/LICENSE
  packages/preview/lucky-icml/0.7.0/README.md
  packages/preview/lucky-icml/0.7.0/icml.csl
  packages/preview/lucky-icml/0.7.0/icml.typ
  packages/preview/lucky-icml/0.7.0/icml2024.typ
  packages/preview/lucky-icml/0.7.0/icml2025.typ
  packages/preview/lucky-icml/0.7.0/template/appendix.typ
  packages/preview/lucky-icml/0.7.0/template/icml-numpapers.svg
  packages/preview/lucky-icml/0.7.0/template/logo.typ
  packages/preview/lucky-icml/0.7.0/template/main.bib
  packages/preview/lucky-icml/0.7.0/template/main.typ
  packages/preview/lucky-icml/0.7.0/thumbnail.png
  packages/preview/lucky-icml/0.7.0/typst.toml
Labels: update

#1587 stundenzettel:0.1.0
  packages/preview/stundenzettel/0.1.0/LICENSE
  packages/preview/stundenzettel/0.1.0/README.md
  packages/preview/stundenzettel/0.1.0/lib.typ
  packages/preview/stundenzettel/0.1.0/template/main.typ
  packages/preview/stundenzettel/0.1.0/thumbnail.png
  packages/preview/stundenzettel/0.1.0/typst.toml
Labels: new

#1592 basic-report:0.1.1
  packages/preview/basic-report/0.1.1/LICENSE
  packages/preview/basic-report/0.1.1/README.md
  packages/preview/basic-report/0.1.1/lib.typ
  packages/preview/basic-report/0.1.1/main.typ
  packages/preview/basic-report/0.1.1/template/assets/aerospace-engineering.png
  packages/preview/basic-report/0.1.1/template/main.typ
  packages/preview/basic-report/0.1.1/thumbnail.png
  packages/preview/basic-report/0.1.1/titlepage.typ
  packages/preview/basic-report/0.1.1/typst.toml
Labels: update

#1500 casson-uom-thesis:0.1.0
  packages/preview/casson-uom-thesis/0.1.0/LICENSE
  packages/preview/casson-uom-thesis/0.1.0/README.md
  packages/preview/casson-uom-thesis/0.1.0/casson-uom-thesis.typ
  packages/preview/casson-uom-thesis/0.1.0/template/image.svg
  packages/preview/casson-uom-thesis/0.1.0/template/main.typ
  packages/preview/casson-uom-thesis/0.1.0/template/references.yml
  packages/preview/casson-uom-thesis/0.1.0/thumbnail.png
  packages/preview/casson-uom-thesis/0.1.0/typst.toml
  packages/preview/casson-uom-thesis/0.1.0/uom_logo.svg
Labels: new

#1600 ez-today:0.3.0
  packages/preview/ez-today/0.3.0/LICENSE
  packages/preview/ez-today/0.3.0/README.md
  packages/preview/ez-today/0.3.0/examples/example.typ
  packages/preview/ez-today/0.3.0/ez-today.typ
  packages/preview/ez-today/0.3.0/typst.toml
Labels: update

#1589 modern-whs-thesis:0.1.0
  packages/preview/modern-whs-thesis/0.1.0/README.md
  packages/preview/modern-whs-thesis/0.1.0/example/acronyms.typ
  packages/preview/modern-whs-thesis/0.1.0/example/bibliography.bib
  packages/preview/modern-whs-thesis/0.1.0/example/chapters/00_abstract.typ
  packages/preview/modern-whs-thesis/0.1.0/example/chapters/01_introduction.typ
  packages/preview/modern-whs-thesis/0.1.0/example/chapters/02_definitions.typ
  packages/preview/modern-whs-thesis/0.1.0/example/chapters/03_concept.typ
  packages/preview/modern-whs-thesis/0.1.0/example/chapters/04_implementation.typ
  packages/preview/modern-whs-thesis/0.1.0/example/chapters/05_conclusion.typ
  packages/preview/modern-whs-thesis/0.1.0/example/main.typ
  packages/preview/modern-whs-thesis/0.1.0/example/meta.typ
  packages/preview/modern-whs-thesis/0.1.0/template/elements.typ
  packages/preview/modern-whs-thesis/0.1.0/template/iso690-author-date-de.csl
  packages/preview/modern-whs-thesis/0.1.0/template/lib.typ
  packages/preview/modern-whs-thesis/0.1.0/template/partial/affidavit.typ
  packages/preview/modern-whs-thesis/0.1.0/template/partial/glossar.typ
  packages/preview/modern-whs-thesis/0.1.0/template/partial/images/background.png
  packages/preview/modern-whs-thesis/0.1.0/template/partial/title.typ
  packages/preview/modern-whs-thesis/0.1.0/template/settings.typ
  packages/preview/modern-whs-thesis/0.1.0/thumbnail.png
  packages/preview/modern-whs-thesis/0.1.0/typst.toml
Labels: new

#1601 colorful-boxes:1.4.2
  packages/preview/colorful-boxes/1.4.2/LICENSE
  packages/preview/colorful-boxes/1.4.2/README.md
  packages/preview/colorful-boxes/1.4.2/background.svg
  packages/preview/colorful-boxes/1.4.2/examples/colorbox.pdf
  packages/preview/colorful-boxes/1.4.2/examples/colorbox.png
  packages/preview/colorful-boxes/1.4.2/examples/colorbox.typ
  packages/preview/colorful-boxes/1.4.2/examples/outline-colorbox.pdf
  packages/preview/colorful-boxes/1.4.2/examples/outline-colorbox.png
  packages/preview/colorful-boxes/1.4.2/examples/outline-colorbox.typ
  packages/preview/colorful-boxes/1.4.2/examples/slanted-colorbox.pdf
  packages/preview/colorful-boxes/1.4.2/examples/slanted-colorbox.png
  packages/preview/colorful-boxes/1.4.2/examples/slanted-colorbox.typ
  packages/preview/colorful-boxes/1.4.2/examples/stickybox.pdf
  packages/preview/colorful-boxes/1.4.2/examples/stickybox.png
  packages/preview/colorful-boxes/1.4.2/examples/stickybox.typ
  packages/preview/colorful-boxes/1.4.2/lib.typ
  packages/preview/colorful-boxes/1.4.2/tape.svg
  packages/preview/colorful-boxes/1.4.2/typst.toml
Labels: update

#1603 color-my-agda:0.1.0
  packages/preview/color-my-agda/0.1.0/Agda.sublime-syntax
  packages/preview/color-my-agda/0.1.0/LICENSE
  packages/preview/color-my-agda/0.1.0/README.md
  packages/preview/color-my-agda/0.1.0/main.typ
  packages/preview/color-my-agda/0.1.0/typst.toml
Labels: new

#1599 codex-woltiensis:0.1.0
  packages/preview/codex-woltiensis/0.1.0/README.md
  packages/preview/codex-woltiensis/0.1.0/format/chant_format.typ
  packages/preview/codex-woltiensis/0.1.0/format/chant_style.typ
  packages/preview/codex-woltiensis/0.1.0/format/chapter_format.typ
  packages/preview/codex-woltiensis/0.1.0/format/chapter_style.typ
  packages/preview/codex-woltiensis/0.1.0/format/constant.typ
  packages/preview/codex-woltiensis/0.1.0/format/index_format.typ
  packages/preview/codex-woltiensis/0.1.0/format/index_style.typ
  packages/preview/codex-woltiensis/0.1.0/format/utils.typ
  packages/preview/codex-woltiensis/0.1.0/lib.typ
  packages/preview/codex-woltiensis/0.1.0/typst.toml
Labels: new

#1596 ape:0.1.0
  packages/preview/ape/0.1.0/README.md
  packages/preview/ape/0.1.0/figure/drawing.typ
  packages/preview/ape/0.1.0/figure/plotting.typ
  packages/preview/ape/0.1.0/lib.typ
  packages/preview/ape/0.1.0/style/apply-style.typ
  packages/preview/ape/0.1.0/style/code-display.typ
  packages/preview/ape/0.1.0/style/doc.typ
  packages/preview/ape/0.1.0/style/front-pages.typ
  packages/preview/ape/0.1.0/style/header-footer.typ
  packages/preview/ape/0.1.0/style/outline.typ
  packages/preview/ape/0.1.0/style/styles/colored.typ
  packages/preview/ape/0.1.0/style/styles/numbered.typ
  packages/preview/ape/0.1.0/style/styles/plain.typ
  packages/preview/ape/0.1.0/style/styles/presentation.typ
  packages/preview/ape/0.1.0/template/main.typ
  packages/preview/ape/0.1.0/thumbnail.png
  packages/preview/ape/0.1.0/tools/formatting.typ
  packages/preview/ape/0.1.0/tools/shortcuts.typ
  packages/preview/ape/0.1.0/typst.toml
Labels: new

#1591 modern-whs-assignment:0.1.0
  packages/preview/modern-whs-assignment/0.1.0/README.md
  packages/preview/modern-whs-assignment/0.1.0/example/chapters/01_introduction.typ
  packages/preview/modern-whs-assignment/0.1.0/example/main.typ
  packages/preview/modern-whs-assignment/0.1.0/example/meta.typ
  packages/preview/modern-whs-assignment/0.1.0/example/references.bib
  packages/preview/modern-whs-assignment/0.1.0/template/images/logo.png
  packages/preview/modern-whs-assignment/0.1.0/template/lib.typ
  packages/preview/modern-whs-assignment/0.1.0/template/partial/iso690-author-date-de.csl
  packages/preview/modern-whs-assignment/0.1.0/template/partial/title.typ
  packages/preview/modern-whs-assignment/0.1.0/template/util.typ
  packages/preview/modern-whs-assignment/0.1.0/thumbnail.png
  packages/preview/modern-whs-assignment/0.1.0/typst.toml
Labels: new

#1602 modern-cv:0.8.0
  packages/preview/modern-cv/0.8.0/LICENSE
  packages/preview/modern-cv/0.8.0/README.md
  packages/preview/modern-cv/0.8.0/assets/images/coverletter.png
  packages/preview/modern-cv/0.8.0/assets/images/coverletter2.png
  packages/preview/modern-cv/0.8.0/assets/images/resume.png
  packages/preview/modern-cv/0.8.0/assets/images/resume2.png
  packages/preview/modern-cv/0.8.0/assets/images/typst_web_editor.png
  packages/preview/modern-cv/0.8.0/lang.toml
  packages/preview/modern-cv/0.8.0/lib.typ
  packages/preview/modern-cv/0.8.0/template/coverletter.typ
  packages/preview/modern-cv/0.8.0/template/coverletter2.typ
  packages/preview/modern-cv/0.8.0/template/profile.png
  packages/preview/modern-cv/0.8.0/template/resume.typ
  packages/preview/modern-cv/0.8.0/typst.toml
Labels: update

#1598 minimal-thesis-luebeck:0.1.0
  packages/preview/minimal-thesis-luebeck/0.1.0/LICENSE
  packages/preview/minimal-thesis-luebeck/0.1.0/README.md
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/abstract.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/acknowledgement.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/acronyms.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/disclaimer.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/titlepage.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/utils/print-page-break.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/config/utils/todo.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/images/slogan.png
  packages/preview/minimal-thesis-luebeck/0.1.0/template/images/top-left.png
  packages/preview/minimal-thesis-luebeck/0.1.0/template/images/top-right.png
  packages/preview/minimal-thesis-luebeck/0.1.0/template/texts/abstract-de.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/texts/abstract-en.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/texts/acknowledgement.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/texts/appendix.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/texts/tutorial.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/template/thesis.bib
  packages/preview/minimal-thesis-luebeck/0.1.0/template/thesis.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/thesis-function.typ
  packages/preview/minimal-thesis-luebeck/0.1.0/thumbnail.png
  packages/preview/minimal-thesis-luebeck/0.1.0/typst.toml
Labels: new

#1604 modern-acad-cv:0.1.2
  packages/preview/modern-acad-cv/0.1.2/LICENSE
  packages/preview/modern-acad-cv/0.1.2/README.md
  packages/preview/modern-acad-cv/0.1.2/assets/example1.png
  packages/preview/modern-acad-cv/0.1.2/assets/example2.png
  packages/preview/modern-acad-cv/0.1.2/assets/example3.png
  packages/preview/modern-acad-cv/0.1.2/lib.typ
  packages/preview/modern-acad-cv/0.1.2/template/dbs/committee.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/conferences.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/education.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/grants.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/i18n.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/refs.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/skills.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/talks.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/teaching.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/training.yaml
  packages/preview/modern-acad-cv/0.1.2/template/dbs/work.yaml
  packages/preview/modern-acad-cv/0.1.2/template/example.typ
  packages/preview/modern-acad-cv/0.1.2/template/metadata.yaml
  packages/preview/modern-acad-cv/0.1.2/typst.toml
Labels: update

#1609 moderner-cv:0.1.2
  packages/preview/moderner-cv/0.1.2/LICENSE
  packages/preview/moderner-cv/0.1.2/README.md
  packages/preview/moderner-cv/0.1.2/assets/thumbnail.png
  packages/preview/moderner-cv/0.1.2/lib.typ
  packages/preview/moderner-cv/0.1.2/template/cv.typ
  packages/preview/moderner-cv/0.1.2/typst.toml
Labels: update

#1611 efilrst:0.3.1
  packages/preview/efilrst/0.3.1/.gitignore
  packages/preview/efilrst/0.3.1/LICENSE
  packages/preview/efilrst/0.3.1/README.md
  packages/preview/efilrst/0.3.1/img/image.png
  packages/preview/efilrst/0.3.1/src/lib.typ
  packages/preview/efilrst/0.3.1/typst.toml
Labels: update

#1606 brilliant-cv:2.0.4
  packages/preview/brilliant-cv/2.0.4/LICENSE
  packages/preview/brilliant-cv/2.0.4/README.md
  packages/preview/brilliant-cv/2.0.4/cv.typ
  packages/preview/brilliant-cv/2.0.4/docs/docs-template.typ
  packages/preview/brilliant-cv/2.0.4/docs/docs.typ
  packages/preview/brilliant-cv/2.0.4/letter.typ
  packages/preview/brilliant-cv/2.0.4/lib.typ
  packages/preview/brilliant-cv/2.0.4/metadata.toml.schema.json
  packages/preview/brilliant-cv/2.0.4/template/cv.typ
  packages/preview/brilliant-cv/2.0.4/template/letter.typ
  packages/preview/brilliant-cv/2.0.4/template/metadata.toml
  packages/preview/brilliant-cv/2.0.4/template/modules_en/certificates.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_en/education.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_en/professional.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_en/projects.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_en/publications.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_en/skills.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_fr/certificates.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_fr/education.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_fr/professional.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_fr/projects.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_fr/publications.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_fr/skills.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_zh/certificates.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_zh/education.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_zh/professional.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_zh/projects.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_zh/publications.typ
  packages/preview/brilliant-cv/2.0.4/template/modules_zh/skills.typ
  packages/preview/brilliant-cv/2.0.4/template/src/avatar.png
  packages/preview/brilliant-cv/2.0.4/template/src/logos/abc_company.png
  packages/preview/brilliant-cv/2.0.4/template/src/logos/pqr_corp.png
  packages/preview/brilliant-cv/2.0.4/template/src/logos/ucla.png
  packages/preview/brilliant-cv/2.0.4/template/src/logos/xyz_corp.png
  packages/preview/brilliant-cv/2.0.4/template/src/publications.bib
  packages/preview/brilliant-cv/2.0.4/template/src/signature.png
  packages/preview/brilliant-cv/2.0.4/thumbnail.png
  packages/preview/brilliant-cv/2.0.4/typst.toml
  packages/preview/brilliant-cv/2.0.4/utils/injection.typ
  packages/preview/brilliant-cv/2.0.4/utils/lang.typ
  packages/preview/brilliant-cv/2.0.4/utils/styles.typ
Labels: update

#1605 ennui-ur-report:0.1.0
  packages/preview/ennui-ur-report/0.1.0/LICENSE
  packages/preview/ennui-ur-report/0.1.0/README.md
  packages/preview/ennui-ur-report/0.1.0/assets/UNIVRENNES_LOGOnoir.svg
  packages/preview/ennui-ur-report/0.1.0/assets/inria_logo_rouge.svg
  packages/preview/ennui-ur-report/0.1.0/assets/istic.png
  packages/preview/ennui-ur-report/0.1.0/examples/compte-rendu.typ
  packages/preview/ennui-ur-report/0.1.0/examples/rapport-stage.typ
  packages/preview/ennui-ur-report/0.1.0/lib.typ
  packages/preview/ennui-ur-report/0.1.0/thumbnail.png
  packages/preview/ennui-ur-report/0.1.0/typst.toml
Labels: new

#1616 timeliney:0.2.0
  packages/preview/timeliney/0.2.0/LICENSE
  packages/preview/timeliney/0.2.0/README.md
  packages/preview/timeliney/0.2.0/manual.pdf
  packages/preview/timeliney/0.2.0/manual.typ
  packages/preview/timeliney/0.2.0/sample.png
  packages/preview/timeliney/0.2.0/sample.typ
  packages/preview/timeliney/0.2.0/timeliney.typ
  packages/preview/timeliney/0.2.0/typst.toml
Labels: update

#1615 paris-saclay-thesis-flat:1.0.2
  packages/preview/paris-saclay-thesis-flat/1.0.2/LICENSE
  packages/preview/paris-saclay-thesis-flat/1.0.2/README.md
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/2MIB.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/AAIF.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/ABIES.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/BIOSIGNE.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/CBMS.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/DEM.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/EDMH.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/EDOM.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/EDSP.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/EOBE.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/INTERFACES.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/ITFA.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/PHENIICS.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/PIF.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/README.md
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/SDSV.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/SEIF.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/SEVE.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/SMEMAG.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/SSH.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/SSMMH.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/STIC.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/img/universite-paris-saclay.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/src/lib.typ
  packages/preview/paris-saclay-thesis-flat/1.0.2/template/bib.yml
  packages/preview/paris-saclay-thesis-flat/1.0.2/template/main.typ
  packages/preview/paris-saclay-thesis-flat/1.0.2/thumbnails/p1.png
  packages/preview/paris-saclay-thesis-flat/1.0.2/typst.toml
Labels: new

#1613 examify:0.1.0
  packages/preview/examify/0.1.0/LICENSE
  packages/preview/examify/0.1.0/README.md
  packages/preview/examify/0.1.0/lib.typ
  packages/preview/examify/0.1.0/template/main.typ
  packages/preview/examify/0.1.0/thumbnail.png
  packages/preview/examify/0.1.0/typst.toml
Labels: new

#1618 problemst:0.1.1
  packages/preview/problemst/0.1.1/LICENSE.md
  packages/preview/problemst/0.1.1/README.md
  packages/preview/problemst/0.1.1/pset.typ
  packages/preview/problemst/0.1.1/template/main.typ
  packages/preview/problemst/0.1.1/thumbnail.png
  packages/preview/problemst/0.1.1/typst.toml
Labels: update

#1619 Add more context to bundling errors
  bundler/src/main.rs
Labels: meta

#1608 sdu-touying-simpl:0.2.0
  packages/preview/sdu-touying-simpl/0.2.0/LICENSE
  packages/preview/sdu-touying-simpl/0.2.0/README.md
  packages/preview/sdu-touying-simpl/0.2.0/dependency.typ
  packages/preview/sdu-touying-simpl/0.2.0/example/figures/main.png
  packages/preview/sdu-touying-simpl/0.2.0/example/main.typ
  packages/preview/sdu-touying-simpl/0.2.0/img/brand-rust.svg
  packages/preview/sdu-touying-simpl/0.2.0/img/github-mark-white.svg
  packages/preview/sdu-touying-simpl/0.2.0/img/sdu.png
  packages/preview/sdu-touying-simpl/0.2.0/lib.typ
  packages/preview/sdu-touying-simpl/0.2.0/src/call-out.typ
  packages/preview/sdu-touying-simpl/0.2.0/typst.toml
Labels: update

#1620 examify:0.1.1
  packages/preview/examify/0.1.1/.gitignore
  packages/preview/examify/0.1.1/LICENSE
  packages/preview/examify/0.1.1/README.md
  packages/preview/examify/0.1.1/lib.typ
  packages/preview/examify/0.1.1/template/main.typ
  packages/preview/examify/0.1.1/thumbnail.png
  packages/preview/examify/0.1.1/typst.toml
Labels: update

#1614 shuxuejuan:0.1.0
  packages/preview/shuxuejuan/0.1.0/LICENSE
  packages/preview/shuxuejuan/0.1.0/README.md
  packages/preview/shuxuejuan/0.1.0/examples/example.typ
  packages/preview/shuxuejuan/0.1.0/lib.typ
  packages/preview/shuxuejuan/0.1.0/src/answer.typ
  packages/preview/shuxuejuan/0.1.0/src/env.typ
  packages/preview/shuxuejuan/0.1.0/src/export.typ
  packages/preview/shuxuejuan/0.1.0/src/question-group.typ
  packages/preview/shuxuejuan/0.1.0/src/question.typ
  packages/preview/shuxuejuan/0.1.0/src/reference.typ
  packages/preview/shuxuejuan/0.1.0/src/utils.typ
  packages/preview/shuxuejuan/0.1.0/typst.toml
Labels: new

#1621 flow:0.2.0
  packages/preview/flow/0.2.0/CHANGELOG.md
  packages/preview/flow/0.2.0/LICENSE.md
  packages/preview/flow/0.2.0/README.md
  packages/preview/flow/0.2.0/asset/halcyon.tmTheme
  packages/preview/flow/0.2.0/src/callout.typ
  packages/preview/flow/0.2.0/src/cfg.typ
  packages/preview/flow/0.2.0/src/checkbox.typ
  packages/preview/flow/0.2.0/src/gfx/draw.typ
  packages/preview/flow/0.2.0/src/gfx/maybe-stub.typ
  packages/preview/flow/0.2.0/src/gfx/mod.typ
  packages/preview/flow/0.2.0/src/gfx/render.typ
  packages/preview/flow/0.2.0/src/gfx/stub.typ
  packages/preview/flow/0.2.0/src/gfx/stub/draw.typ
  packages/preview/flow/0.2.0/src/gfx/util.typ
  packages/preview/flow/0.2.0/src/info.typ
  packages/preview/flow/0.2.0/src/keywords.typ
  packages/preview/flow/0.2.0/src/lib.typ
  packages/preview/flow/0.2.0/src/palette.typ
  packages/preview/flow/0.2.0/src/template.typ
  packages/preview/flow/0.2.0/src/tyck.typ
  packages/preview/flow/0.2.0/src/util/mod.typ
  packages/preview/flow/0.2.0/src/util/preset/calculus.typ
  packages/preview/flow/0.2.0/src/util/preset/linalg.typ
  packages/preview/flow/0.2.0/src/util/preset/mod.typ
  packages/preview/flow/0.2.0/src/util/preset/ops.typ
  packages/preview/flow/0.2.0/src/util/preset/quantum.typ
  packages/preview/flow/0.2.0/template/main.typ
  packages/preview/flow/0.2.0/thumbnail/page-1.png
  packages/preview/flow/0.2.0/typst.toml
  packages/preview/flow/0.2.0/util/flow-export
Labels: update

#1622 ssrn-scribe:0.7.0
  packages/preview/ssrn-scribe/0.7.0/README.md
  packages/preview/ssrn-scribe/0.7.0/paper_template.typ
  packages/preview/ssrn-scribe/0.7.0/template/bib.bib
  packages/preview/ssrn-scribe/0.7.0/template/extra.typ
  packages/preview/ssrn-scribe/0.7.0/template/main.typ
  packages/preview/ssrn-scribe/0.7.0/thumbnail.png
  packages/preview/ssrn-scribe/0.7.0/typst.toml
Labels: update

#1624 mcm-scaffold:0.2.0
  packages/preview/mcm-scaffold/0.2.0/LICENSE
  packages/preview/mcm-scaffold/0.2.0/README.md
  packages/preview/mcm-scaffold/0.2.0/lib.typ
  packages/preview/mcm-scaffold/0.2.0/template/figures/image1.png
  packages/preview/mcm-scaffold/0.2.0/template/main.typ
  packages/preview/mcm-scaffold/0.2.0/template/references.bib
  packages/preview/mcm-scaffold/0.2.0/template/references.yml
  packages/preview/mcm-scaffold/0.2.0/thumbnail.png
  packages/preview/mcm-scaffold/0.2.0/typst.toml
Labels: update

#1625 ez-today:1.0.0
  packages/preview/ez-today/1.0.0/LICENSE
  packages/preview/ez-today/1.0.0/README.md
  packages/preview/ez-today/1.0.0/examples/example.typ
  packages/preview/ez-today/1.0.0/ez-today.typ
  packages/preview/ez-today/1.0.0/typst.toml
Labels: update

#1626 polylux:0.4.0
  packages/preview/polylux/0.4.0/LICENSE
  packages/preview/polylux/0.4.0/README.md
  packages/preview/polylux/0.4.0/assets/logo.png
  packages/preview/polylux/0.4.0/assets/logo2.png
  packages/preview/polylux/0.4.0/assets/polylux-logo.svg
  packages/preview/polylux/0.4.0/examples/.gitignore
  packages/preview/polylux/0.4.0/examples/demo.pdfpc
  packages/preview/polylux/0.4.0/examples/demo.typ
  packages/preview/polylux/0.4.0/examples/literature.bib
  packages/preview/polylux/0.4.0/examples/minimal.png
  packages/preview/polylux/0.4.0/examples/minimal.typ
  packages/preview/polylux/0.4.0/src/logic.typ
  packages/preview/polylux/0.4.0/src/polylux.typ
  packages/preview/polylux/0.4.0/src/toolbox/pdfpc.typ
  packages/preview/polylux/0.4.0/src/toolbox/toolbox-impl.typ
  packages/preview/polylux/0.4.0/src/toolbox/toolbox.typ
  packages/preview/polylux/0.4.0/typst.toml
Labels: update

#1629 glossy:0.6.0
  packages/preview/glossy/0.6.0/.gitignore
  packages/preview/glossy/0.6.0/LICENSE
  packages/preview/glossy/0.6.0/README.md
  packages/preview/glossy/0.6.0/bin/autotest.sh
  packages/preview/glossy/0.6.0/lib.typ
  packages/preview/glossy/0.6.0/src/gloss.typ
  packages/preview/glossy/0.6.0/src/schemas.typ
  packages/preview/glossy/0.6.0/src/themes.typ
  packages/preview/glossy/0.6.0/src/themes/academic.typ
  packages/preview/glossy/0.6.0/src/themes/basic.typ
  packages/preview/glossy/0.6.0/src/themes/chicago-index.typ
  packages/preview/glossy/0.6.0/src/themes/compact.typ
  packages/preview/glossy/0.6.0/src/themes/table.typ
  packages/preview/glossy/0.6.0/src/themes/twocol.typ
  packages/preview/glossy/0.6.0/src/utils.typ
  packages/preview/glossy/0.6.0/tests/abbreviated-syntax/ref/1.png
  packages/preview/glossy/0.6.0/tests/abbreviated-syntax/test.typ
  packages/preview/glossy/0.6.0/tests/demo/ref/1.png
  packages/preview/glossy/0.6.0/tests/demo/test.typ
  packages/preview/glossy/0.6.0/tests/determine-article/ref/1.png
  packages/preview/glossy/0.6.0/tests/determine-article/test.typ
  packages/preview/glossy/0.6.0/tests/format-term/ref/1.png
  packages/preview/glossy/0.6.0/tests/format-term/test.typ
  packages/preview/glossy/0.6.0/tests/forward-links/ref/1.png
  packages/preview/glossy/0.6.0/tests/forward-links/test.typ
  packages/preview/glossy/0.6.0/tests/group-specified/abbreviations.json
  packages/preview/glossy/0.6.0/tests/group-specified/ref/1.png
  packages/preview/glossy/0.6.0/tests/group-specified/ref/2.png
  packages/preview/glossy/0.6.0/tests/group-specified/ref/3.png
  packages/preview/glossy/0.6.0/tests/group-specified/ref/4.png
  packages/preview/glossy/0.6.0/tests/group-specified/test.typ
  packages/preview/glossy/0.6.0/tests/no-sort/glossary.yml
  packages/preview/glossy/0.6.0/tests/no-sort/ref/1.png
  packages/preview/glossy/0.6.0/tests/no-sort/test.typ
  packages/preview/glossy/0.6.0/tests/noref/ref/1.png
  packages/preview/glossy/0.6.0/tests/noref/test.typ
  packages/preview/glossy/0.6.0/tests/page-numbers/ref/1.png
  packages/preview/glossy/0.6.0/tests/page-numbers/ref/2.png
  packages/preview/glossy/0.6.0/tests/page-numbers/ref/3.png
  packages/preview/glossy/0.6.0/tests/page-numbers/ref/4.png
  packages/preview/glossy/0.6.0/tests/page-numbers/test.typ
  packages/preview/glossy/0.6.0/tests/pluralize/test.typ
  packages/preview/glossy/0.6.0/tests/refs-exhaustive/test.typ
  packages/preview/glossy/0.6.0/tests/refs-in-captions/ref/1.png
  packages/preview/glossy/0.6.0/tests/refs-in-captions/test.typ
  packages/preview/glossy/0.6.0/tests/sorting/ref/1.png
  packages/preview/glossy/0.6.0/tests/sorting/test.typ
  packages/preview/glossy/0.6.0/tests/theme-gallery/ref/1.png
  packages/preview/glossy/0.6.0/tests/theme-gallery/test.typ
  packages/preview/glossy/0.6.0/tests/utf-handling/glossary.yml
  packages/preview/glossy/0.6.0/tests/utf-handling/ref/1.png
  packages/preview/glossy/0.6.0/tests/utf-handling/test.typ
  packages/preview/glossy/0.6.0/themeshots.png
  packages/preview/glossy/0.6.0/thumbnail.png
  packages/preview/glossy/0.6.0/typst.toml
Labels: update

#1633 finely-crafted-cv:0.3.0
  packages/preview/finely-crafted-cv/0.3.0/.gitignore
  packages/preview/finely-crafted-cv/0.3.0/LICENSE
  packages/preview/finely-crafted-cv/0.3.0/README.md
  packages/preview/finely-crafted-cv/0.3.0/lib.typ
  packages/preview/finely-crafted-cv/0.3.0/src/constants.typ
  packages/preview/finely-crafted-cv/0.3.0/src/helpers.typ
  packages/preview/finely-crafted-cv/0.3.0/src/resume.typ
  packages/preview/finely-crafted-cv/0.3.0/src/state.typ
  packages/preview/finely-crafted-cv/0.3.0/template/assets/my-qr-code.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/coral.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/earth.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/email.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/graduation-cap.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/linkedin.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/microscope.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/palm-tree.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/phone.svg
  packages/preview/finely-crafted-cv/0.3.0/template/icons/whale.svg
  packages/preview/finely-crafted-cv/0.3.0/template/main.typ
  packages/preview/finely-crafted-cv/0.3.0/tests/example/assets/my-qr-code.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/coral.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/earth.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/email.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/graduation-cap.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/linkedin.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/microscope.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/palm-tree.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/phone.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/icons/whale.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/example/ref/1.png
  packages/preview/finely-crafted-cv/0.3.0/tests/example/test.typ
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/assets/my-qr-code.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/icons/coral.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/icons/earth.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/icons/graduation-cap.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/icons/microscope.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/icons/palm-tree.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/icons/whale.svg
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/ref/1.png
  packages/preview/finely-crafted-cv/0.3.0/tests/linkedin-none/test.typ
  packages/preview/finely-crafted-cv/0.3.0/thumbnail.png
  packages/preview/finely-crafted-cv/0.3.0/typst.toml
Labels: update

#1623 rexllent:0.3.0 and zebraw:0.3.0
  packages/preview/rexllent/0.3.0/LICENSE
  packages/preview/rexllent/0.3.0/README.md
  packages/preview/rexllent/0.3.0/assets/example1.png
  packages/preview/rexllent/0.3.0/assets/example2.png
  packages/preview/rexllent/0.3.0/assets/example3.png
  packages/preview/rexllent/0.3.0/assets/example4.png
  packages/preview/rexllent/0.3.0/assets/example5.png
  packages/preview/rexllent/0.3.0/assets/example6.png
  packages/preview/rexllent/0.3.0/assets/example7.png
  packages/preview/rexllent/0.3.0/assets/excel.png
  packages/preview/rexllent/0.3.0/assets/three-line-table.png
  packages/preview/rexllent/0.3.0/lib.typ
  packages/preview/rexllent/0.3.0/mod.typ
  packages/preview/rexllent/0.3.0/rexllent.wasm
  packages/preview/rexllent/0.3.0/typst.toml
  packages/preview/zebraw/0.3.0/LICENSE
  packages/preview/zebraw/0.3.0/README.md
  packages/preview/zebraw/0.3.0/assets/example1.svg
  packages/preview/zebraw/0.3.0/assets/example2.svg
  packages/preview/zebraw/0.3.0/assets/example3.svg
  packages/preview/zebraw/0.3.0/assets/example4.svg
  packages/preview/zebraw/0.3.0/assets/example5.svg
  packages/preview/zebraw/0.3.0/assets/example6.svg
  packages/preview/zebraw/0.3.0/assets/example7.svg
  packages/preview/zebraw/0.3.0/assets/example8.svg
  packages/preview/zebraw/0.3.0/assets/line-spacing.svg
  packages/preview/zebraw/0.3.0/lib.typ
  packages/preview/zebraw/0.3.0/mod.typ
  packages/preview/zebraw/0.3.0/typst.toml
Labels: update

#1634 truthfy:0.6.0
  packages/preview/truthfy/0.6.0/LICENSE
  packages/preview/truthfy/0.6.0/README.md
  packages/preview/truthfy/0.6.0/example.pdf
  packages/preview/truthfy/0.6.0/example.typ
  packages/preview/truthfy/0.6.0/main.typ
  packages/preview/truthfy/0.6.0/typst.toml
Labels: update

#1632 basic-polylux:0.1.0
  packages/preview/basic-polylux/0.1.0/LICENSE
  packages/preview/basic-polylux/0.1.0/README.md
  packages/preview/basic-polylux/0.1.0/lib.typ
  packages/preview/basic-polylux/0.1.0/template/.gitignore
  packages/preview/basic-polylux/0.1.0/template/slides.typ
  packages/preview/basic-polylux/0.1.0/thumbnail.png
  packages/preview/basic-polylux/0.1.0/typst.toml
Labels: new

#1631 hanzi-calligraphy:0.1.0
  packages/preview/hanzi-calligraphy/0.1.0/LICENSE
  packages/preview/hanzi-calligraphy/0.1.0/README.md
  packages/preview/hanzi-calligraphy/0.1.0/imgs/template-2.png
  packages/preview/hanzi-calligraphy/0.1.0/imgs/template-3.png
  packages/preview/hanzi-calligraphy/0.1.0/lib.typ
  packages/preview/hanzi-calligraphy/0.1.0/template/template.typ
  packages/preview/hanzi-calligraphy/0.1.0/thumbnail.png
  packages/preview/hanzi-calligraphy/0.1.0/typst.toml
Labels: new

#1635 typsium:0.0.1
  packages/preview/typsium/0.0.1/LICENSE
  packages/preview/typsium/0.0.1/README.md
  packages/preview/typsium/0.0.1/lib.typ
  packages/preview/typsium/0.0.1/typst.toml
Labels: new

#1637 friendly-polylux:0.1.0
  packages/preview/friendly-polylux/0.1.0/LICENSE
  packages/preview/friendly-polylux/0.1.0/README.md
  packages/preview/friendly-polylux/0.1.0/friendly.typ
  packages/preview/friendly-polylux/0.1.0/icons/down-arrow.svg
  packages/preview/friendly-polylux/0.1.0/icons/email.svg
  packages/preview/friendly-polylux/0.1.0/icons/icons.typ
  packages/preview/friendly-polylux/0.1.0/icons/mastodon.svg
  packages/preview/friendly-polylux/0.1.0/icons/right-arrow.svg
  packages/preview/friendly-polylux/0.1.0/icons/up-arrow.svg
  packages/preview/friendly-polylux/0.1.0/icons/www-black.svg
  packages/preview/friendly-polylux/0.1.0/icons/www.svg
  packages/preview/friendly-polylux/0.1.0/lib.typ
  packages/preview/friendly-polylux/0.1.0/template/slides.typ
  packages/preview/friendly-polylux/0.1.0/thumbnail.png
  packages/preview/friendly-polylux/0.1.0/typst.toml
Labels: new

#1639 ttt-utils:0.1.3
  packages/preview/ttt-utils/0.1.3/LICENSE
  packages/preview/ttt-utils/0.1.3/README.md
  packages/preview/ttt-utils/0.1.3/lib/assignments.typ
  packages/preview/ttt-utils/0.1.3/lib/components.typ
  packages/preview/ttt-utils/0.1.3/lib/grading.typ
  packages/preview/ttt-utils/0.1.3/lib/helpers.typ
  packages/preview/ttt-utils/0.1.3/lib/layout.typ
  packages/preview/ttt-utils/0.1.3/lib/lib.typ
  packages/preview/ttt-utils/0.1.3/lib/random.typ
  packages/preview/ttt-utils/0.1.3/typst.toml
Labels: update

#1641 mannot:0.2.1
  packages/preview/mannot/0.2.1/LICENSE
  packages/preview/mannot/0.2.1/README.md
  packages/preview/mannot/0.2.1/docs/doc-template.typ
  packages/preview/mannot/0.2.1/docs/doc.pdf
  packages/preview/mannot/0.2.1/docs/doc.typ
  packages/preview/mannot/0.2.1/docs/tidy-style.typ
  packages/preview/mannot/0.2.1/examples/showcase.svg
  packages/preview/mannot/0.2.1/examples/showcase.typ
  packages/preview/mannot/0.2.1/examples/usage1.svg
  packages/preview/mannot/0.2.1/examples/usage1.typ
  packages/preview/mannot/0.2.1/examples/usage2.svg
  packages/preview/mannot/0.2.1/examples/usage2.typ
  packages/preview/mannot/0.2.1/examples/usage3.svg
  packages/preview/mannot/0.2.1/examples/usage3.typ
  packages/preview/mannot/0.2.1/examples/usage4.svg
  packages/preview/mannot/0.2.1/examples/usage4.typ
  packages/preview/mannot/0.2.1/examples/usage5.svg
  packages/preview/mannot/0.2.1/examples/usage5.typ
  packages/preview/mannot/0.2.1/src/annot.typ
  packages/preview/mannot/0.2.1/src/lib.typ
  packages/preview/mannot/0.2.1/src/mark.typ
  packages/preview/mannot/0.2.1/src/util.typ
  packages/preview/mannot/0.2.1/typst.toml
Labels: update

#1440 suboutline:0.1.0
  packages/preview/suboutline/0.1.0/LICENSE
  packages/preview/suboutline/0.1.0/README.md
  packages/preview/suboutline/0.1.0/lib.typ
  packages/preview/suboutline/0.1.0/typst.toml
Labels: new

#1627 minimal-thesis-luebeck:0.2.0
  packages/preview/minimal-thesis-luebeck/0.2.0/LICENSE
  packages/preview/minimal-thesis-luebeck/0.2.0/README.md
  packages/preview/minimal-thesis-luebeck/0.2.0/styles/abstract.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/styles/acknowledgement.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/styles/disclaimer.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/styles/titlepage.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/styles/toc.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/images/slogan.png
  packages/preview/minimal-thesis-luebeck/0.2.0/template/images/top-left.png
  packages/preview/minimal-thesis-luebeck/0.2.0/template/images/top-right.png
  packages/preview/minimal-thesis-luebeck/0.2.0/template/texts/abbreviations.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/texts/abstract-de.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/texts/abstract-en.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/texts/acknowledgement.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/texts/appendix.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/texts/tutorial.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/template/thesis.bib
  packages/preview/minimal-thesis-luebeck/0.2.0/template/thesis.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/thesis-template.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/thumbnail.png
  packages/preview/minimal-thesis-luebeck/0.2.0/typst.toml
  packages/preview/minimal-thesis-luebeck/0.2.0/utils/print-page-break.typ
  packages/preview/minimal-thesis-luebeck/0.2.0/utils/todo.typ
Labels: update

#1642 equate:0.3.0
  packages/preview/equate/0.3.0/LICENSE
  packages/preview/equate/0.3.0/README.md
  packages/preview/equate/0.3.0/assets/example-1.svg
  packages/preview/equate/0.3.0/assets/example-2.svg
  packages/preview/equate/0.3.0/assets/example.typ
  packages/preview/equate/0.3.0/src/equate.typ
  packages/preview/equate/0.3.0/src/lib.typ
  packages/preview/equate/0.3.0/typst.toml
Labels: update

#1638 markly:0.2.0
  packages/preview/markly/0.2.0/LICENSE
  packages/preview/markly/0.2.0/README.md
  packages/preview/markly/0.2.0/example/main.pdf
  packages/preview/markly/0.2.0/example/main.typ
  packages/preview/markly/0.2.0/example/ping-pong.jpg
  packages/preview/markly/0.2.0/img.png
  packages/preview/markly/0.2.0/img.typ
  packages/preview/markly/0.2.0/lib.typ
  packages/preview/markly/0.2.0/typst.toml
Labels: new

#1630 cheda-seu-thesis:0.3.1
  packages/preview/cheda-seu-thesis/0.3.1/.gitignore
  packages/preview/cheda-seu-thesis/0.3.1/CHANGELOG.md
  packages/preview/cheda-seu-thesis/0.3.1/LICENSE
  packages/preview/cheda-seu-thesis/0.3.1/README.md
  packages/preview/cheda-seu-thesis/0.3.1/init-files/bachelor_thesis.typ
  packages/preview/cheda-seu-thesis/0.3.1/init-files/degree_thesis.typ
  packages/preview/cheda-seu-thesis/0.3.1/init-files/demo_image/2-2a.png
  packages/preview/cheda-seu-thesis/0.3.1/init-files/demo_image/2-2b.png
  packages/preview/cheda-seu-thesis/0.3.1/init-files/demo_image/24h_rain.png
  packages/preview/cheda-seu-thesis/0.3.1/init-files/gb-t-7714-2015-numeric-seu-bachelor.csl
  packages/preview/cheda-seu-thesis/0.3.1/init-files/gb-t-7714-2015-numeric-seu-degree.csl
  packages/preview/cheda-seu-thesis/0.3.1/init-files/ref.bib
  packages/preview/cheda-seu-thesis/0.3.1/init-files/thesis.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/assets/cover_school.png
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/assets/vi/seu.png
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/assets/vi/seu_logo.png
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/assets/vi/东南大学校标文字组合.png
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/lib.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/pages/cover-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/pages/cover-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/pages/statement-bachelor-ic.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/pages/statement-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/pages/title-page-degree-cn-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/pages/title-page-degree-en-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/abstract-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/abstract-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/main-body-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/main-body-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/outline-bachelor-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/outline-degree-fn.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/parts/terminology.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/templates/bachelor.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/templates/degree.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/bachelor-footnote.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/bilingual-bibliography.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/fake-par.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/fonts.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/numbering-tools.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/packages.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/set-bachelor.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/set-degree.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/show-appendix.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/show-equation-degree.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/show-heading.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/smart-pagebreak.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/states.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/thanks.typ
  packages/preview/cheda-seu-thesis/0.3.1/seu-thesis/utils/to-string.typ
  packages/preview/cheda-seu-thesis/0.3.1/thumbnail.webp
  packages/preview/cheda-seu-thesis/0.3.1/typst.toml
Labels: update

#1644 pubmatter:0.2.0
  packages/preview/pubmatter/0.2.0/LICENSE
  packages/preview/pubmatter/0.2.0/README.md
  packages/preview/pubmatter/0.2.0/pubmatter.typ
  packages/preview/pubmatter/0.2.0/typst.toml
  packages/preview/pubmatter/0.2.0/validate-frontmatter.typ
Labels: update

#1647 hei-synd-report:0.1.0
  packages/preview/hei-synd-report/0.1.0/.gitignore
  packages/preview/hei-synd-report/0.1.0/LICENSE
  packages/preview/hei-synd-report/0.1.0/README.md
  packages/preview/hei-synd-report/0.1.0/lib/boxes.typ
  packages/preview/hei-synd-report/0.1.0/lib/constants.typ
  packages/preview/hei-synd-report/0.1.0/lib/helpers.typ
  packages/preview/hei-synd-report/0.1.0/lib/i18n.json
  packages/preview/hei-synd-report/0.1.0/lib/img/fire.svg
  packages/preview/hei-synd-report/0.1.0/lib/img/idea.svg
  packages/preview/hei-synd-report/0.1.0/lib/img/important.svg
  packages/preview/hei-synd-report/0.1.0/lib/img/info.svg
  packages/preview/hei-synd-report/0.1.0/lib/img/rocket.svg
  packages/preview/hei-synd-report/0.1.0/lib/img/todo.svg
  packages/preview/hei-synd-report/0.1.0/lib/img/warning.svg
  packages/preview/hei-synd-report/0.1.0/lib/pages-report.typ
  packages/preview/hei-synd-report/0.1.0/lib/template-report.typ
  packages/preview/hei-synd-report/0.1.0/template/main/01-intro.typ
  packages/preview/hei-synd-report/0.1.0/template/main/02-specification.typ
  packages/preview/hei-synd-report/0.1.0/template/main/03-design.typ
  packages/preview/hei-synd-report/0.1.0/template/main/04-implementation.typ
  packages/preview/hei-synd-report/0.1.0/template/main/05-validation.typ
  packages/preview/hei-synd-report/0.1.0/template/main/06-conclusion.typ
  packages/preview/hei-synd-report/0.1.0/template/metadata.typ
  packages/preview/hei-synd-report/0.1.0/template/report.typ
  packages/preview/hei-synd-report/0.1.0/template/resources/code/uss-rustacean.rs
  packages/preview/hei-synd-report/0.1.0/template/resources/img/hei.svg
  packages/preview/hei-synd-report/0.1.0/template/resources/img/project-logo.svg
  packages/preview/hei-synd-report/0.1.0/template/resources/img/synd.svg
  packages/preview/hei-synd-report/0.1.0/template/tail/bibliography.bib
  packages/preview/hei-synd-report/0.1.0/template/tail/bibliography.typ
  packages/preview/hei-synd-report/0.1.0/template/tail/glossary.typ
  packages/preview/hei-synd-report/0.1.0/thumbnail.png
  packages/preview/hei-synd-report/0.1.0/typst.toml
Labels: new

#1595 iconic-salmon-svg:2.1.0
  packages/preview/iconic-salmon-svg/2.1.0/LICENSE
  packages/preview/iconic-salmon-svg/2.1.0/README.md
  packages/preview/iconic-salmon-svg/2.1.0/examples/.gitignore
  packages/preview/iconic-salmon-svg/2.1.0/examples/examples.typ
  packages/preview/iconic-salmon-svg/2.1.0/examples/minimal_example.typ
  packages/preview/iconic-salmon-svg/2.1.0/iconic-salmon-svg-icons.typ
  packages/preview/iconic-salmon-svg/2.1.0/iconic-salmon-svg.typ
  packages/preview/iconic-salmon-svg/2.1.0/svg/Discord_icon_clyde_black_RGB.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Discord_icon_clyde_blurple_RGB.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Discord_icon_clyde_white_RGB.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Facebook_Logo_Primary.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/GitLab_icon.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Google_Scholar_logo.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Instagram_logo_2022.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/LinkedIn_icon.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Logo_of_Twitter.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/ORCID_iD.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/README.md
  packages/preview/iconic-salmon-svg/2.1.0/svg/ResearchGate_icon_SVG.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Stack_Exchange_icon.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/Stack_Overflow_icon.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/TikTok_Icon_Black.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/X_logo_2023.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/YouTube_full-color_icon_(2017).svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/codeberg-logo_icon_blue.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/codeberg-logo_icon_white.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/docker-mark-blue.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/docker-mark-white.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/github-mark-white.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/github-mark.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/gitlab-logo-500.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/gitlab-logo-600.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/mark-gradient-blue-bitbucket.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/mark-gradient-neutral-bitbucket.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/mark-gradient-white-bitbucket.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/mastodon-logo-black.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/mastodon-logo-purple.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/mastodon-logo-white.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/skype-icon.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/sourceforge-seeklogo.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/tryhackme.com.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/tryhackme_logo_icon_249349.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/vimeo-tile.svg
  packages/preview/iconic-salmon-svg/2.1.0/svg/xing-icon.svg
  packages/preview/iconic-salmon-svg/2.1.0/typst.toml
Labels: update
