Repository typst/packages, pull requests merged in 2025-04, with the labels that each got.

#2105 shiroa:0.2.2
  packages/preview/shiroa/0.2.2/LICENSE
  packages/preview/shiroa/0.2.2/README.md
  packages/preview/shiroa/0.2.2/lib.typ
  packages/preview/shiroa/0.2.2/media.typ
  packages/preview/shiroa/0.2.2/meta-and-state.typ
  packages/preview/shiroa/0.2.2/summary-internal.typ
  packages/preview/shiroa/0.2.2/summary.typ
  packages/preview/shiroa/0.2.2/supports-link.typ
  packages/preview/shiroa/0.2.2/supports-text.typ
  packages/preview/shiroa/0.2.2/sys.typ
  packages/preview/shiroa/0.2.2/template-link.typ
  packages/preview/shiroa/0.2.2/template-theme.typ
  packages/preview/shiroa/0.2.2/templates.typ
  packages/preview/shiroa/0.2.2/typst.toml
  packages/preview/shiroa/0.2.2/utils.typ
  packages/preview/shiroa/0.2.2/xcommand.typ
Labels: update

#2104 wenyuan-campaign:0.1.1
  packages/preview/wenyuan-campaign/0.1.1/LICENSE.txt
  packages/preview/wenyuan-campaign/0.1.1/README.md
  packages/preview/wenyuan-campaign/0.1.1/campaign.typ
  packages/preview/wenyuan-campaign/0.1.1/colours.typ
  packages/preview/wenyuan-campaign/0.1.1/dnditem.typ
  packages/preview/wenyuan-campaign/0.1.1/docs.pdf
  packages/preview/wenyuan-campaign/0.1.1/docs.typ
  packages/preview/wenyuan-campaign/0.1.1/footer-left.png
  packages/preview/wenyuan-campaign/0.1.1/footer-right.png
  packages/preview/wenyuan-campaign/0.1.1/sample.pdf
  packages/preview/wenyuan-campaign/0.1.1/sample.png
  packages/preview/wenyuan-campaign/0.1.1/statblock.typ
  packages/preview/wenyuan-campaign/0.1.1/template/main.typ
  packages/preview/wenyuan-campaign/0.1.1/template/snakecaller-guild.png
  packages/preview/wenyuan-campaign/0.1.1/typst.toml
Labels: update

#2090 derive-it:0.1.3
  packages/preview/derive-it/0.1.3/LICENSE
  packages/preview/derive-it/0.1.3/README.md
  packages/preview/derive-it/0.1.3/examples/example.png
  packages/preview/derive-it/0.1.3/examples/example.typ
  packages/preview/derive-it/0.1.3/examples/indentation-test.png
  packages/preview/derive-it/0.1.3/lib.typ
  packages/preview/derive-it/0.1.3/typst.toml
Labels: update

#2092 lasaveur:0.1.4 and touying2video:0.1.0
  packages/preview/lasaveur/0.1.4/README.md
  packages/preview/lasaveur/0.1.4/typst-lasaveur.typ
  packages/preview/lasaveur/0.1.4/typst.toml
  packages/preview/touying2video/0.1.0/README.md
  packages/preview/touying2video/0.1.0/p2vmeta.typ
  packages/preview/touying2video/0.1.0/typst.toml
Labels: new, update

#2106 modern-szu-thesis:0.4.0
  packages/preview/modern-szu-thesis/0.4.0/.gitignore
  packages/preview/modern-szu-thesis/0.4.0/LICENSE
  packages/preview/modern-szu-thesis/0.4.0/README.md
  packages/preview/modern-szu-thesis/0.4.0/assets/vi/nju-emblem-purple.svg
  packages/preview/modern-szu-thesis/0.4.0/assets/vi/nju-emblem.svg
  packages/preview/modern-szu-thesis/0.4.0/assets/vi/nju-name-purple.svg
  packages/preview/modern-szu-thesis/0.4.0/assets/vi/nju-name.svg
  packages/preview/modern-szu-thesis/0.4.0/assets/vi/szu.png
  packages/preview/modern-szu-thesis/0.4.0/assets/vi/szu.svg
  packages/preview/modern-szu-thesis/0.4.0/imgs/gallery.png
  packages/preview/modern-szu-thesis/0.4.0/imgs/template.png
  packages/preview/modern-szu-thesis/0.4.0/imgs/vsc-template.png
  packages/preview/modern-szu-thesis/0.4.0/imgs/webapp.png
  packages/preview/modern-szu-thesis/0.4.0/layouts/achievement.typ
  packages/preview/modern-szu-thesis/0.4.0/layouts/appendix.typ
  packages/preview/modern-szu-thesis/0.4.0/layouts/doc.typ
  packages/preview/modern-szu-thesis/0.4.0/layouts/mainmatter.typ
  packages/preview/modern-szu-thesis/0.4.0/layouts/preface.typ
  packages/preview/modern-szu-thesis/0.4.0/lib.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/acknowledgement.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/bachelor-abstract-en.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/bachelor-abstract.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/bachelor-cover.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/bachelor-decl-page.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/bachelor-outline-page.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/fonts-display-page.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/list-of-figures.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/list-of-tables.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/master-abstract-en.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/master-abstract.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/master-cover.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/master-decl-page.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/master-outline-page.typ
  packages/preview/modern-szu-thesis/0.4.0/pages/notation.typ
  packages/preview/modern-szu-thesis/0.4.0/template/bachelor-thesis.typ
  packages/preview/modern-szu-thesis/0.4.0/template/images/nju-emblem.svg
  packages/preview/modern-szu-thesis/0.4.0/template/master-thesis.typ
  packages/preview/modern-szu-thesis/0.4.0/template/ref.bib
  packages/preview/modern-szu-thesis/0.4.0/thumbnail.png
  packages/preview/modern-szu-thesis/0.4.0/typst.toml
  packages/preview/modern-szu-thesis/0.4.0/utils/bilingual-bibliography.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/custom-cuti.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/custom-heading.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/custom-numbering.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/custom-tablex.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/datetime-display.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/double-underline.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/hline.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/invisible-heading.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/justify-text.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/style.typ
  packages/preview/modern-szu-thesis/0.4.0/utils/unpairs.typ
Labels: update

#2108 typographic-resume:0.1.0
  packages/preview/typographic-resume/0.1.0/.gitignore
  packages/preview/typographic-resume/0.1.0/README.md
  packages/preview/typographic-resume/0.1.0/images/envelope-solid.svg
  packages/preview/typographic-resume/0.1.0/images/github-brands.svg
  packages/preview/typographic-resume/0.1.0/images/phone-solid.svg
  packages/preview/typographic-resume/0.1.0/package.typ
  packages/preview/typographic-resume/0.1.0/template/main.typ
  packages/preview/typographic-resume/0.1.0/thumbnail.webp
  packages/preview/typographic-resume/0.1.0/typst.toml
Labels: new

#2107 curli:0.1.0
  packages/preview/curli/0.1.0/LICENSE
  packages/preview/curli/0.1.0/README.md
  packages/preview/curli/0.1.0/src/curli.typ
  packages/preview/curli/0.1.0/src/impl.typ
  packages/preview/curli/0.1.0/typst.toml
Labels: new

#2109 tracl:0.6.1
  packages/preview/tracl/0.6.1/LICENSE
  packages/preview/tracl/0.6.1/README.md
  packages/preview/tracl/0.6.1/lib.typ
  packages/preview/tracl/0.6.1/template/association-for-computational-linguistics-blinky.csl
  packages/preview/tracl/0.6.1/template/main.typ
  packages/preview/tracl/0.6.1/thumbnail.png
  packages/preview/tracl/0.6.1/typst.toml
Labels: update

#2110 quick-sip:0.1.2
  packages/preview/quick-sip/0.1.2/LICENSE
  packages/preview/quick-sip/0.1.2/README.md
  packages/preview/quick-sip/0.1.2/lib.typ
  packages/preview/quick-sip/0.1.2/template/main.typ
  packages/preview/quick-sip/0.1.2/thumbnail.png
  packages/preview/quick-sip/0.1.2/typst.toml
Labels: update

#2113 starter-journal-article:0.3.2
  packages/preview/starter-journal-article/0.3.2/LICENSE
  packages/preview/starter-journal-article/0.3.2/README.md
  packages/preview/starter-journal-article/0.3.2/assets/basic.png
  packages/preview/starter-journal-article/0.3.2/assets/basic.typ
  packages/preview/starter-journal-article/0.3.2/assets/custom-abstract.png
  packages/preview/starter-journal-article/0.3.2/assets/custom-abstract.typ
  packages/preview/starter-journal-article/0.3.2/assets/custom-author-info.png
  packages/preview/starter-journal-article/0.3.2/assets/custom-author-info.typ
  packages/preview/starter-journal-article/0.3.2/assets/custom-title.png
  packages/preview/starter-journal-article/0.3.2/assets/custom-title.typ
  packages/preview/starter-journal-article/0.3.2/lib.typ
  packages/preview/starter-journal-article/0.3.2/template/main.typ
  packages/preview/starter-journal-article/0.3.2/template/ref.bib
  packages/preview/starter-journal-article/0.3.2/test.typ
  packages/preview/starter-journal-article/0.3.2/thumbnail.png
  packages/preview/starter-journal-article/0.3.2/typst.toml
Labels: update

#2111 humble-dtu-thesis:0.1.0
  packages/preview/humble-dtu-thesis/0.1.0/.gitignore
  packages/preview/humble-dtu-thesis/0.1.0/LICENSE
  packages/preview/humble-dtu-thesis/0.1.0/README.md
  packages/preview/humble-dtu-thesis/0.1.0/src/dtu-template/copyright.typ
  packages/preview/humble-dtu-thesis/0.1.0/src/dtu-template/frontpage-dtu.typ
  packages/preview/humble-dtu-thesis/0.1.0/src/dtu-template/last-page.typ
  packages/preview/humble-dtu-thesis/0.1.0/src/functions.typ
  packages/preview/humble-dtu-thesis/0.1.0/src/images/DTU/DTU_stock_photo.jpg
  packages/preview/humble-dtu-thesis/0.1.0/src/images/DTU/white_rgb.svg
  packages/preview/humble-dtu-thesis/0.1.0/src/lib.typ
  packages/preview/humble-dtu-thesis/0.1.0/src/preamble.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/main.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/appendix.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/conclusion.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/introduction.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/abstract.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/acknowledgement.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/contents.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/danish.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/english.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/preface.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/sections/preface/readers-guide.typ
  packages/preview/humble-dtu-thesis/0.1.0/template/works.bib
  packages/preview/humble-dtu-thesis/0.1.0/thumbnail.webp
  packages/preview/humble-dtu-thesis/0.1.0/typst.toml
Labels: new

#2115 minimal-thesis-luebeck:0.3.0
  packages/preview/minimal-thesis-luebeck/0.3.0/LICENSE
  packages/preview/minimal-thesis-luebeck/0.3.0/README.md
  packages/preview/minimal-thesis-luebeck/0.3.0/styles/abstract.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/styles/acknowledgement.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/styles/disclaimer.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/styles/titlepage.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/styles/toc.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/images/slogan.png
  packages/preview/minimal-thesis-luebeck/0.3.0/template/images/top-left.png
  packages/preview/minimal-thesis-luebeck/0.3.0/template/images/top-right.png
  packages/preview/minimal-thesis-luebeck/0.3.0/template/texts/abbreviations.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/texts/abstract-de.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/texts/abstract-en.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/texts/acknowledgement.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/texts/appendix.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/texts/tutorial.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/template/thesis.bib
  packages/preview/minimal-thesis-luebeck/0.3.0/template/thesis.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/thesis-template.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/thumbnail.png
  packages/preview/minimal-thesis-luebeck/0.3.0/typst.toml
  packages/preview/minimal-thesis-luebeck/0.3.0/utils/print-page-break.typ
  packages/preview/minimal-thesis-luebeck/0.3.0/utils/todo.typ
Labels: update

#2116 obsidius:0.1.1
  packages/preview/obsidius/0.1.1/README.md
  packages/preview/obsidius/0.1.1/lib.typ
  packages/preview/obsidius/0.1.1/sample/sample.png
  packages/preview/obsidius/0.1.1/sample/sample.typ
  packages/preview/obsidius/0.1.1/template/main.typ
  packages/preview/obsidius/0.1.1/typst.toml
Labels: update

#2117 modern-xmu-thesis:0.2.0
  packages/preview/modern-xmu-thesis/0.2.0/LICENSE
  packages/preview/modern-xmu-thesis/0.2.0/README.md
  packages/preview/modern-xmu-thesis/0.2.0/assets/xmu-zi-jiageng.svg
  packages/preview/modern-xmu-thesis/0.2.0/layouts/appendix.typ
  packages/preview/modern-xmu-thesis/0.2.0/layouts/doc.typ
  packages/preview/modern-xmu-thesis/0.2.0/layouts/mainmatter.typ
  packages/preview/modern-xmu-thesis/0.2.0/layouts/preface.typ
  packages/preview/modern-xmu-thesis/0.2.0/lib.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/acknowledgement.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bachelor-abstract-en.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bachelor-abstract.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bachelor-cover.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bachelor-integrity.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bachelor-outline-page-en.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bachelor-outline-page.typ
  packages/preview/modern-xmu-thesis/0.2.0/pages/bilingual-bibliography.typ
  packages/preview/modern-xmu-thesis/0.2.0/template/images/xmu-logo.svg
  packages/preview/modern-xmu-thesis/0.2.0/template/ref.bib
  packages/preview/modern-xmu-thesis/0.2.0/template/thesis.typ
  packages/preview/modern-xmu-thesis/0.2.0/thumbnail.png
  packages/preview/modern-xmu-thesis/0.2.0/typst.toml
  packages/preview/modern-xmu-thesis/0.2.0/utils/datetime-display.typ
  packages/preview/modern-xmu-thesis/0.2.0/utils/invisible-heading.typ
  packages/preview/modern-xmu-thesis/0.2.0/utils/style.typ
  packages/preview/modern-xmu-thesis/0.2.0/utils/unpairs.typ
Labels: update

#2119 amsterdammetje-article:0.1.1
  packages/preview/amsterdammetje-article/0.1.1/LICENSE
  packages/preview/amsterdammetje-article/0.1.1/README.md
  packages/preview/amsterdammetje-article/0.1.1/lib.typ
  packages/preview/amsterdammetje-article/0.1.1/logoUvA_en.svg
  packages/preview/amsterdammetje-article/0.1.1/logoUvA_nl.svg
  packages/preview/amsterdammetje-article/0.1.1/template/main.typ
  packages/preview/amsterdammetje-article/0.1.1/template/references.bib
  packages/preview/amsterdammetje-article/0.1.1/thumbnail.png
  packages/preview/amsterdammetje-article/0.1.1/typst.toml
Labels: update

#2120 scaffolder:0.2.0
  packages/preview/scaffolder/0.2.0/CHANGELOG.md
  packages/preview/scaffolder/0.2.0/LICENSE
  packages/preview/scaffolder/0.2.0/README.md
  packages/preview/scaffolder/0.2.0/docs/example-1-p1.svg
  packages/preview/scaffolder/0.2.0/docs/example-1-p2.svg
  packages/preview/scaffolder/0.2.0/src/impl.typ
  packages/preview/scaffolder/0.2.0/src/lib.typ
  packages/preview/scaffolder/0.2.0/typst.toml
Labels: new

#2121 callisto:0.1.0
  packages/preview/callisto/0.1.0/LICENSE
  packages/preview/callisto/0.1.0/README.md
  packages/preview/callisto/0.1.0/resources/lorenz.png
  packages/preview/callisto/0.1.0/src/callisto.typ
  packages/preview/callisto/0.1.0/src/config.typ
  packages/preview/callisto/0.1.0/src/reading.typ
  packages/preview/callisto/0.1.0/src/rendering.typ
  packages/preview/callisto/0.1.0/src/templates.typ
  packages/preview/callisto/0.1.0/tests/.gitignore
  packages/preview/callisto/0.1.0/tests/R.typ
  packages/preview/callisto/0.1.0/tests/api.typ
  packages/preview/callisto/0.1.0/tests/data.typ
  packages/preview/callisto/0.1.0/tests/equations.typ
  packages/preview/callisto/0.1.0/tests/images/xeus-cling.png
  packages/preview/callisto/0.1.0/tests/images/xtensor.png
  packages/preview/callisto/0.1.0/tests/images/xwidgets.png
  packages/preview/callisto/0.1.0/tests/justfile
  packages/preview/callisto/0.1.0/tests/latex.typ
  packages/preview/callisto/0.1.0/tests/lorenz.typ
  packages/preview/callisto/0.1.0/tests/markdown-images.typ
  packages/preview/callisto/0.1.0/tests/notebooks/Cpp.ipynb
  packages/preview/callisto/0.1.0/tests/notebooks/Data.ipynb
  packages/preview/callisto/0.1.0/tests/notebooks/Lorenz.ipynb
  packages/preview/callisto/0.1.0/tests/notebooks/Manifest.toml
  packages/preview/callisto/0.1.0/tests/notebooks/Project.toml
  packages/preview/callisto/0.1.0/tests/notebooks/R.ipynb
  packages/preview/callisto/0.1.0/tests/notebooks/Typesetting Equations.ipynb
  packages/preview/callisto/0.1.0/tests/notebooks/julia.ipynb
  packages/preview/callisto/0.1.0/tests/notebooks/lorenz.py
  packages/preview/callisto/0.1.0/tests/notebooks/python.ipynb
  packages/preview/callisto/0.1.0/tests/render.typ
  packages/preview/callisto/0.1.0/tests/usage.typ
  packages/preview/callisto/0.1.0/typst.toml
Labels: new

#2124 tutor:0.8.0
  packages/preview/tutor/0.8.0/LICENSE
  packages/preview/tutor/0.8.0/README.md
  packages/preview/tutor/0.8.0/lib.typ
  packages/preview/tutor/0.8.0/typst.toml
Labels: update

#2123 zheyan:0.1.0
  packages/preview/zheyan/0.1.0/CHANGELOG.md
  packages/preview/zheyan/0.1.0/LICENSE
  packages/preview/zheyan/0.1.0/README.md
  packages/preview/zheyan/0.1.0/src/lib.typ
  packages/preview/zheyan/0.1.0/typst.toml
Labels: new

#2129 parcio-thesis:0.2.1
  packages/preview/parcio-thesis/0.2.1/LICENSE
  packages/preview/parcio-thesis/0.2.1/README.md
  packages/preview/parcio-thesis/0.2.1/src/parcio.typ
  packages/preview/parcio-thesis/0.2.1/src/titlepage.typ
  packages/preview/parcio-thesis/0.2.1/src/translations.toml
  packages/preview/parcio-thesis/0.2.1/src/util.typ
  packages/preview/parcio-thesis/0.2.1/template/appendix.typ
  packages/preview/parcio-thesis/0.2.1/template/bibliography/apalike.csl
  packages/preview/parcio-thesis/0.2.1/template/bibliography/refs.bib
  packages/preview/parcio-thesis/0.2.1/template/chapters/abstract.typ
  packages/preview/parcio-thesis/0.2.1/template/chapters/background/background.typ
  packages/preview/parcio-thesis/0.2.1/template/chapters/conclusion/conc.typ
  packages/preview/parcio-thesis/0.2.1/template/chapters/eval/eval.typ
  packages/preview/parcio-thesis/0.2.1/template/chapters/introduction/intro.typ
  packages/preview/parcio-thesis/0.2.1/template/images/ovgu-fin.svg
  packages/preview/parcio-thesis/0.2.1/template/legal.typ
  packages/preview/parcio-thesis/0.2.1/template/thesis.typ
  packages/preview/parcio-thesis/0.2.1/thumbnails/1.png
  packages/preview/parcio-thesis/0.2.1/thumbnails/2.png
  packages/preview/parcio-thesis/0.2.1/thumbnails/3.png
  packages/preview/parcio-thesis/0.2.1/typst.toml
Labels: update

#2132 modern-shu-thesis:0.3.2
  packages/preview/modern-shu-thesis/0.3.2/LICENSE
  packages/preview/modern-shu-thesis/0.3.2/README.md
  packages/preview/modern-shu-thesis/0.3.2/assets/cover.png
  packages/preview/modern-shu-thesis/0.3.2/assets/under-cover.png
  packages/preview/modern-shu-thesis/0.3.2/layouts/appendix.typ
  packages/preview/modern-shu-thesis/0.3.2/layouts/doc.typ
  packages/preview/modern-shu-thesis/0.3.2/layouts/mainmatter.typ
  packages/preview/modern-shu-thesis/0.3.2/lib.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/abstract.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/acknowledgement.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/bib.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/conclusion.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/cover.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/declare.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/outline.typ
  packages/preview/modern-shu-thesis/0.3.2/pages/under-cover.typ
  packages/preview/modern-shu-thesis/0.3.2/style/distr.typ
  packages/preview/modern-shu-thesis/0.3.2/style/enums.typ
  packages/preview/modern-shu-thesis/0.3.2/style/figures.typ
  packages/preview/modern-shu-thesis/0.3.2/style/font.typ
  packages/preview/modern-shu-thesis/0.3.2/style/heading.typ
  packages/preview/modern-shu-thesis/0.3.2/style/uline.typ
  packages/preview/modern-shu-thesis/0.3.2/template/figures/energy-distribution.png
  packages/preview/modern-shu-thesis/0.3.2/template/ref.bib
  packages/preview/modern-shu-thesis/0.3.2/template/thesis.typ
  packages/preview/modern-shu-thesis/0.3.2/thumbnail.png
  packages/preview/modern-shu-thesis/0.3.2/typst.toml
Labels: update

#2134 modern-hsh-thesis:1.1.0
  packages/preview/modern-hsh-thesis/1.1.0/.gitignore
  packages/preview/modern-hsh-thesis/1.1.0/CHANGELOG.md
  packages/preview/modern-hsh-thesis/1.1.0/CONTRIBUTING.md
  packages/preview/modern-hsh-thesis/1.1.0/LICENSE
  packages/preview/modern-hsh-thesis/1.1.0/README.md
  packages/preview/modern-hsh-thesis/1.1.0/docs/manual.pdf
  packages/preview/modern-hsh-thesis/1.1.0/src/Logo.svg
  packages/preview/modern-hsh-thesis/1.1.0/src/Wortmarke.svg
  packages/preview/modern-hsh-thesis/1.1.0/src/lib.typ
  packages/preview/modern-hsh-thesis/1.1.0/template/Code/code.typ
  packages/preview/modern-hsh-thesis/1.1.0/template/abbreviations.typ
  packages/preview/modern-hsh-thesis/1.1.0/template/chapters/1-einleitung.typ
  packages/preview/modern-hsh-thesis/1.1.0/template/customFunctions.typ
  packages/preview/modern-hsh-thesis/1.1.0/template/main.typ
  packages/preview/modern-hsh-thesis/1.1.0/template/sources.bib
  packages/preview/modern-hsh-thesis/1.1.0/template/sources.yaml
  packages/preview/modern-hsh-thesis/1.1.0/thumbnail.png
  packages/preview/modern-hsh-thesis/1.1.0/typst.toml
Labels: update

#2135 cjk-unbreak:0.1.0
  packages/preview/cjk-unbreak/0.1.0/LICENSE
  packages/preview/cjk-unbreak/0.1.0/README.md
  packages/preview/cjk-unbreak/0.1.0/lib.typ
  packages/preview/cjk-unbreak/0.1.0/remove-cjk-break-space.typ
  packages/preview/cjk-unbreak/0.1.0/transform-childs.typ
  packages/preview/cjk-unbreak/0.1.0/typst.toml
Labels: new

#2131 tntt:0.1.0
  packages/preview/tntt/0.1.0/LICENSE
  packages/preview/tntt/0.1.0/README.md
  packages/preview/tntt/0.1.0/src/assets/logo.jpg
  packages/preview/tntt/0.1.0/src/font.typ
  packages/preview/tntt/0.1.0/src/imports.typ
  packages/preview/tntt/0.1.0/src/layouts/appendix.typ
  packages/preview/tntt/0.1.0/src/layouts/doc.typ
  packages/preview/tntt/0.1.0/src/layouts/mainmatter.typ
  packages/preview/tntt/0.1.0/src/layouts/preface.typ
  packages/preview/tntt/0.1.0/src/lib.typ
  packages/preview/tntt/0.1.0/src/pages/abstract-en.typ
  packages/preview/tntt/0.1.0/src/pages/abstract.typ
  packages/preview/tntt/0.1.0/src/pages/achv.typ
  packages/preview/tntt/0.1.0/src/pages/ack.typ
  packages/preview/tntt/0.1.0/src/pages/copy.typ
  packages/preview/tntt/0.1.0/src/pages/cover.typ
  packages/preview/tntt/0.1.0/src/pages/decl.typ
  packages/preview/tntt/0.1.0/src/pages/figure-list.typ
  packages/preview/tntt/0.1.0/src/pages/fonts-display.typ
  packages/preview/tntt/0.1.0/src/pages/notation.typ
  packages/preview/tntt/0.1.0/src/pages/outline.typ
  packages/preview/tntt/0.1.0/src/pages/table-list.typ
  packages/preview/tntt/0.1.0/src/utils/bilingual-bibliography.typ
  packages/preview/tntt/0.1.0/src/utils/custom-heading.typ
  packages/preview/tntt/0.1.0/src/utils/custom-numbering.typ
  packages/preview/tntt/0.1.0/src/utils/custom-tablex.typ
  packages/preview/tntt/0.1.0/src/utils/datetime-display.typ
  packages/preview/tntt/0.1.0/src/utils/invisible-heading.typ
  packages/preview/tntt/0.1.0/src/utils/justify-text.typ
  packages/preview/tntt/0.1.0/src/utils/unpairs.typ
  packages/preview/tntt/0.1.0/template/media/logo.jpg
  packages/preview/tntt/0.1.0/template/ref.bib
  packages/preview/tntt/0.1.0/template/thesis.typ
  packages/preview/tntt/0.1.0/thumbnail.png
  packages/preview/tntt/0.1.0/typst.toml
Labels: new

#2139 clear-iclr:0.7.0
  packages/preview/clear-iclr/0.7.0/LICENSE
  packages/preview/clear-iclr/0.7.0/README.md
  packages/preview/clear-iclr/0.7.0/iclr.csl
  packages/preview/clear-iclr/0.7.0/iclr.typ
  packages/preview/clear-iclr/0.7.0/iclr2025.typ
  packages/preview/clear-iclr/0.7.0/template/logo.typ
  packages/preview/clear-iclr/0.7.0/template/main.bib
  packages/preview/clear-iclr/0.7.0/template/main.typ
  packages/preview/clear-iclr/0.7.0/thumbnail.png
  packages/preview/clear-iclr/0.7.0/typst.toml
Labels: update

#2136 barcala:0.1.0
  packages/preview/barcala/0.1.0/LICENSE
  packages/preview/barcala/0.1.0/README.md
  packages/preview/barcala/0.1.0/src/images/informática.png
  packages/preview/barcala/0.1.0/src/images/ingeniería.png
  packages/preview/barcala/0.1.0/src/images/unlp.svg
  packages/preview/barcala/0.1.0/src/lib.typ
  packages/preview/barcala/0.1.0/src/types.typ
  packages/preview/barcala/0.1.0/template/main.typ
  packages/preview/barcala/0.1.0/thumbnail.png
  packages/preview/barcala/0.1.0/typst.toml
Labels: new

#2140 modern-hsh-thesis:1.1.1
  packages/preview/modern-hsh-thesis/1.1.1/.gitignore
  packages/preview/modern-hsh-thesis/1.1.1/CHANGELOG.md
  packages/preview/modern-hsh-thesis/1.1.1/CONTRIBUTING.md
  packages/preview/modern-hsh-thesis/1.1.1/LICENSE
  packages/preview/modern-hsh-thesis/1.1.1/README.md
  packages/preview/modern-hsh-thesis/1.1.1/docs/manual.pdf
  packages/preview/modern-hsh-thesis/1.1.1/src/Logo.svg
  packages/preview/modern-hsh-thesis/1.1.1/src/Wortmarke.svg
  packages/preview/modern-hsh-thesis/1.1.1/src/lib.typ
  packages/preview/modern-hsh-thesis/1.1.1/template/Code/code.typ
  packages/preview/modern-hsh-thesis/1.1.1/template/abbreviations.typ
  packages/preview/modern-hsh-thesis/1.1.1/template/chapters/1-einleitung.typ
  packages/preview/modern-hsh-thesis/1.1.1/template/customFunctions.typ
  packages/preview/modern-hsh-thesis/1.1.1/template/main.typ
  packages/preview/modern-hsh-thesis/1.1.1/template/sources.bib
  packages/preview/modern-hsh-thesis/1.1.1/template/sources.yaml
  packages/preview/modern-hsh-thesis/1.1.1/thumbnail.png
  packages/preview/modern-hsh-thesis/1.1.1/typst.toml
Labels: update

#2141 basic-report:0.2.0
  packages/preview/basic-report/0.2.0/LICENSE
  packages/preview/basic-report/0.2.0/README.md
  packages/preview/basic-report/0.2.0/lib.typ
  packages/preview/basic-report/0.2.0/template/assets/aerospace-engineering.png
  packages/preview/basic-report/0.2.0/template/main.typ
  packages/preview/basic-report/0.2.0/thumbnail.png
  packages/preview/basic-report/0.2.0/titlepage.typ
  packages/preview/basic-report/0.2.0/typst.toml
Labels: update

#2144 juti:0.0.1
  packages/preview/juti/0.0.1/LICENSE
  packages/preview/juti/0.0.1/README.md
  packages/preview/juti/0.0.1/juti.typ
  packages/preview/juti/0.0.1/logo.jpg
  packages/preview/juti/0.0.1/template/figure1.jpg
  packages/preview/juti/0.0.1/template/main.typ
  packages/preview/juti/0.0.1/template/references.bib
  packages/preview/juti/0.0.1/thumbnail.png
  packages/preview/juti/0.0.1/typst.toml
Labels: new

#2127 unofficial-sdu-thesis:0.2.1
  packages/preview/unofficial-sdu-thesis/0.2.1/LICENSE
  packages/preview/unofficial-sdu-thesis/0.2.1/README.md
  packages/preview/unofficial-sdu-thesis/0.2.1/imgs/logo.svg
  packages/preview/unofficial-sdu-thesis/0.2.1/layouts/appendix.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/layouts/doc.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/layouts/mainmatter.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/lib.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/pages/abstract.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/pages/acknowledgement.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/pages/bib.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/pages/cover.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/pages/outline.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/styles/distr.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/styles/enums.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/styles/figures.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/styles/fonts.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/styles/heading.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/template/concise.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/template/img/AlbertEinstein.png
  packages/preview/unofficial-sdu-thesis/0.2.1/template/img/ClaudeElwoodShannon.png
  packages/preview/unofficial-sdu-thesis/0.2.1/template/img/John von Neumann.png
  packages/preview/unofficial-sdu-thesis/0.2.1/template/img/appendix/Lenna.png
  packages/preview/unofficial-sdu-thesis/0.2.1/template/img/appendix/Sierpinski_pyramid.jpg
  packages/preview/unofficial-sdu-thesis/0.2.1/template/img/appendix/Sigmoid.svg
  packages/preview/unofficial-sdu-thesis/0.2.1/template/ref.bib
  packages/preview/unofficial-sdu-thesis/0.2.1/template/thesis.typ
  packages/preview/unofficial-sdu-thesis/0.2.1/thumbnail.png
  packages/preview/unofficial-sdu-thesis/0.2.1/typst.toml
Labels: update

#2126 definitely-not-isec-thesis:2.0.1
  packages/preview/definitely-not-isec-thesis/2.0.1/LICENSE
  packages/preview/definitely-not-isec-thesis/2.0.1/README.md
  packages/preview/definitely-not-isec-thesis/2.0.1/src/assets/tuglogo.svg
  packages/preview/definitely-not-isec-thesis/2.0.1/src/helper.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/lib.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/packages/acrostiche.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/packages/notations.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/abstract.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/acknowledgements.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/acronyms.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/affidavit.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/kurzfassung.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/notations.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/table-of-contents.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/src/pages/title.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/template/bibliography.bib
  packages/preview/definitely-not-isec-thesis/2.0.1/template/thesis.typ
  packages/preview/definitely-not-isec-thesis/2.0.1/thumbnail.png
  packages/preview/definitely-not-isec-thesis/2.0.1/typst.toml
Labels: update

#2128 sdu-touying-simpl:0.2.2
  packages/preview/sdu-touying-simpl/0.2.2/LICENSE
  packages/preview/sdu-touying-simpl/0.2.2/README.md
  packages/preview/sdu-touying-simpl/0.2.2/dependency.typ
  packages/preview/sdu-touying-simpl/0.2.2/example/figures/main.png
  packages/preview/sdu-touying-simpl/0.2.2/example/main.typ
  packages/preview/sdu-touying-simpl/0.2.2/img/brand-rust.svg
  packages/preview/sdu-touying-simpl/0.2.2/img/github-mark-white.svg
  packages/preview/sdu-touying-simpl/0.2.2/img/sdu.png
  packages/preview/sdu-touying-simpl/0.2.2/lib.typ
  packages/preview/sdu-touying-simpl/0.2.2/src/call-out.typ
  packages/preview/sdu-touying-simpl/0.2.2/typst.toml
Labels: update

#2145 qooklet:0.1.0
  packages/preview/qooklet/0.1.0/LICENSE
  packages/preview/qooklet/0.1.0/README.md
  packages/preview/qooklet/0.1.0/src/fonts.toml
  packages/preview/qooklet/0.1.0/src/lang.toml
  packages/preview/qooklet/0.1.0/src/lib.typ
  packages/preview/qooklet/0.1.0/typst.toml
Labels: new

#2147 vercanard:1.0.3
  packages/preview/vercanard/1.0.3/LICENSE
  packages/preview/vercanard/1.0.3/README.md
  packages/preview/vercanard/1.0.3/demo.pdf
  packages/preview/vercanard/1.0.3/template.typ
  packages/preview/vercanard/1.0.3/template/main.typ
  packages/preview/vercanard/1.0.3/thumbnail.png
  packages/preview/vercanard/1.0.3/typst.toml
Labels: update

#2148 juti:0.0.2
  packages/preview/juti/0.0.2/LICENSE
  packages/preview/juti/0.0.2/README.md
  packages/preview/juti/0.0.2/juti.typ
  packages/preview/juti/0.0.2/logo.jpg
  packages/preview/juti/0.0.2/template/figure1.jpg
  packages/preview/juti/0.0.2/template/main.typ
  packages/preview/juti/0.0.2/template/references.bib
  packages/preview/juti/0.0.2/thumbnail.png
  packages/preview/juti/0.0.2/typst.toml
Labels: update

#2149 timeliney:0.2.1
  packages/preview/timeliney/0.2.1/LICENSE
  packages/preview/timeliney/0.2.1/README.md
  packages/preview/timeliney/0.2.1/manual.pdf
  packages/preview/timeliney/0.2.1/manual.typ
  packages/preview/timeliney/0.2.1/sample.png
  packages/preview/timeliney/0.2.1/sample.typ
  packages/preview/timeliney/0.2.1/timeliney.typ
  packages/preview/timeliney/0.2.1/typst.toml
Labels: update

#2151 leonux:1.0.0
  packages/preview/leonux/1.0.0/LICENSE
  packages/preview/leonux/1.0.0/README.md
  packages/preview/leonux/1.0.0/template.typ
  packages/preview/leonux/1.0.0/template/bibliography.bib
  packages/preview/leonux/1.0.0/template/main.typ
  packages/preview/leonux/1.0.0/thumbnail.png
  packages/preview/leonux/1.0.0/typst.toml
Labels: new

#2153 wavy:0.1.3
  packages/preview/wavy/0.1.3/LICENSE
  packages/preview/wavy/0.1.3/NOTICE
  packages/preview/wavy/0.1.3/README.md
  packages/preview/wavy/0.1.3/lib.typ
  packages/preview/wavy/0.1.3/typst.toml
  packages/preview/wavy/0.1.3/wavy.js
  packages/preview/wavy/0.1.3/wavy.svg
  packages/preview/wavy/0.1.3/wavy.typ
Labels: update

#2155 brain-transplant:0.1.0
  packages/preview/brain-transplant/0.1.0/LICENSE
  packages/preview/brain-transplant/0.1.0/README.md
  packages/preview/brain-transplant/0.1.0/assets/logo.svg
  packages/preview/brain-transplant/0.1.0/src/brain-transplant.typ
  packages/preview/brain-transplant/0.1.0/src/lib.typ
  packages/preview/brain-transplant/0.1.0/typst.toml
Labels: new

#2161 brain-transplant:0.1.0
  packages/preview/brain-transplant/0.1.0/docs/manual.pdf
Labels: new

#2160 tiefletter:0.1.0
  packages/preview/tiefletter/0.1.0/LICENSE
  packages/preview/tiefletter/0.1.0/README.md
  packages/preview/tiefletter/0.1.0/lib.typ
  packages/preview/tiefletter/0.1.0/template/header.svg
  packages/preview/tiefletter/0.1.0/template/main.typ
  packages/preview/tiefletter/0.1.0/thumbnail.png
  packages/preview/tiefletter/0.1.0/typst.toml
Labels: new

#2163 barcala:0.1.1
  packages/preview/barcala/0.1.1/LICENSE
  packages/preview/barcala/0.1.1/README.md
  packages/preview/barcala/0.1.1/src/images/informática.png
  packages/preview/barcala/0.1.1/src/images/ingeniería.png
  packages/preview/barcala/0.1.1/src/images/unlp.svg
  packages/preview/barcala/0.1.1/src/lib.typ
  packages/preview/barcala/0.1.1/src/types.typ
  packages/preview/barcala/0.1.1/template/bibliografia.bib
  packages/preview/barcala/0.1.1/template/main.typ
  packages/preview/barcala/0.1.1/thumbnail.png
  packages/preview/barcala/0.1.1/typst.toml
Labels: update

#2142 sns-polylux-template:0.1.0
  packages/preview/sns-polylux-template/0.1.0/README.md
  packages/preview/sns-polylux-template/0.1.0/sns-theme.typ
  packages/preview/sns-polylux-template/0.1.0/template/main.typ
  packages/preview/sns-polylux-template/0.1.0/template/pics/logo_SNS_bianco.svg
  packages/preview/sns-polylux-template/0.1.0/template/pics/logo_SNS_grigio.svg
  packages/preview/sns-polylux-template/0.1.0/template/pics/logo_SNS_verde.svg
  packages/preview/sns-polylux-template/0.1.0/thumbnail.png
  packages/preview/sns-polylux-template/0.1.0/typst.toml
Labels: new

#2166 ijimai:0.0.4
  packages/preview/ijimai/0.0.4/LICENSE
  packages/preview/ijimai/0.0.4/README.md
  packages/preview/ijimai/0.0.4/ijimai.typ
  packages/preview/ijimai/0.0.4/template/Jane Smith.jpg
  packages/preview/ijimai/0.0.4/template/John Doe.jpg
  packages/preview/ijimai/0.0.4/template/axes.svg
  packages/preview/ijimai/0.0.4/template/bibliography.bib
  packages/preview/ijimai/0.0.4/template/cylinder.svg
  packages/preview/ijimai/0.0.4/template/paper.toml
  packages/preview/ijimai/0.0.4/template/paper.typ
  packages/preview/ijimai/0.0.4/template/tetrahedron.svg
  packages/preview/ijimai/0.0.4/template/unir logo.svg
  packages/preview/ijimai/0.0.4/thumbnail.png
  packages/preview/ijimai/0.0.4/typst.toml
Labels: update

#2133 callisto:0.2.2
  packages/preview/callisto/0.2.2/LICENSE
  packages/preview/callisto/0.2.2/README.md
  packages/preview/callisto/0.2.2/docs/Reference.md
  packages/preview/callisto/0.2.2/docs/Tutorial.md
  packages/preview/callisto/0.2.2/docs/cell-no-result.png
  packages/preview/callisto/0.2.2/docs/cell-result.png
  packages/preview/callisto/0.2.2/docs/example.ipynb
  packages/preview/callisto/0.2.2/docs/justfile
  packages/preview/callisto/0.2.2/docs/lorenz-extract.png
  packages/preview/callisto/0.2.2/docs/lorenz-extract.typ
  packages/preview/callisto/0.2.2/src/callisto.typ
  packages/preview/callisto/0.2.2/src/config.typ
  packages/preview/callisto/0.2.2/src/reading.typ
  packages/preview/callisto/0.2.2/src/rendering.typ
  packages/preview/callisto/0.2.2/src/templates.typ
  packages/preview/callisto/0.2.2/typst.toml
Labels: update

#2169 qooklet:0.2.0
  packages/preview/qooklet/0.2.0/LICENSE
  packages/preview/qooklet/0.2.0/README.md
  packages/preview/qooklet/0.2.0/src/fonts.toml
  packages/preview/qooklet/0.2.0/src/lang.toml
  packages/preview/qooklet/0.2.0/src/lib.typ
  packages/preview/qooklet/0.2.0/template/main.typ
  packages/preview/qooklet/0.2.0/thumbnail.png
  packages/preview/qooklet/0.2.0/typst.toml
Labels: update

#2176 tgm-hit-thesis:0.3.1
  packages/preview/tgm-hit-thesis/0.3.1/.gitignore
  packages/preview/tgm-hit-thesis/0.3.1/CHANGELOG.md
  packages/preview/tgm-hit-thesis/0.3.1/LICENSE
  packages/preview/tgm-hit-thesis/0.3.1/README.md
  packages/preview/tgm-hit-thesis/0.3.1/docs/manual.pdf
  packages/preview/tgm-hit-thesis/0.3.1/example.pdf
  packages/preview/tgm-hit-thesis/0.3.1/src/assets.typ
  packages/preview/tgm-hit-thesis/0.3.1/src/assets/logo-left.png
  packages/preview/tgm-hit-thesis/0.3.1/src/assets/logo-right.png
  packages/preview/tgm-hit-thesis/0.3.1/src/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.3.1/src/bib.typ
  packages/preview/tgm-hit-thesis/0.3.1/src/glossary.typ
  packages/preview/tgm-hit-thesis/0.3.1/src/l10n.toml
  packages/preview/tgm-hit-thesis/0.3.1/src/l10n.typ
  packages/preview/tgm-hit-thesis/0.3.1/src/lib.typ
  packages/preview/tgm-hit-thesis/0.3.1/src/utils.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/assets.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/assets/logo.png
  packages/preview/tgm-hit-thesis/0.3.1/template/assets/mod.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/bibliography.bib
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/conclusio.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/danksagung.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/einleitung.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/implementierung.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/konzept.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/kurzfassung.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/retrospektive.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/studie.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/chapters/vorwort.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/glossaries.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/lib.typ
  packages/preview/tgm-hit-thesis/0.3.1/template/main.typ
  packages/preview/tgm-hit-thesis/0.3.1/thumbnail.png
  packages/preview/tgm-hit-thesis/0.3.1/typst.toml
Labels: update

#2179 gantty:0.2.0
  packages/preview/gantty/0.2.0/.gitignore
  packages/preview/gantty/0.2.0/CHANGELOG.md
  packages/preview/gantty/0.2.0/LICENSE
  packages/preview/gantty/0.2.0/README.md
  packages/preview/gantty/0.2.0/example/gantt.svg
  packages/preview/gantty/0.2.0/example/gantt.typ
  packages/preview/gantty/0.2.0/example/gantt.yaml
  packages/preview/gantty/0.2.0/lib.typ
  packages/preview/gantty/0.2.0/typst.toml
Labels: update

#2180 parcio-thesis:0.2.2
  packages/preview/parcio-thesis/0.2.2/LICENSE
  packages/preview/parcio-thesis/0.2.2/README.md
  packages/preview/parcio-thesis/0.2.2/src/parcio.typ
  packages/preview/parcio-thesis/0.2.2/src/titlepage.typ
  packages/preview/parcio-thesis/0.2.2/src/translations.toml
  packages/preview/parcio-thesis/0.2.2/src/util.typ
  packages/preview/parcio-thesis/0.2.2/template/appendix.typ
  packages/preview/parcio-thesis/0.2.2/template/bibliography/apalike.csl
  packages/preview/parcio-thesis/0.2.2/template/bibliography/refs.bib
  packages/preview/parcio-thesis/0.2.2/template/chapters/abstract.typ
  packages/preview/parcio-thesis/0.2.2/template/chapters/background/background.typ
  packages/preview/parcio-thesis/0.2.2/template/chapters/conclusion/conc.typ
  packages/preview/parcio-thesis/0.2.2/template/chapters/eval/eval.typ
  packages/preview/parcio-thesis/0.2.2/template/chapters/introduction/intro.typ
  packages/preview/parcio-thesis/0.2.2/template/images/ovgu-fin.svg
  packages/preview/parcio-thesis/0.2.2/template/legal.typ
  packages/preview/parcio-thesis/0.2.2/template/thesis.typ
  packages/preview/parcio-thesis/0.2.2/thumbnails/1.png
  packages/preview/parcio-thesis/0.2.2/thumbnails/2.png
  packages/preview/parcio-thesis/0.2.2/thumbnails/3.png
  packages/preview/parcio-thesis/0.2.2/typst.toml
Labels: update

#2181 leonux:1.1.0
  packages/preview/leonux/1.1.0/LICENSE
  packages/preview/leonux/1.1.0/README.md
  packages/preview/leonux/1.1.0/template.typ
  packages/preview/leonux/1.1.0/template/bibliography.bib
  packages/preview/leonux/1.1.0/template/main.typ
  packages/preview/leonux/1.1.0/thumbnail.png
  packages/preview/leonux/1.1.0/typst.toml
Labels: update

#2182 scaffolder:0.2.1
  packages/preview/scaffolder/0.2.1/LICENSE
  packages/preview/scaffolder/0.2.1/README.md
  packages/preview/scaffolder/0.2.1/docs/example-1-p1.svg
  packages/preview/scaffolder/0.2.1/docs/example-1-p2.svg
  packages/preview/scaffolder/0.2.1/src/impl.typ
  packages/preview/scaffolder/0.2.1/src/lib.typ
  packages/preview/scaffolder/0.2.1/typst.toml
Labels: update

#2187 callisto:0.2.2
  packages/preview/callisto/0.2.2/README.md
Labels: update

#2189 academicv:1.1.0
  packages/preview/academicv/1.1.0/LICENSE
  packages/preview/academicv/1.1.0/README.md
  packages/preview/academicv/1.1.0/assets/thumbnail_1.png
  packages/preview/academicv/1.1.0/assets/thumbnail_2.png
  packages/preview/academicv/1.1.0/cv.typ
  packages/preview/academicv/1.1.0/cv.typ.schema.json
  packages/preview/academicv/1.1.0/layouts/bullet-list.typ
  packages/preview/academicv/1.1.0/layouts/header.typ
  packages/preview/academicv/1.1.0/layouts/numbered-list.typ
  packages/preview/academicv/1.1.0/layouts/prose.typ
  packages/preview/academicv/1.1.0/layouts/timeline.typ
  packages/preview/academicv/1.1.0/template/template.typ
  packages/preview/academicv/1.1.0/template/template.yml
  packages/preview/academicv/1.1.0/typst.toml
  packages/preview/academicv/1.1.0/utils.typ
Labels: update

#2184 touying-quick:0.1.0
  packages/preview/touying-quick/0.1.0/LICENSE
  packages/preview/touying-quick/0.1.0/README.md
  packages/preview/touying-quick/0.1.0/fonts.toml
  packages/preview/touying-quick/0.1.0/img/sky.png
  packages/preview/touying-quick/0.1.0/lang.toml
  packages/preview/touying-quick/0.1.0/lib.typ
  packages/preview/touying-quick/0.1.0/template/main.typ
  packages/preview/touying-quick/0.1.0/thumbnail.png
  packages/preview/touying-quick/0.1.0/typst.toml
Labels: new

#2171 touying-flow:1.1.0 and touying-flow:1.2.0
  packages/preview/touying-flow/1.1.0/content/example/main.pdf
  packages/preview/touying-flow/1.2.0/README.md
  packages/preview/touying-flow/1.2.0/components.typ
  packages/preview/touying-flow/1.2.0/content/example/main.typ
  packages/preview/touying-flow/1.2.0/image.png
  packages/preview/touying-flow/1.2.0/lib.typ
  packages/preview/touying-flow/1.2.0/src/components.typ
  packages/preview/touying-flow/1.2.0/src/configs.typ
  packages/preview/touying-flow/1.2.0/src/core.typ
  packages/preview/touying-flow/1.2.0/src/exports.typ
  packages/preview/touying-flow/1.2.0/src/magic.typ
  packages/preview/touying-flow/1.2.0/src/pdfpc.typ
  packages/preview/touying-flow/1.2.0/src/slides.typ
  packages/preview/touying-flow/1.2.0/src/utils.typ
  packages/preview/touying-flow/1.2.0/theme.typ
  packages/preview/touying-flow/1.2.0/typst.toml
Labels: update

#2190 unofficial-sdu-thesis:0.2.2
  packages/preview/unofficial-sdu-thesis/0.2.2/LICENSE
  packages/preview/unofficial-sdu-thesis/0.2.2/README.md
  packages/preview/unofficial-sdu-thesis/0.2.2/imgs/logo.svg
  packages/preview/unofficial-sdu-thesis/0.2.2/layouts/appendix.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/layouts/doc.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/layouts/mainmatter.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/lib.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/pages/abstract.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/pages/acknowledgement.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/pages/bib.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/pages/cover.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/pages/outline.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/styles/distr.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/styles/enums.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/styles/figures.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/styles/fonts.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/styles/heading.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/template/concise.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/template/img/AlbertEinstein.png
  packages/preview/unofficial-sdu-thesis/0.2.2/template/img/ClaudeElwoodShannon.png
  packages/preview/unofficial-sdu-thesis/0.2.2/template/img/John von Neumann.png
  packages/preview/unofficial-sdu-thesis/0.2.2/template/img/appendix/Lenna.png
  packages/preview/unofficial-sdu-thesis/0.2.2/template/img/appendix/Sierpinski_pyramid.jpg
  packages/preview/unofficial-sdu-thesis/0.2.2/template/img/appendix/Sigmoid.svg
  packages/preview/unofficial-sdu-thesis/0.2.2/template/ref.bib
  packages/preview/unofficial-sdu-thesis/0.2.2/template/thesis.typ
  packages/preview/unofficial-sdu-thesis/0.2.2/thumbnail.png
  packages/preview/unofficial-sdu-thesis/0.2.2/typst.toml
Labels: update

#2193 hagakiii:0.1.0
  packages/preview/hagakiii/0.1.0/LICENSE
  packages/preview/hagakiii/0.1.0/README.md
  packages/preview/hagakiii/0.1.0/hagaki.png
  packages/preview/hagakiii/0.1.0/lib.typ
  packages/preview/hagakiii/0.1.0/tests/test.png
  packages/preview/hagakiii/0.1.0/typst.toml
Labels: new

#2183 orange-book:0.6.1
  packages/preview/orange-book/0.6.1/LICENSE
  packages/preview/orange-book/0.6.1/README.md
  packages/preview/orange-book/0.6.1/lib.typ
  packages/preview/orange-book/0.6.1/my-index.typ
  packages/preview/orange-book/0.6.1/my-outline.typ
  packages/preview/orange-book/0.6.1/template/background.svg
  packages/preview/orange-book/0.6.1/template/creodocs_logo.svg
  packages/preview/orange-book/0.6.1/template/main.typ
  packages/preview/orange-book/0.6.1/template/orange1.jpg
  packages/preview/orange-book/0.6.1/template/orange2.jpg
  packages/preview/orange-book/0.6.1/template/orange3.jpg
  packages/preview/orange-book/0.6.1/template/placeholder.jpg
  packages/preview/orange-book/0.6.1/template/sample.bib
  packages/preview/orange-book/0.6.1/theorems.typ
  packages/preview/orange-book/0.6.1/thumbnail.png
  packages/preview/orange-book/0.6.1/typst.toml
Labels: update

#2197 nup:0.1.0
  packages/preview/nup/0.1.0/LICENSE
  packages/preview/nup/0.1.0/README.md
  packages/preview/nup/0.1.0/assets/inception.svg
  packages/preview/nup/0.1.0/assets/inception.typ
  packages/preview/nup/0.1.0/assets/preview.pdf
  packages/preview/nup/0.1.0/assets/preview.typ
  packages/preview/nup/0.1.0/assets/test.pdf
  packages/preview/nup/0.1.0/assets/test.typ
  packages/preview/nup/0.1.0/assets/test1.svg
  packages/preview/nup/0.1.0/assets/test2.svg
  packages/preview/nup/0.1.0/images/preview1.svg
  packages/preview/nup/0.1.0/images/preview10.svg
  packages/preview/nup/0.1.0/images/preview11.svg
  packages/preview/nup/0.1.0/images/preview12.svg
  packages/preview/nup/0.1.0/images/preview2.svg
  packages/preview/nup/0.1.0/images/preview3.svg
  packages/preview/nup/0.1.0/images/preview4.svg
  packages/preview/nup/0.1.0/images/preview5.svg
  packages/preview/nup/0.1.0/images/preview6.svg
  packages/preview/nup/0.1.0/images/preview7.svg
  packages/preview/nup/0.1.0/images/preview8.svg
  packages/preview/nup/0.1.0/images/preview9.svg
  packages/preview/nup/0.1.0/src/lib.typ
  packages/preview/nup/0.1.0/src/nup.typ
  packages/preview/nup/0.1.0/typst.toml
Labels: new

#2198 simple-tubs-letter:0.1.1
  packages/preview/simple-tubs-letter/0.1.1/.gitignore
  packages/preview/simple-tubs-letter/0.1.1/COPYING
  packages/preview/simple-tubs-letter/0.1.1/LICENCES/GPL-3.0
  packages/preview/simple-tubs-letter/0.1.1/LICENCES/MIT
  packages/preview/simple-tubs-letter/0.1.1/README.md
  packages/preview/simple-tubs-letter/0.1.1/template.typ
  packages/preview/simple-tubs-letter/0.1.1/template/.gitignore
  packages/preview/simple-tubs-letter/0.1.1/template/assets/figure/tubs/institute_logo.jpg
  packages/preview/simple-tubs-letter/0.1.1/template/assets/figure/tubs/tubs_logo.svg
  packages/preview/simple-tubs-letter/0.1.1/template/letter.typ
  packages/preview/simple-tubs-letter/0.1.1/template/metadata.typ
  packages/preview/simple-tubs-letter/0.1.1/thumbnail.webp
  packages/preview/simple-tubs-letter/0.1.1/typst.toml
Labels: update

#2175 herodot:0.1.0
  packages/preview/herodot/0.1.0/LICENSE
  packages/preview/herodot/0.1.0/README.md
  packages/preview/herodot/0.1.0/example.pdf
  packages/preview/herodot/0.1.0/example.typ
  packages/preview/herodot/0.1.0/lib.typ
  packages/preview/herodot/0.1.0/src/functions.typ
  packages/preview/herodot/0.1.0/src/primitives.typ
  packages/preview/herodot/0.1.0/typst.toml
Labels: new

#2174 tapestry:0.0.2
  packages/preview/tapestry/0.0.2/LICENSE
  packages/preview/tapestry/0.0.2/README.md
  packages/preview/tapestry/0.0.2/lib.typ
  packages/preview/tapestry/0.0.2/template/main.typ
  packages/preview/tapestry/0.0.2/thumbnail.png
  packages/preview/tapestry/0.0.2/typst.toml
Labels: update

#2194 mechanical-system-cetz-34j:0.1.0
  packages/preview/mechanical-system-cetz-34j/0.1.0/LICENSE
  packages/preview/mechanical-system-cetz-34j/0.1.0/README.md
  packages/preview/mechanical-system-cetz-34j/0.1.0/src/lib.typ
  packages/preview/mechanical-system-cetz-34j/0.1.0/tests/test.png
  packages/preview/mechanical-system-cetz-34j/0.1.0/typst.toml
Labels: new

#2204 messeji:0.1.0
  packages/preview/messeji/0.1.0/.gitignore
  packages/preview/messeji/0.1.0/LICENSE
  packages/preview/messeji/0.1.0/README.md
  packages/preview/messeji/0.1.0/examples/example.jpg
  packages/preview/messeji/0.1.0/examples/main.pdf
  packages/preview/messeji/0.1.0/examples/main.typ
  packages/preview/messeji/0.1.0/examples/output.example.json
  packages/preview/messeji/0.1.0/messeji.typ
  packages/preview/messeji/0.1.0/typst.toml
Labels: new

#2207 scholarly-tauthesis:0.11.2
  packages/preview/scholarly-tauthesis/0.11.2/.gitattributes
  packages/preview/scholarly-tauthesis/0.11.2/.gitignore
  packages/preview/scholarly-tauthesis/0.11.2/LICENSE
  packages/preview/scholarly-tauthesis/0.11.2/README.md
  packages/preview/scholarly-tauthesis/0.11.2/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.11.2/template/code/README.md
  packages/preview/scholarly-tauthesis/0.11.2/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.11.2/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/B.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/README.md
  packages/preview/scholarly-tauthesis/0.11.2/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/images/README.md
  packages/preview/scholarly-tauthesis/0.11.2/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.11.2/template/main.typ
  packages/preview/scholarly-tauthesis/0.11.2/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.11.2/thumbnail.png
  packages/preview/scholarly-tauthesis/0.11.2/typst.toml
Labels: update

#2206 text-dirr:1.0.0
  packages/preview/text-dirr/1.0.0/LICENSE
  packages/preview/text-dirr/1.0.0/README.md
  packages/preview/text-dirr/1.0.0/lib.typ
  packages/preview/text-dirr/1.0.0/typst.toml
Labels: new

#2209 rubber-article:0.4.0
  packages/preview/rubber-article/0.4.0/CHANGELOG.md
  packages/preview/rubber-article/0.4.0/LICENSE
  packages/preview/rubber-article/0.4.0/README.md
  packages/preview/rubber-article/0.4.0/src/constructors.typ
  packages/preview/rubber-article/0.4.0/src/dependencies.typ
  packages/preview/rubber-article/0.4.0/src/lib.typ
  packages/preview/rubber-article/0.4.0/src/styles.typ
  packages/preview/rubber-article/0.4.0/src/utils.typ
  packages/preview/rubber-article/0.4.0/template/main.typ
  packages/preview/rubber-article/0.4.0/thumbnail.png
  packages/preview/rubber-article/0.4.0/typst.toml
Labels: update

#2211 tapestry:0.0.3
  packages/preview/tapestry/0.0.3/LICENSE
  packages/preview/tapestry/0.0.3/README.md
  packages/preview/tapestry/0.0.3/lib.typ
  packages/preview/tapestry/0.0.3/template/main.typ
  packages/preview/tapestry/0.0.3/thumbnail.png
  packages/preview/tapestry/0.0.3/typst.toml
Labels: update

#2212 modern-sjtu-thesis:0.2.2
  packages/preview/modern-sjtu-thesis/0.2.2/.gitignore
  packages/preview/modern-sjtu-thesis/0.2.2/LICENSE
  packages/preview/modern-sjtu-thesis/0.2.2/README.md
  packages/preview/modern-sjtu-thesis/0.2.2/assets/sjtu-logo.png
  packages/preview/modern-sjtu-thesis/0.2.2/layouts/appendix.typ
  packages/preview/modern-sjtu-thesis/0.2.2/layouts/doc.typ
  packages/preview/modern-sjtu-thesis/0.2.2/layouts/mainmatter.typ
  packages/preview/modern-sjtu-thesis/0.2.2/layouts/preface.typ
  packages/preview/modern-sjtu-thesis/0.2.2/lib.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/abstract-en.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/abstract.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/achievement.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/acknowledgement.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/bib.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/cover-bachelor.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/cover-en.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/cover.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/declare.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/outline.typ
  packages/preview/modern-sjtu-thesis/0.2.2/pages/summary-en.typ
  packages/preview/modern-sjtu-thesis/0.2.2/template/figures/energy-distribution.png
  packages/preview/modern-sjtu-thesis/0.2.2/template/ref.bib
  packages/preview/modern-sjtu-thesis/0.2.2/template/thesis.typ
  packages/preview/modern-sjtu-thesis/0.2.2/thumbnail.png
  packages/preview/modern-sjtu-thesis/0.2.2/typst.toml
  packages/preview/modern-sjtu-thesis/0.2.2/utils/bilingual-bibliography.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/checkbox.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/datetime-display.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/distr.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/header.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/heading.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/list-enum-align.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/shanghai-jiao-tong-university.csl
  packages/preview/modern-sjtu-thesis/0.2.2/utils/style.typ
  packages/preview/modern-sjtu-thesis/0.2.2/utils/uline.typ
Labels: update

#2213 not-jku-thesis:0.2.0
  packages/preview/not-jku-thesis/0.2.0/JKU.png
  packages/preview/not-jku-thesis/0.2.0/LICENSE
  packages/preview/not-jku-thesis/0.2.0/README.md
  packages/preview/not-jku-thesis/0.2.0/abstract.typ
  packages/preview/not-jku-thesis/0.2.0/acknowledgement.typ
  packages/preview/not-jku-thesis/0.2.0/big_K.png
  packages/preview/not-jku-thesis/0.2.0/disclaimer.typ
  packages/preview/not-jku-thesis/0.2.0/template.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/Analysis.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/Appendix.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/Conclusion.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/DataCollection.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/Introduction.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/LiteratureReview.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/Methodology.typ
  packages/preview/not-jku-thesis/0.2.0/template/content/Tutorial.typ
  packages/preview/not-jku-thesis/0.2.0/template/glossary.typ
  packages/preview/not-jku-thesis/0.2.0/template/images/Calcipher.jpg
  packages/preview/not-jku-thesis/0.2.0/template/images/JamesBond.jpg
  packages/preview/not-jku-thesis/0.2.0/template/images/Mei.jpg
  packages/preview/not-jku-thesis/0.2.0/template/images/MissMoneypenny.jpg
  packages/preview/not-jku-thesis/0.2.0/template/items.bib
  packages/preview/not-jku-thesis/0.2.0/template/thesis.typ
  packages/preview/not-jku-thesis/0.2.0/template/utils.typ
  packages/preview/not-jku-thesis/0.2.0/thumbnail.png
  packages/preview/not-jku-thesis/0.2.0/titlepage.typ
  packages/preview/not-jku-thesis/0.2.0/typst.toml
Labels: update

#2215 cmarker:0.1.4
  packages/preview/cmarker/0.1.4/LICENSE
  packages/preview/cmarker/0.1.4/README.md
  packages/preview/cmarker/0.1.4/examples/hexagons.png
  packages/preview/cmarker/0.1.4/examples/simple.png
  packages/preview/cmarker/0.1.4/lib.typ
  packages/preview/cmarker/0.1.4/plugin.wasm
  packages/preview/cmarker/0.1.4/typst.toml
Labels: update

#2219 clean-acmart:0.0.1
  packages/preview/clean-acmart/0.0.1/LICENSE
  packages/preview/clean-acmart/0.0.1/README.md
  packages/preview/clean-acmart/0.0.1/cc-by.svg
  packages/preview/clean-acmart/0.0.1/clean-acmart.typ
  packages/preview/clean-acmart/0.0.1/template/main.typ
  packages/preview/clean-acmart/0.0.1/template/refs.bib
  packages/preview/clean-acmart/0.0.1/thumbnail.webp
  packages/preview/clean-acmart/0.0.1/typst.toml
Labels: new

#2218 suiji:0.4.0
  packages/preview/suiji/0.4.0/LICENSE
  packages/preview/suiji/0.4.0/README.md
  packages/preview/suiji/0.4.0/examples/matrix-rain.png
  packages/preview/suiji/0.4.0/examples/matrix-rain.typ
  packages/preview/suiji/0.4.0/examples/random-permutation.png
  packages/preview/suiji/0.4.0/examples/random-permutation.typ
  packages/preview/suiji/0.4.0/examples/random-walk.png
  packages/preview/suiji/0.4.0/examples/random-walk.typ
  packages/preview/suiji/0.4.0/src/core.wasm
  packages/preview/suiji/0.4.0/src/lib.typ
  packages/preview/suiji/0.4.0/src/random-fast.typ
  packages/preview/suiji/0.4.0/src/random.typ
  packages/preview/suiji/0.4.0/src/taus.typ
  packages/preview/suiji/0.4.0/typst.toml
Labels: update

#2217 messeji:0.2.0
  packages/preview/messeji/0.2.0/.gitignore
  packages/preview/messeji/0.2.0/LICENSE
  packages/preview/messeji/0.2.0/README.md
  packages/preview/messeji/0.2.0/examples/example.jpg
  packages/preview/messeji/0.2.0/examples/main.pdf
  packages/preview/messeji/0.2.0/examples/main.typ
  packages/preview/messeji/0.2.0/examples/output.example.json
  packages/preview/messeji/0.2.0/messeji.typ
  packages/preview/messeji/0.2.0/typst.toml
Labels: update

#2214 superb-pci:0.2.0
  packages/preview/superb-pci/0.2.0/LICENSE
  packages/preview/superb-pci/0.2.0/README.md
  packages/preview/superb-pci/0.2.0/formatters.typ
  packages/preview/superb-pci/0.2.0/lib.typ
  packages/preview/superb-pci/0.2.0/pci.csl
  packages/preview/superb-pci/0.2.0/template/main.typ
  packages/preview/superb-pci/0.2.0/template/pci-graph-small.png
  packages/preview/superb-pci/0.2.0/template/refs.bib
  packages/preview/superb-pci/0.2.0/thumbnail.png
  packages/preview/superb-pci/0.2.0/typst.toml
Labels: update

#2220 simple-bupt-report:0.1.0
  packages/preview/simple-bupt-report/0.1.0/LICENSE
  packages/preview/simple-bupt-report/0.1.0/README.md
  packages/preview/simple-bupt-report/0.1.0/assets/bupt-logo.jpg
  packages/preview/simple-bupt-report/0.1.0/lib.typ
  packages/preview/simple-bupt-report/0.1.0/template/main.typ
  packages/preview/simple-bupt-report/0.1.0/thumbnail.png
  packages/preview/simple-bupt-report/0.1.0/typst.toml
Labels: new

#2222 curryst:0.5.1
  packages/preview/curryst/0.5.1/LICENSE
  packages/preview/curryst/0.5.1/README.md
  packages/preview/curryst/0.5.1/curryst.typ
  packages/preview/curryst/0.5.1/examples/math-formula.svg
  packages/preview/curryst/0.5.1/examples/natural-deduction.svg
  packages/preview/curryst/0.5.1/examples/rule-as-premise.svg
  packages/preview/curryst/0.5.1/examples/usage.svg
  packages/preview/curryst/0.5.1/typst.toml
Labels: update

#2223 tapestry:0.0.4
  packages/preview/tapestry/0.0.4/LICENSE
  packages/preview/tapestry/0.0.4/README.md
  packages/preview/tapestry/0.0.4/lib.typ
  packages/preview/tapestry/0.0.4/template/main.typ
  packages/preview/tapestry/0.0.4/thumbnail.png
  packages/preview/tapestry/0.0.4/typst.toml
Labels: update

#2224 its-scripted:0.1.0
  packages/preview/its-scripted/0.1.0/.gitignore
  packages/preview/its-scripted/0.1.0/LICENSE
  packages/preview/its-scripted/0.1.0/README.md
  packages/preview/its-scripted/0.1.0/docs.md
  packages/preview/its-scripted/0.1.0/example.typ
  packages/preview/its-scripted/0.1.0/lib.typ
  packages/preview/its-scripted/0.1.0/typst.toml
Labels: new

#2228 arborly:0.3.0
  packages/preview/arborly/0.3.0/LICENSE
  packages/preview/arborly/0.3.0/README.md
  packages/preview/arborly/0.3.0/docs/manual.pdf
  packages/preview/arborly/0.3.0/docs/manual.typ
  packages/preview/arborly/0.3.0/src/defaults.typ
  packages/preview/arborly/0.3.0/src/lib.typ
  packages/preview/arborly/0.3.0/typst.toml
Labels: update

#2229 pigmentpedia:0.3.2
  packages/preview/pigmentpedia/0.3.2/LICENSE
  packages/preview/pigmentpedia/0.3.2/README.md
  packages/preview/pigmentpedia/0.3.2/assets/logo/pigmentpedia-icon.svg
  packages/preview/pigmentpedia/0.3.2/assets/logo/pigmentpedia-logo.svg
  packages/preview/pigmentpedia/0.3.2/examples/example.pdf
  packages/preview/pigmentpedia/0.3.2/examples/example.typ
  packages/preview/pigmentpedia/0.3.2/lib.typ
  packages/preview/pigmentpedia/0.3.2/pigments/misc/Chinese/zhcn-trad.typ
  packages/preview/pigmentpedia/0.3.2/pigments/misc/Crayola.typ
  packages/preview/pigmentpedia/0.3.2/pigments/misc/Japanese/jajp-trad.typ
  packages/preview/pigmentpedia/0.3.2/pigments/palettes/Catppuccin.typ
  packages/preview/pigmentpedia/0.3.2/pigments/palettes/Nord.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/CSS.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/DIC.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/HKS.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/ISCC-NBS/ISCC-NBS.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/ISCC-NBS/nbs-iscc.txt
  packages/preview/pigmentpedia/0.3.2/pigments/standards/NCS.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/NipponPaint.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/Pantone.typ
  packages/preview/pigmentpedia/0.3.2/pigments/standards/RAL.typ
  packages/preview/pigmentpedia/0.3.2/src/convert.typ
  packages/preview/pigmentpedia/0.3.2/src/display.typ
  packages/preview/pigmentpedia/0.3.2/src/pigment-playground.typ
  packages/preview/pigmentpedia/0.3.2/src/pigments.typ
  packages/preview/pigmentpedia/0.3.2/src/private.typ
  packages/preview/pigmentpedia/0.3.2/src/search.typ
  packages/preview/pigmentpedia/0.3.2/src/show-tree.typ
  packages/preview/pigmentpedia/0.3.2/src/text-contrast.typ
  packages/preview/pigmentpedia/0.3.2/typst.toml
Labels: update

#2231 messeji:0.3.0
  packages/preview/messeji/0.3.0/.gitignore
  packages/preview/messeji/0.3.0/LICENSE
  packages/preview/messeji/0.3.0/README.md
  packages/preview/messeji/0.3.0/docs/example.jpg
  packages/preview/messeji/0.3.0/docs/image.example.json
  packages/preview/messeji/0.3.0/docs/img/cat.jpg
  packages/preview/messeji/0.3.0/docs/img/toebean.jpg
  packages/preview/messeji/0.3.0/docs/messeji-guide.pdf
  packages/preview/messeji/0.3.0/docs/messeji-guide.typ
  packages/preview/messeji/0.3.0/docs/output.example.json
  packages/preview/messeji/0.3.0/docs/template.typ
  packages/preview/messeji/0.3.0/messeji.typ
  packages/preview/messeji/0.3.0/typst.toml
Labels: update

#2233 silky-report-insa:0.5.0
  packages/preview/silky-report-insa/0.5.0/README.md
  packages/preview/silky-report-insa/0.5.0/assets/cvl/back-cover1.png
  packages/preview/silky-report-insa/0.5.0/assets/cvl/back-cover2.png
  packages/preview/silky-report-insa/0.5.0/assets/cvl/front-cover1.png
  packages/preview/silky-report-insa/0.5.0/assets/cvl/front-cover2.png
  packages/preview/silky-report-insa/0.5.0/assets/cvl/front-cover3.png
  packages/preview/silky-report-insa/0.5.0/assets/cvl/logo-white.png
  packages/preview/silky-report-insa/0.5.0/assets/cvl/logo.png
  packages/preview/silky-report-insa/0.5.0/assets/footer.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/back-cover1.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/back-cover2.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/front-cover1.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/front-cover2.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/front-cover3.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/logo-white.png
  packages/preview/silky-report-insa/0.5.0/assets/hdf/logo.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/back-cover1.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/back-cover2.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/front-cover1.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/front-cover2.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/front-cover3.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/logo-white.png
  packages/preview/silky-report-insa/0.5.0/assets/rennes/logo.png
  packages/preview/silky-report-insa/0.5.0/document-template.typ
  packages/preview/silky-report-insa/0.5.0/template/main.typ
  packages/preview/silky-report-insa/0.5.0/thumbnail-insa-document.png
  packages/preview/silky-report-insa/0.5.0/thumbnail-insa-report.png
  packages/preview/silky-report-insa/0.5.0/thumbnail-insa-stage.png
  packages/preview/silky-report-insa/0.5.0/thumbnail.png
  packages/preview/silky-report-insa/0.5.0/typst.toml
Labels: update

#2234 hand-in:1.0.0
  packages/preview/hand-in/1.0.0/LICENSE.txt
  packages/preview/hand-in/1.0.0/README.md
  packages/preview/hand-in/1.0.0/lib.typ
  packages/preview/hand-in/1.0.0/template/main.typ
  packages/preview/hand-in/1.0.0/thumbnail.png
  packages/preview/hand-in/1.0.0/typst.toml
Labels: new

#2235 cvssc:0.1.1
  packages/preview/cvssc/0.1.1/LICENSE.txt
  packages/preview/cvssc/0.1.1/README.md
  packages/preview/cvssc/0.1.1/src/cvssc.typ
  packages/preview/cvssc/0.1.1/src/cvssc.wasm
  packages/preview/cvssc/0.1.1/src/docs.pdf
  packages/preview/cvssc/0.1.1/src/docs.typ
  packages/preview/cvssc/0.1.1/src/main.typ
  packages/preview/cvssc/0.1.1/src/tests.typ
  packages/preview/cvssc/0.1.1/typst.toml
Labels: update

#2225 modern-shu-thesis:0.3.3
  packages/preview/modern-shu-thesis/0.3.3/LICENSE
  packages/preview/modern-shu-thesis/0.3.3/README.md
  packages/preview/modern-shu-thesis/0.3.3/assets/cover.png
  packages/preview/modern-shu-thesis/0.3.3/assets/under-cover.png
  packages/preview/modern-shu-thesis/0.3.3/layouts/appendix.typ
  packages/preview/modern-shu-thesis/0.3.3/layouts/doc.typ
  packages/preview/modern-shu-thesis/0.3.3/layouts/mainmatter.typ
  packages/preview/modern-shu-thesis/0.3.3/lib.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/abstract.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/acknowledgement.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/bib.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/conclusion.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/cover.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/declare.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/outline.typ
  packages/preview/modern-shu-thesis/0.3.3/pages/under-cover.typ
  packages/preview/modern-shu-thesis/0.3.3/style/distr.typ
  packages/preview/modern-shu-thesis/0.3.3/style/enums.typ
  packages/preview/modern-shu-thesis/0.3.3/style/figures.typ
  packages/preview/modern-shu-thesis/0.3.3/style/font.typ
  packages/preview/modern-shu-thesis/0.3.3/style/heading.typ
  packages/preview/modern-shu-thesis/0.3.3/style/uline.typ
  packages/preview/modern-shu-thesis/0.3.3/template/figures/energy-distribution.png
  packages/preview/modern-shu-thesis/0.3.3/template/ref.bib
  packages/preview/modern-shu-thesis/0.3.3/template/thesis.typ
  packages/preview/modern-shu-thesis/0.3.3/thumbnail.png
  packages/preview/modern-shu-thesis/0.3.3/typst.toml
Labels: update

#2227 versatile-apa:7.1.2
  packages/preview/versatile-apa/7.1.2/README.md
  packages/preview/versatile-apa/7.1.2/assets/img/ORCID_iD.svg
  packages/preview/versatile-apa/7.1.2/lib.typ
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-bar-graph.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-consort-flowchart.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-illustration-experimental-stimuli.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-map.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-mixed-methods-research-figure.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-path-model.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample-qualitative-research-figure.png
  packages/preview/versatile-apa/7.1.2/template/assets/images/sample.line-graph.png
  packages/preview/versatile-apa/7.1.2/template/assets/src/main.py
  packages/preview/versatile-apa/7.1.2/template/bibliography/ref.bib
  packages/preview/versatile-apa/7.1.2/template/bibliography/ref.yml
  packages/preview/versatile-apa/7.1.2/template/main.typ
  packages/preview/versatile-apa/7.1.2/template/sections/appendix.typ
  packages/preview/versatile-apa/7.1.2/template/sections/computer-code.typ
  packages/preview/versatile-apa/7.1.2/template/sections/figures.typ
  packages/preview/versatile-apa/7.1.2/template/sections/footnote.typ
  packages/preview/versatile-apa/7.1.2/template/sections/introduction.typ
  packages/preview/versatile-apa/7.1.2/template/sections/lists.typ
  packages/preview/versatile-apa/7.1.2/template/sections/math.typ
  packages/preview/versatile-apa/7.1.2/template/sections/quotes.typ
  packages/preview/versatile-apa/7.1.2/template/sections/tables.typ
  packages/preview/versatile-apa/7.1.2/thumbnail.png
  packages/preview/versatile-apa/7.1.2/typst.toml
  packages/preview/versatile-apa/7.1.2/utils/apa-figure.typ
  packages/preview/versatile-apa/7.1.2/utils/appendix.typ
  packages/preview/versatile-apa/7.1.2/utils/authoring.typ
  packages/preview/versatile-apa/7.1.2/utils/languages.typ
  packages/preview/versatile-apa/7.1.2/utils/orcid.typ
  packages/preview/versatile-apa/7.1.2/utils/to-string.typ
Labels: update

#2237 touying-simpl-cau:0.1.0
  packages/preview/touying-simpl-cau/0.1.0/LICENSE
  packages/preview/touying-simpl-cau/0.1.0/README.md
  packages/preview/touying-simpl-cau/0.1.0/assets/CAU_logo.svg
  packages/preview/touying-simpl-cau/0.1.0/assets/CAU_shield.svg
  packages/preview/touying-simpl-cau/0.1.0/assets/Gate.svg
  packages/preview/touying-simpl-cau/0.1.0/examples/main.typ
  packages/preview/touying-simpl-cau/0.1.0/lib.typ
  packages/preview/touying-simpl-cau/0.1.0/template/main.typ
  packages/preview/touying-simpl-cau/0.1.0/thumbnail.png
  packages/preview/touying-simpl-cau/0.1.0/typst.toml
Labels: new

#2226 magnifying-glass:0.1.0
  packages/preview/magnifying-glass/0.1.0/LICENSE
  packages/preview/magnifying-glass/0.1.0/README.md
  packages/preview/magnifying-glass/0.1.0/assets/example-content.png
  packages/preview/magnifying-glass/0.1.0/assets/example-image.png
  packages/preview/magnifying-glass/0.1.0/lib.typ
  packages/preview/magnifying-glass/0.1.0/typst.toml
  packages/preview/magnifying-glass/0.1.0/util.typ
Labels: new

#2243 starter-journal-article:0.3.3
  packages/preview/starter-journal-article/0.3.3/LICENSE
  packages/preview/starter-journal-article/0.3.3/README.md
  packages/preview/starter-journal-article/0.3.3/assets/basic.png
  packages/preview/starter-journal-article/0.3.3/assets/basic.typ
  packages/preview/starter-journal-article/0.3.3/assets/custom-abstract.png
  packages/preview/starter-journal-article/0.3.3/assets/custom-abstract.typ
  packages/preview/starter-journal-article/0.3.3/assets/custom-author-info.png
  packages/preview/starter-journal-article/0.3.3/assets/custom-author-info.typ
  packages/preview/starter-journal-article/0.3.3/assets/custom-title.png
  packages/preview/starter-journal-article/0.3.3/assets/custom-title.typ
  packages/preview/starter-journal-article/0.3.3/lib.typ
  packages/preview/starter-journal-article/0.3.3/template/main.typ
  packages/preview/starter-journal-article/0.3.3/template/ref.bib
  packages/preview/starter-journal-article/0.3.3/test.typ
  packages/preview/starter-journal-article/0.3.3/thumbnail.png
  packages/preview/starter-journal-article/0.3.3/typst.toml
Labels: update

#2244 cmarker:0.1.5
  packages/preview/cmarker/0.1.5/LICENSE
  packages/preview/cmarker/0.1.5/README.md
  packages/preview/cmarker/0.1.5/examples/hexagons.png
  packages/preview/cmarker/0.1.5/examples/simple.png
  packages/preview/cmarker/0.1.5/lib.typ
  packages/preview/cmarker/0.1.5/plugin.wasm
  packages/preview/cmarker/0.1.5/typst.toml
Labels: update

#2245 alexandria:0.2.0
  packages/preview/alexandria/0.2.0/.gitignore
  packages/preview/alexandria/0.2.0/CHANGELOG.md
  packages/preview/alexandria/0.2.0/LICENSE
  packages/preview/alexandria/0.2.0/README.md
  packages/preview/alexandria/0.2.0/docs/manual.pdf
  packages/preview/alexandria/0.2.0/gallery/example.pdf
  packages/preview/alexandria/0.2.0/src/alexandria.wasm
  packages/preview/alexandria/0.2.0/src/hayagriva.typ
  packages/preview/alexandria/0.2.0/src/internal.typ
  packages/preview/alexandria/0.2.0/src/lib.typ
  packages/preview/alexandria/0.2.0/src/state.typ
  packages/preview/alexandria/0.2.0/thumbnail-dark.svg
  packages/preview/alexandria/0.2.0/thumbnail-light.svg
  packages/preview/alexandria/0.2.0/typst.toml
Labels: update

#2242 shuosc-shu-bachelor-thesis:0.1.1
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/LICENSE
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/LICENSE-MIT
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/README.md
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/assets/cover.png
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/assets/under-cover.png
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/layouts/appendix.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/layouts/doc.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/layouts/mainmatter.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/lib.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/abstract.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/acknowledgement.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/bib.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/conclusion.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/cover.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/declare.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/outline.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/pages/under-cover.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/style/distr.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/style/enums.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/style/figures.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/style/font.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/style/heading.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/style/uline.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/template/figures/energy-distribution.png
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/template/ref.bib
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/template/thesis.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/thumbnail.png
  packages/preview/shuosc-shu-bachelor-thesis/0.1.1/typst.toml
Labels: new

#2248 formalettre:0.1.3
  packages/preview/formalettre/0.1.3/LICENSE
  packages/preview/formalettre/0.1.3/README.md
  packages/preview/formalettre/0.1.3/src/lib.typ
  packages/preview/formalettre/0.1.3/template/src/exemple.typ
  packages/preview/formalettre/0.1.3/thumbnail.png
  packages/preview/formalettre/0.1.3/typst.toml
Labels: update

#2247 touying-simpl-cau:0.2.0
  packages/preview/touying-simpl-cau/0.2.0/LICENSE
  packages/preview/touying-simpl-cau/0.2.0/README.md
  packages/preview/touying-simpl-cau/0.2.0/assets/CAU_logo.svg
  packages/preview/touying-simpl-cau/0.2.0/assets/CAU_shield.svg
  packages/preview/touying-simpl-cau/0.2.0/assets/Gate.svg
  packages/preview/touying-simpl-cau/0.2.0/examples/main.typ
  packages/preview/touying-simpl-cau/0.2.0/lib.typ
  packages/preview/touying-simpl-cau/0.2.0/template/main.typ
  packages/preview/touying-simpl-cau/0.2.0/thumbnail.png
  packages/preview/touying-simpl-cau/0.2.0/typst.toml
Labels: update

#2238 sdu-touying-simpl:0.3.0
  packages/preview/sdu-touying-simpl/0.3.0/LICENSE
  packages/preview/sdu-touying-simpl/0.3.0/README.md
  packages/preview/sdu-touying-simpl/0.3.0/dependency.typ
  packages/preview/sdu-touying-simpl/0.3.0/example/figures/main.png
  packages/preview/sdu-touying-simpl/0.3.0/example/main.typ
  packages/preview/sdu-touying-simpl/0.3.0/img/brand-rust.svg
  packages/preview/sdu-touying-simpl/0.3.0/img/github-mark-white.svg
  packages/preview/sdu-touying-simpl/0.3.0/img/sdu-title.png
  packages/preview/sdu-touying-simpl/0.3.0/img/sdu.png
  packages/preview/sdu-touying-simpl/0.3.0/img/word.png
  packages/preview/sdu-touying-simpl/0.3.0/img/word.svg
  packages/preview/sdu-touying-simpl/0.3.0/lib.typ
  packages/preview/sdu-touying-simpl/0.3.0/src/call-out.typ
  packages/preview/sdu-touying-simpl/0.3.0/typst.toml
Labels: update

#2249 fractusist:0.3.2
  packages/preview/fractusist/0.3.2/LICENSE
  packages/preview/fractusist/0.3.2/README.md
  packages/preview/fractusist/0.3.2/examples/dragon-curve-ex.png
  packages/preview/fractusist/0.3.2/examples/dragon-curve-ex.typ
  packages/preview/fractusist/0.3.2/examples/hypotrochoid-ex.png
  packages/preview/fractusist/0.3.2/examples/hypotrochoid-ex.typ
  packages/preview/fractusist/0.3.2/examples/koch-snowflake-ex.png
  packages/preview/fractusist/0.3.2/examples/koch-snowflake-ex.typ
  packages/preview/fractusist/0.3.2/examples/pythagorean-tree-ex.png
  packages/preview/fractusist/0.3.2/examples/pythagorean-tree-ex.typ
  packages/preview/fractusist/0.3.2/examples/random-fractal-tree-ex.png
  packages/preview/fractusist/0.3.2/examples/random-fractal-tree-ex.typ
  packages/preview/fractusist/0.3.2/examples/sierpinski-triangle-ex.png
  packages/preview/fractusist/0.3.2/examples/sierpinski-triangle-ex.typ
  packages/preview/fractusist/0.3.2/src/iterative/fibonacci.typ
  packages/preview/fractusist/0.3.2/src/iterative/z-order.typ
  packages/preview/fractusist/0.3.2/src/lib.typ
  packages/preview/fractusist/0.3.2/src/lsystem/dragon.typ
  packages/preview/fractusist/0.3.2/src/lsystem/hilbert.typ
  packages/preview/fractusist/0.3.2/src/lsystem/koch.typ
  packages/preview/fractusist/0.3.2/src/lsystem/lsystem-lib.typ
  packages/preview/fractusist/0.3.2/src/lsystem/lsystem.typ
  packages/preview/fractusist/0.3.2/src/lsystem/sierpinski.typ
  packages/preview/fractusist/0.3.2/src/parametric/lissajous.typ
  packages/preview/fractusist/0.3.2/src/parametric/spirograph.typ
  packages/preview/fractusist/0.3.2/src/recursive/carpet.typ
  packages/preview/fractusist/0.3.2/src/recursive/tree.typ
  packages/preview/fractusist/0.3.2/src/tilings/penrose-1.typ
  packages/preview/fractusist/0.3.2/src/tilings/penrose-2.typ
  packages/preview/fractusist/0.3.2/src/tilings/penrose-3.typ
  packages/preview/fractusist/0.3.2/src/tilings/util.typ
  packages/preview/fractusist/0.3.2/typst.toml
Labels: update

#2250 unofficial-cityuhk-thesis:0.1.0
  packages/preview/unofficial-cityuhk-thesis/0.1.0/LICENSE
  packages/preview/unofficial-cityuhk-thesis/0.1.0/README.md
  packages/preview/unofficial-cityuhk-thesis/0.1.0/assets/CityU_logo_2015.png
  packages/preview/unofficial-cityuhk-thesis/0.1.0/src/front-page.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/src/lib.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/chapters/chapter1.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/chapters/chapter2.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/figures/sample-figure.png
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/front-pages/abstract.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/front-pages/acknowledgement.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/main.typ
  packages/preview/unofficial-cityuhk-thesis/0.1.0/template/thesis.bib
  packages/preview/unofficial-cityuhk-thesis/0.1.0/thumbnail.png
  packages/preview/unofficial-cityuhk-thesis/0.1.0/typst.toml
Labels: new

#2230 machiatto:0.1.0
  packages/preview/machiatto/0.1.0/LICENSE
  packages/preview/machiatto/0.1.0/README.md
  packages/preview/machiatto/0.1.0/example/example.pdf
  packages/preview/machiatto/0.1.0/example/example.typ
  packages/preview/machiatto/0.1.0/example/hello.c
  packages/preview/machiatto/0.1.0/lib.typ
  packages/preview/machiatto/0.1.0/typst.toml
Labels: new

#2255 shiroa:0.2.3
  packages/preview/shiroa/0.2.3/LICENSE
  packages/preview/shiroa/0.2.3/README.md
  packages/preview/shiroa/0.2.3/lib.typ
  packages/preview/shiroa/0.2.3/media.typ
  packages/preview/shiroa/0.2.3/meta-and-state.typ
  packages/preview/shiroa/0.2.3/summary-internal.typ
  packages/preview/shiroa/0.2.3/summary.typ
  packages/preview/shiroa/0.2.3/supports-link.typ
  packages/preview/shiroa/0.2.3/supports-text.typ
  packages/preview/shiroa/0.2.3/sys.typ
  packages/preview/shiroa/0.2.3/template-link.typ
  packages/preview/shiroa/0.2.3/template-theme.typ
  packages/preview/shiroa/0.2.3/templates.typ
  packages/preview/shiroa/0.2.3/typst.toml
  packages/preview/shiroa/0.2.3/utils.typ
  packages/preview/shiroa/0.2.3/xcommand.typ
Labels: update

#2252 cyberschool-errorteaplate:0.1.4
  packages/preview/cyberschool-errorteaplate/0.1.4/LICENSE
  packages/preview/cyberschool-errorteaplate/0.1.4/README.md
  packages/preview/cyberschool-errorteaplate/0.1.4/docs/manual.pdf
  packages/preview/cyberschool-errorteaplate/0.1.4/src/lib.typ
  packages/preview/cyberschool-errorteaplate/0.1.4/template/assets/Logo_cyberschool.png
  packages/preview/cyberschool-errorteaplate/0.1.4/template/assets/Logo_univ_rennes.png
  packages/preview/cyberschool-errorteaplate/0.1.4/template/main.typ
  packages/preview/cyberschool-errorteaplate/0.1.4/thumbnail-dark.svg
  packages/preview/cyberschool-errorteaplate/0.1.4/thumbnail-light.svg
  packages/preview/cyberschool-errorteaplate/0.1.4/thumbnail.png
  packages/preview/cyberschool-errorteaplate/0.1.4/typst.toml
Labels: update

#2261 pubmatter:0.2.1
  packages/preview/pubmatter/0.2.1/LICENSE
  packages/preview/pubmatter/0.2.1/README.md
  packages/preview/pubmatter/0.2.1/pubmatter.typ
  packages/preview/pubmatter/0.2.1/typst.toml
  packages/preview/pubmatter/0.2.1/validate-frontmatter.typ
Labels: update

#2260 starter-journal-article:0.4.0
  packages/preview/starter-journal-article/0.4.0/LICENSE
  packages/preview/starter-journal-article/0.4.0/README.md
  packages/preview/starter-journal-article/0.4.0/assets/basic.png
  packages/preview/starter-journal-article/0.4.0/assets/basic.typ
  packages/preview/starter-journal-article/0.4.0/assets/custom-abstract.png
  packages/preview/starter-journal-article/0.4.0/assets/custom-abstract.typ
  packages/preview/starter-journal-article/0.4.0/assets/custom-author-info.png
  packages/preview/starter-journal-article/0.4.0/assets/custom-author-info.typ
  packages/preview/starter-journal-article/0.4.0/assets/custom-title.png
  packages/preview/starter-journal-article/0.4.0/assets/custom-title.typ
  packages/preview/starter-journal-article/0.4.0/lib.typ
  packages/preview/starter-journal-article/0.4.0/template/main.typ
  packages/preview/starter-journal-article/0.4.0/template/ref.bib
  packages/preview/starter-journal-article/0.4.0/test.typ
  packages/preview/starter-journal-article/0.4.0/thumbnail.png
  packages/preview/starter-journal-article/0.4.0/typst.toml
Labels: update

#2259 scienceicons:0.1.0
  packages/preview/scienceicons/0.1.0/LICENSE
  packages/preview/scienceicons/0.1.0/README.md
  packages/preview/scienceicons/0.1.0/index.typ
  packages/preview/scienceicons/0.1.0/typst.toml
Labels: update

#2263 pigmentpedia:0.3.3
  packages/preview/pigmentpedia/0.3.3/LICENSE
  packages/preview/pigmentpedia/0.3.3/README.md
  packages/preview/pigmentpedia/0.3.3/assets/logo/pigmentpedia-icon.svg
  packages/preview/pigmentpedia/0.3.3/assets/logo/pigmentpedia-logo.svg
  packages/preview/pigmentpedia/0.3.3/examples/example.pdf
  packages/preview/pigmentpedia/0.3.3/examples/example.typ
  packages/preview/pigmentpedia/0.3.3/lib.typ
  packages/preview/pigmentpedia/0.3.3/pigments/misc/Chinese/zhcn-trad.typ
  packages/preview/pigmentpedia/0.3.3/pigments/misc/Crayola.typ
  packages/preview/pigmentpedia/0.3.3/pigments/misc/Japanese/jajp-trad.typ
  packages/preview/pigmentpedia/0.3.3/pigments/palettes/Catppuccin.typ
  packages/preview/pigmentpedia/0.3.3/pigments/palettes/Nord.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/CSS.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/DIC.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/HKS.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/ISCC-NBS/ISCC-NBS.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/ISCC-NBS/nbs-iscc.txt
  packages/preview/pigmentpedia/0.3.3/pigments/standards/NCS.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/NipponPaint.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/Pantone.typ
  packages/preview/pigmentpedia/0.3.3/pigments/standards/RAL.typ
  packages/preview/pigmentpedia/0.3.3/src/convert.typ
  packages/preview/pigmentpedia/0.3.3/src/display.typ
  packages/preview/pigmentpedia/0.3.3/src/pigment-playground.typ
  packages/preview/pigmentpedia/0.3.3/src/pigments.typ
  packages/preview/pigmentpedia/0.3.3/src/private.typ
  packages/preview/pigmentpedia/0.3.3/src/search.typ
  packages/preview/pigmentpedia/0.3.3/src/show-tree.typ
  packages/preview/pigmentpedia/0.3.3/src/text-contrast.typ
  packages/preview/pigmentpedia/0.3.3/typst.toml
Labels: update

#2265 vartable:0.2.0
  packages/preview/vartable/0.2.0/LICENSE
  packages/preview/vartable/0.2.0/README.md
  packages/preview/vartable/0.2.0/documentation.pdf
  packages/preview/vartable/0.2.0/documentation.typ
  packages/preview/vartable/0.2.0/examples/hyperbolicFunction.png
  packages/preview/vartable/0.2.0/examples/hyperbolicFuntion.pdf
  packages/preview/vartable/0.2.0/examples/hyperbolicFuntion.typ
  packages/preview/vartable/0.2.0/examples/trigonometricFunction.pdf
  packages/preview/vartable/0.2.0/examples/trigonometricFunction.png
  packages/preview/vartable/0.2.0/examples/trigonometricFunction.typ
  packages/preview/vartable/0.2.0/tabvar.typ
  packages/preview/vartable/0.2.0/typst.toml
Labels: update

#2267 pillar:0.3.2
  packages/preview/pillar/0.3.2/LICENSE
  packages/preview/pillar/0.3.2/README.md
  packages/preview/pillar/0.3.2/src/impl.typ
  packages/preview/pillar/0.3.2/src/pillar.typ
  packages/preview/pillar/0.3.2/typst.toml
Labels: update

#2266 tidy:0.4.3
  packages/preview/tidy/0.4.3/LICENSE
  packages/preview/tidy/0.4.3/README.md
  packages/preview/tidy/0.4.3/src/helping.typ
  packages/preview/tidy/0.4.3/src/locales.typ
  packages/preview/tidy/0.4.3/src/new-parser.typ
  packages/preview/tidy/0.4.3/src/old-parser.typ
  packages/preview/tidy/0.4.3/src/parse-module.typ
  packages/preview/tidy/0.4.3/src/show-example.typ
  packages/preview/tidy/0.4.3/src/show-module.typ
  packages/preview/tidy/0.4.3/src/styles.typ
  packages/preview/tidy/0.4.3/src/styles/default.typ
  packages/preview/tidy/0.4.3/src/styles/help.typ
  packages/preview/tidy/0.4.3/src/styles/minimal.typ
  packages/preview/tidy/0.4.3/src/testing.typ
  packages/preview/tidy/0.4.3/src/tidy.typ
  packages/preview/tidy/0.4.3/src/utilities.typ
  packages/preview/tidy/0.4.3/typst.toml
Labels: update

#2269 rexllent:0.3.1
  packages/preview/rexllent/0.3.1/LICENSE
  packages/preview/rexllent/0.3.1/README.md
  packages/preview/rexllent/0.3.1/assets/example1.png
  packages/preview/rexllent/0.3.1/assets/example2.png
  packages/preview/rexllent/0.3.1/assets/example3.png
  packages/preview/rexllent/0.3.1/assets/example4.png
  packages/preview/rexllent/0.3.1/assets/example5.png
  packages/preview/rexllent/0.3.1/assets/example6.png
  packages/preview/rexllent/0.3.1/assets/example7.png
  packages/preview/rexllent/0.3.1/assets/excel.png
  packages/preview/rexllent/0.3.1/assets/three-line-table.png
  packages/preview/rexllent/0.3.1/assets/typst_example1.png
  packages/preview/rexllent/0.3.1/assets/typst_example2.png
  packages/preview/rexllent/0.3.1/assets/typst_example3.png
  packages/preview/rexllent/0.3.1/src/lib.typ
  packages/preview/rexllent/0.3.1/src/mod.typ
  packages/preview/rexllent/0.3.1/src/rexllent.wasm
  packages/preview/rexllent/0.3.1/typst.toml
Labels: update

#2272 splash:0.5.0
  packages/preview/splash/0.5.0/LICENSE
  packages/preview/splash/0.5.0/README.md
  packages/preview/splash/0.5.0/doc/main.pdf
  packages/preview/splash/0.5.0/doc/main.typ
  packages/preview/splash/0.5.0/doc/util.typ
  packages/preview/splash/0.5.0/src/palettes.typ
  packages/preview/splash/0.5.0/src/palettes/beamer.typ
  packages/preview/splash/0.5.0/src/palettes/google-workspace.typ
  packages/preview/splash/0.5.0/src/palettes/kth.typ
  packages/preview/splash/0.5.0/src/palettes/latexcolors.typ
  packages/preview/splash/0.5.0/src/palettes/misc.typ
  packages/preview/splash/0.5.0/src/palettes/okabe-ito.typ
  packages/preview/splash/0.5.0/src/palettes/seaborn.typ
  packages/preview/splash/0.5.0/src/palettes/tailwind-css.typ
  packages/preview/splash/0.5.0/src/palettes/tol.typ
  packages/preview/splash/0.5.0/src/palettes/typst-highlighting.typ
  packages/preview/splash/0.5.0/src/palettes/xcolor.typ
  packages/preview/splash/0.5.0/src/palettes/xkcd.typ
  packages/preview/splash/0.5.0/typst.toml
Labels: update

#2262 htlwienwest-da:0.3.2
  packages/preview/htlwienwest-da/0.3.2/LICENSE
  packages/preview/htlwienwest-da/0.3.2/README.md
  packages/preview/htlwienwest-da/0.3.2/blob/p01.png
  packages/preview/htlwienwest-da/0.3.2/blob/p08.png
  packages/preview/htlwienwest-da/0.3.2/blob/p12.png
  packages/preview/htlwienwest-da/0.3.2/blob/p19.png
  packages/preview/htlwienwest-da/0.3.2/diplomarbeit.pdf
  packages/preview/htlwienwest-da/0.3.2/justfile
  packages/preview/htlwienwest-da/0.3.2/lib.typ
  packages/preview/htlwienwest-da/0.3.2/lib/assertions.typ
  packages/preview/htlwienwest-da/0.3.2/lib/elements.typ
  packages/preview/htlwienwest-da/0.3.2/lib/fontchecker.typ
  packages/preview/htlwienwest-da/0.3.2/lib/images/HTLWienWest.png
  packages/preview/htlwienwest-da/0.3.2/lib/pages/arbeitsaufteilung.typ
  packages/preview/htlwienwest-da/0.3.2/lib/pages/deckblatt.typ
  packages/preview/htlwienwest-da/0.3.2/lib/pages/dokumentation.typ
  packages/preview/htlwienwest-da/0.3.2/lib/pages/eidesstattliche.typ
  packages/preview/htlwienwest-da/0.3.2/lib/settings.typ
  packages/preview/htlwienwest-da/0.3.2/lib/template.typ
  packages/preview/htlwienwest-da/0.3.2/scripts/package
  packages/preview/htlwienwest-da/0.3.2/scripts/relpaths
  packages/preview/htlwienwest-da/0.3.2/template/abbildungen/demoAbb.jpeg
  packages/preview/htlwienwest-da/0.3.2/template/abbildungen/typst.svg
  packages/preview/htlwienwest-da/0.3.2/template/anhang.typ
  packages/preview/htlwienwest-da/0.3.2/template/diplomarbeit.typ
  packages/preview/htlwienwest-da/0.3.2/template/literaturverzeichnis.bib
  packages/preview/htlwienwest-da/0.3.2/thumbnail.png
  packages/preview/htlwienwest-da/0.3.2/typst.toml
Labels: update

#2275 shuxuejuan:0.1.2
  packages/preview/shuxuejuan/0.1.2/LICENSE
  packages/preview/shuxuejuan/0.1.2/README.md
  packages/preview/shuxuejuan/0.1.2/examples/example.typ
  packages/preview/shuxuejuan/0.1.2/lib.typ
  packages/preview/shuxuejuan/0.1.2/src/answer.typ
  packages/preview/shuxuejuan/0.1.2/src/env.typ
  packages/preview/shuxuejuan/0.1.2/src/export.typ
  packages/preview/shuxuejuan/0.1.2/src/question-group.typ
  packages/preview/shuxuejuan/0.1.2/src/question.typ
  packages/preview/shuxuejuan/0.1.2/src/reference.typ
  packages/preview/shuxuejuan/0.1.2/src/utils.typ
  packages/preview/shuxuejuan/0.1.2/typst.toml
Labels: update

#2279 htlwienwest-da:0.3.3
  packages/preview/htlwienwest-da/0.3.3/LICENSE
  packages/preview/htlwienwest-da/0.3.3/README.md
  packages/preview/htlwienwest-da/0.3.3/blob/p01.png
  packages/preview/htlwienwest-da/0.3.3/blob/p08.png
  packages/preview/htlwienwest-da/0.3.3/blob/p12.png
  packages/preview/htlwienwest-da/0.3.3/blob/p19.png
  packages/preview/htlwienwest-da/0.3.3/diplomarbeit.pdf
  packages/preview/htlwienwest-da/0.3.3/justfile
  packages/preview/htlwienwest-da/0.3.3/lib.typ
  packages/preview/htlwienwest-da/0.3.3/lib/assertions.typ
  packages/preview/htlwienwest-da/0.3.3/lib/elements.typ
  packages/preview/htlwienwest-da/0.3.3/lib/fontchecker.typ
  packages/preview/htlwienwest-da/0.3.3/lib/images/HTLWienWest.png
  packages/preview/htlwienwest-da/0.3.3/lib/pages/arbeitsaufteilung.typ
  packages/preview/htlwienwest-da/0.3.3/lib/pages/deckblatt.typ
  packages/preview/htlwienwest-da/0.3.3/lib/pages/dokumentation.typ
  packages/preview/htlwienwest-da/0.3.3/lib/pages/eidesstattliche.typ
  packages/preview/htlwienwest-da/0.3.3/lib/settings.typ
  packages/preview/htlwienwest-da/0.3.3/lib/template.typ
  packages/preview/htlwienwest-da/0.3.3/scripts/package
  packages/preview/htlwienwest-da/0.3.3/scripts/relpaths
  packages/preview/htlwienwest-da/0.3.3/template/abbildungen/demoAbb.jpeg
  packages/preview/htlwienwest-da/0.3.3/template/abbildungen/typst.svg
  packages/preview/htlwienwest-da/0.3.3/template/anhang.typ
  packages/preview/htlwienwest-da/0.3.3/template/diplomarbeit.typ
  packages/preview/htlwienwest-da/0.3.3/template/literaturverzeichnis.bib
  packages/preview/htlwienwest-da/0.3.3/thumbnail.png
  packages/preview/htlwienwest-da/0.3.3/typst.toml
Labels: update

#2281 zebraw:0.5.4
  packages/preview/zebraw/0.5.4/LICENSE
  packages/preview/zebraw/0.5.4/README.md
  packages/preview/zebraw/0.5.4/README_zh.md
  packages/preview/zebraw/0.5.4/assets/copyable-false.png
  packages/preview/zebraw/0.5.4/assets/copyable-true.png
  packages/preview/zebraw/0.5.4/assets/frame_0.svg
  packages/preview/zebraw/0.5.4/assets/frame_1.svg
  packages/preview/zebraw/0.5.4/assets/frame_10.svg
  packages/preview/zebraw/0.5.4/assets/frame_11.svg
  packages/preview/zebraw/0.5.4/assets/frame_12.svg
  packages/preview/zebraw/0.5.4/assets/frame_13.svg
  packages/preview/zebraw/0.5.4/assets/frame_14.svg
  packages/preview/zebraw/0.5.4/assets/frame_15.svg
  packages/preview/zebraw/0.5.4/assets/frame_16.svg
  packages/preview/zebraw/0.5.4/assets/frame_17.svg
  packages/preview/zebraw/0.5.4/assets/frame_18.svg
  packages/preview/zebraw/0.5.4/assets/frame_19.svg
  packages/preview/zebraw/0.5.4/assets/frame_2.svg
  packages/preview/zebraw/0.5.4/assets/frame_20.svg
  packages/preview/zebraw/0.5.4/assets/frame_21.svg
  packages/preview/zebraw/0.5.4/assets/frame_22.svg
  packages/preview/zebraw/0.5.4/assets/frame_23.svg
  packages/preview/zebraw/0.5.4/assets/frame_24.svg
  packages/preview/zebraw/0.5.4/assets/frame_25.svg
  packages/preview/zebraw/0.5.4/assets/frame_26.svg
  packages/preview/zebraw/0.5.4/assets/frame_27.svg
  packages/preview/zebraw/0.5.4/assets/frame_28.svg
  packages/preview/zebraw/0.5.4/assets/frame_29.svg
  packages/preview/zebraw/0.5.4/assets/frame_3.svg
  packages/preview/zebraw/0.5.4/assets/frame_30.svg
  packages/preview/zebraw/0.5.4/assets/frame_4.svg
  packages/preview/zebraw/0.5.4/assets/frame_5.svg
  packages/preview/zebraw/0.5.4/assets/frame_6.svg
  packages/preview/zebraw/0.5.4/assets/frame_7.svg
  packages/preview/zebraw/0.5.4/assets/frame_8.svg
  packages/preview/zebraw/0.5.4/assets/frame_9.svg
  packages/preview/zebraw/0.5.4/assets/html-example.png
  packages/preview/zebraw/0.5.4/assets/html-template.typ
  packages/preview/zebraw/0.5.4/assets/tokyo-night.tmTheme
  packages/preview/zebraw/0.5.4/src/html.typ
  packages/preview/zebraw/0.5.4/src/indentation.typ
  packages/preview/zebraw/0.5.4/src/lib.typ
  packages/preview/zebraw/0.5.4/src/mod.typ
  packages/preview/zebraw/0.5.4/src/state.typ
  packages/preview/zebraw/0.5.4/src/theme.typ
  packages/preview/zebraw/0.5.4/src/util.typ
  packages/preview/zebraw/0.5.4/typst.toml
Labels: update

#2282 illc-mol-thesis:0.2.0
  packages/preview/illc-mol-thesis/0.2.0/LICENSE
  packages/preview/illc-mol-thesis/0.2.0/README.md
  packages/preview/illc-mol-thesis/0.2.0/img/illclogo.svg
  packages/preview/illc-mol-thesis/0.2.0/img/thumbnail.png
  packages/preview/illc-mol-thesis/0.2.0/src/main.pdf
  packages/preview/illc-mol-thesis/0.2.0/src/main.typ
  packages/preview/illc-mol-thesis/0.2.0/template/1-introduction.typ
  packages/preview/illc-mol-thesis/0.2.0/template/2-my-logic.typ
  packages/preview/illc-mol-thesis/0.2.0/template/3-examples.typ
  packages/preview/illc-mol-thesis/0.2.0/template/main.typ
  packages/preview/illc-mol-thesis/0.2.0/template/references.bib
  packages/preview/illc-mol-thesis/0.2.0/typst.toml
Labels: update

#2274 clean-agh-thesis:0.1.0
  packages/preview/clean-agh-thesis/0.1.0/LICENSE
  packages/preview/clean-agh-thesis/0.1.0/README.md
  packages/preview/clean-agh-thesis/0.1.0/agh.jpg
  packages/preview/clean-agh-thesis/0.1.0/lib.typ
  packages/preview/clean-agh-thesis/0.1.0/template/main.typ
  packages/preview/clean-agh-thesis/0.1.0/template/refs.bib
  packages/preview/clean-agh-thesis/0.1.0/thumbnail.png
  packages/preview/clean-agh-thesis/0.1.0/typst.toml
Labels: new

#2271 qec-thrust:0.1.0
  packages/preview/qec-thrust/0.1.0/LICENSE
  packages/preview/qec-thrust/0.1.0/README.md
  packages/preview/qec-thrust/0.1.0/examples/steane.png
  packages/preview/qec-thrust/0.1.0/examples/surface.png
  packages/preview/qec-thrust/0.1.0/examples/toric1.png
  packages/preview/qec-thrust/0.1.0/examples/toric2.png
  packages/preview/qec-thrust/0.1.0/lib.typ
  packages/preview/qec-thrust/0.1.0/typst.toml
Labels: new

#2240 modern-bnu-thesis:0.0.2
  packages/preview/modern-bnu-thesis/0.0.2/.gitignore
  packages/preview/modern-bnu-thesis/0.0.2/LICENSE
  packages/preview/modern-bnu-thesis/0.0.2/README.md
  packages/preview/modern-bnu-thesis/0.0.2/assets/vi/bnu-name.svg
  packages/preview/modern-bnu-thesis/0.0.2/assets/vi/old_bnu-name.svg
  packages/preview/modern-bnu-thesis/0.0.2/imgs/editor.png
  packages/preview/modern-bnu-thesis/0.0.2/imgs/empty_avatar.png
  packages/preview/modern-bnu-thesis/0.0.2/layouts/appendix.typ
  packages/preview/modern-bnu-thesis/0.0.2/layouts/doc.typ
  packages/preview/modern-bnu-thesis/0.0.2/layouts/mainmatter.typ
  packages/preview/modern-bnu-thesis/0.0.2/layouts/preface.typ
  packages/preview/modern-bnu-thesis/0.0.2/lib.typ
  packages/preview/modern-bnu-thesis/0.0.2/others/bachelor-proposal.typ
  packages/preview/modern-bnu-thesis/0.0.2/others/master-proposal-logo.png
  packages/preview/modern-bnu-thesis/0.0.2/others/master-proposal.typ
  packages/preview/modern-bnu-thesis/0.0.2/others/style.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/achievements.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/acknowledgement.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/bachelor-abstract-en.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/bachelor-abstract.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/bachelor-cover.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/bachelor-decl-page.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/bachelor-outline-page.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/fonts-display-page.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/list-of-figures.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/list-of-tables.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/master-abstract-en.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/master-abstract.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/master-cover.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/master-decl-page.typ
  packages/preview/modern-bnu-thesis/0.0.2/pages/notation.typ
  packages/preview/modern-bnu-thesis/0.0.2/template/chapters/ch1.typ
  packages/preview/modern-bnu-thesis/0.0.2/template/chapters/ch2.typ
  packages/preview/modern-bnu-thesis/0.0.2/template/images/bnu-emblem.svg
  packages/preview/modern-bnu-thesis/0.0.2/template/ref.bib
  packages/preview/modern-bnu-thesis/0.0.2/template/thesis.typ
  packages/preview/modern-bnu-thesis/0.0.2/thumbnail.png
  packages/preview/modern-bnu-thesis/0.0.2/typst.toml
  packages/preview/modern-bnu-thesis/0.0.2/utils/bilingual-bibliography.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/custom-algo.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/custom-cuti.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/custom-heading.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/custom-numbering.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/custom-tablex.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/datetime-display.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/double-underline.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/hline.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/indent.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/invisible-heading.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/justify-text.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/style.typ
  packages/preview/modern-bnu-thesis/0.0.2/utils/unpairs.typ
Labels: update

#2264 tfguf:0.0.2
  packages/preview/tfguf/0.0.2/LICENSE
  packages/preview/tfguf/0.0.2/README.md
  packages/preview/tfguf/0.0.2/portada.png
  packages/preview/tfguf/0.0.2/template/bibliografia.bib
  packages/preview/tfguf/0.0.2/template/tfg.typ
  packages/preview/tfguf/0.0.2/template/unir logo.png
  packages/preview/tfguf/0.0.2/typst.toml
  packages/preview/tfguf/0.0.2/unirfisica.typ
Labels: update
