Repository typst/packages, pull requests merged in 2025-08, with the labels that each got.

#2804 booktabs:0.0.2
  packages/preview/booktabs/0.0.2/LICENSE
  packages/preview/booktabs/0.0.2/README.md
  packages/preview/booktabs/0.0.2/examples/simple_table.pdf
  packages/preview/booktabs/0.0.2/examples/simple_table.png
  packages/preview/booktabs/0.0.2/examples/simple_table.typ
  packages/preview/booktabs/0.0.2/src/lib.typ
  packages/preview/booktabs/0.0.2/typst.toml
Labels: update

#2806 olaii-upn-qr:0.0.1
  packages/preview/olaii-upn-qr/0.0.1/.typstignore
  packages/preview/olaii-upn-qr/0.0.1/LICENSE
  packages/preview/olaii-upn-qr/0.0.1/README.md
  packages/preview/olaii-upn-qr/0.0.1/examples/bottom.typ
  packages/preview/olaii-upn-qr/0.0.1/examples/main.typ
  packages/preview/olaii-upn-qr/0.0.1/examples/multiple.typ
  packages/preview/olaii-upn-qr/0.0.1/src/assets/upn-qr.png
  packages/preview/olaii-upn-qr/0.0.1/src/olaii-upn-qr.typ
  packages/preview/olaii-upn-qr/0.0.1/thumbnail.png
  packages/preview/olaii-upn-qr/0.0.1/typst.toml
Labels: new

#2813 cleanified-hpi-research-proposal:0.0.1
  packages/preview/cleanified-hpi-research-proposal/0.0.1/LICENSE
  packages/preview/cleanified-hpi-research-proposal/0.0.1/README.md
  packages/preview/cleanified-hpi-research-proposal/0.0.1/example/main.typ
  packages/preview/cleanified-hpi-research-proposal/0.0.1/template/hpi_logo.svg
  packages/preview/cleanified-hpi-research-proposal/0.0.1/template/lib.typ
  packages/preview/cleanified-hpi-research-proposal/0.0.1/thumbnail.png
  packages/preview/cleanified-hpi-research-proposal/0.0.1/typst.toml
Labels: new

#2829 clean-hwr:0.1.3
  packages/preview/clean-hwr/0.1.3/LICENSE
  packages/preview/clean-hwr/0.1.3/README.md
  packages/preview/clean-hwr/0.1.3/hwr_citation.csl
  packages/preview/clean-hwr/0.1.3/lib.typ
  packages/preview/clean-hwr/0.1.3/template/images/header_logo.png
  packages/preview/clean-hwr/0.1.3/template/main.typ
  packages/preview/clean-hwr/0.1.3/template/refs.bib
  packages/preview/clean-hwr/0.1.3/thumbnail.png
  packages/preview/clean-hwr/0.1.3/typst.toml
Labels: update

#2835 lavandula:0.1.0
  packages/preview/lavandula/0.1.0/LICENSE
  packages/preview/lavandula/0.1.0/README.md
  packages/preview/lavandula/0.1.0/src/lavandula.typ
  packages/preview/lavandula/0.1.0/src/lib.typ
  packages/preview/lavandula/0.1.0/templates/assets/flags/LICENSE.txt
  packages/preview/lavandula/0.1.0/templates/assets/flags/fr.png
  packages/preview/lavandula/0.1.0/templates/assets/flags/gb.png
  packages/preview/lavandula/0.1.0/templates/main.typ
  packages/preview/lavandula/0.1.0/thumbnail.png
  packages/preview/lavandula/0.1.0/typst.toml
Labels: new

#2846 dice:1.0.0
  packages/preview/dice/1.0.0/LISENSE
  packages/preview/dice/1.0.0/README.md
  packages/preview/dice/1.0.0/lib.typ
  packages/preview/dice/1.0.0/typst.toml
Labels: new

#2847 xyznote:0.4.0
  packages/preview/xyznote/0.4.0/LICENSE
  packages/preview/xyznote/0.4.0/README.md
  packages/preview/xyznote/0.4.0/src/color-box.typ
  packages/preview/xyznote/0.4.0/src/colors.typ
  packages/preview/xyznote/0.4.0/src/lib.typ
  packages/preview/xyznote/0.4.0/template/main.typ
  packages/preview/xyznote/0.4.0/template/refs.bib
  packages/preview/xyznote/0.4.0/thumbnail.png
  packages/preview/xyznote/0.4.0/typst.toml
Labels: update

#2839 mercator:0.1.0
  packages/preview/mercator/0.1.0/LICENSE
  packages/preview/mercator/0.1.0/README.md
  packages/preview/mercator/0.1.0/mercator.typ
  packages/preview/mercator/0.1.0/mercator.wasm
  packages/preview/mercator/0.1.0/typst.toml
Labels: new

#2840 asciim:0.1.0
  packages/preview/asciim/0.1.0/LICENSE
  packages/preview/asciim/0.1.0/README.md
  packages/preview/asciim/0.1.0/lib.typ
  packages/preview/asciim/0.1.0/typst.toml
Labels: new

#2841 booktabs:0.0.3
  packages/preview/booktabs/0.0.3/LICENSE
  packages/preview/booktabs/0.0.3/README.md
  packages/preview/booktabs/0.0.3/docs/index.md
  packages/preview/booktabs/0.0.3/examples/simple_table.pdf
  packages/preview/booktabs/0.0.3/examples/simple_table.png
  packages/preview/booktabs/0.0.3/examples/simple_table.typ
  packages/preview/booktabs/0.0.3/src/lib.typ
  packages/preview/booktabs/0.0.3/typst.toml
Labels: update

#2849 ctyp:0.1.1
  packages/preview/ctyp/0.1.1/LICENSE
  packages/preview/ctyp/0.1.1/NEWS.md
  packages/preview/ctyp/0.1.1/README.md
  packages/preview/ctyp/0.1.1/lib.typ
  packages/preview/ctyp/0.1.1/src/ctyp.typ
  packages/preview/ctyp/0.1.1/src/fonts/fandol.typ
  packages/preview/ctyp/0.1.1/src/fonts/fangzheng.typ
  packages/preview/ctyp/0.1.1/src/fonts/huawen.typ
  packages/preview/ctyp/0.1.1/src/fonts/index.typ
  packages/preview/ctyp/0.1.1/src/fonts/noto.typ
  packages/preview/ctyp/0.1.1/src/fonts/source.typ
  packages/preview/ctyp/0.1.1/src/fonts/windows.typ
  packages/preview/ctyp/0.1.1/src/index.typ
  packages/preview/ctyp/0.1.1/src/utils/enumitem.typ
  packages/preview/ctyp/0.1.1/src/utils/page-grid.typ
  packages/preview/ctyp/0.1.1/typst.toml
Labels: update

#2852 ezexam:0.1.2
  packages/preview/ezexam/0.1.2/LICENSE
  packages/preview/ezexam/0.1.2/README.md
  packages/preview/ezexam/0.1.2/ezexam.typ
  packages/preview/ezexam/0.1.2/template/17.png
  packages/preview/ezexam/0.1.2/template/6.png
  packages/preview/ezexam/0.1.2/template/main.typ
  packages/preview/ezexam/0.1.2/thumnail.png
  packages/preview/ezexam/0.1.2/typst.toml
  packages/preview/ezexam/0.1.2/utils/choice.typ
  packages/preview/ezexam/0.1.2/utils/const-state.typ
  packages/preview/ezexam/0.1.2/utils/outline.typ
  packages/preview/ezexam/0.1.2/utils/question.typ
Labels: update

#2854 cyberschool-errorteaplate:0.1.9
  packages/preview/cyberschool-errorteaplate/0.1.9/LICENSE
  packages/preview/cyberschool-errorteaplate/0.1.9/README.md
  packages/preview/cyberschool-errorteaplate/0.1.9/src/lib.typ
  packages/preview/cyberschool-errorteaplate/0.1.9/template/assets/Logo_cyberschool.png
  packages/preview/cyberschool-errorteaplate/0.1.9/template/assets/Logo_univ_rennes.png
  packages/preview/cyberschool-errorteaplate/0.1.9/template/main.typ
  packages/preview/cyberschool-errorteaplate/0.1.9/thumbnail.png
  packages/preview/cyberschool-errorteaplate/0.1.9/typst.toml
Labels: update

#2848 gruvy:2.1.0
  packages/preview/gruvy/2.1.0/LICENSE
  packages/preview/gruvy/2.1.0/README.md
  packages/preview/gruvy/2.1.0/assets/example-1.png
  packages/preview/gruvy/2.1.0/assets/example-2.png
  packages/preview/gruvy/2.1.0/assets/example-3.png
  packages/preview/gruvy/2.1.0/assets/example-4.png
  packages/preview/gruvy/2.1.0/assets/example-5.png
  packages/preview/gruvy/2.1.0/assets/example-6.png
  packages/preview/gruvy/2.1.0/colors.typ
  packages/preview/gruvy/2.1.0/gruvboxDark.tmTheme
  packages/preview/gruvy/2.1.0/gruvboxLight.tmTheme
  packages/preview/gruvy/2.1.0/lib.typ
  packages/preview/gruvy/2.1.0/typst.toml
Labels: update

#2855 lure:0.1.0
  packages/preview/lure/0.1.0/LICENSE
  packages/preview/lure/0.1.0/README.md
  packages/preview/lure/0.1.0/typ/lib.typ
  packages/preview/lure/0.1.0/typ/lure.typ
  packages/preview/lure/0.1.0/typ/lure.wasm
  packages/preview/lure/0.1.0/typst.toml
Labels: new

#2856 rowmantic:0.4.0
  packages/preview/rowmantic/0.4.0/CHANGELOG.md
  packages/preview/rowmantic/0.4.0/LICENSE-EUPL-1.2.txt
  packages/preview/rowmantic/0.4.0/README.md
  packages/preview/rowmantic/0.4.0/docs/figures/readmepicture1-dark.svg
  packages/preview/rowmantic/0.4.0/docs/figures/readmepicture1.svg
  packages/preview/rowmantic/0.4.0/docs/figures/readmepicture2-dark.svg
  packages/preview/rowmantic/0.4.0/docs/figures/readmepicture2.svg
  packages/preview/rowmantic/0.4.0/docs/rowmantic-manual.pdf
  packages/preview/rowmantic/0.4.0/src/lib.typ
  packages/preview/rowmantic/0.4.0/src/rowtable.typ
  packages/preview/rowmantic/0.4.0/typst.toml
Labels: update

#2857 barcala:0.1.3
  packages/preview/barcala/0.1.3/LICENSE
  packages/preview/barcala/0.1.3/README.md
  packages/preview/barcala/0.1.3/src/images/informática.png
  packages/preview/barcala/0.1.3/src/images/ingeniería.png
  packages/preview/barcala/0.1.3/src/images/unlp.svg
  packages/preview/barcala/0.1.3/src/lib.typ
  packages/preview/barcala/0.1.3/src/types.typ
  packages/preview/barcala/0.1.3/template/bibliografia.bib
  packages/preview/barcala/0.1.3/template/main.typ
  packages/preview/barcala/0.1.3/thumbnails/1.png
  packages/preview/barcala/0.1.3/thumbnails/2.png
  packages/preview/barcala/0.1.3/typst.toml
Labels: update

#2858 cyberschool-errorteaplate:0.1.10
  packages/preview/cyberschool-errorteaplate/0.1.10/LICENSE
  packages/preview/cyberschool-errorteaplate/0.1.10/README.md
  packages/preview/cyberschool-errorteaplate/0.1.10/src/lib.typ
  packages/preview/cyberschool-errorteaplate/0.1.10/template/assets/Logo_cyberschool.png
  packages/preview/cyberschool-errorteaplate/0.1.10/template/assets/Logo_univ_rennes.png
  packages/preview/cyberschool-errorteaplate/0.1.10/template/main.typ
  packages/preview/cyberschool-errorteaplate/0.1.10/thumbnail.png
  packages/preview/cyberschool-errorteaplate/0.1.10/typst.toml
Labels: update

#2843 muw-touying-community:0.1.0
  packages/preview/muw-touying-community/0.1.0/LICENSE
  packages/preview/muw-touying-community/0.1.0/README.md
  packages/preview/muw-touying-community/0.1.0/assets/muw_dunkelblau.svg
  packages/preview/muw-touying-community/0.1.0/assets/muw_white.svg
  packages/preview/muw-touying-community/0.1.0/colors.typ
  packages/preview/muw-touying-community/0.1.0/examples/example_brain_mri.png
  packages/preview/muw-touying-community/0.1.0/examples/example_infobox_picture.jpg
  packages/preview/muw-touying-community/0.1.0/examples/example_wide_picture.jpg
  packages/preview/muw-touying-community/0.1.0/examples/template.typ
  packages/preview/muw-touying-community/0.1.0/lib.typ
  packages/preview/muw-touying-community/0.1.0/thumbnail.png
  packages/preview/muw-touying-community/0.1.0/typst.toml
Labels: new

#2864 g-exam:0.4.3
  packages/preview/g-exam/0.4.3/LICENSE
  packages/preview/g-exam/0.4.3/README.md
  packages/preview/g-exam/0.4.3/gallery/exam-table-content.png
  packages/preview/g-exam/0.4.3/src/auxiliary.typ
  packages/preview/g-exam/0.4.3/src/clarification.typ
  packages/preview/g-exam/0.4.3/src/exam.typ
  packages/preview/g-exam/0.4.3/src/global.typ
  packages/preview/g-exam/0.4.3/src/lang.toml
  packages/preview/g-exam/0.4.3/src/lib.typ
  packages/preview/g-exam/0.4.3/src/option.typ
  packages/preview/g-exam/0.4.3/src/question.typ
  packages/preview/g-exam/0.4.3/src/solution.typ
  packages/preview/g-exam/0.4.3/src/sugar.typ
  packages/preview/g-exam/0.4.3/template/1er exam.typ
  packages/preview/g-exam/0.4.3/template/logo.png
  packages/preview/g-exam/0.4.3/thumbnail.png
  packages/preview/g-exam/0.4.3/typst.toml
Labels: update

#2863 cellpress-unofficial:0.1.0
  packages/preview/cellpress-unofficial/0.1.0/LICENSE
  packages/preview/cellpress-unofficial/0.1.0/README.md
  packages/preview/cellpress-unofficial/0.1.0/example/example.png
  packages/preview/cellpress-unofficial/0.1.0/example/example.typ
  packages/preview/cellpress-unofficial/0.1.0/src/lib.typ
  packages/preview/cellpress-unofficial/0.1.0/typst.toml
Labels: new

#2871 cyberschool-errorteaplate:0.1.11
  packages/preview/cyberschool-errorteaplate/0.1.11/LICENSE
  packages/preview/cyberschool-errorteaplate/0.1.11/README.md
  packages/preview/cyberschool-errorteaplate/0.1.11/src/lib.typ
  packages/preview/cyberschool-errorteaplate/0.1.11/template/assets/Logo_cyberschool.png
  packages/preview/cyberschool-errorteaplate/0.1.11/template/assets/Logo_univ_rennes.png
  packages/preview/cyberschool-errorteaplate/0.1.11/template/main.typ
  packages/preview/cyberschool-errorteaplate/0.1.11/thumbnail.png
  packages/preview/cyberschool-errorteaplate/0.1.11/typst.toml
Labels: update

#2872 tblr:0.4.0
  packages/preview/tblr/0.4.0/LICENSE
  packages/preview/tblr/0.4.0/README.md
  packages/preview/tblr/0.4.0/examples/booktabs-2.svg
  packages/preview/tblr/0.4.0/examples/booktabs-2.typ
  packages/preview/tblr/0.4.0/examples/booktabs.svg
  packages/preview/tblr/0.4.0/examples/booktabs.typ
  packages/preview/tblr/0.4.0/examples/decimal-align.svg
  packages/preview/tblr/0.4.0/examples/decimal-align.typ
  packages/preview/tblr/0.4.0/examples/general-align.svg
  packages/preview/tblr/0.4.0/examples/general-align.typ
  packages/preview/tblr/0.4.0/examples/grant-spend.svg
  packages/preview/tblr/0.4.0/examples/grant-spend.typ
  packages/preview/tblr/0.4.0/examples/inputs.svg
  packages/preview/tblr/0.4.0/examples/inputs.typ
  packages/preview/tblr/0.4.0/examples/population-2.svg
  packages/preview/tblr/0.4.0/examples/population-2.typ
  packages/preview/tblr/0.4.0/examples/population.svg
  packages/preview/tblr/0.4.0/examples/population.typ
  packages/preview/tblr/0.4.0/tblr.typ
  packages/preview/tblr/0.4.0/typst.toml
Labels: update

#2879 mercator:0.1.1
  packages/preview/mercator/0.1.1/LICENSE
  packages/preview/mercator/0.1.1/README.md
  packages/preview/mercator/0.1.1/mercator.typ
  packages/preview/mercator/0.1.1/mercator.wasm
  packages/preview/mercator/0.1.1/typst.toml
Labels: update

#2880 haw-hamburg-bachelor-thesis:0.6.0, haw-hamburg-master-thesis:0.6.0, haw-hamburg-report:0.6.0 and haw-hamburg:0.6.0
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/LICENSE
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/README.md
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/lib.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/abbreviations.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/bibliography.bib
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/dependencies.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/glossary.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/ieeetran.csl
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/src/main.typ
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/thumbnail.png
  packages/preview/haw-hamburg-bachelor-thesis/0.6.0/typst.toml
  packages/preview/haw-hamburg-master-thesis/0.6.0/LICENSE
  packages/preview/haw-hamburg-master-thesis/0.6.0/README.md
  packages/preview/haw-hamburg-master-thesis/0.6.0/lib.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/abbreviations.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/bibliography.bib
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/dependencies.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/glossary.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/ieeetran.csl
  packages/preview/haw-hamburg-master-thesis/0.6.0/src/main.typ
  packages/preview/haw-hamburg-master-thesis/0.6.0/thumbnail.png
  packages/preview/haw-hamburg-master-thesis/0.6.0/typst.toml
  packages/preview/haw-hamburg-report/0.6.0/LICENSE
  packages/preview/haw-hamburg-report/0.6.0/README.md
  packages/preview/haw-hamburg-report/0.6.0/lib.typ
  packages/preview/haw-hamburg-report/0.6.0/src/abbreviations.typ
  packages/preview/haw-hamburg-report/0.6.0/src/bibliography.bib
  packages/preview/haw-hamburg-report/0.6.0/src/chapters/01_introduction.typ
  packages/preview/haw-hamburg-report/0.6.0/src/chapters/02_background.typ
  packages/preview/haw-hamburg-report/0.6.0/src/dependencies.typ
  packages/preview/haw-hamburg-report/0.6.0/src/glossary.typ
  packages/preview/haw-hamburg-report/0.6.0/src/ieeetran.csl
  packages/preview/haw-hamburg-report/0.6.0/src/main.typ
  packages/preview/haw-hamburg-report/0.6.0/thumbnail.png
  packages/preview/haw-hamburg-report/0.6.0/typst.toml
  packages/preview/haw-hamburg/0.6.0/LICENSE
  packages/preview/haw-hamburg/0.6.0/README.md
  packages/preview/haw-hamburg/0.6.0/assets/ieeetran.csl
  packages/preview/haw-hamburg/0.6.0/assets/logo.svg
  packages/preview/haw-hamburg/0.6.0/lib.typ
  packages/preview/haw-hamburg/0.6.0/pages/abstract.typ
  packages/preview/haw-hamburg/0.6.0/pages/cover.typ
  packages/preview/haw-hamburg/0.6.0/pages/declaration_of_independent_processing.typ
  packages/preview/haw-hamburg/0.6.0/pages/list_of_figures.typ
  packages/preview/haw-hamburg/0.6.0/pages/list_of_tables.typ
  packages/preview/haw-hamburg/0.6.0/pages/listings.typ
  packages/preview/haw-hamburg/0.6.0/pages/outline.typ
  packages/preview/haw-hamburg/0.6.0/template.pdf
  packages/preview/haw-hamburg/0.6.0/template.typ
  packages/preview/haw-hamburg/0.6.0/translations.typ
  packages/preview/haw-hamburg/0.6.0/typst.toml
Labels: update

#2892 volt-internship-ensea:0.1.0 and volt-lab-ensea:0.1.0
  packages/preview/volt-internship-ensea/0.1.0/README.md
  packages/preview/volt-internship-ensea/0.1.0/assets/logo-ENSEA.png
  packages/preview/volt-internship-ensea/0.1.0/template-internship.typ
  packages/preview/volt-internship-ensea/0.1.0/template/abstract.typ
  packages/preview/volt-internship-ensea/0.1.0/template/acknowledgements.typ
  packages/preview/volt-internship-ensea/0.1.0/template/appendices.typ
  packages/preview/volt-internship-ensea/0.1.0/template/glossary.yaml
  packages/preview/volt-internship-ensea/0.1.0/template/main-internship.typ
  packages/preview/volt-internship-ensea/0.1.0/template/media/logo-ENSEA.png
  packages/preview/volt-internship-ensea/0.1.0/template/media/logo.png
  packages/preview/volt-internship-ensea/0.1.0/template/references.bib
  packages/preview/volt-internship-ensea/0.1.0/thumbnail-internship-1.png
  packages/preview/volt-internship-ensea/0.1.0/thumbnail-internship-2.png
  packages/preview/volt-internship-ensea/0.1.0/thumbnail-internship-3.png
  packages/preview/volt-internship-ensea/0.1.0/thumbnail-internship-4.png
  packages/preview/volt-internship-ensea/0.1.0/thumbnail-internship-5.png
  packages/preview/volt-internship-ensea/0.1.0/thumbnail-internship-6.png
  packages/preview/volt-internship-ensea/0.1.0/typst.toml
  packages/preview/volt-lab-ensea/0.1.0/README.md
  packages/preview/volt-lab-ensea/0.1.0/assets/logo-ENSEA.png
  packages/preview/volt-lab-ensea/0.1.0/template-lab.typ
  packages/preview/volt-lab-ensea/0.1.0/template/main-lab.typ
  packages/preview/volt-lab-ensea/0.1.0/template/media/logo-ENSEA.png
  packages/preview/volt-lab-ensea/0.1.0/thumbnail-lab-1.png
  packages/preview/volt-lab-ensea/0.1.0/thumbnail-lab-2.png
  packages/preview/volt-lab-ensea/0.1.0/typst.toml
Labels: new

#2898 unofficial-ukim-thesis:0.1.0
  packages/preview/unofficial-ukim-thesis/0.1.0/LICENSE
  packages/preview/unofficial-ukim-thesis/0.1.0/README.md
  packages/preview/unofficial-ukim-thesis/0.1.0/logo.png
  packages/preview/unofficial-ukim-thesis/0.1.0/template/logo.png
  packages/preview/unofficial-ukim-thesis/0.1.0/template/main.typ
  packages/preview/unofficial-ukim-thesis/0.1.0/thumbnail.png
  packages/preview/unofficial-ukim-thesis/0.1.0/typst.toml
  packages/preview/unofficial-ukim-thesis/0.1.0/uthesis.typ
Labels: new

#2905 tblr:0.4.1
  packages/preview/tblr/0.4.1/LICENSE
  packages/preview/tblr/0.4.1/README.md
  packages/preview/tblr/0.4.1/examples/booktabs-2.svg
  packages/preview/tblr/0.4.1/examples/booktabs-2.typ
  packages/preview/tblr/0.4.1/examples/booktabs.svg
  packages/preview/tblr/0.4.1/examples/booktabs.typ
  packages/preview/tblr/0.4.1/examples/decimal-align.svg
  packages/preview/tblr/0.4.1/examples/decimal-align.typ
  packages/preview/tblr/0.4.1/examples/general-align.svg
  packages/preview/tblr/0.4.1/examples/general-align.typ
  packages/preview/tblr/0.4.1/examples/grant-spend.svg
  packages/preview/tblr/0.4.1/examples/grant-spend.typ
  packages/preview/tblr/0.4.1/examples/inputs.svg
  packages/preview/tblr/0.4.1/examples/inputs.typ
  packages/preview/tblr/0.4.1/examples/population-2.svg
  packages/preview/tblr/0.4.1/examples/population-2.typ
  packages/preview/tblr/0.4.1/examples/population.svg
  packages/preview/tblr/0.4.1/examples/population.typ
  packages/preview/tblr/0.4.1/tblr.typ
  packages/preview/tblr/0.4.1/typst.toml
Labels: update

#2896 cleanified-hpi-research-proposal:0.0.2
  packages/preview/cleanified-hpi-research-proposal/0.0.2/LICENSE
  packages/preview/cleanified-hpi-research-proposal/0.0.2/README.md
  packages/preview/cleanified-hpi-research-proposal/0.0.2/example/hpi_logo.svg
  packages/preview/cleanified-hpi-research-proposal/0.0.2/example/main.typ
  packages/preview/cleanified-hpi-research-proposal/0.0.2/template/hpi_logo.svg
  packages/preview/cleanified-hpi-research-proposal/0.0.2/template/lib.typ
  packages/preview/cleanified-hpi-research-proposal/0.0.2/thumbnail.png
  packages/preview/cleanified-hpi-research-proposal/0.0.2/typst.toml
Labels: update

#2910 neat-cv:0.4.0
  packages/preview/neat-cv/0.4.0/LICENSE
  packages/preview/neat-cv/0.4.0/README.md
  packages/preview/neat-cv/0.4.0/assets/cv_p1.png
  packages/preview/neat-cv/0.4.0/assets/cv_p2.png
  packages/preview/neat-cv/0.4.0/lib.typ
  packages/preview/neat-cv/0.4.0/template/cv.typ
  packages/preview/neat-cv/0.4.0/template/profile.png
  packages/preview/neat-cv/0.4.0/template/publications.yml
  packages/preview/neat-cv/0.4.0/typst.toml
Labels: update

#2883 minimal-presentation:0.7.0
  packages/preview/minimal-presentation/0.7.0/LICENSE
  packages/preview/minimal-presentation/0.7.0/README.md
  packages/preview/minimal-presentation/0.7.0/lib.typ
  packages/preview/minimal-presentation/0.7.0/template/bibliography.yaml
  packages/preview/minimal-presentation/0.7.0/template/image_1.jpg
  packages/preview/minimal-presentation/0.7.0/template/logo.svg
  packages/preview/minimal-presentation/0.7.0/template/logo_light.svg
  packages/preview/minimal-presentation/0.7.0/template/main.typ
  packages/preview/minimal-presentation/0.7.0/thumbnail.png
  packages/preview/minimal-presentation/0.7.0/typst.toml
Labels: update

#2894 payqr-swiss:0.3.0
  packages/preview/payqr-swiss/0.3.0/CH-Kreuz_7mm.svg
  packages/preview/payqr-swiss/0.3.0/CHANGELOG.md
  packages/preview/payqr-swiss/0.3.0/CONTRIBUTING.md
  packages/preview/payqr-swiss/0.3.0/LICENSE
  packages/preview/payqr-swiss/0.3.0/README.md
  packages/preview/payqr-swiss/0.3.0/examples/.gitignore
  packages/preview/payqr-swiss/0.3.0/examples/example-invoice.typ
  packages/preview/payqr-swiss/0.3.0/examples/example.png
  packages/preview/payqr-swiss/0.3.0/examples/example.typ
  packages/preview/payqr-swiss/0.3.0/payqr-swiss.typ
  packages/preview/payqr-swiss/0.3.0/typst.toml
Labels: update

#2919 eeaabb:0.1.0
  packages/preview/eeaabb/0.1.0/LICENSE.md
  packages/preview/eeaabb/0.1.0/README.md
  packages/preview/eeaabb/0.1.0/aabb.typ
  packages/preview/eeaabb/0.1.0/debug-font.typ
  packages/preview/eeaabb/0.1.0/lib.typ
  packages/preview/eeaabb/0.1.0/typst.toml
Labels: new

#2913 vartable:0.2.1
  packages/preview/vartable/0.2.1/LICENSE
  packages/preview/vartable/0.2.1/README.md
  packages/preview/vartable/0.2.1/examples/hyperbolicFunction.png
  packages/preview/vartable/0.2.1/examples/hyperbolicFuntion.typ
  packages/preview/vartable/0.2.1/examples/randomFunction.png
  packages/preview/vartable/0.2.1/examples/randomFunction.typ
  packages/preview/vartable/0.2.1/examples/trigonometricFunction.png
  packages/preview/vartable/0.2.1/examples/trigonometricFunction.typ
  packages/preview/vartable/0.2.1/tabvar.typ
  packages/preview/vartable/0.2.1/typst.toml
Labels: update

#2916 volt-internship-ensea:0.1.1
  packages/preview/volt-internship-ensea/0.1.1/README.md
  packages/preview/volt-internship-ensea/0.1.1/assets/logo-ENSEA.png
  packages/preview/volt-internship-ensea/0.1.1/template-internship.typ
  packages/preview/volt-internship-ensea/0.1.1/template/abstract.typ
  packages/preview/volt-internship-ensea/0.1.1/template/acknowledgements.typ
  packages/preview/volt-internship-ensea/0.1.1/template/appendices.typ
  packages/preview/volt-internship-ensea/0.1.1/template/glossary.yaml
  packages/preview/volt-internship-ensea/0.1.1/template/main-internship.typ
  packages/preview/volt-internship-ensea/0.1.1/template/media/logo-ENSEA.png
  packages/preview/volt-internship-ensea/0.1.1/template/media/logo.png
  packages/preview/volt-internship-ensea/0.1.1/template/references.bib
  packages/preview/volt-internship-ensea/0.1.1/thumbnail-internship-1.png
  packages/preview/volt-internship-ensea/0.1.1/thumbnail-internship-2.png
  packages/preview/volt-internship-ensea/0.1.1/thumbnail-internship-3.png
  packages/preview/volt-internship-ensea/0.1.1/thumbnail-internship-4.png
  packages/preview/volt-internship-ensea/0.1.1/thumbnail-internship-5.png
  packages/preview/volt-internship-ensea/0.1.1/thumbnail-internship-6.png
  packages/preview/volt-internship-ensea/0.1.1/typst.toml
Labels: update

#2925 zero:0.5.0
  packages/preview/zero/0.5.0/LICENSE
  packages/preview/zero/0.5.0/README.md
  packages/preview/zero/0.5.0/src/align-column.typ
  packages/preview/zero/0.5.0/src/assertations.typ
  packages/preview/zero/0.5.0/src/formatting.typ
  packages/preview/zero/0.5.0/src/impl.typ
  packages/preview/zero/0.5.0/src/num.typ
  packages/preview/zero/0.5.0/src/parsing.typ
  packages/preview/zero/0.5.0/src/rounding.typ
  packages/preview/zero/0.5.0/src/state.typ
  packages/preview/zero/0.5.0/src/units.typ
  packages/preview/zero/0.5.0/src/utility.typ
  packages/preview/zero/0.5.0/src/zero.typ
  packages/preview/zero/0.5.0/src/zi.typ
  packages/preview/zero/0.5.0/src/ztable.typ
  packages/preview/zero/0.5.0/typst.toml
Labels: update

#2926 min-manual:0.2.0
  packages/preview/min-manual/0.2.0/LICENSE
  packages/preview/min-manual/0.2.0/README.md
  packages/preview/min-manual/0.2.0/src/comments.typ
  packages/preview/min-manual/0.2.0/src/lib.typ
  packages/preview/min-manual/0.2.0/src/markdown.typ
  packages/preview/min-manual/0.2.0/src/utils.typ
  packages/preview/min-manual/0.2.0/template/assets/logo.png
  packages/preview/min-manual/0.2.0/template/manual.typ
  packages/preview/min-manual/0.2.0/thumbnail.png
  packages/preview/min-manual/0.2.0/typst.toml
Labels: update

#2930 tessera:0.1.0
  packages/preview/tessera/0.1.0/LICENSE.txt
  packages/preview/tessera/0.1.0/README.md
  packages/preview/tessera/0.1.0/assets/excalidraw/masonry-layout.excalidraw.svg
  packages/preview/tessera/0.1.0/assets/excalidraw/matrix-layout.excalidraw.svg
  packages/preview/tessera/0.1.0/src/_impl/item.typ
  packages/preview/tessera/0.1.0/src/_impl/masonry-layout-helper.wasm
  packages/preview/tessera/0.1.0/src/_impl/masonry-layout-helper_wasm.typ
  packages/preview/tessera/0.1.0/src/_impl/masonry.typ
  packages/preview/tessera/0.1.0/src/_impl/matrix.typ
  packages/preview/tessera/0.1.0/src/_impl/transform.typ
  packages/preview/tessera/0.1.0/src/_impl/typing.typ
  packages/preview/tessera/0.1.0/src/_impl/utils.typ
  packages/preview/tessera/0.1.0/src/lib.typ
  packages/preview/tessera/0.1.0/src/transform.typ
  packages/preview/tessera/0.1.0/typst.toml
Labels: new

#2899 qec-thrust:0.1.1
  packages/preview/qec-thrust/0.1.1/LICENSE
  packages/preview/qec-thrust/0.1.1/README.md
  packages/preview/qec-thrust/0.1.1/examples/steane.png
  packages/preview/qec-thrust/0.1.1/examples/steane.typ
  packages/preview/qec-thrust/0.1.1/examples/surface.png
  packages/preview/qec-thrust/0.1.1/examples/surface.typ
  packages/preview/qec-thrust/0.1.1/examples/toric1.png
  packages/preview/qec-thrust/0.1.1/examples/toric1.typ
  packages/preview/qec-thrust/0.1.1/examples/toric2.png
  packages/preview/qec-thrust/0.1.1/examples/toric2.typ
  packages/preview/qec-thrust/0.1.1/lib.typ
  packages/preview/qec-thrust/0.1.1/typst.toml
Labels: update

#2938 rexllent:0.3.4
  packages/preview/rexllent/0.3.4/LICENSE
  packages/preview/rexllent/0.3.4/README.md
  packages/preview/rexllent/0.3.4/assets/example1.png
  packages/preview/rexllent/0.3.4/assets/example2.png
  packages/preview/rexllent/0.3.4/assets/example3.png
  packages/preview/rexllent/0.3.4/assets/example4.png
  packages/preview/rexllent/0.3.4/assets/example5.png
  packages/preview/rexllent/0.3.4/assets/example6.png
  packages/preview/rexllent/0.3.4/assets/example7.png
  packages/preview/rexllent/0.3.4/assets/excel.png
  packages/preview/rexllent/0.3.4/assets/three-line-table.png
  packages/preview/rexllent/0.3.4/assets/typst_example1.png
  packages/preview/rexllent/0.3.4/assets/typst_example2.png
  packages/preview/rexllent/0.3.4/assets/typst_example3.png
  packages/preview/rexllent/0.3.4/src/lib.typ
  packages/preview/rexllent/0.3.4/src/mod.typ
  packages/preview/rexllent/0.3.4/src/numfmt.typ
  packages/preview/rexllent/0.3.4/src/numfmt.wasm
  packages/preview/rexllent/0.3.4/src/rexllent.wasm
  packages/preview/rexllent/0.3.4/typst.toml
Labels: update

#2935 intextual:0.1.0
  packages/preview/intextual/0.1.0/LICENSE
  packages/preview/intextual/0.1.0/README.md
  packages/preview/intextual/0.1.0/example.pdf
  packages/preview/intextual/0.1.0/example.typ
  packages/preview/intextual/0.1.0/imgs/example.png
  packages/preview/intextual/0.1.0/intextual.typ
  packages/preview/intextual/0.1.0/lib.typ
  packages/preview/intextual/0.1.0/typst.toml
Labels: new

#2940 stash:0.1.0
  packages/preview/stash/0.1.0/CHANGELOG.md
  packages/preview/stash/0.1.0/LICENSE
  packages/preview/stash/0.1.0/README.md
  packages/preview/stash/0.1.0/src/lib.typ
  packages/preview/stash/0.1.0/thumbnail-dark.svg
  packages/preview/stash/0.1.0/thumbnail-light.svg
  packages/preview/stash/0.1.0/typst.toml
Labels: new

#2957 Bundler flag for skipping license validation
  bundler/src/main.rs
Labels: meta

#2944 yi:0.1.0
  packages/preview/yi/0.1.0/LICENSE
  packages/preview/yi/0.1.0/README.md
  packages/preview/yi/0.1.0/lib.typ
  packages/preview/yi/0.1.0/typst.toml
Labels: new

#2945 classic-aau-report:0.3.1
  packages/preview/classic-aau-report/0.3.1/AAUgraphics/aau_logo_circle_en.svg
  packages/preview/classic-aau-report/0.3.1/AAUgraphics/aau_logo_da.svg
  packages/preview/classic-aau-report/0.3.1/AAUgraphics/aau_logo_en.svg
  packages/preview/classic-aau-report/0.3.1/AAUgraphics/aau_waves.svg
  packages/preview/classic-aau-report/0.3.1/LICENSE
  packages/preview/classic-aau-report/0.3.1/README.md
  packages/preview/classic-aau-report/0.3.1/lib.typ
  packages/preview/classic-aau-report/0.3.1/src/main.typ
  packages/preview/classic-aau-report/0.3.1/src/utils.typ
  packages/preview/classic-aau-report/0.3.1/template/appendices/scripting.typ
  packages/preview/classic-aau-report/0.3.1/template/chapters/conclusion.typ
  packages/preview/classic-aau-report/0.3.1/template/chapters/custom-macros.typ
  packages/preview/classic-aau-report/0.3.1/template/chapters/introduction.typ
  packages/preview/classic-aau-report/0.3.1/template/chapters/problem-analysis.typ
  packages/preview/classic-aau-report/0.3.1/template/figures/.gitkeep
  packages/preview/classic-aau-report/0.3.1/template/main.typ
  packages/preview/classic-aau-report/0.3.1/template/references.bib
  packages/preview/classic-aau-report/0.3.1/template/setup/macros.typ
  packages/preview/classic-aau-report/0.3.1/template/setup/todo.typ
  packages/preview/classic-aau-report/0.3.1/thumbnail.png
  packages/preview/classic-aau-report/0.3.1/typst.toml
Labels: update

#2950 scholarly-tauthesis:0.16.3
  packages/preview/scholarly-tauthesis/0.16.3/.gitattributes
  packages/preview/scholarly-tauthesis/0.16.3/.gitignore
  packages/preview/scholarly-tauthesis/0.16.3/LICENSE
  packages/preview/scholarly-tauthesis/0.16.3/README.md
  packages/preview/scholarly-tauthesis/0.16.3/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.16.3/template/brakets.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/code/README.md
  packages/preview/scholarly-tauthesis/0.16.3/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.16.3/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/B.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/README.md
  packages/preview/scholarly-tauthesis/0.16.3/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/images/README.md
  packages/preview/scholarly-tauthesis/0.16.3/template/images/tau-logo-eng.svg
  packages/preview/scholarly-tauthesis/0.16.3/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.16.3/template/images/tau-logo-fin.svg
  packages/preview/scholarly-tauthesis/0.16.3/template/main.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.16.3/template/publications/publications.yaml
  packages/preview/scholarly-tauthesis/0.16.3/thumbnail.png
  packages/preview/scholarly-tauthesis/0.16.3/typst.toml
  packages/preview/scholarly-tauthesis/0.16.3/utils/packageLocally.py
Labels: update

#2959 herodot:0.2.0
  packages/preview/herodot/0.2.0/LICENSE
  packages/preview/herodot/0.2.0/README.md
  packages/preview/herodot/0.2.0/examples/example-1.png
  packages/preview/herodot/0.2.0/examples/example-2.png
  packages/preview/herodot/0.2.0/examples/example-3.png
  packages/preview/herodot/0.2.0/examples/example.pdf
  packages/preview/herodot/0.2.0/examples/example.typ
  packages/preview/herodot/0.2.0/lib.typ
  packages/preview/herodot/0.2.0/src/functions.typ
  packages/preview/herodot/0.2.0/src/primitives.typ
  packages/preview/herodot/0.2.0/typst.toml
Labels: update

#2952 h-graph:0.1.0
  packages/preview/h-graph/0.1.0/README.md
  packages/preview/h-graph/0.1.0/docs/README-cn.md
  packages/preview/h-graph/0.1.0/docs/img/A-B.png
  packages/preview/h-graph/0.1.0/docs/img/demo1.png
  packages/preview/h-graph/0.1.0/docs/img/demo2.png
  packages/preview/h-graph/0.1.0/docs/img/demo3.png
  packages/preview/h-graph/0.1.0/docs/img/demo4.png
  packages/preview/h-graph/0.1.0/docs/img/demo5.png
  packages/preview/h-graph/0.1.0/docs/img/demo6.png
  packages/preview/h-graph/0.1.0/src/lib.typ
  packages/preview/h-graph/0.1.0/src/parser.typ
  packages/preview/h-graph/0.1.0/src/render.typ
  packages/preview/h-graph/0.1.0/typst.toml
Labels: new

#2962 bei-report:0.1.1
  packages/preview/bei-report/0.1.1/CHANGELOG.md
  packages/preview/bei-report/0.1.1/LICENSE
  packages/preview/bei-report/0.1.1/README.md
  packages/preview/bei-report/0.1.1/copyright
  packages/preview/bei-report/0.1.1/src/lib.typ
  packages/preview/bei-report/0.1.1/template/.gitignore
  packages/preview/bei-report/0.1.1/template/get_ensimag_logo
  packages/preview/bei-report/0.1.1/template/logos/ensimag_logo.png.DIGEST
  packages/preview/bei-report/0.1.1/template/main.typ
  packages/preview/bei-report/0.1.1/template/refs.bib
  packages/preview/bei-report/0.1.1/thumbnail-dark.svg
  packages/preview/bei-report/0.1.1/thumbnail-light.svg
  packages/preview/bei-report/0.1.1/thumbnail.png
  packages/preview/bei-report/0.1.1/typst.toml
Labels: update

#2965 algorithmic:1.0.4
  packages/preview/algorithmic/1.0.4/LICENSE
  packages/preview/algorithmic/1.0.4/NEWS.md
  packages/preview/algorithmic/1.0.4/README.md
  packages/preview/algorithmic/1.0.4/algorithmic.typ
  packages/preview/algorithmic/1.0.4/typst.toml
Labels: update

#2969 tiefletter:0.1.2
  packages/preview/tiefletter/0.1.2/LICENSE
  packages/preview/tiefletter/0.1.2/README.md
  packages/preview/tiefletter/0.1.2/lib.typ
  packages/preview/tiefletter/0.1.2/template/header.svg
  packages/preview/tiefletter/0.1.2/template/main.typ
  packages/preview/tiefletter/0.1.2/thumbnail.png
  packages/preview/tiefletter/0.1.2/typst.toml
Labels: update

#2964 linkify:0.1.1
  packages/preview/linkify/0.1.1/LICENSE.txt
  packages/preview/linkify/0.1.1/README.md
  packages/preview/linkify/0.1.1/src/_impl/bili.typ
  packages/preview/linkify/0.1.1/src/_impl/bili.wasm
  packages/preview/linkify/0.1.1/src/_impl/bili_typ.typ
  packages/preview/linkify/0.1.1/src/_impl/display.typ
  packages/preview/linkify/0.1.1/src/_impl/init.typ
  packages/preview/linkify/0.1.1/src/_impl/url.typ
  packages/preview/linkify/0.1.1/src/_impl/utils.typ
  packages/preview/linkify/0.1.1/src/bili.typ
  packages/preview/linkify/0.1.1/src/display.typ
  packages/preview/linkify/0.1.1/src/lib.typ
  packages/preview/linkify/0.1.1/src/url.typ
  packages/preview/linkify/0.1.1/typst.toml
Labels: update

#2963 solo-lu-df:0.1.0
  packages/preview/solo-lu-df/0.1.0/LICENSE
  packages/preview/solo-lu-df/0.1.0/README.md
  packages/preview/solo-lu-df/0.1.0/src/lib.typ
  packages/preview/solo-lu-df/0.1.0/src/utils.typ
  packages/preview/solo-lu-df/0.1.0/template/bibliography.yml
  packages/preview/solo-lu-df/0.1.0/template/main.typ
  packages/preview/solo-lu-df/0.1.0/thumbnail.png
  packages/preview/solo-lu-df/0.1.0/typst.toml
Labels: new
