Repository typst/packages, pull requests merged in 2025-06, with the labels that each got.

#2468 modern-uit-thesis:0.1.6
  packages/preview/modern-uit-thesis/0.1.6/LICENSE
  packages/preview/modern-uit-thesis/0.1.6/README.md
  packages/preview/modern-uit-thesis/0.1.6/assets/backpage.svg
  packages/preview/modern-uit-thesis/0.1.6/assets/frontpage_full.svg
  packages/preview/modern-uit-thesis/0.1.6/assets/logo.svg
  packages/preview/modern-uit-thesis/0.1.6/flake.lock
  packages/preview/modern-uit-thesis/0.1.6/flake.nix
  packages/preview/modern-uit-thesis/0.1.6/garnix.yaml
  packages/preview/modern-uit-thesis/0.1.6/lib.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/abbreviations.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/abstract.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/acknowledgements.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/backpage.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/epigraph.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/frontpage.typ
  packages/preview/modern-uit-thesis/0.1.6/modules/supervisors.typ
  packages/preview/modern-uit-thesis/0.1.6/nix/packages/default.nix
  packages/preview/modern-uit-thesis/0.1.6/nix/packages/glossarium.nix
  packages/preview/modern-uit-thesis/0.1.6/nix/packages/thesis.nix
  packages/preview/modern-uit-thesis/0.1.6/nix/packages/xcharter.nix
  packages/preview/modern-uit-thesis/0.1.6/template/chapters/appendix.typ
  packages/preview/modern-uit-thesis/0.1.6/template/chapters/basic-usage.typ
  packages/preview/modern-uit-thesis/0.1.6/template/chapters/figures.typ
  packages/preview/modern-uit-thesis/0.1.6/template/chapters/introduction.typ
  packages/preview/modern-uit-thesis/0.1.6/template/chapters/typst-basics.typ
  packages/preview/modern-uit-thesis/0.1.6/template/chapters/utilities.typ
  packages/preview/modern-uit-thesis/0.1.6/template/code-snippets/Program.fsx
  packages/preview/modern-uit-thesis/0.1.6/template/figures/dining_philosophers.png
  packages/preview/modern-uit-thesis/0.1.6/template/figures/philosophers.png
  packages/preview/modern-uit-thesis/0.1.6/template/figures/plot_serial.svg
  packages/preview/modern-uit-thesis/0.1.6/template/figures/table.csv
  packages/preview/modern-uit-thesis/0.1.6/template/figures/uit_aurora.jpg
  packages/preview/modern-uit-thesis/0.1.6/template/refs.bib
  packages/preview/modern-uit-thesis/0.1.6/template/thesis.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/caption.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/feedback.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/form.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/global.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/subfigure.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/symbols.typ
  packages/preview/modern-uit-thesis/0.1.6/template/utils/todo.typ
  packages/preview/modern-uit-thesis/0.1.6/thumbnail.png
  packages/preview/modern-uit-thesis/0.1.6/typst.toml
Labels: update

#2476 touying-unistra-pristine:1.4.0
  packages/preview/touying-unistra-pristine/1.4.0/CHANGELOG.md
  packages/preview/touying-unistra-pristine/1.4.0/LICENSE
  packages/preview/touying-unistra-pristine/1.4.0/README.md
  packages/preview/touying-unistra-pristine/1.4.0/assets/thumbnail.webp
  packages/preview/touying-unistra-pristine/1.4.0/assets/unistra.svg
  packages/preview/touying-unistra-pristine/1.4.0/assets/unistrafooter.svg
  packages/preview/touying-unistra-pristine/1.4.0/src/citations.typ
  packages/preview/touying-unistra-pristine/1.4.0/src/colors.typ
  packages/preview/touying-unistra-pristine/1.4.0/src/icons.typ
  packages/preview/touying-unistra-pristine/1.4.0/src/lib.typ
  packages/preview/touying-unistra-pristine/1.4.0/src/unistra.typ
  packages/preview/touying-unistra-pristine/1.4.0/src/utils.typ
  packages/preview/touying-unistra-pristine/1.4.0/template/template.typ
  packages/preview/touying-unistra-pristine/1.4.0/template/unistra.svg
  packages/preview/touying-unistra-pristine/1.4.0/template/unistrafooter.svg
  packages/preview/touying-unistra-pristine/1.4.0/typst.toml
Labels: update

#2473 cmarker:0.1.6
  packages/preview/cmarker/0.1.6/LICENSE
  packages/preview/cmarker/0.1.6/README.md
  packages/preview/cmarker/0.1.6/examples/hexagons.png
  packages/preview/cmarker/0.1.6/examples/simple.png
  packages/preview/cmarker/0.1.6/lib.typ
  packages/preview/cmarker/0.1.6/plugin.wasm
  packages/preview/cmarker/0.1.6/typst.toml
Labels: update

#2475 iconic-salmon-fa:1.1.0
  packages/preview/iconic-salmon-fa/1.1.0/LICENSE
  packages/preview/iconic-salmon-fa/1.1.0/README.md
  packages/preview/iconic-salmon-fa/1.1.0/examples/examples.typ
  packages/preview/iconic-salmon-fa/1.1.0/examples/minimal_example.typ
  packages/preview/iconic-salmon-fa/1.1.0/iconic-salmon-fa.typ
  packages/preview/iconic-salmon-fa/1.1.0/typst.toml
Labels: update

#2470 rowmantic:0.1.0
  packages/preview/rowmantic/0.1.0/CHANGELOG.md
  packages/preview/rowmantic/0.1.0/LICENSE-EUPL-1.2.txt
  packages/preview/rowmantic/0.1.0/README.md
  packages/preview/rowmantic/0.1.0/docs/figures/readmepicture1-dark.svg
  packages/preview/rowmantic/0.1.0/docs/figures/readmepicture1.svg
  packages/preview/rowmantic/0.1.0/docs/figures/readmepicture2-dark.svg
  packages/preview/rowmantic/0.1.0/docs/figures/readmepicture2.svg
  packages/preview/rowmantic/0.1.0/src/lib.typ
  packages/preview/rowmantic/0.1.0/src/rowtable.typ
  packages/preview/rowmantic/0.1.0/typst.toml
Labels: new

#2477 flow:0.3.2
  packages/preview/flow/0.3.2/CHANGELOG.md
  packages/preview/flow/0.3.2/LICENSE.md
  packages/preview/flow/0.3.2/README.md
  packages/preview/flow/0.3.2/asset/data.toml
  packages/preview/flow/0.3.2/asset/halcyon.tmTheme
  packages/preview/flow/0.3.2/src/asset.typ
  packages/preview/flow/0.3.2/src/callout.typ
  packages/preview/flow/0.3.2/src/cfg.typ
  packages/preview/flow/0.3.2/src/checkbox.typ
  packages/preview/flow/0.3.2/src/gfx/draw.typ
  packages/preview/flow/0.3.2/src/gfx/maybe-stub.typ
  packages/preview/flow/0.3.2/src/gfx/mod.typ
  packages/preview/flow/0.3.2/src/gfx/render/mod.typ
  packages/preview/flow/0.3.2/src/gfx/render/segment.typ
  packages/preview/flow/0.3.2/src/gfx/stub.typ
  packages/preview/flow/0.3.2/src/gfx/stub/draw.typ
  packages/preview/flow/0.3.2/src/gfx/util.typ
  packages/preview/flow/0.3.2/src/hacks.typ
  packages/preview/flow/0.3.2/src/info.typ
  packages/preview/flow/0.3.2/src/keywords.typ
  packages/preview/flow/0.3.2/src/lib.typ
  packages/preview/flow/0.3.2/src/palette.typ
  packages/preview/flow/0.3.2/src/template.typ
  packages/preview/flow/0.3.2/src/tyck.typ
  packages/preview/flow/0.3.2/src/util/mod.typ
  packages/preview/flow/0.3.2/src/util/preset/arrow.typ
  packages/preview/flow/0.3.2/src/util/preset/chem.typ
  packages/preview/flow/0.3.2/src/util/preset/math.typ
  packages/preview/flow/0.3.2/src/util/preset/mod.typ
  packages/preview/flow/0.3.2/src/util/preset/ops.typ
  packages/preview/flow/0.3.2/src/util/preset/quantum.typ
  packages/preview/flow/0.3.2/src/util/preset/sew.typ
  packages/preview/flow/0.3.2/src/util/small.typ
  packages/preview/flow/0.3.2/src/xlink.typ
  packages/preview/flow/0.3.2/template/main.typ
  packages/preview/flow/0.3.2/thumbnail/page-1.png
  packages/preview/flow/0.3.2/typst.toml
  packages/preview/flow/0.3.2/util/common
  packages/preview/flow/0.3.2/util/flow
  packages/preview/flow/0.3.2/util/flow-export
  packages/preview/flow/0.3.2/util/flow-query
Labels: update

#2466 unofficial-tyut-thesis:0.1.0
  packages/preview/unofficial-tyut-thesis/0.1.0/LICENSE
  packages/preview/unofficial-tyut-thesis/0.1.0/README.md
  packages/preview/unofficial-tyut-thesis/0.1.0/assets/tyut-logo.jpg
  packages/preview/unofficial-tyut-thesis/0.1.0/layouts/appendix.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/layouts/doc.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/layouts/glossary.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/layouts/mainmatter.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/layouts/preface.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/lib.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/pages/abstract-en.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/pages/abstract.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/pages/acknowledgement.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/pages/cover.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/pages/decl.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/pages/outline-page.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/template/imgs/author-signature.jpg
  packages/preview/unofficial-tyut-thesis/0.1.0/template/references.bib
  packages/preview/unofficial-tyut-thesis/0.1.0/template/thesis.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/thumbnail.png
  packages/preview/unofficial-tyut-thesis/0.1.0/typst.toml
  packages/preview/unofficial-tyut-thesis/0.1.0/utils/bilingual-bibliography.typ
  packages/preview/unofficial-tyut-thesis/0.1.0/utils/justify-text.typ
Labels: new

#2479 eggs:0.1.0
  packages/preview/eggs/0.1.0/LICENSE.txt
  packages/preview/eggs/0.1.0/README.md
  packages/preview/eggs/0.1.0/documentation.typ
  packages/preview/eggs/0.1.0/eggs.typ
  packages/preview/eggs/0.1.0/src/abbreviations.typ
  packages/preview/eggs/0.1.0/src/config.typ
  packages/preview/eggs/0.1.0/src/ex-label.typ
  packages/preview/eggs/0.1.0/src/ex-ref.typ
  packages/preview/eggs/0.1.0/src/examples.typ
  packages/preview/eggs/0.1.0/src/gloss.typ
  packages/preview/eggs/0.1.0/src/judge.typ
  packages/preview/eggs/0.1.0/typst.toml
Labels: new

#2482 qooklet:0.6.0
  packages/preview/qooklet/0.6.0/LICENSE
  packages/preview/qooklet/0.6.0/README.md
  packages/preview/qooklet/0.6.0/src/chapters.typ
  packages/preview/qooklet/0.6.0/src/common.typ
  packages/preview/qooklet/0.6.0/src/config/info.toml
  packages/preview/qooklet/0.6.0/src/config/names.toml
  packages/preview/qooklet/0.6.0/src/config/styles.toml
  packages/preview/qooklet/0.6.0/src/contents.typ
  packages/preview/qooklet/0.6.0/src/cover.typ
  packages/preview/qooklet/0.6.0/src/dependencies.typ
  packages/preview/qooklet/0.6.0/src/front-matters.typ
  packages/preview/qooklet/0.6.0/src/lib.typ
  packages/preview/qooklet/0.6.0/src/referable.typ
  packages/preview/qooklet/0.6.0/src/utils.typ
  packages/preview/qooklet/0.6.0/template/main.typ
  packages/preview/qooklet/0.6.0/thumbnail.png
  packages/preview/qooklet/0.6.0/typst.toml
Labels: update

#2452 simple-tubs-letter:0.1.2
  packages/preview/simple-tubs-letter/0.1.2/.gitignore
  packages/preview/simple-tubs-letter/0.1.2/COPYING
  packages/preview/simple-tubs-letter/0.1.2/LICENCES/GPL-3.0
  packages/preview/simple-tubs-letter/0.1.2/LICENCES/MIT
  packages/preview/simple-tubs-letter/0.1.2/README.md
  packages/preview/simple-tubs-letter/0.1.2/template.typ
  packages/preview/simple-tubs-letter/0.1.2/template/.gitignore
  packages/preview/simple-tubs-letter/0.1.2/template/assets/figure/tubs/institute_logo.jpg
  packages/preview/simple-tubs-letter/0.1.2/template/assets/figure/tubs/tubs_logo.svg
  packages/preview/simple-tubs-letter/0.1.2/template/letter.typ
  packages/preview/simple-tubs-letter/0.1.2/template/metadata.typ
  packages/preview/simple-tubs-letter/0.1.2/thumbnail.webp
  packages/preview/simple-tubs-letter/0.1.2/typst.toml
Labels: update

#2486 scholarly-tauthesis:0.15.2
  packages/preview/scholarly-tauthesis/0.15.2/.gitattributes
  packages/preview/scholarly-tauthesis/0.15.2/.gitignore
  packages/preview/scholarly-tauthesis/0.15.2/LICENSE
  packages/preview/scholarly-tauthesis/0.15.2/README.md
  packages/preview/scholarly-tauthesis/0.15.2/tauthesis.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/bibliography.bib
  packages/preview/scholarly-tauthesis/0.15.2/template/brakets.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/code/README.md
  packages/preview/scholarly-tauthesis/0.15.2/template/code/square.jl
  packages/preview/scholarly-tauthesis/0.15.2/template/content/01.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/02.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/03.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/04.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/A.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/B.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/README.md
  packages/preview/scholarly-tauthesis/0.15.2/template/content/abstract.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/glossary.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/preface.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/tekoalyn-kaytto.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/tiivistelmä.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/content/use-of-ai.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/images/README.md
  packages/preview/scholarly-tauthesis/0.15.2/template/images/tau-logo-eng.svg
  packages/preview/scholarly-tauthesis/0.15.2/template/images/tau-logo-fin-eng.svg
  packages/preview/scholarly-tauthesis/0.15.2/template/images/tau-logo-fin.svg
  packages/preview/scholarly-tauthesis/0.15.2/template/main.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/preamble.typ
  packages/preview/scholarly-tauthesis/0.15.2/template/publications/publications.yaml
  packages/preview/scholarly-tauthesis/0.15.2/thumbnail.png
  packages/preview/scholarly-tauthesis/0.15.2/typst.toml
  packages/preview/scholarly-tauthesis/0.15.2/utils/packageLocally.py
Labels: update

#2487 cetramed-polylux:0.1.0
  packages/preview/cetramed-polylux/0.1.0/LICENSE
  packages/preview/cetramed-polylux/0.1.0/README.md
  packages/preview/cetramed-polylux/0.1.0/img/header-decoration.svg
  packages/preview/cetramed-polylux/0.1.0/img/title-decoration.svg
  packages/preview/cetramed-polylux/0.1.0/lib.typ
  packages/preview/cetramed-polylux/0.1.0/template/.gitignore
  packages/preview/cetramed-polylux/0.1.0/template/slides.typ
  packages/preview/cetramed-polylux/0.1.0/thumbnail.png
  packages/preview/cetramed-polylux/0.1.0/typst.toml
Labels: new

#2491 impressive-impression:0.1.0
  packages/preview/impressive-impression/0.1.0/LICENSE
  packages/preview/impressive-impression/0.1.0/README.md
  packages/preview/impressive-impression/0.1.0/src/cv.typ
  packages/preview/impressive-impression/0.1.0/src/elements.typ
  packages/preview/impressive-impression/0.1.0/src/lib.typ
  packages/preview/impressive-impression/0.1.0/src/theme.typ
  packages/preview/impressive-impression/0.1.0/src/themes/forty-seconds.typ
  packages/preview/impressive-impression/0.1.0/src/utils.typ
  packages/preview/impressive-impression/0.1.0/template/assets/flags/fr.svg
  packages/preview/impressive-impression/0.1.0/template/assets/flags/gb.svg
  packages/preview/impressive-impression/0.1.0/template/assets/flags/gr.svg
  packages/preview/impressive-impression/0.1.0/template/assets/profile.png
  packages/preview/impressive-impression/0.1.0/template/assets/signature.svg
  packages/preview/impressive-impression/0.1.0/template/cv.typ
  packages/preview/impressive-impression/0.1.0/template/theme.typ
  packages/preview/impressive-impression/0.1.0/template/utils.typ
  packages/preview/impressive-impression/0.1.0/thumbnail.png
  packages/preview/impressive-impression/0.1.0/typst.toml
Labels: new

#2492 bob-draw:0.1.1
  packages/preview/bob-draw/0.1.1/LICENSE
  packages/preview/bob-draw/0.1.1/README.md
  packages/preview/bob-draw/0.1.1/bob_typ.wasm
  packages/preview/bob-draw/0.1.1/examples/basic-example.svg
  packages/preview/bob-draw/0.1.1/examples/basic-example.typ
  packages/preview/bob-draw/0.1.1/examples/example.typ
  packages/preview/bob-draw/0.1.1/lib.typ
  packages/preview/bob-draw/0.1.1/typst.toml
Labels: update

#2495 epsilon:0.1.0
  packages/preview/epsilon/0.1.0/LICENSE
  packages/preview/epsilon/0.1.0/README.md
  packages/preview/epsilon/0.1.0/src/lib.typ
  packages/preview/epsilon/0.1.0/typst.toml
Labels: new

#2497 oxifmt:1.0.0
  packages/preview/oxifmt/1.0.0/LICENSE
  packages/preview/oxifmt/1.0.0/LICENSE-APACHE
  packages/preview/oxifmt/1.0.0/LICENSE-MIT
  packages/preview/oxifmt/1.0.0/README.md
  packages/preview/oxifmt/1.0.0/lib.typ
  packages/preview/oxifmt/1.0.0/oxifmt.typ
  packages/preview/oxifmt/1.0.0/typst.toml
Labels: update

#2498 shuosc-shu-bachelor-thesis:0.3.1
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/LICENSE
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/LICENSE-MIT
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/README.md
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/assets/citation-style.csl
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/assets/cover.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/assets/under-cover.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/layouts/appendix.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/layouts/doc.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/layouts/mainmatter.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/lib.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/abstract.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/acknowledgement.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/bib.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/conclusion.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/cover.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/declare.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/outline.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/pages/under-cover.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/style/distr.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/style/enums.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/style/figures.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/style/font.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/style/heading.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/style/uline.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/data/heros.csv
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/data/nyuv2.csv
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/figures/cetz.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/figures/energy-distribution.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/figures/fletcher.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/figures/sign.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/ref.bib
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/template/thesis.typ
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/thumbnail.png
  packages/preview/shuosc-shu-bachelor-thesis/0.3.1/typst.toml
Labels: update

#2496 amlos:0.2.1 and uwnibook-color:0.1.0
  packages/preview/amlos/0.2.1/typst.toml
  packages/preview/uwnibook-color/0.1.0/.gitignore
  packages/preview/uwnibook-color/0.1.0/.gitmodules
  packages/preview/uwnibook-color/0.1.0/LICENSE
  packages/preview/uwnibook-color/0.1.0/README.md
  packages/preview/uwnibook-color/0.1.0/boilerplate/chapters/1_intro.typ
  packages/preview/uwnibook-color/0.1.0/boilerplate/chapters/appendix.typ
  packages/preview/uwnibook-color/0.1.0/boilerplate/chapters/preamble.typ
  packages/preview/uwnibook-color/0.1.0/boilerplate/citation.bib
  packages/preview/uwnibook-color/0.1.0/boilerplate/header_imgs/img1.jpg
  packages/preview/uwnibook-color/0.1.0/boilerplate/header_imgs/imgs.typ
  packages/preview/uwnibook-color/0.1.0/boilerplate/main.typ
  packages/preview/uwnibook-color/0.1.0/boilerplate/uwnibook.typ
  packages/preview/uwnibook-color/0.1.0/documentation/appendices/data.typ
  packages/preview/uwnibook-color/0.1.0/documentation/appendices/proof.typ
  packages/preview/uwnibook-color/0.1.0/documentation/chapters/0_abs.typ
  packages/preview/uwnibook-color/0.1.0/documentation/chapters/1_intro.typ
  packages/preview/uwnibook-color/0.1.0/documentation/chapters/assets/Augustin-Louis_Cauchy_1901.jpg
  packages/preview/uwnibook-color/0.1.0/documentation/chapters/usage.typ
  packages/preview/uwnibook-color/0.1.0/documentation/citation.bib
  packages/preview/uwnibook-color/0.1.0/documentation/defs.typ
  packages/preview/uwnibook-color/0.1.0/documentation/header_imgs/img1.jpg
  packages/preview/uwnibook-color/0.1.0/documentation/header_imgs/imgs.typ
  packages/preview/uwnibook-color/0.1.0/documentation/main.typ
  packages/preview/uwnibook-color/0.1.0/documentation/misc/ref.typ
  packages/preview/uwnibook-color/0.1.0/documentation/my-preset.typ
  packages/preview/uwnibook-color/0.1.0/documentation/packages.typ
  packages/preview/uwnibook-color/0.1.0/lib.typ
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/.github/FUNDING.yml
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/.gitignore
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/README.md
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/UNLICENSE
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/lib.typ
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/main.typ
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/preview.svg
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/tidy-style.typ
  packages/preview/uwnibook-color/0.1.0/packages/typst-marginalia/typst.toml
  packages/preview/uwnibook-color/0.1.0/src/components.typ
  packages/preview/uwnibook-color/0.1.0/src/coverpage.typ
  packages/preview/uwnibook-color/0.1.0/src/environments.typ
  packages/preview/uwnibook-color/0.1.0/src/index.typ
  packages/preview/uwnibook-color/0.1.0/src/packages/marginalia.typ
  packages/preview/uwnibook-color/0.1.0/src/presets/config-en.typ
  packages/preview/uwnibook-color/0.1.0/src/presets/config-zh.typ
  packages/preview/uwnibook-color/0.1.0/src/template.typ
  packages/preview/uwnibook-color/0.1.0/src/titlepage.typ
  packages/preview/uwnibook-color/0.1.0/thumbnail.png
  packages/preview/uwnibook-color/0.1.0/typst.toml
Labels: new, update

#2505 diatypst:0.6.0
  packages/preview/diatypst/0.6.0/LICENSE
  packages/preview/diatypst/0.6.0/README.md
  packages/preview/diatypst/0.6.0/example/diaprojektor.jpg
  packages/preview/diatypst/0.6.0/example/diatype.jpg
  packages/preview/diatypst/0.6.0/example/example.pdf
  packages/preview/diatypst/0.6.0/example/example.typ
  packages/preview/diatypst/0.6.0/example/example_full.pdf
  packages/preview/diatypst/0.6.0/lib.typ
  packages/preview/diatypst/0.6.0/screenshots/Example-Section.png
  packages/preview/diatypst/0.6.0/screenshots/Example-Slide.png
  packages/preview/diatypst/0.6.0/screenshots/Example-TOC.png
  packages/preview/diatypst/0.6.0/screenshots/Example-Title.png
  packages/preview/diatypst/0.6.0/screenshots/Full-Example-Slide.png
  packages/preview/diatypst/0.6.0/screenshots/Full-Example-TOC.png
  packages/preview/diatypst/0.6.0/screenshots/Thumbnail.png
  packages/preview/diatypst/0.6.0/template/main.typ
  packages/preview/diatypst/0.6.0/typst.toml
Labels: update

#2504 oxifmt:1.0.0
  packages/preview/oxifmt/1.0.0/README.md
Labels: update

#2506 vienna-tech:1.1.0
  packages/preview/vienna-tech/1.1.0/CHANGELOG.md
  packages/preview/vienna-tech/1.1.0/LICENSE
  packages/preview/vienna-tech/1.1.0/README.md
  packages/preview/vienna-tech/1.1.0/src/constructors.typ
  packages/preview/vienna-tech/1.1.0/src/lib.typ
  packages/preview/vienna-tech/1.1.0/src/styles.typ
  packages/preview/vienna-tech/1.1.0/src/utils.typ
  packages/preview/vienna-tech/1.1.0/template/abstract.typ
  packages/preview/vienna-tech/1.1.0/template/appendix.typ
  packages/preview/vienna-tech/1.1.0/template/assets/refs.bib
  packages/preview/vienna-tech/1.1.0/template/main.typ
  packages/preview/vienna-tech/1.1.0/template/sections.typ
  packages/preview/vienna-tech/1.1.0/thumbnail.png
  packages/preview/vienna-tech/1.1.0/typst.toml
Labels: update

#2512 tfguf:0.0.3
  packages/preview/tfguf/0.0.3/LICENSE
  packages/preview/tfguf/0.0.3/README.md
  packages/preview/tfguf/0.0.3/portada.png
  packages/preview/tfguf/0.0.3/template/bibliografia.bib
  packages/preview/tfguf/0.0.3/template/tfg.typ
  packages/preview/tfguf/0.0.3/template/unir logo.svg
  packages/preview/tfguf/0.0.3/typst.toml
  packages/preview/tfguf/0.0.3/unirfisica.typ
Labels: update

#2509 cjk-unbreak:0.1.1
  packages/preview/cjk-unbreak/0.1.1/LICENSE
  packages/preview/cjk-unbreak/0.1.1/README.md
  packages/preview/cjk-unbreak/0.1.1/lib.typ
  packages/preview/cjk-unbreak/0.1.1/remove-cjk-break-space.typ
  packages/preview/cjk-unbreak/0.1.1/transform-childs.typ
  packages/preview/cjk-unbreak/0.1.1/typst.toml
Labels: update

#2516 nutshell:0.1.0
  packages/preview/nutshell/0.1.0/LICENSE
  packages/preview/nutshell/0.1.0/README.md
  packages/preview/nutshell/0.1.0/examples/gandalf.typ
  packages/preview/nutshell/0.1.0/examples/map-svgrepo-com.svg
  packages/preview/nutshell/0.1.0/examples/pipe-4-svgrepo-com.svg
  packages/preview/nutshell/0.1.0/examples/staff.svg
  packages/preview/nutshell/0.1.0/main-nup.png
  packages/preview/nutshell/0.1.0/nutshell.typ
  packages/preview/nutshell/0.1.0/template/main.typ
  packages/preview/nutshell/0.1.0/template/noun-hiking-7853559.svg
  packages/preview/nutshell/0.1.0/template/noun-kettle-7840362.svg
  packages/preview/nutshell/0.1.0/thumbnail.png
  packages/preview/nutshell/0.1.0/typst.toml
Labels: new

#2517 jaconf:0.3.0
  packages/preview/jaconf/0.3.0/LICENSE
  packages/preview/jaconf/0.3.0/README.md
  packages/preview/jaconf/0.3.0/lib.typ
  packages/preview/jaconf/0.3.0/rsj.csl
  packages/preview/jaconf/0.3.0/sice.csl
  packages/preview/jaconf/0.3.0/template/main.typ
  packages/preview/jaconf/0.3.0/template/refs.yml
  packages/preview/jaconf/0.3.0/thumbnail.png
  packages/preview/jaconf/0.3.0/typst.toml
Labels: update

#2521 clean-dhbw:0.3.1
  packages/preview/clean-dhbw/0.3.1/LICENSE
  packages/preview/clean-dhbw/0.3.1/README.md
  packages/preview/clean-dhbw/0.3.1/check-attributes.typ
  packages/preview/clean-dhbw/0.3.1/confidentiality-statement.typ
  packages/preview/clean-dhbw/0.3.1/declaration-of-authorship.typ
  packages/preview/clean-dhbw/0.3.1/dhbw.svg
  packages/preview/clean-dhbw/0.3.1/docs/assumptions.md
  packages/preview/clean-dhbw/0.3.1/docs/design-explained.md
  packages/preview/clean-dhbw/0.3.1/docs/im-begin-chapter.png
  packages/preview/clean-dhbw/0.3.1/docs/usability-issues.md
  packages/preview/clean-dhbw/0.3.1/lib.typ
  packages/preview/clean-dhbw/0.3.1/locale.typ
  packages/preview/clean-dhbw/0.3.1/shared-lib.typ
  packages/preview/clean-dhbw/0.3.1/template/assets/ts.svg
  packages/preview/clean-dhbw/0.3.1/template/glossary.typ
  packages/preview/clean-dhbw/0.3.1/template/main.typ
  packages/preview/clean-dhbw/0.3.1/template/sources.bib
  packages/preview/clean-dhbw/0.3.1/thumbnail.png
  packages/preview/clean-dhbw/0.3.1/titlepage.typ
  packages/preview/clean-dhbw/0.3.1/typst.toml
Labels: update

#2523 cetz:0.4.0
  packages/preview/cetz/0.4.0/LICENSE
  packages/preview/cetz/0.4.0/README.md
  packages/preview/cetz/0.4.0/cetz-core/cetz_core.wasm
  packages/preview/cetz/0.4.0/gallery/karls-picture.png
  packages/preview/cetz/0.4.0/gallery/karls-picture.typ
  packages/preview/cetz/0.4.0/gallery/paciolis.png
  packages/preview/cetz/0.4.0/gallery/paciolis.typ
  packages/preview/cetz/0.4.0/gallery/periodic-table.png
  packages/preview/cetz/0.4.0/gallery/periodic-table.typ
  packages/preview/cetz/0.4.0/gallery/plate-capacitor.png
  packages/preview/cetz/0.4.0/gallery/plate-capacitor.typ
  packages/preview/cetz/0.4.0/gallery/tree.png
  packages/preview/cetz/0.4.0/gallery/tree.typ
  packages/preview/cetz/0.4.0/gallery/waves.png
  packages/preview/cetz/0.4.0/gallery/waves.typ
  packages/preview/cetz/0.4.0/src/aabb.typ
  packages/preview/cetz/0.4.0/src/anchor.typ
  packages/preview/cetz/0.4.0/src/bezier.typ
  packages/preview/cetz/0.4.0/src/canvas.typ
  packages/preview/cetz/0.4.0/src/complex.typ
  packages/preview/cetz/0.4.0/src/coordinate.typ
  packages/preview/cetz/0.4.0/src/deps.typ
  packages/preview/cetz/0.4.0/src/draw.typ
  packages/preview/cetz/0.4.0/src/draw/grouping.typ
  packages/preview/cetz/0.4.0/src/draw/projection.typ
  packages/preview/cetz/0.4.0/src/draw/shapes.typ
  packages/preview/cetz/0.4.0/src/draw/styling.typ
  packages/preview/cetz/0.4.0/src/draw/transformations.typ
  packages/preview/cetz/0.4.0/src/draw/util.typ
  packages/preview/cetz/0.4.0/src/drawable.typ
  packages/preview/cetz/0.4.0/src/hobby.typ
  packages/preview/cetz/0.4.0/src/intersection.typ
  packages/preview/cetz/0.4.0/src/lib.typ
  packages/preview/cetz/0.4.0/src/lib/angle.typ
  packages/preview/cetz/0.4.0/src/lib/decorations.typ
  packages/preview/cetz/0.4.0/src/lib/decorations/brace.typ
  packages/preview/cetz/0.4.0/src/lib/decorations/path.typ
  packages/preview/cetz/0.4.0/src/lib/palette.typ
  packages/preview/cetz/0.4.0/src/lib/pin.typ
  packages/preview/cetz/0.4.0/src/lib/tree.typ
  packages/preview/cetz/0.4.0/src/mark-shapes.typ
  packages/preview/cetz/0.4.0/src/mark.typ
  packages/preview/cetz/0.4.0/src/matrix.typ
  packages/preview/cetz/0.4.0/src/path-util.typ
  packages/preview/cetz/0.4.0/src/polygon.typ
  packages/preview/cetz/0.4.0/src/process.typ
  packages/preview/cetz/0.4.0/src/sorting.typ
  packages/preview/cetz/0.4.0/src/styles.typ
  packages/preview/cetz/0.4.0/src/util.typ
  packages/preview/cetz/0.4.0/src/vector.typ
  packages/preview/cetz/0.4.0/src/version.typ
  packages/preview/cetz/0.4.0/src/wasm.typ
  packages/preview/cetz/0.4.0/typst.toml
Labels: update

#2529 niram-css:0.1.0
  packages/preview/niram-css/0.1.0/CHANGELOG.md
  packages/preview/niram-css/0.1.0/LICENSE
  packages/preview/niram-css/0.1.0/README.md
  packages/preview/niram-css/0.1.0/docs/manual.pdf
  packages/preview/niram-css/0.1.0/src/niram-css.typ
  packages/preview/niram-css/0.1.0/thumbnail-2-dark.svg
  packages/preview/niram-css/0.1.0/thumbnail-2-light.svg
  packages/preview/niram-css/0.1.0/thumbnail-dark.svg
  packages/preview/niram-css/0.1.0/thumbnail-light.svg
  packages/preview/niram-css/0.1.0/typst.toml
Labels: new

#2526 accelerated-jacow:0.1.4
  packages/preview/accelerated-jacow/0.1.4/LICENSE
  packages/preview/accelerated-jacow/0.1.4/README.md
  packages/preview/accelerated-jacow/0.1.4/jacow.csl
  packages/preview/accelerated-jacow/0.1.4/jacow.typ
  packages/preview/accelerated-jacow/0.1.4/template/paper.typ
  packages/preview/accelerated-jacow/0.1.4/template/references.bib
  packages/preview/accelerated-jacow/0.1.4/template/writer.svg
  packages/preview/accelerated-jacow/0.1.4/thumbnail.webp
  packages/preview/accelerated-jacow/0.1.4/typst.toml
Labels: update

#2535 marginalia:0.2.0
  packages/preview/marginalia/0.2.0/README.md
  packages/preview/marginalia/0.2.0/UNLICENSE
  packages/preview/marginalia/0.2.0/lib.typ
  packages/preview/marginalia/0.2.0/typst.toml
Labels: update

#2531 cetz-venn:0.1.4
  packages/preview/cetz-venn/0.1.4/LICENSE
  packages/preview/cetz-venn/0.1.4/README.md
  packages/preview/cetz-venn/0.1.4/gallery/venn2.png
  packages/preview/cetz-venn/0.1.4/gallery/venn2.typ
  packages/preview/cetz-venn/0.1.4/gallery/venn3.png
  packages/preview/cetz-venn/0.1.4/gallery/venn3.typ
  packages/preview/cetz-venn/0.1.4/manual.pdf
  packages/preview/cetz-venn/0.1.4/manual.typ
  packages/preview/cetz-venn/0.1.4/src/lib.typ
  packages/preview/cetz-venn/0.1.4/src/venn.typ
  packages/preview/cetz-venn/0.1.4/typst.toml
Labels: update

#2538 hei-synd-thesis:0.2.0
  packages/preview/hei-synd-thesis/0.2.0/CHANGELOG.md
  packages/preview/hei-synd-thesis/0.2.0/LICENSE
  packages/preview/hei-synd-thesis/0.2.0/README.md
  packages/preview/hei-synd-thesis/0.2.0/cliff.toml
  packages/preview/hei-synd-thesis/0.2.0/lib/boxes.typ
  packages/preview/hei-synd-thesis/0.2.0/lib/constants.typ
  packages/preview/hei-synd-thesis/0.2.0/lib/helpers.typ
  packages/preview/hei-synd-thesis/0.2.0/lib/i18n-thesis.json
  packages/preview/hei-synd-thesis/0.2.0/lib/img/check-badge.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/check-circle.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/check-square.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/check.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/circle.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/file.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/fire.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/folder.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/idea.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/important.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/info.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/rocket.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/square.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/todo.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/warning.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/x-circle.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/x-square.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/img/x.svg
  packages/preview/hei-synd-thesis/0.2.0/lib/items.typ
  packages/preview/hei-synd-thesis/0.2.0/lib/pages-thesis.typ
  packages/preview/hei-synd-thesis/0.2.0/lib/syntax/VHDL.sublime-syntax
  packages/preview/hei-synd-thesis/0.2.0/lib/syntax/riscv.sublime-syntax
  packages/preview/hei-synd-thesis/0.2.0/lib/template-thesis.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/00-acknowledgements.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/01-abstract.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/02-introduction.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/03-analysis.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/04-design.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/05-implementation.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/06-validation.typ
  packages/preview/hei-synd-thesis/0.2.0/template/main/07-conclusion.typ
  packages/preview/hei-synd-thesis/0.2.0/template/metadata.typ
  packages/preview/hei-synd-thesis/0.2.0/template/resources/code/rustfmt.toml
  packages/preview/hei-synd-thesis/0.2.0/template/resources/code/uss-rustacean.rs
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/icon.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/logos/hei-defr.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/logos/hei-en.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/logos/hesso-logo.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/logos/hevs-pictogram.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/logos/swiss_universities-valais-excellence-logo.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/logos/synd.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/placeholder.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/project-logo.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/signature.svg
  packages/preview/hei-synd-thesis/0.2.0/template/resources/img/specifications.svg
  packages/preview/hei-synd-thesis/0.2.0/template/tail/a-appendix.typ
  packages/preview/hei-synd-thesis/0.2.0/template/tail/bibliography.bib
  packages/preview/hei-synd-thesis/0.2.0/template/tail/bibliography.typ
  packages/preview/hei-synd-thesis/0.2.0/template/tail/glossary.typ
  packages/preview/hei-synd-thesis/0.2.0/template/thesis.typ
  packages/preview/hei-synd-thesis/0.2.0/thumbnail.png
  packages/preview/hei-synd-thesis/0.2.0/typst.toml
Labels: update

#2542 touying-unistra-pristine:1.4.1
  packages/preview/touying-unistra-pristine/1.4.1/CHANGELOG.md
  packages/preview/touying-unistra-pristine/1.4.1/LICENSE
  packages/preview/touying-unistra-pristine/1.4.1/README.md
  packages/preview/touying-unistra-pristine/1.4.1/assets/thumbnail.webp
  packages/preview/touying-unistra-pristine/1.4.1/assets/unistra.svg
  packages/preview/touying-unistra-pristine/1.4.1/assets/unistrafooter.svg
  packages/preview/touying-unistra-pristine/1.4.1/src/citations.typ
  packages/preview/touying-unistra-pristine/1.4.1/src/colors.typ
  packages/preview/touying-unistra-pristine/1.4.1/src/icons.typ
  packages/preview/touying-unistra-pristine/1.4.1/src/lib.typ
  packages/preview/touying-unistra-pristine/1.4.1/src/unistra.typ
  packages/preview/touying-unistra-pristine/1.4.1/src/utils.typ
  packages/preview/touying-unistra-pristine/1.4.1/template/template.typ
  packages/preview/touying-unistra-pristine/1.4.1/template/unistra.svg
  packages/preview/touying-unistra-pristine/1.4.1/template/unistrafooter.svg
  packages/preview/touying-unistra-pristine/1.4.1/typst.toml
Labels: update

#2541 plotsy-3d:0.2.0
  packages/preview/plotsy-3d/0.2.0/LICENSE
  packages/preview/plotsy-3d/0.2.0/README.md
  packages/preview/plotsy-3d/0.2.0/examples/examples.pdf
  packages/preview/plotsy-3d/0.2.0/examples/examples.typ
  packages/preview/plotsy-3d/0.2.0/examples/examples1.png
  packages/preview/plotsy-3d/0.2.0/examples/examples10.png
  packages/preview/plotsy-3d/0.2.0/examples/examples2.png
  packages/preview/plotsy-3d/0.2.0/examples/examples3.png
  packages/preview/plotsy-3d/0.2.0/examples/examples4.png
  packages/preview/plotsy-3d/0.2.0/examples/examples5.png
  packages/preview/plotsy-3d/0.2.0/examples/examples6.png
  packages/preview/plotsy-3d/0.2.0/examples/examples7.png
  packages/preview/plotsy-3d/0.2.0/examples/examples8.png
  packages/preview/plotsy-3d/0.2.0/examples/examples9.png
  packages/preview/plotsy-3d/0.2.0/plotsy-3d.typ
  packages/preview/plotsy-3d/0.2.0/typst.toml
Labels: update

#2540 simple-unimi-thesis:0.1.0
  packages/preview/simple-unimi-thesis/0.1.0/.gitignore
  packages/preview/simple-unimi-thesis/0.1.0/CONTRIBUTING.md
  packages/preview/simple-unimi-thesis/0.1.0/LICENSE
  packages/preview/simple-unimi-thesis/0.1.0/README.md
  packages/preview/simple-unimi-thesis/0.1.0/docs/bibliografia.bib
  packages/preview/simple-unimi-thesis/0.1.0/docs/instructions.pdf
  packages/preview/simple-unimi-thesis/0.1.0/docs/instructions.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/1_introduzione.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/2_stato_dellarte.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/3_tecnologie.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/4_nome.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/5_test.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/6_conclusioni.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/A1_tirocinio.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/A2_documenti.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/dedica.typ
  packages/preview/simple-unimi-thesis/0.1.0/docs/sections/ringraziamenti.typ
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/adapt.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/aislab.jpg
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/anacleto.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/bisp.pdf
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/bisp.svg
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/connets.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/everyware.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/false.pdf
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/false.svg
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/iebil.pdf
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/iebil.svg
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/islab.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/laila.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/laser.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/law.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/lim.pdf
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/lim.svg
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/mips.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/opt.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/phuse.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/pong.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/sesar.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/spdp.png
  packages/preview/simple-unimi-thesis/0.1.0/src/img/loghi/unimi.pdf
  packages/preview/simple-unimi-thesis/0.1.0/src/img/unimi.pdf
  packages/preview/simple-unimi-thesis/0.1.0/src/img/unimi.svg
  packages/preview/simple-unimi-thesis/0.1.0/src/lib.typ
  packages/preview/simple-unimi-thesis/0.1.0/src/utils/laboratories.yaml
  packages/preview/simple-unimi-thesis/0.1.0/src/utils/locale.yaml
  packages/preview/simple-unimi-thesis/0.1.0/symlink.sh
  packages/preview/simple-unimi-thesis/0.1.0/template/main.typ
  packages/preview/simple-unimi-thesis/0.1.0/template/myoverride.yml
  packages/preview/simple-unimi-thesis/0.1.0/thumbnail.png
  packages/preview/simple-unimi-thesis/0.1.0/typst.toml
Labels: new

#2546 tntt:0.3.1
  packages/preview/tntt/0.3.1/LICENSE
  packages/preview/tntt/0.3.1/README.md
  packages/preview/tntt/0.3.1/src/assets/logo.png
  packages/preview/tntt/0.3.1/src/imports.typ
  packages/preview/tntt/0.3.1/src/layouts/back-matter.typ
  packages/preview/tntt/0.3.1/src/layouts/doc.typ
  packages/preview/tntt/0.3.1/src/layouts/front-matter.typ
  packages/preview/tntt/0.3.1/src/layouts/main-matter.typ
  packages/preview/tntt/0.3.1/src/lib.typ
  packages/preview/tntt/0.3.1/src/pages/abstract.typ
  packages/preview/tntt/0.3.1/src/pages/achievement.typ
  packages/preview/tntt/0.3.1/src/pages/acknowledge.typ
  packages/preview/tntt/0.3.1/src/pages/copyright.typ
  packages/preview/tntt/0.3.1/src/pages/cover.typ
  packages/preview/tntt/0.3.1/src/pages/declaration.typ
  packages/preview/tntt/0.3.1/src/pages/equation-list.typ
  packages/preview/tntt/0.3.1/src/pages/figure-list.typ
  packages/preview/tntt/0.3.1/src/pages/fonts-display.typ
  packages/preview/tntt/0.3.1/src/pages/notation.typ
  packages/preview/tntt/0.3.1/src/pages/outline-wrapper.typ
  packages/preview/tntt/0.3.1/src/pages/table-list.typ
  packages/preview/tntt/0.3.1/src/utils/bibliography.typ
  packages/preview/tntt/0.3.1/src/utils/font.typ
  packages/preview/tntt/0.3.1/src/utils/numbering.typ
  packages/preview/tntt/0.3.1/src/utils/text.typ
  packages/preview/tntt/0.3.1/src/utils/util.typ
  packages/preview/tntt/0.3.1/template/media/logo.jpg
  packages/preview/tntt/0.3.1/template/ref.bib
  packages/preview/tntt/0.3.1/template/thesis.typ
  packages/preview/tntt/0.3.1/thumbnail.png
  packages/preview/tntt/0.3.1/typst.toml
Labels: update

#2530 dovenv:0.1.0
  packages/preview/dovenv/0.1.0/README.md
  packages/preview/dovenv/0.1.0/examples/.env
  packages/preview/dovenv/0.1.0/examples/.env.local
  packages/preview/dovenv/0.1.0/internal.typ
  packages/preview/dovenv/0.1.0/lib.typ
  packages/preview/dovenv/0.1.0/typst.toml
Labels: new

#2545 songting-book:0.0.1
  packages/preview/songting-book/0.0.1/LICENSE
  packages/preview/songting-book/0.0.1/README.md
  packages/preview/songting-book/0.0.1/lib.typ
  packages/preview/songting-book/0.0.1/typst.toml
Labels: new

#2511 typhorm:0.1.0
  packages/preview/typhorm/0.1.0/LICENSE
  packages/preview/typhorm/0.1.0/README.md
  packages/preview/typhorm/0.1.0/src/config/info.toml
  packages/preview/typhorm/0.1.0/src/config/names.toml
  packages/preview/typhorm/0.1.0/src/config/styles.toml
  packages/preview/typhorm/0.1.0/src/deps.typ
  packages/preview/typhorm/0.1.0/src/lib.typ
  packages/preview/typhorm/0.1.0/src/utils.typ
  packages/preview/typhorm/0.1.0/typst.toml
Labels: new

#2559 songting-book:0.0.2
  packages/preview/songting-book/0.0.2/LICENSE
  packages/preview/songting-book/0.0.2/README.md
  packages/preview/songting-book/0.0.2/lib.typ
  packages/preview/songting-book/0.0.2/typst.toml
Labels: update

#2544 statementsp:0.1.1
  packages/preview/statementsp/0.1.1/LICENSE
  packages/preview/statementsp/0.1.1/README.md
  packages/preview/statementsp/0.1.1/images/sampleimage.jpg
  packages/preview/statementsp/0.1.1/images/superdefinition.png
  packages/preview/statementsp/0.1.1/statementsp.typ
  packages/preview/statementsp/0.1.1/typst.toml
Labels: update

#2558 quill:0.7.1
  packages/preview/quill/0.7.1/LICENSE
  packages/preview/quill/0.7.1/README.md
  packages/preview/quill/0.7.1/src/arrow.typ
  packages/preview/quill/0.7.1/src/decorations.typ
  packages/preview/quill/0.7.1/src/draw-functions.typ
  packages/preview/quill/0.7.1/src/gates.typ
  packages/preview/quill/0.7.1/src/layout.typ
  packages/preview/quill/0.7.1/src/length-helpers.typ
  packages/preview/quill/0.7.1/src/process-args.typ
  packages/preview/quill/0.7.1/src/quantum-circuit.typ
  packages/preview/quill/0.7.1/src/quill.typ
  packages/preview/quill/0.7.1/src/tequila-impl.typ
  packages/preview/quill/0.7.1/src/tequila.typ
  packages/preview/quill/0.7.1/src/utility.typ
  packages/preview/quill/0.7.1/src/verifications.typ
  packages/preview/quill/0.7.1/typst.toml
Labels: update

#2560 nifty-ntnu-thesis:0.1.3
  packages/preview/nifty-ntnu-thesis/0.1.3/LICENSE
  packages/preview/nifty-ntnu-thesis/0.1.3/README.md
  packages/preview/nifty-ntnu-thesis/0.1.3/example.pdf
  packages/preview/nifty-ntnu-thesis/0.1.3/lib.typ
  packages/preview/nifty-ntnu-thesis/0.1.3/template/figures/kart_student.png
  packages/preview/nifty-ntnu-thesis/0.1.3/template/main.typ
  packages/preview/nifty-ntnu-thesis/0.1.3/template/thesis.bib
  packages/preview/nifty-ntnu-thesis/0.1.3/thumbnail.png
  packages/preview/nifty-ntnu-thesis/0.1.3/typst.toml
Labels: update

#2563 flyingcircus:3.3.0
  packages/preview/flyingcircus/3.3.0/CHANGELOG.md
  packages/preview/flyingcircus/3.3.0/LICENSE
  packages/preview/flyingcircus/3.3.0/README.md
  packages/preview/flyingcircus/3.3.0/src/FlyingCircus.typ
  packages/preview/flyingcircus/3.3.0/src/Impl.typ
  packages/preview/flyingcircus/3.3.0/src/images/Default.png
  packages/preview/flyingcircus/3.3.0/template/Basic Biplane_stats.json
  packages/preview/flyingcircus/3.3.0/template/Main.typ
  packages/preview/flyingcircus/3.3.0/template/Sample Vehicle_stats.json
  packages/preview/flyingcircus/3.3.0/template/images/Bergziegel_image.jpg
  packages/preview/flyingcircus/3.3.0/template/images/Cover.png
  packages/preview/flyingcircus/3.3.0/template/images/Macchi Frigate.png
  packages/preview/flyingcircus/3.3.0/template/images/Rifle.png
  packages/preview/flyingcircus/3.3.0/template/images/Wandelburg.jpg
  packages/preview/flyingcircus/3.3.0/thumbnail.png
  packages/preview/flyingcircus/3.3.0/typst.toml
Labels: update

#2564 basalt-lib:1.1.0
  packages/preview/basalt-lib/1.1.0/LICENSE
  packages/preview/basalt-lib/1.1.0/README.md
  packages/preview/basalt-lib/1.1.0/src/error-handling.typ
  packages/preview/basalt-lib/1.1.0/src/exports.typ
  packages/preview/basalt-lib/1.1.0/src/metadata-with-id.typ
  packages/preview/basalt-lib/1.1.0/src/note.typ
  packages/preview/basalt-lib/1.1.0/src/tag.typ
  packages/preview/basalt-lib/1.1.0/src/vault.typ
  packages/preview/basalt-lib/1.1.0/src/xlink.typ
  packages/preview/basalt-lib/1.1.0/typst.toml
Labels: update

#2543 uwnibook-color:0.2.0
  packages/preview/uwnibook-color/0.2.0/.gitignore
  packages/preview/uwnibook-color/0.2.0/.gitmodules
  packages/preview/uwnibook-color/0.2.0/LICENSE
  packages/preview/uwnibook-color/0.2.0/README.md
  packages/preview/uwnibook-color/0.2.0/boilerplate/chapters/1_intro.typ
  packages/preview/uwnibook-color/0.2.0/boilerplate/chapters/appendix.typ
  packages/preview/uwnibook-color/0.2.0/boilerplate/chapters/preamble.typ
  packages/preview/uwnibook-color/0.2.0/boilerplate/citation.bib
  packages/preview/uwnibook-color/0.2.0/boilerplate/header_imgs/img1.jpg
  packages/preview/uwnibook-color/0.2.0/boilerplate/header_imgs/imgs.typ
  packages/preview/uwnibook-color/0.2.0/boilerplate/main.typ
  packages/preview/uwnibook-color/0.2.0/boilerplate/uwnibook.typ
  packages/preview/uwnibook-color/0.2.0/lib.typ
  packages/preview/uwnibook-color/0.2.0/src/components.typ
  packages/preview/uwnibook-color/0.2.0/src/coverpage.typ
  packages/preview/uwnibook-color/0.2.0/src/environments.typ
  packages/preview/uwnibook-color/0.2.0/src/index.typ
  packages/preview/uwnibook-color/0.2.0/src/packages/marginalia.typ
  packages/preview/uwnibook-color/0.2.0/src/presets/config-en.typ
  packages/preview/uwnibook-color/0.2.0/src/presets/config-zh.typ
  packages/preview/uwnibook-color/0.2.0/src/template.typ
  packages/preview/uwnibook-color/0.2.0/src/titlepage.typ
  packages/preview/uwnibook-color/0.2.0/thumbnail.png
  packages/preview/uwnibook-color/0.2.0/typst.toml
Labels: update

#2566 griddle:0.2.0
  packages/preview/griddle/0.2.0/LICENSE
  packages/preview/griddle/0.2.0/README.md
  packages/preview/griddle/0.2.0/docs/example1.png
  packages/preview/griddle/0.2.0/docs/example3.png
  packages/preview/griddle/0.2.0/docs/example_crossword16.png
  packages/preview/griddle/0.2.0/docs/example_init.png
  packages/preview/griddle/0.2.0/docs/example_mini.png
  packages/preview/griddle/0.2.0/docs/example_mini_fancy.png
  packages/preview/griddle/0.2.0/docs/example_sator.png
  packages/preview/griddle/0.2.0/examples/data_crossword16.yaml
  packages/preview/griddle/0.2.0/examples/data_init.yaml
  packages/preview/griddle/0.2.0/examples/data_mini.yaml
  packages/preview/griddle/0.2.0/examples/data_sator.yaml
  packages/preview/griddle/0.2.0/examples/example_crossword16.typ
  packages/preview/griddle/0.2.0/examples/example_init.typ
  packages/preview/griddle/0.2.0/examples/example_mini.typ
  packages/preview/griddle/0.2.0/examples/example_sator.typ
  packages/preview/griddle/0.2.0/src/definitions.typ
  packages/preview/griddle/0.2.0/src/lib.typ
  packages/preview/griddle/0.2.0/src/loader.typ
  packages/preview/griddle/0.2.0/src/schema.typ
  packages/preview/griddle/0.2.0/src/utils.typ
  packages/preview/griddle/0.2.0/typst.toml
Labels: update

#2539 rose-pine:0.2.1
  packages/preview/rose-pine/0.2.1/.editorconfig
  packages/preview/rose-pine/0.2.1/LICENSE
  packages/preview/rose-pine/0.2.1/README.md
  packages/preview/rose-pine/0.2.1/lib.typ
  packages/preview/rose-pine/0.2.1/src/apply.typ
  packages/preview/rose-pine/0.2.1/src/rose-pine-template.tmTheme
  packages/preview/rose-pine/0.2.1/src/template.typ
  packages/preview/rose-pine/0.2.1/src/themes/rose-pine-dawn.tmTheme
  packages/preview/rose-pine/0.2.1/src/themes/rose-pine-dawn.typ
  packages/preview/rose-pine/0.2.1/src/themes/rose-pine-moon.tmTheme
  packages/preview/rose-pine/0.2.1/src/themes/rose-pine-moon.typ
  packages/preview/rose-pine/0.2.1/src/themes/rose-pine.tmTheme
  packages/preview/rose-pine/0.2.1/src/themes/rose-pine.typ
  packages/preview/rose-pine/0.2.1/typst.toml
Labels: update

#2572 conjak:0.2.3
  packages/preview/conjak/0.2.3/LICENSE
  packages/preview/conjak/0.2.3/README.md
  packages/preview/conjak/0.2.3/src/conjak.wasm
  packages/preview/conjak/0.2.3/src/lib.typ
  packages/preview/conjak/0.2.3/typst.toml
Labels: new

#2578 jastylest-zh:0.1.1
  packages/preview/jastylest-zh/0.1.1/LICENSE
  packages/preview/jastylest-zh/0.1.1/README-zh.md
  packages/preview/jastylest-zh/0.1.1/README.md
  packages/preview/jastylest-zh/0.1.1/jastylest-zh.typ
  packages/preview/jastylest-zh/0.1.1/template/document.typ
  packages/preview/jastylest-zh/0.1.1/thumbnail.png
  packages/preview/jastylest-zh/0.1.1/typst.toml
Labels: update

#2580 neat-cv:0.2.0
  packages/preview/neat-cv/0.2.0/LICENSE
  packages/preview/neat-cv/0.2.0/README.md
  packages/preview/neat-cv/0.2.0/assets/cv_p1.png
  packages/preview/neat-cv/0.2.0/assets/cv_p2.png
  packages/preview/neat-cv/0.2.0/justfile
  packages/preview/neat-cv/0.2.0/lib.typ
  packages/preview/neat-cv/0.2.0/manifest.yml
  packages/preview/neat-cv/0.2.0/template/cv.typ
  packages/preview/neat-cv/0.2.0/template/profile.png
  packages/preview/neat-cv/0.2.0/template/publications.yml
  packages/preview/neat-cv/0.2.0/typst.toml
Labels: update

#2586 clean-math-paper:0.2.2
  packages/preview/clean-math-paper/0.2.2/.gitignore
  packages/preview/clean-math-paper/0.2.2/LICENSE
  packages/preview/clean-math-paper/0.2.2/README.md
  packages/preview/clean-math-paper/0.2.2/lib.typ
  packages/preview/clean-math-paper/0.2.2/orcid.svg
  packages/preview/clean-math-paper/0.2.2/template/bibliography.bib
  packages/preview/clean-math-paper/0.2.2/template/main.typ
  packages/preview/clean-math-paper/0.2.2/thumbnail.png
  packages/preview/clean-math-paper/0.2.2/typst.toml
Labels: update

#2569 sdu-touying-simpl:1.0.0
  packages/preview/sdu-touying-simpl/1.0.0/LICENSE
  packages/preview/sdu-touying-simpl/1.0.0/README.md
  packages/preview/sdu-touying-simpl/1.0.0/dependency.typ
  packages/preview/sdu-touying-simpl/1.0.0/example/bibliography.bib
  packages/preview/sdu-touying-simpl/1.0.0/example/figures/fibonacci.png
  packages/preview/sdu-touying-simpl/1.0.0/example/figures/main.png
  packages/preview/sdu-touying-simpl/1.0.0/example/figures/meme.png
  packages/preview/sdu-touying-simpl/1.0.0/example/figures/poster.png
  packages/preview/sdu-touying-simpl/1.0.0/example/main.typ
  packages/preview/sdu-touying-simpl/1.0.0/img/brand-rust.svg
  packages/preview/sdu-touying-simpl/1.0.0/img/github-mark-white.svg
  packages/preview/sdu-touying-simpl/1.0.0/img/sdu-title.png
  packages/preview/sdu-touying-simpl/1.0.0/img/sdu.png
  packages/preview/sdu-touying-simpl/1.0.0/img/uob-bullet.svg
  packages/preview/sdu-touying-simpl/1.0.0/img/word.png
  packages/preview/sdu-touying-simpl/1.0.0/img/word.svg
  packages/preview/sdu-touying-simpl/1.0.0/lib.typ
  packages/preview/sdu-touying-simpl/1.0.0/src/call-out.typ
  packages/preview/sdu-touying-simpl/1.0.0/src/octique-decode.typ
  packages/preview/sdu-touying-simpl/1.0.0/src/octique.typ
  packages/preview/sdu-touying-simpl/1.0.0/typst.toml
Labels: update

#2590 jaconf:0.4.1
  packages/preview/jaconf/0.4.1/LICENSE
  packages/preview/jaconf/0.4.1/README.md
  packages/preview/jaconf/0.4.1/lib.typ
  packages/preview/jaconf/0.4.1/rsj.csl
  packages/preview/jaconf/0.4.1/sice.csl
  packages/preview/jaconf/0.4.1/template/main.typ
  packages/preview/jaconf/0.4.1/template/refs.yml
  packages/preview/jaconf/0.4.1/thumbnail.png
  packages/preview/jaconf/0.4.1/typst.toml
Labels: update

#2591 jabiz:0.1.1
  packages/preview/jabiz/0.1.1/LICENSE
  packages/preview/jabiz/0.1.1/README.md
  packages/preview/jabiz/0.1.1/lib.typ
  packages/preview/jabiz/0.1.1/template/main.typ
  packages/preview/jabiz/0.1.1/thumbnail.png
  packages/preview/jabiz/0.1.1/typst.toml
Labels: update

#2592 pointless-size:0.1.1 Update docs
  packages/preview/pointless-size/0.1.1/README.md
Labels: update

#2598 neat-cv:0.2.1
  packages/preview/neat-cv/0.2.1/LICENSE
  packages/preview/neat-cv/0.2.1/README.md
  packages/preview/neat-cv/0.2.1/assets/cv_p1.png
  packages/preview/neat-cv/0.2.1/assets/cv_p2.png
  packages/preview/neat-cv/0.2.1/lib.typ
  packages/preview/neat-cv/0.2.1/manifest.yml
  packages/preview/neat-cv/0.2.1/template/cv.typ
  packages/preview/neat-cv/0.2.1/template/profile.png
  packages/preview/neat-cv/0.2.1/template/publications.yml
  packages/preview/neat-cv/0.2.1/typst.toml
Labels: update

#2602 marginalia:0.2.3
  packages/preview/marginalia/0.2.3/README.md
  packages/preview/marginalia/0.2.3/UNLICENSE
  packages/preview/marginalia/0.2.3/lib.typ
  packages/preview/marginalia/0.2.3/typst.toml
Labels: update

#2608 latex-lookalike:0.1.1
  packages/preview/latex-lookalike/0.1.1/LICENSE
  packages/preview/latex-lookalike/0.1.1/README.md
  packages/preview/latex-lookalike/0.1.1/example/example.typ
  packages/preview/latex-lookalike/0.1.1/inc/outline_after.png
  packages/preview/latex-lookalike/0.1.1/inc/outline_before.png
  packages/preview/latex-lookalike/0.1.1/src/lib.typ
  packages/preview/latex-lookalike/0.1.1/typst.toml
Labels: update

#2600 songting-book:0.0.3
  packages/preview/songting-book/0.0.3/LICENSE
  packages/preview/songting-book/0.0.3/README.md
  packages/preview/songting-book/0.0.3/lib.typ
  packages/preview/songting-book/0.0.3/typst.toml
Labels: update

#2610 lacy-ubc-math-project:0.2.0
  packages/preview/lacy-ubc-math-project/0.2.0/LICENSE
  packages/preview/lacy-ubc-math-project/0.2.0/Makefile
  packages/preview/lacy-ubc-math-project/0.2.0/README.md
  packages/preview/lacy-ubc-math-project/0.2.0/manual.pdf
  packages/preview/lacy-ubc-math-project/0.2.0/manual.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/components.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/defaults.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/drawing.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/internal.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/lib.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/markscheme.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/spec.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/theme.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/themes/ubc.typ
  packages/preview/lacy-ubc-math-project/0.2.0/src/util.typ
  packages/preview/lacy-ubc-math-project/0.2.0/template/assets/madeline-math.jpg
  packages/preview/lacy-ubc-math-project/0.2.0/template/config.typ
  packages/preview/lacy-ubc-math-project/0.2.0/template/project-1.typ
  packages/preview/lacy-ubc-math-project/0.2.0/test/config.typ
  packages/preview/lacy-ubc-math-project/0.2.0/test/math100-p3.typ
  packages/preview/lacy-ubc-math-project/0.2.0/test/noun-submarine-7265824.png
  packages/preview/lacy-ubc-math-project/0.2.0/thumbnail.png
  packages/preview/lacy-ubc-math-project/0.2.0/typst.toml
Labels: update

#2621 efilrst:0.3.2
  packages/preview/efilrst/0.3.2/.gitignore
  packages/preview/efilrst/0.3.2/LICENSE
  packages/preview/efilrst/0.3.2/README.md
  packages/preview/efilrst/0.3.2/img/image.png
  packages/preview/efilrst/0.3.2/src/lib.typ
  packages/preview/efilrst/0.3.2/typst.toml
Labels: update
